### ISSUE TITLE
make python 3.5.2 supported if that is their only python version 2.7.x will be End-of-life in 2020.

### ISSUE THREAD

**Issue by AraHaan** [nodejs/node-gyp#1001]
I personally think it is a shame having it not support python 3.5.2+ luckily i have however VS2015 Community and python 2.7.11. But it does not include asyncio (which adds in coroutines and deamon threads and thread safe stuff). However some threads can crash anyway.

**Comment by bnoordhuis** [comment]
Please see any of the (many) other issues about python 2 vs 3 - as long as GYP needs python 2, node-gyp needs python 2.  Closing.
