### ISSUE TITLE
failed to run node-gyp rebuild

### ISSUE THREAD

**Issue by arielnetanya** [nodejs/node-gyp#1003]
hi! i tried to run npm-gyp rebuild  and i got this:
`C:\devl\work\typings-master>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.3.1 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\efrat netanya\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\devl\\work\\typings-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\efrat netanya\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\efrat netanya\\.node-gyp\\6.3.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\efrat netanya\\.node-gyp\\6.3.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\efrat netanya\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\devl\\work\\typings-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\devl\\work\\typings-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\devl\work\typings-master) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error:`gyp`failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\efrat netanya\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\efrat netanya\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\devl\work\typings-master
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

i'm understand that i need to add a binding.gyp file. but i dont know how to write it.

in addition i tried to using wsdl2.js library, and whem i'm install it, it also doing `node gyp-rebuild` and also fail.

Thanks all

**Comment by bnoordhuis** [comment]
Have you read through https://nodejs.org/dist/latest-v4.x/docs/api/addons.html and https://github.com/nodejs/node-addon-examples?
