### ISSUE TITLE
node-gyp uses some current process information even when a target version is supplied

### ISSUE THREAD

**Issue by murgatroid99** [nodejs/node-gyp#1004]
When running `node-gyp configure`, the config.gypi file is [generated from `process.configure`](https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L101). This is done even if a `--target=<version>` argument is passed, which is incorrect.

For example, the [Linking to OpenSSL](https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL) guide says that the `node_shared_openssl` variable indicates whether to compile against Node's OpenSSL headers. In addition, the `node_module_version` variable contains the Node ABI version. Clearly, both of those (and the rest of the configuration) should depend on their value for the target version.

**Comment by jpambrun** [comment]
Is there a workaround for that? node_shared_openssl, node_shared_zlib, node_module_version, etc are all wrong.

**Comment by rvagg** [comment]
closing due to staleness, but it'd be great to get a pull request to address any outstanding issues here, happy to discuss further around code

**Comment by murgatroid99** [comment]
I just encountered a different problem that I believe is caused by this same bug. When I try to build for Node 14 using Node 12, I see this error: "gyp: name 'v8_enable_pointer_compression' is not defined while evaluating condition 'v8_enable_pointer_compression == 1' in binding.gyp while trying to load binding.gyp"

That condition does not appear anywhere in my own binding.gyp, so I assume that it comes from `common.gypi` or something. `v8_enable_pointer_compression` is defined in `process.config.variables` in Node 14, but not in Node 12.

If I am interpreting this right, that means that as a result of this bug, no binary for Node 14 or later can be built on Node 12 or earlier.

**Comment by richardlau** [comment]
@murgatroid99 thanks for reporting. This is an oversight of https://github.com/nodejs/node/pull/30463. I've raised https://github.com/nodejs/node/pull/33688 to fix.
