### ISSUE TITLE
Windows: old version of node-gyp prevents updated version from running

### ISSUE THREAD

**Issue by eahutchins** [nodejs/node-gyp#1005]
On Windows 8.1 it looks like `npm install -g node-gyp` puts node-gyp under `AppData\Roaming\npm\node-gyp.cmd`, but this command somehow launches a stale version under `c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js`.

I've tried uninstalling and reinstalling, what's the right magic to clean this up? Moving `c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp` out of the way doesn't work. I'm running a legacy node 0.10.34 and npm 1.4.28.

**Comment by joaocgreis** [comment]
`npm install -g node-gyp` will install an updated node-gyp that can be run from the command line with `node-gyp`, but npm will still use its own bundled version of node-gyp - that is intended behavior.

The way to update the node-gyp used by npm is to update npm, but I believe your version still has a bug that prevents that. Can you install the latest v0.10 from https://nodejs.org/dist/latest-v0.10.x/ ? That includes npm v2 with a fix for that bug, so then you can `npm install -g npm@lts` and that will give you the latest version of npm (and with the latest bundled node-gyp) for v0.10.

**Comment by eahutchins** [comment]
Thanks 0.10.46 worked!
