### ISSUE TITLE
gyp is raising an error due to duplicate basenames

### ISSUE THREAD

**Issue by chris-t-reilly** [nodejs/node-gyp#1008]
When trying to build my project, the following error is stopping the build:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/chris/npm/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chris/git/node-aac/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chris/npm/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chris/.node-gyp/6.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/chris/.node-gyp/6.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/chris/npm/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/chris/git/node-aac',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
static library deps/fdk-aac/fdk-aac.gyp:libfdk-aac#target has several files with the same basename:
  sbr_rom: libSBRdec/src/sbr_rom.cpp libSBRenc/src/sbr_rom.cpp
  sbr_ram: libSBRdec/src/sbr_ram.cpp libSBRenc/src/sbr_ram.cpp
libtool on Mac cannot handle that. Use --no-duplicate-basename-check to disable this validation.
gyp: Duplicate basenames in sources section, see list above
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

I don't know why gyp is raising the error, because running the build with the `--no-duplicate-basename-check` will insert the following into the config.gypi:
`"duplicate_basename_check": "false"`.

**Comment by bnoordhuis** [comment]
Well, it says why: libtool doesn't like it.

It's not just OS X.  msbuild on Windows doesn't always handle duplicate basenames well, either.

**Comment by piranna** [comment]
Seems this error was removed on latests versions of `gyp` after deprecation of VisualStudio 2008, an update of `gyp` would fix it. Is there any upcoming version for that?

**Comment by piranna** [comment]
I have reviewed the code and in fact [it would just be to pass the argument](https://github.com/nodejs/node-gyp/blob/f6eab1f9e4b160b60b2736bb01a09c83785ba979/gyp/pylib/gyp/__init__.py#L328-L337). Probably it would be checked and called inconditionally for Linux, so there's no problems there... I could be able to do a pull-request for that.

**Comment by bnoordhuis** [comment]
I'm going to close this because the duplicate basename check still exists in gyp master and I don't expect that to change.
