### ISSUE TITLE
-bash: node-gyp: command not found

### ISSUE THREAD

**Issue by mroftalp** [nodejs/node-gyp#1009]
I'm using mac and I installed it like this `npm install -g node-gyp`
it returned this:
```
├── rimraf@2.5.4
├── graceful-fs@4.1.6
├── semver@5.3.0
├── fstream@1.0.10
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── glob@7.0.5 (inflight@1.0.5, path-is-absolute@1.0.0, fs.realpath@1.0.0)
├── nopt@3.0.6 (abbrev@1.0.9)
├── which@1.2.10 (isexe@1.1.2)
├── tar@2.2.1 (block-stream@0.0.9)
├── minimatch@3.0.3 (brace-expansion@1.1.6)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── npmlog@3.1.2 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-there-yet@1.1.2, gauge@2.6.0)
├── request@2.74.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)
└── path-array@1.0.1 (array-index@1.0.0)
```
Seems like nothing is wrong with the installment. After that, I type `node-gyp`, the command is not found. Is there anything I did wrong? I also have python and Command Line Tools from xcode in my mac.

**Comment by bnoordhuis** [comment]
That's more of an npm question than it is a node-gyp question.  `npm install -g` puts the node-gyp script in a directory somewhere that needs to be on your PATH.

Having said that, in most cases you should use the node-gyp that is bundled with node.  That is installed in the same directory where node is installed.

**Comment by djaramilloj** [comment]
JFYI I just faced this issue and I resolved it by setting an alias of node-gyp which points to the path where modules were install in your machine (that path is shown in console right after the download from npm finished).
