### ISSUE TITLE
All node-gyp solutions are named "binding" - how to give a project specific name?

### ISSUE THREAD

**Issue by twoi** [nodejs/node-gyp#1012]
`node-gyp configure` will look for the file `binding.gyp` - and nothing else. This apparently implies that the (MS Visual Studio) solution name becomes "binding".

![binding](https://cloud.githubusercontent.com/assets/1841686/17952422/6016c36e-6aa5-11e6-8ae3-6b613f45546b.png)

I checked the node-gyp docs, sifted through many of the [binding.gyp files out in the wild](https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild), but it seems everyone is fine with that (or rather, I assume, not using Visual Studio).

So how can I set a project specific name?

**Comment by ayoubserti** [comment]
Hi @twoi,
I think  the problem cames from gyp processor. In fact, ``node-gyp`` module use look for ``binding.gyp`` file in current dir and then throw a bunch of argument to ``gyp`` child process to generate VS solution or what ever.

 ### node-gyp\lib\configure.js
```
  // enforce use of the "binding.gyp" file
      argv.unshift('binding.gyp')
```

``gyp`` generator always names solution using provided ``.gyp`` file.

Also i hope node-gyp implement a lookup mechanism to find ``.gyp`` file in current dir, So we can customize solution name.

personaly i gave up node-gyp, i'm using cmake-js instead which allows me to choose solution/projects names.
-Ayoub
