### ISSUE TITLE
node-gyp enforces gnu++0x language standard mode

### ISSUE THREAD

**Issue by target-san** [nodejs/node-gyp#1013]
Platform: Linux Mint 17.3 x64
Compiler: GCC 5.3

node-gyp, when generating Makefile, inserts "-std=gnu++0x" flag after user-provided flags. Thus, one is unable to build NodeJS addon using more recent compiler mode. In particular, one is unable to turn on C++14 mode.

**Comment by bnoordhuis** [comment]
It doesn't come from node-gyp, it's inherited from [common.gypi](https://github.com/nodejs/node/blob/v6.4.0/common.gypi#L244).  You can suppress it with `'cflags_cc!': ['-std=gnu++0x']` (note the exclamation mark.)

**Comment by target-san** [comment]
@bnoordhuis This is a solution. Although, node-gyp might change '-std' mode someday. That moment such a build would fail.

**Comment by bnoordhuis** [comment]
node, not node-gyp - remember, it's inherited from node's common.gypi.

**Comment by target-san** [comment]
@bnoordhuis Thanks for help. Considering this solved, if you don't mind.
