### ISSUE TITLE
There are plans to make node-gyp compatible with Python 3.5?

### ISSUE THREAD

**Issue by NervenCid** [nodejs/node-gyp#1016]
Hello:

I noticed when i tried to install some packages like serialport, node requires Python but only works with Python 2.7 version... why? I wonder of it is possible to me make node-gyp compatible with Python 3.5

Thank you

**Comment by bnoordhuis** [comment]
See the other issues that have been filed about the dependency of gyp on python 2.  The short version is that:

a) gyp is not under our direct control, and

b) making it 2+3 compatible is a lot of work that is not certain to get accepted upstream, and

c) binding.gyp files contain embedded python code so even if gyp / node-gyp was compatible with python 3, there is still a whole ecosystem that needs to upgrade too.
