### ISSUE TITLE
installing node-gyp

### ISSUE THREAD

**Issue by BrownHat** [nodejs/node-gyp#1017]
I'm using window10 , when i run `cd my_node_addon` , It said:"The system cannot find the path specified". I dont know why. Python was in `PATH`

**Comment by bnoordhuis** [comment]
You will have to provide more details if you want help.  What are you trying to accomplish?  Please post a step-by-step of what you have done so far.

**Comment by Z3R0c007** [comment]
I having the same issue. Where is my_node_addon? It seems so simple yet I cannot find it. Should we mkdir?

**Comment by chellong98** [comment]
what is the my_node_addon ??? @@
