### ISSUE TITLE
Use needle for http to remove requests large dependency tree

### ISSUE THREAD

**Issue by deployable** [nodejs/node-gyp#1018]
requests dependency tree has grown as it supports a whole lot of features on top of standard http. I don't believe any are required for a simple download. I've been moving over to [needle](https://github.com/tomas/needle) and thought it might be appropriate here too.

The event API's from each are a little different so it's not a straight swap. The front end api's are similar and support the same `ca` and `proxy` options. 

```
  var requestOpts = {
    headers: {
      'User-Agent': 'node-gyp v' + gyp.version + ' (node ' + process.version + ')'
    }
  }
  var req = require('needle').get(url,requestOpts)
  req.on('end', function (err, res, body) {
    if (!err && res) log.http(res.statusCode, url);
  })
```

request has a dependency tree just over 10MB now. Needle is ~ 776k and also loads significantly faster.

```
└─┬ needle@1.1.0 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  └── iconv-lite@0.4.13 
```

```
└─┬ request@2.74.0 
  ├── aws-sign2@0.6.0 
  ├── aws4@1.4.1 
  ├─┬ bl@1.1.2 
  │ └─┬ readable-stream@2.0.6 
  │   ├── core-util-is@1.0.2 
  │   ├── inherits@2.0.1 
  │   ├── isarray@1.0.0 
  │   ├── process-nextick-args@1.0.7 
  │   ├── string_decoder@0.10.31 
  │   └── util-deprecate@1.0.2 
  ├── caseless@0.11.0 
  ├─┬ combined-stream@1.0.5 
  │ └── delayed-stream@1.0.0 
  ├── extend@3.0.0 
  ├── forever-agent@0.6.1 
  ├─┬ form-data@1.0.1 
  │ └─┬ async@2.0.1 
  │   └── lodash@4.15.0 
  ├─┬ har-validator@2.0.6 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├─┬ commander@2.9.0 
  │ │ └── graceful-readlink@1.0.1 
  │ ├─┬ is-my-json-valid@2.13.1 
  │ │ ├── generate-function@2.0.0 
  │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ └── is-property@1.0.2 
  │ │ ├── jsonpointer@2.0.0 
  │ │ └── xtend@4.0.1 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├─┬ hawk@3.1.3 
  │ ├── boom@2.10.1 
  │ ├── cryptiles@2.0.5 
  │ ├── hoek@2.16.3 
  │ └── sntp@1.0.9 
  ├─┬ http-signature@1.1.1 
  │ ├── assert-plus@0.2.0 
  │ ├─┬ jsprim@1.3.0 
  │ │ ├── extsprintf@1.0.2 
  │ │ ├── json-schema@0.2.2 
  │ │ └── verror@1.3.6 
  │ └─┬ sshpk@1.10.0 
  │   ├── asn1@0.2.3 
  │   ├── assert-plus@1.0.0 
  │   ├─┬ bcrypt-pbkdf@1.0.0 
  │   │ └── tweetnacl@0.14.3 
  │   ├─┬ dashdash@1.14.0 
  │   │ └── assert-plus@1.0.0 
  │   ├── ecc-jsbn@0.1.1 
  │   ├─┬ getpass@0.1.6 
  │   │ └── assert-plus@1.0.0 
  │   ├── jodid25519@1.0.2 
  │   ├── jsbn@0.1.0 
  │   └── tweetnacl@0.13.3 
  ├── is-typedarray@1.0.0 
  ├── isstream@0.1.2 
  ├── json-stringify-safe@5.0.1 
  ├─┬ mime-types@2.1.11 
  │ └── mime-db@1.23.0 
  ├── node-uuid@1.4.7 
  ├── oauth-sign@0.8.2 
  ├── qs@6.2.1 
  ├── stringstream@0.0.5 
  ├── tough-cookie@2.3.1 
  └── tunnel-agent@0.4.3 
```

**Comment by bnoordhuis** [comment]
I don't think moving away from request is a bad idea per se but it probably won't have much impact as long as npm still depends on request.  Most people use the node-gyp that is bundled with npm and those share a copy of request.

**Comment by deployable** [comment]
Ah, of course. I'll raise the same for node-pre-gyp too. If it were successful in node-pre-gyp and node-gyp then it might be more likely to be used by npm-registry-client. Their use case is probably a bit broader though. 

In my first attempts I was more successful modifying node-gyps consumption of the events than creating a shim that made needle behave like request.  As it would need to cross multiple projects it still might be more worthwhile having a replacement that's largely api compatible? request-lite or some such.

**Comment by wtgtybhertgeghgtwtg** [comment]
Another small alternative is [`got`](https://github.com/sindresorhus/got), although that would require bumping the mimimum require `node` version to at least `node@4.0.0`.

**Comment by bnoordhuis** [comment]
I'll close this as there are no actionable items at the moment.  Can reopen if necessary.
