### ISSUE TITLE
Error in usage of std::unordered_map c++11

### ISSUE THREAD

**Issue by andbrain** [nodejs/node-gyp#1019]
I tried to use unordered_map from c++11, but I got errors related with : 
*** Error in `node': munmap_chunk(): invalid pointer

Bellow, an example of what I tried:

```
std::unordered_map<int,int> t;
std::cout << "Trying..." << std::endl;
t.insert(std::pair<int,int>(1,10));
std::cout << "Ok..." << std::endl;
```

I tried with std::map as well, but std::map works fine.

binding.gyp as bellow:

```
{
  "targets": [
    {
    	"target_name": "addon",
        "cflags": ["-std=c++11"],
    	"sources": [ 
    		"binder.cc"
    	]
    }
  ]
}
```

**Comment by andbrain** [comment]
I've tried as a simple program, with g++  (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2))
and it works.

But, when I'm trying to use insert method, I got that error of invalid pointer.

**Comment by bnoordhuis** [comment]
Closing, this is completely off-topic for the node-gyp bug tracker.
