### ISSUE TITLE
npm install Error failed to find python 

### ISSUE THREAD

**Issue by ganeshradj** [nodejs/node-gyp#1022]
I am getting error while installing npm packages and i have tried some online solutions. finnaly i am getting the error in the image attached.

Please refer the below screen for more info
https://cloud.githubusercontent.com/assets/10123941/18387393/0d72641c-76ba-11e6-81a5-b05436144f39.png

**Comment by bnoordhuis** [comment]
What exactly is unclear?  It's telling you that it can't find a python 2 executable.  If you have it installed, point the PYTHON environment variable to it or pass `--python <path>` on the command line.

**Comment by ganeshradj** [comment]
Yes i added a PYTHON variable to this "C:\Users\is4488\.windows-build-tools\python27\python.exe"
Still problem persist!!
Any Suggestions??

**Comment by bnoordhuis** [comment]
In the screenshot I don't see `\python.exe` in the printed path.

**Comment by ganeshradj** [comment]
Hi bnoordhuis,

After setting python variable below error comes .Refer below screenshot

https://cloud.githubusercontent.com/assets/10123941/18408164/1cf9e604-7745-11e6-8bfa-7343f9cb9348.png

**Comment by bnoordhuis** [comment]
Do you have more than one version of Visual Studio or the Windows SDK installed?  Try passing `--msvs_version=2015` on the command line.

**Comment by ganeshradj** [comment]
Hi bnoordhuis,

No I have only one version of visual studio 2012 professional.
I tried like `--msvs_version=2015` this also,But same error comes

**Comment by bnoordhuis** [comment]
> visual studio 2012 professional

You are targeting node.js v4 so you need VS 2013 at the very least.  Since you need to upgrade anyway, I'd skip 2013 and move to either VS 2015 or Visual C++ Build Tools.

Good luck.  If you still have issues afterwards, holler and I'll reopen the issue.

**Comment by ganeshradj** [comment]
Hi bnoordhuis,

I installed Visual C++ Build Tools 2015 and installed and below error comes.
Please refer screen shot
`https://cloud.githubusercontent.com/assets/10123941/18583931/4d8ecdb2-7c2b-11e6-9fc1-af0e509d8887.png`

**Comment by ganeshradj** [comment]
https://cloud.githubusercontent.com/assets/10123941/18583931/4d8ecdb2-7c2b-11e6-9fc1-af0e509d8887.png

**Comment by bnoordhuis** [comment]
I don't want to sound overly critical but it's rather obvious what is happening, isn't it?

Have you tried googling for 'C1060 error'?  The first hit is https://msdn.microsoft.com/en-us/library/yz7kx3y2.aspx - it explains the compiler is out of memory and what you can do to remedy it.
