### ISSUE TITLE
trying to install node-red but stuck at gyp verb extracted file from tarball include/node/v8.h

### ISSUE THREAD

**Issue by sumarouno** [nodejs/node-gyp#1025]
I do : 
`npm install node-red --verbose`

After 2 hour, installation progres is stuck at gyp verb extracted file from tarball include/node/v8.h

```
npm -v
2.15.9
node -v
v4.5.0

```

Thanks

**Comment by bnoordhuis** [comment]
Can you post the full output?

**Comment by sumarouno** [comment]
Here, the maximum line i can copy from the verbose output:
[](https://gist.github.com/sumarouno/f725a8b6ba5e8f5750e8c04222281b35)

Thank you @bnoordhuis

**Comment by bnoordhuis** [comment]
Can you `rm -rf $HOME/.node-gyp` and then post the output of `npm install --production heapdump`?  I picked heapdump because it's a standalone native module, no other dependencies.

**Comment by sumarouno** [comment]
@bnoordhuis Ok, here the output:
https://gist.github.com/sumarouno/f606a51b3711ca8d28ff9b6e2af9b0c9

Thanks

**Comment by bnoordhuis** [comment]
Good, we've established that building native modules works.  Can you try `rm -rf $HOME/.node-gyp` one more time (maybe nuke `$HOME/.npm` or wherever your npm cache is as well) and try to install node-red again?

**Comment by sumarouno** [comment]
Before I post this issue, I tried `npm cache clean` . Now, I will do your suggestion, and try again. I will give you a report. Thanks

**Comment by sumarouno** [comment]
@bnoordhuis , i'm back to give you a report. Now, the installation stuck at gyp verb extracted file from tarball include/node/openssl/pem.h
Thanks.
FYI my OS is Fedora 24

**Comment by sumarouno** [comment]
@bnoordhuis 
HI, my problem is solved.
I install node-gyp for all user: `sudo node install -g node-gyp`
And then install node-red for local user: `node install node-red`

I don't know why, and don't know the real problem, but IT WORK like a charm.
Thanks for helping me
