### ISSUE TITLE
Build node-gyp without XCode

### ISSUE THREAD

**Issue by ndtreviv** [nodejs/node-gyp#1026]
From the docs I'm told that I must have XCode installed in order to get gcc and make tools.
I have MacOSX with gcc and make installed separately via homebrew.

I'd much rather not install XCode as it messes with a bunch of other stuff and starts taking liberties that I don't like.

Will there ever be an option to install without needing XCode?

**Comment by bnoordhuis** [comment]
Not an officially supported one.  Certainly not in the near future, quite possibly never.
