### ISSUE TITLE
Seen so many times...

### ISSUE THREAD

**Issue by Steviey** [nodejs/node-gyp#1031]
Tell the author that this fails on your system:
829 error     if [ "$CI" = "true" ]; then node-gyp rebuild --debug; else node-gyp rebuild; fi;

**Comment by bnoordhuis** [comment]
node-gyp is a build tool, please report it to the project that you are trying to build (and do them a favor and include the full build output.)

**Comment by Steviey** [comment]
Node-gyp is such a build tool that it does not matter which Sqlite3-package I try to build.
It fails with every package using Windows and has crazy MS dependencies (VS13/Net-Framework 2 etc.). 
The internet is full of related stuff (Windows <->Sqlite3) but obviously nobody else gives a shit. 
I have never seen such a build disaster like with node-gyp on Windows. 
Unfortunately some important packages are tied to it.

**Comment by bnoordhuis** [comment]
Read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html if you want people to help you in the future.  Whining and bumping random issues is not how you do it.
