### ISSUE TITLE
change all places where #include <string.h> is

### ISSUE THREAD

**Issue by AraHaan** [nodejs/node-gyp#1033]
Well since C++ 11 you do not have to provide the ``.h`` part of string and on Windows ``<string.h>`` on some versions of the WinSDK is not there for that it is named ``<string>``. So, I recommend doing the same on if it is windows as the ``.h`` part is optional and is in some cases not present. (I know I am using C++ v14.0 and see no string.h but a ``string`` file that is the same contents of string.h.

**Comment by bnoordhuis** [comment]
Closing, outside node-gyp's remit.  It's a build tool, not a style checker.

Aside, `<string.h>` and `<string>` are not the same thing.  You may be thinking of `<cstring>`.
