### ISSUE TITLE
Can't use -fopenmp

### ISSUE THREAD

**Issue by kenOfYugen** [nodejs/node-gyp#1037]
First of all, thanks to all collaborators for your efforts.

I am trying to port the `binary-trees` C++ benchmark from the [benchmark game](http://benchmarksgame.alioth.debian.org/u64q/program.php?test=binarytrees&lang=gpp&id=7) to a native addon for node. The point is to make it as equal as possible to the original, in order to compare the performance overhead.

By itself it compiles and runs perfectly.
When compiling it for node, without the `-fopenmp` option, it builds fine and runs as expected.
When I try to enable the flag, it builds without errors but doesn't run. I get the error: `undefined symbol: GOMP_loop_dynamic_start`.

No matter what I have tried (specifying the specific boost library, the path where it is located and generally everything related in the issues and 'the internet') I always end up with the same error message.

When I try get the symbols exposed:
```
$ nm -g /usr/lib/libboost_system.so
nm: /usr/lib/libboost_system.so: no symbols
```
Which leads me to believe that perhaps the issue lies in the way `libboost_system.so` is compiled. On the other hand, it build and runs fine when not embedded in node.
 
So I would like to know, if it is a `node-gyp` - boost issue, otherwise I must be doing something in the wrong way. Perhaps it's an issue when using boost along the [`nbind`](https://github.com/charto/nbind) headers, in which case I'll have to report this elsewhere.

I'm including a sample `binding.gyp` file for reference, out of the many I've tried:
```
{
	"targets": [
		{
			"includes": [
				"auto.gypi"
			],
			"sources": [
				"binarytrees.cpp"
			],
			"cflags_cc": [
				"-pipe",
				"-O3",
				"-fomit-frame-pointer",
				"-march=native",
				"-std=c++14",
				"-fopenmp"
			],
			"link_settings":{
				"ldflags": [
					"-L/usr/lib -lboost_system"
				],
			}
		}
	],
	"includes": [
		"auto-top.gypi"
	]
}
```

**Comment by bnoordhuis** [comment]
I can't say for sure but the missing symbol seems to suggest you need to link to libgomp explicitly, i.e., that `-lgomp` should be appended to the ldflags.

**Comment by kenOfYugen** [comment]
@bnoordhuis you're the man!
I have no idea how the original compile flags just work without explicitly including the `-lgomp`.
Closing it since it obviously is not an actual issue. Thanks for the quick reply!

**Comment by kenOfYugen** [comment]
[Yeap, `gcc` always implies `-gomp` when using `-fopenmp`.](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=24845)
