### ISSUE TITLE
Cannot install: Angular dependency issue

### ISSUE THREAD

**Issue by vitaly-t** [nodejs/node-gyp#1039]
Can't install the tool at the moment at all, getting:

```
C:\Projects\Angular2-demo>npm install -g node-gyp
C:\Program Files\nodejs\node-gyp -> C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-gyp"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/compiler@2.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/compiler-cli@0.6.4 wants @angular/compiler@2.0.2
npm ERR! peerinvalid Peer @angular/platform-server@2.1.0 wants @angular/compiler@2.1.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Angular2-demo\npm-debug.log
```

Any idea what is wrong?

**Comment by bnoordhuis** [comment]
I don't know but I don't think it's a node-gyp issue.  You should get in touch with the angular project.

**Comment by vitaly-t** [comment]
I'm getting this error while running command `npm install -g node-gyp`. How is it not related?

**Comment by bnoordhuis** [comment]
The peerDependencies errors are about angular packages.  node-gyp doesn't use angular.  QED.

**Comment by cogsuvarna** [comment]
I'm getting this error while running command npm install.
npm WARN package.json angular2-demo@1.0.0 No description
npm WARN package.json angular2-demo@1.0.0 No repository field.
npm WARN package.json angular2-demo@1.0.0 No README data
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\266018\Desktop\angular2-demo\npm-debug.log

how to resolve this issue?

**Comment by bnoordhuis** [comment]
@cogsuvarna Please file a new issue, don't hijack an existing one.
