### ISSUE TITLE
I have issue instaling hombridge on windows 10 need help :(

### ISSUE THREAD

**Issue by INFINIX98** [nodejs/node-gyp#1044]
whe in try installing npm install -g hombridge 
he give me that : 

"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2059: syntax error: '.' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'error' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebri
dge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'open' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebrid
ge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2015: too many characters in constant (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\cur
ve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(1): error C2146: syntax error: missing ';' before identifier 'such' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebrid
ge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2059: syntax error: ':' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2146: syntax error: missing ';' before identifier 'Microsoft' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\hom
ebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(3): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2146: syntax error: missing ';' before identifier 'nodejs' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(5): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(5): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(6): error C2059: syntax error: 'constant' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519
-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(6): error C2059: syntax error: ')' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\buil
d\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2017: illegal escape sequence (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-
n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming
\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2086: 'int Programmes': redefinition (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curv
e25519-n\build\curve.vcxproj]
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(4): note: see declaration of 'Programmes' (compiling source file ..\node_curve.cc)
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): error C2146: syntax error: missing ';' before identifier 'nodejs' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(307): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.c
c) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(307): error C2143: syntax error: missing ',' before '*' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(313): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(314): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(315): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(316): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(317): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(318): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(319): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(320): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(321): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(322): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'u8': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'output': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_mod
ules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2065: 'input': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2275: 'felem': illegal use of this type as an expression (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\R
oaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
  d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(53): note: see declaration of 'felem' (compiling source file ..\node_curve.cc)
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2182: 'fcontract': illegal use of type 'void' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\
node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(330): error C2448: 'fcontract': function-style initializer appears to be a function definition (compiling source file ..\node_curve.cc
) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(445): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\node_curve.c
c) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(445): error C2143: syntax error: missing ',' before '*' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(453): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2146: syntax error: missing ';' before identifier 'byte' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\R
oaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(456): error C2065: 'n': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(458): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(463): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(469): error C2065: 'q': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\
homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(485): error C2065: 'byte': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2065: 'u8': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules
\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2065: 'mypublic': undeclared identifier (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_m
odules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2059: syntax error: 'const' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\node_modules\homeb
ridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2143: syntax error: missing ';' before '{' (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppData\Roaming\npm\nod
e_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
d:\users\fdp\appdata\roaming\npm\node_modules\homebridge\node_modules\curve25519-n\curve25519-donna.c(564): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\node_curve.cc) [D:\Users\FDP\AppDat
a\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
..\node_curve.cc(27): error C3861: 'curve25519_donna': identifier not found [D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `D:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\FDP\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
D:\Users\FDP\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\FDP\npm-debug.log
npm ERR! code 1"

can anyone help me ? i will realy apreciate because i searched with my friend google and i didnt find how to solve it i am a noob :(

**Comment by rvagg** [comment]
I'm not really sure there's much we can do about this. The project it's coming from is https://github.com/volschin/node-curve25519 and perhaps it doesn't support compiling on Windows.

Can someone in @nodejs/platform-windows run an `npm install curve25519-n` and report whether you get a successful build?

**Comment by INFINIX98** [comment]
its not worcking i have the same issue 
i am trying to install homebridge with this tutorial https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows

**Comment by seishun** [comment]
This looks like a homebridge issue and not a node-gyp issue. I suggest you submit an issue with homebridge instead.

**Comment by INFINIX98** [comment]
Are you sure because othe people are able to do it !:(

**Comment by bnoordhuis** [comment]
It might be an issue with your Visual Studio install but it's not a node-gyp issue.

**Comment by INFINIX98** [comment]
I have installed the visual studio community 2015 with tools and windows 10sdk
Windows 10sdk and windows 8sdk/windows phone sdk 
What I am suposed to do more than that ?

**Comment by rvagg** [comment]
That should be it @INFINIX98, do you happen to have any other visual studio versions installed on your system? You could try clearing everything else out. I'm still not convinced that this isn't just an issue with `curve25519-n` on Windows. It could even be a compatibility problem with Windows 10 || VS 2015, hence it working for others but not now.

**Comment by INFINIX98** [comment]
I only have this installation of visual studio should I remove it and installe an othe one if yes can you say to me which one ?

**Comment by joaocgreis** [comment]
@INFINIX98 `unistd.h` is not shipped with Visual Studio, and including it is a pretty good indication that Windows is not supported out of the box. I looked around and found this that may help you: https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows . If not, the correct place to ask for help might be https://github.com/nfarina/homebridge/issues .

**Comment by INFINIX98** [comment]
I tried to installation it on ubuntu but i have this problème now ! rty@localhost:~$ sudo homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[11/5/2016, 4:34:26 PM] Loaded plugin: homebridge-http
[11/5/2016, 4:34:27 PM] Registering accessory 'homebridge-http.Http'
[11/5/2016, 4:34:27 PM] ---
[11/5/2016, 4:34:27 PM] Loaded config.json with 1 accessories and 0 platforms.
[11/5/2016, 4:34:27 PM] ---
[11/5/2016, 4:34:27 PM] Loading 0 platforms...
[11/5/2016, 4:34:27 PM] Loading 1 accessories...
[11/5/2016, 4:34:27 PM] [Chambre] Initializing Http accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)

**Comment by bnoordhuis** [comment]
@INFINIX98 You should report that to homebridge or mdns, it doesn't have anything to do with node-gyp.
