### ISSUE TITLE
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".

### ISSUE THREAD

**Issue by eltonmkw** [nodejs/node-gyp#1045]
**MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".  To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua l Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\xampp\htdocs\node-printer\build\binding.sln]**

![aaa](https://cloud.githubusercontent.com/assets/3103419/19926601/6e58ba88-a130-11e6-86e0-44b4f8094002.PNG)

**Comment by dominikbulaj** [comment]
Hi!
How do you solve issue? What did you exactly install?

Thx,
DB

**Comment by eltonmkw** [comment]
Hi @dominikbulaj , I couldn't recalled how I fix it, but if I'm not mistaken as I remembered that to install every missing component via its component name.

`npm install <component-name> --save`

**Comment by chadillac81** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=15354

**Comment by eltonmkw** [comment]
Thank you @chadillac81 ! 👍 😄

**Comment by simonh1000** [comment]
but isn't that some very old software that only works  in 'compatibility' mode with newer versions of windows - how do I get the c++ for win 10

**Comment by refack** [comment]
@simonh1000 we have some links in the README https://github.com/nodejs/node-gyp#on-windows
Simplest option is to install [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017)

**Comment by solominh** [comment]
@refack Thank you very much. I was struggling with building electron app with electron-builder. I installed Visual studio 2017 but it didn't work. Meanwhile, installing build tools did work perfectly.

**Comment by bitsnaps** [comment]
Fixed in Windows, I just had to do `npm install --global --production windows-build-tools` it will install Build Tools and python 2.7 even if python 2.7 was already installed.

**Comment by mrbontor** [comment]
Hi @bitsnaps , while you do the command, do you still to install manually c++?

**Comment by bitsnaps** [comment]
@mrbontor for some reasons I don't have Visual Studio installed in my machine (I use gcc mostly), and since I'm not sure which version should I install, I let `npm` setup the right one for me.

**Comment by mrbontor** [comment]
thanks dude. got it.
