### ISSUE TITLE
Propose release: v3.5.0

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-gyp#1049]
It's been a while and some of this stuff looks useful.

* [[`37ae7be114`](https://github.com/nodejs/node-gyp/commit/37ae7be114)] - Try python launcher when stock python is python 3. (Ben Noordhuis) [#992](https://github.com/nodejs/node-gyp/pull/992)
* [[`e3778d9907`](https://github.com/nodejs/node-gyp/commit/e3778d9907)] - Add lots of findPython() tests. (Ben Noordhuis) [#992](https://github.com/nodejs/node-gyp/pull/992)
* [[`afc766adf6`](https://github.com/nodejs/node-gyp/commit/afc766adf6)] - Unset executable bit for .bat files (Pavel Medvedev) [#969](https://github.com/nodejs/node-gyp/pull/969)
* [[`ddac348991`](https://github.com/nodejs/node-gyp/commit/ddac348991)] - Use push on PYTHONPATH and add tests (Michael Hart) [#990](https://github.com/nodejs/node-gyp/pull/990)
* [[`b182a19042`](https://github.com/nodejs/node-gyp/commit/b182a19042)] - ***Revert*** "add "path-array" dep" (Michael Hart) [#990](https://github.com/nodejs/node-gyp/pull/990)
* [[`9c8d275526`](https://github.com/nodejs/node-gyp/commit/9c8d275526)] - Add --devdir flag. (Ben Noordhuis) [#916](https://github.com/nodejs/node-gyp/pull/916)
* [[`7c08b85c5a`](https://github.com/nodejs/node-gyp/commit/7c08b85c5a)] - ***Revert*** "**configure**: use "path-array" for PYTHONPATH" (Michael Hart) [#990](https://github.com/nodejs/node-gyp/pull/990)
* [[`f6eab1f9e4`](https://github.com/nodejs/node-gyp/commit/f6eab1f9e4)] - **doc**: add windows-build-tools to readme (Felix Rieseberg) [#970](https://github.com/nodejs/node-gyp/pull/970)

The `add --devdir` flag sounds like a minor to me.

cc @nodejs/node-gyp, @bnoordhuis, @rvagg

**Comment by bnoordhuis** [comment]
`--devdir` is semver-minor, yes.  It would be great if someone has time to review #919, that would also make a nice addition.

**Comment by alanpurple** [comment]
please add VS2017 support to this

**Comment by Fishrock123** [comment]
@alanpurple I suspect that will be the release after if no PR is made very soon. Unfortunately I do not have any expertise in that area so I can't really help. :(

**Comment by Fishrock123** [comment]
I think we should probably just release this already. @bnoordhuis are you ok with that? We can always do another minor once that PR and VS2017 land, but progress is pretty slow.

**Comment by bnoordhuis** [comment]
SGTM

**Comment by Fishrock123** [comment]
@bnoordhuis / @rvagg I'm willing to finish this if I can get npm release perms, does anything special need to be done for the changelog or do I just clean up what sounds important and markdownize it?

**Comment by Jeff-Lewis** [comment]
@Fishrock123 Can we get pull [#1085 skip ValueError for long, list and dict type](https://github.com/nodejs/node-gyp/pull/1085) release asap? I think it's crushing all [yarn Windows and ARM users](https://github.com/yarnpkg/yarn/issues/2286) who have `bcrypt` dependency.

**Comment by Fishrock123** [comment]
Maybe @bnoordhuis or @nodejs/python could review that? Python isn't exactly my familiarity.

**Comment by Fishrock123** [comment]
Looks like that PR is now at https://github.com/nodejs/node-gyp/pull/1088

**Comment by rvagg** [comment]
v3.5.0 published
