### ISSUE TITLE
Error C1083: Cannot open include file:“node.h”

### ISSUE THREAD

**Issue by joeferner** [nodejs/node-gyp#105]
A user of one of my modules is seeing the following error. (full details here: https://github.com/voodootikigod/node-serialport/issues/55)

I've successfully compiled it on my machine which is also Windows 7 and VS2010. I haven't been able to reproduce the problem. It looks like a node-gyp issue.

Any thoughts on how I can debug further?

```
D:\nodetest\nodemodules\serialport>node "C:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
serialport_unix.cpp
serialport_win.cpp
d:\nodetest\node_modules\serialport\src\serialport.h(5): fatal error C1083: Cannot open include file:“node.h”: No such file or directory [D:\nodetest\node_modules\seria
lport\
build\serialport.vcxproj]
serialport.cpp
d:\nodetest\node_modules\serialport\src\serialport.h(5): fatal error C1083: Cannot open include file:“node.h”: No such file or directory [D:\nodetest\node_modules\seria
lport\
build\serialport.vcxproj]
gyp ERR! rebuild error Error: msbuild failed with exit code: 1
gyp ERR! rebuild error at ChildProcess.onExit (C:\Program Files\nodejs\node
modules\npm\node_modules\node-gyp\lib\build.js:214:23)
gyp ERR! rebuild error at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok
```

**Comment by Trott** [comment]
This issue is approaching 6 years of inactivity. Should it remain open? (Not saying it should or shouldn't. Just honestly asking. For all I know, the issue has been resolved.)

**Comment by bnoordhuis** [comment]
The extra checking @TooTallNate mentions has been implemented so I don't think there's anything left to do.  I don't remember receiving bug reports about this particular error either.
