### ISSUE TITLE
Getting extra ../ added to releative paths

### ISSUE THREAD

**Issue by ben-kirk** [nodejs/node-gyp#1050]
I'm currently using node-gyp v3.4.0 (node v7.0.0) and I've noticed that when I put relative paths in my binding.gyp file, it adds an extra ../ to the auto-generated MSVS 2015 project. 

For example, in this binding.gyp:

```
{
  "targets": [
    {
      "target_name": "hello",
      "sources": [ "hello.cc" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
                "..\\iconv"
      ],        
      "link_settings": {
        "library_dirs": [
          "..\\iconv\\lib"
        ]  
      }
    }
  ]
}
```

After npm install and opening the MSVS sln file that was generated, I see...

hello Property Pages --> C/C++ --> General --> Additional Include Directories:

..\\..\iconv when I was expecting to see ..\iconv

Same thing is seen for lib dir too...

hello Property Pages --> Linker --> General --> Additional Library Directories:

..\\..\iconv\lib when I was expecting to see ..\iconv\lib

This also happens when I use forward slash (/) instead of escaped backslash (\\) in binding.gyp.

Hopefully this is not some dumb user error on my behalf... I'm a bit new to the Node.js world.

**Comment by bnoordhuis** [comment]
That's because the path is relative to the build directory, not the top-level project directory.  node-gyp builds it in `$project/Debug` or `$project/Release`.

**Comment by ben-kirk** [comment]
Yeah, when filling in the binding.gyp, I was already thinking relative to there the project file is located so I was thrown off when node-gyp auto-adjusted it for me... makes sense now.

**Comment by bnoordhuis** [comment]
Glad to hear.  I'll close the issue.
