### ISSUE TITLE
How to use node-gyp with header *.hpp and source *.cpp files?

### ISSUE THREAD

**Issue by subwaystation** [nodejs/node-gyp#1051]
Hi everyone,

I am wondering how to use nbind (and therefore node-gyp!) having a C++ code structured in header files (ending with .hpp) and source files (ending with .cpp).
One major question is, how to let node-gyp know, when or how to use my header file?

My second question is where to put the nbind stuff:
The class declaration is in my hpp file:

#include <string>
#include <iostream>

class Greeter {
public:
static void sayHello(std::string name);
};

The implementation in my cpp file:

#include "hello.hpp"

static void sayHello(std::string name) {
std::cout<< "Hello, "<< name << "!\n";
}

#include "nbind/nbind.h"

NBIND_CLASS(Greeter) {
method(sayHello);
}

Does it make sense to bind a class here? Or how to I bind a class which was declared in the header file....

All the best.

**Comment by bnoordhuis** [comment]
> how to let node-gyp know, when or how to use my header file?

You add the .cpp to the 'sources' section of your binding.gyp.  You can optionally also add the .hpp; node-gyp will deduce its presence automatically most of the time but being explicit won't hurt.

Questions about nbind should be directed to that project.
