### ISSUE TITLE
Image on popular node-gyp issue (this tracker) got hijacked

### ISSUE THREAD

**Issue by Qix-** [nodejs/node-gyp#1063]
Probably a non-issue but it's kind of trashy. [This comment](https://github.com/nodejs/node-gyp/issues/629#issuecomment-132563324) contains what I imagine was a screenshot but has now been replaced (hijacked by the hosting website ~~probably~~ definitely) with an advert for a potentially harmful site.

Maintainers might want to remove it or figure out what was there beforehand in order to restore it.

I don't think the user is to blame here since the surrounding conversation seems perfectly on-topic and according to Github the comment hasn't been edited.

**EDIT:** It appears the original link was `sd-onsite dot com/wp-content/uploads/2013/02/Changing-profile-path-in-registry.jpg` (seems to have some crap-ware on it now). Definitely should be edited off.

// cc @Sogl

**Comment by addaleax** [comment]
I did that, thanks for pointing it out!

(I am not a node-gyp maintainer but I think it’s okay to do things that are obviously the right thing to do. If anybody feels differently, the original links are still left included as HTML comments.)

**Comment by Qix-** [comment]
Thanks @addaleax :)

**Comment by Sogl** [comment]
Hi!

I'm sorry for the trouble. I searched in Google images for some screens that explained what I'm talked about and have no idea what happened with site which contains them after some time. 

Anyway thanks for the fix, because I can't do edit of this message.
