### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by oliversalzburg** [nodejs/node-gyp#1068]
Our CI is occassionally failing with the following output. I'm not sure what to make of it.

```shell
> bcrypt@1.0.1 install /home/strider/workspace/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@6.9.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unexpected end of file
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:370:17)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/home/strider/workspace/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/strider/workspace/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/strider/workspace/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/strider/workspace/node_modules/bcrypt
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/strider/workspace/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/strider/workspace/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/strider/workspace/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/strider/workspace/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/strider/workspace/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/strider/workspace/node_modules/bcrypt
node-pre-gyp ERR! node -v v6.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/strider/workspace/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/strider/workspace/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/strider/workspace/node_modules/bcrypt/lib/binding' (1)
```

**Comment by tylyo** [comment]
same problem to me

**Comment by oliversalzburg** [comment]
We switched to https://www.npmjs.com/package/bcryptjs

**Comment by joekrump** [comment]
Same problem

**Comment by bnoordhuis** [comment]
I'll close this out because it's not an issue with node-gyp itself.  It tries to download the node source tarball from https://nodejs.org/ but the download is evidently corrupted in your case, presumably because of transient network issues.

As a workaround, download the appropriate tarball manually and point node-gyp to it with the `--tarball` switch.  If you have a local node checkout or an unpacked tarball, you can also use the `--nodedir` switch.  Good luck.

**Comment by oliversalzburg** [comment]
Downloading the tarball manually isn't really an option in CI.

Also, I guess you meant https://github.com and the file that is mentioned (https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v48-linux-x64.tar.gz ) results in a 404 to me. So, unless I'm misinterpreting the output, shouldn't it fall back to just building the library?

Also, if there are transient network issues, I would propose that node-gyp should handle them more gracefully if it will otherwise fail like this.

That being said, I somewhat doubt that theory as we were seeing this exact same error with exactly this package for several days in CI while any other package would install just fine. And we're pulling loads of stuff from GitHub in CI and we're also seeing this exact same node-gyp download workflow working just fine with other packages.

**Comment by bnoordhuis** [comment]
Keep in mind that node-gyp and node-pre-gyp are different things.  node-pre-gyp tries to download a precompiled .node file.  When that fails, it hands control to node-gyp which then proceeds to build from source (but first needs to download the SDK from https://nodejs.org/.)

It's possible the error message is a red herring and it's actually a node.bcrypt.js pre- or post-install script that generates the error.  Obviously you should report that to that project, not here.

> Also, if there are transient network issues, I would propose that node-gyp should handle them more gracefully if it will otherwise fail like this.

A corrupted download is a corrupted download.  There is nothing to do but report an error or try again.  node-gyp does the former.
