### ISSUE TITLE
How to select c++ runtime based on target version

### ISSUE THREAD

**Issue by appdlh** [nodejs/node-gyp#1072]
I need to select which C++ runtime to link with on macOS based on the target node version. Something like this:

`
'conditions': [
  ['target>=7.0.0', { ... }, { ... }]
]
`

However, target is string valued in the format "vX.Y.Z" and even if it wasn't prefixed with a 'v' I don't think a numeric comparison like that would work.

How would I set up a condition that tests if the target version is <7 or >= 7?

**Comment by bnoordhuis** [comment]
`'target >= "v7"'` should work, at least until node reaches v10.  If you want to go fancier, you could compare against `int(target[1:].split('.')[0])`.

**Comment by bnoordhuis** [comment]
That said, why do you want to change the runtime?  Unless you have good reason you should use the one that node links against.  Mixing C++ runtimes in a single process is usually asking for trouble.

**Comment by appdlh** [comment]
I'm not the one wanting to change the runtime, just the one tasked with figuring out how to accomplish that... I'll double check on the requirements / why of it. 

Thanks for the solution above, I didn't know conditional expressions were that rich!

**Comment by appdlh** [comment]
I closed this prematurely :-/ It turns out `target` is only set if you explicitly pass `--target=` on the command line. We need something we can switch on that is always there. The only thing I see in config.gypi after a straight `node-gyp clean configure` is `nodedir`; I don't know how reliable that would be, since in most cases it would probably point to an un-versioned system directory?

So, is there a way to determine the target node version even when --target hasn't been specified explicitly?

Thanks!

**Comment by bnoordhuis** [comment]
> The only thing I see in config.gypi after a straight node-gyp clean configure is nodedir; I don't know how reliable that would be, since in most cases it would probably point to an un-versioned system directory?

Correct.  node-gyp builds against a source tree and doesn't really know the version number or even if it's node - it could be node-webkit, electron, etc.  You can try to extract the version number by searching for `#define NODE_MAJOR_VERSION (\d+)` in `$nodedir/src/node_version.h`.

With newer versions of node there is a `node_module_version` variable that corresponds to NODE_MODULE_VERSION from node_version.h.  The check for >= v7 would look like this:
```
['conditions': [ ['node_module_version >= 51', { ... } ] ] ],
```
It's probably still better for your long-term sanity to not mess around with C++ runtimes, though.
