### ISSUE TITLE
possible edge case when packaging self-contained node with C++/CLI native modules

### ISSUE THREAD

**Issue by issacg** [nodejs/node-gyp#1074]
(moved from [#10723](https://github.com/nodejs/node/issues/10233))

I've run into an odd case on Windows platform, when I try to create a self-contained node application (I've been using [nexe](https://github.com/jaredallard/nexe) and [xbin](https://github.com/calebboyd/xbin) to help package; both reproduce the error) with a native module that uses C++/CLI, I consistently get the error message `Error: Module didn't self-register` when require()ing the module.

When require()ing the module in a normal node.js build (on the same toolchain), the module self-registers and runs just fine.  When require()ing a pure-c++ native extension on the self-contained applications, the module self-registers and runs just fine.  In trying to rule out specific compilers or Node.js versions I've reproduced the problem on Node 4.4.4, Node 6.3.1 and Node 6.9.1 in ia32 and x64 modes, with Visual Studio 2013 Update 5 and Visual Studio 2015 Update 3.

I've written [this gist](https://gist.github.com/issacg/a64a8805b0731537e495d57ab39acf3a) which shows a sample problematic native extension.  This will build, load and run quite nicely using a standalone nodejs (with and without packing with the webpack config seen in the gist)

However, when bundling the webpack and creating a standalone application (leaving the native module as a dynamically loaded module), I get the error message "Module didn't self register". 

Unlike what I wrote in issue [#10723](https://github.com/nodejs/node/issues/10233), it *is* correctly hooking `node_module_register` (discovered after reverse-engineering the assembly code :/)

After investigating, it seems that the line `decltype (__pfnDliNotifyHook2)  __pfnDliNotifyHook2 = load_exe_hook;` is never being called, and thus when the native module is loaded, it has some other reference to an uninitialized nodejs runtime in memory.  Presumably, it's finding a code reference to node.exe somewhere (haven't worked out where quite yet) and thus rather than refusing to load the DLL, it's running `node_module_register` in some other copy of the nodejs runtime rather than where `modpending` is waiting to be populated (there are other side effects too, such as `node_is_initialized` being `false` in this "other" runtime)

I have worked around it by using [this tool](https://github.com/ironSource/rename-import-dll) to patch the DLL, but it seems to me that there must be a better way...

**Comment by bnoordhuis** [comment]
Is your question how to disable the load hook?  Set `'win_delay_load_hook': 'false'` in the add-on's binding.gyp at the same level as target_name.

**Comment by issacg** [comment]
> Is your question how to disable the load hook?

No, not at all.  I need the load hook since I'm renaming the binary. The problem is that the load hook isn't being registered at runtime.

**Comment by bnoordhuis** [comment]
I'm going to close this for inactivity.  I don't have an answer to your question but I'd say it's rather outside node-gyp's normal mode of operation.  You probably have to look elsewhere for a solution.
