### ISSUE TITLE
Can't compile CPP file with node-gyp

### ISSUE THREAD

**Issue by sergenikov** [nodejs/node-gyp#1075]
I am learning how to build a node add-on with this tutorial http://stackabuse.com/how-to-create-c-cpp-addons-in-node, (tutorial itself is irrelevant) but can't build because of msbuild error duing `node-gyp build` command. I followed instruction in the README and additional instructions here: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules.

```
C:\Users\Sergey\code\mod>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.2 | win32 | x64
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Sergey\code\mod\build\pow.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\M
icrosoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is
 correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sergey\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sergey\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\Sergey\code\mod
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp
```

- Window 10 updated (a clean OS install)
- Installed VS2015 Community with Common Tools for Visual C+
- python 2.7 installed and in PATH
- tried `npm config set msvs_version 2015 -g` (and without -g)
- tried `node-gyp --msvs_version=2015 build` and `node-gyp build --msvs_version=2015` (just in case)
- Tried adding a string value `VCTartgetsPath` to the registry following some SO recommendations
- Tried setting environement variable VCTartgetsPath
- Installed `npm install --global --production windows-build-tools`, removed my other python, added the newly installed python to path, but still got the same error.
- also tried hardcoding the string in the vcxproj file to `<Import Project="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props"/>` in all cases where VCTargetsPath is in the file.

In the `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0` I only have the V140 directory, which I think is created by the VS2015 installation. I think `V110` is created by VS2012 (could be wrong), but why would I need to install that?

`node-gyp` still keeps looking for the project in this `v110` directory. I am at a loss: I found so many conversations in Issues (in this repo) and SO discussions, but it looks like there are a million variables that affect if `node-gyp` will run. Does this error message and the combination of my attempts and environment give any clue as to why the error is happening? I would really appreciate some help.

**Comment by sergenikov** [comment]
I am not sure this is a solution, but in my case duplicating the V140 directory and renaming it into V110 solved the problem, and I was able to compile a working addon. Maybe it will help someone else.

**Comment by VincentSCW** [comment]
I have the same issue. Then I install VS2012, but still didn't work. It gives me this:
`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds
tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Proje
ct menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 bu
ild tools. [D:\Project\Omni\omni-operation-ui\node_modules\png-img\build\third_party\libpng\libpng.vcxproj]`

It looks like a joke...

**Comment by bnoordhuis** [comment]
@VincentSCW Try passing `--msvs_version=2015`.  VS 2012 won't work for any supported version of node.js, by the way.  They all need 2013 or better.
