### ISSUE TITLE
node-gyp configure

### ISSUE THREAD

**Issue by lancefarrah** [nodejs/node-gyp#1076]
I am trying to run another software but it needs node-gyp to work. I have no idea why this is happening.
Running Ubuntu 16.04.

node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@0.10.32 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /node_modules
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
Do you have node and python2 on the $PATH?  Does `node-gyp --python /path/to/python2-binary configure` work?

**Comment by lancefarrah** [comment]
Yeah got it straight thanks I just had more version of python installed I wasn’t aware of...thanks it's fixed.
