### ISSUE TITLE
error LNK2001: 无法解析的外部符号 __imp__cairo_image_surface_create_from_png

### ISSUE THREAD

**Issue by gyx434494833** [nodejs/node-gyp#1078]
C:\Users\Gong\AppData\Roaming\npm\node_modules\canvas\build\Release\canvas.node
 : fatal error LNK1120: 111 个无法解析的外部命令 [C:\Users\Gong\AppData\Roaming\
npm\node_modules\canvas\build\canvas.vcxproj]

GTK: C:\GTK
node -v: v5.0.0
node-gyp -v v3.4.0
npm: v4.1.1

Help Me!

**Comment by gyx434494833** [comment]
The problems of the node-canvas compiler

**Comment by bnoordhuis** [comment]
Closing, not related to node-gyp.  Try filing an issue with node-canvas.

**Comment by gyx434494833** [comment]
May I ask you for a look

**Comment by gibfahn** [comment]
@gyx434494833 Have you tried raising an issue with node-canvas? I assume here: https://github.com/Automattic/node-canvas/issues
