### ISSUE TITLE
Node-gyp compatible toolchains/tools for Windows

### ISSUE THREAD

**Issue by amigo421** [nodejs/node-gyp#1079]
This is not an issue or feature request, 
I'm just trying to understand which latest MS toolchains are supported and which ones are not
1. VC++ Build Tools 2015 - not support from my perspective. Error related with VCBuild even MSBuild is really installed 
2. VS 2015 - supported
3. VS2017 RC  and VS2017 Build Tools RC - both not supported yet
Is it correct? 
I don't use MS VS IDE, and currently seems node-gyp requires me forcly to install full IDE, is it right?

**Comment by gibfahn** [comment]
Visual C++ Build Tools 2015 should work (as should [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) with `npm install --global --production windows-build-tools` ) as covered in [the README](https://github.com/nodejs/node-gyp#installation).

>VC++ Build Tools 2015 - not support from my perspective.

This seems like the issue. It is supported. If you've followed the instructions in the README and are still having issues then let us know the details in this issue.

**Comment by amigo421** [comment]
my inattention, sorry let me check build tools again with an instructions
