### ISSUE TITLE
Centos 6

### ISSUE THREAD

**Issue by romansopov** [nodejs/node-gyp#1080]
Make to Centos 6
required ```sudo yum groupinstall 'Development Tools'```

**Comment by gibfahn** [comment]
Not sure what this issue means. I'm guessing you saw the requirement to have make installed [in the README](https://github.com/nodejs/node-gyp#installation) and googled "CentOS 6 install make" to get this command? Are you seeing a `node-gyp` related problem?

Closing, feel free to comment on here if you think it should be reopened.
