### ISSUE TITLE
how to check difference of two objects nodejs

### ISSUE THREAD

**Issue by addikhann** [nodejs/node-gyp#1086]
i am new in nodejs i am using below library.. i don't understand example of this site.. i have 2 object..1 is request and scond is findbyid response..i want to check difference... but my code does not work please help me...  i am using node promises and mongoose schema

> Error: functions are not supported

[check difference library](https://www.npmjs.com/package/jsondiffpatch)

>   export function update(req, res) {
> 
>    Job.findOne( {_id: req.params.id}).exec().then(function(Job){
> 
>   var diffpatcher = jsondiffpatch.create({
> 
>         objectHash: function(Job) {         
>             return Job.title;
>         }
>     });
> 
>  var delta = diffpatcher.diff(Job, req);
> console.log(delta)
> 
>    }).catch(function(error){
> console.log('error body');
> console.log(error);
> 
>    });

**Comment by gibfahn** [comment]
Can you please post this in https://github.com/nodejs/help ?
