### ISSUE TITLE
Can't build with node version 6.9.4

### ISSUE THREAD

**Issue by sakshi-kataria** [nodejs/node-gyp#1095]
$ .\node_modules\.bin\electron-rebuild -a=ia32
× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nizam.khan\\.electron-gyp\\.node-gyp\\iojs-1.4.15\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nizam.khan\\.electron-gyp\\.node-gyp\\iojs-1.4.15',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\edge-atom-shell\build\edge.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.4.15" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\edge-atom-shell
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Failed with exit code: 1
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nizam.khan\\.electron-gyp\\.node-gyp\\iojs-1.4.15\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nizam.khan\\.electron-gyp\\.node-gyp\\iojs-1.4.15',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\edge-atom-shell\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\edge-atom-shell\build\edge.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Nizam_Work\\GitLab\\smartbox-terminal\\smartbox-client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.4.15" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\edge-atom-shell
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Failed with exit code: 1
    at SafeSubscriber.obs.subscribe.e [as _error] (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\spawn-rx\lib\index.js:311:43)
    at SafeSubscriber.__tryOrUnsub (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:223:16)
    at SafeSubscriber.error (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:184:26)
    at Subscriber._error (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber.pipesClosed.subscribe [as _next] (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\spawn-rx\lib\index.js:284:42)
    at SafeSubscriber.__tryOrUnsub (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:223:16)
    at SafeSubscriber.next (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:172:22)
    at Subscriber._next (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:89:18)
    at ReduceSubscriber._complete (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\operator\reduce.js:116:30)
    at ReduceSubscriber.Subscriber.complete (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\Subscriber.js:114:18)
    at MergeAllSubscriber.notifyComplete (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\operator\mergeAll.js:105:30)
    at InnerSubscriber._complete (D:\Nizam_Work\GitLab\smartbox-terminal\smartbox-client\node_modules\rxjs\InnerSubscriber.js:30:21)

**Comment by sakshi-kataria** [comment]
I am using Node 6.9.4 and visual studio 2013 but not able to create build

**Comment by bnoordhuis** [comment]
You need Visual Studio 2015 Update 3 or Visual C++ Build Tools with v6.9.4, VS 2013 isn't supported.
