### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by sgehrman** [nodejs/node-gyp#1104]
normal windows 10, normal installed python latest.

I try to build, It can't find python??  I have the default setup, nothing weird.  which command returns python path.

checkPythonLauncher seems pretty bad, I would look there.

f:\Github\electron-store\node_modules\runas>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:111:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd f:\Github\electron-store\node_modules\runas
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
store@1.0.0 f:\Github\electron-store
`-- (empty)

**Comment by sgehrman** [comment]
And, yes I did try setting the ENV, nothing worked.  The code looks buggy.

**Comment by bnoordhuis** [comment]
Exact steps please?  People set PYTHON all the time so odds are it's something on your end.

If you invoke node-gyp through npm, do `npm config set python \path\to\python2.7`.

**Comment by richardlau** [comment]
Also you need python 2 -- python 3 will not work.

**Comment by VincentSCW** [comment]
After resolve this, there are tons of issues remaining...

**Comment by bnoordhuis** [comment]
No follow-up from OP, closing.
