### ISSUE TITLE
Within a docker build, Modules dependant on node-gyp fail (only where npm-shrinkwap in use)

### ISSUE THREAD

**Issue by vidhill** [nodejs/node-gyp#1105]
Not sure which is the best place for this, 

We are using a number of npm packages which in turn have a dependancy on node-gyp, 

i.e. my project does not _directly_ use node-gyp

We run npm-install as part of our docker image build process..

When I put a npm-shrinkwrap.json in place the npm install is failing due to errors relating to python not being in place..

```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

Maybe I need to include a python install as part of pre-build

But my confusion is, why is would fail for this reason **only** when the npm-shrinkwrap is in place?

**Comment by bnoordhuis** [comment]
Maybe there are install scripts that start node-gyp, that's something a quick `grep -r` through your node_modules directory should be able to tell you.

If that isn't it, you'll probably have more luck getting your question answered at https://github.com/npm/npm/issues.  node-gyp's role is a passive one, it only does what it's told by the process that started it, presumably npm.

**Comment by vidhill** [comment]
node-gyp is being kicked off by a https://github.com/kesla/node-snappy

I was able to get it to work by installing python, make and GCC as part of the docker build process, but it seems strange to me that this is necessary in this case

**Comment by vidhill** [comment]
The solution was to modify my docker image to install the dependancies of node-gyp:
make, GCC and python 

So that the node-gyp script could run.

As to why the behaviour is different from the shrinkwrap non skrinkwrapped is still a bit of a mystery to me

**Comment by iwarner** [comment]
@vidhill Can you please provide your dockerfile I am constanly getting Gyp errors - sepecifally around Python paths.

**Comment by mtrogers** [comment]
@vidhill I second this motion

**Comment by vidhill** [comment]
Hi,
I can't share the exact Dockerfile, as it's not an open source project, for now I'll create a gist..

https://gist.github.com/vidhill/0a85dc1848feee4171944dc4d7757895

-this is an untested Dockerfile because I'm off to bed now..
if this doesn't help I can create a proper mini-project
