### ISSUE TITLE
Build a dylib file for node

### ISSUE THREAD

**Issue by KamyarGhajar** [nodejs/node-gyp#1106]
hi,
How can I build a dylib file to be used by node js as a module?
How the binding.gyp should be set etc.

**Comment by bnoordhuis** [comment]
You've read https://nodejs.org/docs/latest/api/addons.html?  If yes, what's unclear?  If not, go do that first.

**Comment by KamyarGhajar** [comment]
I only have the pre-built .dylib file and not the source code of it...how can I get the .node file built from this single dylib file to require it in the project?

**Comment by bnoordhuis** [comment]
You could have been more explicit about that, that would've saved us both some time...  If you want to link in a pre-existing .dylib, you'd add something like this to your binding.gyp:
```
'link_settings': {
  'libraries': ['-L/path/to/dir']
},
'libraries': ['-Llibname'],
```
You may want to define an rpath so you don't have to set DYLD_LIBRARY_PATH at runtime.  Consult `man ld` or just google it.

You're still going to need glue code for exposing your dylib as a node add-on.  That's well outside the scope of this issue tracker though; see the link to the addons documentation I posted earlier.
