### ISSUE TITLE
Expose .dylib for node.js

### ISSUE THREAD

**Issue by KamyarGhajar** [nodejs/node-gyp#1108]
How can I expose a dylib to a node.js code...I can require a module in node.js now with cpp codes built into a .node file...but my library is not exposed...this is my binding.gyp file:
```
{
  'targets': [
    {
      'target_name': 'abc',
      'include_dirs': ['libabc'],
      'sources': [ 'main.cpp'],
      'link_settings': {
        'libraries': [
        '/Users/user/Developer/Projects/abc/libabc/libabc.dylib',
        '/Users/user/Developer/Projects/abc/libabc/libabc.4.dylib',
        '/Users/user/Developer/Projects/abc/libabc/libabc.4.8.2.dylib'
      ]
      },
      'libraries': [
        '/Users/user/Developer/Projects/abc/libabc/libabc.dylib',
        '/Users/user/Developer/Projects/abc/libabc/libabc.4.dylib',
        '/Users/user/Developer/Projects/abc/libabc/libabc.4.8.2.dylib'
      ]
    }
  ]
}
```

this is how the files places in the abc folder:
```
abc ->
        - binding.gyp
        - main.cpp
        - libabc ->
                      - libabc.dylib
                      - libabc.4.dylib
                      - libabc.4.8.2.dylib
```

and this is my main.cpp file (including a test sample from [here](https://nodejs.org/docs/latest/api/addons.html)):
```
// addon.cc
#include <node.h>

namespace demo {
    
    using v8::Exception;
    using v8::FunctionCallbackInfo;
    using v8::Isolate;
    using v8::Local;
    using v8::Number;
    using v8::Object;
    using v8::String;
    using v8::Value;
    
    // This is the implementation of the "add" method
    // Input arguments are passed using the
    // const FunctionCallbackInfo<Value>& args struct
    void Add(const FunctionCallbackInfo<Value>& args) {
        Isolate* isolate = args.GetIsolate();
        
        // Check the number of arguments passed.
        if (args.Length() < 2) {
            // Throw an Error that is passed back to JavaScript
            isolate->ThrowException(Exception::TypeError(
                                                         String::NewFromUtf8(isolate, "Wrong number of arguments")));
            return;
        }
        
        // Check the argument types
        if (!args[0]->IsNumber() || !args[1]->IsNumber()) {
            isolate->ThrowException(Exception::TypeError(
                                                         String::NewFromUtf8(isolate, "Wrong arguments")));
            return;
        }
        
        // Perform the operation
        double value = args[0]->NumberValue() + args[1]->NumberValue();
        Local<Number> num = Number::New(isolate, value);
        
        // Set the return value (using the passed in
        // FunctionCallbackInfo<Value>&)
        args.GetReturnValue().Set(num);
    }
    
    void Init(Local<Object> exports) {
        NODE_SET_METHOD(exports, "add", Add);
    }
    
    NODE_MODULE(addon, Init)
    
}
```

p.s. I can access the `add` function in main.cpp from node.js with `require`.

**Comment by bnoordhuis** [comment]
Is your question how to write glue code for your shared library?  That's either an add-on programming question or a general C++ question.  Either way, this bug tracker isn't the right place to ask.

For add-on related questions, try https://github.com/nodejs/help/issues.  Note that you shouldn't expect answers when it's something you can find in the documentation.

For questions specific to the shared library that you're writing bindings for, you should consult its documentation.  Good luck.

**Comment by KamyarGhajar** [comment]
@bnoordhuis would you mind giving me a link to the documentation that shows how to expose the dylib library to node js...if it was that obvious I assure you I wouldn't bother you this much.

**Comment by bnoordhuis** [comment]
The add-ons documentation on https://nodejs.org/ explains how to write C++ code that is accessible to JS code.  Interfacing that C++ code with your library is not something I or anyone in this community can help you with but google around for other add-ons that are bindings to existing libraries (like e.g. node-iconv.)

**Comment by KamyarGhajar** [comment]
I've actually looked for an answer for a while now, but thank you for the tip @bnoordhuis...I'll look into it.
