### ISSUE TITLE
rebuild/configure "Error: `gyp` failed with exit code: 1"

### ISSUE THREAD

**Issue by Theawesome624** [nodejs/node-gyp#1110]
I am trying to use rebuild and it doesn't work, I then tried `clean`,`configure` and `build` individually and in that order, and it seems to give me this error on the `configure` part. : 
![image](https://cloud.githubusercontent.com/assets/15312295/22765508/525b23ea-ee36-11e6-8bc0-41f6fb425de9.png)

**Comment by bnoordhuis** [comment]
'binding.gyp not found' means you're executing node-gyp from a directory that doesn't contain an add-on.  What exactly are you trying to do or build?

**Comment by Theawesome624** [comment]
I'm trying to install "robotjs". One of the required libraries is node-gyp

**Comment by bnoordhuis** [comment]
node-gyp is just a build tool, nothing more.  You are probably executing it from the wrong directory but I can't tell you what the right directory should be.  Try reporting it to robotjs, they can probably help you.  Good luck.
