### ISSUE TITLE
Two new commit patch `GYP` code but are missing .patch file

### ISSUE THREAD

**Issue by refack** [nodejs/node-gyp#1119]
ec5fc36a80ea1e98eac1f490545ccb4e71fce846
a04ea3051a60bbfdabda3bafef213028cc099f6a

**Comment by bnoordhuis** [comment]
I think I'll remove the .patch files, they just duplicate what's already in git.  Thanks for bringing it up though.

**Comment by refack** [comment]
What if you want to rebase our changes onto a new `GYP` version?
