### ISSUE TITLE
Stop using tape for tests

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-gyp#1123]
Tape runs all tests in the same process.  There doesn't seem to be a way to request process-per-test isolation.

Monkey-patching in tests ends up affecting other tests.  I'm quite sure at least one or two bugs (hopefully only in tests) went unnoticed because of it so I propose we move away from tape.

**Comment by rvagg** [comment]
or we could stop monkey patching or do proper isolation with child processes as required

**Comment by richardlau** [comment]
Another reason to stop using tape -- The test failure in https://github.com/nodejs/node-gyp/pull/1131 actually stopped the test execution dead in its tracks (i.e. no further tests were run), e.g. https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms/118/MACHINE=aix61-ppc64/console

**Comment by NatalieWolfe** [comment]
[Tap](https://www.npmjs.com/package/tap) would be largely a drop-in replacement and runs each of the test files as separate child processes.

**Comment by gibfahn** [comment]
We already use tap for [node-report](https://github.com/nodejs/node-report/), [citgm](), and [npm](https://github.com/nodejs/citgm), and [npm](https://github.com/nodejs/node/blob/master/deps/npm/package.json#L219), so it would probably make sense to use it here as well.

**Comment by rvagg** [comment]
moving to #1171
