### ISSUE TITLE
Permission error on WSL when globally installing

### ISSUE THREAD

**Issue by strarsis** [nodejs/node-gyp#1127]
node-gyp fails with permission errors on WSL (BashOnWindows) when 
installing globally (npm install -g) as root user:
https://github.com/creationix/nvm/issues/1405#issuecomment-282096545

**Comment by bnoordhuis** [comment]
Any reason to believe it's a node-gyp issue and not simply a matter of fixing those permissions?  Does the node-gyp script have its executable bit set?

**Comment by strarsis** [comment]
Installation of these packages without -g switch works fine.

`~/.nvm/versions/node/v4.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js` 
has chmod +x set but this doesn't fix the issue.

**Comment by bnoordhuis** [comment]
Then I don't know.  The error you posted in the other issue, `sh: 1: node-gyp: Permission denied`, says that the shell can't execute node-gyp, it doesn't come from node-gyp itself.  You'll probably have to look elsewhere to get your issue resolved.
