### ISSUE TITLE
install error  Cannot open include file: 'node.h'

### ISSUE THREAD

**Issue by Usatijj** [nodejs/node-gyp#1129]
I have Windows 10 Pro x64, node v6.10.0, npm v3.10.10
when I make: npm install hummus , I have error:

![error](https://cloud.githubusercontent.com/assets/25999847/23295961/b6afe320-fa7b-11e6-8cc3-9fcb4c2b8254.png)
 what I do wrong?

**Comment by bnoordhuis** [comment]
Hard to say but it's probably not anything to do with node-gyp.  You should report this to the hummus project.  Good luck.

**Comment by Usatijj** [comment]
Thanks. Good luck.
