### ISSUE TITLE
node-gyp failing when module built with yarn in official docker image

### ISSUE THREAD

**Issue by mattkime** [nodejs/node-gyp#1135]
https://github.com/mattkime/get-cursor-position-fail/

Running `docker build .` from the repo directory results in -

```
[4/4] Building fresh packages...
error /home/mup/node_modules/get-cursor-position: Command failed.
Exit code: 127
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/mup/node_modules/get-cursor-position
Output:
sh: 1: node-gyp: not found
```

Modify Dockerfile to use npm instead and it works fine.

The official docker images, verified in both v7.6 and v7.7.1. Both use yarn v0.21.3

---

I have no idea if this is a yarn, docker node image, or node-gyp problem

**Comment by bnoordhuis** [comment]
See https://github.com/nodejs/docker-node/issues/346 and https://github.com/yarnpkg/yarn/issues/2266, it's a known yarn issue.
