### ISSUE TITLE
sudo: node-gyp: command not found error

### ISSUE THREAD

**Issue by Pltnorwich** [nodejs/node-gyp#1136]
Hi Guys,

Im new to all of this command line tools, I have a raspberry pi 2 and wanted to install homebridge,

I have followed this tutorial and managed to get to install homebridge and dependancies
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#introduction

After issuing the following commands;
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /usr/local/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns           All run ok.

The last one;
sudo node-gyp BUILDTYPE=Release rebuild  --------- I receive the following error;

sudo: node-gyp: command not found

All the commands have been issued via ssh ( I'm on a mac if it makes a difference)
Any help would be greatly appreciated as I don't know why the last step fails - there were no errors through the tutorial.

If you have an idea; I can copy and paste commands, but if you need more info you will have to assist on how i get that.

Many Thanks

Phil

**Comment by bnoordhuis** [comment]
You probably need to run `sudo PATH="$PATH" node-gyp ...` because I expect node-gyp isn't installed in a directory that is on the root user's path.

**Comment by Pltnorwich** [comment]
hi bnoordhuis,
 is that the command i can copy and paste into terminal, or do i need to add more to it? like i say I'm new to this - i guess the command is telling the system the path of node so it knows where to look if called upon?
is there some search function that will show me the location of node-gyp?

Thanks so far for your help

**Comment by gibfahn** [comment]
You originally typed `sudo node-gyp BUILDTYPE=Release rebuild`, you should replace with `sudo PATH="$PATH" node-gyp BUILDTYPE=Release rebuild`.

When you run as sudo the command is executed as the `root` user. The root user may have a different path defined, which probably doesn't include the directory where npm installed `node-gyp`. The command @bnoordhuis suggested sets the `PATH` variable for that command to your user's PATH (your username is whatever `whoami` returns).

You can echo your path with `echo $PATH`, and you can find out the root user's path with `sudo env | grep PATH`. To find out where `node-gyp` is just run `which node-gyp`.

**Comment by Pltnorwich** [comment]
Hi Gibfahn.

Im in front of the RaspberryPI for a bit. whoami returns "pi"

I open a new terminal window and ran 
"sudo su - " and it returned "root@raspberrypi:~# "

echo $PATH returned "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

Running "which node-gyp" in either the above terminal window or another returns no answer.

Im slowly trying to get my head round what everything means and works.

**Comment by bnoordhuis** [comment]
Did the `sudo PATH="$PATH" node-gyp BUILDTYPE=Release rebuild` stanza work though?

**Comment by Pltnorwich** [comment]
Hi bnoordhuis,

I was in this directory 
pi@raspberrypi:/opt/node/lib/node_modules/hap-nodejs/node_modules/mdns $

i then issued -     sudo PATH="$PATH" node-gyp BUILDTYPE=Release rebuild

It returned -      sudo: node-gyp: command not found

Thanks

**Comment by Pltnorwich** [comment]
Hi, this is the list of commands issued in order, none showed errors, perhaps this will also help...

sudo apt-get update

sudo apt-get upgrade

(I had to install node.js binaries this way)
wget https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-armv6l.tar.xz

tar xJvf node-v6.9.5-linux-armv6l.tar.xz

sudo mkdir -p /opt/node

sudo mv node-v6.9.5-linux-armv6l/* /opt/node/

sudo update-alternatives --install "/usr/bin/node" "node" "/opt/node/bin/node" 1

sudo update-alternatives --install "/usr/bin/npm" "npm" "/opt/node/bin/npm" 1

sudo apt-get install libavahi-compat-libdnssd-dev

Homebridge Dependencies
(note that /usr/local/lib should be replaced with /usr/lib/ if you installed node using apt-get method above or with /opt/node/lib/ if binary method used)

I used /opt/node/lib as i installed using binary as its on raspberry pi 2

sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp

cd /usr/local/lib/node_modules/homebridge/

sudo npm install --unsafe-perm bignum

cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns

sudo node-gyp BUILDTYPE=Release rebuild   ----- this is the last stage but shows node-gyp command not found.

I hope you guys can help me out.

Thanks

Phil

**Comment by gibfahn** [comment]
@Pltnorwich what does `npm bin -g` return on your system (if that doesn't work try `sudo npm bin -g`?

**Comment by Pltnorwich** [comment]
pi@raspberrypi:~ $  npm bin -g
/opt/node/bin
(not in PATH env variable)

**Comment by gibfahn** [comment]
Okay, then try `sudo PATH="$PATH:/opt/node/bin" node-gyp BUILDTYPE=Release rebuild`

**Comment by Pltnorwich** [comment]
Hi gibfahn,

i copied the above into terminal and received the following;

pi@raspberrypi:~ $ sudo PATH="$PATH:/opt/node/bin" node-gyp BUILDTYPE=Release rebuild
sudo: node-gyp: command not found

i then tried to change to the node-modules directory and run ( last step before rebuild command in tutorial)

/opt/node/lib/node_modules/hap-nodejs/node_modules/mdns $ sudo PATH="$PATH:/opt/node/bin" node-gyp BUILDTYPE=Release rebuild
sudo: node-gyp: command not found

Should i try run the command in a different directory? I guess I'm including the "" marks too?

Thank you so far

**Comment by Pltnorwich** [comment]
<img width="576" alt="screenshot 2017-03-06 22 08 41" src="https://cloud.githubusercontent.com/assets/9009774/23632403/a68b817a-02b9-11e7-980a-f0e0370b8c9b.png">

**Comment by Pltnorwich** [comment]
<img width="590" alt="screenshot 2017-03-06 22 12 39" src="https://cloud.githubusercontent.com/assets/9009774/23632507/0f3a0566-02ba-11e7-8289-cd2139a45f6e.png">

**Comment by gibfahn** [comment]
What do these:

```bash
npm list -g --depth 0
sudo npm list -g --depth 0
```

return? That should show you a list of all the modules you've installed globally (and the full path to them). You should get something like:

```
/usr/local/lib
├── bower@1.8.0
├── citgm@1.11.0
├── core-validate-commit@3.1.0
├── eslint@3.14.1
├── npm@4.1.2
└── yo@1.8.5
```

As long as `node-gyp` is in that list then it's been installed successfully. You should be able to add that directory to the path. Try this:

```bash
sudo su -
npm install -g node-gyp             # Does nothing if it's already installed
export PATH=$PATH:/usr/local/lib    # Replace /usr/local/lib with the path from npm list
which node-gyp                      # Should show the path to node-gyp
node-gyp BUILDTYPE=Release rebuild  # Don't need sudo cause you're already in a sudo shell
exit                                # Quit
```

The output from `npm install` should confirm that you're in the right directory.

**Comment by Pltnorwich** [comment]
Ran the first one, returned.....

pi@raspberrypi:~ $ npm list -g --depth 0
/opt/node/lib
├── hap-nodejs@0.4.21
├── homebridge@0.4.16
├── node-gyp@3.5.0
└── npm@3.10.10

npm ERR! extraneous: bignum@0.12.5 /opt/node/lib/node_modules/homebridge/node_modules/bignum
pi@raspberrypi:~ $ 

2nd one;

pi@raspberrypi:~ $ sudo npm list -g --depth 0
/opt/node/lib
├── hap-nodejs@0.4.21
├── homebridge@0.4.16
├── node-gyp@3.5.0
└── npm@3.10.10

npm ERR! extraneous: bignum@0.12.5 /opt/node/lib/node_modules/homebridge/node_modules/bignum
  
somewhere there has been an error :-(

Open the case up of the Raspberry too ( its from work)    Its a PI B+  (shocked)   Maybe this is causing the error not being compatible ?
I will run the ;
sudo su          later.

What you think that npm ERR! extraneous means - compatibility? i will look at buying a PI 3 if i know i can get it to function.

Thank you

**Comment by gibfahn** [comment]
The `npm ERR! extraneous: bignum@0.12.5 /opt/node/lib/node_modules/homebridge/node_modules/bignum` isn't necessarily a problem.

It looks to me like the instructions you're following are missing the step where you update your path to include the directory npm is installing to, its probably worth [raising an issue](https://github.com/nfarina/homebridge/issues/new) with your problem there so it can be fixed for other people.

**Comment by Pltnorwich** [comment]
Hi gibfahn,
Have you an idea of what command I could type to update the path from the above.

I will add it to the original tutorial as well later this evening. 
Thanks

**Comment by Pltnorwich** [comment]
hi Gibfahn,

I ran your commands and here is the output.....
<img width="572" alt="screenshot 2017-03-07 20 30 40" src="https://cloud.githubusercontent.com/assets/9009774/23676544/f7a53662-0374-11e7-8570-bad8647b954d.png">

The install command and the export command ran ok.

Which node-gyp    gave no output.
should i have changed directory before running the BUILDTYPE command?

**Comment by gibfahn** [comment]
As I said above, you need to replace /usr/local/lib with the path from `npm list`, i.e.:

```bash
export PATH=$PATH:/opt/node/lib    # Replace /usr/local/lib with the path from npm list
```

retry the `sudo su -` commands with that.

`node-gyp rebuild` will run in your current directory, so you need to cd into whichever directory you're trying to build. You also need to make sure that the directory containing `node-gyp` is in your `$PATH` environment variable, as when you type `node-gyp BUILDTYPE=Release rebuild` bash will search all the directories in your path for a binary (executable) called `node-gyp`.


```bash
sudo su -
which node-gyp                 # This should have no output as you haven't added the directory to the path yet
npm install -g node-gyp             # Does nothing if it's already installed (but shows you the path)
export PATH=$PATH:/opt/node/lib    # Add the directory containing node-gyp to your path
which node-gyp                      # Should show the path to node-gyp now
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild
```

**Comment by gibfahn** [comment]
Remember to look at the error message you get back, in this case: `-su: node-gyp: command not found` is an error from `su` (superuser, the root shell you're running) which tells you that the command `node-gyp` wasn't found (because it wasn't in the path). It's not a node-gyp error.

I highly recommend learning some shell basics if you're going to be doing anything with Linux or Raspberry Pis, it'll really pay off longer term.

Quick interactive course: https://www.codecademy.com/en/courses/learn-the-command-line/lessons/environment/exercises/bash-profile
Cheatsheet: https://learnxinyminutes.com/docs/bash/

**Comment by Pltnorwich** [comment]
I appreciate that Link - will definatley give it a read, i was looking for linux books to understand it more. DOS i could get my head around but thats not used now, haha.

Followed the above commands run as sudo su - 

which node-gyp    returned no output

npm install           output returned        
_/opt/node/bin/node-gyp -> /opt/node/lib/node_modules/node-gyp/bin/node-gyp.js
/opt/node/lib
└── node-gyp@3.5.0_ 

export PATH=$PATH:/opt/node/lib      (do i leave it as opt/node/lib = npm list showed that path, change it to /opt/node/bin/  = as nom install  or  /opt/node/lib/node_modules/node-gyp/bin/

which node-gyp     returned no output - 


i think i have all the information its just picking the right pieces.

Your help is greatly appreciated.

**Comment by gibfahn** [comment]
You want to add the directory that contains the `node-gyp` binary to the PATH, which is what `export PATH=$PATH:/some/path` does.

Okay, so it looks like it is in `/opt/node/bin`, this line:

```bash
/opt/node/bin/node-gyp -> /opt/node/lib/node_modules/node-gyp/bin/node-gyp.js
```

means create a symlink (shortcut) at `/opt/node/bin/node-gyp` which points to `/opt/node/lib/node_modules/node-gyp/bin/node-gyp.js`. So try adding `/opt/node/bin` to your path.

Basically you want to add directories to your root path until `where node-gyp` prints out a path, that tells you bash can now find the node-gyp binary.

```bash
sudo su -
npm install -g node-gyp             # Does nothing if it's already installed
export PATH=$PATH:/opt/node/bin     # Replace /usr/local/lib with the path from npm list
which node-gyp                      # Should show the path to node-gyp
node-gyp BUILDTYPE=Release rebuild  # Don't need sudo cause you're already in a sudo shell
exit                                # Quit
```


Incidentally to format code nicely you do this:

    ```bash
    bash code here
    ```

**Comment by mediaj** [comment]
I found out that this command:

```bash
sudo /opt/node/bin/node-gyp BUILDTYPE=Release rebuild
```

works. I.e.  node-gyp starts doing its thing. I was having the same issue with te 'command not found'-thing.

**Comment by mediaj** [comment]
@gibfahn It seems your commands are doing just that, but it kept throwing me the same error every time.

**Comment by mediaj** [comment]
@gibfahn Although node-gyp says everything was 'ok', I'm still not able to start Homebridge :/ It says in the Installation Guide at this point I should install Homebridge (didn't I already do that?) and then I should be able to just type 'homebridge' to fire things up. But it doesn't work.

**Comment by mediaj** [comment]
In /opt/node/bin is the file homebridge:

```bash

#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');

// Run HomeBridge
require(lib + '/cli')();
```
But apparently this won't startup Homebrigde.

**Comment by mediaj** [comment]
Okay. I think I found the solution. 

After the rebuild of mdns by node-gyp:

```bash
cd /opt/node/bin
node homebridge
```
It will warn you about Avahi and such, but homebridge will start and show a code. I was able to add Homebridge to the Home-app on my iPhone 6.

**Comment by gibfahn** [comment]
@Pltnorwich @mediaj could you do `ls -l /opt/node/bin` for me?

I think the issue might be related to the fact that you're running npm as root, it's not really designed for that, and I'm not sure why it's necessary to do so.

In any event @Pltnorwich you can do what @mediaj suggested:

```bash
cd /opt/node/lib/node_modules/hap-nodejs/node_modules/mdns
sudo /opt/node/bin/node-gyp BUILDTYPE=Release rebuild
```

**Comment by Pltnorwich** [comment]
@gibfahn 

```
sudo su -
npm install -g node-gyp
root@raspberrypi:~# export PATH=$PATH:/opt/node/bin                                                        #added path
root@raspberrypi:~# export PATH=$PATH:/opt/node/lib/node_modules/node-gyp/bin/      #added second path nom install listed
root@raspberrypi:~# which node-gyp                                                                                                          
/opt/node/bin/node-gyp                                                                                                               #return this path
root@raspberrypi:~# cd /opt/node/lib/node_modules/hap-nodejs/node_modules/mdns
root@raspberrypi:/opt/node/lib/node_modules/hap-nodejs/node_modules/mdns# node-gyp BUILDTYPE=Release rebuild                                                                                                         #ran this and showed no errors

home bridge is now running with the same errors at the start as @mediaj - thanks.

Im doing the website you sent as well gibfahn - Thank you for your help and perseverance.

**Comment by Pltnorwich** [comment]
@mediaj - have you added any smart devices to you PI Homebridge, this is now my next task to add my door lock, I believe its about Json files. Be great to know if you have added any none home kit stuff.

**Comment by mediaj** [comment]
@Pltnorwich I added - just for testing purposes - the plugin that shows the temperature of the RPi CPU and a plugin that gives me the current outside temperature (based on OpenWeather). Both work as expected. I can add the Homebridge as a bridge to Homekit and the 'sensors' immediately show up.

Install the plugins according to the instructions and then configure them. Configuration is really easy. 

```bash
cd /home/pi/.homebridge
sudo nano config.js
```

Then copy paste the basic config from Homebridge and add the necesssary config from the plugins. 

Good luck!

**Comment by anandumdas** [comment]
The error happens because the binary you are trying to call from command line is only part of the current user's PATH variable, but not a part of  root user's PATH.

You can verify this by locating the path of the binary you are trying to access. In my case I was trying to call "bettercap-ng". So I ran,

`$ which bettercap-ng`

`output: /home/user/work/bin/bettercap`

I checked whether this location is part of my root user's PATH.

`$ sudo env | grep ^PATH`

output: `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

So sudo cannot find the binary that I am trying to call from commandline. Hence returns the error command not found. 

You can direct sudo to use the current user's PATH when calling a binary like below.

`$ sudo -E env "PATH=$PATH" [command] [arguments]`

In fact, one can make an alias out of it:

`$ alias mysudo='sudo -E env "PATH=$PATH"'`

It's also possible to name the alias itself sudo, replacing the original sudo.

Please refer to [this video][1] for step by step solution


  [1]: https://youtu.be/nTLuTZqQbNI
