### ISSUE TITLE
ARM cross compiling not working

### ISSUE THREAD

**Issue by Hackzzila** [nodejs/node-gyp#1137]
I am trying to cross compile for ARM on ubuntu. It builds successfully, but only 1/5 bindings actually work.
I get errors similar to [this](https://light-theme-hurts.my-ey.es/c22325.png) when trying to use the bindings. I am setting `--arch=arm` and these environment variables (and I have tried more too): 
```
AR: 'arm-linux-gnueabi-ar',
CC: 'arm-linux-gnueabi-gcc',
CXX: 'arm-linux-gnueabi-g++',
LINK: 'arm-linux-gnueabi-g++',
```
I am stumped with this, and the only person I know who knows about this stuff is stuck too. Any help would be appreciated!

**Comment by bnoordhuis** [comment]
Your best bet is to report that to each project individually.  Many native modules assume that host_arch == target_arch, those would need fixes to make cross-compiling work.
