### ISSUE TITLE
binding.gyp not found (cwd: c:\Users\xxxx\xxxx\) while trying to load binding.gyp

### ISSUE THREAD

**Issue by mscherer82** [nodejs/node-gyp#1138]
Why was this issues closed? There is no fix for this but a lot of +1 and a lot opened and unanswered [stackoverflow questions](http://stackoverflow.com/search?q=%22binding.gyp+not+found%22) about this issue! 
Please reopen https://github.com/nodejs/node-gyp/issues/702 and delete this post.

**Comment by bnoordhuis** [comment]
From https://github.com/nodejs/node-gyp/issues/702#issuecomment-134758224:

> Closing since not a node-gyp issue.

The reports in that issue are a mixture of user error and problems with a module that isn't node-gyp.

**Comment by Steviey** [comment]
https://news.ycombinator.com/item?id=6845286

**Comment by bnoordhuis** [comment]
@Steviey Deleted your comment.  Please don't do that again.

**Comment by a3zzat** [comment]
I think it is a very common issue that at least put some restrictions to prevent it from happening
or make the error more verbose and less confusing
