### ISSUE TITLE
npm install express-generator -g 

### ISSUE THREAD

**Issue by MarcioDuran** [nodejs/node-gyp#1143]
Can someone help me ?

npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/node" "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/npm" "install" "express-generator" "-g"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
ubuntu@ubuntu:~$ npm config set prefix ~/npm
ubuntu@ubuntu:~$ npm install express-generator -g 
npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/node" "/home/ubuntu/.nvm/versions/node/v7.7.2/bin/npm" "install" "express-generator" "-g"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by bnoordhuis** [comment]
Wrong bug tracker?  That's an npm issue, not a node-gyp issue.  See if upgrading npm helps.  Good luck.
