### ISSUE TITLE
npm installed failed

### ISSUE THREAD

**Issue by rajkanase** [nodejs/node-gyp#1147]
before few minutes i have installed visual studio. First time i was running it on ripple S emulator.After very long process i got following message & errors in attached screenshot.

npm ERR! Please include the following file with any support request: (TaskId:10)
1>                     npm ERR!     C:\Users\Raj\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\6.1.1\npm-debug.log (TaskId:10)
1>                     [Error ------ npm install failed. Exit code: 1] (TaskId:10)

Attachment is here
![screenshot 27](https://cloud.githubusercontent.com/assets/25950095/24072834/2517ed00-0c13-11e7-83b7-8d760c6bbaf5.png)

**Comment by bnoordhuis** [comment]
I don't know what your issue is but it's not a node-gyp issue.  Try reporting it to the project that you are trying to install.
