### ISSUE TITLE
Failing on rebuild

### ISSUE THREAD

**Issue by Rawnly** [nodejs/node-gyp#1148]
[Here the link](https://travis-ci.org/Rawnly/splash-cli/jobs/205957466) to my travis log.

When installing on Windows or Linux it gives me this error, how can i fix that? Is that a *node-gyp* issue?

Thanks.

**Comment by bnoordhuis** [comment]
Your compiler is too old.  Install g++ >= 4.8 or clang++ >= 3.4 and it should work.
