### ISSUE TITLE
npm install fails on node-gyp rebuild (using puppet)

### ISSUE THREAD

**Issue by glesperance** [nodejs/node-gyp#115]
I'm currently trying to deploy my web app using a puppet script issuing the `npm install`command using my webapp's directory as the CWD. 

All packages but those that depend on **node-gyp** install correctly. 

The strange thing is that when I do`npm install` manually in my app's directory, everything seems to work correctly.  Setting up the PATH or NODE_ENV environment variables does not help. This could be linked to an issue with permissions although the puppet script does run as root so there shouldn't be any problem there. 

Is there anything node-gyp requires to run properly that I should double check? Could npm be somehow dropping the privileges  and causing these errors? 

---

Below are two logs of different packages that failed to build on two different attempts (the second attempt had the _bcrypt_ dep removed out of _package.json_)
#### bcrypt@0.7.0

```
504 info postuninstall bcrypt@0.7.0
505 error bcrypt@0.7.0 install: `node-gyp rebuild`
505 error `sh "-c" "node-gyp rebuild"` failed with 1
506 error Failed at the bcrypt@0.7.0 install script.
506 error This is most likely a problem with the bcrypt package,
506 error not with npm itself.
506 error Tell the author that this fails on your system:
506 error     node-gyp rebuild
506 error You can get their info via:
506 error     npm owner ls bcrypt
506 error There is likely additional logging output above.
507 error System Linux 3.2.0-23-generic
508 error command "nodejs" "/usr/bin/npm" "install"
509 error cwd /usr/local/src/wavo.me
510 error node -v v0.8.4
511 error npm -v 1.1.45
512 error code ELIFECYCLE
513 verbose exit [ 1, true ]
```
#### node-proxy@0.6.0

```
5503 error node-proxy@0.6.0 install: `node-gyp configure build`
5503 error `sh "-c" "node-gyp configure build"` failed with 1
5504 error Failed at the node-proxy@0.6.0 install script.
5504 error This is most likely a problem with the node-proxy package,
5504 error not with npm itself.
5504 error Tell the author that this fails on your system:
5504 error     node-gyp configure build
5504 error You can get their info via:
5504 error     npm owner ls node-proxy
5504 error There is likely additional logging output above.
5505 error System Linux 3.2.0-23-generic
5506 error command "nodejs" "/usr/bin/npm" "install"
5507 error cwd /usr/local/src/wavo.me
5508 error node -v v0.8.4
5509 error npm -v 1.1.45
5510 error code ELIFECYCLE
5511 verbose exit [ 1, true ]
```

**Comment by a0viedo** [comment]
hey @glesperance, it's been long time. is this still an issue?

**Comment by glesperance** [comment]
hey @a0viedo thanks for asking. I dont recall having this problem anymore. Not sure if we ever fixed it either 6 years ago.

Gonna close the issue
