### ISSUE TITLE
How to install the source when there is no network

### ISSUE THREAD

**Issue by lihy87** [nodejs/node-gyp#1154]
the target machine(ubuntu 16.04) has no network, how do i install it in source?

**Comment by bnoordhuis** [comment]
Copy over the source tarball from nodejs.org and pass `--tarball <location>` to node-gyp or npm.

**Comment by lihy87** [comment]
Could you write the detailed steps?

**Comment by bnoordhuis** [comment]
That's really all there is to it.  If anything specific is unclear, let me know and I'll try to clarify.

**Comment by gibfahn** [comment]
>the target machine(ubuntu 16.04) has no network, how do i install it in source?

Are you trying to install `node-gyp` or node itself? Do you just want to `npm install` native modules?

If you've installed node and npm you already have `node-gyp` installed (it's a dependency of npm), you just need the headers.

Assuming you're using node v6.10.1:

Headers are stored in `~/.node-gyp/6.10.1/`, you also need the `installVersion` file. In later versions of node-gyp these files could change, check the contents of `~/.node-gyp`  on a machine with internet access when you run `npm i -g node-gyp && node-gyp configure` and duplicate it.

```bash
curl -O https://nodejs.org/dist/v6.10.1/node-v6.10.1-headers.tar.gz # on a computer with internet
# Copy header tarball to offline machine
mkdir -p  ~/.node-gyp/6.10.1
tar -xf node-v6.10.1-headers.tar.gz --directory ~/.node-gyp/6.10.1/ --strip-components 1
echo 9 >~/.node-gyp/6.10.1/installVersion
```

This should be enough for the common use case, if you need something more specific please provide some actual information about what you want to do.

**Comment by bdharrington7** [comment]
Not sure if this is related or not, but I have a dependency (better-sqlite3) that has a compilation step that uses node-gyp to compile. For reasons I don't quite [understand](https://github.com/nodejs/node-gyp/issues/1247), the header files are downloaded when this compilation phase is kicked off for the first time. When this module is compiled, a folder is created at `$HOME/.node-gyp` that contains the header files that are downloaded, and includes a `installVersion` file containing the number `9` only. 

When I run `npm install -g node-gyp && node-gyp ./tarball.tar.gz`, this folder doesn't show up at all. I've also tried `npm install --tarball ./tarball.tar.gz` and `node-gyp --tarball ./tarball.tar.gz`

node v8.1.2
npm v5.0.3

**Comment by bnoordhuis** [comment]
@bdharrington7 The tarball that node-gyp downloads contains the node.js SDK ([this file](https://nodejs.org/dist/v8.1.3/node-v8.1.3-headers.tar.gz)), it's not related to the tarball that npm downloads from its registry when you install a package.

If you download the SDK tarball manually, invoke node-gyp like this from inside the directory that contains the add-on you want to build (with a binding.gyp in it):
```
$ node-gyp --tarball /path/to/node-x.y.z-headers.tar.gz rebuild
```

**Comment by bdharrington7** [comment]
The issue I'm trying to solve for is that the directory that contains the add-on I want to build doesn't exist at the time I want to install the headers. I'm trying to preemptively provide these headers in the expected location so that when `npm install` is run, it doesn't try to go out and fetch the headers. 

A little more insight on the problem: I'm trying to create a development environment in Docker that works offline. As such, since the `npm install` layer is re-built when something in `package.json` changes, the installation of the `node-gyp` headers is no longer present in the expected location, and is subsequently re-downloaded.

**Comment by bnoordhuis** [comment]
`node-gyp install` will do that for you; `node-gyp install --ensure` to only download them when not already present.

**Comment by gibfahn** [comment]
>`node-gyp install` will do that for you; `node-gyp install --ensure` to only download them when not already present.

`--ensure` is on by default unless you're using `--tarball` IIRC

_**EDIT:**_ [lib/configure.js#L77](https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L77)

**Comment by abhagupta** [comment]
@bdharrington7  did you get past this problem in your docker container?

**Comment by bdharrington7** [comment]
Yeah, I download and place the header files like this, but you’ll have to figure out where to get the binary, I’m getting them from an internal repo.

```
ENV NODE_VERSION v8.9.4
ENV NODE_FILENAME node-${NODE_VERSION}-linux-x64.tar.gz
ENV NODE_URL https://${SOMEREPO}.com/node-distributions/${NODE_VERSION}/${NODE_FILENAME}

RUN wget -nv "${NODE_URL}" -O "/tmp/${NODE_FILENAME}" && \
    tar xf "/tmp/${NODE_FILENAME}" -C /usr/local/ --strip=1 && \
    rm "/tmp/${NODE_FILENAME}"
```

**Comment by abhagupta** [comment]
How did you do the `npm install` to make sure your dependencies are loading `node-gyp` without needing internet connection?

**Comment by bdharrington7** [comment]
I store my dependencies in source control (the non-compiled ones) so I turn off WiFi and run `npm rebuild`

**Comment by nickboldt** [comment]
Simpler solution in https://github.com/nodejs/node-gyp/issues/1133#issuecomment-538767799:

```
NODE_VER=v10.14.1
curl -sSL https://nodejs.org/download/release/${NODE_VER}/node-${NODE_VER}-headers.tar.gz \
        -o /tmp/node-headers.tgz; \
npm config set tarball /tmp/node-headers.tgz
```

**Comment by DJViking** [comment]
This should not be closed. The `--nodedir` is a workaround, not a proper solution to the problem.

A proper solution would be to fix node-gyp with an URL in `.npmrc` where to retrieve the node-headers archive.
This solution works for others like we use.
```
chromedriver_cdnurl=https://nexus.company.com/javascript/chromedriver
phantomjs_cdnurl=https://nexus.company.com/javascript/
sass_binary_site=https://nexus.company.com/javascript/node-sass
```

The node-gyp could have something like this, to avoid going out on the Internet to retrieve the node headers.

**Comment by Maxim-Mazurok** [comment]
Windows users, beware:
As mentioned [here](https://stackoverflow.com/a/69020434/4536543), 
> on Windows `--tarball` is useless because node-gyp subsequently wants to download the node.lib file

**Comment by NexZhu** [comment]
`npm conifg set tarball` is no longer working for Node.js 19.3.0 and npm 9.2.0
```
[root@Nogard baas]# npm config set tarball /tmp/headers.tar
npm ERR! `tarball` is not a valid npm option

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-26T15_23_07_615Z-debug-0.log
```

Anyone know any alternative solution?

**Comment by cclauss** [comment]
[`export GYP_TARBALL=/node/node-headers.tar.gz`](https://github.com/nodejs/node-gyp/issues/2800#issuecomment-1571376531)

**Comment by pcurrivan** [comment]
GYP_TARBALL does not work with Node v18.16.1 and NPM v9.3.1.  gyp still tries to download the headers from nodejs.org:
`gyp http GET https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz`

**Comment by robingood556** [comment]
@pcurrivan did you solved this problem?

**Comment by chj-damon** [comment]
@pcurrivan have you solved this problem?

**Comment by robingood556** [comment]
@chj-damon i solved my problem using env var - NODEJS_ORG_MIRROR

**Comment by chj-damon** [comment]
@robingood556 can you share how you did it? thanks

**Comment by robingood556** [comment]
@chj-damon add ENV in my Dockerfile

**Comment by pcurrivan** [comment]
It seems like the tarball NPM option does actually still work, you just can't set it with "npm config set",  Adding it manually to .npmrc or using the env var npm_config_tarball seems to still work.
