### ISSUE TITLE
Unable to install node_gyp

### ISSUE THREAD

**Issue by spiotr12** [nodejs/node-gyp#1159]
npm install node_gyp -g returns 404 error

After I wnt to the site:
https://registry.npmjs.org/node_gyp
It is empty, or an empty JSON is there

**Comment by spiotr12** [comment]
same for node_pre_gyp

**Comment by gibfahn** [comment]
Try: https://registry.npmjs.org/node-gyp

**Comment by gibfahn** [comment]
I'll close this, let me know if this doesn't resolve your issue and I can reopen.

**Comment by spiotr12** [comment]
my bad, I misplaced `-` with `_`
