### ISSUE TITLE
Apple LLVM 8.1 breaks node-gyp?

### ISSUE THREAD

**Issue by kessiler** [nodejs/node-gyp#1160]
Today's apple update for LLVM 8.1 seems to break node-gyp. 

```
/Users/kessilerrodrigues/.node-gyp/0.12.18/include/node/v8.h:5800:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
  return Handle<T>(reinterpret_cast<T*>(HandleScope::CreateHandle(
                                        ~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/kessilerrodrigues/.node-gyp/0.12.18/include/node/v8.h:820:29: note: declared protected here
  static internal::Object** CreateHandle(internal::Isolate* isolate,
```

Apple LLVM version 8.1.0 (clang-802.0.38)

**Comment by bnoordhuis** [comment]
You're probably out of luck.  v0.12.18 is out of support, nothing can be done about that.  Try upgrading to node.js v4.x or newer.

**Comment by kessiler** [comment]
:(

**Comment by Thoro** [comment]
@kessiler Just move the definition of CreateHandle in the .h file from the protected to the public definition - that should fix the build error!

**Comment by DannyJoris** [comment]
@Thoro that worked, thanks!

**Comment by jainmonica** [comment]
@Thoro Thanks for the tip, this really worked

**Comment by pedrosanta** [comment]
@kessiler also struggling with this very issue, trying to install `livedb`/`hiredis` on `0.12`. 😕 I think it will just speed up the planned maintenance for this.

**Comment by andrewhine** [comment]
For those who are not familiar with .h files, you need to move:

`    static internal::Object** CreateHandle(internal::Isolate* isolate,
                                           internal::Object* value);`

from under 

> protected:

to under

> public:

Around line 820 in 

> v8/include/v8.h
