### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by smersh2009** [nodejs/node-gyp#1161]
../src/png.cpp: In static member function ‘static void Png::PngEncodeAsync(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/png.cpp:264:76: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
     Local<Value> buf_val = Local<Object>::New(isolate, png->persistent())->GetHiddenValue(Str
                                                                            ^
png.target.mk:93: recipe for target 'Release/obj.target/png/src/png.o' failed
make[2]: *** [Release/obj.target/png/src/png.o] Error 1
make[2]: Leaving directory '/home/server/moloch/viewer/node_modules/png/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-63-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/server/moloch/viewer/node_modules/png
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! png@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png@3.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs png
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-03-30T18_01_46_786Z-debug.log
Makefile:11: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/server/moloch/viewer'
Makefile:322: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by bnoordhuis** [comment]
That's a problem with the module you are trying to install, png, not with node-gyp.
