### ISSUE TITLE
NPM install fails for node-gyp

### ISSUE THREAD

**Issue by arumugamshanmugam** [nodejs/node-gyp#1163]
Hi,  
When i tried to install dependencies by npm install im getting the following error

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Roaming\npm\nod
e_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData
\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "bu
ild" "--fallback-to-build" "--module=C:\\Users\\User\\Documents\\milkyway\\src\\
app\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v48-win32-x64\\debug.nod
e" "--module_name=debug" "--module_path=C:\\Users\\User\\Documents\\milkyway\\sr
c\\app\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\User\Documents\milkyway\src\app\node_modules\v8-debug
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=C:\Users\User\Documents\milkyway\src\app\node_modules\v8-debug
\build\debug\v0.4.6\node-v48-win32-x64\debug.node --module_name=debug --module_p
ath=C:\Users\User\Documents\milkyway\src\app\node_modules\v8-debug\build\debug\v
0.4.6\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\User\Documents
\milkyway\src\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User
\\Documents\\milkyway\\src\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\User\Documents\milkyway\src\app\node_modules\v8-d
ebug
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\User
\Documents\milkyway\src\app\node_modules\v8-debug\build\debug\v0.4.6\node-v48-wi
n32-x64\debug.node --module_name=debug --module_path=C:\Users\User\Documents\mil
kyway\src\app\node_modules\v8-debug\build\debug\v0.4.6\node-v48-win32-x64' (1)
marfcat@1.0.0 C:\Users\User\Documents\milkyway\src\app
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment]
> this is most likely a problem with the v8-debug package

I.e., not a node-gyp problem.  Try reporting it to that project although I suspect they're going to tell you to upgrade because the latest version is 1.0.1, not 0.4.6.
