### ISSUE TITLE
When NodeJS is down, it fails node-gyp installation.

### ISSUE THREAD

**Issue by thalesfsp** [nodejs/node-gyp#1165]
Versions: 

- Node: `7.5.0`
- NPM: `4.1.2`
- node-gyp: `3.4.0`

Stack:

```
> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.10.1/node-v6.10.1-headers.tar.gz
gyp http 522 https://nodejs.org/download/release/v6.10.1/node-v6.10.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response downloading https://nodejs.org/download/release/v6.10.1/node-v6.10.1-headers.tar.gz
```

![unspecified](https://cloud.githubusercontent.com/assets/750360/24682835/a182297e-1950-11e7-8e42-8f301761eacc.png)

Saved by `NODEJS_ORG_MIRROR` pointing out to `https://cnpmjs.org/mirrors/node`

Proposed solutions:
- Automatic fallback to X, Y or Z mirrors if `https://nodejs.org` isn't available
- Follow redirections
- Updated README/documentation with a list of ENV VARS, with examples

**Comment by richardlau** [comment]
https://github.com/nodejs/nodejs.org/issues/1191

**Comment by thalesfsp** [comment]
@richardlau Updated issue

**Comment by WayneUong** [comment]
It would be nice to have a fall-back mirror link in case node is down again.

**Comment by richardlau** [comment]
Can you try pointing `NODEJS_ORG_MIRROR` to `https://cnpmjs.org/mirrors/node` instead of `https://cnpmjs.org/mirrors/node/latest-v6.x/node-v6.10.1-headers.tar.gz`?

**Comment by dimko** [comment]
@thalesfsp change the NODEJS_ORG_MIRROR variable to just https://cnpmjs.org/mirrors/node

**Comment by thalesfsp** [comment]
@richardlau @dimko Worked! I updated again, the issue.

**Comment by sferoze** [comment]
I am trying to deploy my Meteor app and cannot because of this issue. And I really need to deploy an update. I am not sure in Meteor if I can change NODEJS_ORG_MIRROR... any clue how?

**Comment by bnoordhuis** [comment]
Closing, should be working again.
