### ISSUE TITLE
Update default MSBuild version.

### ISSUE THREAD

**Issue by MicahZoltu** [nodejs/node-gyp#1173]
Someone feel free to correct me if I am wrong here but I believe MSBuild 2.0 was released with .NET 2.0 which was around 2005 and end-of-lifed in 2011.  MSBuild 4.0 I believe came out with .NET 4.0 and was released in ~2010.  It is now 2017 and from what I can tell, node-gyp is still defaulting to MSBuild 2.0.  In order to work on any modern system users have to do something along the lines of `yarn config set msvs_version 2015 --global`, the npm equivalent, or set an environment variable.

Seeing as how Microsoft end-of-lifed MSBuild 2.0 and they tend to be _really_ cautious about end-of-lifing products I think it is safe to bump the default version of MSBuild that node-gyp uses to something more modern.  I _think_ that MSBuild 4.0 is also end-of-lifed (last year) so the default should at the _least_ be MSBuild 14.  My recommendation would be to have the default be the most recent stable release of the product, which I _think_ is [15](https://github.com/Microsoft/msbuild/releases).  At the least, v15 is the easiest version to get a hold of these days as it comes packaged with dotnet CLI and and the current retail release of Visual Studio.

**Comment by bnoordhuis** [comment]
node-gyp (well, actually GYP) tries to auto-detect the VS version (and thus msbuild.)  In a perfect world, you would never need to specify msvs_version.

I suppose we can raise the fallback default but since we still nominally support node.js v0.10 and v1.x, we probably can't go further than VS 2008 or VS 2010 which probably doesn't help very much.

**Comment by MicahZoltu** [comment]
Ah, so it sounds like the problem here is that GYP is detecting VS version, not MSBuild version.  Since users can easily get build tools without VS these days, perhaps another improvement would be making the version detection system support systems without VS.

**Comment by bnoordhuis** [comment]
It kind of does, it's also able to auto-detect the Windows SDK.  Whether that also covers Build Tools, I don't know.  The recent VS 2017 support works different still, it's COM- rather than registry-based.
