### ISSUE TITLE
Doesn't respect no_proxy

### ISSUE THREAD

**Issue by ballwood** [nodejs/node-gyp#1175]
Hi,

Seems from my testing at work that node-gyp doesn't respect the no_proxy environmental variable. Would it be alright if I did a pull request to support this?

**Comment by bnoordhuis** [comment]
Depends on how complex it gets.  The logic is in lib/install.js.

**Comment by ballwood** [comment]
@bnoordhuis https://github.com/nodejs/node-gyp/pull/1176 if you could advise on how to handle the unit/integration tests I'll see if I can do them.

**Comment by bnoordhuis** [comment]
@ballwood You can add the functions to the `module.exports.test` declaration at the top so you can test them in isolation in unit tests.

**Comment by rvagg** [comment]
I'd support a NO_PROXY (as a rule I think I'm OK with being consistent with [curl](ENVIRONMENT VARIABLES) on env vars. But this needs a pull request to move forward.

**Comment by rvagg** [comment]
Ahh #1176 is there, I'll get to that soon hopefully.
