### ISSUE TITLE
npm install with optional node-gyp rebuild

### ISSUE THREAD

**Issue by jorangreef** [nodejs/node-gyp#1177]
I am writing a module which has a native binding which is built by default but not required.

I would like `npm install` to work even if the native binding cannot be compiled because the `node-gyp rebuild` step fails. This might be because the user is installing the module on a platform which only has node and npm installed and no support for building native addons.

What would be the best way of allowing the user to run `npm install`, building the native binding if possible, but not failing if that is not possible?

**Comment by bnoordhuis** [comment]
Add a `"install": "node install.js"` rule to your package.json and invoke node-gyp from the script if you need fancy, or `"install": "node-gyp rebuild || exit 0"` if you don't.  The latter still prints the build error, which may confuse your users.

**Comment by jorangreef** [comment]
Thanks.
