### ISSUE TITLE
Support moving the ~/.node-gyp/ directory

### ISSUE THREAD

**Issue by evaryont** [nodejs/node-gyp#1180]
I'm on a mission to clean up my home directory. Or, at least, the top level. Part of it is minimizing the number of hidden dotfiles.

It would be appreciated if node-gyp supported using an environment variable to override the path to the devdir, complementing the current `--devdir` argument.

**Comment by bnoordhuis** [comment]
It already does (or should): `npm_config_devdir` - that's how node-gyp normally inherits config settings from npm.

**Comment by evaryont** [comment]
Ah! I did not grok the source code well enough to catch that. It would be nice if it was called out more explicitly.

**Comment by bnoordhuis** [comment]
I wouldn't object to a pull request that adds a blurb to the README.
