### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by lishihui0613** [nodejs/node-gyp#1184]
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  hello.cc
..\hello.cc : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 [E:\app\build\addon.vcxproj]
..\hello.cc(5): fatal error C1083: 无法打开包括文件: “UsbDevInterface.h”: No such file or directory [E:\app\build\addon.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd E:\app
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

**Comment by refack** [comment]
@lishihui0613 this is an addon you are writing yourself? It seems like "UsbDevInterface.h" is not in your library path. You could tell `GYP` where it is in the `addon.gyp` file. Here's a link to the GYP manual https://gyp.gsrc.io/docs/UserDocumentation.md

**Comment by bnoordhuis** [comment]
No follow-up, closing.
