### ISSUE TITLE
gyp configure error

### ISSUE THREAD

**Issue by KhaleelAzmiAlhalaseh** [nodejs/node-gyp#1190]
![error for github](https://cloud.githubusercontent.com/assets/25429490/25677752/da34fa42-304f-11e7-983b-54efc6faf7b3.PNG)
any help please? 

i followed this https://github.com/nodejs/node-gyp but im stuck 

i need help please !!!!!

**Comment by addaleax** [comment]
You need to run `node-gyp configure` in the directory in which the project you are trying to build is (i.e. where a `binding.gyp` file is, that’s what the error message here complains about).

This is not a bug, and not a problem with node-gyp itself, so I’m closing this, and I would suggest to re-open this as an issue on [nodejs/help](https://github.com/nodejs/help) instead (but please try to give a bit more information about what you’re trying to do).
