### ISSUE TITLE
nodejs 'make install'ed headers are ignored

### ISSUE THREAD

**Issue by soulne4ny** [nodejs/node-gyp#1191]
node's build process installs headers in `{prefix}/include/node` when running `make install`, but node-gyp install does download its own copy almost the same. One of them is just an useless extra.

And `./configure`d headers are better tailored for the local environment usually.

**Comment by bnoordhuis** [comment]
You can point it to the local headers with the `--nodedir` switch.  node-gyp is not and cannot be made aware of them (reliably.)

> And ./configured headers are better tailored for the local environment usually.

Not with node, it doesn't matter whether it uses the local ones or the downloaded ones.

**Comment by soulne4ny** [comment]
Neither npm nor yarn know anything about `--nodedir`.

**Comment by gibfahn** [comment]
>Neither npm nor yarn know anything about `--nodedir`.

npm (and I assume yarn) pass on any arguments they don't understand to whatever they spawn, in this case `node-gyp`.

**Comment by soulne4ny** [comment]
10x
Crazy, Rather unexpected.
Then, hypothetically, if npm would spawn 2 different commands echo requiring different command line flags during one run, both of them should break because it is usually what commands do with unknown flags...

**Comment by gibfahn** [comment]
>Then, hypothetically, if npm would spawn 2 different commands echo requiring different command line flags during one run,

Maybe, I've never heard of that being an issue, but if you want to avoid it just set the environment variable or the `npm config` value (see https://github.com/nodejs/node-gyp/pull/1185 for docs):

```bash
export npm_config_nodedir=/path/to/headers
# Or:
npm config set nodedir /path/to/headers
```

**Comment by soulne4ny** [comment]
> export npm_config_nodedir=/path/to/headers
👍

**Comment by cor** [comment]
FYI: When we build this with `nix`, using `nix-npm-buildpackage`'s `buildNpmPackage` we only faced this issue on `aarch64` machines.
