### ISSUE TITLE
node-gyp Unresolved Sxternal Symbol Error

### ISSUE THREAD

**Issue by Pecacheu** [nodejs/node-gyp#1194]
I'm trying to make a native module that uses DirectX for some of it's functionality, but I get this error when I try to `node-gyp build`:
```
main.obj : error LNK2001: unresolved external symbol Direct3DCreate9
```
I'm including d3d9.h in my c++ file. Is there something I'm doing wrong?

**Comment by refack** [comment]
Since it's a link error, my first guess is you're not including the `.lib` file that actually defines `Direct3DCreate9` in the `libraries` clause of your `.gyp`
from https://msdn.microsoft.com/en-us/library/windows/desktop/bb219685(v=vs.85).aspx
```
Requirements

Header: D3D9.h
Library: D3d9.lib
DLL: D3d9.dll
```

**Comment by bnoordhuis** [comment]
Answered and not a node-gyp issue in the first place, so I'll close.

**Comment by refack** [comment]
> node-gyp issue in the first place, so I'll close.

@bnoordhuis Is there a good place for `node-gyp` support we can redirect people with such questions?

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/help/issues - but if it's an issue with a specific module, people should report it there.

**Comment by Pecacheu** [comment]
Okay,
a. I don't know where D3D9.lib is, although I finally found D3D9.dll in Windows/System32, but more importantly...
b. How on earth do you include them in `node-gyp`. I can't find any documentation. Whenever I google for node-gyp help, I only get unofficial tutorials, and there doesn't seem to be any written on this topic.

I know how to include Windows dll's and lib's in Visual Studio. Basically just open the right menu (which is a bit hard to find, but whatever) and select the ones you want. Obviously it doesn't work like that with node-gyp, so I'm stuck.

**Comment by refack** [comment]
As @bnoordhuis suggested, since this is a "usage" problem and not a direct bug in `node-gyp`, open an issue there and I'll give you some tips

[Reasoning]
This is not just a whim, on the one hand we want this issue board to reflect actual "bugs" in `node-gyp`, and on the other hand we want [`nodejs/help`](https://github.com/nodejs/help/issues) to be the knowledge base for "how to use" the products in the nodejs org.
