### ISSUE TITLE
Error running npm-install

### ISSUE THREAD

**Issue by im1dermike** [nodejs/node-gyp#1195]
Today, I started getting errors when running npm install for my web application.  I seem to have traced it to npm-gyp.  Here is what I get when I try to install it:

```
$ npm install node-gyp@3.6.1

> microtime@2.1.3 install C:\Development\node_modules\microtime
> node-gyp rebuild


C:\Development\node_modules\microtime>if not defined npm_config_node_gyp (node "C:\Users\me\AppData\Roaming\npm\node_modules\n                                                                                                       pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re                                                                                                       build"
gyp ERR! cwd C:\Development\node_modules\microtime
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Advaxis.Norm.Web@0.0.0 C:\Development\Advaxis\Advaxis.norm\Advaxis.Norm.web
+-- UNMET PEER DEPENDENCY @angular/common@2.4.10
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.10
+-- UNMET PEER DEPENDENCY @angular/core@2.4.10
+-- node-gyp@3.6.1
+-- UNMET PEER DEPENDENCY rxjs@5.4.0
`-- UNMET PEER DEPENDENCY zone.js@0.7.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angular2-toaster@3.0.1 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN angular2-toaster@3.0.1 requires a peer of @angular/compiler@^4.0.0 but none was installed.
npm WARN angular2-toaster@3.0.1 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of rxjs@~5.0.0-beta.12 but none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN Advaxis.Norm.Web@0.0.0 No description
npm WARN Advaxis.Norm.Web@0.0.0 No repository field.
npm WARN Advaxis.Norm.Web@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: microtime@2.1.3 (node_modules\microtime):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: microtime@2.1.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by mercurjl** [comment]
+1

**Comment by gabrielgomez522** [comment]
+1

**Comment by ukphillips** [comment]
This has brought our dev team to a halt. When trying to install microtime directly which is kicking off the node-gyp rebuild here is the error(s) I get: 

 C:\Users\k_phillips\test  (test@0.0.0)
 npm install microtime@2.1.3

 microtime@2.1.3 install C:\Users\k_phillips\test\node_modules\microtime
 node-gyp rebuild


C:\Users\k_phillips\test\node_modules\microtime>if not defined npm_config_node_gyp (node "C:\Users\k_phillips\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\k_phillips\test\node_modules\microtime\build\microtime.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\k_phillips\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\k_phillips\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\k_phillips\test\node_modules\microtime
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of rxjs@~5.0.0-beta.12 but none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN test@0.0.0 No description
npm WARN test@0.0.0 No repository field.
npm WARN test@0.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\k_phillips\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "microtime@2.1.3"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! microtime@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@2.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs microtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\k_phillips\AppData\Roaming\npm-cache\_logs\2017-05-11T17_59_58_211Z-debug.log

**Comment by im1dermike** [comment]
@ukphillips That is where I actually started with this.  This has been a huge time waste for my team too.  https://github.com/wadey/node-microtime/issues/49

**Comment by skkonstantin** [comment]
I'm using windows, after the steps described here https://github.com/nodejs/node-gyp#installation, the error was gone

**Comment by ukphillips** [comment]
@im1dermike I just noticed that - I am now where you are. VERY frustrating that this has all blown up without a single change to any of our code. All I can assume is a package somewhere in the dependency chain change that has caused this mess.

**Comment by im1dermike** [comment]
@ukphillips NPM's biggest issue IMO.  I'm thinking that changing my package.json file to exclude the `^`  prefix to packages so it won't be affected by issues like this with new versions would be smart.

**Comment by vikshv** [comment]
+1

**Comment by ukphillips** [comment]
Is this the same issue? The symptom sounds the same [https://github.com/nodejs/node-gyp/issues/1144](url)

**Comment by im1dermike** [comment]
@skkonstantin Which steps did you follow?  I ran `npm install --global --production windows-build-tools` and still have the issue.

**Comment by skkonstantin** [comment]
@im1dermike , I did the same thing, with administrator root . i think this error came after OS update

**Comment by gibfahn** [comment]
@nodejs/platform-windows any ideas? Looks like the original issue is 

```
File "C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
```

which is indeed the same as https://github.com/nodejs/node-gyp/issues/1144. (so cc/ @refack )

**Comment by im1dermike** [comment]
It looks like someone (the author of pdbdf2?) has fixed it.  https://github.com/wadey/node-microtime/issues/49.  I just blew out my node_modules folder and ran `npm install` and it looks like it worked!

**Comment by gibfahn** [comment]
>It looks like someone (the author of pdbdf2?) has fixed it. wadey/node-microtime#49. I just blew out my node_modules folder and ran npm install and it looks like it worked!

So a native module was added to the `dependencies`, and now it's been removed again. FWIW it sounds like you can't install any native modules, so the issue is still there.

**Comment by refack** [comment]
Not 1144, there the error is `KeyError: '2017'`

@im1dermike 's error has this in log: `node-gyp -v v3.4.0`
@ukphillips last log shows also old node-gyp: `node-gyp -v v3.5.0`

First thing to try is to update `npm` or just `node-gyp`

**Comment by refack** [comment]
For posterity doing
`npm install node-gyp@3.6.1`
or even 
`npm i -g node-gyp@3.6.1`
Is not sufficient, since when triggering the build on native Addon via `npm i` `npm` will use it's own version of `node-gyp`, so if you want to use Visual Studio 2017, you'll need to update `npm` to a version >= `4.5.0`

**Comment by skynode** [comment]
Found out that `npm` was using `node-gyp@3.5.0` while running `npm i`. But `node-gyp -v` yields v3.6.1. 
I went into the npm folder, `/Program Files (x86)/.../npm` and ran `npm i --save node-gyp@3.6.1` to bring `node-gyp` up to date with my global install. 

Errors remains *(SelectVisualStudioVersion...)*. Version change reflected in same error stack trace.

**Comment by skynode** [comment]
Forgot to mention, I'm running `npm@4.2.0` and `node@7.10.0`. 

And `SelectVisualStudioVersion​` is same error as `KeyError: '2017'`.

**Comment by refack** [comment]
First make sure you see
```
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
```
In the error output.

If you do: look at #1179 

Else: do the npm upgrade dance - https://docs.npmjs.com/getting-started/installing-node
`npm install npm@latest -g`

**Comment by tuespetre** [comment]
@refack I ran into this issue today and I've seen that some others have been befuddled by it as well, with seemingly no resolution. I found out something and wanted to share it in case anyone else finds it useful.

Here: https://github.com/nodejs/node-gyp/blob/v3.6.2/lib/find-vs2017.js#L17

I changed that to `log.warn` instead of `log.silly` just so I could see what was coming out, and I see a pretty JSON object like I should... except before the pretty JSON object, I have a pesky `WARNING: Could not find ssh-agent` thanks to posh-git. Looking up and taking care of that issue resolved this issue for me.

**Comment by refack** [comment]
@tuespetre Just FYI, you can make npm log at `silly` level with `npm -ddd i`.

So I'm assuming `posh-git` in your PS profile script tried to autorun and fails, so I'll add `-NoProfile` to https://github.com/nodejs/node-gyp/blob/b5b52f7bffb55064a623e2478252a8939259cf3f/lib/find-vs2017.js#L9-L11

**Comment by tuespetre** [comment]
@refack I did `--loglevel=silly` and for some reason I did get a ton of those logs but not the ones I was hoping to see from that. Only reason 😛

**Comment by refack** [comment]
> I did --loglevel=silly and for some reason I did get a ton of those logs but not the ones I was hoping to see from that. Only reason 😛

Well it is called `silly` 🤷‍♂️ 
Refs: https://github.com/dahlbyk/posh-git/pull/484

**Comment by refack** [comment]
Cross-ref: https://github.com/nodejs/node-gyp/pull/1292

**Comment by refack** [comment]
@tuespetre FYI, @dahlbyk landed a fix in `posh-git` and we landed a fix here (but it still needs to get into a release, then be picked-up by `npm`)

**Comment by paulprendergast** [comment]
Has this been fixed? 

C:\electronDevelopment\chap5\exampleEdge2>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.2.1/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v8.2.1/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.2.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v8.2.1/win-x86/node.lib
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Paulp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\electronDevelopment\\chap5\\exampleEdge2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Paulp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Paulp\\.node-gyp\\8.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Paulp\\.node-gyp\\8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Paulp\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Paulp\\.node-gyp\\8.2.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\electronDevelopment\\chap5\\exampleEdge2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\electronDevelopment\\chap5\\exampleEdge2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\electronDevelopment\chap5\exampleEdge2) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Paulp\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Paulp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\electronDevelopment\chap5\exampleEdge2
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by refack** [comment]
@paulprendergast is seems like your folder `C:\electronDevelopment\chap5\exampleEdge2` does not have a `binding.gyp` file.

**Comment by paulprendergast** [comment]
Has this been resolved? if it has been resolved can you directed to page and location on page or give me direct feedback

versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017' 

attached are my logs
[KeyError2017.pdf](https://github.com/nodejs/node-gyp/files/1447101/KeyError2017.pdf)

I have tried this with
electron-edge-js
electron-edge
electron 1.7.9

 it seems to be with node-gyp.
I can node-gyp build at the root at electron-edge-js and electron-edge but when i try under \tools\build.bat release 7.9.0

electron-edge-js
supports Electron 1.7.x - Node.js v7.9.0.

electron-edge
Supports Electron 1.7.x - Node.js v7.9.0.

My Computer:
Win10
VS2015
Python=2.7.9
angularCLI =latest

Environment Vars: 
GYP_MSVS_VERSION= 2015

**Comment by filston2006** [comment]
run this command : meteor npm install --save @babel/runtime 
All errors will disappear! Magic!!!

**Comment by montaro** [comment]
After trying for many days, I found that my problem is that the nodejs aerospike client uses node-gyp for building, and the client depends on `libss-dev` which was not installed on the box I use (VSTS Linux Build Agent).

I added the repo and installed the package before running the `npm install`:
```
add-apt-repository 'deb http://security.ubuntu.com/ubuntu xenial-security main'
sudo apt update
sudo apt install g++ libssl1.0.0 libssl-dev
```

**Comment by Maheshg232** [comment]
> heapdump@0.3.9 install C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump
> node-gyp rebuild


C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 (node_modules\appium\node_modules\heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ appium@1.8.0
updated 1 package in 32.944s

C:\Users\Lenovo>np

**Comment by Maheshg232** [comment]
how to solve this
for which mistack  this error  will come

**Comment by zeiontic** [comment]
this is bullshit

**Comment by NitroBAY** [comment]
Refack's solution saved me after I wasted days with this issue. Try to UPDATE NPM (`npm install -g npm`) that's crazy how many days I lost because of that. Couldn't you check that and advice us to do that somewhere (when the package fails maybe and in the readme). Anyway thanks @refack.
Everything has broken when I update my OS. I reinstalled everything from node to meteor but also all packages deleted node-gyp, reinstalled node-gyp, every tools required via every possible way and did one thousand other things

**Comment by DigaoParceiro** [comment]
@NitroBAY Thank you!!! `npm install -g npm` solved!

**Comment by MatviiStelmakh** [comment]
only this option helped https://github.com/nodejs/node-gyp#option-2

**Comment by Seb33300** [comment]
Be careful, You have to use Python 2.7 (and not 3.7 which is the current latest version).

**Comment by hadimsamir** [comment]
npm install --global --production windows-build-tools .. work well . Thank you.

**Comment by fjh1997** [comment]
after install tools 
```
npm install --global --production windows-build-tools
```
You need to set new python path  in environment-variable PATH. be sure not to install different version of python.

**Comment by AbdelAbdelAli** [comment]
whene i run this command ::::: npm i --s firebase @angular/fire
i get this error :;:
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\saado\Desktop\Angular-Crud\AngularFirestore\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\saado\Desktop\Angular-Crud\AngularFirestore\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

**Comment by myxomor** [comment]
I had installing `windows-building-tools ` , python2.7 and the error still occurred.
But after updating npm with `npm i -g npm` , installing gone done!!!

**Comment by machouz** [comment]
On Mac OS doing :
      `nvm install 10.13.0
       nvm use 10.13.0`
solved for me the problem.

**Comment by darrensapalo** [comment]
On Windows, what I did to fix it were the following:

1. Download the [latest Node installer](https://nodejs.org/en/download/) for Windows.
2. Install it.
3. _At this point, the `node-gyp` issue is still not resolved._
2. Go to my `C:\Users\MY_USERNAME\AppData\Roaming`.
3. Delete the `npm` folder.
4. Run the same installer in step 1, to repair missing files, registry settings.
5. Once finished, `npm install -g npm`.

**Comment by xuantjen410** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crud@0.0.0 start: `concurrently "ng serve --proxy-config proxy.conf.json" "json-server --watch db.json --routes routes.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crud@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2020-04-29T00_57_00_039Z-debug.log

--------------------------------
Can you help me ??

**Comment by Sjos12** [comment]
From the [node-gyp docs](https://github.com/nodejs/node-gyp)

These are the steps if you are on Windows to solve the issue

1. Download latest python version (If you're getting issues try python 2.7) 
2. Download latest MSVS [here](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)
3. Install just the build tools or install the entire Visual Studio installation using the **"Desktop development with C++" workload**
4. Go to your project folder and run `npm config set msvs_version {{ version of msvs you installed }}`. So if you installed the 2019 edition the command would be `npm config set msvs_version 2019`. 
5. Finally run `npm install -g node-gyp` and it should work!
