### ISSUE TITLE
node-gyp is not recognized as an internal or external command

### ISSUE THREAD

**Issue by dauledk** [nodejs/node-gyp#1196]
After running: npm install --global --production windows-build-tools
I try to run the following command: node-gyp --python C:\Python27\python27 and then get the following message: 
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by refack** [comment]
Hello @dauledk 
you have two way to trigger `node-gyp`:
1. If the addon is ready (i.e. has a `binding.gyp` file) you just just run `npm i`
2. If you want to explicitly run `node-gyp` you'll need to install it as a global module with `npm i -g node-gyp`

*note*: https://github.com/nodejs/node-gyp/issues/1195#issuecomment-300888406 - `npm` has it's own version locked copy of the `node-gyp` module.

*note2*: if your `python` is in your path you don't need the `--python C:\Python27\python27` flag

**Comment by Fusseldieb** [comment]
For whatever reason, at least for me, deleting .node-modules and doing "npm install" again did the trick

**Comment by firaszoghlami** [comment]
1.Delete .node-modules
2.npm cache clean
3. npm install
i had the same issue as you and it work for me!
