### ISSUE TITLE
node-gyp fails to install on Mac Sierra

### ISSUE THREAD

**Issue by afarbmangit** [nodejs/node-gyp#1200]
Please help with my issue below:

Running npm install -g node-gyp worked. Get version v3.6.1 running node-gyp --version. Running node-gyp configure I get this:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.3 | darwin | x64
gyp http GET https://nodejs.org/download/release/v6.10.3/node-v6.10.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack at Error (native)
gyp ERR! stack at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
gyp ERR! stack at emitNone (events.js:86:13)
gyp ERR! stack at TLSSocket.emit (events.js:185:7)
gyp ERR! stack at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/userpath/.nvm/versions/node/v6.10.3/bin/node" "/Users/userpath/.nvm/versions/node/v6.10.3/bin/node-gyp" "configure"
gyp ERR! cwd /Users/userpath/git/forks/Web
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
Are you behind a proxy of some kind that intercepts outgoing connections?

**Comment by afarbmangit** [comment]
Not behind a proxy, but we have a Palo Alto thing that restricts access. Do you think this is an issue with a URL not being whitelisted?

**Comment by bnoordhuis** [comment]
Yes.  The error means the TLS certificate for https://nodejs.org/ doesn't match.

**Comment by refack** [comment]
@afarbmangit as a workaround you can download the needed headers and point `node-gyp` to use the local copy. See #1020
