### ISSUE TITLE
node-gyp configure failed

### ISSUE THREAD

**Issue by Vladyslav93** [nodejs/node-gyp#1202]
Hello, I get this Error. I tried to find something on google, but nothing works. Do someone had the same maybe? Some suggestion?

![image](https://cloud.githubusercontent.com/assets/28342273/26197737/9def792a-3bc3-11e7-8723-988602621d35.png)

Thanks.

**Comment by bnoordhuis** [comment]
You need to run node-gyp inside the directory of the add-on you are trying to build.  If you use npm to install modules/add-ons, you don't need to do anything, npm will invoke node-gyp on your behalf.
