### ISSUE TITLE
 Error: `gyp` failed with exit code: 1 at ChildProcess.onCpExit

### ISSUE THREAD

**Issue by LizanLycan** [nodejs/node-gyp#1209]
**Description:**
I tried to install several packages and I got the same error. The question is what happens when I want to configure: `node-gyp configure --msvs_version = 2015`

**ERROR**
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\USER\.windows-build-tools\python27\pythonw.exe
gyp info spawn args [ 'C:\\USER\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\WINDOWS\\system32\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\USER\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\USER\\.node-gyp\\6.9.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Lizandro Zerpa\\.node-gyp\\6.9.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Lizandro Zerpa\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\WINDOWS\\system32',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\WINDOWS\\system32\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Lizandro Zerpa\AppData\Roaming\npm\node_modules\node-gyp\lib\confi
gure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\USER\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "configure" "--msvs_version=2015"
gyp ERR! cwd C:\WINDOWS\system32
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

**Comment by richardlau** [comment]
> gyp info spawn C:\USER.windows-build-tools\python27\pythonw.exe

I'm not in front of a Windows system right now to check but does `gyp` work with `pythonw.exe`? If not then the question is whether this is a misconfiguration or fault in the python finding code.

**Comment by LizanLycan** [comment]
@richardlau well, change to the next addres: ` C:\USER\.windows-build-tools\python27\python.exe`, but, it still doesn't work. Try setting `node-gyp --python /path/to/python2.7`, but do not grab this configuration. I have already compiled packages with node-gyp, and they work fine, but now this error appeared with some packages that I need, and I still do not solve!

**Comment by joaocgreis** [comment]
@LizanLycan can you try removing the spaces around `=` in your command?
```
node-gyp configure --msvs_version=2015
```

If that doesn't work, add `--verbose` or even `--silly` to get more output.

**Comment by LizanLycan** [comment]
@joaocgreis Still does not work. I tried again with: `node-gyp --python /path/to/python2.7` and the same error, because its a global configuration

**Comment by lerfi** [comment]
Same problem after update to nodejs 8 !

**Comment by bnoordhuis** [comment]
Closing this out because it's been dormant for over a month.  If it's still an issue, please provide the requested logs.

**Comment by sanelib** [comment]
pkg-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'pkg-config --libs  cairo poppler-qt5' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

**Comment by bnoordhuis** [comment]
@sanelib pkg-config is an external tool and not normally available on Windows.  Try reaching out to the authors of the package you are trying to install, perhaps Windows isn't supported.

**Comment by jeanru** [comment]
After I input command: node-gyp rebuild,  I find following error:
gyp: binding.gyp not found (cwd: C:\Users\leon\AppData\Roaming\npm\node_modules\node-gyp) while trying to load binding.g
yp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\leon\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:33
6:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\leon\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\leon\AppData\Roaming\npm\node_modules\node-gyp
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by gibfahn** [comment]
@jeanru you need to run `node-gyp rebuild` in a directory that contains a `binding.gyp`.

**Comment by jeanru** [comment]
@gibfahn  Thanks, I have fixed this issue by create binding.gyp file manually, and then run node-gyp rebuild

**Comment by jeanru** [comment]
@gibfahn Thanks, I have fixed this issue by creating binding.gyp file manually, and then run node-gyp rebuild

**Comment by dhBunny** [comment]
I am getting this error every time I run a `node-gyp` command and when I try to install [enmap](https://npmjs.com/package/enmap) and [quick.db](https://npmjs.com/package/quick.db) 

```gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\ADRIÁN\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ADRIÁN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2015"
gyp ERR! cwd C:\Users\matt\Music\Discord-All\DiscordiumBots\Customers-Bots\SCP Assistant
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok```

I have `Node.js v12.13.0`, `npm v6.12.0` and `Python 2.7.16`
In my directory, there is a `binding.gyp` file I created myself, it is empty as I don't know if I have to add anything.

**Comment by Sentero-esp12** [comment]
I get the same error as above. Detailed: https://github.com/nodejs/node-gyp/issues/1969
binding.gyp should contain something like this:
`{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon.cc" ]
    }
  ]
}`

**Comment by dhBunny** [comment]
Alright, thank you so much!

**Comment by dhBunny** [comment]
But how should I fix the error I am getting? Would adding that to binding.gyp fix the error?

**Comment by Sentero-esp12** [comment]
In my case the error was because of a folder name. The fix was to rename this folder C:\Users\[username] to English, without spaces.
