### ISSUE TITLE
AttributeError: 'MSVSProject' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by alanpurple** [nodejs/node-gyp#1213]
![image](https://cloud.githubusercontent.com/assets/4515120/26611873/1f101e88-45ec-11e7-9d0c-cd4b0306f532.png)

**Comment by refack** [comment]
@bnoordhuis isn't `fsevents` supposed to be skipped on `windows`?
I think there's a bug in `npm@5`, I can run `npm i fsevents` and get:
<details>
<pre>
D:\code\4node\node-gyp-1144$ npm i fsevents@0.3.4
npm http fetch GET 304 https://registry.npmjs.org/fsevents 239ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 70ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/nan/-/nan-1.5.3.tgz 127ms
npm http fetch GET 200 https://registry.npmjs.org/fsevents/-/fsevents-0.3.4.tgz 130ms

> fsevents@0.3.4 install D:\code\4node\node-gyp-1144\node_modules\fsevents
> node-gyp rebuild


@CLINK_PROMPTD:\code\4node\node-gyp-1144\node_modules\fsevents$ if not defined npm_config_node_gyp (node "D:\bin\dev\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\bin\dev\node\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\bin\\dev\\node\\node.exe" "D:\\bin\\dev\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\code\4node\node-gyp-1144\node_modules\fsevents
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\code\4node\node-gyp-1144\package.json'
npm WARN node-gyp-1144 No description
npm WARN node-gyp-1144 No repository field.
npm WARN node-gyp-1144 No README data
npm WARN node-gyp-1144 No license field.
npm WARN node-gyp-1144 Invalid dependency: windows-autoconf undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@0.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@0.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\bin\var\npm-cache\_logs\2017-05-31T02_24_21_771Z-debug.log

D:\code\4node\node-gyp-1144$
</pre>
</details>

**Comment by refack** [comment]
IMHO it's a bug in the new `npm@5` - ref https://github.com/npm/npm/issues/16810

**Comment by alanpurple** [comment]
@refack I think so too since this happens right after upgrade to node v8.0.0 ( which includes npm 5 )

**Comment by refack** [comment]
@alanpurple I'll be closing this issue, but keeping track of https://github.com/npm/npm/issues/16810, if this doesn't solve the problem I'll reopen. Also you can feel free to reopen is any new information comes up.
