### ISSUE TITLE
Relative path for cafile isn't working

### ISSUE THREAD

**Issue by vbfox** [nodejs/node-gyp#1214]
When `cafile` is specified in a local `.npmrc` it's most often as a local path relative to the `.npmrc` file (In our case it's committed to our git repository)

`c:\foo\.npmrc`:
```
registry=https://npm_cache.local/
cafile=cafile
```

(`c:\foo\cafile` is our cafile)

Error in console:
```
gyp ERR! stack Error: ENOENT: no such file or directory, open 'c:\foo\node_modules\gulp-sass\node_modules\node-sass\cafile'
gyp ERR! stack     at Object.fs.openSync (fs.js:638:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:540:33)
gyp ERR! stack     at readCAFile (c:\foo\node_modules\node-gyp\lib\install.js:466:15)gyp ERR! stack     at download (c:\foo\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at c:\foo\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at c:\foo\node_modules\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)
```

*(Even when an absolute path is used it now fail as the download URL isn't on an internal server and our cafile contained only our internal root cert, but we could easily fix that)*

**Comment by bnoordhuis** [comment]
That isn't something node-gyp can fix, I think.

npm passes the cafile option as an environment variable (`npm_config_cafile`) to node-gyp but there is no way for node-gyp to know whether it's from .npmrc or from the `--cafile` option.

That is, node-gyp doesn't know whether it should be relative to the current working directory (`--cafile`) or to the .npmrc file.

I'd suggest filing an issue with npm.  Maybe they can add some preprocessing step that turns it into an absolute path.
