### ISSUE TITLE
[Question] Illegal instruction (core dumped) when building docker container

### ISSUE THREAD

**Issue by tuananh** [nodejs/node-gyp#1218]
Not sure if this is the right place to ask.

I have a native module and it works fine locally (OS X). Also tested in Linux.

However, when I build Docker containers, even though everything seems to work (image built and pushed) but it doesn't work. I got `Illegal instruction (core dumped)` error thrown.

I tried manually login into the container and re-rerun `node-gyp rebuild` and everything is working as expected again.

Does any of you know what could possibly cause this?

Many thanks.

Build logs attached.

```
make: Entering directory '/app/node_modules/<package-name>/build'
  CXX(target) Release/obj.target/hello/src/hello.o
  SOLINK_MODULE(target) Release/obj.target/hello.node
  COPY Release/hello.node
make: Leaving directory '/app/node_modules/<package-name>/build'
gyp info ok 
```

**Comment by bnoordhuis** [comment]
Hard to say.  If you had a core dump, you could load it into gdb and run `disassemble` to see the offending instruction.

**Comment by tuananh** [comment]
Here's the all the logs from gdb. Can you give me some guidelines to help debugging this.

It seems the error is thrown from `load_string`. However, I still don't get it why `node-gyp rebuild` would fix the problem?

Thank you.

```
(gdb) #14 0x00007f836c0d5541 in pugi::xml_document::load_string(char const*, unsigned int) () from /app/node_modules/camaro/build/Release/pugixml.node
(gdb) #13 0x00007ffe2a8ad4e0 in ?? ()
(gdb) #12 0x00007ffe2a8ad710 in ?? ()
(gdb) #11 0x0000000000000074 in ?? ()
(gdb) #10 0x00007ffe2a8ad710 in ?? ()
(gdb) #9  0x00007ffe2a8ad550 in ?? ()
(gdb) #8  0x00007f836a9f8020 in ?? ()
(gdb) #7  0x0000559ea7692230 in ?? ()
(gdb) #6  0x2b5b8c1863ff265b in ?? ()
(gdb) #5  0x0000559ea76920f8 in ?? ()
(gdb) #4  0x00000001a7692248 in ?? ()
(gdb) #3  0x0000559ea7692238 in ?? ()
(gdb) #2  0x00007f836c0e690f in ?? () from /app/node_modules/camaro/build/Release/pugixml.node
(gdb) #1  0x00007f836c0d45f1 in pugi::xml_parse_result::description() const () from /app/node_modules/camaro/build/Release/pugixml.node
(gdb) #0  0x00007f836c0d43f0 in pugi::xml_document::_destroy() () from /app/node_modules/camaro/build/Release/pugixml.node
```

**Comment by bnoordhuis** [comment]
Again, hard to say, unless you still have the old .node file.  Maybe it was linked against the wrong libc or libc++?  Your guess is as good as mine.

**Comment by tuananh** [comment]
I still have it. What can i do with it?

**Comment by bnoordhuis** [comment]
Check it for differences with ldd / otool, nm, objdump, etc.

**Comment by tuananh** [comment]
Thanks. I will take a look at those.

Is there any chance you can take a look at my repo real quick? https://github.com/tuananh/camaro/tree/master/src
