### ISSUE TITLE
Warning: Do not know how to convert MSVS attribute InheritedPropertySheets

### ISSUE THREAD

**Issue by Montaldo** [nodejs/node-gyp#1219]
I am trying to add my msvs property sheets to the binding.gyp configuration. Afaik this is the way to do it but the `node-gyp configure` keeps on throwing this warning and the generated `.vcxproj` does not come out the way it should.

`Warning: Do not know how to convert MSVS attribute InheritedPropertySheets`

I am expecting the generated `.vcxproj` to look like:

```
  <ImportGroup Label="PropertySheets">
    ...
    <Import Project="..\..\properties\default-release.props" />
  </ImportGroup>
```
But the PropertySheets label statys empty and my property sheets arent imported. Except for the default microsoft props file ofcourse.
```
  <ImportGroup Label="PropertySheets">
    ...
  </ImportGroup>
```

Here is a snippet of the respective importing of the msvs_props.

```
"conditions": [
  ['OS=="win"', {
    "defines": [
    ],
    "msvs_props": [
      "./properties/default-release.props"
    ]
  }]
]
```
`node-gyp v3.4.0`

Is the feature of importing property sheets in the binding.gyp supported in the current node-gyp version or am I doing something terrible wrong.

**Comment by bnoordhuis** [comment]
Did you manage to figure this out?  I think you may need to write this instead:
```
'msvs_props': ['$(SolutionDir)/properties/default-release.props']
```

**Comment by Montaldo** [comment]
Thanks for the reply! I havent solved it yet. Hacking around it by adding the settings in all property files manually to match the property sheets but that is far from ideal. 

I tried your suggestion. Thought I am not sure if SolutionDir is a thing outside of visual studio, the warning stays the same.

`Warning: Do not know how to convert MSVS attribute InheritedPropertySheets`

After running `configure `and `rebuild` the property sheets arent listed in the project file in the build directory, so my guess is it doesnt work. I've been looking at the implementation as well for parsing the props files and my guess is the issue is there but I havent had the time to fix it, test it and do a pull request. 

I might still be missing something so any other suggestions are more than welcome. Thanks again for your time and the reply!

**Comment by bnoordhuis** [comment]
I had a look and it seems GYP currently only knows about the following properties:

- CharacterSet
- ConfigurationType
- IntermediateDirectory
- OutputDirectory

So yes, it looks like InheritedPropertySheets won't work at this time.

**Comment by Montaldo** [comment]
Yea exactly, I am looking at doing stuff with the _Additional Include Dirs_,  _Library_ - and _Executable_ settings ect. I'll keep it like this for now. Thanks again!
