### ISSUE TITLE
Where could I find some variables?

### ISSUE THREAD

**Issue by XadillaX** [nodejs/node-gyp#1223]
I only know a variable called `module_root_dir`.

I want to know the list of all the variables in GYP.

Where could I find them?

**Comment by refack** [comment]
So there are at least 4 levels
1. `GYP` - https://gyp.gsrc.io/docs/InputFormatReference.md#Predefined-Variables
2. `node`'s `common.gypi` - https://github.com/nodejs/node/blob/master/common.gypi
3. `node-gyp`'s `addon.gypi` - https://github.com/nodejs/node-gyp/blob/master/addon.gypi
4. variables `node-gyp` adds at run time - https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L292

**Comment by XadillaX** [comment]
Thanks. I think maybe someday it can have some documentations.
