### ISSUE TITLE
`make` failed with exit code: 2

### ISSUE THREAD

**Issue by csonlai** [nodejs/node-gyp#1227]
make: *** [Release/obj.target/nbind/sources/yoga/YGNodeList.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--asmjs=1"
gyp ERR! cwd /Users/cson/Documents/newyoga/node_modules/yoga-layout

**Comment by gibfahn** [comment]
- What module were you trying to build (at what version)?
- what version of node and npm are you using?

Basically how can I reproduce this?

**Comment by bnoordhuis** [comment]
No follow-up, closing.
