### ISSUE TITLE
gyp http 404 fail

### ISSUE THREAD

**Issue by Fjandin** [nodejs/node-gyp#1233]
After upgrading to node 8 i get this error when i do a `yarn`

```
error /app/node_modules/libpq: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /app/node_modules/libpq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.1 | linux | x64
gyp http GET https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp http 404 https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp WARN install got an error, rolling back install
```

Not sure wether this has something to do with gyp or libpq

But i know for a fact that `https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz` does indeed not exist but `https://nodejs.org/download/release/v8.1.1/node-v8.1.1-headers.tar.gz` exists. Note the missing `/release/`

**Comment by bnoordhuis** [comment]
See https://github.com/nodejs/node/issues/13667 for cause and workaround.  The next node release will have a proper download URL again.  I'll close this out, cheers.
