### ISSUE TITLE
Error when downloading headers

### ISSUE THREAD

**Issue by Robinfr** [nodejs/node-gyp#1234]
I'm getting the following error when I'm installing `node-gyp`:

```
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
```

**Comment by bnoordhuis** [comment]
See #1230, #1231, #1232 and #1233.  I'll leave this issue open for a while in the hope that it stops the duplicates.

tl;dr use `npm install --dist-url https://nodejs.org/download/release`

**Comment by bnoordhuis** [comment]
Should be okay now that https://github.com/nodejs/build/pull/759 is in place.  You'll still want to upgrade to v8.1.2 when it comes out later today / tomorrow.

**Comment by Robinfr** [comment]
Ah sorry for the duplicate, this is also caused by the fact that the laster Node Docker image is using 8.1.1.
