### ISSUE TITLE
[SWIG] [ANSI C] Fatal error: utility: No such file or directory

### ISSUE THREAD

**Issue by papaiatis** [nodejs/node-gyp#1238]
Hi all,

I'm trying to create a javascript wrapper for an ANSI C file using SWIG and node-gyp.
I'm basically using this this doc as a starting point: http://www.swig.org/Doc3.0/Javascript.html#Javascript

I created the wrapper C file with SWIG which I'd like to build with node-gyp, however I does not seem to be finding some system headers:

```
$ node-gyp build                                              
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/atis/swig-test/src/build'
  CC(target) Release/obj.target/test2/test2_wrap.o
In file included from /home/atis/.node-gyp/6.10.1/include/node/node.h:42:0,
                 from ../test2_wrap.c:132:
/home/atis/.node-gyp/6.10.1/include/node/v8.h:21:19: fatal error: utility: No such file or directory
 #include <utility>
                   ^
compilation terminated.
make: *** [Release/obj.target/test2/test2_wrap.o] Error 1
make: Leaving directory `/home/atis/swig-test/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-119-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/atis/swig-test/src
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

I found the `utility` header file here: /usr/include/c++/4.8/utility
I have installed "swig3.0", "libjavascriptcoregtk-1.0-dev" and "libv8-dev" too.
I'm on Ubuntu 14.10, kernel 3.13.0-119.
gcc version 4.8.4

```
$ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.1 | linux | x64
6.10.1
gyp info ok 
```

Note that I'm not building a NodeJS extension, I just want to use a C file in JS.
Any help would be great!

**Comment by bnoordhuis** [comment]
Compile your file as C++.  Node's and V8's API are C++ (C++11 to be specific) so if you include their headers in your source code, it needs to be compiled with a C++ compiler.

**Comment by papaiatis** [comment]
@bnoordhuis I've not really used C/C++ so far. How do I compile my .c file as C++?

**Comment by bnoordhuis** [comment]
I edited my comment after posting but for posterity, give it a .cc extension and it should be routed to the C++ compiler.

**Comment by papaiatis** [comment]
I don't really see how would renaming the .c file to .cc help. I did the rename but nothing changed.
Didn't mention earlier, but I've got a test2.i file with this content:

```
/* File: test2.i */
%module test2
%{
#include "test2.h"
%}
extern void some_test_method(char const *input, char *output);
```

I call `swig3.0 -javascript -node test2.i` which generates a test2_wrap.c file and this wrapper is referenced in `binding.gyp`:
```
{
    "targets": [
        {
            "target_name": "test2",
            "sources": ["test2_wrap.c"]
        }
    ]
}
```

If I rename `test2_wrap.c` to `test2_wrap.cxx` then I get a lot of other compiler errors.

**Comment by bnoordhuis** [comment]
Right, that's something you'll have to figure out on your own; it's not a node-gyp issue.

I'm going to close this out but if you're still looking for help, open an issue over at https://github.com/nodejs/help/issues.
