### ISSUE TITLE
Support for mingw/msys/cygwin for node-gyp

### ISSUE THREAD

**Issue by smaudet** [nodejs/node-gyp#1240]
The authors claims that mingw is not a viable target for node-gyp on windows I believe to be patently false.

I would like to patch node-gyp to allow it to correctly build msys compatible make files, for versions of nodejs built with the msys/gcc toolchain.

From my research so far, this is not only possible, but partially already supported. Two things need to happen:

1) Stop assuming that only msvs is supported on windows
2) Add an msys make target with the following properties:
  a) support /c/
  b) No colons are allowed in e.g. /C:/
3) link to appropriate msys versions of libraries.

If those conditions are met, it appears that node-gyp generates/builds just fine on msys nodejs, contrary to the author's wild claims to the contrary.

Referencing these old tickets in case there's anything of value/relevance in them:

https://github.com/nodejs/node-gyp/issues/194
https://github.com/nodejs/node-gyp/issues/280
https://github.com/nodejs/node-gyp/issues/660

**Comment by bnoordhuis** [comment]
If it's a few small unobtrusive changes, that might be fine.  If it's going to take major surgery and ongoing maintenance effort, the answer is 'no'.

Building node with mingw isn't supported so there is only marginal value in supporting it in node-gyp.  You won't be able to load a mingw-compiled add-on in a msvs-compiled node, or vice versa.

If you are serious about this, you should upstream your changes to nodejs/node first.

> contrary to the author's wild claims to the contrary

Lay off the condescension, will you?  What are you, a twelve year old?

**Comment by smaudet** [comment]
Major surgery etc are unlikely to occur. Unless linux becomes an unsupported platform (in which case I'm likely to ditch nodejs entirely), gcc support is available, and while gcc support is available, mingw support is not much of an effort.

There might be some retraining required down-stream (if people are doing awful things with their node-gyp files).

As for upstream, the version I'm using is based on a patch engine that somebody else is reponsible for (credit to Alexey Pawlow https://github.com/Alexpux).

I'm unsure what his effort on this issue is. His stuff works fine.

As for 'condescension', all it took me was a minor bit of googling and a bit of playing around to figure this stuff out so far. The node-gyp authors can't have even tried.

**Comment by bnoordhuis** [comment]
Yeah, because we're well aware of the cost/benefit ratio.  The point stands that as long as upstream node doesn't support mingw, supporting it in node-gyp is of extremely marginal utility.

You are welcome to open a pull request but if I deem it too invasive or too much of a maintenance headache, I'll have no qualms about rejecting it.

**Comment by smaudet** [comment]
'Just works' support for msys is fairly big benefit. Dealing with required admin access to machines/bulky msvs compilers with large buggy .NET dependencies is a fairly major drawback.

**Comment by bnoordhuis** [comment]
As long as this is an issue:

> You won't be able to load a mingw-compiled add-on in a msvs-compiled node, or vice versa.

mingw will always be a fringe thing.  I would be more supportive of clang-cl support, it's ABI-compatible with msvs.

**Comment by smaudet** [comment]
This is getting very off-topic, but, M\maybe. But I'm not aware of any clang-cl based runtimes - sure that's a nice idea, but where's my pacman on windows and my bash?

Also, I've not followed up with the windows 10 linux subsystem, but I'd think that'd make stuff like this more prevalent, not less. Perhaps eventually msys2 morphs into another compatibility layer there?

**Comment by bnoordhuis** [comment]
> But I'm not aware of any clang-cl based runtimes

I don't know what you mean by that.  clang-cl is a front-end to clang that emits msvs-compatible machine code (same C++ name mangling, calling conventions, etc.)

mingw uses its own name mangling scheme that makes interoperability impossible.

> At any rate, you seem to be more intent on talking about why its a bad idea, I'll focus on actually coding, thanks.

You go, kid.  And I, I'll go close out the issue.

**Comment by smaudet** [comment]
Um, why close it? I'm still working on this.

**Comment by bnoordhuis** [comment]
You rather clearly indicated the discussion ran its course.  Looking forward to the PR.

**Comment by smaudet** [comment]
Ah, ok. I have to go to work here in a bit. I was under the impression it should stay open until there was a PR.

**Comment by gibfahn** [comment]
>Also, I've not followed up with the windows 10 linux subsystem, but I'd think that'd make stuff like this more prevalent, not less. 

If you're in the subsystem you have full access to gcc, what's the usecase for using mingw?

>I would like to patch node-gyp to allow it to correctly build msys compatible make files, for versions of nodejs built with the msys/gcc toolchain.
>it appears that node-gyp generates/builds just fine on msys nodejs, 

Have you tried contributing your msys nodejs support into nodejs?


>Dealing with required admin access to machines/bulky msvs compilers with large buggy .NET dependencies is a fairly major drawback.

Have you tried http://landinghub.visualstudio.com/visual-cpp-build-tools ?

**Comment by smaudet** [comment]
In short:

1) Not in it.
2) Not mine.
3) Not applicable to me.

**Comment by smaudet** [comment]
Quick update - there is a symbol mangling issue which is caused by something in the build system.

As I've spent a fair amount of time learning now how gyp works, and basically that all node-gyp is, is an addon on top of that, my conclusion is that it probably makes sense to build a new gyp addon tool, an alternative to node-gyp. Maybe ultimately it makes sense to port whatever build tool changes I make back to node-gyp, but for now I'm thinking node-gyp is the wrong approach.

As for node packages which require node-gyp to build, an immediate solution would be to use npm's facilities to forcefully replace node-gyp with an alternative, through linking or custom npm repositories.

**Comment by smaudet** [comment]
Some good news, I have it working.

By that I mean, I have patches that produce correct build files for nodejs on mingw, and I have the hello world example building.

Now comes the hard part of building reproduce-able patches.

**Comment by sekhat** [comment]
@smaudet did a PR ever result from this?

**Comment by Kreijstal** [comment]
still interested in this

**Comment by abcfy2** [comment]
Any updates ? Support mingw/msys/cygwin make senses to me.

**Comment by Kreijstal** [comment]
> Any updates ? Support mingw/msys/cygwin make senses to me.

you need to compile node in mingw first, apparently.

**Comment by theoparis** [comment]
This is currently blocking me from installing anything to do with napi, such as the re2 package on windows 😕 
I have clang installed in msys2 but it still asks for VS 2017.

**Comment by Kreijstal** [comment]
https://opensourcepack.blogspot.com/2013/06/nodejs-with-posix-path-support.html Ah look, it seems you need to uses mys python
https://github.com/nodejs/node-gyp/issues/194 this is quite unfortunate, but someone was trying to patch mingw python to support the msys enviroment... not sure if that's stable enough

**Comment by Kreijstal** [comment]
> Some good news, I have it working.
> 
> By that I mean, I have patches that produce correct build files for nodejs on mingw, and I have the hello world example building.
> 
> Now comes the hard part of building reproduce-able patches.

I also got it working... but now I need to think about how to keep msvc and mignw support, mine just deletes the msvc nonsense, and supports only mingw which solved the immediate need... but I wonder about conditional compilation to support both mingw and propietary msvc
