### ISSUE TITLE
node-gyp rebuild fails w7 Visual Studio 2017 and node v8.1.2

### ISSUE THREAD

**Issue by daixtrose** [nodejs/node-gyp#1246]
- OS: Windows 10

```bash
$ node --version
v8.1.3 
$ npm --version
5.0.3
```

in some project I run `npm update`

```bash
github-issues-export\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  contextify.cc
  win_delay_load_hook.cc
..\src\contextify.cc(150): error C2039: "SetAccessCheckCallbacks": Ist kein Element von "v8::ObjectTemplate" [ ... github-issues-export\node_modules\contextify\build\contextify.vcxproj]
``` 

Is this a problem with old dependencies of [`github-issues-export`](https://github.com/gizur/github-issues-export) or a general issue with node-gyp?

**Comment by gibfahn** [comment]
cc/ @nodejs/platform-windows

**Comment by refack** [comment]
`contextify` is incompatible with recent `node` versions, and anyway is unneeded for `node>0.12`... So it's a `github-issues-export` issue (should move `contextify` to `optionalDependencies`)
@daixtrose I'm closing this issue, feel free to reopen if you have new information or find a problem with `node-gyp`
