### ISSUE TITLE
build node-sass with yarn

### ISSUE THREAD

**Issue by nodece** [nodejs/node-gyp#1250]
### env
- win 10
- yarn 
- python2
- vs2017
### error
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。

### proplem
Does node-gyp support vs2017 ?

**Comment by bnoordhuis** [comment]
The latest version does.

**Comment by nodece** [comment]
it work
dowload Visual Studio 2015 build tool
yarn config msvs_version 2015
rebuild
