### ISSUE TITLE
Dynamic linkings do not resolve

### ISSUE THREAD

**Issue by devsnek** [nodejs/node-gyp#1252]
* **Node Version**: `v8.1.4` and `5.3.0`
* **Platform**: `Linux 4.11.7-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux`
* **Compiler**: `gcc version 7.1.1 20170621 (GCC)`

At runtime dyanmic libraries are not resolved.
`Error: libfreenect.so.0.5: cannot open shared object file: No such file or directory`

binding.gyp:
```json
{
  "targets": [
    {
      "target_name": "freenect",
      "cflags!": ["-fno-exceptions"],
      "cflags_cc!": ["-fno-exceptions"],
      "include_dirs": [
        "/usr/local/include/libfreenect",
        "<!@(node -p \"require('node-addon-api').include\")",
      ],
      "link_settings": {
        "ldflags": ["-L/usr/local/lib", "-lfreenect", "-lfreenect_sync"]
      },
      "ldlibs": ["-L/usr/lib", "-L/usr/lib64", "-L/usr/local/lib"],
      "sources": [
        "src/freenect.cc",
        "src/binding.cc"
      ],
      "dependencies": [
        "<!(node -p \"require('node-addon-api').gyp\")"
      ]
    }
  ]
}
```
If I change them to static (`-l:libfreenect.a`), it works, but then i go down a rabbit hole of compiling everything staticly, and after i needed to get a static build of libudev i decided that enough was enough.

Additionally, I am using the new N-API bindings.

**Comment by devsnek** [comment]
It would appear this might not be a gyp issue after i ran one of the example binaries provided with libfreenect, and it also gave errors about loading the dynamic libraries, so I will close this for now.

**Comment by bnoordhuis** [comment]
Not a node-gyp indeed but try setting DYLD_LIBRARY_PATH or linking with `-Wl,-rpath,/path/to/addon/dir`.

**Comment by devsnek** [comment]
Just to follow up, it appears that arch does not load `/usr/local/lib` into its ldconfig by default, which I was not expecting, but a quick `sudo ldconfig /usr/local/lib` fixed it up
