### ISSUE TITLE
c1xx : fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [E:\..\build\binding.vcxproj]

### ISSUE THREAD

**Issue by nikunjdnp** [nodejs/node-gyp#1253]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
E:\Web>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [E:\Quarterly\Quarterly-Web\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\..\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd E:\Quarterly\Quarterly-Web
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

</details>

Where can I get this binding,cc file!?

**Comment by bnoordhuis** [comment]
What exactly are you trying to do?

**Comment by nikunjdnp** [comment]
I am trying to install node-gyp in windows-8.1.It was require binding.cc file which i have declared in binding.gyp file.

My question is : should i create empty binding.cc file?

**Comment by bnoordhuis** [comment]
Can you explain what you are trying to accomplish?  node-gyp is a build tool for C and C++ code.

**Comment by nikunjdnp** [comment]
I am setting up one app which have front-end in ionic and backend in node.I was trying to set up front-end in windows.When i was trying to execute '**ionic serve**' ,It throws an error that Error in your gulp script. Then,I have installed npm build-tools. After all these process,Trying to execute '**node-gyp**' which gives me this error.

**Comment by bnoordhuis** [comment]
I don't think the issue is with node-gyp.  As I said, it's only a build tool.  What's more, there is no gulp script, that's probably from ionic.  Perhaps try contacting that project.

You shouldn't need to deal with node-gyp directly, `npm install` normally takes care of running it when necessary.  Good luck.

**Comment by Epameinondas-Theodoropoulos** [comment]
I have the same problem exaxtly

**Comment by cclauss** [comment]
Please provide the command that you typed and the full error log.

**Comment by abarojohncleo** [comment]
In case someone gets here.

https://stackoverflow.com/questions/44357010/node-gyp-build-fatal-error-c1083

**Comment by 182exe** [comment]
what a helpful support person
didnt answer question, closed issue, person left confused.
