### ISSUE TITLE
Getting connection refused while build : Not able to download binary.

### ISSUE THREAD

**Issue by ashishsantikari** [nodejs/node-gyp#1254]
I am getting build failed error while running the Angular-CLI project. On careful analysis, I see that the binary is not getting downloaded.

[INFO] > fsevents@1.1.2 install /Users/ashish.santikari/temp-test/vems-gui-sso-integration/vems-gui/node_modules/fsevents
[INFO] > node install
[INFO] 
[INFO] [fsevents] Success: "/Users/ashish.santikari/temp-test/vems-gui-sso-integration/vems-gui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
[INFO] Pass --update-binary to reinstall or --build-from-source to recompile
[INFO] 
[INFO] > node-sass@4.5.3 install /Users/ashish.santikari/temp-test/vems-gui-sso-integration/vems-gui/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-48_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-48_binding.node": 
[ERROR] 
[ERROR] read ECONNRESET
[ERROR] 
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
[ERROR] 
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR] 
[ERROR] or configure npm proxy via
[ERROR] 
[ERROR]       npm config set proxy http://example.com:8080
[INFO] 
[INFO] > node-sass@4.5.3 postinstall /Users/ashish.santikari/temp-test/vems-gui-sso-integration/vems-gui/node_modules/node-sass

**Comment by bnoordhuis** [comment]
Not a node-gyp issue.  That's from the node-sass install script.

**Comment by ashishsantikari** [comment]
Okay. Issue reported to node-sass. Thanks, @bnoordhuis.
