### ISSUE TITLE
Using absolute path in binding.gyp

### ISSUE THREAD

**Issue by tahnik** [nodejs/node-gyp#1255]
* **Node Version**: v8.2.1
* **Platform**: Linux 4.10.0-27-generic (Ubuntu)
* **Compiler**: gcc v5.4.0
* **Module**: NodeJS C++ Addon

I am using an external library for building a custom nodejs c++ addon. I need to include on of the files from that library that exists in "/opt/lib/file.cpp".

This doesn't work:

```
...
"include_dirs": [
  "/opt/lib"
],
"sources": [
  "processor/Processor.cc",
  "/opt/lib/file.cpp"
],
...
```
The error I get is this:
```
make: *** No rule to make target 'Release/obj.target/processor//opt/lib/file.o', needed by 'Release/obj.target/processor.node'. Stop.
make: Leaving directory '/home/username/project/build'
```

But this works:
```
...
"include_dirs": [
  "/opt/lib"
],
"sources": [
  "processor/Processor.cc",
  "../../../opt/lib/file.cpp"
],
...
```

So in brief it works if I use relative path. Is there any way to use absolute path in sources of binding.gyp?

Thank you

**Comment by bnoordhuis** [comment]
I believe the answer is: no, there is not; source paths are always made absolute relative to the project root.

**Comment by tahnik** [comment]
@bnoordhuis that makes is almost impossible to build the addon on CI environment :(

**Comment by bnoordhuis** [comment]
As a workaround, you can symlink the external directory in the project directory.
