### ISSUE TITLE
Error during installation lwip on mac 

### ISSUE THREAD

**Issue by UmairNazir** [nodejs/node-gyp#1260]
During installation of  node lwip on mac.. it is throwing this error 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/usr/local/Cellar/node/8.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/affanfaisal/workspace/konmari/konmari-api/node_modules/lwip
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package request is included as both a dev and production dependency.
npm WARN The package sendgrid is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/affanfaisal/.npm/_logs/2017-08-11T07_21_39_623Z-debug.log

**Comment by bnoordhuis** [comment]
You didn't include the actual build error but this:

> gyp ERR! stack Error: make failed with exit code: 2

Suggests the problem is with the module you are trying to build, not node-gyp.

**Comment by UmairNazir** [comment]
ok.. then how i will solve this issue??

**Comment by bnoordhuis** [comment]
Can you post the full output?  That might give some insight.
