### ISSUE TITLE
How to add dependence of shared_library in binding.gyp?

### ISSUE THREAD

**Issue by Shivani26Singh** [nodejs/node-gyp#1270]
I have .node file of my C++ project and I want to refer this .node file in its Unit test project. But I am unable to link .node/ .dll file in binding.gyp file of my Unit Test project. If I build my C++ project with static library, I am able to execute my unit tests sucessfully.

**Comment by bnoordhuis** [comment]
Can you post your code?  I can only guess at what you are trying to do otherwise.

I'll close this out for now pending more information.

**Comment by LyonOconner** [comment]
post code plz.
