### ISSUE TITLE
node-gyp rebuild sporadically gets stuck on AppVeyor

### ISSUE THREAD

**Issue by FeodorFitsner** [nodejs/node-gyp#1274]
* **Node Version**: Node.js 6.11.2 x86 (but it reproduces on 7.x and 8.x as well).
* **Platform**: Windows Server 2012 R2
* **Compiler**: MSBuild
* **Module**: `runas` (https://github.com/atom/node-runas)

Sometimes, while installing `runas` module (and others using `node-gyp`) `node-gyp rebuild` is getting stuck.

The place where it hangs is approximately in the same area, but looks different from build to build:

1st failing build: https://ci.appveyor.com/project/FeodorFitsner/node-gyp-issue/build/1.0.2

```
...
gyp http 200 https://nodejs.org/download/release/v6.11.2/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v6.11.2/SHASUMS256.txt
gyp verb checksum data {"node-v6.11.2-aix-ppc64.tar.gz":"79ead2addfa70ea471406f48917530822e9214acd2351d1f02401b3c4dd7a34a", ...
<stuck here>
```

2nd failing build: https://ci.appveyor.com/project/FeodorFitsner/node-gyp-issue/build/1.0.3

```
...
gyp http 200 https://nodejs.org/download/release/v6.11.2/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v6.11.2/SHASUMS256.txt
gyp verb checksum data {"node-v6.11.2-aix-ppc64.tar.gz":"79ead2addfa70ea471406f48917530822e9214acd2351d1f02401b3c4dd7a34a", ...
<stuck here>
```

3rd failing build: https://ci.appveyor.com/project/FeodorFitsner/node-gyp-issue/build/1.0.10

```
...
gyp http 200 https://nodejs.org/download/release/v6.11.2/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v6.11.2/win-x64/node.lib
<stuck here>
```

Test command:

    npm install runas --loglevel verbose

All builds (failing and successful): https://ci.appveyor.com/project/FeodorFitsner/node-gyp-issue/history

Test repository: https://github.com/FeodorFitsner/node-gyp-issue

What might be a cause of that issue?

Thank you!

**Comment by bnoordhuis** [comment]
I would guess a network issue.  They all seem to be stuck on downloading the .lib files.  It's probably not an issue with https://nodejs.org/ - at least, I haven't seen similar bug reports.

**Comment by FeodorFitsner** [comment]
@bnoordhuis Looks like this is the case. We'll check with our hosting provider. Thanks for replying so fast!
