### ISSUE TITLE
Error while compiling related to missing locale

### ISSUE THREAD

**Issue by juliensnz** [nodejs/node-gyp#1283]
Hello, I'm reporting here an issue for which I have already a solution. I spent 4h to fix it so I think that it worth the sharing.

My goal was to install microtime for an IoT project on my Next Thing C.H.I.P. (similar to a Raspberry Pi). Gcc and G++ was installed and properly working. When doing npm install I was getting this error:

```
Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp.
```

Running `node -e "require('nan')"` was not displaying any error but was indeed returning a code `0` (which is not an error code btw).
I tried pretty much anything to fix the issue (reinstalling build essential, node-gyp, node, npm, etc).

I then realised that from time to time I was getting this error: 

```
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```
Indeed a locale is missing on this system and this warning is the cause of this fail during the preparation of the compilation.

To fix the problem, simply run 

```
sudo apt-get install locales
localedef -i en_US -f UTF-8 en_US.UTF-8
```

* **Node Version**: latest node 6.x 8.x
* **Platform**: Debian (chip kernel 4.4.13)
* **Module**: microtime, spi, etc

**Comment by bnoordhuis** [comment]
I'll close this out as it's not an issue with node-gyp itself but thanks for the report.
