### ISSUE TITLE
node: symbol lookup error: /home/folder/api/addon/build/Release/addon.node: undefined symbol: _ZN4demo3sumEii

### ISSUE THREAD

**Issue by amitnagar19** [nodejs/node-gyp#1284]
Hello, I am creating a C++ addon and I wanted to use a static library. i have a .a library libarith which does simple addition.
-libarith.a
-hello.cc
-hello.js
my binding.gyp file is as follows:-
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "hello.cc" ],
"libraries": [ "-/home/folder/api/addon/libarith.a" ],
          "cflags!": [ "-fno-exceptions" ],
          "cflags": [ "-std=c++11" ],
          "cflags_cc!": [ "-fno-exceptions" ]
    }
  ]
}

When i compile my hello.cc it compiles well. But when i run my addon , it gives following error:
node: symbol lookup error: /home/folder/api/addon/build/Release/addon.node: undefined symbol: _ZN4demo3sumEii.

I am new to addons, a help would be very much appreciated.
Thanks in advance.

**Comment by bnoordhuis** [comment]
That's an issue with the add-on you are trying to load (source code typo, maybe?), not node-gyp.  Sorry, can't help you with that.
