### ISSUE TITLE
node-gyp configure

### ISSUE THREAD

**Issue by sonydaman** [nodejs/node-gyp#1285]
node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\xampp_New\\htdocs\\REPO\\REACTNATIVE\\react-native-facebook-account-kit\\examples\\RN024\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\SonyDaman\\.node-gyp\\6.11.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\SonyDaman\\.node-gyp\\6.11.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\SonyDaman\\.node-gyp\\6.11.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\xampp_New\\htdocs\\REPO\\REACTNATIVE\\react-native-facebook-account-kit\\examples\\RN024',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\xampp_New\\htdocs\\REPO\\REACTNATIVE\\react-native-facebook-account-kit\\examples\\RN024\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\SonyDaman\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
> gyp: binding.gyp not found (cwd: F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024) while trying to load binding.gyp

That's the error.  You are trying to run node-gyp on a directory that doesn't contain an add-on.
