### ISSUE TITLE
Can not download headers

### ISSUE THREAD

**Issue by MaxCCC** [nodejs/node-gyp#1287]
* **Node Version**: node: 7.10.0
* **Platform**: Archlinux
* **Module**: node-sass

During the install of node-sass it tries to install node-gyp

```
[INFO] [4/4] Building fresh packages...

/xxx/.node-gyp/7.10.0\ngyp verb created nodedir /xxx/.node-gyp\ngyp http GET https:/xxx/artifactory/nodejs-dist/v7.10.0/node-v7.10.0-headers.tar.gz\ngyp WARN install got an error, rolling back install\ngyp verb command remove [ '7.10.0' ]
..
 ERR! stack Error: self signed certificate in certificate chain\ngyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\ngyp ERR! stack     at emitNone (events.js:86:13)\ngyp ERR! stack     at TLSSocket.emit (events.js:188:7)\ngyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)\ngyp ERR! stack     at TLSWrap.ssl.onhandshakedone
```

Why is `\ngyp` added behind the URL? Is this causing an issue or the certificate. We are using the mirror to our own artifactory because node-gyp seems not to pick up our proxy settings? 
By default it tries to download from nodejs.org

Edit: I've added 'NODE_TLS_REJECT_UNAUTHORIZED=0' as temporary hack to ignore the SSL part.
I still have the issue with my URL

</details>

**Comment by bnoordhuis** [comment]
I'm going to guess that you are using yarn and that the `\ngyp` is an artifact of how yarn prints output from child processes.  If you want to know for sure, you should ask that project.

If you are using a custom download server, pass `--cafile /path/to/ca.crt` to node-gyp, where `ca.crt` contains the certificate chain of your server's certificate.  With npm, you can also set `cafile` in your .npmrc; I don't know if or how that works with yarn.

node-gyp also respects the `http_proxy` environment variable and npm's `proxy` setting (assuming yarn passes it to node-gyp the same way npm does.)

Hope that helps!
