### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by karun-r** [nodejs/node-gyp#1288]
I was trying to create a web app which queries a set of SQL Server and returns some data. It was working for a while during the development process just when I made some small jQuery change in the UI part, I got this error in msnodesqlv8 module file(I think). Environment details below:

Node version - v6.11.2
OS - Windows 10  (64 Bit)
Modules using - mssql,msnodesqlv8

Complete error trace:
```js
Error: %1 is not a valid Win32 application.
\\?\d:\Folder1\node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v1.7.5.ia32.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at attemptToExportBinary (d:\OEM\OPK\node_modules\msnodesqlv8\lib\sqlserver.native.js:55:24)
    at d:\OEM\OPK\node_modules\msnodesqlv8\lib\sqlserver.native.js:45:7
    at Array.forEach (native)
```

**Comment by refack** [comment]
@karun-r there are a few missing pieces in your report. It seems like you have a run time error, and `node-gyp` is a building tool so I'm not sure how we can help you.
It does seem like there is something wrong with your `d:\Folder1\node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v1.7.5.ia32.node` file, which I assume is installed by `msnodesqlv8`. So first I'd suggest running `npm -ddd i` making sure everything is ok, then look in the [`msnodesqlv8` repo](https://github.com/TimelordUK/node-sqlserver-v8/issues)maybe they have experience with this error.
I'm going to close this issue, but feel free to reopen if you have new information.
