### ISSUE TITLE
Cannot build on OSX with Node 6 or 4 ?

### ISSUE THREAD

**Issue by MatthD** [nodejs/node-gyp#1290]
How is it possible that a node-gyp app (An add-on in c++ for node.js) could build correctly on Linux for Node 8.4,6.11 & 4.4 and on OSX for 8.4 BUT NOT for OS X 6.11 and 4.4 ?

The system should be the same, the compiler too I think.

Does OS X -Travis keep files between different process ?

The errors seems to occurred on the library that I use not on node-gyp or nan itself, so that is strange.

I really do not understand what could happen because the system configuration for OSX should be the same :s

My travis built  to check : https://travis-ci.org/istex/popplonode/builds/275480040

Thanks!

**Comment by bnoordhuis** [comment]
If I had to guess, it's that you need to add a `'CLANG_CXX_LANGUAGE_STANDARD': 'c++11'` to a `'xcode_settings'` block in your binding.gyp somewhere.

**Comment by MatthD** [comment]
thanks you send me on the right way, in fact I needed to set "MACOSX_DEPLOYMENT_TARGET": "10.12", and then it compile great 👍 

My binding.gyp & lib.gypi has this now 

```
["OS=='mac'", {
          "xcode_settings": {
           "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
           "GCC_ENABLE_CPP_RTTI": "YES",
           "MACOSX_DEPLOYMENT_TARGET": "10.12",
           "CLANG_CXX_LANGUAGE_STANDARD": "c++11"
          }
        }]
```
