### ISSUE TITLE
Compile is ok, but error when use Symbol not found: _iconv_open

### ISSUE THREAD

**Issue by MatthD** [nodejs/node-gyp#1291]
Hi everyone,

I build a .node correctly but I have got a probleme when run it on OSX, it gave me an error : 

`dyld: lazy symbol binding failed: Symbol not found: _iconv_open`

And then it crash, the error is happening on all nodes version on OSX  BUT NOT on linux, it runs fine.

What could be the way to correct this ? Maybe a lib path problem ?

Thanks

**Comment by bnoordhuis** [comment]
You probably need to link against libiconv (`-liconv`); on linux, it's part of glibc, but it's a separate library on other platforms.

A gentle reminder: I don't mind the occasional question but this issue is for reporting node-gyp issues, not general build issues.

**Comment by MatthD** [comment]
Super ! that was this , thanks you, I was on this since an entire day !!
