### ISSUE TITLE
text in readme in wrong place

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-gyp#1295]
* **Node Version**: n/a
* **Platform**: Windows
* **Compiler**: n/a
* **Module**: n/a

Under the "On Windows" installation section there is a blurb about macOS that should be moved back into the "On Mac OS X" installation section:

> Note that OS X is just a flavour of Unix and so needs python, make, and C/C++. An easy way to obtain these is to install XCode from Apple, and then use it to install the command line tools (under Preferences -> Downloads).

**Comment by andrwsalcdo** [comment]
Can I take this one? new contributor.

**Comment by mscdex** [comment]
@andrwsalcdo  Sure, go for it.
