### ISSUE TITLE
fatal error LNK1104: can not open file "a boost lib"

### ISSUE THREAD

**Issue by kwzm** [nodejs/node-gyp#1297]
* **Node Version**: node 6.10.2 and npm 3.10.10
* **Platform**: window7 x64
* **Compiler**: windows
* **Module**: a simple file I/O addon depend on boost
<summary>Verbose output (from npm or node-gyp):</summary>

```
LINK : fatal error LNK1104: 无法打开文件(can not open file)“libboost_filesystem-vc140-mt-s-1_65_1.lib
```

binding.gyp:
```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon_boost.cpp" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "D:/boost_1_65_1",
        "D:/boost_1_65_1/stage/lib"
      ]
    }
  ]
}
```

addon_boost.cpp header:

```
#include <iostream>
#include <string>
#include <nan.h>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
using namespace std;
namespace bf = boost::filesystem;
```

**Comment by bnoordhuis** [comment]
That can't be the complete binding.gyp because you don't have a `libraries'` stanza in there that tells node-gyp to actually link in the .lib file.

Aside: `using namespace` is almost always a terrible idea, `using namespace std` doubly so.

**Comment by kwzm** [comment]
Thanks for your advice, now the binding,gyp like this:

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon_boost.cpp" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "D:/boost_1_65_1"
      ],
      "libraries": [
        "-LD:\boost_1_65_1\stage\lib"
      ]
    }
  ]
}
```

But the error still exist /(ㄒoㄒ)/~~

I found some doubtful points:

1、I don`t have  libboost_filesystem-vc140-mt-s-1_65_1.lib in my lib, i only have libboost_filesystem-vc140-mt-1_65_1.lib and libboost_filesystem-vc140-mt-gd-1_65_1.lib

2、I compile boost in x86 way, but my computer is x64, i know how to run in vs2015 use x86 but i don`t 
know how to build with node-gyp in x86.
I try to reubild --arch=x86 but fail, error is cannot find .node-gyp/6.10.2/x86/node.lib

Looking forward to your reply

PS: Forgive my broken English.

**Comment by bnoordhuis** [comment]
I still don't see where you link in that specific library.

What does `node -p process.arch` print?  If it's `ia32` that's good, that's x86.  If it's `x64`, you need to use 64 bits libs.

**Comment by kwzm** [comment]
Hi, thanks for you advice.
I try node -p process.arch, is x64, but i don't have 64bits libs, can`t i use x86 way to compile like vs2015 ?
Besides, i don`t find libboost_filesystem-vc140-mt-s-1_65_1.lib in my computer, i don`t know why it needs a inexistent lib, do you know boost, how can i get this lib, i run b2.exe only get libboost_filesystem-vc140-mt-1_65_1.lib and libboost_filesystem-vc140-mt-gd-1_65_1.lib.

Looking forward to your reply.

**Comment by bnoordhuis** [comment]
If you only have x86 libs, download the 32 bits version of node.  I don't know the answer to your other question.

**Comment by kwzm** [comment]
Thanks a lot.
Finally i build the addon successfully.
But have error when execute this addon:

```
%1 is not a valid Win32 application.
```

I think is arch problem like you said, my addon is build by x86 way but my node is 64 bits.

So if we need to build different bits addon in order to let different platforms users to choose which addon to use when we want to build a be widely used addon ?

Looking forward to your reply.

**Comment by bnoordhuis** [comment]
Yes, that error means there is a 32/64 bits mismatch.

I don't quite understand what you ask next but if it's how to build for 64 bits, I think you'll have to consult the Boost documentation.

**Comment by refack** [comment]
@kwzm just FYI - Boost provide pre-built binaries for windows in all sort of flavors -
 https://sourceforge.net/projects/boost/files/boost-binaries/1.65.1/

**Comment by kwzm** [comment]
@bnoordhuis  Please forgive my broken English, i didn't explain clearly. I think I'll ask someone else in my company. I will close the issue. Thank you very much for your help.

**Comment by refack** [comment]
@kwzm if you manage to resolve this, could you please post the solution in case anyone else finds the same issue?

**Comment by kwzm** [comment]
@refack Thanks for your advice, the official website does write in detail.

**Comment by kwzm** [comment]
@refack OK, i will summarize the solution and post in next week.

ps: Have a nice weekend :)

**Comment by kwzm** [comment]
1、Ensure you have this lib in your local environment. libboost_filesystem-vc140-mt-s-1_65_1.lib didn't in my disk because i  executed the default compilation configuration. Your need set `runtime-link=static` to get this lib.
For detail:  [http://www.boost.org/](http://www.boost.org/)     
2、Add link-settings in your binding.gyp file, like this:

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon_boost.cpp" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "D:/boost_1_65_1"
      ],
      "link-settings": {
         "libraries": [
             "D:\boost_1_65_1\stage\lib\libboost_filesystem-vc140-mt-s-1_65_1.lib"
          ]
       }
    }
  ]
}
```

3、 Your need to match the node bits with your addon compiled bits . Use `--arch=$arch` to compile what bits addon you need. Use `node -p process.arch` to query your node bits.
