### ISSUE TITLE
Add --help for all commands.

### ISSUE THREAD

**Issue by TooTallNate** [nodejs/node-gyp#13]

**Comment by Trott** [comment]
Is this still considered a desirable addition? If so, maybe we can add a "help wanted" or "good first contribution" label? If not, then I guess we should close the issue. @nodejs/node-gyp

**Comment by gibfahn** [comment]
I think it's worth doing, and the standard that I've seen in other projects is to add a help subcommand, so you can do `node-gyp help configure` to get the help for configure.

**Comment by owl-from-hogvarts** [comment]
Any progress here?

**Comment by Trott** [comment]
`npx node-gyp --help` produces meaningful output so I think this is finally close-able after more than 12 years?
