### ISSUE TITLE
ERR! Error: EXDEV, link '/usr/lib/node_modules/npm/node_modules/node-gyp/legacy/tools/gyp/gyptest.pyc'

### ISSUE THREAD

**Issue by navaneeth** [nodejs/node-gyp#130]
Hello,

I am deploying my nodejs application in OpenShift, Redhat's cloud. Currently I am using the free tier and the whole environment is very restricted. I don't have access to create directories in my HOME path. I have got a node module that uses node-gyp for building. When I install it using npm, node-gyp fails with error 

```
ERR! Error: EACCES, mkdir '/var/lib/stickshift/my-user-hash/.node-gyp'
```

This is because I don't have write permission to the home directory. 

Doing something like,

```
HOME=. npm install
```

also fails with error

```
ERR! Error: EXDEV, link '/usr/lib/node_modules/npm/node_modules/node-gyp/legacy/tools/gyp/gyptest.pyc
```

Is this an issue with node-gyp? How will I workaround this?

Thanks

**Comment by Trott** [comment]
It seems like perhaps this should be closed (or, if still an issue, perhaps directed to Red Hat support?). Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.
