### ISSUE TITLE
node-gyp configure build fails when npm install

### ISSUE THREAD

**Issue by rarehonour** [nodejs/node-gyp#1305]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "bui
ld"
gyp ERR! cwd D:\work-ahlad\node-bluetooth-obd-master\node_modules\bluetooth-seri
al-port
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bluetooth-serial-port@2.1.5 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bluetooth-serial-port@2.1.5 install script 'node-gyp conf
igure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bluetooth-serial-port
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bluetooth-serial-port
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bluetooth-serial-port
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work-ahlad\node-bluetooth-obd-master\npm-debug.log

**Comment by bnoordhuis** [comment]
You haven't included the actual error.  It's probably a few lines up.  As well, note this:

> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the bluetooth-serial-port
package

I.e., not node-gyp.

**Comment by rarehonour** [comment]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets
(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') can
not be found. To build using the v120 build tools, please install v120 build to
ols.  Alternatively, you may upgrade to the current Visual Studio tools by sele
cting the Project menu or right-click the solution, and then selecting "Retarge
t solution". [D:\work-ahlad\node-bluetooth-obd-master\node_modules\bluetooth-se
rial-port\build\BluetoothSerialPort.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets
(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') can
not be found. To build using the v120 build tools, please install v120 build to
ols.  Alternatively, you may upgrade to the current Visual Studio tools by sele
cting the Project menu or right-click the solution, and then selecting "Retarge
t solution". [D:\work-ahlad\node-bluetooth-obd-master\node_modules\bluetooth-se
rial-port\build\BluetoothSerialPortServer.vcxproj]
gyp ERR! build error

this is the error that occurs.
