### ISSUE TITLE
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(35 6,5): error MSB6006: “CL.exe”已退出，代码为 -1073741515。 [C:\test\node_module s\ref\bui ld\binding.vcxproj]

### ISSUE THREAD

**Issue by Moneling** [nodejs/node-gyp#1313]
* **Node Version**:  `8.6.0`
* **npm Version**:  `5.3.0`
* **node-gyp Version**:  `3.6.2`
* **Platform**: `win7 32`
* **pyhton**: `2.7.3`
* **framwork**: `4.5.1`

<details><summary>when I excute the 'node-build' the error is **C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(35 6,5): error MSB6006: “CL.exe”已退出，代码为 -1073741515。 [C:\test\node_module s\ref\bui ld\binding.vcxproj]** ,`node-gyp confugure ` is ok ,the step is follow the `nodejs.org` guild </summary>

```

```

</details>

**Comment by bnoordhuis** [comment]
Can you post the complete build output?  Please use proper formatting.

**Comment by Moneling** [comment]
proper formating???

**Comment by Moneling** [comment]
G:\nwEnvirment\testAddDemo\deom>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | win32 | ia32
gyp info spawn D:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
D:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(35
6,5): error MSB6006: “CL.exe”已退出，代码为 -1073741515。 [G:\nwEnvirment\test
AddDemo\d
eom\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `D:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Users\jonin\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Users\\jonin\\AppDat
a\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd G:\nwEnvirment\testAddDemo\deom
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by Moneling** [comment]
G:\nwEnvirment\testAddDemo\deom>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.6.0 | win32 | ia32
gyp info spawn D:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
**D:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(35
6,5): error MSB6006: “CL.exe”已退出，代码为 -1073741515。 [G:\nwEnvirment\test
AddDemo\d
eom\build\addon.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `D:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Users\jonin\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Users\\jonin\\AppDat
a\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd G:\nwEnvirment\testAddDemo\deom
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by Moneling** [comment]
thanks

**Comment by Moneling** [comment]
when i build the project ,comand  run 'npm config set msvs_version  2013/2012 /2015 ' the different result below 

> npm config set msvs_version 2013 
```
D:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets
(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') can
not be found. To build using the v120 build tools, please install v120 build to
ols.  Alternatively, you may upgrade to the current Visual Studio tools by sele
cting the Project menu or right-click the solution, and then selecting "Retarge
t solution". [D:\workspace\ffitest\node_modules\ref\build\binding.vcxproj]
```

> npm config set msvs_version 2012

```
D:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets
(54,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset
 = 'v110') cannot be found. To build using the v110 build tools, please install
 Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current
 Visual Studio tools by selecting the Project menu or right-click the solution,
 and then selecting "Retarget solution". [D:\workspace\ffitest\node_modules\ref
\build\binding.vcxproj] 
```

>  npm config set msvs_version 2015


```

D:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(35
 6,5): error MSB6006: “CL.exe”已退出，代码为 -1073741515。 [D:\workspace\ffites
 t\node_modules\ref\build\binding.vcxproj]
```

**so I think is the msvs_version problem???**

**Comment by bnoordhuis** [comment]
What version of Visual Studio do you have installed?  Have you tried [windows-build-ools](https://github.com/nodejs/node-gyp#option-1)?

**Comment by bnoordhuis** [comment]
No follow-up, closing.

**Comment by shuaishenk** [comment]
I have the same problem.

**Comment by kingmoumoumou** [comment]
I have the same problem.

**Comment by gibfahn** [comment]
@shuaishenk @kingmoumoumou could you answer Ben's question?

>What version of Visual Studio do you have installed? Have you tried windows-build-tools?

**Comment by shuaishenk** [comment]
1.npm install -g node-gyp
2.npm install --global --msvs_version=2015 windows-build-tools  or install the .exe directly   .netframework4.5 required
3.unzip gtk+-bundle_2.22.1-20101229_win64.zip to c:\GTK
4.install libjpeg-turbo-1.5.2-vc64.exe  to c:\libjpeg-turbo64
5.npm install canvas --save
I have run it successfully as above.

**Comment by kingmoumoumou** [comment]
我是这样解决的:
![image](https://user-images.githubusercontent.com/8298993/36822223-daa472f8-1d31-11e8-93f2-5ede498f6153.png)
在C++这里,可以看到没有安装, 我的是安装后就OK了. 我的图片是安装后的, 没有安装的时候,只有2个, 我安装的是8.1那个.占用空间少一些!

**Comment by gibfahn** [comment]
cc/ @nodejs/platform-windows

**Comment by seishun** [comment]
I don't read Chinese, so I can't help. I would suggest creating a new issue anyway, this one has too much noise.
