### ISSUE TITLE
Link to a mingw dll ?

### ISSUE THREAD

**Issue by MatthD** [nodejs/node-gyp#1316]
Hi everyone,

I want to cross-compile my node addons for windows & I am having difficulties to do it, the library I want to link is poppler .

I builded it for windows using mingw, is it possible to link to the dll created via mingw ? 

Thanks

**Comment by bnoordhuis** [comment]
Is it a C or C++ library?  C should work, C++ won't - MinGW and Visual Studio use incompatible name mangling schemes.  Node.js is built with Visual Studio, therefore your add-on should to.

**Comment by bnoordhuis** [comment]
No answer, closing.
