### ISSUE TITLE
Python 3 incompatability issue

### ISSUE THREAD

**Issue by betteridiot** [nodejs/node-gyp#1320]
* **Node Version**:  v8.1.2
* **Platform**: Windows 10 x64
* **Module**:node-gyp, electron-forge

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
if not defined npm_config_node_gyp (node "C:\Users\<USR>\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" configure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\envs\python27\python.EXE -c import platform; print(platform.python_version());
gyp ERR! stack   File "C:\ProgramData\Anaconda3\Lib\site.py", line 177
gyp ERR! stack     file=sys.stderr)
gyp ERR! stack         ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:270:12)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:548:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MDS\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\MDS
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
</details>

First, this isn't really an issue, but more of a workaround.
So, in trying to use `electron-forge` to `make` installers for a program, I kept getting derivations of this error. In tracking the stack, I found the problem was with `node-gyp`. Being a Windows and Python 3 user, a lot of places were saying to set your `PYTHON` variable to an installed `npm install --global --production windows-build-tools` python27 executable. However, the way Anaconda installs Python 3 (if you let it) is set your `PYTHONPATH` variable to its directory. Now, I thought I would be smart and just create a `conda env` for python2.7 and get around this. The problem persisted. The `PYTHONPATH` environmental variable kept pointing to python3 scripts, while my `PYTHON` path and current environment were pointing to python27.

The main issue were these two lines:
`C:\ProgramData\Anaconda3\envs\python27\python.EXE -c import platform; print(platform.python_version())`
`C:\ProgramData\Anaconda3\envs\python27\python.EXE -2 -c import sys; print sys.executable`\

So, I hard-coded the `'-E' `argument into the 3 `configure.js` scripts installed (under electron-forge/node_modules/node-gyp, node-gyp, and npm/node_modules/node-gyp) so that my current env now ignores the `PYTHONPATH` environment variables when `python` is called.

This solved the issue for me, so I am just passing it on. Hope it helps.

**Comment by gibfahn** [comment]
Thanks for documenting this! Hopefully it helps someone else.

I think there's nothing for us to do here, so this can be closed, let me know if I'm mistaken and I'll reopen.

**Comment by YonathanB** [comment]
Can you give a bit of more info.
Seems I have the same issue.
I'm using [webfonts-generator](https://github.com/sunflowerdeath/webfonts-generator), which have a dependency to node-gyp. 

On install I have the following error:
```
 C:\Python34\python.EXE -c import sys
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax
```
Can you help or do you think I have to open a separated issue?
