### ISSUE TITLE
node-gyp on Windows

### ISSUE THREAD

**Issue by shawnwhinnery** [nodejs/node-gyp#1321]
pure cancer

**Comment by refack** [comment]
The team is aware of the challenges for using node-gyp on Windows. But there is no place for this sort of expression.
Please edit your comment.

**Comment by refack** [comment]
Original comment deleted as it violated the CoC by:
Failing to be
* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
And exhibiting:
* Trolling, insulting/derogatory comments, and personal or political attacks
