### ISSUE TITLE
node-pre-gyp ERR! node -v v8.9.0 node-pre-gyp ERR! node-pre-gyp -v v0.6.39 node-pre-gyp ERR! not ok

### ISSUE THREAD

**Issue by luhan0420** [nodejs/node-gyp#1322]
$ npm install -g node-inspector

> v8-profiler@5.7.0 preinstall C:\Users\Administrator\AppData\Roaming\npm\node_m                                                                                                                                                                                               odules\node-inspector\node_modules\v8-profiler
> node -e 'process.exit(0)'

> v8-debug@1.0.1 preinstall C:\Users\Administrator\AppData\Roaming\npm\node_modu                                                                                                                                                                                               les\node-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'

C:\Users\Administrator\AppData\Roaming\npm\node-inspector -> C:\Users\Administra                                                                                                                                                                                               tor\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js
C:\Users\Administrator\AppData\Roaming\npm\node-debug -> C:\Users\Administrator\                                                                                                                                                                                               AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js

> v8-debug@1.0.1 install C:\Users\Administrator\AppData\Roaming\npm\node_modules                                                                                                                                                                                               \node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.co                                                                                                                                                                                               m/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.9.0                                                                                                                                                                                                (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                                                                                                                                                                               HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Administrator\AppData\                                                                                                                                                                                               Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\AppData\R                                                                                                                                                                                               oaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\np                                                                                                                                                                                               m\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\node\\node.exe" "C:\\Users\\Administrator\\AppData\\Roamin                                                                                                                                                                                               g\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"                                                                                                                                                                                                "--fallback-to-build" "--module=C:\\Users\\Administrator\\AppData\\Roaming\\npm                                                                                                                                                                                               \\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\no                                                                                                                                                                                               de-v57-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\Ad                                                                                                                                                                                               ministrator\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\                                                                                                                                                                                               v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-inspec                                                                                                                                                                                               tor\node_modules\v8-debug
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\node\node.exe C:\Users\Admi                                                                                                                                                                                               nistrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gy                                                                                                                                                                                               p.js configure --fallback-to-build --module=C:\Users\Administrator\AppData\Roami                                                                                                                                                                                               ng\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node                                                                                                                                                                                               -v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Administrat                                                                                                                                                                                               or\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\d                                                                                                                                                                                               ebug\v1.0.1\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\                                                                                                                                                                                               AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\ut                                                                                                                                                                                               il\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                                                                                                                                                               ld_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "D:\\node\\node.exe" "C:\\Users\\Administrator\\AppDat                                                                                                                                                                                               a\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\                                                                                                                                                                                               node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\no                                                                                                                                                                                               de-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'D:\node\node.exe C:\Users\Administrator\AppData\Roaming\npm\n                                                                                                                                                                                               ode_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-bu                                                                                                                                                                                               ild --module=C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-inspec                                                                                                                                                                                               tor\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --mod                                                                                                                                                                                               ule_name=debug --module_path=C:\Users\Administrator\AppData\Roaming\npm\node_mod                                                                                                                                                                                               ules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64'                                                                                                                                                                                                (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                                                               ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-03T0                                                                                                                                                                                               3_39_41_406Z-debug.log

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by bnoordhuis** [comment]
This is the error:

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT HON env variable.

You need python 2.7.  You can set it in your npmrc so you don't have to set it in the environment every time (although node-gyp will usually find python if it's installed in a default location.)
