### ISSUE TITLE
node-gyp build geoip2 error xcode 9.1

### ISSUE THREAD

**Issue by makoy21** [nodejs/node-gyp#1327]
* **Node Version**: v8.6.0  and 5.5.1
* **Platform**: macOS Sieerra 10.12.6 
* **Compiler**: 
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

* **Module**: geoip2

<details>
<summary>Verbose output (from npm or node-gyp):
<img width="1331" alt="error" src="https://user-images.githubusercontent.com/9860394/32429765-1484681e-c307-11e7-9cd8-d4df1a683660.png">

</summary>

```

```

</details>

**Comment by bnoordhuis** [comment]
That's not a node-gyp issue.  Report it to libmaxminddb.
