### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-gyp#1337]
See ~#1150~, ~#1335~, ~#1336~, and ~https://travis-ci.com/nodejs/node/builds/79706150~ (~nodejs/node#21942~)

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by richardlau** [comment]
Historically the blocker to this has been the gyp dependency and normally changes should be upstreamed there unless we're planning on forking gyp in which case we would want our own gyp project so that we can share the changes with the main Node.js project.

cc @nodejs/gyp

**Comment by mthacker801** [comment]
I cannot successfully install Angular on my mac.  I keep getting gyp error and when I look at gyp-mac-tool it says:
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/thackerfam/AngularProj/angular-cli/node_modules/which/which.js:13:12)

I have had python 3 installed forever and do not want python 2 as it can cause havoc to have both installed as they are not compatible with one another.  If this is the reason for my inability to use Angular, what should I do?

**Comment by cclauss** [comment]
What happens when you do:
* __python2 --version__
* __/usr/bin/python --version__
* __/usr/bin/python2 --version__
* __/usr/bin/python2.7 --version__

I would highly recommend [Homebrew](https://brew.sh) as essential if you are doing real development on a Mac.  You can easily install [both Python 2 and Python3](https://docs.brew.sh/Homebrew-and-Python.html) with: __brew install python2 python3__

See:

**Comment by cclauss** [comment]
A few Python __2__ issues on [__gyp__](https://chromium.googlesource.com/external/gyp):

$ python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
```
./gyptest.py:61:47: F821 undefined name 'opts'
    extra_path = [os.path.abspath(p) for p in opts.path]  # <-- 'opts' should be changed to 'args'
                                              ^
./pylib/gyp/generator/make.py:1637:50: F821 undefined name 'target'
      print "WARNING: no output for", self.type, target  # <-- 'target' should be changes to 'self.target'
                                                 ^
```

**Comment by SatishMHiremath** [comment]
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @latest

angular client project folder path>npm install -g node-gyp

**Comment by stanleyxu2005** [comment]
Is it possible to git rid off python at all? A node tool is relying on Python, which means we cannot fully drop off python. One more embracing thing is, we tried to take advantage of async/await of python, which means we have to ask user to install python 3. Now the node-gyp only supports python 2, so I either have to ask user to have 2 python runtime on machine, or prebuilt node modules for users. Hope we really have a solution without python.

**Comment by stanleyxu2005** [comment]
It's a bit embraced that the original gyp project relies on python 2, and after couple of years, the patch is getting too big so that no people is dare to review and merge it. Need to give the gyp community more feedback to move this forward.

**Comment by AdamMajer** [comment]
Is there any interest in this? Python 2 is starting to get removed from distributions at this point.

**Comment by timoxley** [comment]
> Python 2 is starting to get removed from distributions at this point.

Correct e.g. `brew` is now installing/upgrading to Python 3 by default.

The following just worked for me as I already had a `python2.7` executable installed via `brew`:

```
npm config set python python2.7
```

However, if you don't have a `python2.7` executable, I suspect can do something like:

```bash
brew install python@2
# follow the instructions printed after installing `python@2` to get python 2 on your PATH 
# e.g. echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.bashrc
npm config set python python2.7
```

**Comment by NetOperatorWibby** [comment]
Tim's method should go in the README. I use ZSH and there was a message mentioned Xcode when I installed Python 2 so my process was as follows:

```bash
xcode-select --install

brew install python@2
echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.zshrc
npm config set python python2.7
```

**Comment by cclauss** [comment]
What does __python2.7 --version__ return on your machine?

**Comment by ioquatix** [comment]
```
> python2.7 --version
Python 2.7.14
```

**Comment by ioquatix** [comment]
Here is the full error

```
^_^ > apm install      
Installing modules ✗
> node-pty@0.7.4 install /Users/samuel/.atom/packages/script-runner/node_modules/node-pty
> node scripts/install.js

script-runner@3.0.0 /Users/samuel/.atom/packages/script-runner
├── etch@0.14.0 
├── resize-observer-polyfill@1.5.0 
├─┬ shell-environment@0.3.1 
│ └─┬ os-locale@2.1.0 
│   ├─┬ execa@0.7.0 
│   │ ├─┬ cross-spawn@5.1.0 
│   │ │ ├─┬ lru-cache@4.1.2 
│   │ │ │ ├── pseudomap@1.0.2 
│   │ │ │ └── yallist@2.1.2 
│   │ │ ├─┬ shebang-command@1.2.0 
│   │ │ │ └── shebang-regex@1.0.0 
│   │ │ └─┬ which@1.3.0 
│   │ │   └── isexe@2.0.0 
│   │ ├── get-stream@3.0.0 
│   │ ├─┬ npm-run-path@2.0.2 
│   │ │ └── path-key@2.0.1 
│   │ ├── p-finally@1.0.0 
│   │ ├── signal-exit@3.0.2 
│   │ └── strip-eof@1.0.0 
│   ├─┬ lcid@1.0.0 
│   │ └── invert-kv@1.0.0 
│   └─┬ mem@1.1.0 
│     └── mimic-fn@1.2.0 
├── shellwords@0.1.1 
├─┬ temp-write@3.4.0 
│ ├── graceful-fs@4.1.11 
│ ├── is-stream@1.1.0 
│ ├── make-dir@1.2.0 
│ ├── pify@3.0.0 
│ ├── temp-dir@1.0.0 
│ └── uuid@3.2.1 
└── xterm@3.3.0 


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/samuel/.atom/packages/script-runner/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 17.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/samuel/.atom/.apm/.apmrc" "--userconfig" "/Users/samuel/.atom/.apmrc" "install" "--runtime=electron" "--target=1.7.11" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.7.4 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.7.4 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/samuel/.atom/packages/script-runner/npm-debug.log
```

Here is my config

```
 > apm config list
; cli configs
globalconfig = "/Users/samuel/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 darwin x64"
userconfig = "/Users/samuel/.atom/.apmrc"

; environment configs
node-gyp = "/Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp"
python = "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"

; userconfig /Users/samuel/.atom/.apmrc

; globalconfig /Users/samuel/.atom/.apm/.apmrc
cache = "/Users/samuel/.atom/.apm"
progress = false

; node bin location = /Applications/Atom.app/Contents/Resources/app/apm/bin/node
; cwd = /Users/samuel/.atom/packages/script-runner
; HOME = /Users/samuel/.atom/.node-gyp
; "npm config ls -l" to show all defaults.

^_^ > npm config list
; cli configs
user-agent = "npm/3.10.10 node/v8.10.0 darwin x64"

; userconfig /Users/samuel/.npmrc
init.author.email = "samuel.williams@oriontransfer.co.nz"
init.author.name = "Samuel Williams"
init.author.url = "http://www.codeotaku.com"
python = "python2.7"

; node bin location = /opt/local/bin/node
; cwd = /Users/samuel/.atom/packages/script-runner
; HOME = /Users/samuel
; "npm config ls -l" to show all defaults.
```

Hmm, I'm sure I also had `apm config set python=python2.7`. Maybe that's why it's not working.

**Comment by ioquatix** [comment]
That's odd, maybe it's a bug in `apm`.

```
> apm config set python python2.7
> apm config list                
; cli configs
globalconfig = "/Users/samuel/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 darwin x64"
userconfig = "/Users/samuel/.atom/.apmrc"

; environment configs
node-gyp = "/Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp"
python = "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"

; userconfig /Users/samuel/.atom/.apmrc

; globalconfig /Users/samuel/.atom/.apm/.apmrc
cache = "/Users/samuel/.atom/.apm"
progress = false

; node bin location = /Applications/Atom.app/Contents/Resources/app/apm/bin/node
; cwd = /Users/samuel/.atom/packages/script-runner
; HOME = /Users/samuel/.atom/.node-gyp
; "npm config ls -l" to show all defaults.
```

Even thought I set it, it's not changed in the config!?

**Comment by raininja** [comment]
@ioquatix what does "apm config get" show?

```
[raijin@ishtar][~]%apm config get
; cli configs
globalconfig = "/home/raijin/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 linux x64"
userconfig = "/home/raijin/.atom/.apmrc"

; environment configs
node-gyp = "/usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp"

; userconfig /home/raijin/.atom/.apmrc
python = "python2.7"

; globalconfig /home/raijin/.atom/.apm/.apmrc
cache = "/home/raijin/.atom/.apm"
progress = false

; node bin location = /usr/share/atom/resources/app/apm/bin/node
; cwd = /home/raijin
; HOME = /home/raijin/.atom/.node-gyp
; "npm config ls -l" to show all defaults.
```

**Comment by ioquatix** [comment]
```
koyoko% apm config get
; cli configs
globalconfig = "/home/samuel/.atom/.apm/.apmrc"
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.0.0 node/v10.0.0 linux x64"
userconfig = "/home/samuel/.atom/.apmrc"

; environment configs
python = "/usr/lib/node_modules/atom-package-manager/bin/python-interceptor.sh"

; project config /home/samuel/.npmrc
strict-ssl = true

; globalconfig /home/samuel/.atom/.apm/.apmrc
cache = "/home/samuel/.atom/.apm"
progress = false

; node bin location = /usr/bin/node
; cwd = /home/samuel
; HOME = /home/samuel/.atom/.node-gyp
; "npm config ls -l" to show all defaults.

koyoko% apm config set python foo
koyoko% apm config get           
; cli configs
globalconfig = "/home/samuel/.atom/.apm/.apmrc"
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.0.0 node/v10.0.0 linux x64"
userconfig = "/home/samuel/.atom/.apmrc"

; environment configs
python = "/usr/lib/node_modules/atom-package-manager/bin/python-interceptor.sh"

; project config /home/samuel/.npmrc
strict-ssl = true

; userconfig /home/samuel/.atom/.apmrc

; globalconfig /home/samuel/.atom/.apm/.apmrc
cache = "/home/samuel/.atom/.apm"
progress = false

; node bin location = /usr/bin/node
; cwd = /home/samuel
; HOME = /home/samuel/.atom/.node-gyp
; "npm config ls -l" to show all defaults.
```

**Comment by brennon** [comment]
It's one thing to _retain_ support for Python 2 (though many projects are dropping it altogether). It's another thing entirely to _not _ support Python 3. Please consider this. Python 3 is a decade old, after all... :smile:

**Comment by ioquatix** [comment]
What is GN?

**Comment by Croydon** [comment]
https://chromium.googlesource.com/chromium/src/tools/gn/#what-is-gn

**Comment by raininja** [comment]
Yea but this thread https://groups.google.com/forum/#!topic/gyp-developer/U66xtisrYRM says it's just a matter of Dirk landing and reviewing the patch.

**Comment by raininja** [comment]
My question is this: why can't we just fork gyp and add the patch and go with that?

**Comment by cclauss** [comment]
There is no reason why not.  That is the way of open source.  If no maintainer steps forward with a cogent plan that fits your needs, you can always hit the __fork__ button.

**Comment by conradwt** [comment]
Is there any movement on node-gyp compatible with Python 3.6+ as it does make any sense to downgrade to Python 2.7?  Is the issue with the `gyp` src?  If this is the case, what does one need to do to upgrade this module?

**Comment by George35mk** [comment]
Let's contribute to the deno project.
> https://github.com/ry/deno

**Comment by cclauss** [comment]
They too seem to be [focused on legacy Python](https://github.com/ry/deno/pull/391#issuecomment-406826528) at a time when EOL is only about 500 days away.

**Comment by cclauss** [comment]
Do the math dude!  http://pythonclock.org

**Comment by NetOperatorWibby** [comment]
...I forgot what year it was.

**Comment by KiYugadgeter** [comment]
Should it use six to keep compatibility?

**Comment by andi1984** [comment]
> Is there any movement on node-gyp compatible with Python 3.6+ as it does make any sense to downgrade to Python 2.7 on my system? Is the issue with the `gyp` src? If this is the case, what does one need to do resolve the issue?

Did we get an answer on that? Please let us know what the underlying issue is, so that we can work on allowing having Python 3 used. We do not have to remove support for Python 2, but we should definitely have support for Python 3.

**Comment by refack** [comment]
So https://github.com/nodejs/node-gyp/pull/1335 landed. Now we need to fix the python detection logic in the JS part

**Comment by VenkataChadalawada** [comment]
I got python 3.7 as I installed Anaconda in my new macOSx , Then I had to configure my nodejs project and when I did it it started giving me Error: Can't find Python executable After following the thread I installed python2.7 via home brew and set my npm
echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.bash_profile
npm config set python /usr/local/opt/python@2/bin
still I see gyp 
ERR! stack Error: Can't find Python executable "/usr/local/opt/python@2/bin", you can set the PYTHON env variable.

Any clues on what exactly I need to do to solve my problem happily do npm install?

**Comment by VenkataChadalawada** [comment]
I think I figured it out. I got it working by below steps
I installed python@2 with homebrew . 
1. npm config set python /usr/local/opt/python@2/bin/python2.7
2.echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.bash_profile
3.sudo xcode-select -switch /Library/Developer/CommandLineTools (actually this didn't work for me) then I opened Xcode -> preferences ->location -> opted xcode10 CommandLineTools(third tab)

**Comment by fenchu** [comment]
Any action here: with nodejs 10.13LTS you still ned python2:
```
C:\Users\morten.sensio\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp
(node "C:\dist\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "C:\dist\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\python\Python371\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
```
if you are mainly on python2.7.x or higher most frequent python3 features have been backported like:
```
D:\python\Python371\python.EXE -c "import sys; print('%s.%s.%s' % sys.version_info[:3])"
3.7.1
D:\python\Python2715\python.EXE -c "import sys; print('%s.%s.%s' % sys.version_info[:3])"
2.7.15
```

**Comment by cclauss** [comment]
That code is now at https://github.com/nodejs/node-gyp/commit/a6990ada1f1147cb6da7ceaa0bb7c8333c9c7ae6#diff-7ad6309831a48a234780b58baca65710R374

**Comment by methane** [comment]
FYI, Python 3 support is committed on gyp repository:
https://github.com/chromium/gyp/commits/master

**Comment by cclauss** [comment]
@methane @dpranke On the https://github.com/chromium/gyp repo flake8 still spots at least two Python 3 syntax errors.  I would open an issue or a PR there but they _do not accept_ issues or PRs.
```
./tools/pretty_vcproj.py:66:18: E999 SyntaxError: invalid syntax
      print '%s%s' % (' '*indent, node.data.strip())
                 ^
./pylib/gyp/mac_tool.py:673:59: E999 SyntaxError: invalid syntax
  max_value_length = len(max(filelist.items(), key=lambda (k,v):len(v))[1])
                                                          ^
```

**Comment by cclauss** [comment]
Really nice work!

**Comment by cclauss** [comment]
Where are we on this issue folks??  PRs are no longer getting reviewed?  How do we make progress once again?

**Comment by morenoh149** [comment]
Not sure I see I fix above or not. I have this issue opened where I can't install the module on osx https://github.com/ethereumjs/helpeth/issues/25 should node-gyp be updated in the project?

**Comment by rvagg** [comment]
Discussing this and related issues https://github.com/nodejs/TSC/issues/642, if anyone here is passionate about python & node then you might want to join in on a working group or strategic initiative we may start to figure out an approach to moving ourselves beyond this mess. node-gyp is such a critical piece of Node ecosystem infrastructure that touching it carries a lot of risk, hence some of the hesitancy moving forward too fast on any of this. It's going to be extremely sensitive to breakage and edge cases and this repo already gets more support issues than we can handle.

**Comment by cclauss** [comment]
I am happy to remain engaged in the effort but would appreciate help.  Where there are effective JavaScript solutions, we should transition to those.

> node-gyp is such a critical piece of Node ecosystem infrastructure

One year from now, there will be no more updates -- not even security updates -- to legacy Python.   Node ecosystem infrastructure is too strategic and widely used to be based on unsupported code so by 1/1/2020, we really want no Python 2 in this codebase.  If there are acceptable JavaScript substitutes then we should switch to them but this codebase really should not rely on Python 2.  The sunsetting of Python 2 has already been delayed five years so that community is now quite emphatic on the _no more updates_ policy.  This is fair given that Python 3 predates Node.js.

**Comment by lalomartins** [comment]
I think you're 10 years too late to be talking about “moving forward too fast”.

**Comment by cclauss** [comment]
Over a year ago #1336 attempted to directly link pull requests to automated tests so that contributors and reviewers had ✅ or ❌ to give them a sanity check on PRs.  Can we please something similar working on this repo?

Some tactical steps (going down a path of _porting_ what we have, instead of replacing):
- [ ] Get __nodejs/build__ linting machines running both Python 2 and Python 3
    - [ ] nodejs/build#1639
    - [ ] nodejs/build#1644
    - [ ] nodejs/node#25118
    - [ ] nodejs/build#1631
- [ ] Get Travis CI kicking off automated tests on this repo (#1336 or similar)
- [ ] Get nodejs/node-gyp to be Python 3 syntax compatible
    - [ ] #1611
    - [ ] #1612
    - [ ] #1613
    - [ ] #1614
    - [ ] #1615

One important way that everyone can help is to review the above PRs.

**Comment by Krinkle** [comment]
**https://pythonclock.org** Python 2.7 will reach end-of-life after December 31, 2019.

python2.7 is not installed on Debian 9 Stretch by default it seems, which means unless sysadmins install it explicitly, node projects involving node-gyp somewhere in their dependencies fail to install properly.

**Comment by goddenrich** [comment]
We are transitioning to not supporting python2 anymore. This is the only blocker stopping us from doing this. Im really looking forward to when node-gyp can use python3

**Comment by FranklinYu** [comment]
> Where there are effective JavaScript solutions, we should transition to those.

@cclauss I prefer a pure JavaScript solution, and I would like to help. Is there already an issue discussing the possibility of switching to pure-JavaScript compiling solutions? I guess it would be off-topic to discuss it here.

**Comment by mhdawson** [comment]
@cclauss do you think this is being progressed under https://github.com/nodejs/TSC/issues/642 or is there something we need to action in this issue?

**Comment by cclauss** [comment]
@mhdawson I would love to see progress on #1336 ...  It seems so simple but it has been a _loonng_ time.

https://github.com/nodejs/node-gyp/issues/1337#issuecomment-448581154 is still our running list...  Some progress has been made but still several items are open awaiting review.  More active reviewers would be a beautiful thing.  Also, we are going to need build machines to have Python 3 loaded on them in addition to Python 2 so that we can be sure that tests pass on both versions of Python.

**Comment by vogt31337** [comment]
I don't quite understand the need for Python 2.7 (also it is clocking down [less than a year](https://pythonclock.org/)). 
Wouldn't it be possible to write the python code so that a python 3 interpreter is happy? I've written such code in the past which would run on both py2 and py3. And maybe this could be used for some simple use cases...

**Comment by cclauss** [comment]
@vogt31337 It is a BIG codebase.  See https://github.com/refack/GYP to get a sense of how many changes we required to get it compatible with Python 3.

**Comment by megakoresh** [comment]
> @vogt31337 It is a BIG codebase.  See https://github.com/refack/GYP to get a sense of how many changes were required to get it compatible with Python 3.

I hope we can finally do away with Python 2, I am sure node-gyp is for many the last blocker remaining.

Although I do not personally quite understand why node.js really needs this wrapper around the build tool instead of letting libraries take care of it themselves (you have to install native libraries for many native modules anyway, so its not like node-gyp and gyp itself solve the "per-library requirement" problem), but that's a different story.

**Comment by iMichka** [comment]
Hi. Homebrew maintainer here.

I just wanted to notify the node maintainers that we started the discussions around the Python 2 removal from the Homebrew package manager. Node is one of the last “big” packages that does not support Python 3. I would like to avoid a situation where we would need to remove node from brew. Node is in our top 3 of installed packages, with more than 4 million install events per year. 

Right now we are just gathering opinions https://discourse.brew.sh/t/python-2-eol-2020/4647
No decision has been taken yet.

Options go from plain removal, additional grace period of a few months, moving node to an external tap outside of our org, or any other idea that will come up in the next weeks.

**Comment by rvagg** [comment]
Thanks @iMichka, we have a team that's trying hard to bring Node up to Python 3 support. Unfortunately we missed out on the Node 12.0.0 window but we're acutely aware of the time pressures of continuing our Python 2 requirement. @cclauss @refack @thefourtheye and others are working hard addressing our sprawling use of Python. I'm not sure we have a firm timeframe but this is a well known problem and we all feel the pressure (and bump up against it regularly!). I would hope that we can have it resolved within the next couple of months but I can't speak with any authority on that.

**Comment by cclauss** [comment]
> moving node to an external tap outside of our org
@iMichka Given that soon-to-be-released Node.js 12 will still _require_ legacy Python, can you please provide us with a sense of the degree of difficulty required to setup and maintain an _external tap_?  Are there other examples of external taps that your team considers to be well set up and maintained?

**Comment by scpeters** [comment]
I'm a homebrew maintainer, and I also maintain an external tap with bottles from private CI machines. It's super easy to make a tap and push formula updates to it. In my opinion, the bulk of the work is in getting bottles to build successfully and fixing inter-package compatibility problems. One hopefully useful option will be building homebrew bottles with something like Azure pipelines, as discussed in the following post:

* https://discourse.brew.sh/t/tap-bottles-how-to-publish-after-ci-upload-to-bintray/4674

**Comment by ladislas** [comment]
@cclauss to bounce back on what @scpeters was saying, setting up and maintaining a tap is pretty straight forward and easy.

The bottle part is a little trickier but I'm close to a fully working solution that would make it much easier for tap maintainer to distribute bottles for their taps.

I'll post here when it's ready.

**Comment by refack** [comment]
I'm commented in several other thread that one limiting factor for getting full Python3 compatibility for GYP3, and hence `node-gyp`, is having a proper CI testing setup. I've submitted https://github.com/nodejs/build/issues/1789 as for me setting up CI testing on the Node.js cluster is the lowest hanging fruit.

**Comment by iMichka** [comment]
> a sense of the degree of difficulty required to **set up and maintain an _external 

It is doable. The issue will be more about visibility. More than 4 million install events in a year through homebrew will mean that we need to communicate to all these people about the node removal from homebrew-core, and give instructions on how to tap the new node tap. All the install scripts from the whole industry will probably need an updated too. There will be no automatic redirection to an external tap.

I do not want to pollute this thread more with homebrew discussions though. We are not the only ones to ship node, so the issue is more global than this. Not sure this issue is the best place to discuss all this. We have not taken any decision right now, my initial message was more a gentle nudge to warn you that bigger changes may come :)

**Comment by AdamMajer** [comment]
> We are not the only ones to ship node, so the issue is more global than this.

Indeed, it's much more global than this. There has been discussion on removing python2 from openSUSE Tumbleweed distribution at beginning of next year. For those that don't know, Tumbleweed is the rolling release distribution of openSUSE project.

https://lists.opensuse.org/opensuse-factory/2019-04/msg00229.html

> on the bright fresh chilly morning of 2020-01-02 we are going to remove python2 package (that's python 2.7.* interpreter) from Factory.

**Comment by mingrammer** [comment]
Is this in progress?

**Comment by cclauss** [comment]
@mingrammer https://github.com/nodejs/node-gyp/pull/1723#issuecomment-498666816 lists some current Python 3 incompatibilities if you have some time to work on this.  We also created GYP3 https://github.com/nodejs/node/pull/26620

**Comment by MattIPv4** [comment]
Would it be possible to edit the opening post in this thread with a general summary of the situation with regards to the move to Python 3 due to the Python 2 EOL and drop from Brew/macOS/Linux distros? It'd be great if that could then be kept up to date so the average user can easily see an overview of the current situation and the plan going forward :)

**Comment by cclauss** [comment]
Closing this PR as __GYP__ seems to be Python 3 compatible:
* __node/node-gyp__ [Travis CI tests](https://github.com/nodejs/node-gyp/blob/master/.travis.yml) are run and pass on Linux and macOS.  Help needed on Windows #1801
* GYP3 https://github.com/refack/GYP is also of interest
* Chromium GYP is also making Python 3 progress https://chromium.googlesource.com/external/gyp

__If you find any Python 3 incompatibles in this code, please open an issue.__

NOTE: __nodejs/node__ is _not yet_ compatible with Python 3 but an effort is ongoing there.

**Comment by superern** [comment]
> > Python 2 is starting to get removed from distributions at this point.
> 
> Correct e.g. `brew` is now installing/upgrading to Python 3 by default.
> 
> The following just worked for me as I already had a `python2.7` executable installed via `brew`:
> 
> ```
> npm config set python python2.7
> ```
> 
> However, if you don't have a `python2.7` executable, I **suspect** you can do something like:
> 
> ```shell
> brew install python@2
> # follow the instructions printed after installing `python@2` to get python 2 on your PATH 
> # e.g. echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.bashrc
> npm config set python python2.7
> ```

Thanks! this resolves my issues

**Comment by slim-hmidi** [comment]
I'm using Node.js v 12.18.2 and Python v3.8.1 and when I tried to run `npm install` I got this error:
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\x199377\\AppData\\Local\\Programs\\Git\\react-whiteapp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\x199377\AppData\Local\Programs\Git\react-whiteapp\node_modules\node-sass
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

Please upgrade node-gyp to v7 https://github.com/nodejs/node-gyp/releases

**Comment by richardlau** [comment]
@slim-hmidi If you want to use Python 3 you'll have to take up with node-sass as they're still depending on node-gyp ^3.8.0: https://github.com/sass/node-sass/blob/e1fc1580c2e979113c95850b8ae5d83845063ca5/package.json#L67

node-gyp added Python 3 support in the 5.x and later releases.

**Comment by slim-hmidi** [comment]
@richardlau I installed python v2.7.16 but still the same problem.

**Comment by richardlau** [comment]
If you have the same problem it means that node-gyp is still trying to use Python 3. Maybe try setting the `PYTHON` environment variable to point to your installed Python 2?

**Comment by slim-hmidi** [comment]
I uninstalled python 3 and python 2.7.16 and I'm reinstalling python 2.7.16 again and I will try again.

**Comment by slim-hmidi** [comment]
@richardlau it works now. thanks
