### ISSUE TITLE
Windows instructions don't work for non-admin accounts

### ISSUE THREAD

**Issue by crashspringfield** [nodejs/node-gyp#1341]
* **Node Version**: node 8.9.1, npm 5.5.1
* **Platform**: Windows 7
* **Module**: node-sass

    Downloaded python-2.7.13.msi. Saved to C:\Users\MB\.windows-build-tools\python-2.7.13.msi.
    Starting installation...
    Please restart this script from an administrative PowerShell!
    The build tools cannot be installed without administrative rights.
    To fix, right-click on PowerShell and run "as Administrator".
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! windows-build-tools@1.3.2 postinstall: `node ./lib/index.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the windows-build-tools@1.3.2 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Why is it trying to install Python when Python is already installed and in my path?

**Comment by bnoordhuis** [comment]
You should ask the maintainers of the windows-build-tools package.
