### ISSUE TITLE
Weird orcexec.* file

### ISSUE THREAD

**Issue by BorntraegerMarc** [nodejs/node-gyp#1344]
* **Node Version**: v8.9.1 
* **Platform**: Windows (with linux-alpine docker container) 
* **Compiler**: - 
* **Module**: - 

When running a alpine linux container on Windows every time a new weird file called `orcexec.*` is generated. Where the asterisk * is a placeholder for any string. So sometimes a file `orcexec.oneelL` or sometimes a file `orcexec.BCElgM` is generated. [Apparently these files](https://askubuntu.com/questions/336552/what-are-orcexec-files) are for a JIT compiler.

The problem comes in when committing something to git: I see every time I start my linux server that a new file `orcexec.*` was added and that it can be committed.

Can I disable the `orcexec.*` files?

**Comment by bnoordhuis** [comment]
Can't help you, sorry.  You are asking in the wrong place, it's completely unrelated to node-gyp.
