### ISSUE TITLE
how to link a static library?

### ISSUE THREAD

**Issue by xiongzhend** [nodejs/node-gyp#1345]
I found it shows this as default: '-Dlibrary=shared_library', so I am wondering how could I use static library? I am in windows btw. Does it looks like > node-gyp rebuild --static

**Comment by bnoordhuis** [comment]
Can you be more specific?  Do you want to _link to_ or _link together_ a static library?  The former is not much different from linking to a shared library, just add it to the list of libraries to link in.

**Comment by xiongzhend** [comment]
I need use libbitcoin as node addon, on Mac I am succeed to write the binding.gyp, maybe because it is a shared library, but on Windows, the author said some of the function is not finish yet, so there is only static library can be used on Windows. But I don't know how to make the binding.gyp right. Here is the binding.gyp file:

**Comment by xiongzhend** [comment]
> {
    "targets": [
        {
            "target_name": "module1",
            "sources": [
                "module1.cpp"
            ],
            "conditions": [
                ["OS=='mac'", {
                    "xcode_settings": {
                        "GCC_ENABLE_CPP_RTTI": "YES",
                        "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
                        "OTHER_CFLAGS": [
                            "-std=c++11",
                            "-stdlib=libc++"
                        ]
                    },
                    "include_dirs": [
                        "/usr/local/include"
                    ],
                    "libraries": [
                        "/usr/local/lib/libbitcoin.dylib"
                    ]
                }],
                ["OS=='win'", {
                    "msvs_settings": {
                        "VCCLCompilerTool": {
                            'StringPooling': 'true', # pool string literals
							'DebugInformationFormat': 3, # Generate a PDB
							'WarningLevel': 3,
							'BufferSecurityCheck': 'true',
							'ExceptionHandling': 1, # /EHsc
							'SuppressStartupBanner': 'true',
							'WarnAsError': 'false',
                        }
                    },
                    "include_dirs": [
                        "../libbitcoin/include",
                    ],
                    "libraries": [
                        "../libbitcoin/bin/x64/Release/CTP_Nov2013/staticlibbitcoin.lib"
                    ]
                }]
            ]
        }
    ]
}

**Comment by xiongzhend** [comment]
If I run node-gyp rebuild, then it said like this:
**C:\code\libbitcoin\include\bitcoin/bitcoin/math/hash.hpp(25): fatal error C1083
: Cannot open include file: 'boost/functional/hash_fwd.hpp': No such file or di
rectory (..\module1.cpp) [C:\code\FrisbeeDog-CC\build\module1.vcxproj]**

**Comment by xiongzhend** [comment]
so I add boost dir into include section like this:

>  "include_dirs": [
                        "../libbitcoin/include",
"../libbitcoin/builds/msvc/vs2013/packages/boost.1.57.0.0/lib/native/include"
                    ],

then it show other errors, like:
**C:\code\libbitcoin\include\bitcoin/bitcoin/config/printer.hpp(52): error C2487:
 'max_arguments' : member of dll interface class may not be declared with dll i
nterface (..\module1.cpp) [C:\code\FrisbeeDog-CC\build\module1.vcxproj]
C:\code\libbitcoin\builds\msvc\vs2013\packages\boost.1.57.0.0\lib\native\includ
e\boost/log/detail/config.hpp(30): fatal error C1189: #error :  Boost.Log: RTTI
 is required by the library (..\module1.cpp) [C:\code\FrisbeeDog-CC\build\modul
e1.vcxproj]**

Can you figure out how to make it right?

**Comment by bnoordhuis** [comment]
The RTTI thing probably means you need to set `{'msvs_settings': 'VCCLCompilerTool': { 'RuntimeTypeInfo': 'true' } }` in your binding.gyp.

The other one is an issue with the library, not node-gyp.  I'll close this out because I can't help you with that.
