### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by danikuci1** [nodejs/node-gyp#1347]
hello-

I am having an issue during installation of an application and was pointed here.

Specifically, during installation the CLI outputs these errors:
`npm ERR! Failed at the epoll@0.1.22 install script 'node-gyp rebuild'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the epoll package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR! node-gyp rebuild`

and

`npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the sharp package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR! node-gyp rebuild`

See more details:
https://github.com/philipptrenz/photo-booth/issues/9

Any assistance you can offer would be fantastic. Thanks.

**Comment by bnoordhuis** [comment]
npm is telling you to report the issues to the modules you're trying to install, epoll and sharp, not node-gyp.

When you open an issue with those projects, include the full output - everything from `npm install` on down and make sure you have the prerequisites installed that are listed on https://github.com/nodejs/node-gyp.
