### ISSUE TITLE
freebsd 11.1-release node-gyp rebuild

### ISSUE THREAD

**Issue by cybermerlin** [nodejs/node-gyp#1348]
* **Node Version**: 
```
# node -v
v8.8.1
# npm -v
5.5.1
```
* **Platform**: 
```
 # uname -a
FreeBSD fbsd64_dev 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

```
* **Compiler**: 
```
# cc -v
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
```
* **Module**: 
node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
# node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | freebsd | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.8.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.8.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.8.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p4
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

```

</details>

```
# python2.7 --version
Python 2.7.14
```

**Comment by bnoordhuis** [comment]
Run node-gyp in the directory of the module you want to build or pass `--directory=/path/to/module`.  You're running it from / now.

**Comment by cybermerlin** [comment]
I want just rebuild global node-gyp

**Comment by cybermerlin** [comment]
I trying run and in global node_modules/node-gyp, but didn't help for me

**Comment by refack** [comment]
Hello @cybermerlin,
node-gyp itself does not need any building. It is only useful for building native addon modules, so you would either run it in the addon directory, or it's run automatically by npm while installing a packaged addon.

**Comment by cybermerlin** [comment]
not helpful

**Comment by bnoordhuis** [comment]
Neither is your comment.  If you want help, ask good questions.

**Comment by cybermerlin** [comment]
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/sinopia/node_modules/crypt3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/sinopia/node_modules/crypt3/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/sinopia/node_modules/crypt3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/sinopia/node_modules/crypt3/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/sinopia/node_modules/crypt3/.node-gyp"

**Comment by bnoordhuis** [comment]
*Good* questions.  That's not even a question.

**Comment by cybermerlin** [comment]
Good answer. That's not even a answer.

**Comment by bnoordhuis** [comment]
If you're going to be like that, go get lost.  You seem to be under the impression that you're entitled to support.  You're not.

**Comment by cybermerlin** [comment]
I just change source crypt3 and build with classic make.
Node-gyp I never will be used.

**Comment by bnoordhuis** [comment]
If that means we'll never see the likes of you again, I'd call that a win-win situation.

**Comment by cybermerlin** [comment]
suck my cocks

**Comment by cybermerlin** [comment]
only your fleas will worry about you

**Comment by bnoordhuis** [comment]
Comment deleted.  Next offense gets you an organization-wide ban.

**Comment by Reechajoshi** [comment]
try setting --unsafe-perm
