### ISSUE TITLE
node-gyp configure error Or npm Install error for nodejs project

### ISSUE THREAD

**Issue by Someshthati** [nodejs/node-gyp#1350]
Node Version : node@8.9.1
node-gyp version: node-gyp@3.6.2
Platform: Windows 10 64bit 
Module: NodeJs API (npm install)

* **Node Version**: node@8.9.1  & npm 5.5.1
* **Platform**: Windows 10 64 BIT
* **Compiler**: Windows
* **Module**: npm install (Node JS application)
<details>
> scrypt@6.0.3 preinstall C:\BlockChain\poctest\samplepoc\sampleapi\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\BlockChain\poctest\samplepoc\sampleapi\node_modules\scrypt
> node-gyp rebuild

C:\BlockChain\poctest\samplepoc\sampleapi\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Windows\System32\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
C:\Python27\python.exe: can't open file 'C:\Windows\System32\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (C:\Windows\System32\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\BlockChain\poctest\samplepoc\sampleapi\node_modules\scrypt
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-01T06_00_09_770Z-debug.log
[2017-12-01T06_00_09_770Z-debug.log](https://github.com/nodejs/node-gyp/files/1520601/2017-12-01T06_00_09_770Z-debug.log)

<summary>Log file attached</summary>

```

```

</details>

**Comment by bnoordhuis** [comment]
That's a problem with scrypt, not node-gyp.  Report your issue over there.
