### ISSUE TITLE
Change source files has no effect build output

### ISSUE THREAD

**Issue by oliverw** [nodejs/node-gyp#1355]
* **Node Version**: v8.9.1
* **Platform**: Linux PTC-NB 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
* **Module**: https://github.com/coinfoundry/node-multi-hashing

This is one of the strangest problems ever encountered when dealing with native extensions to interpreted/managed languages.

Steps to reproduce:

1. git clone https://github.com/coinfoundry/node-multi-hashing
2. cd node-multi-hashing
3. Edit multihashing.cc, remove all of the NAN_METHOD blocks
4. node-gyp rebuild
5. Delete node-multi-hashing/node_modules/multi-hashing/build/Release/multihashing.node of consuming NodeJS project
6. Run the consuming project and observe a module not found problem
5. Copy build/Release/multihashing.node to node-multi-hashing/node_modules/multi-hashing/build/Release of consuming NodeJS project
6. Invoke any of the functions supposedly exported by the native module and observe that they are still working 

Ironically, introducing an intentional syntax error in multihashing.cc yields the expected compiler error but any other functional change seems to be totally ignored. I can also strip out everything inside a NAN_METHOD, rebuild, copy and get the expected result when invoking the exported method. I can also remove files references through multihashing.cc from binding.gyp and not even get a linker error.

**Comment by bnoordhuis** [comment]
It sounds like you have a stray .node file somewhere that it's loading instead.  Since you're on linux, you can check with `strace -s 256 -e open,openat node app.js` what file it's actually opening.

**Comment by oliverw** [comment]
I thought so initially, but unfortunately that was not the case.

**Comment by oliverw** [comment]
The original author dispatched the method in question to the wrong implementation

`Nan::Set(target, Nan::New("lyra2re2").ToLocalChecked(), Nan::GetFunction(Nan::New<FunctionTemplate>(fresh)).ToLocalChecked());`
