### ISSUE TITLE
cross compile nodejs addons for arm on ubuntu

### ISSUE THREAD

**Issue by maitreyi-timesys** [nodejs/node-gyp#1358]
**Host Details**
* **Node Version**: 7.6.0
* **Platform**: Linux
* **Compiler**: Make
* **Module**: node-sqlite3

**Target Device Details**
**Node-JS versio**n = 0.12.7
**OS:** Linux
**npm** - not there
**node-gyp** - not there

I am trying to generate arm specific node-sqlite3 addon by following commands
1- Have set the env by sourcing the env generated from Toolchain
to set following
echo $CC
arm-poky-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi
echo $CXX
arm-poky-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi

2- Now invoking npm
sudo npm install sqlite3 --target_arch=arm --build-from-source=sqlite3 --target_platform=linux

This generates the lib/binding/node-v14-linux-arm/node_sqlite3.node but this is not compiled for arm platform rather for host environment

I have also tried using node-gyp and node-pre-gyp
but no success so far

Please see if there is anything wrong

**Comment by maitreyi-timesys** [comment]
I want to cross compile node-sqlite3 module for arm architecture Board from my Ubuntu Host
I have tried many attempts, but cross compiled addon not working on target.
Here are the details 
**Host/Dev Machine Details**
OS= Ubuntu 16.0.4
NodeJS = 7.6.0
npm = 5.5.1

**Target Device Details**
Node-JS version = 0.12.7
OS: Linux
npm - not there
node-gyp - not there

I have tried to generate arm specific node-sqlite3 addon by following commands
1- Have set the env by sourcing the env generated from Toolchain
to set following
echo  $CC 
arm-poky-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi
echo  $CXX
arm-poky-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi
 
2- Now invoking npm
sudo npm install sqlite3 --target_arch=arm --build-from-source=sqlite3 --target_platform=linux

This generates the lib/binding/node-v14-linux-arm/node_sqlite3.node but this is not compiled for arm platform rather for host environment

I have also tried using node-gyp and node-pre-gyp
but no success so far

Please see if there is anything wrong

**Comment by bnoordhuis** [comment]
See #829.  I'll close this out but thanks for the bug report.

**Comment by maitreyi-timesys** [comment]
Issue says its possible 
https://github.com/mapbox/node-sqlite3/issues/249
