### ISSUE TITLE
How to retrieve compiler capabilities in a GYP project file?

### ISSUE THREAD

**Issue by Kristian-Popov** [nodejs/node-gyp#1363]
Good evening!

Is it possible to retrieve tool chain capability (e.g. C++ standard supported) in gyp file? This would enable to write code that supports newer features of C++ while remaining backward compatible with older ones by providing an alternative implementation? If yes, it could be great to add this information into documentation.
If no, I'm pretty sure it would be a useful feature. May be compilers that don't support C++11 are pretty old now, but new C/C++ standards and features are coming.

Regards,
Kristian Popov

**Comment by bnoordhuis** [comment]
Feature detection beyond os/arch is not a goal for node-gyp.  What you want can probably be accomplished by checking the `__cplusplus` macro: 
```c++
#if __cplusplus >= 201103L
  // C++11
#else
  // C++03
#endif
```
There is also the `__has_feature()` macro but it's clang-only (which of course you can #ifdef on.)

**Comment by Kristian-Popov** [comment]
Makes sense, thanks for an clarification. Closing the issue.
