### ISSUE TITLE
Can I use VC2017 instead of VC2015?

### ISSUE THREAD

**Issue by chen4393** [nodejs/node-gyp#1364]
* **Node Version**: `node -v: v6.11.2` and `npm -v: 3.10.10`
* **Platform**: Windows
* **Compiler**: VC2017
* **Module**: react-native-maps

<details><summary>I have VS2017 and VC++ 2017 installed, can I use VC2017 instead of VC2015?</summary>

```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this,

install the .NET Framework 2.0 SDK,
install Microsoft Visual Studio 2005 or
add the location of the component to the system path if it is installed elsewhere. [C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

</details>

**Comment by chen4393** [comment]
`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this,

install the .NET Framework 2.0 SDK,
install Microsoft Visual Studio 2005 or
add the location of the component to the system path if it is installed elsewhere. [C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

**Comment by bnoordhuis** [comment]
Upgrade your copy of node-gyp to the latest.  VS 2017 is supported but not in v3.4.0.
