### ISSUE TITLE
Replace 'request' library

### ISSUE THREAD

**Issue by cktang88** [nodejs/node-gyp#1365]
It seems the only place the `request` library is used is in `lib/install.js`, where it's only used for a simple task.
The `request` library is 52 packages, which take up around 4.22 MB, which seems unjustified for the small one-time usage that it gets included for. Would a PR be welcome to replace it with a lightweight alternative, such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) or [simple-get](https://www.npmjs.com/package/simple-get) or something similar?

**Comment by bnoordhuis** [comment]
Thanks, but not unless npm switches as well.  When node-gyp is bundled with npm (the common case), they share a copy of request, micromatch, and so on.  See #1018.
