### ISSUE TITLE
Error while configure in Windows 7

### ISSUE THREAD

**Issue by RKishore222** [nodejs/node-gyp#1367]
C:\Users\m50541\AppData\Roaming\npm\node_modules\node-gyp>node-gyp configure --v
erbose

C:\Users\m50541\AppData\Roaming\npm\node_modules\node-gyp>if not defined npm_con
fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" configure --verbose )  else (node ""
 configure --verbose )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\m50541\.windows-b
uild-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\m50541\.windows-build-tools\python27\python.
exe C:\Users\m50541\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\m50541\.windows-build-tools\python27\pyt
hon.exe -c "import platform; print(platform.python_version());"` returned: "2.7.
14\r\n"
gyp verb get node dir no --target version specified, falling back to host node v
ersion: 8.9.3
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created C:\Users\m50541\.node-gyp\8.9.3
gyp verb created nodedir C:\Users\m50541\.node-gyp\8.9.3
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.9.3' ]
gyp verb remove using node-gyp dir: C:\Users\m50541\.node-gyp
gyp verb remove removing target version: 8.9.3
gyp verb remove removing development files for version: 8.9.3
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--v
erbose"
gyp ERR! cwd C:\Users\m50541\AppData\Roaming\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Users\m50541\AppData\Roaming\npm\node_modules\node-gyp>

**Comment by bnoordhuis** [comment]
> gyp ERR! stack Error: unable to verify the first certificate

Let me guess: you're behind some kind of MitM corporate proxy.

**Comment by joaocgreis** [comment]
@RKishore222 What are you trying to accomplish here? `node-gyp` is not a native module, it does not make sense to use `node-gyp` on `node-gyp`, so your command would only legitimately fail later if it did not fail there. Also, it's usually a very bad idea to run commands manually in `AppData\Roaming\npm`, unless you know really well what you are doing.
