### ISSUE TITLE
How to debug source on OS X? my problem is output path

### ISSUE THREAD

**Issue by whtiehack** [nodejs/node-gyp#1375]
* **Node Version**: 8.9.4
* **Platform**: OS X 10.11.4
* **Compiler**: 
```
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
```
> xcode 7.0.1

I have read this issue #316 .

My problem is that after I generated the project with the command `node-gyp configure - -f xcode`.
 I clicked run and the resulting executable was not in the directory` build / Release`.
here is the real path.
![image](https://user-images.githubusercontent.com/12741016/35671582-dc43c382-0776-11e8-9015-c782908bb068.png)

Using the command `node-gyp configure - -f xcode`, what should I do to get the correct output path` build / Release / xx.node`?

thanks a lot.

**Comment by bnoordhuis** [comment]
If you just want to debug with lldb, use `node-gyp rebuild --debug`.  The add-on ends up in `build/Debug`.

**Comment by whtiehack** [comment]
However, I want to use xcode debug add-on, the problem is that the compiler path is not correct, how do I do? thx @bnoordhuis

**Comment by bnoordhuis** [comment]
I think the answer is "you don't", except for teaching your JS code to load it from a different location.  Xcode projects have their own conventions.

**Comment by whtiehack** [comment]
@bnoordhuis ,thanks for answer.I remember the build path before is normal`build/Release | build/Debug`,after upgrading node from 6.x to 8.x there is that problem.( WTF build path)

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/35712381-adffc3dc-07fc-11e8-8ea7-2abdd12457e3.png)

When I changed the node back to v6.9.4, the build path was expected.☹️

**Comment by whtiehack** [comment]
So, is this a node-gyp bug?🤕

**Comment by bnoordhuis** [comment]
No.

**Comment by lathoub** [comment]
after `node-gyp configure -- -f xcode`, I open Xcode and edit the Scheme to set the executable to `node` (by default in the `/usr/local/bin/node` directory) and the argument to point to the .js file I want to load (I use an absolute path).

Then in the Build Settings, Build Locations, Per-configuration Build Products Path: replace `$(BUILD_DIR)` with `build`. This will put the generated .node file in the directory where node will search.

I'm using Xcode 9.2, macOS High Sierra 10.13.3, node v9.5.0 and node-gyp v3.6.2

**Comment by whtiehack** [comment]
@lathoub  thanks for answer, this works.
