### ISSUE TITLE
Building the cpp addons in the cloud.

### ISSUE THREAD

**Issue by Himujjal** [nodejs/node-gyp#1376]
I am having trouble installing the pre-requisites required for installing the npm modules in Windows. I have tried every way possible. I don't want to go into details how for the whole day I have been trying to making it run.
Then again for the npm modules to be published we need the end-users to build the modules again and again.

So, I have a suggestion to make. NodeJS Foundation / NPM with so much funds on their side can just buy three servers. Windows Server, MAC OS Server and Linux Servers to build the final build for the NodeJS Addons. The three servers can then send back the compiled/build files to be used (Which can be used in production). 

Plus anyone making a NodeJS  program/module can then simply make a **if/else** with **process.platform** and use the three node addons. This will also help maintain Cross-platform.

This is a suggestion. There are drawbacks to this such as constant uploading and download files from the internet requires a good internet connectivity etc. 

I made a simple production ready Hello World program in Node and C++: https://www.github.com/Himujjal/napi-modules for both Windows and Linux. This program does not need to be compiled either. Just clone it and run the **index.js** file.

**Comment by richardlau** [comment]
Previous discussions around this idea: https://github.com/nodejs/build/issues/151

**Comment by joyeecheung** [comment]
> So, I have a suggestion to make. NodeJS Foundation / NPM with so much funds on their side can just buy three servers. Windows Server, MAC OS Server and Linux Servers to build the final build for the NodeJS Addons. The three servers can then send back the compiled/build files to be used (Which can be used in production).

FWIW, the main problem with these kind of thing is not the lack of funds to buy servers, but usually the lack of human resources - volunteers that setup and maintain those things. The build WG is already under-staffed that we are struggling with keeping the testing CI green. If you really want to push this forward, I would suggest that you join the discussion in the build WG and get more labour contributed instead of funds.

**Comment by Himujjal** [comment]
I would surely love to push this forward. I would definitely volunteer to maintaining it. So, please send me the link to this **build WG**. I will take personal responsibility provided the resources which I as a student cannot quite afford.

**Comment by bnoordhuis** [comment]
@Himujjal It's the link @richardlau posted.  That repo is the build WG's home.  See their README.

**Comment by joyeecheung** [comment]
@Himujjal Great! The build working group is where https://github.com/nodejs/build/issues/151 takes place, the introduction is in https://github.com/nodejs/build . Most people hang out on the #node-build freenode IRC so you can get some questions answered there as well

**Comment by Himujjal** [comment]
@joyeecheung @bnoordhuis  The WG seems to be dormant. No replies for a long time. Could you help me get introduced to anyone who could help me out with this problem above.
I am a newbie in IRC chats. Never used them before. Just joined the group and posted a message.

**Comment by bnoordhuis** [comment]
> No replies for a long time.

You mean in their IRC channel?  Give it time; it's weekend.
