### ISSUE TITLE
Add support for Vala

### ISSUE THREAD

**Issue by ghost** [nodejs/node-gyp#1382]
is it possible to add support for vala ? i want to start making a native addon but not really familiar with c or c++ but i'm familiar with c# and i think vala is almost like c#.

**Comment by bnoordhuis** [comment]
I'm not saying no but probably not anytime soon.  I'll leave this open for a bit to see if there is more interest.

As an interim solution you could distribute the Vala->C translated sources or use a Makefile and an npm postinstall command that invokes make.

**Comment by muhammadsayuti** [comment]
@bnoordhuis is there any detail or tutorial on how to make the module.node file ? 
is this compiler support ninja ? i want to use meson to handle all .vala files.

**Comment by bnoordhuis** [comment]
It's just a .so with a different extension and [some constructor magic](https://github.com/nodejs/node/blob/v9.5.0/src/node.h#L485-L515) that auto-registers on load.

> i want to use meson to handle all .vala files.

No one's stopping you but then why post here?  For questions specific to node-gyp you're in the right place.  For more general questions you should turn to nodejs/help or some other place.

**Comment by rvagg** [comment]
I don't think this is specific to node-gyp, but if you want to try and make a Makefile builder then https://github.com/refack/GYP might be the place to do that work.

Also remember that node-gyp isn't _essential_ for building addons, you could just ship a Makefile and invocation magic in package.json/"build".
