### ISSUE TITLE
How do I prevent node-gyp from taking ‘lib’ off from my `target_name`?

### ISSUE THREAD

**Issue by wlzla000** [nodejs/node-gyp#1387]
* **Node Version**: 9.7.1.
* **Platform**: `Linux ubuntu64-VirtualBox 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`.
* **Compiler**: using built-in specs.
  - `COLLECT_GCC=cc`
  - `COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper`
  - `OFFLOAD_TARGET_NAMES=nvptx-none`
  - `OFFLOAD_TARGET_DEFAULT=1`
  - `Target: x86_64-linux-gnu`
  - `Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3.2' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu`
  - `Thread model: posix`
  - `gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)`
* **Module**: **`libblahblah`**.

<details>
<summary>Verbose output from `node-gyp`</summary>

```
ubuntu64@ubuntu64-VirtualBox:~/Desktop/libblahblah$ cat binding.gyp
{
	"targets": [
		{
			"target_name": "libblahblah",
			"sources": ["source/node-libblahblah.cpp"],
			"include_dirs": ["<!(node -e \"require('nan')\")"]
		}
	]
}
ubuntu64@ubuntu64-VirtualBox:~/Desktop/libblahblah$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.7.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu64/Desktop/libblahblah/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu64/.node-gyp/9.7.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu64/.node-gyp/9.7.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu64/.node-gyp/9.7.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu64/Desktop/libblahblah',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
ubuntu64@ubuntu64-VirtualBox:~/Desktop/libblahblah$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.7.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu64/Desktop/libblahblah/build'
  CXX(target) Release/obj.target/libblahblah/source/node-libblahblah.o
  SOLINK_MODULE(target) Release/obj.target/blahblah.node
  COPY Release/blahblah.node
make: Leaving directory '/home/ubuntu64/Desktop/libblahblah/build'
gyp info ok 
ubuntu64@ubuntu64-VirtualBox:~/Desktop/libblahblah$ ls build/Release
obj.target  blahblah.node
```

</details>

-----

 My module's `"target_name"` is `"libblahblah"`. When `build`ing it, `node-gyp` takes the `lib` off and gives `blahblah.node` instead of `libblahblah.node`. How do I have `node-gyp` not do this?

**Comment by wlzla000** [comment]
@bnoordhuis It worked! Thank you so much. Closing this interrogative issue.

**Comment by TooTallNate** [comment]
I believe `product_prefix` is the more "sanctioned" way to accomplish this: https://github.com/gypified/libogg/blob/35e89da43da17827d59171ed771c4f4add54900d/libogg.gyp#L51
