### ISSUE TITLE
question - How to generate a Xcode vanilla project for a node extension

### ISSUE THREAD

**Issue by avnerbarr** [nodejs/node-gyp#1389]
I want to create a blank project that I can develop from within XCode.

I followed the instructions on installing `node-gyp` and created a basic `binding.gyp` file

containing 

```
{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ "src/binding.cc" ]
    }
  ]
}
```

and then ran 

```
node-gyp configure
```

I want to somehow be able to develop the extension from XCode (or another IDE if necessary).

I don't understand how to generate the xcode project.

Thanks

**Comment by bnoordhuis** [comment]
Run `node-gyp configure -- -f xcode`.  You won't be able to use `node-gyp build` and I'm not 100% sure if xcode puts the binary in the default location of `build/Release`.
