### ISSUE TITLE
How to Run Release Build on Windows 

### ISSUE THREAD

**Issue by chgibb** [nodejs/node-gyp#1400]
* **Node Version**: 8.10.0
* **Platform**: Windows
* **Compiler**: msbuild 14.0.25420.1

Running ```node-gyp configure``` and ```node-gyp build``` with both ```--release``` and ```--no-debug``` is still generating a solution with debug flags on Windows. Is there any way to fix this so switches like ```/Ox``` can be used?

**Comment by bnoordhuis** [comment]
Define 'debug flags'?  What does your binding.gyp look like?

**Comment by chgibb** [comment]
My binding.gyp currently is:
```json
{
    "targets": [
        {
            "target_name": "ngPlasmid",
            "include_dirs": [
                "src",
                "<!(node -e \"require('nan')\")"
            ],
            "sources": [
                "lib/cpp/index.cpp"
            ],
            "cflags_cc" : [
                "-std=c++11",
                "-O3",
                "-ffast-math",
                "-Werror",
                "-Wno-comment",
                "-s"
            ],
            "msvs_settings" : {
                "VCCLCompilerTool" : {
                    "AdditionalOptions" : [
                        "/Ox",
                        "/fp:fast"
                    ]
                }
            }
        }
    ]
}
```

The build ends up looking like this:
```
  Using triplet "x86-windows" from "C:\Tools\vcpkg\installed\x86-windows\"
ClCompile:
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\CL.exe /c /I"C:\Users\appveyor\.node-gyp\8.10.0\include\node" /I"C:\Users\appveyor\.node-gyp\8.10.0\src" /I"C:\Users\appveyor\.node-gyp\8.10.0\deps\uv\include" /I"C:\Users\appveyor\.node-gyp\8.10.0\deps\v8\include" /I..\src /I..\node_modules\nan /I"C:\Tools\vcpkg\installed\x86-windows\include" /Zi /nologo /W3 /WX- /Od /Oy- /D NODE_GYP_MODULE_NAME=ngPlasmid /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D BUILDING_NODE_EXTENSION /D DEBUG /D _DEBUG /D V8_ENABLE_CHECKS /D _WINDLL /GF /Gm- /RTC1 /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\obj\ngPlasmid\\" /Fd"Debug\obj\ngPlasmid\vc140.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /analyze- /errorReport:queue /Ox /fp:fast /bigobj /MP ..\lib\cpp\index.cpp "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
cl : Command line warning D9025: overriding '/Od' with '/Ox' [C:\projects\ngplasmid\build\ngPlasmid.vcxproj]
cl : Command line error D8016: '/RTC1' and '/Ox' command-line options are incompatible [C:\projects\ngplasmid\build\ngPlasmid.vcxproj]
Done Building Project "C:\projects\ngplasmid\build\ngPlasmid.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\projects\ngplasmid\build\binding.sln" (default targets) -- FAILED.

Build FAILED.
```

Despite running with ```--release``` and ```--no-debug```,  ```/RTC``` and ```/Od``` are being passed by the generated project. Is there anyway to turn these off? Specifically ```/RTC```.

**Comment by richardlau** [comment]
> `/RTC` and `/Od` are being passed by the generated project.

These are being inherited from `common.gypi`, specifically these lines:
https://github.com/nodejs/node/blob/c6ae8a28109fc19ea30a5d785b2215345564c0bb/common.gypi#L119-L137

I guess another reason in favor of https://github.com/nodejs/node-gyp/issues/1118.

**Comment by richardlau** [comment]
Do you have any `npm_config_*` environment variables set?

**Comment by chgibb** [comment]
These builds are running on Appveyor. As far as I can tell from poking through their docs and a brief google, no ```npm_config_*``` variables are set. What variables in particular are you interested in? I can try to echo them in a build and see what the output is.

**Comment by chgibb** [comment]
```echo %npm_config_debug%``` results in ```ECHO is off.```. It appears ```npm_config_debug``` is not set (unless my batch is that rusty).

**Comment by chgibb** [comment]
Any insight @richardlau ?

**Comment by rvagg** [comment]
did you figure this out @chgibb ? sorry we didn't get any further here, debug builds are probably something we need in our test suite.

**Comment by chgibb** [comment]
Given the amount of time between responses, I gave up unfortunately. But thanks for following up @rvagg
