### ISSUE TITLE
Error: can't find python executable

### ISSUE THREAD

**Issue by vksonagara** [nodejs/node-gyp#1401]
* **Node Version**: 9.8.0 
* **Platform**: Windows

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

![180327123127](https://user-images.githubusercontent.com/18218599/37906532-144246b4-3120-11e8-93b6-4da45ce6a784.png)
![180327123444](https://user-images.githubusercontent.com/18218599/37906565-2ed38cf4-3120-11e8-8afa-a8eee1d865d1.png)

**Comment by bzoz** [comment]
You need Python 2.7, 3.x.x is not supported.

**Comment by dpundir** [comment]
I had same issue and same node version, it got resolved after downgrading node to version 8.11.1.
https://github.com/nodejs/node-gyp/issues/809

**Comment by David-OConnor** [comment]
Same issue.
