### ISSUE TITLE
[question] after compiled, do I still need python, make, gcc ?

### ISSUE THREAD

**Issue by ozbillwang** [nodejs/node-gyp#1407]
When npm install with `nodejs/node-gyp` package, it asks to install python, make and gcc

https://github.com/nodejs/node-gyp#on-unix

    On Unix
    
    python (v2.7 recommended, v3.x.x is not supported)
    make
    A proper C/C++ compiler toolchain, like GCC

I am building a node docker image and need confirm if finished `npm install --production`, can I remove these toolsets (python, make and gcc) safely? Will generate any impacts for node applications?

**Comment by bnoordhuis** [comment]
You only need them for building native modules, not when using them.  So yes, should be safe to remove again.
