### ISSUE TITLE
Graceful node path detection.

### ISSUE THREAD

**Issue by jdalton** [nodejs/node-gyp#1408]
With issues like https://github.com/nodejs/node/pull/19840 and https://github.com/npm/npm/issues/20163 I thought it would be good to start thinking of ways to better handle `node-gyp` resolution of the Node path as well as how it can have folks like Node and npm rely on it without stepping on each others toes.

File of interest:
[lib/find-node-directory.js](https://github.com/nodejs/node-gyp/blob/f6eab1f9e4b160b60b2736bb01a09c83785ba979/lib/find-node-directory.js).

\cc @iarna from npm and @addaleax @MylesBorins from Node.

**Comment by jdalton** [comment]
\cc @iarna from npm and @addaleax @MylesBorins of Node.

**Comment by MylesBorins** [comment]
Looks like npm opened a PR to bing the dependency back to the main tree and introducing a test to not regress in the future

https://github.com/npm/npm/pull/20276

**Comment by rvagg** [comment]
addressed in npm/npm#20276 I suppose
