### ISSUE TITLE
node-gyp rebuild hangs on MacOS

### ISSUE THREAD

**Issue by stanislavkozlovski** [nodejs/node-gyp#1416]
* **Node Version**: v9.5.0, npm@5.6.0
* **Platform**: `Darwin enether.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64`
* **Compiler**: ﻿
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* **Module**: modern-syslog @ 1.1.4 and 1.1.2.

```
> modern-syslog@1.1.4 install /usr/local/lib/node_modules/modern-syslog
> node-gyp rebuild

```
This command hangs forever. I tried

- re-installing node-gyp
- re-installing with `--unsafe-perm`
- running installs with `sudo`
- using npm@4.3.0
- installing xCode

**Comment by Enether** [comment]
No, `npm install heapdump` also hangs
```
> heapdump@0.3.9 install /Users/stanislavkozlovski/Documents/SumUpCode/apigateway/node_modules/heapdump
> node-gyp rebuild
```

```
> xcode-select-p
/Library/Developer/CommandLineTools
```

**Comment by bnoordhuis** [comment]
Did you accept the EULA when you installed Xcode?  I ask because I expected `xcode-select -p` to point to `/Applications/Xcode.app/Contents/Developer`.  What happens when you switch to that path with `xcode-select -s`?

**Comment by Enether** [comment]
Yes.
Still hangs after switching:
```
sudo xcode-select -s ~/Applications/Xcode.app/Contents/Developer/
Password:
stanislavkozlovski@Stanislavs-iMac ~ -  $ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | darwin | x64
```

**Comment by Tawpie** [comment]
@Enether I ran into this hang today after upgrading to Node 10.0.0, hung on headdump. Backing Node down to 8.11.1 restored the ability to build. I wasn't doing direct builds, rather `yarn install` with a fairly large load of packages (Appium requires rebuild)

**Comment by valeriabarros** [comment]
The only thing that helped me was downgrading my node version from 10.0 to v9.11.1 with nvm.

**Comment by rvagg** [comment]
closing due to staleness, I'm assuming that no additional comments means this may be resolved by newer versions of node?

**Comment by himself65** [comment]
Hello, I'm facing this problem randomly in macOS x64 CI

https://github.com/toeverything/AFFiNE/actions/runs/5676994082/job/15384648202

**Comment by cclauss** [comment]
@himself65 **Error: The operation was canceled.**

Does not look random to me.

**Comment by himself65** [comment]
> @himself65 **Error: The operation was canceled.**
> 
> Does not look random to me.

I was canceled because it reaches the max time of CI which is 6 hrs
