### ISSUE TITLE
Windows .obj files generated in flattened directory causing linker errors.

### ISSUE THREAD

**Issue by Mmdixon** [nodejs/node-gyp#1424]
If the directory looks like:
```
src/
    nodejs/
        folder/
            temp.cpp
    folder/
        temp.cpp
```
with a `binding.gyp` similar to
```
{
    "targets": [
        {
            "target_name": "mytarget",
            "sources": [
                "src/nodejs/folder/temp.cpp",
                "src/folder/temp.cpp",
            ],
        },
    ],
}
```
The CL compiler in Windows generates `build/Release/obj/mytarget/temp.obj` with a name collision on `temp.obj`, and thus causing linker issues later in the build.
Is there a way to preserve the source folder paths in the obj output directory too? This seems to be the job of the `/Fo` flag, but all the `sources` are thrown together in one command to CL, so it doesn't really make sense to set it.

In comparison to a Linux build, the object files preserve the path and it all works out and looks something like:
```
build/Release/obj.target/mytarget/src/nodejs/folder/temp.o
build/Release/obj.target/mytarget/src/folder/temp.o
```
System Details
```
node: v9.11.1
npm: 5.6.0
OS Name: Microsoft Windows 10
OS Version: 10.0.16299
System Type: x64-based PC
Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26131.1 for x64
Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
```

**Comment by bnoordhuis** [comment]
> Is there a way to preserve the source folder paths in the obj output directory too?

The short answer is "you can't (portably)".   GYP changed that years ago to promote consistency across platforms and build systems.  See e.g. libuv/libuv@e132075738, you're not alone. :-)

I've toyed with the idea of using the SHA-1 of the full path as the basename but that has bad error message ergonomics ("missing symbol in 7e6ef1ca3e0ad8ab8a3b79ee2565adcee613d8c0.o".)
