### ISSUE TITLE
npm install error - Windows 10

### ISSUE THREAD

**Issue by doakheggeness** [nodejs/node-gyp#1427]
I have tried to install several Gatsby packages from Github without any luck. The only one I was able to install successfulty was gatsby-starter-lumen.  I also tried them on Ubunto for Windows unsuccessfullly  and uninstalled it.

I went thru the Gatsby on Windows instructions without success, so here I am. Thanks

[2018-04-29T15_27_45_957Z-debug.log](https://github.com/nodejs/node-gyp/files/1958872/2018-04-29T15_27_45_957Z-debug.log)

* **Node Version**: v9.11.1
* **Platform**: Windows 10 Pro V1709  build: 16299.403\2
* **Compiler**: 
* **Module**: npm install

***Console ERR***

<details><summary>C:\Users\doakh\Development\gatsby-starter-casper (master -> origin) (gatsby-starter-casper@1.0.6)
λ npm install

> sharp@0.17.3 install C:\Users\doakh\Development\gatsby-starter-casper\node_modules\sharp
> node-gyp rebuild

C:\Users\doakh\Development\gatsby-starter-casper\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2,7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\doakh\Development\gatsby-starter-casper\node_modules\sharp
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN postcss-html@0.12.0 requires a peer of postcss-less@>=1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-html@0.12.0 requires a peer of sugarss@>=1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-starter-casper@1.0.6 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\doakh\AppData\Roaming\npm-cache\_logs\2018-04-29T15_27_45_957Z-debug.log
:</summary>

`    `

```

```

</details>

**Comment by bnoordhuis** [comment]
This is the error:

> gyp ERR! stack Error: Can't find Python executable "python2,7", you can set the PYTHON env variable.

You can also pass `--python c:\python2.7\python.exe` (or wherever you have it installed) or set the `python` property in your .npmrc.
