### ISSUE TITLE
npm install "npm ERR! file" error

### ISSUE THREAD

**Issue by Mins17** [nodejs/node-gyp#1430]
Hi, I am a newbie in web development and working on a laravel project. I am trying to install npm, using "npm install" command. But I am facing an issue installing it.

Info about my PC
>Windows 7 ultimate, Service pack 1
>System type : 32 bit operating system 

Node version-  v8.11.1
NPM version -  6.0.0

error:

intel@intel-PC MINGW32 /c/xampp/htdocs/realtimeApp
$ npm install

> node-sass@4.9.0 install C:\xampp\htdocs\realtimeApp\node_modules\node-sass
> node scripts/install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! file C:\Program Files\Java\jdk1.8.0_31\bin;
npm ERR! path C:\Program Files\Java\jdk1.8.0_31\bin;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Java\jdk1.8.0_31\bin;
npm ERR! node-sass@4.9.0 install: `node scripts/install.js`
npm ERR! spawn C:\Program Files\Java\jdk1.8.0_31\bin; ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\intel\AppData\Roaming\npm-cache\_logs\2018-05-03T04_17_57_942Z-debug.log

Please look into the issue. I couldn't find a similar issue on GIT.

Log file:
[2018-05-03T04_17_57_942Z-debug.log](https://github.com/nodejs/node-gyp/files/1969670/2018-05-03T04_17_57_942Z-debug.log)

**Comment by bnoordhuis** [comment]
Wrong repo.  You should report that to node-sass.
