### ISSUE TITLE
Node install forAngular CLI what is the problem ? 

### ISSUE THREAD

**Issue by shameembgithub** [nodejs/node-gyp#1438]
ARN notice [SECURITY] ws has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=ws&version=1.1.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] randomatic has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=randomatic&version=1.1.7 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] parsejson has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] tunnel-agent has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] hoek has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] https-proxy-agent has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=https-proxy-agent&version=1.0.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] lodash has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> fsevents@1.2.3 install /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/fsevents
> node install

[fsevents] Success: "/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.0 install /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/vendor/darwin-x64-57 : { Error:EACCES: permission denied, mkdir '/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/vendor' }

> node-sass@4.9.0 postinstall /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:13:12)\n    at F (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:68:19)\n    at E (/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:80:29)\n    at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/which/which.js:89:16\n    at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/index.js:42:5\n    at /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.11.1
gyp verb ensuring nodedir is created /Users/honeycombmacpro/.node-gyp/8.11.1
gyp verb created nodedir /Users/honeycombmacpro/.node-gyp/8.11.1
gyp http GET https://nodejs.org/download/release/v8.11.1/node-v8.11.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.11.1/node-v8.11.1-headers.tar.gz
gyp verb extracted file from tarball include/node/android-ifaddrs.h
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/node_api_types.h
gyp verb extracted file from tarball include/node/node_buffer.h
gyp verb extracted file from tarball include/node/node_object_wrap.h
gyp verb extracted file from tarball include/node/node_version.h
gyp verb extracted file from tarball include/node/pthread-barrier.h
gyp verb extracted file from tarball include/node/stdint-msvc2008.h
gyp verb extracted file from tarball include/node/tree.h
gyp verb extracted file from tarball include/node/uv-aix.h
gyp verb extracted file from tarball include/node/uv-bsd.h
gyp verb extracted file from tarball include/node/uv-darwin.h
gyp verb extracted file from tarball include/node/uv-errno.h
gyp verb extracted file from tarball include/node/uv-linux.h
gyp verb extracted file from tarball include/node/uv-os390.h
gyp verb extracted file from tarball include/node/uv-posix.h
gyp verb extracted file from tarball include/node/uv-sunos.h
gyp verb extracted file from tarball include/node/uv-threadpool.h
gyp verb extracted file from tarball include/node/uv-unix.h
gyp verb extracted file from tarball include/node/uv-version.h
gyp verb extracted file from tarball include/node/uv-win.h
gyp verb extracted file from tarball include/node/uv.h
gyp verb extracted file from tarball include/node/v8-debug.h
gyp verb extracted file from tarball include/node/v8-inspector-protocol.h
gyp verb extracted file from tarball include/node/v8-inspector.h
gyp verb extracted file from tarball include/node/v8-platform.h
gyp verb extracted file from tarball include/node/v8-profiler.h
gyp verb extracted file from tarball include/node/v8-testing.h
gyp verb extracted file from tarball include/node/v8-util.h
gyp verb extracted file from tarball include/node/v8-value-serializer-version.h
gyp verb extracted file from tarball include/node/v8-version-string.h
gyp verb extracted file from tarball include/node/v8-version.h
gyp verb extracted file from tarball include/node/v8.h
gyp verb extracted file from tarball include/node/v8config.h
gyp verb extracted file from tarball include/node/zconf.h
gyp verb extracted file from tarball include/node/zlib.h
gyp verb extracted file from tarball include/node/openssl/aes.h
gyp verb extracted file from tarball include/node/openssl/asn1.h
gyp verb extracted file from tarball include/node/openssl/asn1_mac.h
gyp verb extracted file from tarball include/node/openssl/asn1t.h
gyp verb extracted file from tarball include/node/openssl/bio.h
gyp verb extracted file from tarball include/node/openssl/blowfish.h
gyp verb extracted file from tarball include/node/openssl/bn.h
gyp verb extracted file from tarball include/node/openssl/buffer.h
gyp verb extracted file from tarball include/node/openssl/camellia.h
gyp verb extracted file from tarball include/node/openssl/cast.h
gyp verb extracted file from tarball include/node/openssl/cmac.h
gyp verb extracted file from tarball include/node/openssl/cms.h
gyp verb extracted file from tarball include/node/openssl/comp.h
gyp verb extracted file from tarball include/node/openssl/conf.h
gyp verb extracted file from tarball include/node/openssl/conf_api.h
gyp verb extracted file from tarball include/node/openssl/crypto.h
gyp verb extracted file from tarball include/node/openssl/des.h
gyp verb extracted file from tarball include/node/openssl/des_old.h
gyp verb extracted file from tarball include/node/openssl/dh.h
gyp verb extracted file from tarball include/node/openssl/dsa.h
gyp verb extracted file from tarball include/node/openssl/dso.h
gyp verb extracted file from tarball include/node/openssl/dtls1.h
gyp verb extracted file from tarball include/node/openssl/e_os2.h
gyp verb extracted file from tarball include/node/openssl/ebcdic.h
gyp verb extracted file from tarball include/node/openssl/ec.h
gyp verb extracted file from tarball include/node/openssl/ecdh.h
gyp verb extracted file from tarball include/node/openssl/ecdsa.h
gyp verb extracted file from tarball include/node/openssl/engine.h
gyp verb extracted file from tarball include/node/openssl/err.h
gyp verb extracted file from tarball include/node/openssl/evp.h
gyp verb extracted file from tarball include/node/openssl/hmac.h
gyp verb extracted file from tarball include/node/openssl/idea.h
gyp verb extracted file from tarball include/node/openssl/krb5_asn.h
gyp verb extracted file from tarball include/node/openssl/kssl.h
gyp verb extracted file from tarball include/node/openssl/lhash.h
gyp verb extracted file from tarball include/node/openssl/md4.h
gyp verb extracted file from tarball include/node/openssl/md5.h
gyp verb extracted file from tarball include/node/openssl/mdc2.h
gyp verb extracted file from tarball include/node/openssl/modes.h
gyp verb extracted file from tarball include/node/openssl/obj_mac.h
gyp verb extracted file from tarball include/node/openssl/objects.h
gyp verb extracted file from tarball include/node/openssl/ocsp.h
gyp verb extracted file from tarball include/node/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/opensslv.h
gyp verb extracted file from tarball include/node/openssl/ossl_typ.h
gyp verb extracted file from tarball include/node/openssl/pem.h
gyp verb extracted file from tarball include/node/openssl/pem2.h
gyp verb extracted file from tarball include/node/openssl/pkcs12.h
gyp verb extracted file from tarball include/node/openssl/pkcs7.h
gyp verb extracted file from tarball include/node/openssl/pqueue.h
gyp verb extracted file from tarball include/node/openssl/rand.h
gyp verb extracted file from tarball include/node/openssl/rc2.h
gyp verb extracted file from tarball include/node/openssl/rc4.h
gyp verb extracted file from tarball include/node/openssl/ripemd.h
gyp verb extracted file from tarball include/node/openssl/rsa.h
gyp verb extracted file from tarball include/node/openssl/safestack.h
gyp verb extracted file from tarball include/node/openssl/seed.h
gyp verb extracted file from tarball include/node/openssl/sha.h
gyp verb extracted file from tarball include/node/openssl/srp.h
gyp verb extracted file from tarball include/node/openssl/srtp.h
gyp verb extracted file from tarball include/node/openssl/ssl.h
gyp verb extracted file from tarball include/node/openssl/ssl2.h
gyp verb extracted file from tarball include/node/openssl/ssl23.h
gyp verb extracted file from tarball include/node/openssl/ssl3.h
gyp verb extracted file from tarball include/node/openssl/stack.h
gyp verb extracted file from tarball include/node/openssl/symhacks.h
gyp verb extracted file from tarball include/node/openssl/tls1.h
gyp verb extracted file from tarball include/node/openssl/ts.h
gyp verb extracted file from tarball include/node/openssl/txt_db.h
gyp verb extracted file from tarball include/node/openssl/ui.h
gyp verb extracted file from tarball include/node/openssl/ui_compat.h
gyp verb extracted file from tarball include/node/openssl/whrlpool.h
gyp verb extracted file from tarball include/node/openssl/x509.h
gyp verb content checksum node-v8.11.1-headers.tar.gz ea28109f7a3b3b21705f25fb0e181e984ece46e785dd9912b5c14df4c067fa07
gyp verb extracted file from tarball include/node/openssl/x509_vfy.h
gyp verb extracted file from tarball include/node/openssl/x509v3.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64A/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux32-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-elf/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-armv4/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-aarch64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin-i386-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/libplatform/libplatform-export.h
gyp verb extracted file from tarball include/node/libplatform/libplatform.h
gyp verb extracted file from tarball include/node/libplatform/v8-tracing.h
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`...
gyp verb checksum url https://nodejs.org/download/release/v8.11.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.11.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.11.1/SHASUMS256.txt
gyp verb checksum data {"node-v8.11.1-aix-ppc64.tar.gz":"0dabd62eaa3675dafb458da6206fe31a6edf3c368b428fe8d2f800b857070c44","node-v8.11.1-darwin-x64.tar.gz":"5c7b05899ff56910a2b8180f139d48612f349ac2c5d20f08dbbeffbed9e3a089","node-v8.11.1-darwin-x64.tar.xz":"882fcca054d6100ca67f94e4cf50d8df141f106fafbcefc0b04facc4a9ab956c","node-v8.11.1-headers.tar.gz":"ea28109f7a3b3b21705f25fb0e181e984ece46e785dd9912b5c14df4c067fa07","node-v8.11.1-headers.tar.xz":"0f1838be48063a0c419178b02eeffaffeb6d4b09b50b9b33b4234dc111ff64fa","node-v8.11.1-linux-arm64.tar.gz":"68546c94a730a8d546e37a9bbae919f4a0f864220ce3aa160461a4f3e779a6af","node-v8.11.1-linux-arm64.tar.xz":"ff518f33751baa8ea4f18853d446357c2edecd930a1526ac9b2eaa79baddc1bf","node-v8.11.1-linux-armv6l.tar.gz":"10ccfd8631923cac8b0f41a83ef9316a5f19faf96de1eee66dedc20ebf9d61e7","node-v8.11.1-linux-armv6l.tar.xz":"ae5d9b9804a441b786046e125380ea15755db40a99fb5551582bd6bd59ef71be","node-v8.11.1-linux-armv7l.tar.gz":"73abddb5e80a2926f1646b77bbb7093465b2abc43846c1b468dbccad4b72164d","node-v8.11.1-linux-armv7l.tar.xz":"7bb97e3b06d186cfff576096f75431eedcc0ecee16c47afe8aabd7a22cc31c47","node-v8.11.1-linux-ppc64le.tar.gz":"f894524124c19fcd2180a483b7a238b77a14fb81c3d4723620ec66be2635cb4f","node-v8.11.1-linux-ppc64le.tar.xz":"d05b8a61f253168fc228d0da270a88293d082696b179d057d8aaa5328b43fb9b","node-v8.11.1-linux-s390x.tar.gz":"179e296c0f61fda1a454cba8d24a92efdb3f0646c0efd5c1d78194acf6cfc4df","node-v8.11.1-linux-s390x.tar.xz":"d9e892c7222b8c93f4e57f476a031c047345db1ad6785a5c85f9db41c6f8db23","node-v8.11.1-linux-x64.tar.gz":"0e20787e2eda4cc31336d8327556ebc7417e8ee0a6ba0de96a09b0ec2b841f60","node-v8.11.1-linux-x64.tar.xz":"6617e245fa0f7fbe0e373e71d543fea878315324ab31dc64b4eba10e42d04c11","node-v8.11.1-linux-x86.tar.gz":"373e28cb9549fda7063b35eba84827fb0fda6c01856d0b310431eaea7d0c6d45","node-v8.11.1-linux-x86.tar.xz":"cfe4f6115f9148b16e1b993a6fbbaf21aeecbb97849dd498b979d8511ff25e85","node-v8.11.1.pkg":"3b6b18483e736e3d4690705559f31ead036a42396986f1e5bcb3daa776188bbc","node-v8.11.1-sunos-x64.tar.gz":"bf9e9d404bdc7e383897e82bb834322181b440198313077e4de435a4a56fb837","node-v8.11.1-sunos-x64.tar.xz":"531817fc242bd355f2438aee471bf8c31085e39927012a37eeb558b7d378d6c6","node-v8.11.1-sunos-x86.tar.gz":"e2f2573a3984a155e3001ac09b78d559d506c1160fda0bba0f819021a1eeef6a","node-v8.11.1-sunos-x86.tar.xz":"1c7f0928a66ad986bbf7bd1fb40d45824d1fe2e2aa9fa802e6b25a76273ff674","node-v8.11.1.tar.gz":"86678028f13b26ceed08efc4b838921ca1bf514c0b7e8151bfec8ba15c5e66ad","node-v8.11.1.tar.xz":"40a6eb51ea37fafcf0cfb58786b15b99152bec672cccf861c14d1cca0ad4758a","node-v8.11.1-win-x64.7z":"c4eae881574da81c1617af754151bfbf2f6b558002b71b16d580261ab86bfa6b","node-v8.11.1-win-x64.zip":"7d49b59c2b5d73a14c138e8a215d558a64a5241cd5035d9824f608e7bba097b1","node-v8.11.1-win-x86.7z":"1328604c885d849f3b3d2c93377578b655e74a5f630b4757dbe8b16b9320d888","node-v8.11.1-win-x86.zip":"c07a5eb55268c0bf491e73efb225f42a7289fd92d2b768b955ba9a49d7b916b4","node-v8.11.1-x64.msi":"42a2a4e7972c2266174f114f732c93d183d4df2ddaa31a9d543c96f96a7b1b97","node-v8.11.1-x86.msi":"7662094918364fa33b317b7788413d36ef2eb517fc4a23cee1134bab346f6de5","win-x64/node.exe":"ed9507c4c44915c1183a3bb6747c7821fb5ba194d47ff9351fa153f2ab368ed1","win-x64/node.lib":"45fd5c590a3a0ee9a310b506bdf9d2e530bcdd2200aaac1030b8de1e00183181","win-x64/node_pdb.7z":"b7c499c164a800579ec11061dd9771b601fe6aaa86b183b0a865d064febd4348","win-x64/node_pdb.zip":"99df175e6f7fdf1da9c8a8a6c8ffc18b32537e08170b0872657adb7a57f76ed0","win-x86/node.exe":"eb41ebd07e309443703e57bf54deecd00b8b7aee8edaf8eab12421117d94b117","win-x86/node.lib":"ffc5bd433e8156df0de1ffd0e4060fbd218f591b861325fc3f8bd8a406b22ea6","win-x86/node_pdb.7z":"6923077d76c3897fa4abb1347fd19c7f8b79659c7b71cdb6ed26dd3c69f4c91a","win-x86/node_pdb.zip":"4cdc022ed6f67d1e23ebfa3dd3bc9a21e05356e9d19520ed2e42c9ee8bcda68f"}
gyp verb download contents checksum {"node-v8.11.1-headers.tar.gz":"ea28109f7a3b3b21705f25fb0e181e984ece46e785dd9912b5c14df4c067fa07"}
gyp verb validating download checksum for node-v8.11.1-headers.tar.gz (ea28109f7a3b3b21705f25fb0e181e984ece46e785dd9912b5c14df4c067fa07 == ea28109f7a3b3b21705f25fb0e181e984ece46e785dd9912b5c14df4c067fa07)
gyp verb get node dir target node version installed: 8.11.1
gyp verb build dir attempting to create "build" dir: /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/honeycombmacpro/Documents/Study/Angular/first-app/node_modules/node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/honeycombmacpro/.npm/_logs/2018-05-13T08_15_29_317Z-debug.log
Shameems-MacBook-Pro:first-app honeycombmacpro$

**Comment by bnoordhuis** [comment]
> npm ERR! node-sass@4.9.0 postinstall: node scripts/build.js

In other words, you should report this to node-sass.
