### ISSUE TITLE
Error EPERM with NFS mounting system

### ISSUE THREAD

**Issue by migounette** [nodejs/node-gyp#144]
I have a problem on a build system which has a nfs file system mounted.

This operation works fine on another system without the NFS. 

Suppose that my account ystephan

When I run the node-gyp install I have the following issue:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.6.11
gyp info using node@0.8.11 | linux | x64
gyp http GET http://nodejs.org/dist/v0.8.11/node-v0.8.11.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.11/node-v0.8.11.tar.gz
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: EPERM, utime '/home/ystephan/.node-gyp/0.8.11'
gyp ERR! System Linux 2.6.32-131.0.15.el6.x86_64
gyp ERR! command "node" "/opt/OC/bin/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install"
gyp ERR! cwd /home/ystephan/hpoc-config-tool
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.6.11
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

Debug done in order to understand the issue:

I found that node-gyp creates directory via DirWriter, I put some breakpoints I got this:

I removed the directory, the first pass I have this:

```
bash-4.1$ ls -l
total 0
drwxr-xr-x. 2 ystephan users 96 Oct  8 18:10 0.8.11
```

Second pass, still okay (it tires to create the directory one more time)

Then it tries to create a file (.gitignore or .gitaccesss....), then I have the EPERM and when I looked at the directory I have this.

```
bash-4.1$ ls -l
total 0
drwxr-xr-x. 2 24561 users 96 Oct  8 18:37 0.8.11
```

Where...

```
bash-4.1$ id 24561
id: 24561: No such user
```

I take any potential idea.... Thanks

**Comment by Trott** [comment]
It's not clear to me that this is a bug in node-gyp as opposed to a feature/limitation of NFS. I supsect the latter, so I'm going to close, but feel free to re-open (or comment if GitHub does not let you re-open) if you disagree. @nodejs/node-gyp
