### ISSUE TITLE
Azure error npm install ethereumjs-wallet

### ISSUE THREAD

**Issue by gabrieladeniji** [nodejs/node-gyp#1441]
\> npm install ethereumjs-wallet

> scrypt@6.0.3 preinstall D:\home\site\wwwroot\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install D:\home\site\wwwroot\node_modules\scrypt
> node-gyp rebuild

D:\home\site\wwwroot\node_modules\scrypt>if not defined npm_config_node_gyp (node "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Warning: Missing input files:
D:\home\site\wwwroot\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\home\site\wwwroot\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
D:\home\site\wwwroot\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `D:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\8.11.1\\node.exe" "D:\\Program Files (x86)\\npm\\5.6.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\node_modules\scrypt
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
[37;40mnpm [30;43mWARN tigereum-bc-api@1.0.0 No repository field.

[37;40mnpm [31;40mERR! code ELIFECYCLE
[37;40mnpm [31;40mERR! errno 1
[37;40mnpm [31;40mERR! scrypt@6.0.3 install: `node-gyp rebuild`
[37;40mnpm [31;40mERR! Exit status 1
[37;40mnpm [31;40mERR! 
[37;40mnpm [31;40mERR! Failed at the scrypt@6.0.3 install script.
[37;40mnpm [31;40mERR! This is probably not a problem with npm. There is likely additional logging output above.

[37;40mnpm [31;40mERR! A complete log of this run can be found in:
[37;40mnpm [31;40mERR!     D:\local\Temp\monacositeextension\temp\_logs\2018-05-16T10_51_59_087Z-debug.log

**Comment by bnoordhuis** [comment]
Not a node-gyp issue.  Report it to the module you're trying to build, scrypt.
