### ISSUE TITLE
node-gyp installation failures

### ISSUE THREAD

**Issue by lopezdp** [nodejs/node-gyp#1443]
* **Node Version**: 
 
node v8.11.2
npm v6.0.1
 
* **Platform**: 
 
Windows
 
* **Compiler**: 
* **Module**: 
 
<details><summary>Verbose output (from npm or node-gyp):</summary>
 
I have tried to install node-gyp from npm.
 
I have python 2.7 installed
 
I have changed the npm config setting to point to the right version of python
 
i followed the option2 instructions and I have GTK running correctly.
 
I enter the next command: node-gyp rebuild --GTK_Root=C:\Users\davidlop\Documents\Software\GTK
 
and all I get is: bash: node-gyp: command not found
 
I have tried every fix, I have uninstalled and reinstalled node npm.
 
I have followed the instructions to the letter. Can we be provided with a more effective set of instructions?
 
How do I install this I am trying to work with node canvas and node-gyp is required... What am I doing wrong?
 
 
 

 
```
 
I lost track of the log and where it is. Once I get some progress and a new log I will post.
 
```
 
</details>

**Comment by lopezdp** [comment]
Also I added my $PATH/users/AppData/Roaming/npm directory to my PATH. The error I get is:

Error: Cannot find module 'C:\Program Files\Git\node_modules\node-gyp\bin\node-gyp.js'

**Comment by bzoz** [comment]
Did you try `npm install node-gyp` ?

**Comment by lopezdp** [comment]
yes that is the first command described under the verbose section.

I ended up using another library that doesn’t require this. Thanks anyway.
