### ISSUE TITLE
node-gyp configure/rebuild issue OS X

### ISSUE THREAD

**Issue by malevski** [nodejs/node-gyp#1446]
Hello, I'm trying to run a project, using node-gyp. Since Friday I have tried literally what came in my mind:
- Looking in google;
- Looking in stackoverflow;
- Looking in the issues of the repo;
- Removing and installing Node, NPM, N, NVM, Python, Node-gyp several times.
- Restarting my computer, terminal and everything.

* **Node Version**: node -v v8.11.2, node-gyp -v v3.6.2, npm -v 5.6.0
* **Platform**: Darwin 17.5.0 (Mac OS X High Sierra - 10.13.4 (17E202))
* **Compiler**: cc -v
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: Bustabit game server

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
REPO ➤ sudo node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Vizo/Documents/REPO/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Vizo/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Vizo/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Vizo/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Vizo/Documents/REPO',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/Vizo/Documents/REPO) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Vizo/REPO
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

</details>

I have tried, to run the node-gyp with or without sudo. After one of my re-installation, my global node modules are having EACCESS issue, if they are not ran with sudo, because I know I will delete and re-install it again. Any ideas are welcome.

**Comment by bnoordhuis** [comment]
Try asking the project that you're trying to build.  The error message is that it doesn't have a build file (the binding.gyp) that instructs node-gyp how to build it.

I can't help you with that so I'll close this out.
