### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by sudesh8769** [nodejs/node-gyp#1447]
suxdesh_blockchain@fabric: ~/mn/chaincode$ sudo npm i fabric-shim

grpc@1.10.1 install /home/suxdesh_blockchain/mn/chaincode/node_modules/fabric- 
shim/node_modules/grpc
node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/build'
gyp ERR! System Linux 4.13.0-1016-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Linux 4.13.0-1016-azure
node-pre-gyp ERR! command "/usr/bin/node" "/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/suxdesh_blockchain/mn/chaincode/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)

![capture](https://user-images.githubusercontent.com/32675733/40309557-8dbed0f6-5d27-11e8-8ec3-4c3ef582641f.JPG)

**Comment by bnoordhuis** [comment]
Look at the error message: it's node-pre-gyp that is failing, not node-gyp.  Different project.
