### ISSUE TITLE
can not generate ‘.node’ file

### ISSUE THREAD

**Issue by SoldierA15784** [nodejs/node-gyp#1450]
After building my programme, the output looks OK:
<img width="452" alt="2" src="https://user-images.githubusercontent.com/35686469/40642289-3b6fff0e-634f-11e8-807d-cb7103b3ff65.PNG">

but when i try to run my js code, i found there is no 'hello.node' under the path '/build/Release'.
<img width="226" alt="default" src="https://user-images.githubusercontent.com/35686469/40642358-74bd7b9c-634f-11e8-8f47-e148e27d5a4d.PNG">

so... how can i handle it?

here is my C++ code:
<img width="356" alt="3" src="https://user-images.githubusercontent.com/35686469/40642452-b8eb6f7c-634f-11e8-9380-808fa6514469.PNG">

and binding.gyp:

<img width="247" alt="4" src="https://user-images.githubusercontent.com/35686469/40647420-664a6098-635e-11e8-89f7-769330ad8c3c.PNG">

**Comment by bnoordhuis** [comment]
Can you do a clean build and post the full build output?

**Comment by bnoordhuis** [comment]
Your copy of msbuild is localized.  What does it say, something about parallel builds?

FWIW, I don't see it compiling hello.cc anywhere.

**Comment by SoldierA15784** [comment]
thanks for your prompt and positive response。
it says that it would generate a project at a time.And if i want to generate code parallelism, '/m' should be added.
And you are right, the compiler doesn`t work. But i follow the doc step by step, i don`t know why the compiling failed.

**Comment by bnoordhuis** [comment]
Yeah, I'm afraid I don't know either.  Let me know if you figure out what's causing it.

**Comment by SoldierA15784** [comment]
OK

**Comment by maclover7** [comment]
Seems like this is an issue with the compiler being used, not with node-gyp. Going to give this a close since there's not really anything here to fix in node-gyp
