### ISSUE TITLE
node-gyp error.

### ISSUE THREAD

**Issue by VarPrefix** [nodejs/node-gyp#1452]
when i tried to install canvas package

node-gyp errors

`PS C:\Users\siyah\Desktop\Botlar\TakoBot> npm install canvas

> canvas@1.6.11 install C:\Users\siyah\Desktop\Botlar\TakoBot\node_modules\canvas
> node-gyp rebuild

C:\Users\siyah\Desktop\Botlar\TakoBot\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\siyah\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\siyah\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Terminate batch job (Y/N)? N
PS C:\Users\siyah\Desktop\Botlar\TakoBot> npm i canvas

> canvas@1.6.11 install C:\Users\siyah\Desktop\Botlar\TakoBot\node_modules\canvas
> node-gyp rebuild

C:\Users\siyah\Desktop\Botlar\TakoBot\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\siyah\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\siyah\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:406:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\siyah\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\siyah\Desktop\Botlar\TakoBot\node_modules\canvas
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discordbotdersleri@0.0.1 No description
npm WARN discordbotdersleri@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! canvas@1.6.11 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the canvas@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siyah\AppData\Roaming\npm-cache\_logs\2018-05-31T16_06_13_893Z-debug.log`

**Comment by bnoordhuis** [comment]
Please report that over at node-canvas, the "missing input files" thing is not a node-gyp issue.
