### ISSUE TITLE
Add different .gyp file to node-gyp configure 

### ISSUE THREAD

**Issue by blmalone** [nodejs/node-gyp#1461]
* **Node Version**:  v6.14.2
* **Platform**: Linux f6c5cc000a37 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 7.3.1 20180130 (Red Hat 7.3.1-2) (GCC)
* **Module**:  configure

I'm curious if it is possible to be able to rename the `binding.gyp` file so that `node-gyp configure` can use the new renamed file. Can I tell node-gyp for which file to use on `configure`? 

After looking through the source, it seems like this command is enforced to use `binding.gyp`.

```
      // enforce use of the "binding.gyp" file
      argv.unshift('binding.gyp')
```
Referenced in the source [here](https://github.com/nodejs/node-gyp/blob/eaedc12711a6ea94397f15949591c5a80d077944/lib/configure.js#L321)

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

 N/A

**Comment by bnoordhuis** [comment]
> it seems like this command is enforced to use binding.gyp.

That's right, that's by design, so `npm install` works seamless.  Why would you want to use another name?

**Comment by blmalone** [comment]
Thank you for the clarification. I have multiple binding.gyp files, each slightly different depending on the environment I was compiling for. I'll close this issue.

**Comment by ganeshss100** [comment]
Bindind.gyp will be created automatically after you give npm install node-gyp ?
