### ISSUE TITLE
Security vulnerability in dependency chain

### ISSUE THREAD

**Issue by ebickle** [nodejs/node-gyp#1465]
Installing node-gyp 3.7.0 via NPM causes a security vulnerability notice to appear. Hoek 2.16.3 has a vulnerability in it, which exists in the node-gyp dependency chain. 
node-gyp -> request -> hawk -> hoek

Please update your dependencies or work with those package owners to fix the issue as well. As a result of this issue, the security vulnerability flows up into node-gyp and causes my package to fail our corporate static security analysis.

* **Node Version**: v9.7.0
* **Platform**: Windows 7 Enterprise, 6.1.7601 Service Pack 1, x64
* **Compiler**: N/A
* **Module**: N/A

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
PS C:\Users\user\Documents\Source\custompackage> npm install
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

voltage-node@1.0.9 C:\Users\user\Documents\Source\custompackage
`-- node-gyp@3.7.0
  `-- request@2.81.0
    `-- hawk@3.1.3
      +-- boom@2.10.1
      | `-- hoek@2.16.3  deduped
      +-- hoek@2.16.3
      `-- sntp@1.0.9
        `-- hoek@2.16.3  deduped
```

</details>

**Comment by bnoordhuis** [comment]
Duplicate of several other issues, e.g. #1439.
