### ISSUE TITLE
node-gyp fails to find VS 2017 if "USB Device Connectivity" component is installed in VS 15.7

### ISSUE THREAD

**Issue by tydunkel** [nodejs/node-gyp#1466]
- Node Version: node v8.4 npm 6.1.0 node-gyp 3.6.2
- Platform: Win10
- Full VS 15.7 installation

node-gyp configure will fail to find VS 2017 if a full installation of 15.7 is installed.

Visual Studio 15.7 added a new optional component named "USB Device Connectivity". The id of the component is `Microsoft.VisualStudio.Component.Windows10SDK.IpOverUsb`. This will cause the UInt32.Parse call in the line of code linked below to throw, resulting in node-gyp using default settings.

https://github.com/nodejs/node-gyp/blob/b5b52f7bffb55064a623e2478252a8939259cf3f/lib/Find-VS2017.cs#L235

Maybe consider a try/catch for the parse, or checking with regex that parts[0] is actually a valid number.

**Comment by refack** [comment]
Looking into this.
