### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by xiechuanlong** [nodejs/node-gyp#1467]
Node Version:  v6.9.2
node-gyp Version: v3.4.0
Platform:/ Linux 3.2.0-4-amd64
error message: 
 npmInstall:
     [exec] 
     [exec] > integer@1.0.3 install /srv/ssd1/xxxxx
     [exec] > node tools/install
     [exec] 
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: not found: make
     [exec] gyp ERR! stack     at getNotFoundError (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:14:12)
     [exec] gyp ERR! stack     at F (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:69:19)
     [exec] gyp ERR! stack     at E (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:81:29)
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:90:16
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
     [exec] 
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
     [exec] > farmhash@1.2.1 install /srv/ssd1/kaola/source/kaola-promotionms-web-pro_test1/promotionms-front-web/src/main/resources/webapp/node_modules/farmhashgyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
     [exec] 
     [exec] > node-gyp rebuild
     [exec] gyp ERR! System Linux 3.2.0-4-amd64
     [exec] 
     [exec] gyp ERR! command "/home/ndp-soft/node-v6.9.2-linux-x64/bin/node" "/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
     [exec] gyp ERR! cwd /srv/ssd1/kaola/source/kaola-promotionms-web-pro_test1/promotionms-front-web/src/main/resources/webapp/node_modules/integer
     [exec] gyp ERR! node -v v6.9.2
     [exec] gyp ERR! node-gyp -v v3.4.0
     [exec] gyp ERR! not ok 
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: not found: make
     [exec] gyp ERR! stack     at getNotFoundError (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:14:12)
     [exec] gyp ERR! stack     at F (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:69:19)
     [exec] gyp ERR! stack     at E (/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:81:29)
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/which.js:90:16
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
     [exec] gyp ERR! stack     at /home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
     [exec] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
     [exec] gyp ERR! System Linux 3.2.0-4-amd64
     [exec] gyp ERR! command "/home/ndp-soft/node-v6.9.2-linux-x64/bin/node" "/home/ndp-soft/node-v6.9.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
     [exec] gyp ERR! cwd /srv/ssd1/kaola/source/kaola-promotionms-web-pro_test1/promotionms-front-web/src/main/resources/webapp/node_modules/farmhash
     [exec] gyp ERR! node -v v6.9.2
     [exec] gyp ERR! node-gyp -v v3.4.0
     [exec] gyp ERR! not ok 
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec] npm WARN promotion@1.0.0 No repository field.
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 (node_modules/integer):
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.3 install: `node tools/install`
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 (node_modules/farmhash):
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 install: `node-gyp rebuild`
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

notice: The make command line tools has been installed。 
I am looking forward to your help！！

**Comment by bnoordhuis** [comment]
> [exec] gyp ERR! stack Error: not found: make

You need to install make.  Check the readme for the other prerequisites too.

**Comment by xiechuanlong** [comment]
but the make command line tools has been installed! I don't know why.

**Comment by bnoordhuis** [comment]
You'll have to provide more details if you want an answer.  How did you install make?  What about g++ or clang++?  What do `make -v` and `which make` print?
