### ISSUE TITLE
Error: Can't find Python executable node-gyp rebuild

### ISSUE THREAD

**Issue by rafaP** [nodejs/node-gyp#1474]
* **Node Version**: 
* **Platform**: <OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
System Type:               x64-based PC>

* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>
> opencv4nodejs@4.5.2 install C:\Users\rafael.pereira\Desktop\node\node_modules\opencv4nodejs
> node-gyp rebuild

C:\Users\rafael.pereira\Desktop\node\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\rafael.pereira\AppData\Local\Programs\Python\Python36-32\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rafael.pereira\Desktop\node\node_modules\opencv4nodejs
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
</details>

**Comment by bnoordhuis** [comment]
Did you do what the error message suggests?

**Comment by rafaP** [comment]
Yes I have done that.

Cumprimentos, Rafael Pereira

________________________________

**Comment by bnoordhuis** [comment]
And?  Note that you should it to a python 2 executable, not python 3.

**Comment by rafaP** [comment]
Oh, i will install python 2

**Comment by bnoordhuis** [comment]
Cool.
