### ISSUE TITLE
issue in installing npm 

### ISSUE THREAD

**Issue by hariharan1993** [nodejs/node-gyp#1477]
When i ran npm install i got this error 

> dtrace-provider@0.8.7 install /home/hariharan/fabric-samples/fabcar/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:184:21)
gyp ERR! System Linux 4.4.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hariharan/fabric-samples/fabcar/node_modules/dtrace-provider
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> pkcs11js@1.0.16 install /home/hariharan/fabric-samples/fabcar/node_modules/pkcs11js
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:184:21)
gyp ERR! System Linux 4.4.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hariharan/fabric-samples/fabcar/node_modules/pkcs11js
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN fabcar@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hariharan/.npm/_logs/2018-06-20T10_47_17_523Z-debug.log

**Comment by bnoordhuis** [comment]
> gyp ERR! stack Error: not found: make

You need to install make.  Check the readme for the prerequisites.

**Comment by pesicsasa** [comment]
Yes. Also not a bad idea to check if you may be missing g++.

**Comment by AaronFriel** [comment]
@bnoordhuis can this be re-opened?

It looks like this is a race condition / heisenbug. I'm sometimes seeing this in build logs, sometimes not in a business CI/CD system. We're using builds using a reliable docker image, and it looks like *sometimes* `make` is not being detected (or installed?) and sometimes not.

**Comment by rvagg** [comment]
@AaronFriel best if you open a new issue since I believe the original was actually about not having `make` installed. If you can narrow down conditions, approximations of when/how it happens or even come up with something reproducible then that would be very helpful. If you really have `make` installed (even on your CI/CD where system heisenbugs can appear!) then I'd be looking at `PATH` and even after that be looking at [which](https://github.com/npm/node-which), the library that does the work in node-gyp of looking for `make`, we don't do that much here and as you can see from the error output above, it's all coming out of which.

https://github.com/nodejs/node-gyp/blob/6b8f2652dde9f687f4d98fb26cf923825c2776c1/lib/build.js#L110
