### ISSUE TITLE
unable to match option with wmmintrin

### ISSUE THREAD

**Issue by calidion** [nodejs/node-gyp#1487]
* **Node Version**:  v8.11.2, 6.1.0
* **Platform**:

Linux eric-MacBookAir 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* **Compiler**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
* **Module**:  private

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
In file included from ../src/crypto/slow-hash.c:10:0:
../src/crypto/slow-hash.c: In function ‘ExpandAESKey256_sub2’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
../src/crypto/slow-hash.c:97:8: error: called from here
   tmp4 = _mm_aeskeygenassist_si128(*tmp1, 0x00);
        ^
```

</details>

it can be compiled with sse4.1 out side node-gyp.

**Comment by bnoordhuis** [comment]
That's an issue with the module you're trying to build, or the compiler you're trying to build it with, not node-gyp, that's just the build tool.

**Comment by calidion** [comment]
@bnoordhuis  it is ok out side of node-gyp. my build tools are the same.

**Comment by bnoordhuis** [comment]
Then you're passing wrong options or using the wrong compiler.  `env V=1 node-gyp rebuild` prints the commands.

**Comment by calidion** [comment]
I created a main.c
```
#include "./wallet/wallet.h"
#include <iostream>


using namespace std;

int main() {

  cout << "Hello world" << endl;
  cout << Wallet::decrypt << endl;
  return 0;
}

```

using the command:
```
g++ src/main.c  -o a.out -std=c++11
```
and executed:
```
./a.out
```
to get : 
```
Hello world
1
```
so i am sure it is complied out side of the node-gyp env.

**Comment by calidion** [comment]
@bnoordhuis 

thanks.

by using `env V=1 node-gyp rebuild`, it prints that `cc` command lacks the flags the code needed.

by adding:
```
        "cflags": [
            "-msse2",
            "-maes"
        ],

```
solved this problem.
