### ISSUE TITLE
PATH env variable not set after global install

### ISSUE THREAD

**Issue by dotBeFoRE** [nodejs/node-gyp#1489]
* **Node Version**: node v10.5.0 - nmp 6.1.0
* **Platform**: Windows 10 Pro (1803)

Installed node-gyp using `npm install -g node-gyp` in CMD with administrative rights, but node-gyp is not set as a PATH env variable

No errors, no warnings

**Comment by dotBeFoRE** [comment]
A little more info
I had my Windows reinstalled and dragged and dropped all my user files (that includes all npm packages and configs) into the freshly installed user folder. 

I now uninstalled NodeJs and deleted all of npm, reinstalled everything including node-gyp. The env variable seems to be set now.

**Comment by bzoz** [comment]
`npm` installs commands (`node-gyp.cmd` in this case) in a location that is added to the `PATH` by the Node installer. If you did not install Node on a new box, the `PATH` was not set up properly.
