### ISSUE TITLE
This toolset may be unknown or missing

### ISSUE THREAD

**Issue by micka753** [nodejs/node-gyp#1493]
* **Node Version**: node 8.11.3 & npm 5.6.0
* **Platform**: Windows 7, .net framework 4.7.1 Windows 8.1 Sdk installed
* **Compiler**: I installed with ms build tools 2017 (I checked 2015 and most other stuff too)
* **Module**: fail with everything

<details><summary>Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.DesignTime.targets(488,5): error MSB4062: The "SetEnv" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Build.CppTasks.Common.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b555555555550a3a' or one of its dependencies. Le fichier sp‚cifi‚ est introuvable. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\Apps\gestion-outil\node_modules\serialport\build\serialport.vcxproj</summary>
</details>

I can't have Internet and launch an admin prompt so Windows build tools is not an option.
I have been trying to fix the issue for a while now, any help would be appreciated, thanks.

**Comment by bzoz** [comment]
Can you run `node-gyp build --verbose` and paste complete output?

**Comment by GoodnessEzeokafor** [comment]
i'm having the same issue

**Comment by cclauss** [comment]
@GoodnessEzeokafor Can you run node-gyp build --verbose and paste complete output?

**Comment by GoodnessEzeokafor** [comment]
thanks for the reply bt i've fixed, apperently my file path was set to the old msbuild.exe file
