### ISSUE TITLE
node-gyp - MSBuild 14.0 - exit code 1

### ISSUE THREAD

**Issue by danielbecroft** [nodejs/node-gyp#1494]
We are receiving the following build error when running 'npm install' inside of a Visual Studio project.

* **Node Version**:
Node: v10.5.0
NPM: 6.1.0

* **Platform**:
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
System Type:               x64-based PC

* **Compiler**: 
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework

* **Module**: ttf2woff

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
  > ttf2woff2@2.0.3 install <build-directory>\app\node_modules\ttf2woff2
  > (node-gyp rebuild > builderror.log) || (exit 0)

  gyp ERR! build error
EXEC : gyp ERR! stack error : `msbuild` failed with exit code: 1 [<msbuild project filename>]
  gyp ERR! stack     at ChildProcess.onExit (C:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
  gyp ERR! System Windows_NT 6.3.9600
  gyp ERR! command "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
  gyp ERR! cwd <build-directory>\app\node_modules\ttf2woff2
  gyp ERR! node -v v10.5.0
  gyp ERR! node-gyp -v v3.6.2
  gyp ERR! not ok
  added 731 packages from 535 contributors and audited 4682 packages in 52.56s
  found 187 vulnerabilities (173 low, 7 moderate, 7 high)
```

</details>

We are running the following commands inside of a <PostBuildEvent> of a Visual Studio ASP.NET project. The project is being build with MSBuild 15.0 (Visual Studio 2017) - maybe the use of two different MSBuild versions is the issue?

```
<PostBuildEvent>
	cd $(ProjectDir)app
	call npm install
	call bower install
	call polymer build
	set ERRORLEVEL=0
</PostBuildEvent>
```

The builds are running through Jenkins, with a new workspace each build. The strange thing is that the build will consistently fail every other build (so fails, works, fails, works). I can't tell what the differences are between the separate builds.

I've inherited this project, so I'm not completely familiar with Node.

**Comment by bzoz** [comment]
Can you try running `npm install --verbose`?
