### ISSUE TITLE
Missing extension causes build failures on Windows 10

### ISSUE THREAD

**Issue by markmaynard** [nodejs/node-gyp#1510]
https://github.com/nodejs/node-gyp/blob/c5e980232e2cf9191f2853bccb341823da0a0c6c/lib/node-gyp.js#L67

I resolved the following error:
ERROR in ./node_modules/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in 'D:\gitrepos\eqianalyzer\node_modules\node-gyp\lib'

In v3.7.0

by adding an explicit .json to the `require('../package');`

**Comment by markmaynard** [comment]
https://github.com/markmaynard/node-gyp/commit/3767b782d984e894e492dfb0c7d63b111ff29d4d

**Comment by rvagg** [comment]
seems like a dodgy verison of Node or maybe something loaded in your environment that's messing this up, closing due to age and no further reports
