### ISSUE TITLE
The Visual C++ Build Tools install link in the project README should be changed

### ISSUE THREAD

**Issue by nicszerman** [nodejs/node-gyp#1515]
The current link is dead. It took me 10 minutes of googling to find the correct one.
I think the correct one is https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

Maybe other changes to the install instructions are required as well; I don't know since I changed my mind and did option 1.

**Comment by richardlau** [comment]
https://github.com/nodejs/node-gyp/pull/1392

**Comment by nicszerman** [comment]
@richardlau The link does not point anymore to what that issue describes. I think it leads to the 404 of their website.

**Comment by ManfredLange** [comment]
As of 27 Sep 2018 the VS 2015 build tools are available at https://visualstudio.microsoft.com/vs/older-downloads/ . On that page expand the last section named "Redistributables and Build Tools" and then pick "Microsoft Build Tools 2015 Update 3"

**Comment by rvagg** [comment]
please open a PR if the links we have are incorrect, closing this due to age
