### ISSUE TITLE
Need support for Visual Studio 17, version 15.8

### ISSUE THREAD

**Issue by gauravms** [nodejs/node-gyp#1529]
Hi,

We are building a native node module and we see that there isn't any support for Visual Studio 2017 (see line 149 [here with gyp.opts.msvs_version = '2015'](https://github.com/nodejs/node-gyp/blob/master/lib/configure.js)). Also, we need to use [conformance mode for the compiler](https://blogs.msdn.microsoft.com/visualstudio/2018/08/14/visual-studio-2017-version-15-8/) released as part of visual studio [version 15.8](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes) - currently adding 'experimental':'preprocessor' to 'VCCLCompilerTool' and /permissive- flag to 'AdditionalOptions' in binding.gyp has no effect on the compilation. 
Although VS2017, version 15.8 was just released, when can we expect support for the conformance mode? Our native module is CPP/WRL ported to CPP/WinRT and we need this conformance mode for the module to compile.

Thanks,
Gaurav

* **Node Version**: 8.11.3 
* **Platform**: Windows 10
* **Compiler**: Visual C++ compiler 
* **Module**: Native node module 

<details><summary>Verbose output (from npm or node-gyp): Warning: unrecognized setting VCCLCompilerTool/experimental while converting to MSBuild.</summary>

```

```

</details>

**Comment by gauravms** [comment]
I need c++ compiler support released as part of version 15.8 which is latest and also want compiler flag support as I mentioned. My project is not compiling with latest node-gyp even when it says that is using v141 build tools.

**Comment by refack** [comment]
Just to make sure everything works, you could run ```node-gyp configure```, then patch the `.vcxproj` and run `msbuild` manually.

Also could you post your `binding.gyp`?
