### ISSUE TITLE
Visual Studio 2017 generates link error

### ISSUE THREAD

**Issue by filipecalasans** [nodejs/node-gyp#1530]
I'm facing the following error when I'm building a project generated to VS2015, v141 (node-gyp workaround) using Visual Studio 2017 

> cl : Command line error D8036: '/FoRelease\obj\<PROJECT_NAME>\D' not allowed with multiple source files [<PROJECT_PATH>\<PROJECT_NAME>.vcxproj]cl : Command line error D8036: '/FoRelease\obj\<PROJECT_NAME>\D' not allowed with multiple source files [<PROJECT_PATH>\<PROJECT_NAME>.vcxproj]

This issue is caused due to default value of the property **Object File Name** to be always generated as **$(IntDir)D**. So, I added the following code section at pylib/gyp/msvs.py [line: 3070]. Therefore, it generates a default ObjectFileName property in the project avoiding Visual Studio 2017 to use the default (broken) one.

```[py]
# Add define ObjectFileName, default value in VS2017 
# is causing compilation error due to duplicated object file names
_ToolAppend(msbuild_settings, 'ClCompile',
             'ObjectFileName', '$(IntDir)')
```

* **Node Version**:  v8.11.4
* **Platform**: Windows 10
* **Compiler**: Visual Studio 2017. v141
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by bzoz** [comment]
Could you provide an example project that reproduces this?

**Comment by pacop** [comment]
Same problem right here, did you find some workaround?

**Comment by pacop** [comment]
For some other users that may have been experiencing the same issue. I have solved adding to the `binding.gyp`
```
'msvs_settings': {
  'VCCLCompilerTool': {
     'ObjectFile': "$(IntDir)/%(Directory)/"
  }
},
```
