### ISSUE TITLE
What is the correct way to generate prebuilt addon that depends on a shared library?

### ISSUE THREAD

**Issue by JCMais** [nodejs/node-gyp#1532]
I've a Node.js binding for libcurl, with prebuilt binaries available through node-pre-gyp, and I'm having some issues while building the prebuilt binaries for macOS, this is not really an issue with node-gyp itself, but more of asking for help. If this is not the right place, let me know, I've not asked on SO since most questions there about node-gyp / Node.js native addons do not get any answer.

This is the binding file: https://github.com/JCMais/node-libcurl/blob/da2de42/binding.gyp

The issue is that one: https://github.com/JCMais/node-libcurl/issues/43

I think it's two issues in reality, first one, is the linked library file, which has travis path on it. 
```
Library not loaded: /Users/travis/lib/libcurl.4.dylib
```

And the other is that incompatible version error:
```
 Reason: Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

This is probably something really wrong I'm doing, mostly due to my small experience when linking libraries.

I've ran `otool` against the `.node` file and it prints the following:
```
➜ otool -L node_modules/node-libcurl/lib/binding/node_libcurl.node
node_modules/node-libcurl/lib/binding/node_libcurl.node:
	/Users/travis/lib/libcurl.4.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Some facts:
I'm downloading the latest libcurl to build the prebuilt binary, so, most of the time, the library is going to be built with a more recent version of libcurl, but is going to be installed in a machine which has an older version, and I'm mostly sure this can cause issues.

What is the recommended solution here? Always build the addon with static libraries instead of shared ones?

On linux it works correctly, without any problems. This is the result of running `readelf -d node_modules/node-libcurl/lib/binding/node_libcurl.node` on linux:
```
Dynamic section at offset 0x29a90 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [node_libcurl.node]
```

Thoughts?

**Comment by refack** [comment]
Hello @JCMais and thank you for the report.
Generally usage questions should go to https://github.com/nodejs/help, so I'm going to close this issue.

I'm not a linux/macOS expert but if I understand the above error correctly it seems to me that you issue stems from the fact that you pre-built your addon against a dynamic libcurl@9 and trying to use it with a dynamic libcurl@7. If they are not ABI (i.e. binary) compatible, it can not work. I can think of three quick options:
1. Build with a static library. That's one that gets statically linked and becomes a part of your binary, so it doesn't need anything to be available on the client machine.
2. Install a dynamic libcurl@9 on the client machine, in a place that the dynamic loader can find it.
3. Try to locally rebuild the addon, if libcurl@9 and libcurl@7 are API compatible (i.e. the headers allow you to compile) it might work.
