### ISSUE TITLE
Python executable not found

### ISSUE THREAD

**Issue by DrYSG** [nodejs/node-gyp#1536]
I have read https://stackoverflow.com/questions/47508990/cant-find-python-executable and that is still not working for me.

I have tried putting in my .npmrc either

 - python=D:\Program Files (x86)\Python37-32\python.exe
 - python=D:\Program Files (x86)\Python37-32

An while the python.exe certainly is there, (and is on my windows PATH variable).

I still get:
```
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "D:\Program Files (x86)\Python37-32\python.exe", you can set the PYTHON env variable.
    gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
    gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
    gyp ERR! System Windows_NT 10.0.14393
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd D:\Source\Orchestrator\orchestrator\node_modules\nanomsg
```

**Comment by bzoz** [comment]
You need Python 2.x, version 3 is not supported.

**Comment by DrYSG** [comment]
Ok, but why does the error read that it cannot find the python executable?

Error: Can't find Python executable "D:\Python", you can set the PYTHON env variable. at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)

**Comment by DrYSG** [comment]
If you are detecting it is the wrong version in NPM, can it not put out the same message as in "Node" (I guess I don't appreciate the distinction)

**Comment by richardlau** [comment]
There's this PR to modify the error message: https://github.com/nodejs/node-gyp/pull/1269

**Comment by DrYSG** [comment]
added this to my .npmrc and it works. Maybe this could be in the readme?

python=D:\Program Files (x86)\Python27\python.exe

**Comment by pravintamil** [comment]
I got an error `Can't find python executable` while configuring

![image](https://user-images.githubusercontent.com/14850417/45994639-2c046f80-c0b2-11e8-8bc1-581c27ac9c9d.png)
