### ISSUE TITLE
add PropertyGroup to Visual Studio project

### ISSUE THREAD

**Issue by xenomarz** [nodejs/node-gyp#1537]
Hi there,
How can I specify that I want to add a custom PropertyGroup to my generated Visual Studio project? For example, I want to be able to add this PropertyGroup:
```
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <UseIntelMKL>Parallel</UseIntelMKL>
  </PropertyGroup>
```
Any chance it is possible somehow? I tried to use `msvs_props`, but I keep getting a warning `Do not know how to convert MSVS attribute InheritedPropertySheets`.

version 3.8.0

Thanks

**Comment by bnoordhuis** [comment]
You can't right now. I guess it could be added but right now you can't.

**Comment by rvagg** [comment]
might be a feature request for https://github.com/refack/GYP I think
