### ISSUE TITLE
node-gyp failing on Windows x64

### ISSUE THREAD

**Issue by seanmonstar** [nodejs/node-gyp#154]
As seen in ncb000gt/node.bcrypt.js#122, there's an error building native modules on Windows x64. I see the same error when build node-proxy, node-mailer, and others.

<details>

```
npm install bcrypt
> bcrypt@0.7.1 install D:\Users\Sean\Documents\Mozilla\browserid\node_modules\bcrypt
> node-gyp rebuild


D:\Users\Sean\Documents\Mozilla\browserid\node_modules\bcrypt>node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'bcrypt_lib.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are tryin
g to build a project without a solution file, and have specified a non-default
Platform that doesn't exist for this project. [D:\Users\Sean\Documents\Mozilla\
browserid\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\Sean\Documents\Mozilla\browserid\node_modules\bcrypt
gyp ERR! node -v v0.8.12
gyp ERR! node-gyp -v v0.7.0
gyp ERR! not ok
npm ERR! bcrypt@0.7.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! cwd D:\Users\Sean\Documents\Mozilla\browserid
npm ERR! node -v v0.8.12
npm ERR! npm -v 1.1.63
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Users\Sean\Documents\Mozilla\browserid\npm-debug.log
npm ERR! not ok code 0
```

</details>

**Comment by robin521111** [comment]
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'co
nnect' }

**Comment by robin521111** [comment]
i got below error, and when i look into the folder, there is no error, very strange!
VCBUILD : error : project file 'C:\Users\28850775\AppData\Roaming\npm\node_modu
les\mean-cli\node_modules\mongoose\node_modules\mongodb\node_modules\bson\build
\bson.vcproj' was not found or not a valid project file. [C:\Users\28850775\App
Data\Roaming\npm\node_modules\mean-cli\node_modules\mongoose\node_modules\mongo
db\node_modules\bson\build\binding.sln]

**Comment by Drasius2** [comment]
Solution look this post: http://stackoverflow.com/questions/14573488/error-compiling-bcrypt-node-js

**Comment by kevinlvhsl** [comment]
before install python

**Comment by kevinlvhsl** [comment]
you can try install python and node-gyp  before install bcrypt

**Comment by moxiaobei2** [comment]
Is that worked with windows sdk?windows sdk download so slowerly,i am down~

**Comment by yonkyunior** [comment]
[seamonstar](https://github.com/seanmonstar) It's works, i got the same issues, installing M Visual C++ Redistributable 2005-2015, btw, i installed webmatrix before, i dont think its needed too. and i have M Visual Studio Tools for Application 2012, running well in win 7 x64 now.. thanks a lot!!

**Comment by xgqfrms-GitHub** [comment]
https://github.com/nodejs/node/issues/8939

**Comment by gopithiru** [comment]
C:\xampp\htdocs\gopi\seek-starter>npm test

> seek-starter@0.0.1 test C:\xampp\htdocs\gopi\seek-starter
> npm run unit


> seek-starter@0.0.1 unit C:\xampp\htdocs\gopi\seek-starter
> karma start --single-run

04 02 2017 19:17:43.806:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
04 02 2017 19:17:43.814:INFO [launcher]: Starting browser Chrome
04 02 2017 19:17:45.532:INFO [Chrome 55.0.2883 (Windows 7 0.0.0)]: Connected on socket kjejRwvc9wYxE_aCAAAA with id 51858386
Chrome 55.0.2883 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.005 secs / 0 secs)

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Un1que_85\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "unit"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! seek-starter@0.0.1 unit: `karma start --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the seek-starter@0.0.1 unit script 'karma start --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the seek-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs seek-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls seek-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\gopi\seek-starter\npm-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by MalinBranne** [comment]
Hi! 

I wonder if you could help me. 

I get the following error on windows when trying to install bcrypt: 

denne@DESKTOP-F6FQ1NO MINGW64 ~/st-progress/Backend (master)
$ npm i
> bcrypt@3.0.0 install C:\Users\denne\st-progress\Backend\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
Traceback (most recent call last):
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2025, in GenerateOutput
    version=msvs_version)
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 340, in Write
    f.close()
  File "D:\Node.js\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 393, in close
    os.rename(self.tmp_path, filename)
WindowsError: [Error 183] Det gÕr inte att skapa en fil som redan finns
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Node.js\\node.exe" "D:\\Node.js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\denne\\st-progress\\Backend\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\denne\\st-progress\\Backend\\node_modules\\bcrypt\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "--python=C:\\Users\\denne\\.windows-build-tools\\python27\\python.exe"
gyp ERR! cwd C:\Users\denne\st-progress\Backend\node_modules\bcrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Node.js\node.exe D:\Node.js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\denne\st-progress\Backend\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\denne\st-progress\Backend\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --python=C:\Users\denne\.windows-build-tools\python27\python.exe' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\denne\st-progress\Backend\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\Node.js\\node.exe" "C:\\Users\\denne\\st-progress\\Backend\\node_modules\\bcrypt\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\denne\st-progress\Backend\node_modules\bcrypt
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok
Failed to execute 'D:\Node.js\node.exe D:\Node.js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\denne\st-progress\Backend\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\denne\st-progress\Backend\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --python=C:\Users\denne\.windows-build-tools\python27\python.exe' (1)
npm WARN backend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\denne\AppData\Roaming\npm-cache\_logs\2018-10-12T12_32_17_444Z-debug.log


How do I solve this?

**Comment by refack** [comment]
@MalinBranne I think the key is in `WindowsError: [Error 183] Det gÕr inte att skapa en fil som redan finns` I'm not sure if there's a FS link issue, or it might be just codepage problems with python.
Can you try running `chcp 437` before trying to install (https://ss64.com/nt/chcp.html)

**Comment by MalinBranne** [comment]
Thank you Refael, Ill give it a try :)

**Comment by dewelloper** [comment]
I want to install edge.js and it has a dependency to node-gyp and c++ build tools

Node-gyp in its github said Python must be 2.7 for getting this error but in my case i have tryed 2.7 and 2..7.15 nothing changed
Also i got a dependency too node-java

bored
**java@0.11.0 install: `node-gyp rebuild`** 

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HAMIT\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\studies\edgejs\edge\node_modules\java
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN edge@8.2.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! java@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the java@0.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HAMIT\AppData\Roaming\npm-cache\_logs\2019-05-20T13_41_30_259Z-debug.log

**Comment by richardlau** [comment]
> gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT

@dewelloper https://github.com/nodejs/node-gyp/issues/1688

**Comment by dewelloper** [comment]
@richardlau 
i have 4 gb free memory what i need to working out :)

**Comment by richardlau** [comment]
> 
> 
> @richardlau
> i have 4 gb free memory what i need to working out :)

Nothing to do with the amount of memory you have. If you read the issue I linked to, `node-gyp` doesn't currently support Visual Studio 2019. You could try the workaround posted in the same issue: https://github.com/nodejs/node-gyp/issues/1688#issuecomment-479568599

**Comment by dewelloper** [comment]
I have tryed 2015 and 2017 also ok thanks

**Comment by meeratony** [comment]
> 
> 
> you can try install python and node-gyp before install bcrypt

That helped i installed python on my linux platform and it helped : apk add python-dev build-base gcc make
