### ISSUE TITLE
node-gyp ignores (c++17) cflag

### ISSUE THREAD

**Issue by JlnWntr** [nodejs/node-gyp#1543]
* **Node Version**:  via package-manager
* **Platform**: Ubuntu 16.04
* **Compiler**: gcc-8
* **Module**: my own

I try to configure & build a node.js C++ addon with this 
binding.gyp file:

    { 
      "targets": [
        {
          "target_name": "addon",
          "sources": [ "addon.cpp" ],
          "cflags": [
            "-std=c++17"
          ]          
        }
      ]
    }

But when I run `node-gyp configure` and `node-gype rebuild`
I always get messages like

> warning: ‘if constexpr’ only available with -std=c++17 or -std=gnu++17

The build also fails, because I really depend on these c++17 features. What am I doing wrong?

**Comment by richardlau** [comment]
Maybe try `cflags_cc` instead of `cflags`? It's what `common.gypi` uses: https://github.com/nodejs/node/blob/eaaee92d9b0be82d7f40b2abb67f30ce525d4bc4/common.gypi#L371

**Comment by JlnWntr** [comment]
This works. Thanks.

**Comment by luizperes** [comment]
If you are on Mac, it is actually

```
...
"xcode_settings": {
  ...
  "OTHER_CFLAGS": [ "-std=c++17"],
},
```

It wouldn't work for me otherwise...

**Comment by mceIdo** [comment]
In case anyone reaches here and could get windows builds to work - see https://github.com/nodejs/node-gyp/issues/1662#issuecomment-754283275
