### ISSUE TITLE
"python": "^2.7" should be defined in "engines" field of node-gyp/package.json

### ISSUE THREAD

**Issue by hulkish** [nodejs/node-gyp#1545]
This would be helpful to know during the install phase of node-gyp. Is there any reason not to fo this?

**Comment by refack** [comment]
The only issue that might arise is that `node-gyp` is a dep of `npm` and if it fails, AFAIR it will propagate to fail `npm`. For most users that's an unneeded fails.

**Comment by hulkish** [comment]
@refack I admit this is not specifically a` node-gyp` concern. I guess the question is how are we intended to communicate these kinds of requirements? 

For example, if you don't know that python is required when you install node-gyp - you only learn so when trying (and failing) to actually use node-gyp. Which, I think it might be better to at least emit a warning on the install phase.

**Comment by refack** [comment]
> Which, I think it might be better to at least emit a warning on the install phase.

That's a nice idea. If you have the time to submit a PR to hook `script: {install}`, that would be much appreciated.
