### ISSUE TITLE
“DefineOwnProperty”:  is not “v8::Object” member

### ISSUE THREAD

**Issue by ForeverPx** [nodejs/node-gyp#1550]
when i run   node-gyp rebuild --target=3.0.0 --arch=ia32    in  ffi modules， it console

c:\work\ss\dist\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: “DefineOwnProperty”: 不是“v8::Object”的成员 (编译源文件 ..\src\ffi.cc) [c:\work\ss\dist\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\cvte10\.node-gyp\iojs-3.3.1\include\node\v8.h(2562): note: 参见“v8::Object”的声明 (编译源文件 ..\src\ffi.cc)
c:\work\ss\dist\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: “DefineOwnProperty”: 不是“v8::Object”的成员 (编译源文件 ..\src\threaded_callback_invokation.cc) [c:\work\ss\dist\node_modules\ffi\build\ffi_binding
s.vcxproj]
  c:\users\cvte10\.node-gyp\iojs-3.3.1\include\node\v8.h(2562): note: 参见“v8::Object”的声明 (编译源文件 ..\src\threaded_callback_invokation.cc)
c:\work\ss\dist\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: “DefineOwnProperty”: 不是“v8::Object”的成员 (编译源文件 ..\src\callback_info.cc) [c:\work\ss\dist\node_modules\ffi\build\ffi_bindings.vcxproj]

my node version is  10.2.0  arch ia32

**Comment by bnoordhuis** [comment]
Closing, not a node-gyp issue.
