### ISSUE TITLE
Switch to a JS implementation?

### ISSUE THREAD

**Issue by Pomax** [nodejs/node-gyp#1556]
The readme for https://github.com/indutny/gyp.js/ covers the reasons, really. The fact that even at Node 10 we're still forced to have a Python dependency for Node projects is kind of insane. Especially a python 2.7 dependency that really only makes sense for Apple users because only they are forced into a perpetual python 2.7 installation.

**Comment by richardlau** [comment]
See also https://github.com/nodejs/node-gyp/issues/960. 

https://github.com/nodejs/node-gyp/pull/1092 is open to add gyp.js support, but it looks to have stalled.

**Comment by rvagg** [comment]
yes, stalled, needs a new champion to push it forward
