### ISSUE TITLE
compilation of third-party OpenCV static libraries succeeded with ubantu, but failed to run.

### ISSUE THREAD

**Issue by happytoTom** [nodejs/node-gyp#1557]
I build the code on ubantu, this is my binding.gyp file
{
  "targets": [{
    "target_name": "first",
    "sources": [
      "./cc/first_nan.cpp"
    ],
    "include_dirs": [
        "<!(node -e \"require('nan')\")",
      ],
  },
  {
    "target_name": "opencv",
    'conditions':[[
      "OS==\"linux\"",{
      "libraries": [ "/home/t/opencv/opencv-3.4.2/build/lib/libopencv_world.a" ],
    }
    ]],
    "type": "static_library",
    "sources": [
      "./cc/rotate.cpp"
    ],
    "include_dirs": [
      './cc',
      "/home/t/opencv/opencv-3.4.2/build/lib"
    ]
  }]
}
this is run result, i dont konw how to do  plz help me..

thanks
node: symbol lookup error: /home/t/chromosomeServer/build/Release/first.node: undefined symbol: _ZN2cv6String8allocateEm

**Comment by bnoordhuis** [comment]
Closing, not a node-gyp issue. You need to link properly against opencv, just passing the path to the archive isn't sufficient. Look up the -l and -L flags in `man cc`.
