### ISSUE TITLE
CI Updates

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/node-gyp#1562]
@nodejs/node-gyp FYI, let me know if there's an issue with any of this.

In [nodegyp-test-pull-request](https://ci.nodejs.org/job/nodegyp-test-pull-request/):

- Updated Node.js and npm versions.
- Changed `PR_ID` to `REMOTE_REF`, this allows us to test anything invoking the multiple subjobs at once. The job name remains "test pull request", so the whole job tree could probably be reorganized to make more sense. For now, we can think of it as "not exclusively".
- Skip Node.js v4 for node-gyp v4 (v0.10 and v0.12 were aready skipped).

In [nodegyp-test-commit](https://ci.nodejs.org/job/nodegyp-test-commit/):

- Updated to use https://github.com/npm/cli instead of https://github.com/npm/npm (apparently, all the old releases are there).

**Comment by joaocgreis** [comment]
CI is currently broken for master, PR to fix: https://github.com/nodejs/node-gyp/pull/1561

**Comment by joaocgreis** [comment]
Added v11.0.0 to the matrix. Also added v6.0.0 because that's the oldest we support for v4, so should be tested.

**Comment by joaocgreis** [comment]
Had to change to v6.2.1 because NVS was having issues with 6.0.0 - probably because the zip/7z packages are not available.

**Comment by refack** [comment]
> NVS was having issues with 6.0.0

But besides that it's a great tool for this task, right?

**Comment by joaocgreis** [comment]
Haven't reviewed it carefully but it looks great 👍
