### ISSUE TITLE
'utility' file not found

### ISSUE THREAD

**Issue by yerassyl94** [nodejs/node-gyp#1564]
Node Version: 
node 6.5.0
npm: 6.4.1

Platform: MacOS 10.14 Mojave
Compiler: Apple LLVM version 9.1.0 (clang-902.0.39.2)
Module: npm install

Mean.js project gives this message when run `npm install`

/Users/user/.node-gyp/6.5.0/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>

**Comment by yerassyl94** [comment]
Solved by changing MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.9 in 
Users/user/.node-gyp/6.5.0/include/node/common.gypi

**Comment by AlexVentura** [comment]
@yerassyl94 how exactly did you solve this? Where do you change that variable?

**Comment by refack** [comment]
> Solved by changing MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.9 in

Ohh you are both building with fairly old node versions...
Maybe post a PR to nodejs/node for the v6 branch?

**Comment by yerassyl94** [comment]
> @yerassyl94 how exactly did you solve this? Where do you change that variable?

<Users>/<user>/.node-gyp/6.5.0/include/node/common.gypi
find this file in your MacOS

**Comment by AlexVentura** [comment]
@yerassyl94 Thx I could fix this too!

**Comment by refack** [comment]
### FTR, possible workaround:
#### For users:
```sh
env CXXFLAGS="-mmacosx-version-min=10.9" npm install
```
#### For addon authors:
add this to your `bindings.gyp` (but as mentioned above test)
```py
  'xcode_settings': {
    'MACOSX_DEPLOYMENT_TARGET': '10.9',
  },
```

**Comment by alexbaumgertner** [comment]
Try 
```
CXXFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-mmacosx-version-min=10.9" npm i
```
https://stackoverflow.com/questions/52545166/node-6-node-gyp-rebuild-for-hiredis-fails-on-macos

It works for me, Mac OS 10.14.1 (18B75), node version 6.11.3 (legacy project)

**Comment by megharajsh** [comment]
> Solved by changing MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.9 in
> Users/user/.node-gyp/6.5.0/include/node/common.gypi

Thanks, This resolved the issue
