### ISSUE TITLE
error on build node-gyp on debian raspberry

### ISSUE THREAD

**Issue by platini76** [nodejs/node-gyp#1565]
I have a server on debian raspberry (virtual machine)

I am trying to install homebridge and I have npm installed

my npm-gyp is build on node 10.2.0 and I want to rebuild on 10.0.0
I have this error.. someone can help me?

```
root@raspberry:~# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/.nvm/versions/node/v10.0.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.nvm/versions/node/v10.0.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.0.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /root) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v10.0.0/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/root/.nvm/versions/node/v10.0.0/bin/node" "/root/.nvm/versions/node/v10.0.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /root
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

```

**Comment by platini76** [comment]
it is version 3.8.0 that is compatible to node 10.2.0?
is there a mode to install the correct version?


or is the file binding.gyp ?

**Comment by platini76** [comment]
after many error on installation module it ends like this:

In file included from /var/homebridge/.node-gyp/10.12.0/include/node/node.h:63:0,
                 from ../src/mdns.hpp:11,
                 from ../src/txt_record_buffer_to_object.cpp:1:
/var/homebridge/.node-gyp/10.12.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
/usr/bin/ld: impossibile trovare -ldns_sd
collect2: error: ld returned 1 exit status
dns_sd_bindings.target.mk:200: set di istruzioni per l'obiettivo "Release/obj.target/dns_sd_bindings.node" non riuscito
make: *** [Release/obj.target/dns_sd_bindings.node] Errore 1
make: uscita dalla directory "/usr/local/lib/node_modules/homebridge-dacp/node_modules/mdns/build"
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/local/bin/node" "/root/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-dacp/node_modules/mdns
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/homebridge/.npm/_logs/2018-10-12T18_02_16_862Z-debug.log

**Comment by bnoordhuis** [comment]
> /usr/bin/ld: impossibile trovare -ldns_sd

That's an issue with the module you're trying to install, dns_sd_bindings; not node-gyp.
