### ISSUE TITLE
Security Vulnerability: Join and relpath path traversal vulnerability

### ISSUE THREAD

**Issue by GeekArthur** [nodejs/node-gyp#1567]
When using os.join or os.repath, path traversal is possible. Path traversal allows an attacker inappropriate access to a file.

Issue Example:
```
def function():
    name = request.args.get('name')
    return send_file(os.path.relpath(os.getcwd(), name))
```

Issue Workaround:
Do not to rely upon user input when dealing with file system access. If such a scenario is unavoidable, make sure the file is in an expected directory and the application throws an error if it is not. Alternatively, check the file name being requested by using a map and an ID in the request.

```
def verify_path(basedir, path):
    return os.path.realpath(path).startswith(basedir)
	
def function():
	name = request.args.get('name')
	if (verify_path(os.getcwd(),name):
		return send_file(os.path.relpath(os.getcwd(), name))
	else:
		print("Throw an error")
```

**Comment by bnoordhuis** [comment]
Closing, not a vulnerability. Your bug report is simply not applicable. node-gyp is a build tool, there is no concept of untrusted input.
