### ISSUE TITLE
The target “/t:native_metrics” does not exist in the project

### ISSUE THREAD

**Issue by moco32** [nodejs/node-gyp#1575]
I am trying to run npm install but I am getting the following error:

node_modules\@newrelic\native-metrics\build\binding.sln.metaproj : error MSB4057: The target "/t:native_metrics" does not exist in the project.

I tried a few suggested solutions like: completely uninstalling nodejs (I also removed all the leftover folder in AppData), I tried downgrading node-gyp to an older version rather than the latest. 

I also uninstalled and installed Python2.7 but that didn't help. I removed and installed Windows Build Tools but nothing. I also removed all the npm, npm-cache and .node-gyp folder and that didn't do the trick. I am not getting the error when I run npm install on two other machines. Anyone have any suggestion before I do a clean install of my Windows?

* **Node Version**: `8.12.0` and `6.4.1`
* **Platform**: Windows 10
* **Compiler**: `msbuild`
* **Module**: new relic native metrics 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\Projects\> npm install

> @newrelic/native-metrics@3.1.1 install C:\Users\Projects\node_modules\@newrelic\native-metrics
> node ./lib/pre-build.js install native_metrics

> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean configure
> C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build -j 2 /t:native_metrics
C:\Users\Projects\node_modules\@newrelic\native-metrics\build\binding.sln.me
taproj : error MSB4057: The target "/t:native_metrics" does not exist in the project. [C:\Users\Proj
ects\node_modules\@newrelic\native-metrics\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "-j" "2" "/t:native_metrics"
gyp ERR! cwd C:\Users\Projects\node_modules\@newrelic\native-metrics
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Error: Failed to execute install: Error: Failed to install module: Error: Failed to execute C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build -j 2 /t:native_metrics: code 1; Error: Failed to download https://download.newrelic.com/nodejs_agent/builds/_newrelic_native_metrics-3_1_1-native_metrics-57-win32-x64.gz: code 404
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@3.1.1 (node_modules\@newrelic\native-metrics):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@3.1.1 install: `node ./lib/pre-build.js install native_metrics`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 6708 packages in 10.156s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

</details>

**Comment by bzoz** [comment]
This is an issue with the package you are trying to install, not node-gyp

**Comment by richardlau** [comment]
> 
> 
> This is an issue with the package you are trying to install, not node-gyp

More specifically, this is https://github.com/newrelic/node-native-metrics/pull/52 -- the addon is making an incorrect assumption about node-gyp and prepending `/t:` to the target name when it should not (node-gyp v3.8.0 already does this, so the package ends up with `/t:/t:native_metrics`).

**Comment by eboureau** [comment]
In the meantime, you can workaround this by using a git bash
```
mkdir /c/tmp/gyp-3.0.6
cd /c/tmp/gyp-3.0.6
npm install node-gyp@3.0.6
```
Then, in your project dir
```
npm_config_node_gyp=c:/tmp/gyp-3.0.6/node_modules/node-gyp/bin/node-gyp.js npm i
```

**Comment by moco32** [comment]
> In the meantime, you can workaround this by using a git bash
> 
> ```
> mkdir /c/tmp/gyp-3.0.6
> cd /c/tmp/gyp-3.0.6
> npm install node-gyp@3.0.6
> ```
> Then, in your project dir
> 
> ```
> npm_config_node_gyp=c:/tmp/gyp-3.0.6/node_modules/node-gyp/bin/node-gyp.js npm i
> ```

The last command doesn't seem to be working. It's not being recognized.

**Comment by eboureau** [comment]
Did you run the command in a git bash or windows command prompt ?
However, the fix has been publish in version [3.1.2](https://github.com/newrelic/node-native-metrics/blob/master/CHANGELOG.md) so you no longer need this hack.

**Comment by Seb33300** [comment]
I spend lot of time trying to install node-gyp 3.0.6 as indicate in the previous comment but this version does not exist.

After installing node-gyp 3.6.0, no more issue.

**Comment by IdanAdar** [comment]
I am using Alpine 3.9, which uses Node 10.14.
I am attempting to install @newrelic v5.5.0.

During the build, it fails on @newlic/new-metrics v3.1.2

Full log: https://pastebin.com/Xe4DTwqS

**Comment by richardlau** [comment]
> 
> 
> I am using Alpine 3.9, which uses Node 10.14.
> I am attempting to install @newrelic v5.5.0.
> 
> During the build, it fails on @newlic/new-metrics v3.1.2
> 
> Full log: https://pastebin.com/Xe4DTwqS

@IdanAdar Your issue is nothing to do with the issue discussed here. From the log:

```
> ursa@0.9.4 install /home/jenkins/workspace/Certificates_Manager_develop/node_modules/ursa
...
../src/ursaNative.cc:389:13: error: invalid use of incomplete type 'RSA' {aka 'struct rsa_st'}
     obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
             ^~
In file included from /home/jenkins/.node-gyp/10.14.2/include/node/openssl/crypto.h:31,
                 from /home/jenkins/.node-gyp/10.14.2/include/node/openssl/bio.h:20,
                 from /home/jenkins/.node-gyp/10.14.2/include/node/openssl/asn1.h:16,
                 from /home/jenkins/.node-gyp/10.14.2/include/node/openssl/rsa.h:16,
                 from ../src/ursaNative.h:13,
                 from ../src/ursaNative.cc:3:
```

This is https://github.com/JoshKaufman/ursa/issues/167, basically ursa is not compatible with Node.js 10 and requires a new version to be released: https://github.com/JoshKaufman/ursa/pull/182.
