### ISSUE TITLE
NPM ERR : get-cursor-position | node-gyp rebuild

### ISSUE THREAD

**Issue by CMonjo** [nodejs/node-gyp#1580]
Hello !
I'm trying to install a project on my computer but i've this error. I'm working on a Mac (OSX Mojave). I've friend with the same computer, same OS version and it's work for him. So i've unstall Node and NPM but issue still here after reinstall. How can i do ? Thank's !

* **Node Version**: 10.12.0
* **NPM Version**: 6.4.1
* **Platform**: OSX (Darwin)
* **Compiler**: 
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* **Module**: sudo npm install on project folder

sudo npm install
> get-cursor-position@1.0.3 install /Users/camille/Dev/viatransit/viatransit-API/node_modules/get-cursor-position
> node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/camille/Dev/viatransit/viatransit-API/node_modules/get-cursor-position/build'
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/camille/Dev/viatransit/viatransit-API/node_modules/get-cursor-position
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-cursor-position@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/camille/.npm/_logs/2018-10-25T07_02_39_216Z-debug.log

```
[...]
96 silly saveTree   │     ├── isarray@0.0.1
96 silly saveTree   │     └── string_decoder@0.10.31
96 silly saveTree   ├─┬ readable-stream@1.0.34
96 silly saveTree   │ ├── isarray@0.0.1
96 silly saveTree   │ └── string_decoder@0.10.31
96 silly saveTree   └── setimmediate@1.0.5
97 verbose stack Error: get-cursor-position@1.0.3 install: `node-gyp rebuild`
97 verbose stack Exit status 1
97 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
97 verbose stack     at EventEmitter.emit (events.js:182:13)
97 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
97 verbose stack     at ChildProcess.emit (events.js:182:13)
97 verbose stack     at maybeClose (internal/child_process.js:962:16)
97 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
98 verbose pkgid get-cursor-position@1.0.3
99 verbose cwd /Users/camille/Dev/viatransit/viatransit-API
100 verbose Darwin 18.0.0
101 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
102 verbose node v10.12.0
103 verbose npm  v6.4.1
104 error code ELIFECYCLE
105 error errno 1
106 error get-cursor-position@1.0.3 install: `node-gyp rebuild`
106 error Exit status 1
107 error Failed at the get-cursor-position@1.0.3 install script.
107 error This is probably not a problem with npm. There is likely additional logging output above.
108 verbose exit [ 1, true ]
```

**Comment by bnoordhuis** [comment]
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/camille/Dev/viatransit/viatransit-API/node_modules/get-cursor-position/build'

That's a permissions error. Check that all components are writable. You can rmdir build, node-gyp will recreate it.
