### ISSUE TITLE
 fatal error: 'utility' file not found

### ISSUE THREAD

**Issue by D-mawl** [nodejs/node-gyp#1583]
os: mac 10.14
node : 6.14.4
npm: 6.4.1
i did not install xcode;
i have tried change the MACOSX_DEPLOYMENT_TARGET to 10.9 as issue#23685, but did not work;
` ['OS=="mac"', {
        'defines': ['_DARWIN_USE_64_BIT_INODE=1'],
        'xcode_settings': {
          'ALWAYS_SEARCH_USER_PATHS': 'NO',
          'GCC_CW_ASM_SYNTAX': 'NO',                # No -fasm-blocks
          'GCC_DYNAMIC_NO_PIC': 'NO',               # No -mdynamic-no-pic
                                                    # (Equivalent to -fPIC)
          'GCC_ENABLE_CPP_EXCEPTIONS': 'NO',        # -fno-exceptions
          'GCC_ENABLE_CPP_RTTI': 'NO',              # -fno-rtti
          'GCC_ENABLE_PASCAL_STRINGS': 'NO',        # No -mpascal-strings
          'GCC_THREADSAFE_STATICS': 'NO',           # -fno-threadsafe-statics
          'PREBINDING': 'NO',                       # No -Wl,-prebind
          'MACOSX_DEPLOYMENT_TARGET': '10.9',       # -mmacosx-version-min=10.9
          'USE_HEADERMAP': 'NO',
          'OTHER_CFLAGS': [
            '-fno-strict-aliasing',
          ],
          'WARNING_CFLAGS': [
            '-Wall',
            '-Wendif-labels',
            '-W',
            '-Wno-unused-parameter',
          ],
        },`
there is also some warnings:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/darwin-x64-48_binding.node": HTTP error 404 Not Found

when i execute "npm install fis3-rift-packer -g", an error came out:
`gyp verb `which` failed Error: not found: python2`
`/Users/tt/.node-gyp/6.14.4/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>`

`../src/libsass/ast.hpp:1942:34: warning: expression with side effects will be evaluated despite
      being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
      if (length() > 0 && typeid(*(*this)[0]) == typeid(Type_Selector)`

`WARN invalid config loglevel="notice"
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/darwin-x64-48_binding.node": HTTP error 404 Not Found
yp info it worked if it ends with ok
gyp verb cli [ '/Users/mwl/.nvm/versions/node/v6.14.4/bin/node',
gyp verb cli   '/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@6.14.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:13:12)\n    at F (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:68:19)\n    at E (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:80:29)\n    at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/which/which.js:89:16\n    at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/index.js:42:5\n    at /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 6.14.4
gyp verb command install [ '6.14.4' ]
gyp verb install input version string "6.14.4"
gyp verb install installing version: 6.14.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.14.4
gyp verb build dir attempting to create "build" dir: /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mwl/.node-gyp/6.14.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mwl/.node-gyp/6.14.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/mwl/.node-gyp/6.14.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/mwl/.node-gyp/6.14.4
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.2.5"' -I/Users/mwl/.node-gyp/6.14.4/include/node -I/Users/mwl/.node-gyp/6.14.4/src -I/Users/mwl/.node-gyp/6.14.4/deps/openssl/config -I/Users/mwl/.node-gyp/6.14.4/deps/openssl/openssl/include -I/Users/mwl/.node-gyp/6.14.4/deps/uv/include -I/Users/mwl/.node-gyp/6.14.4/deps/zlib -I/Users/mwl/.node-gyp/6.14.4/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-threadsafe-statics -std=c++11 -stdlib=libc++ -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/ast.o ../src/libsass/ast.cpp
In file included from ../src/libsass/ast.cpp:1:
../src/libsass/ast.hpp:1942:34: warning: expression with side effects will be evaluated despite
      being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
      if (length() > 0 && typeid(*(*this)[0]) == typeid(Type_Selector))
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use
      the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:52:
In file included from /Users/mwl/.node-gyp/6.14.4/include/node/node.h:42:
/Users/mwl/.node-gyp/6.14.4/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/mwl/.nvm/versions/node/v6.14.4/bin/node" "/Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mwl/.nvm/versions/node/v6.14.4/lib/node_modules/fis3-rift-packer/node_modules/node-sass
gyp ERR! node -v v6.14.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.3.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by bnoordhuis** [comment]
Start by upgrading to the latest node-sass. v3.3.3 is over three years old now.

Since this is unlikely to be an issue with node-gyp, I'm closing this out.
