### ISSUE TITLE
Appending "false" to a non-list setting "CompileAsWinRT" for tool "ClCompile" is not allowed, previous value: true

### ISSUE THREAD

**Issue by karangoel16** [nodejs/node-gyp#1585]
* **Node Version**: v8.12.0
* **Platform**: 
* **Compiler**: 
* **Module**: Custom Node Module

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by refack** [comment]
Hello @karangoel16 and thank you for the report.
Cloud you provide the detailed output (npm error log), and your `binding.gyp`?

**Comment by karangoel16** [comment]
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "lib/hello.cpp" ,"lib/xyz.cpp"],
      "include_dirs": [
        "<!(node -e \"require('nan')\")"
      ],
      "conditions":[
        ['OS=="win"',{
          'link_settings': {
            'libraries': [
              'ncrypt.lib',
              'bcrypt.lib',
              'crypt32.lib'
            ],
          },
        "msbuild_settings": {
          "ClCompile": {
            "CompileAsManaged": "true",
            "ExceptionHandling": "Async",
          },
        }
        }]
      ]
    },
    {
     "target_name": "abc",
     "sources":[ "lib/abc.cpp"],
      "include_dirs": [
        "<!(node -e \"require('nan')\")"
      ],
      "conditions":[
        ['OS=="win"',{
          'link_settings': {
            'libraries': [
              'ncrypt.lib',
              'bcrypt.lib',
              'crypt32.lib'
            ],
          }
        }
        ]
      ]
    }
  ]
}

**Comment by refack** [comment]
@karangoel16 did you manage to solve this? Could you post how?
I might be helpful in the future for someone who stumbles on this issue.

**Comment by karangoel16** [comment]
Hi I am compiling the file using Visual studio now, binding.gyp isn't working, tried to work with /ZW flag but that isn't working too, looking for possible solutions, will keep you posted ones I have solution for the same.
