### ISSUE TITLE
not defined npm_config_node_gyp

### ISSUE THREAD

**Issue by mhavci** [nodejs/node-gyp#1587]
> ursa@0.9.4 install C:\workspace\project\node_modules\ursa
> node-gyp rebuild

C:\workspace\project\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\npm\npm-cache\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\workspace\project\node_modules\ursa\node C:\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN elemental@0.6.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN elemental@0.6.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-keystone@3.0.0 requires a peer of eslint@^3.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-keystone-react@1.0.0 requires a peer of eslint@^3.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-keystone-react@1.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-alt-text@2.0.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-day-picker@2.5.0 requires a peer of react@~0.13.x || ~0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-domify@0.2.6 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-images@0.5.6 requires a peer of react-dom@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-images@0.5.6 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@3.0.2 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scrolllock@1.0.9 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
npm WARN keystonecmsss@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 

 node -v v10.13.0
node-gyp -v v3.8.0

**Comment by SalahudinMalik** [comment]
having same issue from last two days.

**Comment by mhavci** [comment]
try it, worked on me.

https://github.com/nodejs/node-gyp/issues/762

**Comment by SalahudinMalik** [comment]
Thanks but I installed vs 2015 and set its environment variables and it worked for me.

**Comment by brunoarruda** [comment]
I'm having this issue trying to install [secp256k1](https://github.com/bitcoinjs/secp256k1-node).

They suggest to install dependencies with a command ```npm install --global windows-build-tools```. Well, I tried this. I tried to install all dependencies by myself, I tried #762, I tried also reinstalling after cleaning the node_modules folder. All attempts doesn't work, this is the log:

    562 silly install tiny-secp256k1@1.0.1
    563 info lifecycle tiny-secp256k1@1.0.1~install: tiny-secp256k1@1.0.1
    564 verbose lifecycle tiny-secp256k1@1.0.1~install: unsafe-perm in lifecycle true
    565 verbose lifecycle tiny-secp256k1@1.0.1~install: PATH: C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\me\AppData\Roaming\npm\node_modules\tiny-secp256k1\node_modules\.bin;C:\Users\me\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;D:\chromedriver2.43;D:\CUDA\v9.2\bin;D:\CUDA\v9.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\PDFtk\bin\;D:\Git\cmd;D:\nodejs\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\me\.windows-build-tools\python27\;C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\me\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\me\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;D:\chromedriver2.43;D:\CUDA\v9.2\bin;D:\CUDA\v9.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\PDFtk\bin\;D:\nodejs\;D:\Git\cmd;D:\Python\Python37\Scripts\;D:\Python\Python37\;D:\Python\Python37-32\Scripts\;D:\Python\Python37-32\;C:\Users\me\AppData\Local\Programs\Python\Launcher\;C:\Users\me\AppData\Local\Microsoft\WindowsApps;D:\heroku\bin;C:\Users\me\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\me\AppData\Local\GitHubDesktop\bin;C:\Users\me\AppData\Roaming\npm
    566 verbose lifecycle tiny-secp256k1@1.0.1~install: CWD: C:\Users\me\AppData\Roaming\npm\node_modules\tiny-secp256k1
    567 silly lifecycle tiny-secp256k1@1.0.1~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
    568 silly lifecycle tiny-secp256k1@1.0.1~install: Returned: code: 1  signal: null
    569 info lifecycle tiny-secp256k1@1.0.1~install: Failed to exec install script
    570 timing action:install Completed in 222ms
    571 verbose unlock done using C:\Users\me\AppData\Roaming\npm-cache\_locks\staging-729d22db0ca9e482.lock for C:\Users\me\AppData\Roaming\npm\node_modules\.staging
    572 timing stage:rollbackFailedOptional Completed in 254ms
    573 timing stage:runTopLevelLifecycles Completed in 2578ms
    574 verbose stack Error: tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
    574 verbose stack Exit status 1
    574 verbose stack     at EventEmitter.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
    574 verbose stack     at EventEmitter.emit (events.js:189:13)
    574 verbose stack     at ChildProcess.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
    574 verbose stack     at ChildProcess.emit (events.js:189:13)
    574 verbose stack     at maybeClose (internal/child_process.js:970:16)
    574 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    575 verbose pkgid tiny-secp256k1@1.0.1
    576 verbose cwd C:\Users\me
    577 verbose Windows_NT 10.0.17763
    578 verbose argv "D:\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tiny-secp256k1"
    579 verbose node v10.15.3
    580 verbose npm  v6.9.0
    581 error code ELIFECYCLE
    582 error errno 1
    583 error tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
    583 error Exit status 1
    584 error Failed at the tiny-secp256k1@1.0.1 install script.
    584 error This is probably not a problem with npm. There is likely additional logging output above.
    585 verbose exit [ 1, true ]

after running ```npm config set msvs_version 2015 --global``` and ```npm install npm@next -g```, calling node-gyp throws the error of this issue.

Even with ```npm config set node_gyp "node path\to\node-gyp.js"``` it doesnt' find node-gyp anymore... 
It's hard even to figure out what is the problem.

**Comment by rvagg** [comment]
sorry we haven't been able to provide an answer here, I'm going to close this and hope that newer versions of npm and node-gyp solve most of these problems

For folks arriving here via google, be careful with `npm_config_node_gyp`, it means you have `npm config set node_gyp` (which you can see with `npm config get`) pointing to an alternative version of node-gyp than the one npm ships with. If you have them mixed up you can end up with perverse situations and odd errors. Before reporting errors, try removing it entirely and using the default npm version, using `npm config delete node_gyp`, and also try upgrading your version of npm (`npm install npm@latest -g`).

**Comment by Prof-isaac** [comment]
you just need the right version of these 
Python 2.7.17
node v12.15.0
npm 6.13.4 or yarn 1.22.10 or both

**Comment by Prof-isaac** [comment]
> > ursa@0.9.4 install C:\workspace\project\node_modules\ursa
> > node-gyp rebuild
> 
> C:\workspace\project\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\npm\npm-cache\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "node C:\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> internal/modules/cjs/loader.js:582
> throw err;
> ^
> 
> Error: Cannot find module 'C:\workspace\project\node_modules\ursa\node C:\nvm\v10.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
> at Function.Module._load (internal/modules/cjs/loader.js:506:25)
> at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
> at startup (internal/bootstrap/node.js:285:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
> npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN elemental@0.6.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN elemental@0.6.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-config-keystone@3.0.0 requires a peer of eslint@^3.10.0 but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-config-keystone-react@1.0.0 requires a peer of eslint@^3.10.0 but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-config-keystone-react@1.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
> npm WARN react-alt-text@2.0.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-day-picker@2.5.0 requires a peer of react@~0.13.x || ~0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-domify@0.2.6 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-images@0.5.6 requires a peer of react-dom@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-images@0.5.6 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-router@3.0.2 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-scrolllock@1.0.9 requires a peer of react@^0.14 || ^15.0 but none is installed. You must install peer dependencies yourself.
> npm WARN keystonecmsss@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status
> 
> node -v v10.13.0
> node-gyp -v v3.8.0






you just need the right version of these
Python 2.7.17
node v12.15.0
npm 6.13.4 or yarn 1.22.10 or both

**Comment by IWRNTHAU** [comment]
ioj bukvty

**Comment by cclauss** [comment]
> node-gyp -v v3.8.0

Current release is v9.1.0 — https://github.com/nodejs/node-gyp/releases

Please upgrade https://github.com/nodejs/node-gyp/tree/main/docs#readme

> you just need the right version of these
Python 2.7.17

Nonsense.  Python 2 died 970 days ago on 1/1/2020.  It has had no security updates since then so legacy Python should no longer be trusted.
