### ISSUE TITLE
how to use cmake as build tool

### ISSUE THREAD

**Issue by kimown** [nodejs/node-gyp#1590]
It seems cmake is experimental feature: https://github.com/nodejs/node-gyp/blob/63e6bc7d5ca7d1a89d52f3033de7b4bb26c75957/gyp/pylib/gyp/generator/cmake.py#L7

do you have plan when release this feature?

**Comment by kimown** [comment]
@refack 
I see, thank you for the response.

**Comment by gengjiawen** [comment]
You can try: https://github.com/nodejs/node-gyp/issues/1668#issuecomment-515729542.
