### ISSUE TITLE
Build for Windows with a Wine Docker image

### ISSUE THREAD

**Issue by paul-roman** [nodejs/node-gyp#1593]
This is actually more of a question than a issue. I'm using Docker to build a Electron app, one build for Windows, one for Linux.
However, this app is using native Node addons. I was wondering if I could build a native addon for Windows with node-gyp inside a Docker container using wine?

* **Node Version**:  `10.2.1` for Node and `5.6.0` for npm
* **Platform**:  Docker using `electronuserland/builder:wine` image
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by rvagg** [comment]
I think the answer is "we don't know", but if you work out, report back or write it up somewhere, I'm sure it'll be fascinating and helpful for someone out there. Best of luck.

**Comment by erick-thompson** [comment]
@paul-roman I am looking at something similar. Were you able to get it working?
