### ISSUE TITLE
docs need clarification re binding.gyp

### ISSUE THREAD

**Issue by xthdraft** [nodejs/node-gyp#1595]
* **Node Version**: node -v10.12.0 and npm -v6.4.1
* **Platform**:  Windows 10
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

The instructions in the docs for building a native module, while clear, seem not to mention any case where multiple source files are entered in the "sources" field in binding.gyp.  As there are very few, if any, tutorials covering this scenario, it would be helpful if the node-gyp docs were updated to show how to build  a module where, say, two  C files existed in the sources field.

**Comment by richardlau** [comment]
At the very least we could link to https://nodejs.org/api/addons.html. For example, the two source files scenario is covered in https://nodejs.org/api/addons.html#addons_addon_examples.

Pull requests are welcome.

**Comment by xthdraft** [comment]
Thanks Richard,  particularly for that  second link.   Following it up, I
found 3 relevant examples in *nodejs/node-addon-examples*.   These are
6_object_wrap,  7_factory_wrap,  and 8_passing_wrapped.

Unfortunately, these examples are  extremely difficult to understand for
someone like me.   An ultra minimal example with clear explanations would
be of immense value.  The simple "hello world" examples repeated everywhere
are of course easy to follow.
