### ISSUE TITLE
MSB4148: The name of a property stored under the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" has zero length 

### ISSUE THREAD

**Issue by glaucia86** [nodejs/node-gyp#1598]
* **Node Version**: v8.12.0 
* **Npm**: 6.4.1
* **Platform**: Windows 10
* **Compiler**: Visual C++ compiler
* **Module**: node-usb | restify

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\Glaucia Lemos\Downloads\Downloads\Backup - Comp Glaucia\Palestras\Apresentação - Semana da Mulher - ChatBot\semana-meninas-mulheres-ciencia>npm install

> dtrace-provider@0.8.7 install C:\Users\Glaucia Lemos\Downloads\Downloads\Backup - Comp Glaucia\Palestras\Apresentação - Semana da Mulher - ChatBot\semana-meninas-mulheres-ciencia\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


C:\Users\Glaucia Lemos\Downloads\Downloads\Backup - Comp Glaucia\Palestras\Apresentação - Semana da Mulher - ChatBot\semana-meninas-mulheres-ciencia\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Users\Glaucia Lemos\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Glaucia Lemos\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Compilando os projetos desta solução um de cada vez. Para habilitar o build paralelo, adicione a opção "/m".
MSBUILD : Configuration error MSB4148: O nome de uma propriedade armazenada na chave do Registro "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" tem comprimento zero.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Glaucia Lemos\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Glaucia Lemos\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Glaucia Lemos\Downloads\Downloads\Backup - Comp Glaucia\Palestras\Apresentação - Semana da Mulher - ChatBot\semana-meninas-mulheres-ciencia\node_modules\dtrace-provider
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
added 176 packages from 339 contributors and audited 372 packages in 8.55s
found 0 vulnerabilities
```

</details>

Hi guys! So... I've been while trying to execute node-gyp on my Windows 10. but without success. I've tried everything. Even the suggestion of the @refack here #1144. But no success.
I even install the VS 2015 and VS 2017 as you already said here on the documentation, but failed.

This is the message that appears in my screen:

```
MSB4148: The name of a property stored under the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" has zero length. 
``` 

I would like ask your help about it. Once I have been trying to install some packages use node-gyp and I can't continue to develop my projects.
Anyone here already resolve this issue?

![screen shot 11-06-18 at 01 00 am](https://user-images.githubusercontent.com/1631477/48040698-28f4a880-e161-11e8-89a1-481cccf861bd.PNG)

![image](https://user-images.githubusercontent.com/1631477/48040727-53466600-e161-11e8-899c-03bee76e2e8e.png)

**Comment by bzoz** [comment]
After a quick search I've found this: https://blogs.msdn.microsoft.com/visualstudio/2010/02/26/my-visual-studio-2008-is-broken-after-uninstalling-net-framework-4-0/, maybe give it a try?

**Comment by glaucia86** [comment]
@bzoz I will try to make a uninstall here my VS 2017 and then I will return here if works! ;)

**Comment by glaucia86** [comment]
Doesn't worked it! :(

![image](https://user-images.githubusercontent.com/1631477/48071357-4c4f4000-e1c1-11e8-8bab-bb2d8548f48a.png)

**Comment by refack** [comment]
AFAICT this looks like a bug in the MSVS install... So maybe also report this issue at https://github.com/Microsoft/msbuild

As a workaround you could try importing this regfile https://gist.github.com/refack/363ee65cb3a9a9c5f59f1977cdbf5fc8

**Comment by glaucia86** [comment]
@refack I uninstall everything on my machine here.  I have done all the documentation procedures of the node-gyp and the error persists.

I've removed: VS 2017 and all subfolders. Everything.

![image](https://user-images.githubusercontent.com/1631477/48079258-27af9400-e1d2-11e8-9809-de5b62363f8a.png)


Now I don't know what can be... :(

**Comment by refack** [comment]
Well my first guess would be that it has something to do with your locale. You could try to search you registry for this value `MSBuildRuntimeVersion` for example. It might be in
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\VersõesDeFerramentas` ;)

**Comment by refack** [comment]
Another thing you can try is to run `node-gyp` in a `Developer Command Prompt for VS 2017` (cmd after running `VsDevCmd.bat`)

**Comment by glaucia86** [comment]
I will try here again and then I will report you! Thanks a lot again! :)

**Comment by glaucia86** [comment]
@refack  I formatted my computer. I installed the node-gyp, but at the time of knowing the version of it appears this error:

![image](https://user-images.githubusercontent.com/1631477/48113993-6ed66d00-e244-11e8-8cb4-1ebe5b52f136.png)

**Comment by glaucia86** [comment]
Going to close this issue once I formatted my computer and this error disappear.

**Comment by ErrorCode313** [comment]
I still have this issue, and I'm not willing to format my computer...
