### ISSUE TITLE
Problem to execute 'node-gyp configure' command inside on node-gyp package

### ISSUE THREAD

**Issue by glaucia86** [nodejs/node-gyp#1601]
* **Node Version**: 8.12. 0
* **Npm Version**:  6.4.1
* **Platform**: Windows 10
* **Compiler**: MSBuild
* **Module**: node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\WINDOWS\system32>npm install --global --production windows-build-tools

> windows-build-tools@5.0.0 postinstall C:\Users\glauc\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading vs_BuildTools.exe
[============================================>] 100.0% of 1.12 MB (1.12 MB/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\glauc\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.0.0
added 144 packages from 97 contributors in 15.947s

C:\WINDOWS\system32>npm install -g node-gyp
C:\Users\glauc\AppData\Roaming\npm\node-gyp -> C:\Users\glauc\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.8.0
added 97 packages from 67 contributors in 2.504s

C:\WINDOWS\system32>npm config set python python2.7

C:\WINDOWS\system32>npm config set msvs_version 2017

C:\WINDOWS\system32>npm config set python C:\Python27\python

C:\WINDOWS\system32>cd C:\Users\glauc\AppData\Roaming\npm\node_modules\node-gyp\

C:\Users\glauc\AppData\Roaming\npm\node_modules\node-gyp>code .

C:\Users\glauc\AppData\Roaming\npm\node_modules\node-gyp>node-gyp configure

C:\Users\glauc\AppData\Roaming\npm\node_modules\node-gyp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" configure )
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\node_modules\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

</details>

This is the binding.gyp file that I am trying to execute inside on node-gyp package:

```
{
    "targets": [{
    "target_name": "binding",
    "sources": [ "build/Release/binding.node" ]
    }]
}
```

This is pretty strange, once before, with the same binding.gyp information I could execute within the node-gyp package.

Any idea what can be @refack ?

![image](https://user-images.githubusercontent.com/1631477/48173556-6127f280-e2eb-11e8-92d1-0d2b5c1428b1.png)

**Comment by bnoordhuis** [comment]
> "sources": [ "build/Release/binding.node" ]

That should be a list of source files, not the name of the resulting .node file.

**Comment by glaucia86** [comment]
Então me explique algo. Como é que antes - na versão anterior conseguia executar esse código sem problemas?
E outro ponto: porque que quando dou node-gyp --version, dá erro? @bnoordhuis

**Comment by glaucia86** [comment]
> So explain something to me. How come before - in the previous version I could run this code without problems?
> And another point: why when I give node-gyp --version, gives error?



> > "sources": [ "build/Release/binding.node" ]
> 
> That should be a list of source files, not the name of the resulting .node file.

So explain something to me. How come before - in the previous version I could run this code without problems?
And another point: why when I give node-gyp --version, gives error?

**Comment by glaucia86** [comment]
@bnoordhuis Hi again. I followed this steps and I got resolved my problem:

# 1 - Uninstall Node.js

# 2 - Delete the folder **npm** on AppData: (manually)
```
C:\Users\<folder-name>\AppData\Roaming\npm directory was not deleted.
```
# 3 - Re-install the latest Node.Js [https://nodejs.org/en/]

# 4 - Open prompt command windows as administrator and execute:

```
> npm install npm@latest -g
```

# 5 - And finally install node-gyp package globally (as administrator):

```
> npm install -g node-gyp
```

After make all these steps finally resolved it! 

Thanks all @refack and @bnoordhuis

**Comment by JobizoIndia** [comment]
> @bnoordhuis Hi again. I followed this steps and I got resolved my problem:
> 
> 1º - Uninstall Node.js
> 
> 2º - Delete the folder **npm** on AppData: (manually)
> 
> ```
> C:\Users\<folder-name>\AppData\Roaming\npm directory was not deleted.
> ```
> 
> 3º - Re-install the latest Node.Js [https://nodejs.org/en/](https://nodejs.org/en)
> 
> 4º - Open prompt command windows as administrator and execute:
> 
> ```
> > npm install npm@latest -g
> ```
> 
> 5º - And finally install node-gyp package globally (as administrator):
> 
> ```
> > npm install -g node-gyp
> ```
> 
> After to do all these steps finally resolved it!
> 
> Thanks all @refack and @bnoordhuis

Thank you
