### ISSUE TITLE
I can't install from npm install and I don't know fixe bug !

### ISSUE THREAD

**Issue by Fabiyo-90** [nodejs/node-gyp#1602]
- I work on windows 10 
- node v10.10.0
- npm v6.4.1
and my error is 

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyserverpac proxyserverpac:80

? Next, which style of NativeScript project would you like to use: Vue.js

> node-sass@4.9.4 install D:\project\mobile\likelemba\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/win32-x64-64_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyserverpac proxyserverpac:80

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> nativescript-dev-webpack@0.17.0 postinstall D:\project\mobile\likelemba\node_modules\nativescript-dev-webpack
> node postinstall.js

Creating file: D:\project\mobile\likelemba\webpack.config.js

NativeScript Webpack plugin was successfully added.
You can now bundle your project by passing --bundle flag to NativeScript CLI commands:
    - tns build android --bundle
    - tns build ios --bundle
    - tns run android --bundle
    - tns run ios --bundle
You can also pass the "--env.uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.

> node-sass@4.9.4 postinstall D:\project\mobile\likelemba\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\project\mobile\likelemba\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\project\\mobile\\likelemba\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\project\mobile\likelemba\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\project\mobile\likelemba\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\project\mobile\likelemba\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\project\mobile\likelemba\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\project\mobile\likelemba\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\project\mobile\likelemba\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\project\mobile\likelemba\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\project\\mobile\\likelemba\\node_modules\\which\\which.js:13:12)\n    at F (D:\\project\\mobile\\likelemba\\node_modules\\which\\which.js:68:19)\n    at E (D:\\project\\mobile\\likelemba\\node_modules\\which\\which.js:80:29)\n    at D:\\project\\mobile\\likelemba\\node_modules\\which\\which.js:89:16\n    at D:\\project\\mobile\\likelemba\\node_modules\\isexe\\index.js:42:5\n    at D:\\project\\mobile\\likelemba\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.10.0
gyp verb command install [ '10.10.0' ]
gyp verb install input version string "10.10.0"
gyp verb install installing version: 10.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.10.0
gyp verb build dir attempting to create "build" dir: D:\project\mobile\likelemba\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? D:\project\mobile\likelemba\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\project\mobile\likelemba\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\project\mobile\likelemba\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: D:\project\mobile\likelemba\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'D:\\project\\mobile\\likelemba\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2017',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\project\\mobile\\likelemba\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\project\\mobile\\likelemba\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.10.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\project\\mobile\\likelemba\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Fabrice IYONGO\\.node-gyp\\10.10.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\project\\mobile\\likelemba\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\project\\mobile\\likelemba\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "D:\project\mobile\likelemba\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\project\mobile\likelemba\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\mobile\\likelemba\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\project\mobile\likelemba\node_modules\node-sass
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN awesome-typescript-loader@5.2.1 requires a peer of typescript@^2.7 || ^3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fabrice IYONGO\AppData\Roaming\npm-cache\_logs\2018-11-09T10_57_55_710Z-debug.log
Command npm.cmd install failed with exit code 1

**Comment by Fabiyo-90** [comment]
If I use "npm install -g nativescript" or "npm install -g @vue/cli @vue/cli-init" is working well but if I use "tns create" I have a bug !

**Comment by ramen-mukherjee** [comment]
same issue

**Comment by AlexRiina** [comment]
```
gyp verb which failed Error: not found: python2
```

looks like the relevant part. node-gyp checks to make sure there is a python2 version installed to a lot of python code inside. There have been a few pull requests to start changing the dependency to python3 which may be more available https://github.com/nodejs/node-gyp/issues/1337

**Comment by bzoz** [comment]
@Fabiyo-90  do you have MS Build Tools or VS Community Edition installed? (you can get MS Build Tools from https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)

**Comment by cclauss** [comment]
> gyp verb which failed Error: not found: python2

What happens when you:
* echo $PYTHON
* python --version
* python2 --version  # legacy Python
* python3 --version  # Python

Node-gyp currently ___requires___ legacy Python.  See #1337

**Comment by krisavi** [comment]
I had something similar with other project. 

In Windows the python will only have python in the path and it will be the latest installed python. In case there is Python 3 installed with python launcher then comes the option to use py -2 and py -3 

As python 2.7 will not have executable of python2, then it will fail always on windows. It seems weird that there is assumption made that everyone are using Unix based systems where python2 and python3 is achieved through symlinking to correct binary. 

The initial poster is saying they use Windows 10, that makes commands like 
echo $PYTHON
python --version
python2 --version # legacy Python
python3 --version # Python
fairly pointless.
`echo $PYTHON` echos "$PYTHON" In windows it should be echo %PYTHON% if variable name is PYTHON, however it is not like that in windows.
`python --version` gives the version of first occurrence of python in the path.
`python2 --version` gives command not found
`python3 --version` gives command not found

Gyp should be made then compatible with windows.
First it tries `python --version`, if that returns python 2.7, all good, continue using `python`, if not, then try `py -2 --version`, if that works, then use `py -2` as python executable. If both of them fail, then ask user to install python 2.7. Python launcher has also the possibility to list installed version with -0 or --list command line argument.

**Comment by cclauss** [comment]
My bad.  You are of course correct.  I have never been a Windows user so I misspoke.  Apologies.  Thanks for the clarifications.

**Comment by alex-piccione** [comment]
I have the same prroblem with node-sass 4.9.4. 
On Windows 10 64bit I have only Python3 (it is probably 10 years that I use only Python 3).
Why this issue is closed, what is the solution? 
All the related Bugs/Issues (make GYP compatible with Python 3) seem to be CLosed.

**Comment by cclauss** [comment]
Don't wait... Just use https://github.com/refack/GYP today.

100 days until Python 2 end of life.

**Comment by AlexByte** [comment]
just update module `gulp-sass` to the latest version, add `sass` module to the package.json and write 

    const sass = require('gulp-sass')(require('sass'));

to the gulpfile.js to get rid off node-gyp.
