### ISSUE TITLE
npm install failed on 'node-gyp' with UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by malindapw** [nodejs/node-gyp#1608]
Getting error when running 'npm install' (logs attached) 

* **Node Version**: node v10.13.0 , npm - 6.4.1
* **Platform**: Windows 10
* **Compiler**: Windows
* **Module**: npm install

<details><summary>Verbose output (from npm or node-gyp):</summary>
C:\Users\malinda
\Project\ui-auto.qa>npm install

> snappy@5.0.5 install C:\Users\malinda
\Project\ui-auto.qa\node_modules\snappy
> node-gyp rebuild

C:\Users\malinda
\Project\ui-auto.qa\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'uri-js'
gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:636:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:20:18)
gyp ERR! stack     at Object.<anonymous> (C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\ajv\lib\compile\resolve.js:3:11)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:688:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:598:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malinda
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\malinda
\Project\ui-auto.qa\node_modules\snappy
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-
[2018-11-22T21_41_52_722Z-debug.log](https://github.com/nodejs/node-gyp/files/2609320/2018-11-22T21_41_52_722Z-debug.log)
[2018-11-22T21_41_52_722Z-debug.log](https://github.com/nodejs/node-gyp/files/2609322/2018-11-22T21_41_52_722Z-debug.log)

gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

> sleep@5.1.1 install C:\Users\malinda
\Project\ui-auto.qa\node_modules\sleep
> node-gyp rebuild

C:\Users\malinda
\Project\ui-auto.qa\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'uri-js'
gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:636:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:20:18)
gyp ERR! stack     at Object.<anonymous> (C:\Users\malinda
\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\ajv\lib\compile\resolve.js:3:11)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:688:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:598:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malinda
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\malinda
\Project\ui-auto.qa\node_modules\sleep
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN bat@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules\snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 7

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\malinda
\AppData\Roaming\npm-cache\_logs\2018-11-22T21_41_52_722Z-debug.log

</details>

Please note: I have updated 'node-gyp' to latest as well but still getting the same issue

**Comment by rvagg** [comment]
` gyp ERR! stack Error: Cannot find module 'uri-js'`
looks like a local problem, not a problem with node-gyp, sorry
closing due to staleness
