### ISSUE TITLE
node-gyp faliled to build

### ISSUE THREAD

**Issue by ArtemSkok** [nodejs/node-gyp#1610]
I am trying to install npm packages whitch use c++ and python libraries. I have python and Visual Studio 2017 Enterprise installed. Building of c++ modules fails and I don't have any idea what's wrong.

In console: 

PS D:\projects\planttron\planttron.API> npm install

> fs-ext@0.5.0 install D:\projects\planttron\planttron.API\node_modules\fs-ext
> node-gyp configure build

D:\projects\planttron\planttron.API\node_modules\fs-ext>if not defined npm_config_node_gyp (node "D:\programs\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "D:\programs\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
  fs-ext.cc
  win_delay_load_hook.cc
d:\projects\planttron\planttron.api\node_modules\nan\nan_maybe_43_inl.h(88): error C2039: ForceSet: не является членом "v8::Object" (компилируется исх
одный файл ..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(3349): note:  см. объявление "v8::Object" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan_implementation_12_inl.h(345): warning C4996: 'v8::StringObject::New': объявлен deprecate (ком
пилируется исходный файл ..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(5241): note:  см. объявление "v8::StringObject::New" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(816): warning C4996: 'node::MakeCallback': объявлен deprecate (компилируется исходный файл
..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\node.h(171): note:  см. объявление "node::MakeCallback" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(830): warning C4996: 'node::MakeCallback': объявлен deprecate (компилируется исходный файл
..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\node.h(164): note:  см. объявление "node::MakeCallback" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(844): warning C4996: 'node::MakeCallback': объявлен deprecate (компилируется исходный файл
..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\node.h(157): note:  см. объявление "node::MakeCallback" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(890): warning C4996: 'v8::Value::ToString': объявлен deprecate (компилируется исходный файл
 ..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(10248): note:  см. объявление "v8::Value::ToString" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(900): warning C4996: 'v8::String::WriteUtf8': объявлен deprecate (компилируется исходный фа
йл ..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2753): note:  см. объявление "v8::String::WriteUtf8" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\nan\nan.h(1457): warning C4996: 'node::MakeCallback': объявлен deprecate (компилируется исходный файл
 ..\fs-ext.cc) [D:\projects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\node.h(171): note:  см. объявление "node::MakeCallback" (компилируется исходный файл ..\fs-ext.cc)
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(108): warning C4996: 'Nan::NanErrnoException': объявлен deprecate [D:\projects\plant
tron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  d:\projects\planttron\planttron.api\node_modules\nan\nan.h(862): note:  см. объявление "Nan::NanErrnoException"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(195): error C3861: fcntl: идентификатор не найден [D:\projects\planttron\planttron.A
PI\node_modules\fs-ext\build\fs-ext.vcxproj]
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(281): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(282): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(297): warning C4996: 'Nan::NanErrnoException': объявлен deprecate [D:\projects\plant
tron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  d:\projects\planttron\planttron.api\node_modules\nan\nan.h(862): note:  см. объявление "Nan::NanErrnoException"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(332): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(334): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(335): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(339): warning C4996: 'Nan::NanErrnoException': объявлен deprecate [D:\projects\plant
tron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  d:\projects\planttron\planttron.api\node_modules\nan\nan.h(862): note:  см. объявление "Nan::NanErrnoException"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(374): error C3861: fcntl: идентификатор не найден [D:\projects\planttron\planttron.A
PI\node_modules\fs-ext\build\fs-ext.vcxproj]
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(369): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(370): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(371): warning C4996: 'v8::Value::Int32Value': объявлен deprecate [D:\projects\plantt
ron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2572): note:  см. объявление "v8::Value::Int32Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(375): warning C4996: 'Nan::NanErrnoException': объявлен deprecate [D:\projects\plant
tron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  d:\projects\planttron\planttron.api\node_modules\nan\nan.h(862): note:  см. объявление "Nan::NanErrnoException"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(423): warning C4996: 'v8::String::Utf8Value::Utf8Value': объявлен deprecate [D:\proj
ects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2991): note:  см. объявление "v8::String::Utf8Value::Utf8Value"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(424): warning C4996: 'v8::Value::IntegerValue': объявлен deprecate [D:\projects\plan
ttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2570): note:  см. объявление "v8::Value::IntegerValue"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(425): warning C4996: 'v8::Value::IntegerValue': объявлен deprecate [D:\projects\plan
ttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2570): note:  см. объявление "v8::Value::IntegerValue"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(433): warning C4996: 'Nan::NanErrnoException': объявлен deprecate [D:\projects\plant
tron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  d:\projects\planttron\planttron.api\node_modules\nan\nan.h(862): note:  см. объявление "Nan::NanErrnoException"
d:\projects\planttron\planttron.api\node_modules\fs-ext\fs-ext.cc(462): warning C4996: 'v8::String::Utf8Value::Utf8Value': объявлен deprecate [D:\proj
ects\planttron\planttron.API\node_modules\fs-ext\build\fs-ext.vcxproj]
  c:\users\art\.node-gyp\11.2.0\include\node\v8.h(2991): note:  см. объявление "v8::String::Utf8Value::Utf8Value"
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\programs\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\programs\\nodejs\\node.exe" "D:\\programs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\projects\planttron\planttron.API\node_modules\fs-ext
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by bzoz** [comment]
Could you provide `npm install --verbose`? This also looks like a problem with `fs-ext`, you should report this in that package issue tracker
