### ISSUE TITLE
error in installing composer rest server

### ISSUE THREAD

**Issue by SirisetyManeela** [nodejs/node-gyp#1622]
> grpc@1.10.1 install C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.14.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.14.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
Traceback (most recent call last):
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2025, in GenerateOutput
    version=msvs_version)
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 340, in Write
    f.close()
  File "C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 393, in close
    os.rename(self.tmp_path, filename)
WindowsError: [Error 183] Cannot create a file when that file already exists
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malli\\AppData\\Roaming\\nvm\\v10.14.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown" "--python=C:\\Users\\malli\\.windows-build-tools\\python27\\python.exe"
gyp ERR! cwd C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --python=C:\Users\malli\.windows-build-tools\python27\python.exe' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --python=C:\Users\malli\.windows-build-tools\python27\python.exe' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\malli\AppData\Roaming\npm-cache\_logs\2018-12-05T04_59_20_992Z-debug.log

**Comment by bzoz** [comment]
Could you try running `npm install --verbose` ?

**Comment by SirisetyManeela** [comment]
npm install composer-rest-server -g
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm ERR! Unexpected end of JSON input while parsing near '...","uuid":"^3.0.1"},"d'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\malli\AppData\Roaming\npm-cache\_logs\2018-12-06T13_07_14_440Z-debug.log

got this error now

**Comment by SirisetyManeela** [comment]
got the same error when i tried again

WindowsError: [Error 183] Cannot create a file when that file already exists
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malli\\AppData\\Roaming\\nvm\\v10.14.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown" "--python=c:\\Python\\27\\python.exe"
gyp ERR! cwd C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --python=c:\Python\27\python.exe' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\malli\\AppData\\Roaming\\npm\\node_modules\\composer-rest-server\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\malli\AppData\Roaming\nvm\v10.14.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\malli\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --python=c:\Python\27\python.exe' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\malli\AppData\Roaming\npm-cache\_logs\2018-12-06T13_33_49_027Z-debug.log

**Comment by itzpc** [comment]
@SirisetyManeela  This is because you are using a different version of node. 
For composer to work you should use node **8.x.x**  versions

#1622 closed

**Comment by tuanhth95** [comment]
@pcakhilnadh, i've try to run composer rest server with node 8.9 but, it seem to the composer is written in node 10.3 or newer, i see this error:

node/v8.9.0/lib/node_modules/composer-rest-server/node_modules/undici/index.js:27
} catch {
        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/composer-rest-server/node_modules/swagger-client/lib/helpers/fetch-ponyfill-undici.node.js:6:15)

i search it on google, it call "Optional catch binding" and appear in node 10.3, its my opinion, how do you think about that

**Comment by cclauss** [comment]
https://www.npmjs.com/package/composer-rest-server --> https://github.com/hyperledger/composer#readme
