### ISSUE TITLE
node-gyp fails to rebuild with NodeJS 10 on Mac OS Mojave

### ISSUE THREAD

**Issue by ExiaSR** [nodejs/node-gyp#1623]
* **Node Version**: 10.14.1
* **Platform**: Mac OS 10.14.1
* **Compiler**: clang, Apple LLVM version 10.0.0 (clang-1000.11.45.5)
* **Module**: node-gyp

Nodejs is installed with `nvm`, I ran `yarn install`, below is the output

https://gist.github.com/ExiaSR/b3f560cbf7b5fb07561f1121f853fce4

I have tried
- Remove `node_modules` and `$HOME/.node-gyp`
- XCode is properly installed, including CLI.
- Clean up yarn cache

**Comment by richardlau** [comment]
```
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
```
Can you check what version of `nan` is being used? Ref https://github.com/nodejs/nan/issues/763.

**Comment by ExiaSR** [comment]
@richardlau 

nan@`2.7.0`

**Comment by yinnette** [comment]
add --unsafe-perm to everything!
