### ISSUE TITLE
NODE PERMISSIONS after Mojave Upgrade 

### ISSUE THREAD

**Issue by yinnette** [nodejs/node-gyp#1624]
I kept getting permissions errors. Mojave has issues with permissions in general. From people getting locked out of their laptop to not having to write access to folders and files. If you are using node add "sudo" to the beginning of install commands and "--unsafe-perm" to the end of those commands. This should fix issues. But what is causing this?

**Comment by yinnette** [comment]
Mojave has issues with permissions in general. From people getting locked out of their laptop to not having to write access to folders and files. If you are using node add "sudo" to the beginning of install commands and "--unsafe-perm" to the end of those commands. This should fix issues.

**Comment by rvagg** [comment]
Sorry there haven't been any responses here, closing due to staleness and I hope you've figured out what you need. Personally when I'm using macOS I make sure my user account owns the important stuff under /usr/local so I rarely have to use `sudo`.
