### ISSUE TITLE
better-sqlite-pool failed to install | NPM JavaScript

### ISSUE THREAD

**Issue by ButterCreations** [nodejs/node-gyp#1626]
* **Node Version**: Node: v10.13.0 | NPM: v6.4.1
* **Platform**: Windows
* **Compiler**:  idk what this is
* **Module**:  better-sqlite-pool

<details><summary>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2018-12-08T02_54_53_483Z-debug.log</summary>
</details>
I was trying to install the better-sqlite-pool but got the error shown above. Any help would be awesome!
Thanks.
P.S. I'm working on a Discord.js bot soooo :p

**Comment by bzoz** [comment]
As it says: `This is probably not a problem with npm.`. You should report this in better-sqlite-pool issue tracker.

**Comment by ButterCreations** [comment]
Fixed. But thank you for letting me know!
