### ISSUE TITLE
How to link a static library when creating a shared_lib using gyp?

### ISSUE THREAD

**Issue by nehasharan** [nodejs/node-gyp#1637]
I am using below code in my gyp file but it is throwing linking error. This works fine when I change the library type to static _library. Do I need to link with shared library only or I am missing something?

'targets': [
{
'target_name': 'abc',
'type': 'shared_library',
'conditions': [],
'dependencies': [],
'libraries':[
'mylib.a'
],
'mac_framework_dirs' : [
],
'all_dependent_settings': {},
},

**Comment by rvagg** [comment]
Sorry we haven't been able to provide an answer @nehasharan. My suggestion is to have a look around at the many examples of addons that are doing things like this already.
