### ISSUE TITLE
"node-gyp --python " doesnt work as per instructions

### ISSUE THREAD

**Issue by SamKacer** [nodejs/node-gyp#1638]
* **Node Version**:node:v10.15.0 npm 6.5.0
* **Platform**: OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17134 N/A Build 17134
System Type:               x64-based PC

I tried to set up node-gyp as per the instructions for windows. My default python is 3.6, so I want to set it to my copy of 2.7.

running the `node-gyp --python` command does not seem to be recognised by node-gyp. any thoughts on what I am doing wrong? I tried putting quotes (both single and double), doubling the backslashes, but in each case I just get the message on usage as if node-gyp doesnt recognise the command.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
c:\> node-gyp --python C:\python27

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.8.0  C:\Users\Sam\AppData\Roaming\npm\node_modules\node-gyp
node@10.15.0
```

</details>

**Comment by Penkie** [comment]
I have the exact same problem

**Comment by bzoz** [comment]
`--python` is an "option". Running `node-gyp build --python=...` etc. should work.
