### ISSUE TITLE
Pass parameter to node-gyp for different C library

### ISSUE THREAD

**Issue by arroyc** [nodejs/node-gyp#1644]
Container 1:
* **Node Version**:  ```
root@dce09bd4ca6c:/# node -v
v10.14.1
root@dce09bd4ca6c:/# npm -v
6.4.1
```
* **Platform**: ```
root@dce09bd4ca6c:/# uname -a
Linux dce09bd4ca6c 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux* 
```**Compiler**: 
```
root@dce09bd4ca6c:
```
/# cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
```

* **Module**: node-sass

container 2:
* **Node Version**: node v8.11.4, npm v5.6.0
* **Platform**: `Linux 78f30054eb2c 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux`
* **Compiler**: 
```
 # apk info
musl
busybox
alpine-baselayout
alpine-keys
libressl2.5-libcrypto
libressl2.5-libssl
libressl2.5-libtls
ssl_client
zlib
apk-tools
scanelf
musl-utils
libc-utils
libgcc
libstdc++
libc6-compat
ca-certificates
libssh2
libcurl
expat
pcre
git
```

* **Module**: node-sass

details:

* **log**:
```
ERROR in ./src/styles/styles.scss
    Module build failed: Error: Missing binding /tests/sound/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
    Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

    Found bindings for the following environments:
      - Linux 64-bit with Node.js 8.x
```

    This usually happens because your environment has changed since running `npm install`.`
Hey all, I'm new to nodejs and node-gyp world. I have a scenario where I need to build machine/container (buildpack-deps:stable) and runtime machine/container (alpine linux) configuration is different. nodejs has native modules, so when I'm trying to use the binary generated by build machine I'm getting failure in run machine (while doing npm start) which is obvious. My question is how should I pass parameter to node-gyp so that it can generate binary as per target os configuration. I checked your repo (I may have missed or overlooked) but haven't seen any parameter that can be passed to node-gyp for different Linux distro.
Note: I'm not interested doing "npm rebuild" or anything as such on runtime containers
Can anyone suggest/help me on that?

**Comment by arroyc** [comment]
unfortunately no one is responding …. is there anything missing in the issue that I listed?

**Comment by rvagg** [comment]
There is `--target` but I don't think that's what you're after. The problem here I'm guessing is that you're compiling in Debian but running in Alpine so you're hitting the musl libc problem (i.e. Debian uses glibc, Alpine uses musl, a compatibility nightmare). The best solution is to be building in a musl environment (cross compiling for musl is a pain in the backside and I'd avoid trying to do it if I were you tbh). Make a special build container with Alpine, put build tools in it (make, g++) and build your addons in there and then ship them into your trimmed-down Alpine container.

**Comment by ejose19** [comment]
@rvagg What about for just downloading a precompiled version? It would be great if we can set override `glibc` with a flag, as we will be downloading binaries there won't be any build issue.

**Comment by cclauss** [comment]
Node-sass is deprecated.  Would the recommend upgrade to Dart-sass be a possibility?

**Comment by ejose19** [comment]
@cclauss Actually I commented here due the title: `Pass parameter to node-gyp for different C library`, I'm not even using `sass`, just want the possibility to download the binaries for other platform/c library.

Also, I noticed that now binaries are called `$package.node` instead of `$package-$arch.node`, so we can't have multiple arch binaries as downloading new ones will overwrite current one, may I ask why was that approach preferred?
