### ISSUE TITLE
npm install sha3@1.2.0

### ISSUE THREAD

**Issue by pragmaticadam** [nodejs/node-gyp#1649]
Hi

when I run 

npm install -g sha3@1.2.0

I've get 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/home/adam/.nvm/versions/node/v11.6.0/bin/node" "/home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/adam/.nvm/versions/node/v11.6.0/lib/node_modules/sha3
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adam/.npm/_logs/2019-01-18T20_06_51_122Z-debug.log

I have hard dependency and connot change to 

sha3@2.0.0 

I'm running it on **Ubuntu 18.04.1 LTS** 

node is 11.6.0

i know fix for windows (npm i -g build-essentials), but here it is **not applicable** 

I've installer gcc as instructed in 

https://github.com/nodejs/node-gyp

my phyton is 2.7

can be runned by 

python 
and
python2.7

**Comment by kivutar** [comment]
I'm getting this with sha3@1.2.2 too

**Comment by pragmaticadam** [comment]
> Can you try [sha3@1.2.1](https://github.com/phusion/node-sha3/releases)? It looks like it contains a fix for Node.js 10.x: [phusion/node-sha3#32](https://github.com/phusion/node-sha3/issues/32) and [phusion/node-sha3#33](https://github.com/phusion/node-sha3/pull/33)

No I can't it is hard dependency of some other library

**Comment by rvagg** [comment]
I think this might be stale so I'm going to close it. I suspect that this due to an incompatibility with the version of sha3 that you're building and the version of Node you're using. If that's a hard indirect dependency then you're either going to need to get the author of the package that's depending on sha3 to update, or downgrade your version of Node (probably to 8).
