### ISSUE TITLE
How to install the python3-backed fork on Windows

### ISSUE THREAD

**Issue by vpontin** [nodejs/node-gyp#1656]
Hi! Code layman here trying to run some packages who depends on gyp.

Just read on [this issue](https://github.com/versatica/mediasoup/issues/207#issuecomment-456607911) node-gyp got support for python3.

BUT in the repository README it still says `v3.x.x is not supported`.

How can i use the py3-powered node-gyp in my machine (Windows 10 x64)? I'm running Node 11.8.0 here.

Thanks in advance!

**Comment by bzoz** [comment]
Python 3 is not supported, if you read following messages it clearly states that those ports do not work. 

This is an active issue in Node community, but requires a lot of work to be done. For now, you have to use Python 2.

**Comment by vpontin** [comment]
Ok thanks
