### ISSUE TITLE
Trying to execute npm install but getting following error

### ISSUE THREAD

**Issue by ankitchawrai** [nodejs/node-gyp#1658]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious>npm install
npm WARN deprecated babel-preset-es2015@6.24.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env t
o update!
npm WARN deprecated nodemailer@3.1.5: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated scmp@1.0.2: scmp v2 uses improved core crypto comparison since Node v6.6.0

> node-sass@4.5.0 install C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\which\\which.js:13:12)\n    at F (C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\which\\which.js:68:19)\n    at E (C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\which\\which.js:80:29)\n    at C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\which\\which.js:89:16\n    at
C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\isexe\\index.js:42:5\n    at C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files (x86)\Python36-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python36-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\stuff\\A CURRENT LEARNING\\[Wes Bos] - Learn Node (2017)\\Learn Node\\Learn-Node-master\\dang-thats-delicious\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\stuff\A CURRENT LEARNING\[Wes Bos] - Learn Node (2017)\Learn Node\Learn-Node-master\dang-thats-delicious\node_modules\node-sass
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankit Chawrai\AppData\Roaming\npm-cache\_logs\2019-02-02T09_16_38_975Z-debug.log

**Comment by bzoz** [comment]
Looks like you are using Python 3. Only Python 2 is supported.
