### ISSUE TITLE
Is there any way to use C++17 on MSBuild?

### ISSUE THREAD

**Issue by Akarinnnnn** [nodejs/node-gyp#1662]
* **Node Version**:10.15.0 
* **Platform**:Windows 10 x64 
* **Compiler**:MSBuild ,toolset v150
* **Module**:my SVLauncherDLL 

<details><summary>Verbose output (from npm or node-gyp):</summary>
  
  
e:\visual studio项目\dsted\source\cpp-addon\svlaunchdll_jswrap.cc(135): error C7525: 内联变量至少需要 "/std:c++17" (编译源文件 ..\cpp-
addon\svlaunchdll_jswrap.cc) [E:\Visual Studio项目\DSTed\Source\build\SVLaunchDLL.vcxproj]

</details>

I need C++17, seriously.

[cpp-addon.zip](https://github.com/nodejs/node-gyp/files/2841669/cpp-addon.zip)

**Comment by refack** [comment]
Add the following to your binding.gyp:
```python
  'msvs_settings': {
    'VCCLCompilerTool': {
      'AdditionalOptions': [ '-std:c++17', ],
    },
  },
```

**Comment by Akarinnnnn** [comment]
Failed  
``
Traceback (most recent call last):
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "E:\NPM_PREFIX\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 251, in LoadOneBuildFile
    None)
  File "binding.gyp", line 23
    'msvs-settings':
                  ^
SyntaxError: invalid syntax``


[binding.gyp.txt](https://github.com/nodejs/node-gyp/files/2841992/binding.gyp.txt)

**Comment by refack** [comment]
replace `[` with `{` for `'msvs_settings'` and `'VCCLCompilerTool'`
[binding.gyp.txt](https://github.com/nodejs/node-gyp/files/2842197/binding.gyp.txt)

**Comment by Akarinnnnn** [comment]
<details><summary>Verbose output (from npm or node-gyp):</summary>
Traceback (most recent call last):
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 425, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1293, in ProcessVariablesAndConditionsInDict
    build_file, key)
  File "E:\NPM_PREFIX\node_modules\prebuild\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1303, in ProcessVariablesAndConditionsInDict
    ' for ' + key)
TypeError: Unknown type set for AdditionalOptions while trying to load binding.gyp
</details>


[binding.gyp.txt](https://github.com/nodejs/node-gyp/files/2844786/binding.gyp.txt)

i had changed binding.gyp as you said, but it does not work

**Comment by rvagg** [comment]
please try and use Refael's exact syntax:

```
			'msvs-settings':
			{
				'VCCLCompilerTool':
				{
					'AdditionalOptions':
						[
						'-std:c++17',
						]
				}
			}
```

note the placement of `{`' and `[`'s

**Comment by AtiqGauri** [comment]
@rvagg still not working

**Comment by aminya** [comment]
This is a full working example for anyone who also has this problem:

```py
{
  "targets": [
    {
      "target_name": "proj",
      "sources": [ "src/proj.cc"],
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions"],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ],
  "target_defaults": {
    "cflags_cc": ["-std=c++17"],
    "conditions": [
      ['OS=="mac"', {
          "xcode_settings": {
            "CLANG_CXX_LIBRARY": "libc++",
            "CLANG_CXX_LANGUAGE_STANDARD":"c++17",
          }
      }],
      ['OS=="win"', {
        "msvs_settings": {
          "VCCLCompilerTool": {
            "AdditionalOptions": [ "-std:c++17", ],
          },
        },
      }]
    ]
  }
}

```

**Comment by mceIdo** [comment]
The solutions above didn't work for me - the only way I could get it to work  was using 
```
"msbuild_settings": {
    "ClCompile": {
        "LanguageStandard": "stdcpp17"
    }
}
```
It thows off some warnings, but it configures the project as it should and compiles

**Comment by Akarinnnnn** [comment]
> The solutions above didn't work for me - the only way I could get it to work was using
> 
> ```
> "msbuild_settings": {
>     "ClCompile": {
>         "LanguageStandard": "stdcpp17"
>     }
> }
> ```
> 
> It thows off some warnings, but it configures the project as it should and compiles

Yes. `ClCompile` MSBuild item controls how compiler treats source file

**Comment by aminya** [comment]
> The solutions above didn't work for me

That's strange. None of the given solutions sets the standard in the sln file for the analysis. But it works for the build.

**Comment by Akarinnnnn** [comment]
> > The solutions above didn't work for me
> 
> That's strange. None of the given solutions sets the standard in the sln file for the analysis. But it works for the build.

see .vcxproj file?

**Comment by AtiqGauri** [comment]
If anyone need solution irrespective of node-gyp use can use cmake...
It easily handle these kind of things. Here is a example for you: https://www.github.com/AtiqGauri/Patternscape/tree/master/Patternscape_Native_Addon%2FCMakeLists.txt

**Comment by aminya** [comment]
> > > The solutions above didn't work for me
> > 
> > 
> > That's strange. None of the given solutions sets the standard in the sln file for the analysis. But it works for the build.
> 
> see .vcxproj file?

Node-gyp does should be able to do this automatically, but it does not. Cmake easily does it by using
```cmake
target_compile_features(project_options INTERFACE cxx_std_17)
```

**Comment by ToadKing** [comment]
Ran into this issue myself. Setting it through `"msbuild_settings"` worked but I think doing it that way messes up the node.exe hooking stuff since the compiled module would not load in electron. It also changes some other flags as well since the module no longer built as a static binary.

@refack's original suggestion worked for me. That said, the `"VCCLCompilerTool"` option should probably be updated to allow setting `"LanguageStandard"` directly instead of adding it through an additional command line option.

**Comment by bladeRunner404** [comment]
> Add the following to your binding.gyp:
> 
> ```python
>   'msvs_settings': {
>     'VCCLCompilerTool': {
>       'AdditionalOptions': [ '-std:c++17', ],
>     },
>   },
> ```

nice, it works!!

**Comment by DanielCaspers** [comment]
For those coming here trying to get C++ 20 working with node addons relying on either Node directly or a derivative (e.g. Electron), don't forget that on Windows you will need to specify ```/Zc:__cplusplus```. It took a while for me to discover this sharp windows specific edge...
https://stackoverflow.com/questions/63057156/language-supported-in-visual-studio-for-c-cplusplus-is-showing-as-c98/63057345#63057345

**Comment by Psychlist1972** [comment]
> ```
>          "msvs_settings": {
>             "VCCLCompilerTool": {
>               "AdditionalOptions": [
>                 "/std:c++17"
>               ]
>             }
>           },
> ```

Thank you for this. In my case, I was trying to sort out how to compile a projection that used the older C++/CX which isn't c++20 compatible, and that did it.

```cpp
    "msvs_settings": {
      "VCCLCompilerTool": {
        "AdditionalOptions": ["/ZW", "-std:c++17"],
        "DisableSpecificWarnings": [4609],
      }
    },
```

I was really banging my head against the wall trying to figure out where the C++20 requirement was coming from when it was in the generated vcproj file. None of the other options worked with Visual Studio 2022 and its MS Build version.

**Comment by Psychlist1972** [comment]
In my case, the -std:c++17 didn't work with VS 2022 and MS Build. I had to use the CLCompile version mentioned above. 

I was banging my head up against the wall trying to find out how to override the C++20 that node-gyp was putting into the vcxprj but never could locate the source.

This is all because NodeRT uses C++ CX to create the projections, and that is not compatible with C++ 20.

```json
    "msbuild_settings":{
        "ClCompile":{
            "LanguageStandard": "stdcpp17",
            "AdditionalOptions": "/ZW",
            "AdditionalUsingDirectories": [
              "%ProgramFiles(x86)%/Microsoft Visual Studio 14.0/VC/lib/store/references",
              "%ProgramFiles%/Microsoft Visual Studio 14.0/VC/lib/store/references",
              "%ProgramFiles(x86)%/Windows Kits/10/UnionMetadata/10.0.20348.0",
              "$(VCToolsInstallDir)/lib/x86/store/references",
              "../../",
            ]

        }
    }
```

I still have this in the binding.gyp, but it is overridden by the msbuild settings above

```json
    "msvs_settings": {
      "VCCLCompilerTool": {
        "AdditionalOptions": ["/ZW", "-std:c++17"],
        "DisableSpecificWarnings": [4609],
      }
    },
```

**Comment by Psychlist1972** [comment]
> For those coming here trying to get C++ 20 working with node addons relying on either Node directly or a derivative (e.g. Electron), don't forget that on Windows you will need to specify `/Zc:__cplusplus`. It took a while for me to discover this sharp windows specific edge... https://stackoverflow.com/questions/63057156/language-supported-in-visual-studio-for-c-cplusplus-is-showing-as-c98/63057345#63057345

In my case, node-gyp was adding both that and the std:c++20 to the project file by default, with no obvious way to override.

**Comment by BFjacky** [comment]
> This is a full working example for anyone who also has this problem:
> 
> ```python
> {
>   "targets": [
>     {
>       "target_name": "proj",
>       "sources": [ "src/proj.cc" ],
>       "include_dirs": [
>         "<!@(node -p \"require('node-addon-api').include\")"
>       ],
>       'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
>       "cflags": [ "-fno-exceptions" ],
>       "cflags_cc": [ "-fno-exceptions", "-std=c++17" ],
>       "conditions": [
>         ['OS=="mac"', {
>             "xcode_settings": {
>               'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
>               "CLANG_CXX_LIBRARY": "libc++",
>               "CLANG_CXX_LANGUAGE_STANDARD":"c++17",
>               'MACOSX_DEPLOYMENT_TARGET': '10.14'
>             }
>         }],
>         ['OS=="win"', {
>           "msvs_settings": {
>             "VCCLCompilerTool": {
>               "AdditionalOptions": [ "-std:c++17", ],
>             },
>           },
>         }]
>       ]
>     }
>   ]
> }
> ```

Worked with this config !!
