### ISSUE TITLE
When will 4.0 be released on npmjs.com?

### ISSUE THREAD

**Issue by reFX-Mike** [nodejs/node-gyp#1665]
Right now we can't build any native modules that work with Electron 4, because they require the delayed windows hook, which is enabled only with node-gyp 4.0. We don't want to fork and modify each and every dependency so we can enable it locally. Is there a good reason not to release node-gyp 4?

**Comment by bnoordhuis** [comment]
@nodejs/node-gyp Thoughts? I'd be okay with releasing v4.0, we have enough interesting changes to merit a release.

**Comment by richardlau** [comment]
No objections. There was a vague plan last summer (https://github.com/nodejs/node-gyp/issues/1519) but I think enough has landed to warrant a release.

**Comment by bnoordhuis** [comment]
#1670 should land before v4.x is released. Any other obsoletisms that ought to be scrapped?

**Comment by reFX-Mike** [comment]
Can we please get this done? Is there a problem merging #1670 and then releasing 4.0?

**Comment by reFX-Mike** [comment]
This issue (and other problems with the Javascript/Node ecosystem) convinced us that using Electron/Node/Javascript for serious applications is a non-starter and we abandoned our project in favor of a native implementation that is done in 10% of the time and with total control and zero dependencies. The binary size for the rewritten tool is 2.2 MB, and that is statically linked and with all necessary assets (icons etc.) embedded.

Electron is a huge mistake. Trying to use a browser for everything is simply ineffective and uses too many resources.
