### ISSUE TITLE
"-std=gnu++1y" overrides my own flags

### ISSUE THREAD

**Issue by kobalicek** [nodejs/node-gyp#1673]
* **Node Version**: node 11.10.0 / npm 6.7.0
* **Node-Gyp**: 3.8.0
* **Platform**: Linux 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-11-02) x86_64 GNU/Linux

Node-gyp overrides "-std=c++17" by "-std=gnu++1y".

I specify "-std=c++17" in my cflags_cc like to following:

```
"cflags_cc": ["-std=c++17"]
```

However, the compilation fails because the flag is overridden by flags I haven't specified. This is a relevant part from `mylib.target.mk` file:

```
CFLAGS_CC_Release := \
	-std=c++17 \
	-fvisibility=hidden \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++1y
```

Not sure how I can workaround this. I think node-gyp should either put its own "-std" flag at the beginning or recognize such flag in cflags_cc and update it.

**Comment by rvagg** [comment]
sorry we weren't able to supply an answer here, did you end up figuring it out?
you can override default gyp options that are forced on you by node and node-gyp by negating with `!`, e.g. `"!cflags_cc": ...`, that can usually help with these kinds of things. Although I can't tell you off the top of my head which option is foisting `-std=gnu++1y` on you.

**Comment by raptor9g** [comment]
Your cflags_cc are ignored on mac due to this block starting line 1227 of the [make.py file](https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/generator/make.py#L1217).

```
if self.flavor == 'mac':
        cflags = self.xcode_settings.GetCflags(configname)
        cflags_c = self.xcode_settings.GetCflagsC(configname)
        cflags_cc = self.xcode_settings.GetCflagsCC(configname)
        cflags_objc = self.xcode_settings.GetCflagsObjC(configname)
        cflags_objcc = self.xcode_settings.GetCflagsObjCC(configname)
```
If you make this change your -std=c++17 will be applied:
```
if self.flavor == 'mac':
         cflags = self.xcode_settings.GetCflags(configname)
-        cflags_c = self.xcode_settings.GetCflagsC(configname)
-        cflags_cc = self.xcode_settings.GetCflagsCC(configname)
+        cflags_c = config.get('cflags_c') or self.xcode_settings.GetCflagsC(configname)
+        cflags_cc = config.get('cflags_cc') or self.xcode_settings.GetCflagsCC(configname)
         cflags_objc = self.xcode_settings.GetCflagsObjC(configname)
         cflags_objcc = self.xcode_settings.GetCflagsObjCC(configname)
```
I do not know enough about why it is setup this way to put in a pull?  Maybe one of the maintainers might know?
