### ISSUE TITLE
Unable to use custom made macOS Framework

### ISSUE THREAD

**Issue by Aerrus** [nodejs/node-gyp#1676]
Writing an addon, it needs to use a custom made mac framework. In one of my `.mm` files I import it as any other framework would via `#import <fwname/fwname.h>`. However, when it gets to that line, it crashes saying `fwname/fwname.h file not found` `make failed with exit code: 2`.

I can't just keep the dependent framework in the global directory (which fixes the issue), I needed to define a custom path within my project directory for it to look at for portability.

```
module/
    binding.gyp
    otherstuff(package.json,index...)
    customfws/
        fwname.Framework
    cppsrc/
        stuff.mm(and more)
```

I will show my binding.gyp file below, it doesn't complain about not being able to find the framework, and doing `node-gyp configure -- -f xcode` then opening it up in Xcode confirms that the Framework Search Path setting is pointing to the right directory.

I hope I'm heading in the right direction with this question, but do I need any other flags to make sure the objective-c files look in the proper directories for the framework?

```
{
  "targets": [
    {
      "target_name": "myproj",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ 
        "cppsrc/wrapper.cc"
      ],
      "conditions": [
        ["OS=='mac'", {
          "xcode_settings": {
            "FRAMEWORK_SEARCH_PATHS": "$(SRCROOT)/**"
          },
          "link_settings": {
            "libraries": [
              "customfws/fwname.framework"
            ]
          },
          "sources": [
            "cppsrc/stuff.mm"
          ]
        }]
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ]
    }
  ]
}

```

Did see Issue #682 , but having the exact same format is throwing a `multiple build files` error.

**Comment by edin-m** [comment]
Wild guess. Try this:

```
	"include_dirs":
		[
			"<path>/<library>.framework -F<path>"
                 ]
```

Specify a parameter `-F` (like for the lib) inside the include dir path.

**Comment by rvagg** [comment]
I'm going to close this due to age and make the assumption that nobody here has anything else to add to it. Feel free to open a new issue with error messages and more specific questions, even example code and config files would be great.
