### ISSUE TITLE
node-gyp with Windows 8 and Visual Studio 2012

### ISSUE THREAD

**Issue by KevinBurton** [nodejs/node-gyp#168]
Is there a way that i can configure or rebuild node-gyp to use VS 2012 and the associated SDK? This is the only tool that I have that uses the two year old VS 2010 so to install this suite, its patches, the SDK that is for this compiler, and the patches for the SDK has become troublesome. Right now I am on Windows 8 with VS 2012 and I cannot install the 7.1 SDK because it says it will not install a file that already exists. All in all this is alot of headache to install all of these tools just for node-gyp. Any ideas?

**Comment by panuhorsmalahti** [comment]
node-gyp was broken for me when I removed VS2012 (I had VS2013) installed. --msvs_version=2013 fixed the issue, but a proper fix was setting the GYP_MSVS_VERSION=2013 environment variable.

**Comment by benjaminmbrown** [comment]
I can confirm @jellydonut's solution works:

npm install gulp-sass --python=C:\tools\python27\python.exe --msvs_version=2013

Works. My setup is also:
Windows 8
VS 2013

**Comment by dalanmao** [comment]
I have the same issue, but I resolve this step by step:
download the module source code 
cd the module dir
node-gyp configure
use the vs2012 to open the vs project and updating the vs project file in the build directory
node-gyp  build 
that works ,but not the idea way , use option --msvs_version=2012 not work for me.

**Comment by dalanmao** [comment]
I have tried the npm option  --msvs_version=2012 , It works, thanks.

here are my pc configuration
windows 8 pro x64, vs2012 (full)
npm -v
1.4.28
node-gyp -v
v1.0.2

**Comment by halt-hammerzeit** [comment]
I was getting 
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Upgrade Solution...". [G:\work\cinema\node_modules\engine.io\node_modules\bufferut
il\build\bufferutil.vcxproj]
```

I had to update Node.js'es internal `node-gyp`:

```
(open console as an administrator)
cd "C:\Program Files\nodejs\node_modules\npm"
npm install node-gyp
```

**Comment by merlynee** [comment]
I've been stuck here for a whole day,downloaded and instaled erverything.It doesn't seem to work. however，I run 'npm update',and god finally smiled at me

**Comment by merlynee** [comment]
crap,it worked for one minute

**Comment by msholly** [comment]
I had a similar issue, and the NPM command for windows-build-tools (from Option 1 in the docs) didn't work for me. 

I had to get the installer for Visual Studio 2015, and install the C++ tools manually. 

`Option 2: Install Visual Studio 2015 (or modify an existing installation) and select Common Tools for Visual C++ during setup. This also works with the free Community and Express for Desktop editions.`

Hope this helps anyone stumbling onto this problem.
