### ISSUE TITLE
error installing integer

### ISSUE THREAD

**Issue by PottingHelps** [nodejs/node-gyp#1681]
* **Node Version**:  `v11.10.0` and `6.7.0`
* **Platform**: Windows 10
* **Module**: 

I am attempting to install integer and I get this error every time I rune "npm i integer"

```
S C:\Users\will_\OneDrive\Desktop\bot-test> npm i integer

> integer@2.1.0 install C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer
> node-gyp rebuild


C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:427:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/next_tick.js:76:17)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN bot-test@1.0.0 No repository field.
npm WARN bot-test@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\will_\AppData\Roaming\npm-cache\_logs\2019-02-28T07_21_17_701Z-debug.log
```

**Comment by bzoz** [comment]
Could you provide output of `npm i integer --verbose`?

**Comment by PottingHelps** [comment]
`PS C:\Users\will_\OneDrive\Desktop\bot-test> npm i integer --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   'integer',
npm verb cli   '--verbose' ]
npm info using npm@6.7.0
npm info using node@v11.10.0
npm verb npm-session 48377105ab9a314e
npm http fetch GET 304 https://registry.npmjs.org/integer 738ms (from cache)
npm timing stage:loadCurrentTree Completed in 1490ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 239ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 228ms
npm timing stage:loadIdealTree Completed in 553ms
npm timing stage:generateActionsToTake Completed in 35ms
npm verb correctMkdir C:\Users\will_\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\will_\AppData\Roaming\npm-cache\_locks\staging-6f1911185b03fc54.lock for C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\.staging
npm timing action:extract Completed in 58ms
npm timing action:finalize Completed in 6ms
npm timing action:refresh-package-json Completed in 13ms
npm info lifecycle integer@2.1.0~preinstall: integer@2.1.0
npm timing action:preinstall Completed in 3ms
npm info linkStuff integer@2.1.0
npm timing action:build Completed in 2ms
npm info lifecycle integer@2.1.0~install: integer@2.1.0

> integer@2.1.0 install C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer
> node-gyp rebuild


C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\will_\.windows-build-tools\python27\Python.exe" in the PATH
gyp verb `which` succeeded C:\Users\will_\.windows-build-tools\python27\Python.exe C:\Users\will_\.windows-build-tools\python27\Python.exe
gyp verb check python version `C:\Users\will_\.windows-build-tools\python27\Python.exe -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 11.10.0
gyp verb command install [ '11.10.0' ]
gyp verb install input version string "11.10.0"
gyp verb install installing version: 11.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 11.10.0
gyp verb build dir attempting to create "build" dir: C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\build
gyp verb build dir "build" dir needed to be created? C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\will_\.windows-build-tools\python27\Python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\will_\\OneDrive\\Desktop\\bot-test\\node_modules\\integer\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\will_\\.node-gyp\\11.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\will_\\.node-gyp\\11.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\will_\\.node-gyp\\11.10.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\will_\\OneDrive\\Desktop\\bot-test\\node_modules\\integer',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\will_\\OneDrive\\Desktop\\bot-test\\node_modules\\integer\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\will_\.node-gyp\11.10.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:427:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/next_tick.js:76:17)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm verb lifecycle integer@2.1.0~install: unsafe-perm in lifecycle true
npm verb lifecycle integer@2.1.0~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer\node_modules\.bin;C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\will_\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\will_\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\will_\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\will_\AppData\Local\Microsoft\WindowsApps;C:\Users\will_\AppData\Local\atom\bin;C:\Users\will_\AppData\Roaming\npm
npm verb lifecycle integer@2.1.0~install: CWD: C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\integer
npm timing audit submit Completed in 508ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 508ms
npm timing audit body Completed in 0ms
npm info lifecycle integer@2.1.0~install: Failed to exec install script
npm timing action:install Completed in 3866ms
npm verb unlock done using C:\Users\will_\AppData\Roaming\npm-cache\_locks\staging-6f1911185b03fc54.lock for C:\Users\will_\OneDrive\Desktop\bot-test\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 14ms
npm timing stage:runTopLevelLifecycles Completed in 6170ms
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN bot-test@1.0.0 No repository field.
npm WARN bot-test@1.0.0 license should be a valid SPDX license expression

npm verb stack Error: integer@2.1.0 install: `node-gyp rebuild`
npm verb stack Exit status 7
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:197:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:197:13)
npm verb stack     at maybeClose (internal/child_process.js:984:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm verb pkgid integer@2.1.0
npm verb cwd C:\Users\will_\OneDrive\Desktop\bot-test
npm verb Windows_NT 10.0.17134
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "integer" "--verbose"
npm verb node v11.10.0
npm verb npm  v6.7.0
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 7, true ]
npm timing npm Completed in 7367ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\will_\AppData\Roaming\npm-cache\_logs\2019-02-28T10_29_23_731Z-debug.log
PS C:\Users\will_\OneDrive\Desktop\bot-test>`

**Comment by bzoz** [comment]
node-gyp tries to spawn detected compiler with `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe`, but the file is not there

Could you test if this file is there? Could you try reinstalling MSBuild?

**Comment by PottingHelps** [comment]
The path ends at `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools` for me i dont have `
MSBuild\15.0\Bin\MSBuild.exe`

**Comment by bzoz** [comment]
@refack could this be some issue with vswhere finding msbuild?

**Comment by rvagg** [comment]
any updates on this @PottingHelps @bzoz @refack? can I close this?
