### ISSUE TITLE
Specify what to install in MSVS

### ISSUE THREAD

**Issue by davalapar** [nodejs/node-gyp#1684]
Windows install step is bit vague, it might help to specify the following selections (to avoid issues like https://github.com/nodejs/node-gyp/issues/1144):

- MSBuild Tools
- Visual C++ Build Tools core features
- Windows 8.1 SDK
- Windows 10 SDK (10.0.x.x)

**Comment by rvagg** [comment]
@bzoz @joaocgreis is there something that should be done with this? That list is more than we have on the README and seems excessive, is it an accurate reflection and therefore should we update the README?

**Comment by gounaman** [comment]
I ran the install no problem.  But I have no idea what actual values to put in this example code
var db = require("odbc")()
	, cn = "DRIVER={FreeTDS};SERVER=host;UID=user;PWD=password;DATABASE=sandbox"
	;
Thx for developing this. I am trying to have JS connect to SQLite using an already installed OBDC driver.  How should I reference this driver? I would really appreciate a simple example that specifically works in the Windows env.  Including specific example directories.  Thanks again!
