### ISSUE TITLE
Why no support Python3

### ISSUE THREAD

**Issue by abersheeran** [nodejs/node-gyp#1687]
Python2 has nine months left to live, so why not move to Python3?
If you don't use Python3, please don't use Python. Can't replace Python with JavaScript?

**Comment by AberSheeran** [comment]
By the way, FUCK YOUR node-gyp！I had to install a Python2 to use it in WSL.

**Comment by Ryanhui** [comment]
use python3, please.

**Comment by LincePotiguara** [comment]
So, this February 2013 issue #193 say that the node staff is aware of the problem [and trying to work on it](https://github.com/nodejs/TSC/issues/642). And the gyp staff are also aware as [this 2009 issue shows](https://bugs.chromium.org/p/gyp/issues/detail?id=36). 
There are some build systems trying to mitigate this like [cmake-js](https://github.com/cmake-js/cmake-js).

**Comment by raphadko** [comment]
+1 for Python3

**Comment by einarpersson** [comment]
+1

**Comment by bnoordhuis** [comment]
In the works, see other open issues and pull requests.

**Comment by ngocdaothanh** [comment]
Hello, is there any progress yet?

**Comment by cclauss** [comment]
Yes.

**Comment by skewty** [comment]
> python: accept Python 3 conditionally (João Reis) #1815

Shouldn't this be re-opened until a release is made with unconditional python3 support?

Is requiring `NODE_GYP_PYTHON3` not a breaking change?

**Comment by actuallymentor** [comment]
> Yes.

Is there any (code) thing I/we can do to support?

This has been an issue for a long time now (not referencing this issue #1687 but the build issue).

**Comment by cclauss** [comment]
It would be ___great___ if you could create a markdown file explaining how to experiment with Python 3.  I believe that those instructions would give others more confidence to try it out an provide feedback and pull requests.

**Comment by actuallymentor** [comment]
> It would be great if you could create a markdown file explaining how to experiment with Python 3

What exactly do you mean? A migration guide for Py2 to Py3 or the logistics of managing python versions when developing?

**Comment by cclauss** [comment]
A __Experimenting with Python 3.md__ file for...

As a __software developer__ want to __build and run GYP on Python 3__ so that I can __be confident about what works and so that I can submit pull requests and open issues where I see bugs__.

**Comment by actuallymentor** [comment]
Are you not just referring to a python 2 -> 3 migration guide? Which are in
the python docs here: https://docs.python.org/3/howto/pyporting.html

**Comment by cclauss** [comment]
node-gyp v5.0.4 landed in nodejs/node-gyp#1893 so we no longer need the markdown file.

**Comment by Wegazz** [comment]
+1 for Python3

**Comment by rvagg** [comment]
Please don't comment or +1 this issue. We consider it closed. Python 3 is supported in the latest versions. 5.0.5 and 6.0.0 are out and have solid Python 3 support. If you don't have those versions then please upgrade. The latest npm has one of them so upgrade npm if you need to.
If you have a Python 3 bug to report please submit a new issue or pull request.
