### ISSUE TITLE
node-gyp build command shows error [gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ] make: Entering directory /root/nodejs-nan/build' CXX(target) Release/obj.target/mimscds/mimscds.o cc1plus: error: unrecognized command line option "-std=gnu++1y" make: *** [Release/obj.target/mimscds/mimscds.o] Error 1 make: Leaving directory /root/nodejs-nan/build']

### ISSUE THREAD

**Issue by AmarishRai** [nodejs/node-gyp#1690]
Hi Geeks,
I am facing the below error, could you please advice how can I fix it.

[root@INCARNUS_SERVER nodejs-nan]# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory /root/nodejs-nan/build' CXX(target) Release/obj.target/mimscds/mimscds.o cc1plus: error: unrecognized command line option "-std=gnu++1y" make: *** [Release/obj.target/mimscds/mimscds.o] Error 1 make: Leaving directory /root/nodejs-nan/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/root/n/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:189:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-642.13.1.el6.x86_64
gyp ERR! command "/root/n/bin/node" "/root/n/bin/node-gyp" "build"
gyp ERR! cwd /root/nodejs-nan
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by danubevictoria** [comment]
Hey what's your gcc version? Something I had to do was install gcc to be 4.9.2. 

```
sudo yum install centos-release-scl -y
sudo yum install devtoolset-3-toolchain -y
scl enable devtoolset-3 bash
```

**Comment by AmarishRai** [comment]
Hi,
Thank you for help,
My gee version is 4.8.5, and i am getting the below error:

[root@localhost nodejs-nan]# node-gyp build

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/Desktop/nodejs-nan/build'
  CXX(target) Release/obj.target/mimscds/node-fasttrack.o
../node-fasttrack.cc: In static member function ‘static void
FastTrack::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../node-fasttrack.cc:57:59: error: no matching function for call to
‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [0])’
     info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                           ^
../node-fasttrack.cc:57:59: note: candidates are:
In file included from /root/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:53,
                 from ../node-fasttrack.h:4,
                 from ../node-fasttrack.cc:1:
/root/.node-gyp/10.15.3/include/node/v8.h:3993:44: note:
v8::MaybeLocal<v8::Object>
v8::Function::NewInstance(v8::Local<v8::Context>, int,
v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/root/.node-gyp/10.15.3/include/node/v8.h:3993:44: note:   candidate
expects 3 arguments, 2 provided
/root/.node-gyp/10.15.3/include/node/v8.h:3996:44: note:
v8::MaybeLocal<v8::Object>
v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/root/.node-gyp/10.15.3/include/node/v8.h:3996:44: note:   candidate
expects 1 argument, 2 provided
../node-fasttrack.cc: In static member function ‘static void
FastTrack::RequestXml(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../node-fasttrack.cc:64:66: warning:
‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated
(declared at /root/.node-gyp/10.15.3/include/node/v8.h:2891): Use Isolate
version [-Wdeprecated-declarations]
     std::string reqXml(*v8::String::Utf8Value(info[0]->ToString()));
                                                                  ^
../node-fasttrack.cc: In static member function ‘static void
FastTrack::Open(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../node-fasttrack.cc:77:66: warning:
‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated
(declared at /root/.node-gyp/10.15.3/include/node/v8.h:2891): Use Isolate
version [-Wdeprecated-declarations]
     std::string param1(*v8::String::Utf8Value(info[0]->ToString()));
                                                                  ^
../node-fasttrack.cc:78:66: warning:
‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated
(declared at /root/.node-gyp/10.15.3/include/node/v8.h:2891): Use Isolate
version [-Wdeprecated-declarations]
     std::string param2(*v8::String::Utf8Value(info[1]->ToString()));
                                                                  ^
make: *** [Release/obj.target/mimscds/node-fasttrack.o] Error 1
make: Leaving directory `/root/Desktop/nodejs-nan/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-327.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /root/Desktop/nodejs-nan
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0

 And also would like to inform you that same application is working with
Node 8.15 but it is not working with Node 10.15.

Thanks,

**Comment by danubevictoria** [comment]
The next thing I'd try is to check if your nodejs-nan is compatible with Node 10.15. If not, then try upgrading it and see if you still hit the same error.

**Comment by bnoordhuis** [comment]
The module you're trying to build is using deprecated/removed V8 APIs. Update it or report it to its maintainers.

I'm closing this as it's not a node-gyp issue.
