### ISSUE TITLE
angular firebase wont install

### ISSUE THREAD

**Issue by AbdelAbdelAli** [nodejs/node-gyp#1693]
whene i run this command    :::::      npm i --s firebase @angular/fire
i get this error :;:
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\saado\Desktop\Angular-Crud\AngularFirestore\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\saado\Desktop\Angular-Crud\AngularFirestore\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

**Comment by rvagg** [comment]
sorry we weren't able to help out here @AbdelAbdelAli, I'm going to close this due to staleness. More verbose error output in future might help someone here provide some suggestions.
