### ISSUE TITLE
node-gyp msbuild.exe failed in Windows 10

### ISSUE THREAD

**Issue by shanezhiu** [nodejs/node-gyp#1695]
* **Node Version**:  v11.9.0 
* **Platform**:  Windows_NT 10.0.17763
* **Compiler**:\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe 
* **Module**: aglio 
* **Command**: npm install -g aglio 

<details><summary>Verbose output (from npm or node-gyp):</summary>
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(8814): note: see declaration of 'v8::TryCatch' (compiling source file ..\src\parse_async.cc)
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_sync.cc(32): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\protago
nist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_async.cc(133): error C2660: 'node::FatalException': function does not take 1 arguments [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\protagon
ist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\node.h(401): note: see declaration of 'node::FatalException' (compiling source file ..\src\parse_async.cc)
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_sync.cc(55): warning C4996: 'v8::Value::ToObject': was declared deprecatedc:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_async.cc(120): war
ning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\protagonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'

  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'
  protagonist.cc
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\options_parser.cc(30): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\pro
tagonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\options_parser.cc(49): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\pro
tagonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
  result.cc
  v8_wrapper.cc
  validate.cc
  validate_async.cc
  validate_sync.cc
  win_delay_load_hook.cc
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_async.cc(59): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\pro
tagonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_async.cc(121): error C2512: 'v8::TryCatch': no appropriate default constructor available [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\pro
tagonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(8814): note: see declaration of 'v8::TryCatch' (compiling source file ..\src\validate_async.cc)
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_async.cc(126): error C2660: 'node::FatalException': function does not take 1 arguments [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\prota
gonist.vcxproj]
  c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\node.h(401): note: see declaration of 'node::FatalException' (compiling source file ..\src\validate_async.cc)
c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_async.cc(119): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\protagonist.vcx
proj]

 

> c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'
> c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_sync.cc(34): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\prot
> agonist.vcxproj]
>   c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
> c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\validate_sync.cc(57): warning C4996: 'v8::Value::ToObject': was declared deprecated 
> 
> C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist\build\protagonist.vcxproj
> 
>   c:\users\admin\appdata\roaming\npm\node_modules\node-gyp\bin\11.9.0\include\node\v8.h(10254): note: see declaration of 'v8::Value::ToObject'
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\protagonist
> gyp ERR! node -v v11.9.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> 

> aglio-theme-olio@1.6.3 postinstall C:\Users\admin\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio
> node scripts/setup-cache.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\aglio\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (node_modules\aglio\node_modules\protagonist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by bzoz** [comment]
`c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_async.cc(133): error C2660: 'node::FatalException': function does not take 1 arguments `

This looks like an issue with aglio module, you should report it there.

**Comment by shanezhiu** [comment]
ok, thanks a lot.

> `c:\users\admin\appdata\roaming\npm\node_modules\aglio\node_modules\protagonist\src\parse_async.cc(133): error C2660: 'node::FatalException': function does not take 1 arguments `
> 
> This looks like an issue with aglio module, you should report it there.
