### ISSUE TITLE
node-gyp --python => not listed command 

### ISSUE THREAD

**Issue by BlenderViza** [nodejs/node-gyp#1697]
I would like to follow your instructions

> Configuring Python Dependency
> If you have multiple Python versions installed, you can identify which Python version node-gyp uses by setting the --python variable:
> 
> $ **node-gyp --python /path/to/python2.7**
> 

to compile node-gyp for node.js 11.10.1 and I get stuck on that point. 

`gyp ERR! stack Error: Command failed: C:\Program Files\Python35\python.EXE `

although I use your 'rebuild'-trick. 

How to fix this?

* **Node Version**:  11.10.1
* **Platform**:  windows 10 1803 64 bit
* **Compiler**: 
* **Module**:  

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by BlenderViza** [comment]
My temporary solution:

### **python_switch27.bat:**
```
rem remove from path 
set PATH=%PATH:C:\Program Files\Python35\Scripts\;=%
set PATH=%PATH:C:\Program Files\Python35\;=%

rem add to path 
set PATH=C:\Program Files\nodejs\node_modules\edge-js\tools\Python27\;%PATH%
set PATH=C:\Program Files\nodejs\node_modules\edge-js\tools\Python27\Scripts\;%PATH%

``` 

and 

### **python_switch35.bat**
```
rem remove from path
set PATH=%PATH:C:\Program Files\nodejs\node_modules\edge-js\tools\Python27\;=%
set PATH=%PATH:C:\Program Files\nodejs\node_modules\edge-js\tools\Python27\Scripts\;=%

rem add to path 
set PATH=C:\Program Files\Python35\Scripts\;%PATH%
set PATH=C:\Program Files\Python35\;%PATH%

```

**Comment by bzoz** [comment]
As the issue template says, please provide verbose log of the npm/node-gyp output.
