### ISSUE TITLE
cannot find node-gyp at  ...AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js

### ISSUE THREAD

**Issue by BlenderViza** [nodejs/node-gyp#1700]
The suffering continues.

build.bat called from node_module\edge-js => missing node-gyp (see issue title) 

I copied node_modules from ...\Program Files\nodejs\**node_modules**  to ...\AppData\Roaming\npm\**node_moduls.** 7307 files 512 MB

build.bat release 11.10.1 => success building edge-js.node

Something ist wrong! 

npm issues edge-js

* **Node Version**: 11.10.1
* **Platform**: Win 10 1803 64 bit
* **Compiler**: MSVS 2017
* **Module**: edge-js

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

[no unknown problem](https://stackoverflow.com/questions/50286109/getting-node-gyp-working-on-windows-10)

**Comment by BlenderViza** [comment]
My ege-js helloWorld example works only if I save it in the folder C:\Users\RVPHX\ AppData\Roaming\npm although my path variable contains this path. 

That's not what I exspected and it's really really weird. 

Why is everything redirected from the original installation path to AppData\Roaming\npm?

**Comment by bzoz** [comment]
As the issue template says, please provide verbose log of the npm/node-gyp output.
