### ISSUE TITLE
Rebuilding electron-edge-js produces a module that cannot be properly delay loaded

### ISSUE THREAD

**Issue by lkonstantinov** [nodejs/node-gyp#1704]
The problem is with the delay loading of the module in Electron - `win_delay_load_hook.cc` needs to have `#pragma unmanaged` as outlined in this issue:

https://github.com/agracio/electron-edge-js/issues/32

https://github.com/agracio/electron-edge-js/issues/32#issuecomment-464369093

**Comment by rvagg** [comment]
this is probably going to require a pull request from someone that wants this to change on node-gyp's side, sorry
