### ISSUE TITLE
npm i -g unit-http fails in node-gyp

### ISSUE THREAD

**Issue by imvetri** [nodejs/node-gyp#1706]
* **Node Version**: Node - v8.11.1 , npm v5.8.0
* **Platform**: 
Darwin C02V41JDG8WL 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64.
OS Name: Mac.
OS Version: 10.13.4.
* **Compiler**: TBD
* **Module**: npm i -g node-http fails.

<details><summary>
 vshanmugam$ npm i -g unit-http

> unit-http@1.8.0 install /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http
> node-gyp configure build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin/node" "/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unit-http@1.8.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unit-http@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vshanmugam/.npm/_logs/2019-04-02T07_21_41_847Z-debug.log
</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'unit-http' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose npm-session 25ceef7dde87f9ac
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/unit-http 27ms (from cache)
8 silly pacote tag manifest for unit-http@latest fetched in 49ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule unit-http@1.8.0 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── unit-http@1.8.0
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add unit-http@1.8.0
19 silly decomposeActions action count 8
20 silly decomposeActions fetch unit-http@1.8.0
21 silly decomposeActions extract unit-http@1.8.0
22 silly decomposeActions preinstall unit-http@1.8.0
23 silly decomposeActions build unit-http@1.8.0
24 silly decomposeActions install unit-http@1.8.0
25 silly decomposeActions postinstall unit-http@1.8.0
26 silly decomposeActions finalize unit-http@1.8.0
27 silly decomposeActions refresh-package-json unit-http@1.8.0
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /Users/vshanmugam/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /Users/vshanmugam/.npm/_locks/staging-187180038430d05c.lock for /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/.staging
32 silly doParallel extract 1
33 silly extract unit-http@1.8.0
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http
39 silly doParallel refresh-package-json 1
40 silly refresh-package-json /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http
41 silly doParallel preinstall 1
42 silly preinstall unit-http@1.8.0
43 info lifecycle unit-http@1.8.0~preinstall: unit-http@1.8.0
44 silly doSerial build 8
45 silly build unit-http@1.8.0
46 info linkStuff unit-http@1.8.0
47 silly linkStuff unit-http@1.8.0 has /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules as its parent node_modules
48 silly linkStuff unit-http@1.8.0 is part of a global install
49 silly linkStuff unit-http@1.8.0 is installed into a global node_modules
50 silly linkStuff unit-http@1.8.0 is installed into the top-level global node_modules
51 verbose linkBins unit-http@1.8.0
52 verbose linkMans unit-http@1.8.0
53 silly doSerial global-link 8
54 silly doParallel update-linked 0
55 silly doSerial install 8
56 silly install unit-http@1.8.0
57 info lifecycle unit-http@1.8.0~install: unit-http@1.8.0
58 verbose lifecycle unit-http@1.8.0~install: unsafe-perm in lifecycle true
59 verbose lifecycle unit-http@1.8.0~install: PATH: /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http/node_modules/.bin:/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/.bin:/Users/vshanmugam/.local/bin:/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
60 verbose lifecycle unit-http@1.8.0~install: CWD: /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/unit-http
61 silly lifecycle unit-http@1.8.0~install: Args: [ '-c', 'node-gyp configure build' ]
62 silly lifecycle unit-http@1.8.0~install: Returned: code: 1  signal: null
63 info lifecycle unit-http@1.8.0~install: Failed to exec install script
64 verbose unlock done using /Users/vshanmugam/.npm/_locks/staging-187180038430d05c.lock for /Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/.staging
65 verbose stack Error: unit-http@1.8.0 install: `node-gyp configure build`
65 verbose stack Exit status 1
65 verbose stack     at EventEmitter.<anonymous> (/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
65 verbose stack     at emitTwo (events.js:126:13)
65 verbose stack     at EventEmitter.emit (events.js:214:7)
65 verbose stack     at ChildProcess.<anonymous> (/Users/vshanmugam/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
65 verbose stack     at emitTwo (events.js:126:13)
65 verbose stack     at ChildProcess.emit (events.js:214:7)
65 verbose stack     at maybeClose (internal/child_process.js:925:16)
65 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
66 verbose pkgid unit-http@1.8.0
67 verbose cwd /Users/vshanmugam
68 verbose Darwin 17.5.0
69 verbose argv "/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin/node" "/Users/vshanmugam/.nvm/versions/node/v8.11.1/bin/npm" "i" "-g" "unit-http"
70 verbose node v8.11.1
71 verbose npm  v5.8.0
72 error code ELIFECYCLE
73 error errno 1
74 error unit-http@1.8.0 install: `node-gyp configure build`
74 error Exit status 1
75 error Failed at the unit-http@1.8.0 install script.
75 error This is probably not a problem with npm. There is likely additional logging output above.
76 verbose exit [ 1, true ]

```

</details>

Let me know if details are not enough. I will update as needed.
 
#https://github.com/nginx/unit/issues/239

**Comment by rvagg** [comment]
closing due to staleness, looks like nginx/unit#239 has some help though
