### ISSUE TITLE
node-gyp Error: Cannot find module

### ISSUE THREAD

**Issue by kakkero** [nodejs/node-gyp#1711]
I have sorted more ways than i could do, e.g. uninstall everything and reinstalling it. but none works. Could someone please assist me on this one?
![Capture](https://user-images.githubusercontent.com/24399654/55664329-771bee00-585e-11e9-9e38-0e992e639ef8.JPG)

C:\Windows\system32>node-gyp rebuild

C:\Windows\system32>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\node_modules\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by bzoz** [comment]
Hi, could you provide node and npm versions?

**Comment by kakkero** [comment]
> Hi, could you provide node and npm versions?

**Comment by kakkero** [comment]
> Hi, could you provide node and npm versions?

![image](https://user-images.githubusercontent.com/24399654/57125367-c43aa380-6dbb-11e9-81a3-723ea314c4e7.png)

**Comment by kakkero** [comment]
C:\Windows\System32>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.15.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\System32
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
Make sure you have python 2 installed and that it's on your %PATH% somewhere. You can also pass `--python <path>\python.exe` to npm / node-gyp or set that in your .npmrc.

**Comment by rvagg** [comment]
see https://github.com/nodejs/node-gyp#on-windows if you need more info on dependencies and how to get them conveniently
