### ISSUE TITLE
Error: `make` failed with exit code: 2 (installing I2C Modules - MCP23017)

### ISSUE THREAD

**Issue by TiaPreve** [nodejs/node-gyp#1712]
Hi,

I'm trying to install the palette `node-red-contrib-mcp23017` in Node-Red.

What it returns to me are just errors both installing via Node-Red or using the npm mode in the .node-red directory.

I followed all the instructions written in the prerequisites in this page [https://flows.nodered.org/node/node-red-contrib-mcp23017](https://flows.nodered.org/node/node-red-contrib-mcp23017)

I installed the Node.js and then when I typed the command `npm install node-mcp23017 --save` it return to me the following error:

> i2c.target.mk:99: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
> make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
> make: Leaving directory '/home/pi/.node-red/node_modules/i2c/build'
> gyp ERR! build error
> gyp ERR! stack Error: make failed with exit code: 2
> gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.19.32-v7+
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/pi/.node-red/node_modules/i2c
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN node-red-project@0.0.1 No repository field.
> npm WARN node-red-project@0.0.1 No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! i2c@0.2.3 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the i2c@0.2.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/pi/.npm/_logs/2019-04-07T12_40_14_264Z-debug.log

I'm using Raspbian Stretch Lite and with the `i2cdetect -y 1` I can see without any problem my device MCP23017. 
I had a look over internet and try different combination without succeed.
Unfortunately I can't installing it using NPM due to this problem.
Could someone help me please?

Thanks a lot,
Mattia

**Comment by bnoordhuis** [comment]
That's an issue with the module you're trying to build, not node-gyp. Try reporting it over there.
