### ISSUE TITLE
4.0.0 is not published to npm

### ISSUE THREAD

**Issue by limonte** [nodejs/node-gyp#1721]
https://github.com/nodejs/node-gyp/blob/master/package.json#L14

![image](https://user-images.githubusercontent.com/6059356/56274384-49109680-6107-11e9-8480-855c78fb7859.png)

https://www.npmjs.com/package/node-gyp

![image](https://user-images.githubusercontent.com/6059356/56274413-54fc5880-6107-11e9-89c7-3deeaf0d74d8.png)

Expected: 4.0.0 is published to npm

**Comment by limonte** [comment]
hm, https://github.com/nodejs/node-gyp/commit/75cfae290fee1791a23fa68820ae5dd841e93e14

**Comment by limonte** [comment]
this nonsense lead to `node-gyp` being vulnerable:

![image](https://user-images.githubusercontent.com/6059356/56275252-094aae80-6109-11e9-9076-a27108ec6761.png)

**Comment by JCMais** [comment]
cc @nodejs/node-gyp

**Comment by shehi** [comment]
@limonte , this situation will be remedied?

**Comment by limonte** [comment]
@shehi I'm not the maintainer of this package. 2 years wasn't enough to run `npm publish` so I'd assume we'll need to wait a few more years.

**Comment by ChALkeR** [comment]
I think this is now fixed per https://github.com/nodejs/node-gyp/pull/1718#issuecomment-486023253 (thanks, @rvagg!).

Closing this now, feel free to reopen and/or comment though.
