### ISSUE TITLE
node-gyp fails with node 12.0, many Utf8Value errors

### ISSUE THREAD

**Issue by markamccann** [nodejs/node-gyp#1726]
* **Node Version**: node 12.0.0 and npm 6.7.0
* **Platform**: macOS 10.14.4 (Mojave)
* **Compiler**: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
* **Module**: trying to install boost-geospatial-index which compiles with node-gpy

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
.node-gyp/12.0.0/include/node/v8.h:3002:5: note: candidate constructor not viable: no
      known conversion from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
```

</details>

In short, all of the many deprecation warnings that have been spewing out when using node-gyp up to node version 11.14 are now errors in 12.0.   Biggest offender seems to be 'Utf8Value'

**Comment by richardlau** [comment]
You’ll need to take this up with `boost-geospatial-index`, which will need to update to be compatible with Node.js 12. If it’s using `nan` then it needs to be using `nan` 2.13.2.

**Comment by markamccann** [comment]
Thanks.  That occurred to me after I posted.
