### ISSUE TITLE
build failed on win7 with vs2010

### ISSUE THREAD

**Issue by xbqian** [nodejs/node-gyp#1729]
Hi there:
I am building addon example(https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world/node-addon-api), but i got missing head file error. 
When i build it with vs2010, the same error is reported.
Can anybody help me with that?
Here is the detail:
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hello.cc
  win_delay_load_hook.cc
C:\Users\xbqian\.node-gyp\10.15.3\include\node\node_api.h(5): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [D:\Projects\nodejs_call_c\node-addon-examples-master\1_hello_world\node-addon-api\build\hello.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xbqian\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xbqian\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\Projects\nodejs_call_c\node-addon-examples-master\1_hello_world\node-addon-api
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

Node Version : 10.15.3
windows 7
vs2010

**Comment by joaocgreis** [comment]
Visual Studio 2010 hasn't been supported for a long time. To build addons with Node 10, you need at least VS2015. When reporting issues, please follow the issue template and use the `--verbose` flag.
