### ISSUE TITLE
how to add c++ dependencies?

### ISSUE THREAD

**Issue by LukeWebb99** [nodejs/node-gyp#1731]
Im trying to add curl to a module I'm making in the .gyp I dont understand how to add dependencies, do I need to make it so that when it builds the visual studio project it can link them in the linker? 

```python
{
  "targets": [
    {
     "target_name": "addon",
     "include_dirs": [ "../curl/include", "../curlcpp/include" ],
     "libraries": [ "../curl/build/lib/x64/libcurld.lib", "../curlcpp/lib/x64/curlcppd.lib"],
     "sources": [ "addon.cpp" ],
    }
  ]
}
```
the curl and curlcpp are in the same file as the .gyp file, is there any reason this doesn't work?

**Comment by refack** [comment]
This looks like it should work.

> do I need to make it so that when it builds the visual studio project

Not necessarily. Adding a dependency that build a vcxproj project is just a convenience so that projects don't need to include a pre-built binary.

You can see a rudimentary GYP documentation at gyp3.org.

Alternative libcurl binding implementations at:
* https://github.com/jiangmiao/node-curl/blob/master/binding.gyp
* https://github.com/JCMais/node-libcurl/blob/develop/binding.gyp

and other working binding.gyp at:
https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild

**Comment by LukeWebb99** [comment]
if I try and run anything ill get the following error:
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_perform [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_init [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_cleanup [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_setopt [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
C:\Users\Luke\Desktop\app\build\Release\addon.node : fatal error LNK1120: 4 unresolved externals [C:\Users\Luke\Desktop\app\build\addon.vcxproj]

**Comment by LukeWebb99** [comment]
LINK : fatal error LNK1181: cannot open input file 'curl\build\lib\x64\libcurl.lib' [C:\Users\Luke\Desktop\app\build\addon.vcxproj]

this is the error I get when I build

**Comment by LukeWebb99** [comment]
changing the lib path to 
"C:/Users/Luke/Desktop/app/curlcpp/lib/x64/curlcppd.lib"
"C:/Users/Luke/Desktop/app/curl/build/lib/x64/libcurld.lib"
I get this error:
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_perform [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_init [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_cleanup [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
addon.obj : error LNK2001: unresolved external symbol __imp_curl_easy_setopt [C:\Users\Luke\Desktop\app\build\addon.vcxproj]
C:\Users\Luke\Desktop\app\build\Release\addon.node : fatal error LNK1120: 4 unresolved externals [C:\Users\Luke\Desktop\app\build\addon.vcxproj]

**Comment by LukeWebb99** [comment]
if I add "defines" : [ "CURL_STATICLIB" ] to the .gyp file i get 24 more errors

**Comment by maxin1** [comment]
How to solve this problem, I have encountered the same problem

**Comment by LukeWebb99** [comment]
Ok this took me like a week to find out, but if you use vcpkg you can search and install libs using that and then when you create you addon on, it also makes a .sln open that in visual studio include everything you need then rebuild it using node-gyp(I've use cmake-js but node-gyp should still work) and if it doesnt give any build errors you should be good

**Comment by LukeWebb99** [comment]
if you need help

**Comment by maxin1** [comment]
I am saddened to find that the class library I rely on must compile the x86 version. In this case, I am not installing the x86 version of nodejs. Now the x64 version

**Comment by maxin1** [comment]
sln has been generated, may not be compiled for this reason

**Comment by LukeWebb99** [comment]
whats the name of the lib you are trying to install? I'll see if I can get it to build

**Comment by maxin1** [comment]
This lib is the lib provided by our company and the underlying communication, not the public library.

**Comment by LukeWebb99** [comment]
Ah I see, in that case using vcpkg isn't gonna work. thats the only reason I got libs to install, I dont really know where else to look for answers no one really has them when I looked.

**Comment by LukeWebb99** [comment]
if you know how to use cmake then cmake-js might be helpful

**Comment by maxin1** [comment]
Thank you very much， I will give it a try.
