### ISSUE TITLE
package tar dependancy has security issues, upgrade required

### ISSUE THREAD

**Issue by uiboy** [nodejs/node-gyp#1735]
`npm audit` flags a Arbitrary File Overwrite vulnerability ( https://npmjs.com/advisories/803) 
in the `tar` package which is a dependancy. 

Due to this several packages that depend on `node-gyp` are being flagged as vulnerable. For.eg `node-sass`   

The vulnerability has been patched in `tar>=4.4.2` So an upgrade to that should fix this.

**Comment by richardlau** [comment]
Already fixed. Modules will need to pick up node-gyp v4.

Duplicate of https://github.com/nodejs/node-gyp/issues/1717.
