### ISSUE TITLE
Cannot link a static library for Electron 

### ISSUE THREAD

**Issue by ChugunovRoman** [nodejs/node-gyp#1736]
Hi.
Im written a module for node with static linked the libfreetype.a library. When I build my module for NodeJS, the module uses functions from static linked library, BUT when I rebuild my module for Electron, the static linked library do not executed. All functions calls occur from shared object library, that installed in OS.
How I noticed that behavior?
I added printf in freetype2, rebuild it as static lib, and then rebuild for NodeJS my module with this new version of freetype2 library. The printf displayed a text. OK. Then I rebuild my module for Electron. Reinstall it as node_module, and run a electron app, and I didn't see the output of the printf. :(

Is it normal what rebuild the module for Electron disables static linked libraries? Or is it bug?
How I can rebuild the module for Electron with static linked library?

* **Node Version**: v10.15.2
* **Electron Version**: v4.1.5
* **Platform**: Linux bubuntu 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)
* **Module**: [my module](https://github.com/ChugunovRoman/figma-linux-bindings)

**Comment by bnoordhuis** [comment]
You should check with Electron's maintainers. I speculate they may be overriding some of node's or node-gyp's defaults.

**Comment by bnoordhuis** [comment]
By the way, `nm addon.node` should not print undefined (U) freetype2 symbols when that library is statically linked. As long as that's the case, you know something's amiss.
