### ISSUE TITLE
Move to python3 or pure node pls!

### ISSUE THREAD

**Issue by HanqingTony** [nodejs/node-gyp#1738]
Everybody has confused by some meaningless python-version problem and hey, why a nodejs module require python2?

**Comment by Toxicable** [comment]
I had issues installing a few libs that use node-gyp the other day since I didn't have python2 installed on windows.
I don't think python2 should be a dep for any npm module, unless it shipps python code itself.

**Comment by bnoordhuis** [comment]
In the works, see open issues and pull requests.
