### ISSUE TITLE
Build fails with heapdump addon error

### ISSUE THREAD

**Issue by kausibalu** [nodejs/node-gyp#1742]
* **Node Version**: 6.11.1
* **Platform**:  (Windows) --> 7 64-bit
* **Module**:  node js application
```
 ERROR in ../wag-common-ui/~/heapdump/lib/main.js
    Module not found: Error: Can't resolve '../build/Debug/addon' in 'C:\Users\kdbalam3\OMS\wag-common-ui\node_modules\heapdump\lib'
     @ ../wag-common-ui/~/heapdump/lib/main.js 21:14-45
     @ ../wag-common-ui/src/util/ExpressJSUtils.js
     @ ../wag-common-ui/ServerUtil.js
     @ ./src/api/ServerEntry.js
```

**Comment by bzoz** [comment]
Please provide entire verbose log.

**Comment by bnoordhuis** [comment]
Closing, no follow-up.

That error probably means the add-on was never built. node-heapdump's JS wrapper looks for build/Release/addon.node first, then build/Debug/addon.node in case it was created with `node-gyp build --debug`.

At any rate, not a node-gyp issue..
