### ISSUE TITLE
node-gyp rebuild error during npm install

### ISSUE THREAD

**Issue by mystikodesign** [nodejs/node-gyp#1743]
System Darwin 18.5.0
node -v v12.1.0
node-gyp -v v3.8.0
npm 6.9.0

'npm install' errors when it reaches ttf2woff2@2.0.3 install:

(node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:10:40: error: no matching member function for call to 'ToObject'
Local inputBuffer = info[0]->ToObject();
~~~~~~~~~^~~~~~~~
/Users/stnaj/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
V8_WARN_UNUSED_RESULT MaybeLocal ToObject(
^
/Users/stnaj/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local ToObject(Isolate* isolate) const);
^
1 error generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:196:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/stnaj/Documents/Work/a2-clients/sites/604_cbaReferral/node_modules/ttf2woff2
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by droconnel22** [comment]
I submitted a SO: https://stackoverflow.com/questions/56138784/unable-to-install-scrypt-due-to-npm-install-crash. I am unable to get past this issue.

**Comment by rvagg** [comment]
This is probably to do with version incompatibility - the version of the addon you're trying to compile isn't compatible with the version of Node you're trying to compile against. This is a very common thing when a new release line of Node comes out--the ecosystem needs to catch up. Node 12.1.0 is early into Node 12, so you (a) either need to be patient for the authors of the addon to catch up or (b) you need to update your dependencies, or get your dependencies to update their dependencies to compatible version. Or just downgrade your Node version and be patient.
If you're interacting with addon authors on these issues, encourage them to migrate to https://github.com/nodejs/node-addon-api which is intended to be a more stable API and ABI to compile against and should reduce these kinds of problems into the future.
