### ISSUE TITLE
Support HTTPS_PROXY

### ISSUE THREAD

**Issue by 50Wliu** [nodejs/node-gyp#1749]
* **Node Version**: 10.15.3, 6.9.0
* **Platform**: Windows Enterprise 10.0.18362 N/D Compilación 18362
* **Compiler**: N/A
* **Module**: N/A

node-gyp supports basic proxy options: https://github.com/nodejs/node-gyp/blob/721eb691cf15556cc2700eda0558d5bad5f84232/lib/install.js#L432-L435
However, it doesn't look like it supports HTTPS_PROXY (and variants).
Would this be something that node-gyp is willing to support? I can create a PR if the answer is yes.

**Comment by bzoz** [comment]
Sure, PRs are always welcomed!

**Comment by rvagg** [comment]
closing in favour of PR @ #1751
