### ISSUE TITLE
Support XDG basedir specification

### ISSUE THREAD

**Issue by eheintzmann** [nodejs/node-gyp#175]
Please support FreeDesktop.org XDG basedir specification for node-gyp

http://ploum.net/post/207-modify-your-application-to-use-xdg-folders
https://live.gnome.org/GnomeGoals/XDGConfigFolders
http://standards.freedesktop.org/basedir-spec/latest/

**Comment by Siilwyn** [comment]
@refack did you make progress on this?

I've done this for several modules using [env-paths](https://github.com/sindresorhus/env-paths) if this change can be made as a major version bump it will be straightforward to do and I'm willing to take this issue and https://github.com/nodejs/node-gyp/issues/1124.

The relevant code is placed this right?
https://github.com/nodejs/node-gyp/blob/b2e5cf077238076f904696e8090e24ebe22b84c4/bin/node-gyp.js#L19-L23

**Comment by Siilwyn** [comment]
@rvagg thoughts? :point_up:
