### ISSUE TITLE
Cannot open include file: 'util-inl.h': No such file or directory (compiling source file ..\src\bufferutil.cc)

### ISSUE THREAD

**Issue by emretapci** [nodejs/node-gyp#1758]
I encountered this error while installing via `npm i bufferutil`.
I am using node.js version 12.3.0

**Comment by richardlau** [comment]
Please see https://github.com/nodejs/node/issues/27803. This is a Node.js issue (not `node-gyp`) and should be fixed in a 12.3.1 release: https://github.com/nodejs/node/pull/27814
