### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by paulmdavies** [nodejs/node-gyp#1774]
The most recent release (released to npm today) doesn't work because of some python formatting issues:

`SyntaxError: from __future__ imports must occur at the beginning of the file`

This can be seen simply by checking out the repo and doing:

`python <repo location>/gyp/tools/pretty_vcproj.py`

or 

`python <repo location>/gyp/tools/pretty_sln.py`

It's a problem with both python 2 and python 3.

**Comment by rvagg** [comment]
@cclauss, @refack, halp!

**Comment by cclauss** [comment]
Why don't we see this in our Travis CI tests?  https://travis-ci.com/nodejs/node-gyp
