### ISSUE TITLE
is not a valid Win32 applicationwhen require a module if compiled with --arch=ia32

### ISSUE THREAD

**Issue by VladimirMerk** [nodejs/node-gyp#1776]
Hello!
I have windows 10 x64. If I compile a module with a flag --arch=ia32, then after compiling I get an error when require module: _addon.node is not a valid Win32 application_

If compiled with the x64 arch flag, then everything is in order, the module is works as it should

What could be the problem?

Versions:
node 10.16.0
npm 6.9.0
node-gyp 5.0.0

Platform:
Windows10 x64

Compiler: 
msbuild 14.0.25420.1

Module: 
Simple c++ NAPI module

Example:
Bad: node-gyp clean configure --arch=ia32 --verbose rebuild
Good: node-gyp clean configure --arch=x64 --verbose rebuild

Verbose output for node-gyp clean configure --arch=ia32 --verbose rebuild:
`gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'clean',
gyp verb cli   'configure',
gyp verb cli   '--arch=ia32',
gyp verb cli   '--verbose',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@5.0.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python checking Python explicitly set from environment variable PYTHON
gyp verb find Python - process.env.PYTHON is "D:\Python27-win\python.exe"
gyp verb find Python - executing "D:\Python27-win\python.exe" to get executable path
gyp verb find Python - executable path is "D:\Python27-win\python.exe"
gyp verb find Python - executing "D:\Python27-win\python.exe" to get version
gyp verb find Python - version is "2.7.15"
gyp info find Python using Python version 2.7.15 found at "D:\Python27-win\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: D:\Projects\addon\build
gyp verb build dir "build" dir needed to be created? D:\Projects\addon\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2017 (15.7.27703.2042) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - "Visual Studio C++ core features" missing
gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
gyp verb find VS looking for Visual Studio 2015
gyp verb find VS - found in "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp verb find VS - MSBuild in "C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Projects\addon\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Projects\addon\config.gypi
gyp verb common.gypi checking for gypi file: D:\Projects\addon\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn D:\Python27-win\python.exe
gyp info spawn args [ 'C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Projects\\addon\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Projects\\addon',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Projects\\addon\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python checking Python explicitly set from environment variable PYTHON
gyp verb find Python - process.env.PYTHON is "D:\Python27-win\python.exe"
gyp verb find Python - executing "D:\Python27-win\python.exe" to get executable path
gyp verb find Python - executable path is "D:\Python27-win\python.exe"
gyp verb find Python - executing "D:\Python27-win\python.exe" to get version
gyp verb find Python - version is "2.7.15"
gyp info find Python using Python version 2.7.15 found at "D:\Python27-win\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: D:\Projects\addon\build
gyp verb build dir "build" dir needed to be created? D:\Projects\addon\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2017 (15.7.27703.2042) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - "Visual Studio C++ core features" missing
gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
gyp verb find VS looking for Visual Studio 2015
gyp verb find VS - found in "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp verb find VS - MSBuild in "C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Projects\addon\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Projects\addon\config.gypi
gyp verb common.gypi checking for gypi file: D:\Projects\addon\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn D:\Python27-win\python.exe
gyp info spawn args [ 'C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Projects\\addon\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Hp\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Hp\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Projects\\addon',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Projects\\addon\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
Сборка начата 15.06.2019 9:22:49.
Проект "D:\Projects\addon\build\binding.sln" в узле 1 (целевые объекты по умолчанию).
ValidateSolutionConfiguration:
  Создание конфигурации решения "Release|Win32".
Проект "D:\Projects\addon\build\binding.sln" (1) выполняет сборку "D:\Projects\client-master\dist\resour
ces\addon\build\addon.vcxproj.metaproj" (2) в узле 1 (целевые объекты по умолчанию).
Проект "D:\Projects\addon\build\addon.vcxproj.metaproj" (2) выполняет сборку "D:\Projects\client-master
\dist\resources\addon\node_modules\node-addon-api\src\nothing.vcxproj" (3) в узле 1 (целевые объекты по умолчанию).
PrepareForBuild:
  Создание каталога "D:\Projects\addon\build\Release\".
InitializeBuildStatus:
  Создание "Release\obj\nothing\nothing.tlog\unsuccessfulbuild", так как было задано "AlwaysCreate".
ClCompile:
  Для всех выходных данных обновления не требуется.
  Для всех выходных данных обновления не требуется.
Lib:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\Lib.exe /OUT:"D:\Projects\addon\b
  uild\Release\nothing.lib" /NOLOGO /LTCG:INCREMENTAL Release\obj\nothing\nothing.obj
  Release\obj\nothing\win_delay_load_hook.obj
  nothing.vcxproj -> D:\Projects\addon\build\Release\\nothing.lib
FinalizeBuildStatus:
  Файл "Release\obj\nothing\nothing.tlog\unsuccessfulbuild" удаляется.
  Обращение к "Release\obj\nothing\nothing.tlog\nothing.lastbuildstate".
Сборка проекта "D:\Projects\addon\node_modules\node-addon-api\src\nothing.vcxproj" завершена (целевые об
ъекты по умолчанию).

Проект "D:\Projects\addon\build\addon.vcxproj.metaproj" (2) выполняет сборку "D:\Projects\client-master
\dist\resources\addon\build\addon.vcxproj" (4) в узле 1 (целевые объекты по умолчанию).
PrepareForBuild:
  Создание каталога "Release\obj\addon\".
  Создание каталога "Release\obj\addon\addon.tlog\".
InitializeBuildStatus:
  Создание "Release\obj\addon\addon.tlog\unsuccessfulbuild", так как было задано "AlwaysCreate".
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\CL.exe /c /I"C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\i
  nclude\node" /I"C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\src" /I"C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\deps\opens
  sl\config" /I"C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\deps\openssl\openssl\include" /I"C:\Users\Hp\AppData\Local\node-gyp\C
  ache\10.16.0\deps\uv\include" /I"C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\deps\zlib" /I"C:\Users\Hp\AppData\Local\node-gyp\C
  ache\10.16.0\deps\v8\include" /I"D:\Projects\addon\node_modules\node-addon-api" /Z7 /nologo /W3 /WX- /
  MP /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=addon /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D
   WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D NAPI_DISABLE_CPP_EXCEPTIONS /D "_SECRET=\"ab
  cd1234\"" /D "_ENCRYPT_DATA=\"hello\"" /D BUILDING_NODE_EXTENSION /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:
  precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\addon\\" /Fd"Release\obj\addon\vc140.pdb" /Gd /TP /wd4351 /wd4355
   /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /analyze- /errorReport:queue ..\cppsrc\main.cpp ..\cppsrc\addon.cpp "C:\Users\Hp\AppData\R
  oaming\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  main.cpp
  addon.cpp
  win_delay_load_hook.cc
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\link.exe /ERRORREPORT:QUEUE /OUT:"D:\Projects\client-master\dis
  t\resources\addon\build\Release\addon.node" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib ad
  vapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib DelayImp.lib "C:\Users\Hp\AppData\Local\node-gyp\Cache\10.16.0\ia3
  2\node.lib" Delayimp.lib /DELAYLOAD:node.exe /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB
  :"D:\Projects\addon\build\Release\addon.pdb" /MAP /MAPINFO:EXPORTS /OPT:REF /OPT:ICF /TLBID:1 /DYNAMI
  CBASE /NXCOMPAT /MACHINE:X86 /SAFESEH /ignore:4199 /LTCG:INCREMENTAL /DLL Release\obj\addon\main.obj
  Release\obj\addon\addon.obj
  Release\obj\addon\win_delay_load_hook.obj
  "D:\Projects\addon\build\Release\nothing.lib"
     Creating library D:\Projects\addon\build\Release\addon.lib and object D:\Projects\client-master\di
  st\resources\addon\build\Release\addon.exp
  Generating code
  All 222 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  addon.vcxproj -> D:\Projects\addon\build\Release\\addon.node
  addon.vcxproj -> D:\Projects\addon\build\Release\addon.pdb (Full PDB)
FinalizeBuildStatus:
  Файл "Release\obj\addon\addon.tlog\unsuccessfulbuild" удаляется.
  Обращение к "Release\obj\addon\addon.tlog\addon.lastbuildstate".
Сборка проекта "D:\Projects\addon\build\addon.vcxproj" завершена (целевые объекты по умолчанию).

Сборка проекта "D:\Projects\addon\build\addon.vcxproj.metaproj" завершена (целевые объекты по умолчанию
).

Сборка проекта "D:\Projects\addon\build\binding.sln" завершена (целевые объекты по умолчанию).

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Затраченное время: 00:00:06.49
gyp info ok`

**Comment by bzoz** [comment]
Are you using 32bit Node when loading 32bit addon?
