### ISSUE TITLE
Rebuild may be started before finishing header files extracted.

### ISSUE THREAD

**Issue by monaka** [nodejs/node-gyp#1780]
* **Node Version**: v10.15.3 / 6.4.1
* **Platform**: inux 98ed0a38bc56 4.14.104+ #1 SMP Mon May 27 23:12:27 PDT 2019 x86_64 Linux
* **Compiler**: gcc version 8.3.0 (Alpine 8.3.0)
* **Module**: native-keymap

<details><summary>Verbose output (from npm or node-gyp):</summary>

https://dev.azure.com/pizzafactory/camino/_build/results?buildId=837&view=logs&jobId=ca395085-040a-526b-2ce8-bdc85f692774&taskId=e32f6c0c-095d-5644-3d3c-8457b0141736&lineStart=115&lineEnd=188&colStart=1&colEnd=1

https://dev.azure.com/pizzafactory/camino/_build/results?buildId=841&view=logs&jobId=ca395085-040a-526b-2ce8-bdc85f692774&taskId=c310a698-906e-53a5-78f7-614142e7c740&lineStart=185&lineEnd=418&colStart=1&colEnd=1

</details>

I got build failures sporadically when my CI runs `node-gyp rebuild.`. Error messages are not same but all of them looks files in ~/.node-gyp/* are broken.

**Comment by monaka** [comment]
Additional info:

I found the similar issue on https://github.com/phusion/node-sha3/issues/42.

Still it is not sure now, I'm checking, but `node-gyp install && node-gyp rebuild` look working without this issue.

**Comment by richardlau** [comment]
Since `yarn` is involved you may be running into https://github.com/nodejs/node-gyp/issues/1054.

**Comment by monaka** [comment]
@richardlau Thank you for the valuable pointer.
And I read https://github.com/yarnpkg/yarn/issues/1874 also.
Let me make sure. In my case,  is it a best practice calling `node-gyp install` before the install process?

**Comment by rvagg** [comment]
`node-gyp install` would probably be a good thing to do before everything else as a workaround if you're using yarn and running into this problem, then it should just check that the files exist in ~/.node-gyp when it does a build. It's not "best practice" per se, but as a workaround, it's fine.
