### ISSUE TITLE
\node_modules\.bin\electron-rebuild.cmd -v 5.0.4    Rebuild Failed

### ISSUE THREAD

**Issue by 18308996929** [nodejs/node-gyp#1783]
electron project uses sqlites , rebuild sqlites module,   but when run  "electron-rebuild.cmd -v  5.0.4"   failed!
my system version infos:
     node  v11.2.0
     electron v5.0.4
     node-gyp v5.0.0
     python v2.7.16
     npm install --global --production windows-build-tools  //this has already run sucessfully
     npm config set python python2.7	//this has already run!
   npm config set msvs_version 2015  //this has already run!

The printout from cmd:  
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@11.2.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\node-gyp\\gyp\\gyp_main.p
y',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\sqlite3\\build\\config.gy
pi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\5.0.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\5.0.4',
gyp info spawn args   '-Dnode_gyp_dir=E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\node-gyp',

gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.electron-gyp\\5.0.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\sqlite3
',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(6
7,5): error MSB8020: �޷��ҵ� v140 �����ɹ���(ƽ̨���߼� =��v140��)����Ҫʹ�� v140 ���ɹ��߽
������ɣ��밲װ v140 ���ɹ��ߡ����ߣ�������������ǰ Visual Studio ���ߣ���ʽ��ͨ��ѡ
����Ŀ���˵����Ҽ������ý��������Ȼ��ѡ���ض��������Ŀ�ꡱ�� [E:\test\electron_video_
src-master\src\system\sqlite\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\test\electron_video_src-master\src\system\sqlite\node_modules\node-gyp\lib
\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\node_js\\node.exe" "E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modules\\node-g
yp\\bin\\node-gyp.js" "rebuild" "--target=5.0.4" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-
source" "--module_name=node_sqlite3" "--module_path=E:\\test\\electron_video_src-master\\src\\system\\sqlite\\node_modul
es\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=
./{name}/v4.0.9/{toolset}/" "--package_name=electron-v5.0-win32-x64.tar.gz"
gyp ERR! cwd E:\test\electron_video_src-master\src\system\sqlite\node_modules\sqlite3
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

Failed with exit code: 1

If anyone has any idas I would be very grateful!!!!!

**Comment by bzoz** [comment]
Run `npm config set msvs_version 2017` and try again.
