### ISSUE TITLE
Using node-gyp to build modules for embedded nodejs

### ISSUE THREAD

**Issue by ross-weir** [nodejs/node-gyp#1784]
Is `node-gyp` suitable for building native modules that will be used with embedded node?

Any help on this would be very much appreciated.

I have node embedded into an application I am working on but I'm having issues loading native modules that I'm trying to trace down.

I notice that all the configuration that `node-gyp` generates for node addons seems to be aimed at an executable node. One of my current theories is maybe the symbols cannot be found because of this.

For completeness:

I've been debugging the runtime execution and it seems to be crashing when the native module is trying to call `GetProcAddress` on `napi_module_register`. Which backs up my current theory of not being able to find symbols, maybe.

**Comment by ross-weir** [comment]
Actually I don't think the problem related to how the native modules are built, but I'll leave this question open for now in case of confirmation 👍

**Comment by bnoordhuis** [comment]
> Is node-gyp suitable for building native modules that will be used with embedded node?

The short answer is 'yes.'

You need to do some work on your end as an embedder to make symbols available, get node-gyp to pick up the right header files and common.gypi, etc., but that's merely yak shaving, there are no fundamental barriers.

See e.g. electron for an example.
