### ISSUE TITLE
Add @bzoz to @nodejs/node-gyp team

### ISSUE THREAD

**Issue by rvagg** [nodejs/node-gyp#1786]
@bzoz you're very active here helping out on Windows issues but I don't think you have access to merge stuff or close issues. Do you mind if we add you to @nodejs/node-gyp and step your access up to give you these things?

And if so .. could I get someone who has access to do this please.

**Comment by rvagg** [comment]
actually I'd like to be on that group too, I have access through nodejs/build only at the moment, I'll request it.

**Comment by bnoordhuis** [comment]
For some reason only @Fishrock123 is a maintainer of the node-gyp team...

@Fishrock123 Can you upgrade everyone to maintainer and add @rvagg and @bzoz? Cheers.

**Comment by bzoz** [comment]
@rvagg, yeah, that would be great!

**Comment by rvagg** [comment]
@cclauss would you like to be a maintainer too? We can put you on the node-gyp team in the same batch if you'd like.

**Comment by cclauss** [comment]
Sure.

**Comment by rvagg** [comment]
@sam-github, @Trott or someone else: could you please do some permissions adjustments here? Add @bzoz, @cclauss and @rvagg to nodejs/node-gyp: https://github.com/orgs/nodejs/teams/node-gyp/members

**Comment by Trott** [comment]
> @sam-github, @Trott or someone else: could you please do some permissions adjustments here? Add @bzoz, @cclauss and @rvagg to nodejs/node-gyp: https://github.com/orgs/nodejs/teams/node-gyp/members

Done.
