### ISSUE TITLE
I found same problem . after install free  MS Visuals studio 2019 .

### ISSUE THREAD

**Issue by simmani5** [nodejs/node-gyp#1797]
I found same problem . after install free  MS Visuals studio 2019 .
I saw   install node js during install MS Visual Studio 2019 .. so I thout  it cause some proble. to me. 
but any way  install done . and I did not use MS VS2019 but..

im tried  intsall 
    git clone git@github.com:andrew/node-sass-example.git
    cd node-sass-example
    npm install  (((=== Error here )))
    node server.js
    open http://localhost:8000

I think it cause VS 2019 setup . may be..
debug.log === under ===here===
4778 verbose pkgid node-sass@3.13.1
4779 verbose cwd D:\_hom\github\andrew\node-sass-example
4780 verbose Windows_NT 10.0.17763
4781 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
4782 verbose node v10.16.0
4783 verbose npm  v6.9.0
4784 error code ELIFECYCLE
4785 error errno 1
4786 error node-sass@3.13.1 postinstall: `node scripts/build.js`
4786 error Exit status 1
4787 error Failed at the node-sass@3.13.1 postinstall script.
4787 error This is probably not a problem with npm. There is likely additional logging output above.
4788 verbose exit [ 1, true ]
=============
is there any one ? who know how to solve  this Error  ?

1st I tried  npm install at  MigWin64 terminal  it installed when I install Git program.
 

======= Im tried   cmd  " npm remove  node-sass " but fail , Errmsg unser ==== here ===

gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\admin\.node-gyp\10.16.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\_hom\\github\\andrew\\node-sass-example\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\_hom\github\andrew\node-sass-example\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-06-23T22_38_31_862Z-debug.log

I found .. same Err Solving ========= 
### https://github.com/felixrieseberg/windows-build-tools/issues/182

**Comment by richardlau** [comment]
Please see https://github.com/nodejs/node-gyp/issues/1753#issuecomment-501827267 re. VS 2019 support.
