### ISSUE TITLE
setting of gyp variables via command line

### ISSUE THREAD

**Issue by kontrafiktion** [nodejs/node-gyp#180]
As far as I understand the gyp documentation, I should be able to set a gyp variable using

```
  node-gyp configure -DLNNZ_VERSION=10
```

And in my binding.gyp file:

```
  'variables': {
    'LNNZ_VERSION%': '11'
  },
```

I would expect that the value of LNNZ_VERSION is 10 with the above invocation. Am I doing something wrong, or is this not supported by node-gyp?

Background: depending on the version of Oracle installed on the system, there is either a lnnz10 or a lnnz11 library. And the build must use the correct one ...
The only other solution would be to create a dynamic link 'lnnz' and use that as dependency

Any input?

**Comment by piranna** [comment]
How can this be done when installing a package with ```npm install```?

**Comment by TooTallNate** [comment]
Just pass it along as a flag to npm. Unhandled options from npm get turned into gyp flags. See https://github.com/TooTallNate/node-speaker#audio-backend-selection for an example.

```
$ npm install foo --LNNZ_VERSION=10
```

Let me know if that doesn't work as expected.

**Comment by piranna** [comment]
Oh cool, thanks! Just didn't know it :-) I'll try it and tell you if it works ;-)

**Comment by piranna** [comment]
Ok, that worked :-) Thank you @TooTallNate! :-D
