### ISSUE TITLE
Travis CI tests are failing on Windows

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-gyp#1801]
Travis CI currently runs tests on Windows but those tests are currently run in __allow_failures__ mode.  https://github.com/nodejs/node-gyp/blob/master/.travis.yml#L15-L20

It would be really cool to get those tests passing.

**Comment by richardlau** [comment]
> 
> 
> Travis CI currently runs tests on Windows but those tests are currently run in **allow_failures** mode. https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/builds/116968308#L734
> 
> It would be really cool to get those tests passing.

Did you post the wrong link?

**Comment by cclauss** [comment]
Yes.  Fixed inline above.

**Comment by cclauss** [comment]
@krisavi @joaocgreis If you have any cycles/ideas on how to get Windows tests working on Travis CI...
