### ISSUE TITLE
gyp ERR! configure error  

### ISSUE THREAD

**Issue by MokMec** [nodejs/node-gyp#1814]
I just installed nodejs 10.16 and ionic. 
When I try to run ionic serve on an empty project I get an error:"[ng] Error: Cannot find module "node-sass'"".

when I do sudo npm ls node-sass I get this:
ionicV3@0.0.1 /Users/m/Projects/ionicV3
└─┬ @angular-devkit/build-angular@0.13.9
  └── 18 OPTIONAL DEPENDENCY UNMET node-sass@4.12.0 

and when I do a sudo npm install -g node-sass I get the following error: 

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/node-sass/build'
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can someone help me? 

Thank you

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node-gyp/issues?utf8=%E2%9C%93&q=is%3Aissue+EACCES - it's been asked many times before.

**Comment by xacaxulu** [comment]
+1

**Comment by jiaoyueyue** [comment]
+1

**Comment by cclauss** [comment]
https://github.com/sass/node-sass/issues/2952
