### ISSUE TITLE
'list' object has no attribute 'items

### ISSUE THREAD

**Issue by orangebook** [nodejs/node-gyp#1831]
* **Node Version**: 

```
node v12.6.0 
npm v6.10.1
```
* **Platform**:

```
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019;
 root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
* **Compiler**: 
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: 
node-gyp
<details>
<summary>AttributeError: 'list' object has no attribute 'items'

gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.6.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/local/opt/python@2/bin/python2.7"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Arthur/NodeProj/node-osip/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Arthur/Library/Caches/node-gyp/12.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Arthur/Library/Caches/node-gyp/12.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Arthur/Library/Caches/node-gyp/12.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Arthur/NodeProj/node-osip',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2844, in Load
    DoDependentSettings(settings_type, flat_list, targets, dependency_nodes)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1931, in DoDependentSettings
    build_file, dependency_build_file)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2121, in MergeDicts
    for k, v in fro.items():
AttributeError: 'list' object has no attribute 'items'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Arthur/NodeProj/node-osip
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
</summary>
</details>

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blame/master/gyp/pylib/gyp/input.py#L2121 was last modified two years ago...  For study needed.

**Comment by orangebook** [comment]
fine, find 
```
          'direct_dependent_settings': {
              # add new tag, and pass
              'include_dirs': [
                  './libosip2-5.1.0/include/osip2/',
                  './libosip2-5.1.0/include/osip2/',
              ]
          },
```

**Comment by cclauss** [comment]
The solution was?!?

**Comment by orangebook** [comment]
> The solution was?!?

One by one check tags (didn't add array tag) from your provide link
