### ISSUE TITLE
tns migrate node-gyp error

### ISSUE THREAD

**Issue by habmoh** [nodejs/node-gyp#1832]
command  :  tns migrate 

* **Node Version**: 6.4.1
* **Platform**: Windows 10
* **Compiler**:  `msbuild /version & cl` (Windows) 
* **Module**:  tns migrate

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Source\\Repos\\DSCIT-MFG-QMDB-Mobile\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Source\Repos\DSCIT-MFG-QMDB-Mobile\node_modules\node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
```

</details>

**Comment by rvagg** [comment]
you may not have the build tools installed, try `npm install --global --production windows-build-tools `

**Comment by richardlau** [comment]
> ```
> gyp ERR! UNCAUGHT EXCEPTION
> gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
> ```

VS2019 support was added in node-gyp 5.0.0. See https://github.com/nodejs/node-gyp/pull/1715#issuecomment-502211967 for instructions on how to temporarily upgrade.

**Comment by bzoz** [comment]
Closing as solved per @richardlau comment. If you have any more problems feel free to open new issues.

**Comment by habmoh** [comment]
I have already installed that.
