### ISSUE TITLE
Error when installing certain packages with --save option

### ISSUE THREAD

**Issue by Hexxonite** [nodejs/node-gyp#1833]
* **Node Version**: v11.4.0
* **Platform**:  Windows 10 Pro (command doesnt work)
* **Compiler**: Ms Build VS 2019 (command doesnt work)
* **Module**: node-webcrypto-ossl

<details><summary>Verbose output (from npm or node-gyp):</summary>

[2019-07-18T13_33_49_004Z-debug.log](https://github.com/nodejs/node-gyp/files/3406715/2019-07-18T13_33_49_004Z-debug.log)

</details>

I'm having a lot of struggle with node-gyp.
This is not the first time or package this happened but its starting to annoy me.....

Any fix?

**Comment by bzoz** [comment]
Looks like one of the modules needs to be built. Install build tools by running `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).
