### ISSUE TITLE
Replace dependency CircularJSON with its successor flatted

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-gyp#1838]
Every time our Travis CI tests run, they generate [the following warning](https://travis-ci.com/nodejs/node-gyp/jobs/218185939#L1913):
$ __npm install__
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

Would it be worthwhile to make this switch from the deprecated [CircularJSON](https://github.com/WebReflection/circular-json) --> [flatted](https://github.com/WebReflection/flatted)?
Both are from WebReflection but they do NOT share the same LICENSE.

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by bnoordhuis** [comment]
That's not under our control. It's not a direct dependency, not even close:
```
$ npm ls circular-json
node-gyp@5.0.3 /Users/bnoordhuis/src/node-gyp
└─┬ standard@12.0.1
  └─┬ eslint@5.4.0
    └─┬ file-entry-cache@2.0.0
      └─┬ flat-cache@1.3.4
        └── circular-json@0.3.3 
```

**Comment by rvagg** [comment]
needs an upgrade to standard@13

_However_ there's a new rule for no spacing inside square brackets that makes my blood boil: https://github.com/standard/standard/issues/1318

Let me get over my syntax rage and I'll put in a PR to "fix" this.
