### ISSUE TITLE
when i use pm2 to install a module   pm2 install pm2-webshell-jnk   this module donot have package.json only have package-lock.json how to fixed it  thanks a lot

### ISSUE THREAD

**Issue by Destiny-1** [nodejs/node-gyp#1848]
In file included from ../src/bufferutil.cc:15:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:337:64: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(nan_isolate, receiver, argc, argv);
                                                                ^
../node_modules/nan/nan.h:337:64: note: candidate is:
In file included from ../src/bufferutil.cc:7:0:
/root/.node-gyp/8.16.0/include/node/v8.h:5971:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/8.16.0/include/node/v8.h:5971:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/bufferutil.cc:15:0:
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::UnboundScript; P = v8::Local<v8::String>]’:
../node_modules/nan/nan.h:400:67: warning: ‘static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:1454): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’:
../node_modules/nan/nan.h:405:57: warning: ‘static v8::Local<v8::String> v8::String::NewExternal(v8::Isolate*, v8::String::ExternalStringResource*)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:2768): Use maybe version [-Wdeprecated-declarations]
     return v8::String::NewExternal(nan_isolate, resource);
                                                         ^
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:409:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../node_modules/nan/nan.h:409:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../node_modules/nan/nan.h:409:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../node_modules/nan/nan.h:403:36: error: previous declaration of ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../node_modules/nan/nan.h:409:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../node_modules/nan/nan.h:409:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::BooleanObject; P = bool]’:
../node_modules/nan/nan.h:415:40: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:4895): Pass an isolate [-Wdeprecated-declarations]
     return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                        ^
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:427:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../node_modules/nan/nan.h:420:3: error: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../node_modules/nan/nan.h:444:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:438:36: error: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:456:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:450:36: error: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::Uint32; P = int]’:
../node_modules/nan/nan.h:463:68: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:9858): Use maybe version [-Wdeprecated-declarations]
     return v8::Uint32::NewFromUnsigned(nan_isolate, val)->ToUint32();
                                                                    ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::Uint32; P = unsigned int]’:
../node_modules/nan/nan.h:468:68: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:9858): Use maybe version [-Wdeprecated-declarations]
     return v8::Uint32::NewFromUnsigned(nan_isolate, val)->ToUint32();
                                                                    ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::Int32; P = int]’:
../node_modules/nan/nan.h:473:54: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:9864): Use maybe version [-Wdeprecated-declarations]
     return v8::Int32::New(nan_isolate, val)->ToInt32();
                                                      ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::Int32; P = unsigned int]’:
../node_modules/nan/nan.h:478:54: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:9864): Use maybe version [-Wdeprecated-declarations]
     return v8::Int32::New(nan_isolate, val)->ToInt32();
                                                      ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P, int) [with T = v8::String; P = unsigned char*]’:
../node_modules/nan/nan.h:522:15: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:2729): Use maybe version [-Wdeprecated-declarations]
       , length);
               ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P, int) [with T = v8::String; P = const unsigned char*]’:
../node_modules/nan/nan.h:533:15: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:2729): Use maybe version [-Wdeprecated-declarations]
       , length);
               ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::String; P = unsigned char*]’:
../node_modules/nan/nan.h:538:55: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:2729): Use maybe version [-Wdeprecated-declarations]
     return v8::String::NewFromOneByte(nan_isolate, arg);
                                                       ^
../node_modules/nan/nan.h: In function ‘v8::Local<T> NanNew(P) [with T = v8::String; P = const unsigned char*]’:
../node_modules/nan/nan.h:544:55: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:2729): Use maybe version [-Wdeprecated-declarations]
     return v8::String::NewFromOneByte(nan_isolate, arg);
                                                       ^
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:586:20: error: variable or field ‘NanAddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:586:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:587:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:592:20: error: variable or field ‘NanRemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:597:20: error: variable or field ‘NanAddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:597:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:598:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:603:20: error: variable or field ‘NanRemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h:631:13: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a type
       const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> >& data);
             ^
../node_modules/nan/nan.h:631:17: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
       const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> >& data);
                 ^
../node_modules/nan/nan.h:631:33: error: expected ‘,’ or ‘...’ before ‘<’ token
       const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> >& data);
                                 ^
../node_modules/nan/nan.h:767:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:767:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:770:57: error: ‘callback’ was not declared in this scope
     return node::Buffer::New(nan_isolate, data, length, callback, hint);
                                                         ^
../node_modules/nan/nan.h:770:67: error: ‘hint’ was not declared in this scope
     return node::Buffer::New(nan_isolate, data, length, callback, hint);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:777:53: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(nan_isolate, data, size);
                                                     ^
In file included from ../src/bufferutil.cc:9:0:
/root/.node-gyp/8.16.0/include/node/node_buffer.h:67:40: error:   initializing argument 2 of ‘v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)’ [-fpermissive]
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
In file included from ../src/bufferutil.cc:15:0:
../node_modules/nan/nan.h:777:53: error: could not convert ‘node::Buffer::New(nan_isolate, ((char*)data), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(nan_isolate, data, size);
                                                     ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:781:47: error: could not convert ‘node::Buffer::New(nan_isolate, ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(nan_isolate, size);
                                               ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:788:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(nan_isolate, data, size);
            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>, const v8::ScriptOrigin&)’:
../node_modules/nan/nan.h:814:60: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:1473): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(nan_isolate, &source);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>)’:
../node_modules/nan/nan.h:821:60: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated (declared at /root/.node-gyp/8.16.0/include/node/v8.h:1473): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(nan_isolate, &source);
                                                            ^
../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../node_modules/nan/nan.h:1728:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../node_modules/nan/nan.h:1729:11: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
           ^
../node_modules/nan/nan.h:1730:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../node_modules/nan/nan.h:1730:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Initialize(v8::Handle<v8::Object>)’:
../src/bufferutil.cc:29:52: error: call of overloaded ‘NODE_SET_METHOD(v8::Local<v8::FunctionTemplate>&, const char [7], void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’ is ambiguous
     NODE_SET_METHOD(t, "unmask", BufferUtil::Unmask);
                                                    ^
../src/bufferutil.cc:29:52: note: candidates are:
In file included from ../src/bufferutil.cc:8:0:
/root/.node-gyp/8.16.0/include/node/node.h:308:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Template>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
             ^
/root/.node-gyp/8.16.0/include/node/node.h:321:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^
../src/bufferutil.cc:30:48: error: call of overloaded ‘NODE_SET_METHOD(v8::Local<v8::FunctionTemplate>&, const char [5], void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’ is ambiguous
     NODE_SET_METHOD(t, "mask", BufferUtil::Mask);
                                                ^
../src/bufferutil.cc:30:48: note: candidates are:
In file included from ../src/bufferutil.cc:8:0:
/root/.node-gyp/8.16.0/include/node/node.h:308:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Template>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
             ^
/root/.node-gyp/8.16.0/include/node/node.h:321:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^
../src/bufferutil.cc:31:50: error: call of overloaded ‘NODE_SET_METHOD(v8::Local<v8::FunctionTemplate>&, const char [6], void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’ is ambiguous
     NODE_SET_METHOD(t, "merge", BufferUtil::Merge);
                                                  ^
../src/bufferutil.cc:31:50: note: candidates are:
In file included from ../src/bufferutil.cc:8:0:
/root/.node-gyp/8.16.0/include/node/node.h:308:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Template>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
             ^
/root/.node-gyp/8.16.0/include/node/node.h:321:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v8.16.0/bin/node" "/root/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.pm2/modules/pm2-webshell/node_modules/ws
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by rvagg** [comment]
These kinds of errors indicate that you're compiling a version of an addon with a version of of Node.js that it wasn't meant to be compiled with. Most likely an older addon with a newer Node.js. Your choices are either to install a newer version of the addon or downgrade your version of Node.js but since you seem to be using Node 8 I wouldn't recommend the latter. If the addon is a dependency of a dependency and you don't have a newer version available then you'll need to chase up the people publishing the package that has the older dependency to update. Most likely you just need to update your dependencies.
