### ISSUE TITLE
rebuild node-gyp failed.

### ISSUE THREAD

**Issue by dz-paji** [nodejs/node-gyp#1856]
* **Node Version**: `node:v0.10.28`,`npm:1.4.9`
* **Platform**: Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (CentOS 7.6)

* **Compiler**: 
```
Target：x86_64-redhat-linux
Configuration：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Threading model：posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
```

* **Module**: node-gyp

<details><summary>

> mmmagic@0.5.3 install /srv/node_modules/mmmagic
> node-gyp rebuild

/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/rimraf/rimraf.js:7
let glob = undefined
    ^^^^
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Unexpected identifier
gyp ERR! stack     at Module._compile (module.js:439:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:312:12)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! stack     at require (module.js:380:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js:10:10)
gyp ERR! stack     at Module._compile (module.js:456:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/node_modules/mmmagic
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! mmmagic@0.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the mmmagic@0.5.3 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.
</summary>
</details>

```
[root@localhost srv]# node-gyp rebuild --verbose

/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js:7
const envPaths = require('env-paths')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by rvagg** [comment]
> Node Version: node:v0.10.28,npm:1.4.9

Very sorry @dz-paji but we're unable to offer support on such an old version of Node. 0.10 has been out of support for a very long time, as has npm 1. You're using a newer node-gyp with a very old Node which doesn't even support basic syntax changes that have happened in JavaScript in the years between.

I'd recommend upgrading to at least Node 10.
