### ISSUE TITLE
Dependency 'binding.gyp:#target' not found while trying to load target binding.gyp:desktop_serializer#target

### ISSUE THREAD

**Issue by JohnScience** [nodejs/node-gyp#1866]
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\demen\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.812) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\demen\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\demen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\demen\\Documents\\GitHub\\Desktop-Serializer-For-Node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\demen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\demen\\AppData\\Local\\node-gyp\\Cache\\10.16.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\demen\\AppData\\Local\\node-gyp\\Cache\\10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\demen\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\demen\\AppData\\Local\\node-gyp\\Cache\\10.16.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\demen\\Documents\\GitHub\\Desktop-Serializer-For-Node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\demen\\Documents\\GitHub\\Desktop-Serializer-For-Node\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Dependency 'binding.gyp:#target' not found while trying to load target binding.gyp:desktop_serializer#target
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\demen\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\demen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\demen\Documents\GitHub\Desktop-Serializer-For-Node
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

**Comment by rvagg** [comment]
you're going to need to share your binding.gyp for this to be actionable.

**Comment by rvagg** [comment]
OK, if you've pasted this in as-is then your quote escaping is missing in the node-addon-api inclusions. You want to quote everything inside the [] but escape quote marks that get in the way between them.

Replace those two lines with exactly what's listed @ https://github.com/nodejs/node-addon-api/blob/master/doc/setup.md#installation-and-usage:

```
  'include_dirs': ["<!@(node -p \"require('node-addon-api').include\")"],
  'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
```
