### ISSUE TITLE
Unable to rebuild nodejieba on Node.js v10.16.3 (LTS)

### ISSUE THREAD

**Issue by binarykitchen** [nodejs/node-gyp#1869]
Just switched from Node.js v8.15.0 to v10.16.3. and am unable to rebuild `nodejieba` within my project. See Gist for full error by yarn https://gist.github.com/binarykitchen/8d3c235413b3dfdbe69e6cda77ae7ce2

* **Node Version**: 
Node.js v10.16.3
Yarn v1.17.3

* **Platform**: 
Darwin M3-2.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

* **Compiler**:
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* **Module**: 
nodejieba

The Gist says it all. But here one example of all those errors being thrown

```
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
```

**Comment by richardlau** [comment]
Those errors indicate you are using an out of date version of `nan`.
