### ISSUE TITLE
ImportError: cannot import name print_function

### ISSUE THREAD

**Issue by Messilimeng** [nodejs/node-gyp#1870]
PS D:\arcsoft> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Python27\python.exe"
gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v10.16.3/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v10.16.3/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.3/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v10.16.3/win-x64/node.lib
gyp info find VS using VS2017 (15.9.28307.812) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\limen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\arcsoft\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\limen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\limen\\AppData\\Local\\node-gyp\\Cache\\10.16.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\limen\\AppData\\Local\\node-gyp\\Cache\\10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\limen\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\limen\\AppData\\Local\\node-gyp\\Cache\\10.16.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\arcsoft',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\arcsoft\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\limen\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\Users\limen\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 7, in <module>
    from __future__ import print_function
ImportError: cannot import name print_function
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\limen\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\limen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\arcsoft
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

**Comment by cclauss** [comment]
Somewhere on your machine there is a Python < 2.6 that should be deleted.
https://docs.python.org/2/library/__future__.html

**Comment by Messilimeng** [comment]
@cclauss  i can not find anyother python version in my computer，and install anaconda is always say
like this 
![{E`UQ4OA(~K{32(7${_H 5Y](https://user-images.githubusercontent.com/12272166/64395210-020e4800-d08c-11e9-9255-e2bd6def21d7.png)

**Comment by Messilimeng** [comment]
get it

**Comment by cclauss** [comment]
What was the answer?

**Comment by Messilimeng** [comment]
@cclauss  before i installed the Tribon M3 software ，when i uninstall the software then all can work,
