### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by ktpx** [nodejs/node-gyp#1872]
Is it even possible to install this crap?

Never works.

**Comment by addaleax** [comment]
@ktpx Even if you need to vent, please remember that this project is governed by a [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md) and referring to other people’s software as “crap” is generally not appreciated. If you do need help getting something to work, feel free to post in https://github.com/nodejs/help/.

**Comment by ktpx** [comment]
Sorry, was a bad moment after hours of frustration.  :D
