### ISSUE TITLE
Handle migration away from Python 2 (sunsetting)

### ISSUE THREAD

**Issue by tracker1** [nodejs/node-gyp#1873]
Python 2 will no longer be supported in January 2020.  It would be a good idea to migrate to another process to support binary node modules that do not rely on Python 2.

https://www.python.org/doc/sunset-python-2/

**Comment by rvagg** [comment]
thanks @tracker1 this is a work in progress, slow, but it's happening, please review https://github.com/nodejs/node-gyp/issues?utf8=%E2%9C%93&q=python for the volumes of discussion and changes involved in this complex issue
