### ISSUE TITLE
That was an error when finding Win10 SDK Version 18362

### ISSUE THREAD

**Issue by ZhyMC** [nodejs/node-gyp#1876]
i read the source codes of node-gyp and how it find packages by powershell.
then i read getSDK().

found that vsinfos got string 'Microsoft.VisualStudio.Component.Windows10SDK.18362'
but on my machine,it has installed a version "Windows10SDK.18362.1".
"node-gyp configure" generated a config.gypi 
`   "msvs_windows_target_platform_version": "10.0.18362.0"
 `
it cause " visual studio 2019 " build failed:
`error MSB8036: The Windows SDK version 10.0.18362.0 was not found.`

hope to find the solution of this issue.

**Comment by ZhyMC** [comment]
see this https://raw.githubusercontent.com/mosserlee/PSTips/master/Functions/Get-InstalledSoftwares.ps1

and  "Get-InstalledSoftwares | ConvertTo-Json"

we can directly get the correct version number

**Comment by joaocgreis** [comment]
@ZhyMC currently only SDKs installed with Visual Studio are supported. SDKs installed independently don't work. I'd welcome a PR to add support, as long as they only get picked when they can be used to compile Desktop C++, to avoid errors when actually compiling.

However, I see that node-gyp picks the SDK that was installed with Visual Studio (that is actually the latest one), so it should work. Can you paste the output of `node-gyp rebuild --verbose` and confirm the SDK version 10.0.18362.0 is actually installed in Visual Studio Installer for the version that node-gyp picks?

**Comment by ZhyMC** [comment]
actually i install win10sdk 18362 through the 'Visual Studio Installer',and followings are the result of executing 'node-pre-gyp rebuild --verbose'
`C:\Users\zhymc\Desktop\face++\node_modules\mmap-object>node-pre-gyp rebuild --verbose
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\zhymc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'rebuild',
node-pre-gyp verb cli   '--verbose' ]
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.15.3 | win32 | x64
node-pre-gyp verb command rebuild []
node-pre-gyp verb command clean []
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\zhymc\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib\\mmap-object.node',
gyp verb cli   '--module_name=mmap-object',
gyp verb cli   '--module_path=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib',
gyp verb cli   '--napi_version=3',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v64' ]
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if the py launcher can be used to find Python 2
gyp verb find Python - executing "py.exe" to get Python 2 executable path
gyp verb find Python - "py.exe" is not in PATH or produced an error
gyp verb find Python checking if Python is C:\Python27\python.exe
gyp verb find Python - executing "C:\Python27\python.exe" to get version
gyp verb find Python - version is "2.7.16"
gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.15.3
gyp verb build dir attempting to create "build" dir: C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build
gyp verb build dir "build" dir needed to be created? C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2019 (16.2.29215.179) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v142
gyp verb find VS - found Windows SDK: 10.0.18362.0
gyp info find VS using VS2019 (16.2.29215.179) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\zhymc\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhymc\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhymc\\AppData\\Local\\node-gyp\\Cache\\10.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhymc\\AppData\\Local\\node-gyp\\Cache\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zhymc\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\zhymc\\AppData\\Local\\node-gyp\\Cache\\10.15.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\zhymc\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib\\mmap-object.node',
gyp verb cli   '--module_name=mmap-object',
gyp verb cli   '--module_path=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib',
gyp verb cli   '--napi_version=3',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v64' ]
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\zhymc\AppData\Local\node-gyp\Cache\10.15.3
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
生成启动时间为 2019/9/18 10:15:53。
节点 1 上的项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\binding.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|x64”。
项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\binding.sln”(1)正在节点 1 上生成“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\action_after_bui
ld.vcxproj.metaproj”(2) (默认目标)。
项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\action_after_build.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\zhymc\Desktop\face++\node_modules\mmap-objec
t\build\mmap-object.vcxproj”(3) (默认目标)。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version
10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and s
electing "Retarget solution". [C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\mmap-object.vcxproj]
已完成生成项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\mmap-object.vcxproj”(默认目标)的操作 - 失败。

已完成生成项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\action_after_build.vcxproj.metaproj”(默认目标)的操作 - 失败。

已完成生成项目“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\binding.sln”(默认目标)的操作 - 失败。


生成失败。

“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\binding.sln”(默认目标) (1) ->
“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\action_after_build.vcxproj.metaproj”(默认目标) (2) ->
“C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\mmap-object.vcxproj”(默认目标) (3) ->
(_CheckWindowsSDKInstalled 目标) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK versio
n 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and
 selecting "Retarget solution". [C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\build\mmap-object.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:05.42
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zhymc\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\zhymc\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--loglevel=verbose" "--module=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib\\mmap-object.node" "--module_name=mmap-object" "--module_path=C:\\Users\\zhymc\\Desktop\\face++\\node_modules\\mmap-object\\lib" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\zhymc\Desktop\face++\node_modules\mmap-object
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\nodejs\node.exe C:\Users\zhymc\node_modules\node-gyp\bin\node-gyp.js build --loglevel=verbose --module=C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\lib\mmap-object.node --module_name=mmap-object --module_path=C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\lib --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\zhymc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\zhymc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild" "--verbose"
node-pre-gyp ERR! cwd C:\Users\zhymc\Desktop\face++\node_modules\mmap-object
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\nodejs\node.exe C:\Users\zhymc\node_modules\node-gyp\bin\node-gyp.js build --loglevel=verbose --module=C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\lib\mmap-object.node --module_name=mmap-object --module_path=C:\Users\zhymc\Desktop\face++\node_modules\mmap-object\lib --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

C:\Users\zhymc\Desktop\face++\node_modules\mmap-object>`

**Comment by joaocgreis** [comment]
Node-gyp finds the SDK component, confirming it was installed with the Visual Studio Installer. Then MSBuild doesn't find it. I don't know what is happening there, perhaps a corrupted installation. Can you try reinstalling Visual Studio (or just the SDK)?

**Comment by ZhyMC** [comment]
maybe you are right,i searched information on msdn,and it is an visual studio installation problem.

**Comment by ZhyMC** [comment]
i uninstalled vs2019 vs and installed vs2017,then install sdk from vs installer and it worked
