### ISSUE TITLE
npm install mongojs : building bson c++ extension : gyp ERR!

### ISSUE THREAD

**Issue by Revlin** [nodejs/node-gyp#188]
I'm on Ubuntu 12.04 and I've built/installed node 0.8.18 from source.
When attempting to npm install mongojs (both with and without 'sudo'), I get:
# 

=                                                                              =
=  Attempting to build bson c++ extension                                      =
=   Windows: no build will be attempted as binaries are prepackaged            =
=   Unix: on failure the package will still install without the C++ extension  =
# =                                                                              =

node-gyp clean
node-gyp configure build
gyp http GET http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: EACCES, utime '/home/revlin/.node-gyp/0.8.18'
gyp ERR! System Linux 3.2.0-36-generic-pae
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/src/netentionjs2/node_modules/mongojs/node_modules/mongodb/node_modules/bson
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues
make: **\* [node_gyp] Error 7
child process exited with code 2

I didn't see any similar problems when I searched previous issues.

thx,
Rev

**Comment by Hunger-satisfied7** [comment]
@TooTallNate https://consular5.github.io/fmk2L4zLlUkgqFqbZgokO2uHMzUTfIdmmX2mZW8JI5uTAKH94cDlW2NLgVZWv/
