### ISSUE TITLE
Can't build with Visual Studio 2017 Express

### ISSUE THREAD

**Issue by eduardtudor21** [nodejs/node-gyp#1881]
* **Node Version**:  v10.16.3 - 6.10.3
* **Platform**: Windows 10
* **Compiler**:  MSBUILD 15.9.21.664 / CL 19.16.27027.1 for x64
* **Module**: node-rfc

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress"
gyp ERR! find VS - will only use this version
gyp ERR! find VS checking VS2017 (15.9.28307.423) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS looking for Visual Studio 2013
gyp ERR! find VS - not found
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
```

</details>

It looks like it can find the standard libraries but can't find the sdk?
I'm sure I have the sdks because I also have C++ programs that use windows api.

Note: I can't use the standalone vc++ build tools as it can't be used in enterprise when I don't have enterprise/pro visual studio license.

 Thanks in advance.

**Comment by joaocgreis** [comment]
I can reproduce.

Node-gyp looks for the component `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` because it is present when both the Toolset and the files MSBuild needs to use it are present. But the Express edition does not have this component. I'll see if a different combination of components can be used.
