### ISSUE TITLE
Python 2.7 EOL migration

### ISSUE THREAD

**Issue by scOwez** [nodejs/node-gyp#1883]
In the required dependencies of the [README](https://github.com/nodejs/node-gyp/blob/master/README.md) for `node-gyp`, it states Python 2.7.x being **required**. Here's a screenshot of what I mean:

![image](https://user-images.githubusercontent.com/30081702/65365598-9216ca80-dc12-11e9-9aa0-e34302f59ad7.png)

This is the same for the Mac build, not just *nix.

As the Python 2.7 EOL is coming soon (**[PEP for EOL](https://www.python.org/dev/peps/pep-0373/)**, [countdown](https://pythonclock.org/)), this should be upgraded to ideally 3.7.

**Comment by rvagg** [comment]
It's a complicated work in progress but is underway. Please perform a basic search of the issue tracker before opening new issues of this nature in future.
