### ISSUE TITLE
Completion callback never invoked!

### ISSUE THREAD

**Issue by leonschwanitz** [nodejs/node-gyp#1887]
`C:\Users\Leon\Desktop\quickstart\addon>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" install )  else (node "C:\Users\Leon\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" install )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | win32 | x64
gyp http GET https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Leon\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install"
gyp ERR! cwd C:\Users\Leon\Desktop\quickstart\addon
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>`

**Comment by yansuofengyue** [comment]
I have the same problem.

**Comment by mmdevries** [comment]
We have the same problem on Linux:

gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@8.16.0 | linux | x64
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v8.16.0/node-v8.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.16.0/node-v8.16.0-headers.tar.gz
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/kees/workspace/konijn/node_modules/spook
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**Comment by goooseman** [comment]
Me either.

MacOS 10.14.5
node v10.11
node-gyp v5.0.3

```
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.11.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://nodejs.org/download/release/v10.11.0/node-v10.11.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.11.0/node-v10.11.0-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/goooseman/.fnm/node-versions/v10.11.0/installation/bin/node" "/var/folders/4n/2d4l1g210q92n_mk4csqjjs40000gn/T/fnm-shell-3525402/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/goooseman/dev/boodkaProjects/boodka-desktop
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

**Comment by goooseman** [comment]
The same issue with Node v12.9.0

```
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.9.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://nodejs.org/download/release/v12.9.0/node-v12.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.9.0/node-v12.9.0-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/goooseman/.fnm/node-versions/v12.9.0/installation/bin/node" "/Users/goooseman/.npm/_npx/11089/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/xxx
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

**Comment by lissyx** [comment]
Same with NodeJS v8.16.1, node-pre-gyp@0.13.0 and node-gyp@4.0.0

**Comment by lissyx** [comment]
> Same with NodeJS v8.16.1, node-pre-gyp@0.13.0 and node-gyp@4.0.0
> 
> Repro on linux, windows and macOS @cclauss

And this magically started to work again for me. Bogus server ?

**Comment by langsz** [comment]
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | ia32
gyp info find Python using Python version 2.7.11 found at "F:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v5.0.1/node-v5.0.1-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v5.0.1/node-v5.0.1-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\nodejs\\node.exe" 
"\\PXTool\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.1" "--arch=ia32" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd \node_modules\@serialport\bindings
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**Comment by leonschwanitz** [comment]
Its working now. Could really have been a server problem.

**Comment by mmarchini** [comment]
The issue was caused by `node-tar` and `minipass`. See https://github.com/npm/node-tar/issues/232 and https://github.com/isaacs/minipass/issues/9 for more context. Upgrading these dependencies to the latest version should fix the issue.
