### ISSUE TITLE
node-gyp does not run seemlessly across platforms

### ISSUE THREAD

**Issue by incomingstick** [nodejs/node-gyp#1897]
* **Linux Node Version**: node v12.10.0 | npm v6.11.3 | node-gyp v5.0.4
* **Windows Node Version**: node v12.10.0 | npm v6.11.3 | node-gyp v5.0.4
* **Linux Platform Info**: Linux arch 5.3.1-arch1-1-ARCH SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
* **Windows Platform Info**: 
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
System Type:               x64-based PC
```
* **Linux Compiler**: gcc version 9.1.0 (GCC)
* **Windows Compiler**: MSVC 19.21.27702.2
* **Module**: openrpg-libs

<details><summary>Verbose output (from npm or node-gyp):</summary>

Here is the binding.gyp:
```
{
  "targets": [
    {
      'target_name': 'prebuild',
      'type': 'none',
      'actions': [
        {
          'action_name': 'build_core',
          'message': 'Building ORPG Core...',
          'inputs': [''],
          'outputs': [''],
          "action": [
            "node run build"
          ]
        },
      ],
    },
    {
      "target_name": "roll",
      "include_dirs": [
        "include"
      ],
      "link_settings": {
        "conditions": [
          ["OS=='linux'", {
            "libraries": [
              "<(module_root_dir)/build/lib/openrpg/libroll-parser.so"
            ]
          }],
          ["OS=='win'", {
            "libraries": [
              "<(module_root_dir)/build/lib/Release/roll-parser.lib",
              "<(module_root_dir)/build/lib/Release/roll-parser.exp"
            ]
          }]
        ],
      },
      "sources": [ 
        "<(module_root_dir)/wrappers/roll/rollAddon.cpp",
        "<(module_root_dir)/wrappers/roll/rollWrapper.cpp"
      ]
    }
  ]
}
```

Output of npm install (error number 1):
```
> openrpg-libs@0.0.10 install /home/user/Documents/projects/OpenRPG
> node-gyp configure build --verbose

gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/user/.nvm/versions/node/v12.10.0/bin/node',
gyp verb cli   '/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   'build',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | linux | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/home/user/bin/python"
gyp verb find Python - executing "/home/user/bin/python" to get version
gyp verb find Python - version is "2.7.16"
gyp info find Python using Python version 2.7.16 found at "/home/user/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 12.10.0
gyp verb command install [ '12.10.0' ]
gyp verb install input version string "12.10.0"
gyp verb install installing version: 12.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.10.0
gyp verb build dir attempting to create "build" dir: /home/user/Documents/projects/OpenRPG/build
gyp verb build dir "build" dir needed to be created? null
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/user/Documents/projects/OpenRPG/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/user/Documents/projects/OpenRPG/config.gypi
gyp verb common.gypi checking for gypi file: /home/user/Documents/projects/OpenRPG/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /home/user/bin/python
gyp info spawn args [
gyp info spawn args   '/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Documents/projects/OpenRPG/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/12.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/12.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/12.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Documents/projects/OpenRPG',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/user/.cache/node-gyp/12.10.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/Documents/projects/OpenRPG/build'
  LD_LIBRARY_PATH=/home/user/Documents/projects/OpenRPG/build/Release/lib.host:/home/user/Documents/projects/OpenRPG/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; "node run build"
/bin/sh: node run build: command not found
make: *** [prebuild.target.mk:13: .] Error 127
make: Leaving directory '/home/user/Documents/projects/OpenRPG/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.1-arch1-1-ARCH
gyp ERR! command "/home/user/.nvm/versions/node/v12.10.0/bin/node" "/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--verbose"
gyp ERR! cwd /home/user/Documents/projects/OpenRPG
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openrpg-libs@0.0.10 install: `node-gyp configure build --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openrpg-libs@0.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Output of npm install (error number 2):
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/bin/sh: ./Release/.deps/..d: No such file or directory
make: *** [prebuild.target.mk:13: .] Error 1
make: Leaving directory '/home/user/Documents/projects/OpenRPG/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.1-arch1-1-ARCH
gyp ERR! command "/home/user/.nvm/versions/node/v12.10.0/bin/node" "/home/user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--verbose"
gyp ERR! cwd /home/user/Documents/projects/OpenRPG
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openrpg-libs@0.0.10 install: `node-gyp configure build --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openrpg-libs@0.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
</details>

edit2: I apologize if the title does not accurately explain the issue, but honestly I don't know what title would..

So to explain the above issue. I am attempting to create a package that uses node-gyp to wrap some C++ libraries into a node module. On Windows, the above configuration works without much of a hitch. The build output on Windows warns of a cyclical error (I have no clue why...) but compiles fine without any errors. On Linux, this build fails with the above error output (error number 1). The main error here is `/bin/sh: node run build: command not found`. This issue can be fixed (sort of) by changing the binding.gyp prebuild action from `"action": ["node run build"]` to directly just preform the build script via `"action": ["node", "build.js"]`. It is important to point out that changing it to  `"action": ["node build.js"]` **does not work either**. On Linux it appears that the action line needs each individual string to be its own action, and it cat's it all together, whereas on Windows, it can take each full command as its own action in the array. Making this change on Linux makes the cyclical error **from Windows (???)** prevalent, as it just enters an endless make loop, so now the full command becomes  `"action": ["node", "build.js", "rebuild"]` (rebuild is a cla that build.js take that will clear the `build/` directory, and.. well.. rebuild.). The build.js compilation succeeds, but the node-gyp then fails with the above error number 2. I have no clue what this error means, nor how to go about fixing it. It is likely due to the fact that we nuke the build folder as a part of the prebuild action, but without that, it just sits in and endless loop. Making this same change also fails on Windows, but for a completely different reason. On Windows it seems to pass "rebuild" to build.js as `"..\\rebuild"` instead for some reason... this means that the same changes made on Linux completely breaks the Windows build as well.

Clearly things do not seem to work the same way with node-gyp across platforms. This discrepancy can be solved by using the conditions array, like I do with the `roll` target. I am not opposed to this, but even accounting for the platform changes, it still does not want to run properly on Linux.

My end goal is to run this build.js script as a part of the compilation process, as the node module being built relies on dynamic libraries built from that script. The script needs to be run as a part of node-gyp instead of being a node preinstall script, because electron-rebuild uses the binding.gyp to recompile, but nukes the build folder first, meaning the libs that are built in the initial pass get nuked with it. The means that using the node preinstall script is simply not an option.

Any insight into my issues would be greatly appreciated.

edit: formatting fixes

**Comment by cclauss** [comment]
@incomingstick Your review please?

**Comment by incomingstick** [comment]
@cclauss I'm sorry, I don't understand the question. Did I forget to add something in my issue?

Perhaps this will help? I will try to summarize my issues here:
1) on Windows you can run an action `"action": ["node build.js rebuild"]` but on Linux it has to be formatted as "action": ["node", "build.js", "rebuild"], and with longer commands this can get extremely excessive. On Windows the same change creates some odd behavior where it seems to pass "rebuild" to build.js as "..\\rebuild".
2) running a pre-build script as a target somehow causes a cyclical make build causing it to infinitely recurs on itself only on Linux, though Windows will warn about it. It builds without recursion on Windows.

At the end of the day I am looking to know the proper way to run a build script before node-gyp builds its targets.

My repo in quesiton can be found [here](https://github.com/incomingstick/OpenRPG/tree/npm-integration).
It can be used as an npm package [here](https://www.npmjs.com/settings/incomingstick/packages).

I hope this helps!

**Comment by rvagg** [comment]
For anyone else looking at this, the code in question that might help this make sense is https://github.com/incomingstick/OpenRPG/blob/8692600a86163f1d6700c66b6abbc3f89fd11cfd/binding.gyp#L6

I don't think I've never used GYP actions and I don't see many projects doing so either so perhaps this functionality just doesn't get enough of a workout. We can see if anyone else watching this repo has an idea of what might be going on but I suspect your best bet might be to try and debug this yourself by poking around in the Python and watching what it does to your input.

There's also a bunch of changes over in https://github.com/refack/GYP3 what we haven't picked up here that may impact this, you could try swapping out the gyp in node-gyp here with that one to see if it makes a difference for your usecase at all. That's just a wild guess and might be one of the things I'd try as I stumbled around blindly in the Python.

Although, tbh, I would personally rely much less on GYP logic than on what could be achieved with npm scripts, raw JavaScript or some other utility that already exists, like https://github.com/prebuild/prebuild (although I don't know if that achieves what you're trying to do).

**Comment by incomingstick** [comment]
I have switched to using cmake-js instead of node-gyp.

Thank you for your time.
