### ISSUE TITLE
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by GanZhiXiong** [nodejs/node-gyp#1898]
Windows PowerShell run "npm install --build-from-source" 
An error occurred, as shown below

![image](https://user-images.githubusercontent.com/27394631/65841185-6dc59700-e352-11e9-8436-465cbd5d6b1f.png)

**Comment by sscots** [comment]
+1

**Comment by pdrArantes** [comment]
+1

**Comment by joaocgreis** [comment]
@GanZhiXiong it looks like node-gyp is working well, the error comes from Visual Studio. Please try the solutions listed in https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1106?view=vs-2019

I'll close this issue since it does not appear to be a node-gyp issue, but feel free to provide more information if you believe otherwise. If this keeps being an issue for you, please make sure you follow all the instructions in https://github.com/node-hid/node-hid and report the issue there.

**Comment by GanZhiXiong** [comment]
I solved this problem by performing "npm install --global --production windows-build-tools" on Win10 without visual studio installed, which I think has something to do with installing vs2019。

> But before I installed another vs2019 win10 on a long time to solve this problem, because there is no record halfway I also forgot my specific operation steps

**Comment by boystray** [comment]
node.lib in windows has bug
i delete node.lib and download node.lib from web 
and work fine

**Comment by GPudgima** [comment]
@boystray 

> node.lib in windows has bug
> i delete node.lib and download node.lib from web
> and work fine

Please explain, as I'm having the same issue.

**Comment by sebastianoscarlopez** [comment]
> I solved this problem by performing "npm install --global --production windows-build-tools" on Win10 without visual studio installed, which I think has something to do with installing vs2019。
> 
> > But before I installed another vs2019 win10 on a long time to solve this problem, because there is no record halfway I also forgot my specific operation steps

Before we must open console with adminitrator privilege

**Comment by IgorGomesFATEC** [comment]
> I solved this problem by performing "npm install --global --production windows-build-tools" on Win10 without visual studio installed, which I think has something to do with installing vs2019。
> 
> > But before I installed another vs2019 win10 on a long time to solve this problem, because there is no record halfway I also forgot my specific operation steps

GOD

**Comment by WinterSpringTiger** [comment]
How long does it take to perform "npm install --global --production windows-build-tools" GanZhiXiong?

**Comment by cclauss** [comment]
https://www.npmjs.com/package/windows-build-tools should ___not___ be used because it installs Python 2 which died on 1/1/2020 (608 days ago) and is no longer supported by node-gyp.
