### ISSUE TITLE
The 'tar' node package needs to be updated

### ISSUE THREAD

**Issue by jkim7** [nodejs/node-gyp#1918]
Hi

Older versions of tar has a file called cb-never-called-1.0.1.tgz, and it triggers a warning on virus scans, could you guys upgrade to a newer version of tar to remove it?

thanks

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by rvagg** [comment]
Please use a newer version of node-gyp, or npm if you are using it from there. This should already have been resolved.

**Comment by rvagg** [comment]
OK, I take that back. I don't know about the specific issue you're pointing out but it looks like a v5 of node-tar has been released. We should look at that.

**Comment by rvagg** [comment]
It looks like this was resolved in node-tar v3, https://github.com/npm/node-tar/pull/72#issuecomment-300347778, we are on to v4 and I can't find the file in the package. So, indeed, upgrade your node-gyp or npm and it should go away. I'll deal with a node-tar upgrade separately.
