### ISSUE TITLE
Environment Variables not working

### ISSUE THREAD

**Issue by joeferner** [nodejs/node-gyp#192]
I've had a couple user report this issue with my project on Ubuntu. In my bindings file I'm using "$(JAVA_HOME)" to pull in the JAVA_HOME environment variable. One user ran node-gyp using the following without success.

```
$ export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
$ npm install java
```

I'm unable to duplicate the issue on my Ubuntu machine.

Here is a link to the issue on my project: https://github.com/nearinfinity/node-java/issues/35

**Comment by tk120404** [comment]
@joeferner please close this issue
