### ISSUE TITLE
node-gyp configure

### ISSUE THREAD

**Issue by Li0nh3art** [nodejs/node-gyp#1928]
I am new to coding and when attempting to setup for this tutorial I receive the following error when attempting to configure node-gyp
![node-gyperror](https://user-images.githubusercontent.com/56652334/66948468-c4a1c080-f022-11e9-9430-fabcb7fc906a.jpg)

**Comment by rvagg** [comment]
hi @Li0nh3art, what tutorial are you following? This is a pretty advanced tool to jump in and learn. You are missing a binding.gyp file in the directory you're running this. You need to make one to suit your addon C++ files.

**Comment by Li0nh3art** [comment]
I am following the tutorial in the following article: https://blog.risingstack.com/node-js-windows-10-tutorial/ which has a link to a node.js native addon build tool here on Github. I try and follow the readme and when I get to the configure step is when I get errors. Someone suggested the article as a way to learn how to code as a beginner.

**Comment by rvagg** [comment]
@Li0nh3art ah ok, well I think for the purpose of that tutorial you can just read the section in the README titled "On Windows": https://github.com/nodejs/node-gyp#on-windows, and it's thankfully a bit simpler now than it used to be when that Risingstack tutorial was written. You just need to get the latest Python from the Microsoft Store and install the windows build tools (skipping the whole MSVS stuff in the Risingstack tutorial) with `npm install --global --production windows-build-tools`. Once you've done that, jump back to learning Node & npm and hopefully you'll be able to ignore the node-gyp and compile steps. Some addons that you install as dependencies will need to be compiled but hopefully that will be painless and automatic and you can ignore it all.

I'm going to close this but please let me know if any of this is confusing or you're struggling to move forward.
