### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by mcandre** [nodejs/node-gyp#193]
Please add support for Python 3.

Some tools require Python 2, some require Python 3, and this makes it really hard to setup a build environment. Better to support both when possible.

**Comment by bricss** [comment]
https://github.com/saghul/gyn

**Comment by unbornchikken** [comment]
coz da petition didnt help: https://github.com/unbornchikken/cmake-js

**Comment by untitaker** [comment]
Please try to use `env python2`. The current version of `node-gyp` completely breaks on distributions that have their default Python binary set to Python 3.

**Comment by Demurgos** [comment]
Looks like they are working on it.

https://codereview.chromium.org/1454433002

**Comment by bendavis78** [comment]
Is there any reason why node-gyp can't autodetect the location of python2 and use that to run gyp?

**Comment by bnoordhuis** [comment]
@bendavis78 It does, it looks for `python2` first before falling back to `python`.  On Windows, it also looks in well-known locations and consults the python launcher when available.

**Comment by mikemaccana** [comment]
This just hit me too trying node on Windows for the first time (Windows that I, have been using node since 0.6). npm install asked for Python, I installed Python. Then it complains about python 3.

**Comment by Justinfront** [comment]
Please reopen, this still seems to be a problem and desirable.
Error: Python executable "/opt/local/bin/python" is v3.4.5, which is not supported by gyp

**Comment by Justinfront** [comment]
I hate setting stuff up!! I really don't want to remove 3.4.5 as use for haxe and perhaps blender but running two versions of python with brew seems not so simple.
https://www.linkedin.com/pulse/installing-python-via-homebrew-macos-sierra-1012-developer-brink

**Comment by Justinfront** [comment]
"gyp project used by the Chromium team and takes away the pain of dealing with the various differences in build platforms" mm seems not quite :)

**Comment by arthurcolle** [comment]
this is so annoying

**Comment by refack** [comment]
You're all missing the point 😉
The real goal is to remove the dependency on python completely #960

**Comment by CamiloMM** [comment]
Imagine a Perl package that depends on VB.NET code. It's bonkers how it got this far.On Apr 23, 2017 00:06, Refael Ackermann <notifications@github.com> wrote:You're all missing the point 😉
The real goal is to remove the dependency on python completely #960

**Comment by maxkoryukov** [comment]
@refack, we all missing the point? Lets look at things globally: _#960 is about coding for tiny **PYTHON** interpreter in **JAVASCRIPT**_ ;)

```
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░▄▄███▄▄▄░▄▄██▄░░░░░░░
░░░░░░░░░██▀███████████████▀▀▄█░░░░░░
░░░░░░░░█▀▄▀▀▄██████████████▄░░█░░░░░
░░░░░░░█▀▀░▄██████████████▄█▀░░▀▄░░░░
░░░░░▄▀░░░▀▀▄████████████████▄░░░█░░░
░░░░░▀░░░░▄███▀░░███▄████░████░░░░▀▄░
░░░▄▀░░░░▄████░░▀▀░▀░░░░░░██░▀▄░░░░▀▄
░▄▀░░░░░▄▀▀██▀░░░░░▄░░▀▄░░██░░░▀▄░░░░
█░░░░░█▀░░░██▄░░░░░▀▀█▀░░░█░░░░░░█░░░
█░░░▄▀░░░░░░██░░░░░▀██▀░░█▀▄░░░░░░▀▀▀
▀▀▀▀░▄▄▄▄▄▄▀▀░█░░░░░░░░░▄█░░█▀▀▀▀▀█░░
░░░░█░░░▀▀░░░░░░▀▄░░░▄▄██░░░█░░░░░▀▄░
░░░░█░░░░░░░░░░░░█▄▀▀▀▀▀█░░░█░░░░░░█░
░░░░▀░░░░░░░░░░░░░▀░░░░▀░░░░▀░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
```

Of course, Node.JS is not the same as javascript.

**Comment by refack** [comment]
@maxkoryukov eventually https://github.com/indutny/gyp.js was written to run on node.js, with a port to C for bootstrapping https://github.com/indutny/dukgyp

**Comment by er3456qi** [comment]
Hey, it is 2017 now,  does node-gyp support python 3 ? NO!

**Comment by untitaker** [comment]
Curb your entitlement.

On 9 September 2017 14:56:14 GMT+02:00, Wnbot <notifications@github.com> wrote:
>Hey, it is 2017 now,  does node-gyp support python 3 ? NO!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nodejs/node-gyp/issues/193#issuecomment-328275700

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SatishMHiremath** [comment]
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @latest

angular client project folder path>npm install -g node-gyp

**Comment by fengerzh** [comment]
It's 2018, still Python 2. 😕

**Comment by banrieen** [comment]
npm install -g appium on win10 pro 64bit with Python3.6.3 and Python3.6.4 : 

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lizhen\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lizhen\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\lizhen\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lizhen\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lizhen\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 (node_modules\appium\node_modules\heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1  

From https://github.com/haraka/Haraka/issues/1721 wzup  tips:
This is what I did to solve the issue. From here https://github.com/nodejs/node-gyp

**Comment by dpotier** [comment]
I was having this issue installing `wdio-mocha-framework` with `npm` and I noticed in the error logs node apparently has a flag to target which python. So if you have both python 2 and python 3 installed on your machine you can do:

`npm install wdio-mocha-framework --save-dev --python=python2.7` 

And it works.

I get the point is that there shouldn't be this dependency in TYOOL 2018 but I thought I would leave this work around here since it would have helped me to see it.

[Source: switching between python versions stackoverflow](https://stackoverflow.com/questions/20454199/how-to-use-a-different-version-of-python-during-npm-install)

**Comment by NetOperatorWibby** [comment]
_[Copied from another issue](https://github.com/nodejs/node-gyp/issues/1337#issuecomment-375927595 "Success!"), in case this helps someone lurking in 2019 and this still isn't fixed_

This assumes you're using ZSH and are on macOS.

```bash
xcode-select --install

brew install python@2
echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.zshrc
npm config set python python2.7
```

**Comment by mtobeiyf** [comment]
For Windows users: 
```shell
$ npm install --global --production windows-build-tools
```
This will install windows build tools including python 2.7 and vs tools in your user directory. Then

```shell
$ npm config set python C:\Users\USERNAME\.windows-build-tools\python27\python.exe
```
or you may select your installed python 2.7
I tried setting env variables, didn't help. Use `npm config` solved it.

**Comment by joshas** [comment]
There are signals that gyp project _might_ land Python 3 patches sometime: https://groups.google.com/forum/#!topic/gyp-developer/U66xtisrYRM . As far as I understand most of the work is done, both Python 2 and Python 3 are supported, but some tests are failing on Python 3.
With Python 2 EOL approaching, it would be about time to fix this issue. node-gyp is quite popular with still increasing download count and 422 dependent packages.

**Comment by aljones15** [comment]
hope they fix it soon most distros no longer ship with python 2 out of the box anymore.

**Comment by bricss** [comment]
I'm afraid that no one in long-term period of time is gonna fix it.
In 2016, `GYP` was abandoned and replaced with `GN` by Google in Chromium & V8 projects. So the best solutions may be to move towards `GN` in sync with Chromium team, or switched to use [CMake](https://github.com/cmake-js/cmake-js) instead.

**Comment by lolzcalvin** [comment]
@bricss many thanks for the CMake suggestion!

**Comment by reebr** [comment]
Still using Python 2?

**Comment by virgo47** [comment]
When I unknowingly upgrade Node LTS, going from 8 to 10, and my `node-sass` binding is unusable (again) and I want to `rebuild node-sass` and get to the message that Python at `some/existing/path/to/python.exe` doesn't exist (with "gyp:" line prefix)... which leads me here... I kinda lost the hope for node/npm ecosystem. How many languages and platforms do I actually need to build an Angular application? (Sure, I should watch my versions, but still...)

**Comment by techdragon** [comment]
Hey so now that GYP is fixed. - https://bugs.chromium.org/p/gyp/issues/detail?id=36
When do we get this re-opened and fixed properly? @TooTallNate - (tagging you because you were the one that closed this originally.)

**Comment by AlexandraBryantKS** [comment]
If we want to keep up with the future (not just updated python) should we just abandon node-gyp in favor of the suggestions from @bricss?

**Comment by rvagg** [comment]
Related https://github.com/nodejs/build/issues/1631#issuecomment-448059025 (general thoughts on python 2/3 pain).

For addon authors, CMake isn't a terrible idea, you should consider it at least. The way node-gyp is integrated into Node makes it convenient for fetching various variables about the build being compiled against, but this isn't strictly essential and if you can achieve it with a better supported tool then that might be a good idea.

At the moment we just don't have a good strategy for the future of GYP and our reliance on it. Maybe that'll come one day, but it's going to need some folks to propose and push something new.

**Comment by stochastic-thread** [comment]
some say they'll never update

**Comment by ashb** [comment]
https://pythonclock.org/

**Comment by mcandre** [comment]
With the rise of WASM do we really need to support native libraries in Node projects any longer

**Comment by JamesMGreene** [comment]
@mcandre I'm no WAsm expert but, as I understand it, WebAssembly modules are sandboxed in a way that many existing native modules could not function within. 🔒 

Furthermore, there is a large collection of existing native modules that would either need to be converted or else cease to be officially supported. 😬

**Comment by VergLsm** [comment]
It's 2019-5-19, still Python 2.

**Comment by osljw** [comment]
Wow, It's been six years.

**Comment by ORESoftware** [comment]
Why not just ditch Python? Python sucks anyway.

**Comment by shirshak55** [comment]
haha :( 😂 😆 

People still use python2... :( python2 should have been removed from universe earlier so we don't have to face this problem :/

**Comment by devinbost** [comment]
What is the block here? There's a tool for AUTOMATED migration to Python 3: https://docs.python.org/2/library/2to3.html
It's part of the core Python library itself!

**Comment by filips123** [comment]
@devinbost Unfortunately, that tool only migrates some parts of the code. Some bigger breaking changes then still need to be fixed manually.

**Comment by kumarharsh** [comment]
Hold your horses! It seems like something is afoot: https://github.com/nodejs/node-gyp/commit/66ad30577594a37b08939948db1d4f1018d85335

**Comment by alexdevero** [comment]
@kumarharsh Now way 🤞!

**Comment by cclauss** [comment]
The Python 3 tests are currently run in __allow_failures__ mode: https://travis-ci.com/nodejs/node-gyp

It we can get those test to be green and drop the __allow_failures__ mode then we can 🚀 🎉 🍾

**Comment by shirshak55** [comment]
Finally after 6 years :)

**Comment by sbrl** [comment]
and not a moment too soon.

Warning: Python 2 will be retired on 1st January 2020: https://pythonclock.org/

**Comment by gluons** [comment]
[Time to shed Python 2](https://www.ncsc.gov.uk/blog-post/time-to-shed-python-2) by UK The National Cyber Security Centre

**Comment by ucodelukas** [comment]
kill py2

**Comment by zabiksandbox** [comment]
2024, still here.

**Comment by refack** [comment]
The ~node.js~ OpenJS Foundation has explicitly chosen other priorities over this. Please voice you complaint to them.
https://projects.propublica.org/nonprofits/organizations/471491876/202313179349304446/full

**Comment by mcandre** [comment]
A notable alternative is to use Go code rather than Python. Go dramatically reduces the need for native C/C++ code in the first place. And Go has builtin support for FFI via cgo.
