### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by MyriamCounilh** [nodejs/node-gyp#1930]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by rvagg** [comment]
"what's a pirate's favourite letter of the alphabet"
