### ISSUE TITLE
Remove Node.js 6 support 

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-gyp#1945]
Since Node.js is not support anymore. It's maybe good to remove related code and test.

**Comment by rvagg** [comment]
PR would be good.

This would be good to do in 6, or 7 (not planned yet but might be something we do in time for Node 14), but we should probably be more careful with 5, for people who are stuck.

**Comment by richardlau** [comment]
If it's in a semver-major I'd be okay dropping Node.js 8 support too.

**Comment by codler** [comment]
Node js 8 is only supported untill 2019-12-31, so might be good to drop node 8 also
