### ISSUE TITLE
node-gyp configure uncaught exception 

### ISSUE THREAD

**Issue by phantasmicmeans** [nodejs/node-gyp#1949]
**OS**
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial

**>> node-gyp configure**                          
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@4.2.6 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at exports.runInThisContext (vm.js:53:16)
gyp ERR! stack     at Module._compile (module.js:374:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! stack     at Module.load (module.js:344:32)
gyp ERR! stack     at Function.Module._load (module.js:301:12)
gyp ERR! stack     at Module.require (module.js:354:17)
gyp ERR! stack     at require (internal/module.js:12:17)
**gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/configure.js:12:18)**
gyp ERR! stack     at Module._compile (module.js:410:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /home/sangmin/test
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v6.0.0
**gyp ERR! This is a bug in `node-gyp`.**
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**-> /usr/local/lib/node_modules/node-gyp/lib/configure.js:12:18**
1. 'use strict'
2. 
3. const fs = require('graceful-fs')
4. const path = require('path')
5. const log = require('npmlog')
6. const os = require('os')
7. const mkdirp = require('mkdirp')
8. const processRelease = require('./process-release')
9. const win = process.platform === 'win32'
10. const findNodeDirectory = require('./find-node-directory')
11. const msgFormat = require('util').format
12. var findPython = require('./find-python')
13. if (win) {
14.   var findVisualStudio = require('./find-visualstudio')
15. }

**>> node-gyp configure --python /usr/bin/python3**
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@4.2.6 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at exports.runInThisContext (vm.js:53:16)
gyp ERR! stack     at Module._compile (module.js:374:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! stack     at Module.load (module.js:344:32)
gyp ERR! stack     at Function.Module._load (module.js:301:12)
gyp ERR! stack     at Module.require (module.js:354:17)
gyp ERR! stack     at require (internal/module.js:12:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/configure.js:12:18)
gyp ERR! stack     at Module._compile (module.js:410:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! System Linux 4.15.0-66-generic
**gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "configure" "--python" "/usr/bin/python3"**
gyp ERR! cwd /home/sangmin/Node-Example/addon-example/Node-Addon-cpp
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v6.0.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**python2.7, python3.5, gcc5.4.0 already installed properly..
Is there any reference that I can use?
thank you**

**Comment by richardlau** [comment]
Node.js 4 is too old to run node-gyp 6. You need to be using at least Node.js 6 and ideally Node.js 10 (since Node.js 6 is no longer supported and support for Node.js 8 will end at the end of this year).

**Comment by phantasmicmeans** [comment]
thank you, solved it now !
