### ISSUE TITLE
Automatically check for tool dependencies before installing

### ISSUE THREAD

**Issue by mcandre** [nodejs/node-gyp#195]
Could node-gyp check for Python v2, `make`, and `gcc`/`cl` before installing? This would clear up a lot of confusion.

If `gcc`/`cl` are not found, perhaps node-gyp could report simple messages like:

> Python 3 found, but Python 2 is required for node-gyp. Please install Python 2.
> 
> make not found (either make or nmake). Please install build-essential (Unix), or MinGW/Visual Studio (Windows).
> 
> C compiler not found (either gcc or cl). Please install build-essential (Unix), or MinGW/Visual Studio (Windows).

**Comment by Emasoft** [comment]
Node-gyp should not only report a message, but it should automatically download and install the dependencies.

**Comment by rvagg** [comment]
closing due to staleness, I think a lot of work has been done on this since 2013 anyway
