### ISSUE TITLE
Error in build npm install node-sass

### ISSUE THREAD

**Issue by lucassantosTI** [nodejs/node-gyp#1960]
I'm getting the following error message when trying to run my application's npm install, which uses the node-sass module which in turn uses node-gyp,

```
> node-sass@4.12.0 postinstall C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.0.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Cliente\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Cliente\.windows-build-tools\python27\python.exe C:\Users\Cliente\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\Cliente\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 13.0.1
gyp verb command install [ '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 13.0.1
gyp verb build dir attempting to create "build" dir: C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Cliente\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cliente\\.node-gyp\\13.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Cliente\\.node-gyp\\13.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Cliente\\.node-gyp\\13.0.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Cliente\.node-gyp\13.0.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Cliente\\source\\repos\\Integracao\\Organiza.Portal.Web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Cliente\source\repos\Integracao\Organiza.Portal.Web\node_modules\node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
```

**Comment by hulucc** [comment]
same here.

**Comment by richardlau** [comment]
Support for Visual Studio 2019 was [added in node-gyp v5.0.0](https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v500-2019-06-13) by https://github.com/nodejs/node-gyp/pull/1762. It looks like node-sass would need to update the version of node-gyp it depends on: https://github.com/sass/node-sass/blob/fbc9ff5abc72d9bc22a3b0bc9fa902fc46c980f7/package.json#L67

**Comment by hulucc** [comment]
I resolved by running the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd.bat" before npm install

**Comment by asolopovas** [comment]
same here. It doesn't seem to work with node 13

**Comment by cclauss** [comment]
> node-gyp@3.8.0

vs. https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md

**Comment by pleongomez** [comment]
Hi, I get the same error on a azure pipeline build using a yarn task.

**Comment by wildlifechorus** [comment]
This is breaking my continuous integration pipeline.

**Comment by pleongomez** [comment]
> This is breaking my continuous integration pipeline.

It calm me down that I'm not the only one ;)

**Comment by cclauss** [comment]
Please publish:
* node-gyp@???
* node@???
* Microsoft Visual Studio@???
* Python@???

**Comment by richardlau** [comment]
Closing as this isn't an issue with node-gyp and needs to be taken up with node-sass. node-gyp 5 (or 6) is required for Visual Studio 2019 support.

**Comment by pleongomez** [comment]
> This is breaking my continuous integration pipeline.

I fixed this problem adding to the build phase a command line task forcing to install a specific version of node.

`npm install -g node@8.12.0`

**Comment by shopOFF** [comment]
Same here, does some one have a working solution?

**Comment by martijintro** [comment]
Similar problem here, our project was created by Angular 7.0.5, now we use the current Version 8.3.23.

No matter what i do, each npm cli command leads to the same result! The mode-sass C/C++ build that fails...

I also installed the build tools (python etc.) - does not work.

That issue made me INSANE, i'm working since days on it but there seems to be NO solution.

(Maybe setup the whole source code by a new Angular 8.3.23 project??!?)

**Comment by rvagg** [comment]
Not much we can do about Angular or node-sass here, please take it to their repos.

I appreciate the need for catharsis, but this is not an ideal place for it.

**Comment by martijintro** [comment]
OK, thx.

"I appreciate the need for catharsis, but this is not an ideal place for it."

...that sounds really interesting!! ;-)

**Comment by AndreKelling** [comment]
node-sass has min requirements on the node version itself. 
see here: https://www.npmjs.com/package/node-sass

**Comment by martijintro** [comment]
ok thx

**Comment by martijintro** [comment]
The only one (quick?) solution was to downgrade to the latest 10.x version. But is there a solution, i can't always install and uninstall different node versions.

**Comment by umairisrar** [comment]
> The only one (quick?) solution was to downgrade to the latest 10.x version. But is there a solution, i can't always install and uninstall different node versions.

Install NVM on your system it will list down all your installed node version in console by using "nvm llist" command and you can switch to your node version when needed by this command "nvm use NODE_VERSION"

**Comment by martijintro** [comment]
ok thx

**Comment by archywillhe** [comment]
hmm getting this though on the right version of node

**Comment by jmar83** [comment]
thank you for your information.

**Comment by yairEO** [comment]
I was able to install `node-sass` by downgrading to node version `12` (I'm using [Volta](https://docs.volta.sh/guide/#how-does-it-work) to manage versions on Windows)

Node version `14.16` and `15.x` did not work for me.

I also installed Python v3 and made sure to add it to the *env variables* in Windows and also to the `path`. I am uncertain if it had any affect on the success. 

![image](https://user-images.githubusercontent.com/845031/111451534-34394500-871a-11eb-8a1c-6f80033437f2.png)

**Comment by jayjupdhig** [comment]
ok thx

**Comment by cclauss** [comment]
Node-sass is deprecated so it would be safer to migrate to an alternative.  https://sass-lang.com/blog/libsass-is-deprecated

**Comment by robbiemu** [comment]
what are you supposed to install?

**Comment by onyet** [comment]
> I resolved it by running the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd.bat" before npm install

Thanks, i run `LaunchDevCmd.bat` on `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools`, and `cd` to my root project from **DevCmd** and install node-sass@4.14.1, it'is works... 🥳

**Comment by chitgoks** [comment]
yarn add node-sass worked. 

what's weird is that i already tried "npm install node-sass" and "npm install -g node-sass" and it didnt work.

**Comment by beatrizsmerino** [comment]
I have the same problem and I am using mac

**Comment by beatrizsmerino** [comment]
I solved the error by uninstalling the Xcode program and installing node version 12.
[https://nodejs.org/dist/latest-v12.x/](https://nodejs.org/dist/latest-v12.x/)

**Comment by jayjupdhig** [comment]
OK thx

**Comment by robbiemu** [comment]
in node 14 you can switch to sass .. this past year has seen two major library deprecations for me: node-sass and tslint

src: https://sass-lang.com/blog/libsass-is-deprecated
src: https://blog.palantir.com/tslint-in-2019-1a144c2317a9 (ts lint dep. was even older, but didnt effect for example angular until this year for me)
