### ISSUE TITLE
Please use safety parentheses to query Python version

### ISSUE THREAD

**Issue by mcandre** [nodejs/node-gyp#1965]
On my machine, the `python` binary points to Python v3.7.

```console
$ cat .python-version 
3.7.4

$ pyenv versions
  system
  2.7.13
  2.7.15
  3.4.3
  3.7.0
* 3.7.4

$ python --version
Python 3.7.4

$ npm config get python
/Users/tkmamhf/.pyenv/shims/python
```

However, when I try to `npm install` a package like appmetrics-prometheus which depends on node-gyp, then node-gyp sends Python *2* style code to query the Python version, which fails:

```console
$ npm install

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/tkmamhf/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
```

I forcibly reconfigured my NPM python path with `npm config set python python3.7` and get the same error.

Please make sure to wrap `print` arguments in safety parentheses, so that this query for Python versions can be supplied to different Python versions.

**Comment by cclauss** [comment]
Please upgrade node-gyp.  This issue was fixed long ago.

**Comment by frkami123** [comment]
this kinda annoying since node-gyp very deep in the dependencies hierarchy (of blueprintjs) and 3.8.0 the last release of major vesion 3.x.x has this bug.

**Comment by cclauss** [comment]
Use legacy Python instead of Python 3 or upgrade Node-gyp to a version that supports Python 3.
