### ISSUE TITLE
How do I remove this damn package?

### ISSUE THREAD

**Issue by jbis9051** [nodejs/node-gyp#1970]
Every time I run npm install this package seems to run and it fails preventing me from installing any modules. I have attempted to uninstall in the following ways:

```shell
rm -rf ~/.node-gyp
rm -rf node_modules
npm uninstall node-gyp
npm uninstall -g node-gyp
```

**Comment by rvagg** [comment]
It doesn't "install", it just keeps a cache of node.js header files in ~/.node-gyp (older node-gyp) or ~/.cache/node-gyp (Linux) or ~/Library/Caches/node-gyp/ (macOS). Without this cache, every time you install a native addons (C++) you'll be downloading the same file each time.

node-gyp shouldn't be preventing you from doing anything. If you are having trouble installing packages then perhaps you have compiler toolchain setup problems or are installing packages that aren't compatible with your version of Node.js.

Paste some error output here and perhaps it'll be a straightforward fix.

**Comment by jbis9051** [comment]
I'm an idiot. Please disregard this issue.
