### ISSUE TITLE
Problem OSX(Catalina) plugin and NodeJS12+

### ISSUE THREAD

**Issue by oktapodia** [nodejs/node-gyp#1981]
I have a problem when using a C++ native module on Nodejs 12 and above, the function always returns 0 instead of the expected value

* **Node Version**: node 12.13.1 and npm 6.12.1
* **Platform**: OSX Catalina (I followed the [tutorial](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md) and everything looks well configured) 
* **Compiler**: Apple clang version 11.0.0 (clang-1100.0.33.12)
* **packages version:**
* * node-addon-api: *
* * node-gyp: ^6.0.1

<details><summary>Binding.gyp:</summary>

```javascript
{
  'targets': [{
    'target_name': 'testlib',
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions' ],
      'xcode_settings': {
        'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7',
      },
    'include_dirs': [
      '<!@(node -p "require(\'node-addon-api\').include")',
    ],
    'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],

    'cflags': [
      '-Wall',
      '-Wparentheses',
      '-Winline',
      '-Wbad-function-cast',
      '-Wdisabled-optimization'
    ],

    'conditions': [
      ['OS == "mac"', {
          'cflags+': ['-fvisibility=hidden'],
          'xcode_settings': {
            'GCC_SYMBOLS_PRIVATE_EXTERN': 'YES', # -fvisibility=hidden
          },
        'include_dirs': [
          '<!@(node -p "require(\'node-addon-api\').include")',
          'System/Library/Frameworks/CoreFoundation.Framework/Headers',
          'System/Library/Frameworks/Carbon.Framework/Headers',
          'System/Library/Frameworks/ApplicationServices.framework/Headers',
          'System/Library/Frameworks/OpenGL.framework/Headers',
        ],
        'link_settings': {
          'libraries': [
            '-framework Carbon',
            '-framework CoreFoundation',
            '-framework ApplicationServices',
            '-framework OpenGL'
          ]
        }
      }],
    ],

    'sources': [
        'src/main.cpp',
        'src/main/screen.c',
    ]
  }]
}
```

</details>

<details><summary>screen.c:</summary>

```c
#if defined(IS_MACOSX)
	#include <ApplicationServices/ApplicationServices.h>
#endif

MMSize getDisplaySize(void)
{
#if defined(IS_MACOSX)
	CGDirectDisplayID displayID = CGMainDisplayID();
	return MMSizeMake(CGDisplayPixelsWide(displayID),
	                  CGDisplayPixelsHigh(displayID));
#endif
}
```
</details>

<details><summary>main.cpp:</summary>

```c
#include <napi.h>
#include "screen.h"

Napi::Object screen::getScreenSize(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    MMSize displaySize = getDisplaySize();
    Napi::Object obj = Napi::Object::New(env);

    obj.Set("width", displaySize.width);
    obj.Set("height", displaySize.height);

    return obj;
}

Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
    screen::Init(env, exports);

    return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, InitAll)
```
</details>

Output 11 and below:
```
{ width: 1920, height: 1200 }
```

Output Nodejs 12+:
```
{ width: 0, height: 0 }
```

I've added more information about the code, this might be helpful.

I don't really know if it is a problem about `node-gyp` or `napi`

Any ideas?

PS: It is working well on linux with a X11 code

Regards

**Comment by rvagg** [comment]
I don't think we have have enough information to be helpful here. Your screen.c isn't addon code, is it printing those values _in_ c++ or is that what's returning to JavaScript somewhere in main.cpp?

**Comment by oktapodia** [comment]
Thank you for your comment @rvagg I've updated my main post

**Comment by cclauss** [comment]
Would it be possible to put this code into a Travis CI test or a GitHub Actions test?

**Comment by rvagg** [comment]
OK, this is pretty interesting, can confirm that something is screwy. My minimal repro:

package.json:

```json
{
  "name": "addon",
  "gypfile": true,
  "dependencies": {
    "node-addon-api": "~2.0.0"
  }
}
```

binding.gyp:

```yaml
{
  'targets': [{
    'target_name': 'testlib',
    'xcode_settings': {
      'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
    },
    'include_dirs': [
      '<!@(node -p "require(\'node-addon-api\').include")',
    ],
    'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
    'conditions': [
      ['OS == "mac"', {
        'include_dirs': [
          'System/Library/Frameworks/CoreFoundation.Framework/Headers',
        ],
        'link_settings': {
          'libraries': [
            '-framework CoreFoundation',
          ]
        }
      }],
    ],
    'sources': [
      'main.cpp',
    ]
  }]
}
```

main.cpp:

```c++
#include <napi.h>
#include <ApplicationServices/ApplicationServices.h>

Napi::Object getScreenSize(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    Napi::Object obj = Napi::Object::New(env);
    CGDirectDisplayID displayID = CGMainDisplayID();
    obj.Set("width", CGDisplayPixelsWide(displayID));
    obj.Set("height", CGDisplayPixelsHigh(displayID));
    fflush(stdout);
    return obj;
}

Napi::Object InitAll(Napi::Env env, Napi::Object exports) {
  return Napi::Function::New(env, getScreenSize);
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, InitAll)
```

Test with: `node -pe "require('./build/Release/testlib.node')()"`

Rebuild with `node-gyp rebuild`

On Node 10.x it prints out a proper resolution, on 13.x it prints out `{ width: 0, height: 0 }`.

Minimal direct application to sanity check:

run.cpp

```c++
#include <stdio.h>
#include <ApplicationServices/ApplicationServices.h>

int main() {
    CGDirectDisplayID displayID = CGMainDisplayID();
    printf("{ width: %lu, height: %lu }\n", CGDisplayPixelsWide(displayID), CGDisplayPixelsHigh(displayID));
    fflush(stdout);
    return 0;
}
```

compile with: `clang run.cpp -framework ApplicationServices -o run`.

@nodejs/addon-api @nodejs/n-api anyone care to take a poke at this one? I'm not sure where to go. Related to how we build Node now, with the libnode setup perhaps? Or is there some flag we're setting now that is changing the build enough for this to be different? The only stand-out difference I can see in common.gypi is `MACOSX_DEPLOYMENT_TARGET` being `10.10` not, but the original report has it as `10.7`, the same as we've had in 10.x and a few prior versions.

**Comment by oktapodia** [comment]
I was creating the repository but thank you @rvagg this is exactly the problem I have

**Comment by rvagg** [comment]
Doing a `V=1 node-gyp rebuild` and watching the compile output with old and new Node, the only real differences are: 

```
'-DV8_DEPRECATION_WARNINGS'
'-DV8_IMMINENT_DEPRECATION_WARNINGS'
'-DOPENSSL_THREADS'
```

And the `-mmacosx-version-min=10.7` vs `-mmacosx-version-min=10.10` change.

Then there's this: if I compile the addon with 13.x and run it against both 13.x and 10.x, it _works_ with 10.x but doesn't with 13.x. So I guess that places the blame in Node itself, and/or how it's built:

```
$ node -v
v13.2.0
$ node -pe "require('./build/Release/testlib.node')()"
{ width: 0, height: 0 }
$ ./node-v10.17.0-darwin-x64/bin/node -v
v10.17.0
$ ./node-v10.17.0-darwin-x64/bin/node -pe "require('./build/Release/testlib.node')()"
{ width: 1440, height: 900 }
```

**Comment by oktapodia** [comment]
@NickNaso Any thought on that one?

**Comment by gabrielschulhof** [comment]
Alas, I think this requires an OSX laptop, which I do not have 🙁

**Comment by oktapodia** [comment]
Yes, it is :/ Maybe @romandev or @mhdawson have an OSX computer?

**Comment by NickNaso** [comment]
Hi everybody,
I'm travelling by I tried to investigate the problem. What I found is that the reported behaviour happens starting from the following versions of Node.js:
- v12.13.1
- v13.0.1

**Comment by cclauss** [comment]
Travis CI and GitHub Actions both have Macs...  Can we create a test that fails there?

**Comment by oktapodia** [comment]
@cclauss [Here's](https://github.com/oktapodia/napi-issue-nodegyp-1981) a reproducible example with the [travis tests](https://travis-ci.com/oktapodia/napi-issue-nodegyp-1981/builds/139862634) failing on node 12+

**Comment by legendecas** [comment]
Confirmed issue related to #2566. 

It could be reproduced on Node.js v10 by setting the `process.title` before retrieving the window size.

**Comment by bnoordhuis** [comment]
This was fixed a while ago in libuv (or fixed... it wasn't really a libuv issue to start with but that aside) so I'm going to close this out.
