### ISSUE TITLE
Add krb5 package

### ISSUE THREAD

**Issue by wdavidw** [nodejs/node-gyp#1983]
I invite you to add our [krb5 binding file](https://github.com/adaltas/node-krb5/blob/master/binding.gyp) to the wiki page ["binding.gyp files out in the wild"](https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild)

**Comment by rvagg** [comment]
gee, I forgot we even had a wiki, I'm not sure we want to be in the business of continuing to maintain that as a documentation source but I've added this one for now while we figure out what we're going to do with the wiki
