### ISSUE TITLE
Getting “Symbol Lookup Error” when calling C library from C++ (Node.js Addon)

### ISSUE THREAD

**Issue by icyxieex** [nodejs/node-gyp#1987]
* **Node Version**: v10.16.0
* **Platform**: Linux x86_64 x86_64 x86_64 GNU/Linux

<details><summary> node-gyp:</summary>

```
{
  "targets": [
    {
      "target_name": "normalize_url",
      "sources": [
        "./app/cc/normalize_url.cc"
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")",
        "./include/",
      ],
      "libraries":
      [
        "../library/libalog.so.13",
        "../library/libautil.so.11",
        "../library/libboost_regex.so.1.66.0",
        "../library/libsm_url.so"
      ],
      "link_settings" : {
        "libraries" : ["-lalog","-lautil","-lsm_url"],
        "library_dirs": ["../library/"],
      },
      "dependencies": [
        "<!(node -p \"require('node-addon-api').gyp\")"
      ],
      "ldflags": [
        "-Wl,-rpath,/hubble-js-engine/library/libsm_url.so"
      ],
      "cflags!": ["-fno-exceptions"],
      "cflags": [ "-std=c++11" ],
      "cflags_cc!": ["-fno-exceptions"],
      "defines": ["NAPI_CPP_EXCEPTIONS"],
      "xcode_settings": {
        "GCC_ENABLE_CPP_EXCEPTIONS": "YES"
      }
    }
  ]
}

```
</details>

<details><summary> .cc:</summary>

```
#include <napi.h>
#include <sm_url/url_normalizer.h>

using namespace Napi;

String Hello(const CallbackInfo& info) {
    std::string url =  "http://m.baidu.com";
    std::string normalizedUrl = sm_url::UrlNormalizer::NormalizeUrl(url);
    return String::New(info.Env(), "world");
}
Napi::Object  Init(Env env, Object exports) {
    exports.Set("hello", Function::New(env, Hello));
    return exports;
}
NODE_API_MODULE(addon, Init)
```

</details>

I am trying to use node-gyp in nodejs for call some C++ so, The C++ module compiles, but when I try to run it through Node.js JavaScript, the C++ library fails to be called with a symbol lookup error that I'm having problems debugging:

#LD_LIBRARY_PATH=.:../library/ node --napi-modules -e "console.log(require('./Release/normalize_url.node').hello())" node: symbol lookup error: /hubble-js-engine/build/Release/normalize_url.node: undefined symbol: _ZN6sm_url13UrlNormalizer12NormalizeUrlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjb

And nm c++ so is:

nm -g ../library/libsm_url.so |grep NormalizeUrlER 000000000010df70 T _ZN6sm_url13UrlNormalizer12NormalizeUrlERKSsbjb 000000000010d930 T _ZN6sm_url13UrlNormalizer12NormalizeUrlERKSsRibjb 000000000010d540 T _ZN6sm_url13UrlNormalizer12NormalizeUrlERNS_13StructuredUrlE

**Comment by bnoordhuis** [comment]
That's not a node-gyp issue so I'm going to close this out. If you want to pursue this, try nodejs/help.
