### ISSUE TITLE
Doc clarification required about --target option.

### ISSUE THREAD

**Issue by bimalkjha** [nodejs/node-gyp#1988]
* **Node Version**: 12.4.0
* **Platform**: ntx64
* **Compiler**: msbuild - Microsoft (R) Build Engine version 14.0.27530.0
* **Module**: ibm_db

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\nodework\vscode\db2connect\node_modules\ibm_db>node-gyp configure build  --IS_DOWNLOADED=true --target=6.1.5 --arch=x64 --dist-url=https://atom.io/download/electron  --IBM_DB_HOME=$IBM_DB_HOME
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@12.4.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\bjha\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\nodework\\vscode\\db2connect\\node_modules\\ibm_db\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bjha\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\bjha\\.node-gyp\\6.1.5\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\bjha\\.node-gyp\\6.1.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\bjha\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\bjha\\.node-gyp\\6.1.5\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\nodework\\vscode\\db2connect\\node_modules\\ibm_db',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\nodework\\vscode\\db2connect\\node_modules\\ibm_db\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn msbuild
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
C:\Users\bjha\.node-gyp\6.1.5\include\node\v8.h(8207): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc.cpp)C:\Users\bjha\.node-gyp\6.1.5\include\node\v8.h(8207): warning C4996
: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_connection.cpp) [C:\nodework\vscode\db2connect\node_modules\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc.cpp(995): error C2664: 'v8::Local<v8::String> v8::Value::ToString(void) const': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' [C:\nodework\vscode\db2connect\node_modules\ibm_db\build\odbc_binding
s.vcxproj]
```

</details>

I am trying to compile ibm_db for electron version 6.1.5 using node.js version 12.4.0. For non-electron build, ibm_db compiles and works fine i.e. without --target and without --dist-url option in node-gyp. The syntax in source code is fine for node.js v12.4.0. But, in --target, when I use electron version, it uses node 6.1.5 and compilation fails.

As per: https://electronjs.org/docs/tutorial/using-native-node-modules
* --target=1.2.3 is the version of Electron.

But, as per node-gyp documentation: https://github.com/nodejs/node-gyp
* --target=v6.2.1 | Node.js version to build for (default is process.version)

**Which documentation is correct? What value should I use for --target option of node-gyp?**

**Comment by bimalkjha** [comment]
I am getting invalid NODE_MODULE_VERSION error while building ibm_db with VSCode when I use --target=12.4.0 with node-gyp. 
'''
Error: The module '\\?\c:\nodework\vscode\db2connect\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
'''
NODE_MODULE_VERSION value 72 is equivalent for node.js version 12.4.0. 
What value of --target option is equivalent for NODE_MODULE_VERSION 73?

**Comment by sincerefly** [comment]
I have the same question.

**Comment by bencefr** [comment]
Same

**Comment by sincerefly** [comment]
Now, I think the `--target` is Node.js version.

**Comment by bnoordhuis** [comment]
`--target` is the node version. If you're compiling for e.g. electron, you also want to use flags like `--dist-url` to tell node-gyp where to find the SDK.

I'm closing this but please open a PR if you think the documentation can be improved.

**Comment by bimalkjha** [comment]
@bnoordhuis I am hitting below error using VSCode 1.46.1 which is built using electron version 7.3.1 and node.js version 12.8.1. When I use electron version in target it works, but when use node.js version, it fails with error. Could you please reconfirm that --target should be node.js version not the electron version?
```
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --target=12.8.1 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME=$IBM_DB_HOME
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://atom.io/download/electron/v12.8.1/node-v12.8.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\nodework\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:187:14)
gyp ERR! stack     at Request.emit (events.js:208:15)
gyp ERR! stack     at Request.onRequestResponse (C:\nodework\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:203:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:22)
gyp ERR! stack     at TLSSocket.emit (events.js:203:13)
gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:276:11)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\nodework\\nodejs\\node.exe" "C:\\nodework\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--target=12.8.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--IBM_DB_HOME=$IBM_DB_HOME"
```
Thanks.

**Comment by richardlau** [comment]
Looking at [`lib/process-release.js`](https://github.com/nodejs/node-gyp/blob/3555ff4f0031f067bda9a49cbb2dbe6c04f4b5c7/lib/process-release.js) the answer appears to be that the value of `--target` is used with `--dist-url` to build URLs to download from. The default (i.e. not specified) dist-url is for Node.js, so `--target` should specify a Node.js version when `--dist-url` is not specified.

If you're setting `--dist-url` then what `--target` represents is up to whoever is maintaining the URL you've specified. So for Electron's dist-url (https://atom.io/download/electron) it looks like `--target` should be Electron's version.
