### ISSUE TITLE
Windows building errors

### ISSUE THREAD

**Issue by libvirtadept** [nodejs/node-gyp#1989]
* **Node Version**:  13.0.1 / 6.12.0
* **Platform**:  Windows
* **Compiler**:  15.9.21.664
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--msvs_version=2015'
gyp verb cli ]
gyp info using node-gyp@6.0.1
gyp info using node@13.0.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe" to get version
gyp verb find Python - version is "3.7.5"
gyp info find Python using Python version 3.7.5 found at "C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 13.0.1
gyp verb command install [ '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 13.0.1
gyp verb build dir attempting to create "build" dir: C:\Users\admin\Desktop\libvirt-dev-xml\build
gyp verb build dir "build" dir needed to be created? C:\Users\admin\Desktop\libvirt-dev-xml\build
gyp verb find VS msvs_version was set from command line or npm config
gyp verb find VS - looking for Visual Studio version 2015
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2017 (15.9.28307.905) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp verb find VS - msvs_version does not match this version
gyp verb find VS checking VS2017 (15.9.28307.905) found at:
gyp verb find VS "E:\Visual Studio"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp verb find VS - msvs_version does not match this version
gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
gyp verb find VS looking for Visual Studio 2015
gyp verb find VS - found in "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp verb find VS - MSBuild in "C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\admin\Desktop\libvirt-dev-xml\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\admin\Desktop\libvirt-dev-xml\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\admin\Desktop\libvirt-dev-xml\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\libvirt-dev-xml\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\AppData\\Local\\node-gyp\\Cache\\13.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\admin\\AppData\\Local\\node-gyp\\Cache\\13.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\13.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\admin\\Desktop\\libvirt-dev-xml',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\libvirt-dev-xml\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
    gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
    Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
Сборка начата 04.12.2019 13:49:02.
Проект "C:\Users\admin\Desktop\libvirt-dev-xml\build\binding.sln" в узле 1 (целевые объекты по умолчанию).
ValidateSolutionConfiguration:
  Создание конфигурации решения "Release|x64".
Проект "C:\Users\admin\Desktop\libvirt-dev-xml\build\binding.sln" (1) выполняет сборку "C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj" (2) в узле 1 (целевые объекты по умолчанию).
PrepareForBuild:
  Создание каталога "Release\obj\virt\".
  Создание каталога "Release\obj\virt\virt.tlog\".
InitializeBuildStatus:
  Создание "Release\obj\virt\virt.tlog\unsuccessfulbuild", так как было задано "AlwaysCreate".
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\include\node" /I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\src" /
  I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\deps\openssl\config" /I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\deps\openssl\openssl\include" /I"C:\Users\admin\AppData\Local\node-gyp\Cach 
  e\13.0.1\deps\uv\include" /I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\deps\zlib" /I"C:\Users\admin\AppData\Local\node-gyp\Cache\13.0.1\deps\v8\include" /I"C:\Users\admin\Desktop\libvirt-dev-xml 
  \node_modules\node-addon-api" /IC:\Users\admin\Desktop\libvirt\include /I.. /Z7 /nologo /W3 /WX- /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=virt /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_ 
  DEPRECATION_WARNINGS=1 /D V8_DEPRECATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WARNINGS /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO_PINSHARED /D OPE 
  NSSL_THREADS /D NAPI_DISABLE_CPP_EXCEPTIONS /D BUILDING_NODE_EXTENSION /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\v 
  irt\\" /Fd"Release\obj\virt\vc140.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /errorReport:queue /MP /EHsc ..\src\libvirt.cc ..\src\worker.cc ..\src\hypervisor.cc "..\src\hypervi 
  sor-connect.cc" "..\src\hypervisor-domain.cc" "..\src\hypervisor-node.cc" ..\src\domain.cc "C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  libvirt.cc
  worker.cc
  hypervisor.cc
  hypervisor-connect.cc
  hypervisor-domain.cc
  hypervisor-node.cc
  domain.cc
  win_delay_load_hook.cc
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\admin\Desktop\libvirt-dev-xml\build\Release\libvirt.node" /INCREMENTAL:NO /NOLOGO kernel32.lib 
  user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib DelayImp.lib "C:\\Users\\admin\\AppData\\Local\\node-gyp\\Cache\\13.0.1\\x64\\node.lib"  
  libvirt.lib Delayimp.lib /DELAYLOAD:node.exe /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\admin\Desktop\libvirt-dev-xml\build\Release\libvirt.pdb" /OP 
  T:REF /OPT:ICF /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /MACHINE:X64 /SAFESEH:NO /ignore:4199 /DLL Release\obj\virt\libvirt.obj
  Release\obj\virt\worker.obj
  Release\obj\virt\hypervisor.obj
  "Release\obj\virt\hypervisor-connect.obj"
  "Release\obj\virt\hypervisor-domain.obj"
  "Release\obj\virt\hypervisor-node.obj"
  Release\obj\virt\domain.obj
  Release\obj\virt\win_delay_load_hook.obj
LINK : fatal error LNK1181: cannot open input file 'libvirt.lib' [C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj]
Сборка проекта "C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.

Сборка проекта "C:\Users\admin\Desktop\libvirt-dev-xml\build\binding.sln" завершена (целевые объекты по умолчанию) с ошибкой.

Ошибка сборки.

"C:\Users\admin\Desktop\libvirt-dev-xml\build\binding.sln" (целевой объект по умолчанию) (1) ->
"C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj" (целевой объект по умолчанию) (2) ->
(Целевой объект Link) ->
  LINK : fatal error LNK1181: cannot open input file 'libvirt.lib' [C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj]

    Предупреждений: 0
    Ошибок: 1

Затраченное время: 00:00:00.89
gyp ERR! build error 
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" 
"--msvs_version=2015"
gyp ERR! cwd C:\Users\admin\Desktop\libvirt-dev-xml
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok
</details>

When link_settings => libraries doesn't have "-llibvirt.lib" node-gyp returning many errors
`hypervisor-domain.obj : error LNK2001: unresolved external symbol virDomainGetID [C:\Users\admin\Desktop\libvirt-dev-xml\build\virt.vcxproj]`

On linux all building successfully

**Comment by syedsimanta03** [comment]
same

**Comment by zuluoaaa** [comment]
I have same proble

**Comment by behroozbc** [comment]
i have same error
