### ISSUE TITLE
Builds Fail on WSL

### ISSUE THREAD

**Issue by devnuvven** [nodejs/node-gyp#1991]
I am running VS on a WSL (Windows Subsystem for Linux) and when I am trying to do ‘npm install’ I am getting an error which says
make: Leaving directory ‘/home/rishabh/customer-management-api/node_modules/couchbase/build’
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/rishabh/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:219:5)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command “/home/rishabh/.nvm/versions/node/v13.3.0/bin/node” “/home/rishabh/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js” “rebuild”
gyp ERR! cwd /home/rishabh/customer-management-api/node_modules/couchbase
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! couchbase@2.6.9 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the couchbase@2.6.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[npm_install_error.zip](https://github.com/nodejs/node-gyp/files/3957019/npm_install_error.zip)

**Comment by gengjiawen** [comment]
Looks like couchbase not ready for Node.js 13, Can you try 12 instead.
