### ISSUE TITLE
Header test is making CITGM fail on new releases

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/node-gyp#2000]
https://github.com/nodejs/node-gyp/commit/0670e5189d00b5db3c3058220367a41d407b218a

Due to the 404 when getting the resource the test will always fail.

**Comment by BridgeAR** [comment]
The test obviously fails for release builds. Either the test would have to check if the release number if already available or be skipped in case installation fails.

**Comment by richardlau** [comment]
The test in question has a bypass mechanism
https://github.com/nodejs/node-gyp/blob/038b4a37444aa3711327863ff6cc431242769c82/test/test-download.js#L207-L215

I'll PR a change to CITGM's lookup to add the `FAST_TEST` environment variable for `node-gyp`.

**Comment by richardlau** [comment]
https://github.com/nodejs/citgm/pull/776
