### ISSUE TITLE
gyp err uncaught exception

### ISSUE THREAD

**Issue by germanDevguru** [nodejs/node-gyp#2004]
Hi Richardlau!
I've some problems in my project, something like below.
Can you help me with this problem?
![image](https://user-images.githubusercontent.com/55408281/71447796-d8ad2100-273b-11ea-8274-6f5682cc65b5.png)

I hope you help me with this problem.
If it is not comfortable to have chat, you can contact me on skype with id: live:csillag.szabolcs.andras

Best regards.

**Comment by joaocgreis** [comment]
@germanDevguru can you run with `--verbose` and paste the full output?

This might actually be an issue with node-gyp. This is version 5.0.5 which supports VS2019 and checks that MSBuild is installed, but then can't launch it.

**Comment by germanDevguru** [comment]
Thanks for your kind reply. So have I downgrade the node-gyp version?

**Comment by germanDevguru** [comment]
If so, can you tell me recommended node-gyp version?
For solve this problem, I've installed 2019 before, but it doesn't work. So I've uninstall 2019 and reinstall vs2015. Now what can I do to solve this problem?

**Comment by joaocgreis** [comment]
This version should be good. Can you run with `--verbose`, copy all the output that appears on the console and paste it here?
