### ISSUE TITLE
Unable to build most projects using node-gyp

### ISSUE THREAD

**Issue by gdefraiteur** [nodejs/node-gyp#2007]
Hello, i'm trying to npm install this project: https://github.com/node-xr/node-openvr 

I got issues with it, i desesperately search a way to have oculus or openvr bindings using nodejs, hope you could help:

`C:\Users\gonza\git_repositories\node-openvr>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  Copying C:\Users\gonza\git_repositories\node-openvr/deps/openvr/bin/win64/openvr_api.dll to C:\Users\gonza\git_repositories\node-openvr/build/Release\openvr_api.dll
          1 fichier(s) copié(s).
  bindings.cpp
  ivrsystem.cpp
  openvr.cpp
  win_delay_load_hook.cc
c:\users\gonza\git_repositories\node-openvr\src\openvr.cpp(26): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build\ope
nvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\openvr.cpp)
c:\users\gonza\git_repositories\node-openvr\src\openvr.cpp(125): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build\op 
envr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\openvr.cpp)
c:\users\gonza\git_repositories\node-openvr\src\openvr.cpp(147): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build\op 
envr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\openvr.cpp)
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(8): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-open 
vr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(7): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr\ 
build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(10): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(9): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr\ 
build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(12): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(11): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr 
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(14): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(13): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr 
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(16): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(15): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr 
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(18): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(17): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr 
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(20): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(19): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(22): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-ope 
nvr\build\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\bindings.cpp) 
c:\users\gonza\git_repositories\node-openvr\src\bindings.cpp(21): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments [C:\Users\gonza\git_repositories\node-openvr 
\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(64): error C2661: 'v8::Value::ToObject' : aucune fonction surchargée ne nécessite 0 arguments (compilation du fichier source ..\src\ivrsyste 
m.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(64): error C2789: 'matrix' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\U 
sers\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(64): note: voir la déclaration de 'matrix' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(68): error C3536: 'matrix' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\ 
Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(68): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\ivr 
system.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(68): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, uint32_t)' (compilation du fichier source ..\sr 
  c\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(68): error C2789: 'row' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\User 
s\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(68): note: voir la déclaration de 'row' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(71): error C3536: 'row' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\Use 
rs\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(71): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\ivr 
system.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(71): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, uint32_t)' (compilation du fichier source ..\sr 
  c\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(71): error C2789: 'cell' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\Use 
rs\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(71): note: voir la déclaration de 'cell' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(72): error C3536: 'cell' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\Us 
ers\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(99): error C2661: 'v8::Value::ToObject' : aucune fonction surchargée ne nécessite 0 arguments (compilation du fichier source ..\src\ivrsyste 
m.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(99): error C2789: 'array' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\Us 
ers\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(99): note: voir la déclaration de 'array' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(103): error C3536: 'array' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\ 
Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(103): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(103): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, uint32_t)' (compilation du fichier source ..\s
  rc\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(103): error C2789: 'cell' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\Us 
ers\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(103): note: voir la déclaration de 'cell' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(104): error C3536: 'cell' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\U 
sers\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(208): error C2661: 'v8::Value::ToObject' : aucune fonction surchargée ne nécessite 0 arguments (compilation du fichier source ..\src\ivrsyst 
em.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(208): error C2789: 'object' : un objet de type qualifié const doit être initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:\ 
Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\src\util.h(208): note: voir la déclaration de 'object' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(214): error C3536: 'object' : ne peut pas être utilisé avant d'avoir été initialisé (compilation du fichier source ..\src\ivrsystem.cpp) [C:
\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\util.h(214): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(214): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie 
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(219): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(219): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(225): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(225): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie 
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(231): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(231): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie 
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(236): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(236): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie 
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\util.h(241): error C2665: 'Nan::Get' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments (compilation du fichier source ..\src\iv 
rsystem.cpp) [C:\Users\gonza\git_repositories\node-openvr\build\openvr.vcxproj]
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(144): note: est peut-être 'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,uint32_t)' (compilation du fi 
  chier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\node_modules\nan\nan_maybe_43_inl.h(134): note: ou       'v8::MaybeLocal<v8::Value> Nan::Get(v8::Local<v8::Object>,v8::Local<v8::Value>)' (compilatio 
  n du fichier source ..\src\ivrsystem.cpp)
  c:\users\gonza\git_repositories\node-openvr\src\util.h(241): note: lors de la tentative de mise en correspondance de la liste des arguments '(int, v8::Local<v8::String>)' (compilation du fichie 
  r source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(163): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(183): error C2660: 'v8::Value::NumberValue' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: voir la déclaration de 'v8::Value::NumberValue' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(184): error C2660: 'v8::Value::NumberValue' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: voir la déclaration de 'v8::Value::NumberValue' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(208): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(254): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(274): error C2660: 'v8::Value::NumberValue' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: voir la déclaration de 'v8::Value::NumberValue' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(275): error C2660: 'v8::Value::NumberValue' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: voir la déclaration de 'v8::Value::NumberValue' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(305): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(414): error C2661: 'v8::Value::BooleanValue' : aucune fonction surchargée ne nécessite 0 arguments [C:\Users\gonza\git_repositories\n 
ode-openvr\build\openvr.vcxproj]
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(437): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(451): error C2660: 'v8::Value::NumberValue' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: voir la déclaration de 'v8::Value::NumberValue' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(526): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(543): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(577): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
c:\users\gonza\git_repositories\node-openvr\src\ivrsystem.cpp(633): error C2660: 'v8::Value::Uint32Value' : la fonction ne prend pas 0 arguments [C:\Users\gonza\git_repositories\node-openvr\build 
\openvr.vcxproj]
  c:\users\gonza\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: voir la déclaration de 'v8::Value::Uint32Value' (compilation du fichier source ..\src\ivrsystem.cpp)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gonza\git_repositories\node-openvr
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openvr@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openvr@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gonza\AppData\Roaming\npm-cache\_logs\2019-12-29T16_41_06_196Z-debug.log`

**Comment by rvagg** [comment]
this looks like you're trying to compile an addon that isn't supported by the version of Node.js you're using. You should either try and install a newer version of the addon that supports Node.js 12, contact the author of the addon to see if they can update it to support Node.js 12, or downgrade your Node.js version to one supported by the addon, perhaps Node.js 10.
