### ISSUE TITLE
Typeerror in xcode_emulation.py

### ISSUE THREAD

**Issue by magikid** [nodejs/node-gyp#2010]
* **Node Version**: 10.16.0, npm version: 6.13.4
* **Platform**: Darwin cjonesmbpx12 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
* **Compiler**: 
```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

* **Module**: `npm install --verbose grpc`

<details><summary>Verbose output (from npm or node-gyp):</summary>

Here is the npm debug log: [2020-01-02T19_13_38_986Z-debug.log](https://github.com/nodejs/node-gyp/files/4017048/2020-01-02T19_13_38_986Z-debug.log)

</details>

The reason that I think this issue is with node-gyp is that part of the output includes this:

```
  File "/Users/cjone0102/.asdf/installs/nodejs/10.16.0/.npm/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv                                                                                                                         if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
```

**Comment by cclauss** [comment]
Dup of #1917 ?

**Comment by magikid** [comment]
Yep, this is a dupe.  Closing it.
