### ISSUE TITLE
always the same error

### ISSUE THREAD

**Issue by omardavinzi** [nodejs/node-gyp#2017]
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/opentrade/node_modules/sqlite3/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '7.10.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
^Cgyp verb install input version string "7.10.1"
gyp verb install installing version: 7.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 7.10.1
gyp verb ensuring nodedir is created /var/www/html/opentrade/node_modules/sqlite3/.node-gyp/7.10.1

**Comment by rvagg** [comment]
you're running in to an npm security feature, which is there for good reason but can be forcibly unset: https://docs.npmjs.com/misc/config#unsafe-perm

_but_ running npm as root is not a good idea, you should avoid doing it at all cost, install and run your Node.js application as an unprivileged user and give it just what it wants.

also installing your application directly in /var/www/html/ is probably not a good idea either if that's the root of an existing web server since everyone can just access your source and modules (and perhaps data and config) via that web server.

**Comment by richardlau** [comment]
This looks a lot like https://github.com/nodejs/node-gyp/issues/1383 which was fixed by https://github.com/nodejs/node-gyp/pull/1384 in node-gyp 3.7.0.
