### ISSUE TITLE
Error for installing integer on macOS 10.15.2

### ISSUE THREAD

**Issue by xzhang2016** [nodejs/node-gyp#2019]
* **Node Version**: node 13.6.0, npm 6.13.4 
* **Platform**:  macOS Catalina 10.15.2 
* **Compiler**: Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin  
* **Module**: npm install integer 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```
 % npm install integer

> integer@1.0.7 install /Users/xuezhang/cwc/cwc-integ/Sbgnviz-Collaborative-Editor/node_modules/better-sqlite3/node_modules/integer
> node-gyp rebuild

  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp:329:21: error: no matching constructor for initialization of 'v8::String::Value'
                v8::String::Value utf16(string);
                                  ^     ~~~~~~
/Users/xuezhang/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3210:5: note: candidate constructor not viable: no known
      conversion from 'v8::Local<v8::String>' to 'const v8::String::Value' for 1st argument
    Value(const Value&) = delete;
    ^
/Users/xuezhang/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3203:5: note: candidate constructor not viable: requires 2
      arguments, but 1 was provided
    Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/integer/src/integer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xuezhang/cwc/cwc-integ/Sbgnviz-Collaborative-Editor/node_modules/better-sqlite3/node_modules/integer
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xuezhang/.npm/_logs/2020-01-10T01_37_43_352Z-debug.log

</details>

**Comment by richardlau** [comment]
> ```
>   CXX(target) Release/obj.target/integer/src/integer.o
> ../src/integer.cpp:329:21: error: no matching constructor for initialization of 'v8::String::Value'
>                 v8::String::Value utf16(string);
>                                   ^     ~~~~~~
> /Users/xuezhang/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3210:5: note: candidate constructor not viable: no known
>       conversion from 'v8::Local<v8::String>' to 'const v8::String::Value' for 1st argument
>     Value(const Value&) = delete;
>     ^
> /Users/xuezhang/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3203:5: note: candidate constructor not viable: requires 2
>       arguments, but 1 was provided
>     Value(Isolate* isolate, Local<v8::Value> obj);
>     ^
> 1 error generated.
> make: *** [Release/obj.target/integer/src/integer.o] Error 1
> ```

This error indicates that integer@1.0.7 is incompatible with Node.js 13. It looks like it was fixed by https://github.com/JoshuaWise/integer/commit/43c981d2b1e57ee619a91a4231ebb55aad5cb751 which is in integer@2.0.0 and above.

**Comment by vashisth00** [comment]
What did you guys do to solve this?

**Comment by cclauss** [comment]
Upgrade to https://www.npmjs.com/package/integer ?
