### ISSUE TITLE
server.key causing security scanning to fail

### ISSUE THREAD

**Issue by mschile** [nodejs/node-gyp#2037]
Our security scanning is flagging this project due to it's inclusion of a private key in [server.key](https://github.com/nodejs/node-gyp/blob/master/test/fixtures/server.key). While I understand this key is only used in testing, what are the thoughts on excluding it from the package?

**Comment by cclauss** [comment]
Better to

**Comment by mschile** [comment]
@cclauss, I think some of your comment may have been cut-off.

**Comment by cclauss** [comment]
Sorry...  What is your recommendation for testing the key functionality with running afoul of your security scanner?

**Comment by mschile** [comment]
My recommendation would be to exclude the file from the package using either the `files` `package.json` property or an `.npmignore` file.

https://docs.npmjs.com/using-npm/developers.html#keeping-files-out-of-your-package

**Comment by rvagg** [comment]
> security scanning 

Maybe get better security scanning since this is a pretty odd false positive?

We're probably not going to be removing it from the package, we ship full test and doc functionality with packages and without the key it's not complete.

If you want, you could submit a PR that embeds it inline in the file that it (and the .key) are used in.

**Comment by psskalyan** [comment]
Whats the final outcome here, can anyone let me know, should we consider this as false positive?

**Comment by psskalyan** [comment]
If thats the case is there any way, where CredScan in Azure Devops pipeline can ignore this? Because it breaking the build when included

**Comment by rvagg** [comment]
If this is really causing headaches for people then you can contribute code that will obfuscate the file - embed it in a .js file and extract it as needed for tests; if it's written to disk then clean it up afterward. You probably should also bundle the .crt files as well for consistency.
