### ISSUE TITLE
Windows requires python 2.7.15, the build will fail if 3.8 is installed

### ISSUE THREAD

**Issue by StJohn3D** [nodejs/node-gyp#2041]
* **Node Version**:  Node v13.1.0 and npm 6.12.1
* **Platform**: 64bit (Windows)
* **Compiler**: `msbuild /version 5.2.2 & cl powershell` (Windows)
* **Module**: node-sass and then node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
  gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
```

</details>

Latest version of node installer will offer to install things like windows-build-tools and python. It installs the latest version of python. So I had both 2.7 and 3.8 installed and node-gyp was failing because it was finding 3.8. I had to uninstall the latest version of python to get node-gyp to work again. This feels very wrong. It's 2020, can we please get node-gyp compatible with the latest version of python? And until then the install instructions for windows should list python 2.7.15 as a requirement, not just for linux.

**Comment by richardlau** [comment]
`node-gyp` is compatible with Python 3. If you're using `node-sass` the issue is with them as they're still using older releases of `node-gyp`: https://github.com/sass/node-sass/issues/2716
