### ISSUE TITLE
Can't install utf-8-validate - if not defined npm_config_node_gyp

### ISSUE THREAD

**Issue by Thiedent** [nodejs/node-gyp#2043]
* **Node Version**: 8.1.0 NPM: 5.0.3
* **Platform**: Windows 7 and High Sierra 10.13.6
* **Compiler**: VS 2017 and VS 2015 / Xcode
* **Module**: utf-8-validate

I have the an installation failure error relating to the message "if not defined npm_config_node_gyp", after having successfully running npm install for a project on both a MAC and WINDOWS system, multiple times with no issue, yesterday both the machines starting throwing this same issue.
I had not changed anything about my system or the projects, only simply reinstalled them.

The package it stalls at is utf-8-validate.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
    utf-8-validate@5.0.1 install c:\browser-laptop\node_modules\utf-8-validate
    node-gyp-build

c:\browser-laptop\node_modules\utf-8-validate>if not defined npm_config_node_gyp
(node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\browser-laptop\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
validation.c
c:\browser-laptop\node_modules\utf-8-validate\src\validation.c(2): fatal error
C1083: Cannot open include file: 'node_api.h': No such file or directory [c:\br
owser-laptop\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Commu nity\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\browser-laptop\node_modules\node-g
yp\lib\build.js:262:23)
gyp ERR! stack at emitTwo (events.js:125:13)
gyp ERR! stack at ChildProcess.emit (events.js:213:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\browser-laptop\node
_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\browser-laptop\node_modules\utf-8-validate
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

</details>

I know the code C1083 is caused by out of date node headers which do not have the node_api.h. But using newer headers that overcome this error only create a further, lengthier chain of errors.
I recognize that the version of node i am using is very out of date, again this isn't a problem since it worked previously.

I must stress that both my MAC and WIN environments are setup correctly and that this issue is only a day old at best. While the issues on my WIN system may appear to be related to VS and VS build tools related configuration problems, i know that this is not the case since the exact same error appeared at the same time on my MAC. I wonder whether since it only changed on a reinstall whether its some dependancy of a dependancy that has been updated and thus broken it.

I would very much appreciate any help.

**Comment by cclauss** [comment]
Node 8 is no longer supported.

https://github.com/nodejs/Release/blob/master/README.md

**Comment by Thiedent** [comment]
My gosh i feel like an idiot, you are right upgrading is what did it. Thank you very much. Would you like me to delete this issue?
