### ISSUE TITLE
I was trying to run yarn install and got this error

### ISSUE THREAD

**Issue by FlintZheng** [nodejs/node-gyp#2050]
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command \"D:\\\\node\\\\node.exe\" \"D:\\\\node\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\zyg\\Desktop\\item\\blog\\blog_frontend\\node_modules\\node-pty
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>"
info This module is OPTIONAL, you can safely ignore this error

**Comment by FlintZheng** [comment]
Found solution:
 I use cnpm install instead

**Comment by bzoz** [comment]
The error message is simple `gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe ENOENT` - gyp can't find your VS installation. Anyway, I'm going to close this. Since cnpm solved this issue for you, it looks like a configuration issue.
