### ISSUE TITLE
Remove python 2.7 as requirement from the README.md

### ISSUE THREAD

**Issue by Pomax** [nodejs/node-gyp#2052]
Python 2.7 is dead. No "if"s, no "but"s, no "we're keeping it around because...": **it's well and truly dead**,

Given that [it got killed on January first, 2020](https://pythonclock.org/), which is nearing two months ago, can we remove it from the README.md as a valid requirement? (as well as everywhere else it's still being referenced?)

**Comment by cclauss** [comment]
Is the [`npm` package manager](https://github.com/npm/cli} which currently [embeds a v5 version of node-gyp](https://github.com/npm/cli/tree/latest/node_modules/node-gyp) fully capable of functioning properly on a Python 3 only box?  Would it have trouble with #2009?

**Comment by rvagg** [comment]
Yeah, it's still on 5.0.5 and unfortunately people are still directed here for details on what to install with native addons. Maybe once we get npm out with ^5.1.0 we can start being more aggressive with our README?

**Comment by Pomax** [comment]
Sounds like a plan, I've filed a feature request over on the npm issue tracker to bump that version to at least 5.1.0 .

**Comment by cclauss** [comment]
My bet is that this would be SemVer Major.  At what stage would it intersect
https://github.com/nodejs/release#nodejs-release-working-group ?

**Comment by richardlau** [comment]
> 
> 
> My bet is that this would be SemVer Major. At what stage would it intersect
> https://github.com/nodejs/release#nodejs-release-working-group ?

It doesn't? At least so far Release has not been involved with node-gyp.

**Comment by Pomax** [comment]
Not directly, but they'd have to decide whether an updated `npm` with python-3-only node-gyp requires a major semver update to Node, or whether it can slip in on a minor/patch release. Given that `node-gyp` is the defacto build system for Node, their awareness is certainly not something to discount.

I've filed https://github.com/nodejs/Release/issues/538 for that purpose.

**Comment by Pomax** [comment]
A correction on the timeline, I missed the fact that a press release [late last December](https://www.python.org/psf/press-release/pr20191220/) pushed the EOL date back to April 1st, so there's a few more weeks left before Python 2.7 is well and truly dead.

**Comment by filips123** [comment]
@Pomax Actually no.

EOL already happened on January 1. Development of Python 2.7 already stopped.

However, the last release will be in April, but EOL is still on January 1.

**Comment by cclauss** [comment]
The "bible" of these things is...
https://devguide.python.org/devcycle/#end-of-life-branches and
https://devguide.python.org/#status-of-python-branches

**Comment by Pomax** [comment]
Even better, thank you.

**Comment by duchanglong** [comment]
How to solve the
Output:
info sharp Using cached /Users/duchanglong/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.10.1 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.10.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/duchanglong/.nvm/versions/node/v13.10.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/duchanglong/Desktop/workspace/image2doc-processor-server/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/duchanglong/.nvm/versions/node/v13.10.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/duchanglong/Library/Caches/node-gyp/13.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/duchanglong/Library/Caches/node-gyp/13.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/duchanglong/.nvm/versions/node/v13.10.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/duchanglong/Library/Caches/node-gyp/13.10.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/duchanglong/Desktop/workspace/image2doc-processor-server/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/duchanglong/Library/Caches/node-gyp/13.10.1/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/duchanglong/Library/Caches/node-gyp/13.10.1/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/duchanglong/.nvm/versions/node/v13.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/duchanglong/.nvm/versions/node/v13.10.1/bin/node" "/Users/duchanglong/.nvm/versions/node/v13.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/duchanglong/Desktop/workspace/image2doc-processor-server/node_modules/sharp

Please help

**Comment by duchanglong** [comment]
![image](https://user-images.githubusercontent.com/53286673/82352843-2a2eb300-9a31-11ea-8efb-242b61e3fcc4.png)

**Comment by duchanglong** [comment]
![image](https://user-images.githubusercontent.com/53286673/82352895-3ca8ec80-9a31-11ea-8866-18aa238d2d78.png)
please help

**Comment by owl-from-hogvarts** [comment]
`README.md` does not contain any mention of python 2.7, so can this issue be closed?

**Comment by richardlau** [comment]
https://github.com/nodejs/node-gyp/pull/2300 removed Python 2 support.
