### ISSUE TITLE
Please unlock the issue that you specifically ask people to comment in.

### ISSUE THREAD

**Issue by coreyward** [nodejs/node-gyp#2056]
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md:

> 8. Add a comment to https://github.com/nodejs/node-gyp/issues/1927 so we can improve.

https://github.com/nodejs/node-gyp/issues/1927:

> Locking thread, this is collecting too many addon+node version incompatibility problems unrelated to Catalina, just because people are running Catalina. Please open new issues so we can try and be a bit more focused.

**Comment by rvagg** [comment]
fair enough, unlocked, but I think we should probably remove that note since Catalina is now getting more established out there

**Comment by coreyward** [comment]
Maybe, but it seems like this is an ongoing issue without a real lasting fix. It’s cost me significant time to fix on multiple occasions, even with the instructions here, because the solutions are temporary. I’ve had to replace fsevents versions in a dozen repos to work around this being broken to prevent teams I am on from losing similar time. A canonical, permanent, not based on “well gee this worked for me but I don’t know why” fix would be drastically better than a guessing game of documentation (especially since while I can install node-gyp fine, running it is problematic). This said, I don’t really even understand what a python build tool is doing as a part of Node, much less why the paths of various Xcode build tools seem to matter so much when they don’t affect anything else I run. 🤷‍♂️
