### ISSUE TITLE
node-gyp rebuild 在npm install时报错

### ISSUE THREAD

**Issue by sunxue421** [nodejs/node-gyp#2059]
mac  node版本：v10.8.0
执行  sudo npm install -g kbone-cli时 会报以下错误：

node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kbone-cli/node_modules/fsevents/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/kbone-cli/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/kbone-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by KyleTryon** [comment]
Running into the same issue with another node module. Running on ubuntu after I thought maybe it was an issue with WSL.

Node v12.10.0


```
techsquid@myhomeserver:~/Projects/SmartBoard$ sudo npm install --save rpi-led-matrix
> rpi-led-matrix@1.9.0 install /home/techsquid/Projects/SmartBoard/node_modules/rpi-led-matrix
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/techsquid/Projects/SmartBoard/node_modules/rpi-led-matrix/build'
gyp ERR! System Linux 4.4.0-173-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/techsquid/Projects/SmartBoard/node_modules/rpi-led-matrix
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN SmartBoard@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpi-led-matrix@1.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rpi-led-matrix@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/techsquid/.npm/_logs/2020-03-07T17_10_25_940Z-debug.log
```

**Comment by bnoordhuis** [comment]
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kbone-cli/node_modules/fsevents/build'

EACCES means node-gyp can't write to that directory and that's because npm drops privileges when it executes node-gyp. Don't run npm as root.

Closing, not really a node-gyp issue.
