### ISSUE TITLE
node-gyp rebuild: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by benlooning** [nodejs/node-gyp#206]
I've some issues while installing iconv via npm. I'm trying to install it on a Windows 8 Pro 64 bit pc. I also installed the pre requirements for node-gyp:
Python v2.7.3
Microsoft Visual Studio C++ 2012 for Windows Desktop (Express)

<pre>c:\workarea\nodejs\fbdialer>npm install iconv
npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/iconv

> iconv@2.0.2 install c:\workarea\nodejs\fbdialer\node_modules\iconv
> node-gyp rebuild

c:\workarea\nodejs\fbdialer\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot read property 'path' of undefined
gyp ERR! stack     at verifyMsbuild (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:143:50)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:163:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:538:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at maybeClose (child_process.js:638:16)
gyp ERR! stack     at Process._handle.onexit (child_process.js:680:5)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\workarea\nodejs\fbdialer\node_modules\iconv
gyp ERR! node -v v0.8.21
gyp ERR! node-gyp -v v0.8.4
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! iconv@2.0.2 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 7
npm ERR!
npm ERR! Failed at the iconv@2.0.2 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv"
npm ERR! cwd c:\workarea\nodejs\fbdialer
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\workarea\nodejs\fbdialer\npm-debug.log
npm ERR! not ok code 0

c:\workarea\nodejs\fbdialer>
</pre>

I figured out that it can't find the path for msbuild.exe in the registry even though I got this entry which points to a valid path:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0MSBuildToolsPath=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

I tried to provide a hardcoded path in build.js by adding the following line:
msbuildPath = 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe';

Now it seems that msbuild can be triggered but I got another issue:

<pre>c:\workarea\nodejs\fbdialer>npm install iconv
npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/iconv

> iconv@2.0.2 install c:\workarea\nodejs\fbdialer\node_modules\iconv
> node-gyp rebuild

c:\workarea\nodejs\fbdialer\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
c:\workarea\nodejs\fbdialer\node_modules\iconv\build\iconv.vcxproj(18,3): error MSB4019: Das importierte Projekt "c:\Microsoft.Cpp.Default.props" wurde nicht g
efunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\workarea\nodejs\fbdialer\node_modules\iconv
gyp ERR! node -v v0.8.21
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok
npm ERR! iconv@2.0.2 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the iconv@2.0.2 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv"
npm ERR! cwd c:\workarea\nodejs\fbdialer
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\workarea\nodejs\fbdialer\npm-debug.log
npm ERR! not ok code 0
</pre>

Did I miss something? Any idea?

**Comment by tj-redwolf** [comment]
@benlooning Are you able to resolve the issue?? as I am facing the same issue at missing msbuild.exe and in attempt to resolve that i face another issue of referencing to c:\Microsoft.Cpp.Default.props.

**Comment by benlooning** [comment]
@tj-redwolf No, I switched to linux, sorry :-).
