### ISSUE TITLE
Cache confuses Electron and Node with same version number. 

### ISSUE THREAD

**Issue by Yoann-Pearson** [nodejs/node-gyp#2066]
* **Node Version**: 12.6.1 
* **Platform**: OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
System Type:               x64-based PC 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

Calling this:
node-gyp rebuild --target=8.0.0 --arch=x64 --build_v8_with_gn=false 

for a module on my machine. 

Then, calling this:
node-gyp rebuild --target=8.0.0 --arch=x64 --build_v8_with_gn=false --dist-url=https://electronjs.org/headers

To build for Electron. Loading this .node file in my electron application produced this error:
was compiled against a different Node.js version using NODE_MODULE_VERSION 57. This version of Node.js requires NODE_MODULE_VERSION 76.

Erasing the cache folder 8.0.0 fixes the problem.

**Comment by Yoann-Pearson** [comment]
Yeah I think this is a duplicate of this old issue, sorry about that: https://github.com/nodejs/node-gyp/issues/1636

But no real solution was provided though except home/dist dir.

**Comment by richardlau** [comment]
@nodejs/node-gyp Probably semver-major, but what if we cached based on the NODE_MODULE_VERSION instead of Node.js version? There should be no clashes for current releases based on https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json (there may still be clashes for versions prior to the introduction of the ABI version registry).

**Comment by richardlau** [comment]
Let's keep the conversation over in https://github.com/nodejs/node-gyp/issues/1636.
