### ISSUE TITLE
Cannot work with Node.js 13

### ISSUE THREAD

**Issue by fengerzh** [nodejs/node-gyp#2068]
On Mac OSX, everytime npm install gyp, compile failed. Downgrade Node.js to 10 will work. But we need it to work with Node 13.

**Comment by fengerzh** [comment]
#1694 this error still exists.

**Comment by rvagg** [comment]
This is almost certainly a problem with the addon you're compiling, not a problem we can fix here. Find the repository of the addon that's failing to build, go to it's GitHub repo and ask there. You probably need a newer version of it, or they need to upgrade their code to work with newer versions of Node.js.
