### ISSUE TITLE
Support Python 3.8 or above

### ISSUE THREAD

**Issue by thanlok** [nodejs/node-gyp#2071]
Hi. Will `node-gyp` support python 3.8? Would really like it to run on the latest python version. Thank you

**Comment by cclauss** [comment]
Every pull request to `node-gyp` is [tested on GitHub Actions](https://github.com/nodejs/node-gyp/actions) on [Python 2.7, 3.6, 3.7, and 3.8](https://github.com/nodejs/node-gyp/blob/master/.github/workflows/Python_tests.yml#L14).  If you find compatibility problems, please open an issue here.
