### ISSUE TITLE
when i run 'npm i', 'node-gyp exited with code 1'

### ISSUE THREAD

**Issue by canon99** [nodejs/node-gyp#2077]
when i run 'npm i', 
'node-gyp exited with code 1'
i install node/npm by brew, how can i fix this...

`> jormougand@0.1.0 serve /Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand
> vue-cli-service serve

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'read-pkg'
Require stack:
- /Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/@vue/cli-service/lib/Service.js
- /Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/@vue/cli-service/lib/Service.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/@vue/cli-service/lib/Service.js',
    '/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jormougand@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jormougand@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2020-03-25T23_49_51_865Z-debug.log
 ✘  ~/go/src/gitlab.deepglint.com/deepglint/jormougand   master  rm -rf node_modules
 ~/go/src/gitlab.deepglint.com/deepglint/jormougand   master  cnpm i
⠹ [47/86] Installing prettier@^1.18.2[npminstall:runscript] @babel/cli@7.8.4 › chokidar@2.1.8 › fsevents@^1.2.7 found binding.gyp file, auto run "node-gyp rebuild", root: "/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_fsevents@1.2.12@fsevents"
⠇ [48/86] Installing postcss-selector-parser@^3.0.0  SOLINK_MODULE(target) Release/.node
⠙ [48/86] Installing stream-http@^2.7.2  CXX(target) Release/obj.target/fse/fsevents.o
⠏ [67/86] Installing stylelint-config-sass-guidelines@^6.1.0  SOLINK_MODULE(target) Release/fse.node
✔ Installed 86 packages
✔ Linked 1207 latest versions
[1/5] scripts.postinstall core-js@^3.1.2 run "node -e \"try{require('./postinstall')}catch(e){}\"", root: "/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_core-js@3.6.4@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[1/5] scripts.postinstall core-js@^3.1.2 finished in 65ms
[2/5] scripts.postinstall element-ui@2.13.0 › async-validator@1.8.5 › babel-runtime@6.26.0 › core-js@^2.4.0 run "node -e \"try{require('./postinstall')}catch(e){}\"", root: "/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_core-js@2.6.11@core-js"
[2/5] scripts.postinstall element-ui@2.13.0 › async-validator@1.8.5 › babel-runtime@6.26.0 › core-js@^2.4.0 finished in 64ms
[3/5] scripts.install @vue/cli-plugin-typescript@4.2.3 › yorkie@^2.0.0 run "node bin/install.js", root: "/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_yorkie@2.0.0@yorkie"
setting up Git hooks
done

[3/5] scripts.install @vue/cli-plugin-typescript@4.2.3 › yorkie@^2.0.0 finished in 109ms
[4/5] scripts.install fibers@^3.1.1 run "node build.js || nodejs build.js", root: "/Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_fibers@3.1.1@fibers"
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:68:2: error: no template named 'Handle'
        Handle<String> NewLatin1String(Isolate* isolate, const char* string) {
        ^
../src/fibers.cc:69:10: error: no viable conversion from returned value of type
      'Local<v8::String>' to function return type 'int'
  ...String::NewFromOneByte(isolate, (const uint8_t*)string, NewStringType::kNormal).ToLocalChecked();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:72:2: error: no template named 'Handle'
        Handle<String> NewLatin1Symbol(Isolate* isolate, const char* string) {
        ^
../src/fibers.cc:73:10: error: no viable conversion from returned value of type
      'Local<v8::String>' to function return type 'int'
  ...String::NewFromOneByte(isolate, (const uint8_t*)string, NewStringType::kNormal).ToLocalChecked();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:94:2: error: no template named 'Handle'
        Handle<Object> NewInstance(Isolate* isolate, Local<Function> fn, int arg...
        ^
../src/fibers.cc:95:10: error: no viable conversion from returned value of type
      'Local<v8::Object>' to function return type 'int'
  ...fn->NewInstance(isolate->GetCurrentContext(), argc, argv).ToLocalChecked();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:104:2: error: no template named 'Handle'
        Handle<Number> ToNumber(Local<Value> value) {
        ^
../src/fibers.cc:105:10: error: no viable conversion from returned value of type
      'Local<v8::Number>' to function return type 'int'
  ...value->ToNumber(Isolate::GetCurrent()->GetCurrentContext()).ToLocalChecked();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:114:50: error: no template named 'Handle'
        Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
                                                        ^
../src/fibers.cc:127:39: error: no template named 'Handle'
        void fixStackLimit(Isolate* isolate, Handle<Context> context) {
                                             ^
../src/fibers.cc:149:58: error: no template named 'Handle'
        void Reset(Isolate* isolate, Persistent<T>& persistent, Handle<T> handle) {
                                                                ^
../src/fibers.cc:162:7: error: variable has incomplete type 'void'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
             ^
../src/fibers.cc:162:26: error: use of undeclared identifier 'Handle'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                ^
../src/fibers.cc:162:33: error: 'T' does not refer to a value
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                       ^
../src/fibers.cc:161:18: note: declared here
        template <class T>
                        ^
../src/fibers.cc:162:36: error: use of undeclared identifier 'handle'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                          ^
../src/fibers.cc:162:48: error: expected
      '(' for function-style cast or type construction
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                  ~~~ ^
../src/fibers.cc:162:59: error: expected
      '(' for function-style cast or type construction
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                             ~~~~^
../src/fibers.cc:162:61: error: use of undeclared identifier 'val'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                                   ^
../src/fibers.cc:162:65: error: expected ';' at end of declaration
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                                       ^
                                                                       ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/13.11.0/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/leo/go/src/gitlab.deepglint.com/deepglint/jormougand/node_modules/_fibers@3.1.1@fibers
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs：未找到命令
[npminstall:runscript:error] fibers@^3.1.1 scripts.install run "node build.js || nodejs build.js" error: Error [RunScriptError]: Run "sh -c node build.js || nodejs build.js" error, exit code 127
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  name: 'RunScriptError',
  stdio: [Object]
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node build.js || nodejs build.js" error, exit code 127
RunScriptError: Run "sh -c node build.js || nodejs build.js" error, exit code 127
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npminstall version: 3.27.0
npminstall args: /usr/local/Cellar/node/13.11.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/leo/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org`

**Comment by cclauss** [comment]
`npm install -g npm`

You will definitely want a more up-to-date version than `gyp ERR! node-gyp -v v3.8.0`.
https://github.com/nodejs/node-gyp/releases
