### ISSUE TITLE
gyp error

### ISSUE THREAD

**Issue by varshith97** [nodejs/node-gyp#2079]
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/varshith/Desktop/vars/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

**Comment by cclauss** [comment]
Further up in the log, is it trying to use Python 2 or Python 3.  If Python 3, then please try to `upgrade node-gyp` because there were a lot of Python 3 changes in that timeframe that were fixed in the following releases https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md
