### ISSUE TITLE
Unable to install 'time' module using npm. 

### ISSUE THREAD

**Issue by Sameeh456** [nodejs/node-gyp#2088]
Hi, I am trying to install necessary dependencies for a project. When installing time module, I am getting the following error. I have tried updating npm and gyp rebuild, but didn't solve the problem. Can someone give me a solution for this?

    I:\Blog Application\StreamingProgram>npm install time
    
    > time@0.12.0 install I:\Blog Application\StreamingProgram\node_modules\time
    > node-gyp rebuild
    
    
    I:\Blog Application\StreamingProgram\node_modules\time>if not defined npm_config_node_gyp (node "C:\Users\Administrator.Sameeh\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
     else (node "C:\Users\Administrator.Sameeh\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
      time.cc
      win_delay_load_hook.cc
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(12): error C2061: syntax error: identifier 'Handle' [I:\Blog A
    pplication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(16): error C2065: 'target': undeclared identifier [I:\Blog App
    lication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(19): error C2065: 'target': undeclared identifier [I:\Blog App
    lication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(22): error C2065: 'target': undeclared identifier [I:\Blog App
    lication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(25): error C2065: 'target': undeclared identifier [I:\Blog App
    lication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(87): error C2660: 'v8::Value::IntegerValue': function does not
     take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2609): note: see declaration of 'v8::Value
      ::IntegerValue' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(141): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(142): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(143): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(144): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(145): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(146): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(147): error C2660: 'v8::Value::Int32Value': function does not 
    take 0 arguments [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(2613): note: see declaration of 'v8::Value
      ::Int32Value' (compiling source file ..\src\time.cc)
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(156): error C2065: 'Handle': undeclared identifier [I:\Blog Ap
    plication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(156): error C2275: 'v8::Object': illegal use of this type as a
    n expression [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
      c:\users\administrator.sameeh\appdata\local\node-gyp\cache\12.13.1\include\node\v8.h(3400): note: see declaration of 'v8::Objec
      t'
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(156): error C2065: 'target': undeclared identifier [I:\Blog Ap
    plication\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(156): error C2182: 'init': illegal use of type 'void' [I:\Blog
     Application\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(156): error C2448: 'init': function-style initializer appears 
    to be a function definition [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
    i:\blog application\streamingprogram\node_modules\time\src\time.cc(159): warning C4312: 'type cast': conversion from 'int' to 'no
    de::addon_register_func' of greater size [I:\Blog Application\StreamingProgram\node_modules\time\build\time.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with
    exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator.Sameeh\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Windows_NT 10.0.17134
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator.Sameeh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd I:\Blog Application\StreamingProgram\node_modules\time
    gyp ERR! node -v v12.13.1
    gyp ERR! node-gyp -v v6.1.0
    gyp ERR! not ok
    npm WARN enoent ENOENT: no such file or directory, open 'I:\Blog Application\StreamingProgram\package.json'
    npm WARN StreamingProgram No description
    npm WARN StreamingProgram No repository field.
    npm WARN StreamingProgram No README data
    npm WARN StreamingProgram No license field.
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! time@0.12.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the time@0.12.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bzoz** [comment]
Nothing looks broken here. You should report this in the `time` module issue tracker.
