### ISSUE TITLE
MSBuild.exe ENOENT

### ISSUE THREAD

**Issue by SetWeather** [nodejs/node-gyp#2099]
* **Node Version**: v12.16.2
* **Platform**: Microsoft Windows 7 Ultimate x64-based PC
* **Module**: npm install brain.js

<pre>
<code>
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nazar\\AppData\\Roaming\\nvm\\v12.16.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nazar\Desktop\Sigma\node_modules\gl
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN sigma@1.0.0 No description
npm WARN sigma@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gl@4.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the gl@4.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nazar\AppData\Roaming\npm-cache\_logs\2020-04-16T13_58_43_089Z-debug.log
</pre>
</code>

<pre>
<code>
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
</pre>
</code>

I try to install brain.js and it throws this error.
I installed full VS2019 and visual 2019 C++ Build tools, also tried to apply all the tips of other articles, but all in vain. I hope for your help

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/issues/1753#issuecomment-501827267

**Comment by SetWeather** [comment]
@cclauss thx) But I have a new error:
```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nazar\node_modules\gl
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nazar\package.json'
npm WARN nazar No description
npm WARN nazar No repository field.
npm WARN nazar No README data
npm WARN nazar No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gl@4.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the gl@4.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by banksdev** [comment]
Does anyone have a fix for this?

**Comment by cclauss** [comment]
> gyp ERR! System Windows_NT 6.1.7601
> npm ERR! code ELIFECYCLE

https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020

**Comment by SetWeather** [comment]
@banksdev  I changed the version Node.js 10.20.0 using NVM. But still got an error again:
 ```
Error: Cannot find module
C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nazar\AppData\Roaming\npm-cache\_logs\2020-04-18T20_43_05_877Z-debug.log
```

**Comment by cclauss** [comment]
Your OS is no longer supported.  Given `npm ERR! Failed at the gl@4.5.0 install script.`, you might open an issue at https://github.com/stackgl/headless-gl and see if they are willing to support an operating system that is end of life.
