### ISSUE TITLE
Make the dev installation directory configurable (~/.node-gyp)

### ISSUE THREAD

**Issue by TooTallNate** [nodejs/node-gyp#21]
Not a real high priority to me, but :+1: if you want this feature.

**Comment by rafi** [comment]
Until you guys decide, it'll be great if you offer an environment variable or npm style config, _e.g._
```ini
cache  = ${XDG_CACHE_HOME}/node-gyp
```
:)

**Comment by dantran** [comment]
where are we with this issue??. Dont meant to brag, but the discusion started in 2012 :-)

**Comment by jmesmon** [comment]
Having an env-var as @mindon suggested would be useful for me as well. Not clear how to adjust the way npm calls node-gyp.

**Comment by terinjokes** [comment]
@TooTallNate echoing @jmesmon I don't know of a good way to change how npm calls node-gyp for me to add the `--nodedir` header. Can we get this as an environment option?

**Comment by bnoordhuis** [comment]
@terinjokes You can pass `--nodedir` to npm and npm will pass it on to node-gyp.  Alternatively, you can set `npm_config_nodedir=/path/to/sources` in the environment.

**Comment by terinjokes** [comment]
@bnoordhuis I had just edited my comment to point that out.

**Comment by jcrben** [comment]
Does npm support `npm_config_devdir`? I tried to test but not really sure how all this stuff is tied together.

**Comment by bnoordhuis** [comment]
It should.  npm passes on options it doesn't consume itself.

**Comment by develar** [comment]
Since electron-builder 18.4.0 ugly solution HOME env will be not used anymore. Because in this case cache dir is doubled (yarn and npm have to download and cache deps twice). Thanks! `--devdir` and `npm_config_devdir` works in my tests. I will risk to roll out this update to users. Thanks again that now node-gyp allows to set devdir.

**Comment by jcrben** [comment]
never ended up figuring out how this works - I suppose I might dig into it someday... these were the steps, expecting `npm install -g node-gyp` to put ~/.node-gyp into the devdir (which I'm setting with `export npm_config_devdir="$XDG_CACHE_HOME"/.node-gyp` in my `.bashrc` on OSX
![image](https://user-images.githubusercontent.com/5614134/36059216-6949d8d0-0de8-11e8-9101-ce6a1b57989e.png)

@jasonkarns fyi, for me, it doesn't seem like ~/.node-gyp is cache data - it's got include files and stuff to run applications, I suppose in XDG it would end up in XDG_DATA_HOME or something

**Comment by mighty9245** [comment]
https://github.com/nodejs/node-gyp/blob/470f04efebbd05fee38b85202d1a830c90382c45/lib/node-gyp.js#L41-L45

found this issue while digging the source code on how it works. yeah, can we have a environment variable or something to move this folder? i don't want to keep this at my home folder and i've already moved almost anything in corresponding folders ($XDG_CONFIG_HOME, $XDG_CACHE_HOME and $XDG_DATA_HOME)

**Comment by richardlau** [comment]
@mighty9245 You should be able to use the `--devdir` parameter if manually invoking `node-gyp` or set the `npm_config_devdir` environment variable to change the folder.

**Comment by mighty9245** [comment]
oh, so it was implemented? sorry, looked through readme, source code and several posts in this issue since i'm not working with node-gyp and something that i built created this directory and i just wanted to prevent this in future. ok, i'll try that, thanks!
