### ISSUE TITLE
 stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by apemen** [nodejs/node-gyp#2102]
C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\8.2.3\\x64\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x54A7C [D
:\project\electron2\node_modules\usb\build\usb_bindings.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1gyp ERR! stack     at ChildProcess.onExit (E:\nodejs\node_global\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nodejs\\node_global\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.3" "--arch=x64" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd D:\project\electron2\node_modules\usb
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

when i try "node-gyp rebuild --target=8.2.3 --arch=x64 --dist-url=https://atom.io/download/electron"  and i get this error. what's the matter

**Comment by bzoz** [comment]
Please use the issue template. We cannot help you if you don't provide the required information.
