### ISSUE TITLE
Issue when building in VS 2019

### ISSUE THREAD

**Issue by rsapko** [nodejs/node-gyp#2111]
node 14.0.0
npm 6.14.4
Microsoft Windows 10 Pro
10.0.17763 N/A Build 17763

error gyp ERR! UNCAUGHT EXCEPTION 
EXEC(0,0): Error : spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rob_s\\source\\repos\\IEvangelist.VideoChat\\ClientApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\rob_s\source\repos\IEvangelist.VideoChat\ClientApp\node_modules\node-sass
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
EXEC(0,0): Error code: 7

**Comment by cclauss** [comment]
Please update npm.

**Comment by malis90** [comment]
same here
any idea how to fix it?

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\OfficeWork\\project\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\OfficeWork\project\node_modules\node-sass
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**Comment by cclauss** [comment]
`gyp ERR! node-gyp -v v3.8.0`  # is too old vs.
https://github.com/nodejs/node-gyp/releases

Please try: `npm update -g npm`
Then see if your command (which you did not provide in you post above) works.  If there is no success then try https://github.com/nodejs/node-gyp/issues/2111#issuecomment-622515316
