### ISSUE TITLE
npm install fails due to node-gyp errors

### ISSUE THREAD

**Issue by ShubhamB99** [nodejs/node-gyp#2113]
* **Node Version**: v14.1.0
* **Platform**: Microsoft Windows 10 Home, 10.0.18363 Build 10.0.18363
* **Compiler**: MSBuild 15.0, using VS 2019 and Python 3
* **Module**: Any module, in this case robotjs

<details><summary>Verbose output (from npm or node-gyp):</summary>

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\nodejs\\node.exe',
npm verb cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.4
npm info using node@v14.1.0

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\Shubham Bhardwaj\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.4 C:\nvm\v14.1.0\node_modules\npm

</details>

<details> <summary> Error Description </summary>
> robotjs@0.6.0 install C:\nodejs\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.1.0 runtime=node arch=x64 libc= platform=win32)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nodejs\node_modules\robotjs
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shubham Bhardwaj\AppData\Roaming\npm-cache\_logs\2020-05-03T09_31_41_003Z-debug.log
</details>

_I tried a lot of solutions, but of no use.
Please guide the way forward. I've been stuck on this for 2-3 days now._

**Comment by ShubhamB99** [comment]
@cclauss @vadimpopa Can you suggest some way out please?

**Comment by bzoz** [comment]
What do you get when you run
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
```
(include the quotes) in the console?

**Comment by Youkko** [comment]
> What do you get when you run
> 
> ```
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
> ```
> 
> (include the quotes) in the console?

Same problem here.
I've run MSBuild.exe.

Here's the output:

C:\Work\Ionic>"c:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe"
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

**Comment by ShubhamB99** [comment]
@bzoz I get the same output on the console as @Youkko ! Any insight on what's causing this?

**Comment by nandas** [comment]
I am also getting same issue. anyone tried a lower version than 2019 MsVS?

**Comment by cclauss** [comment]
@octalmage Any ideas?

**Comment by nandas** [comment]
I dont know if I am going in the correct direction. But I installed MSVS 20115 yesterday and retried

I am getting a different error now because of node-pty

MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution".

**Comment by Youkko** [comment]
Got rid of this error by changing Node.JS version.

**Comment by TulasiJagan49** [comment]
> What do you get when you run
> 
> ```
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
> ```
> 
> (include the quotes) in the console?

I'm getting this: "The system cannot find the path specified."

**Comment by Youkko** [comment]
> > What do you get when you run
> > ```
> > "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
> > ```
> > 
> > 
> > (include the quotes) in the console?
> 
> I'm getting this: "The system cannot find the path specified."

Make sure you have that Visual Studio version. You're trying to execute MSBuild.exe from Visual Studio Community edition's folder. Do you have it installed in this folder?
I use Visual Studio Professional, so mine is in a different folder
(c:\Program Files (x86)\Microsoft Visual Studio\2019\ **Professional** \MSBuild\Current\Bin\MSBuild.exe)
Change this file location to your visual studio folder and you should get it.

**Comment by bzoz** [comment]
@ShubhamB99 could you provide the entire verbose log including the command you are using? Add `--verbose` to whatever npm command you are using that causes this issue.

@Youkko @TulasiJagan49, @nandas your issues could be completely unrelated. Please provide the entire verbose log and your system configuration - basically fill out the issue template. Fell free to open separate issues.

@nandas VS2019 works just fine with node-gyp, no need to downgrade.

**Comment by jabbar86** [comment]
```gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@14.9.0 | win32 | x64
gyp info find Python using Python version 3.8.5 found at "C:\Python38\python.exe"
gyp info find VS using VS2019 (16.7.30523.141) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\jabba\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Zoop\\zoop-product-v0\\src\\node_modules\\x509\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jabba\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jabba\\AppData\\Local\\node-gyp\\Cache\\14.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jabba\\AppData\\Local\\node-gyp\\Cache\\14.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jabba\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jabba\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.9.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\Zoop\\zoop-product-v0\\src\\node_modules\\x509',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\Zoop\\zoop-product-v0\\src\\node_modules\\x509\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
E:\Zoop\zoop-product-v0\src\node_modules\x509\build\x509.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jabba\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jabba\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Zoop\zoop-product-v0\src\node_modules\x509```

Getting this error 
node : 14.9.0
python : 3.8
visual studio : 2019

**Comment by owl-from-hogvarts** [comment]
Is this issue is solved?

**Comment by gideonm-pangea** [comment]
@owl-from-hogvarts no

**Comment by Ematusz** [comment]
@ShubhamB99 did you ever solve this issue? I know it was a while ago but I am running into a very similar problem now.

**Comment by Jabbar-Memon** [comment]
> 
> 
> @ShubhamB99 did you ever solve this issue? I know it was a while ago but I am running into a very similar problem now.

You can try this. https://github.com/nodejs/node-gyp/issues/2113#issuecomment-703753272

**Comment by owl-from-hogvarts** [comment]
@gideonm-pangea what are you trying to do (provide a command you are trying to run, but with `--verbose` flag). And then provide the output of command. Please, formate output as code snippet (put it into ``` (triple back qoute before and after command output))

**Comment by gideonm-pangea** [comment]
@owl-from-hogvarts I myself am not currently having this issue but I do remember that I fixed it, don't remember how. it seems like these errors aren't caused by a bug but by node-gyp being improperly set up by the user, but I do think that maybe the error messages should be a bit more descriptive as to the error and the solution.

**Comment by reduardo7** [comment]
How I can make it work?

**Comment by owl-from-hogvarts** [comment]
Hey! I found hitch! Look closer: `Microsoft\VC\v160\\Microsoft.Cpp.Default.props`! `\\` cause the error! @cclauss @rvagg Sorry for pings but i hope it's worth it

**Comment by owl-from-hogvarts** [comment]
@reduardo7 what npm version do you use?

**Comment by reduardo7** [comment]
@owl-from-hogvarts Thank you for your help!

Here more details:

```bash
+ npm -v
8.1.2
+ node -v
v16.13.1
```

```
npm ERR! code 1
npm ERR! path /home/runner/work/conversifi-web/conversifi-web/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /home/runner/work/conversifi-web/conversifi-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! make: Entering directory '/home/runner/work/conversifi-web/conversifi-web/node_modules/node-sass/build'
npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/home/runner/.node-gyp/16.13.1/include/node -I/home/runner/.node-gyp/16.13.1/src -I/home/runner/.node-gyp/16.13.1/deps/openssl/config -I/home/runner/.node-gyp/16.13.1/deps/openssl/openssl/include -I/home/runner/.node-gyp/16.13.1/deps/uv/include -I/home/runner/.node-gyp/16.13.1/deps/zlib -I/home/runner/.node-gyp/16.13.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp

npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/home/runner/.node-gyp/16.13.1/include/node -I/home/runner/.node-gyp/16.13.1/src -I/home/runner/.node-gyp/16.13.1/deps/openssl/config -I/home/runner/.node-gyp/16.13.1/deps/openssl/openssl/include -I/home/runner/.node-gyp/16.13.1/deps/uv/include -I/home/runner/.node-gyp/16.13.1/deps/zlib -I/home/runner/.node-gyp/16.13.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/values.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/values.o ../src/libsass/src/values.cpp
npm ERR!   rm -f Release/obj.target/src/sass.a && ar crs Release/obj.target/src/sass.a Release/obj.target/libsass/src/libsass/src/ast.o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o Release/obj.target/libsass/src/libsass/src/backtrace.o Release/obj.target/libsass/src/libsass/src/base64vlq.o Release/obj.target/libsass/src/libsass/src/bind.o Release/obj.target/libsass/src/libsass/src/cencode.o Release/obj.target/libsass/src/libsass/src/check_nesting.o Release/obj.target/libsass/src/libsass/src/color_maps.o Release/obj.target/libsass/src/libsass/src/constants.o Release/obj.target/libsass/src/libsass/src/context.o Release/obj.target/libsass/src/libsass/src/cssize.o Release/obj.target/libsass/src/libsass/src/emitter.o Release/obj.target/libsass/src/libsass/src/environment.o Release/obj.target/libsass/src/libsass/src/error_handling.o Release/obj.target/libsass/src/libsass/src/eval.o Release/obj.target/libsass/src/libsass/src/expand.o Release/obj.target/libsass/src/libsass/src/extend.o Release/obj.target/libsass/src/libsass/src/file.o Release/obj.target/libsass/src/libsass/src/functions.o Release/obj.target/libsass/src/libsass/src/inspect.o Release/obj.target/libsass/src/libsass/src/json.o Release/obj.target/libsass/src/libsass/src/lexer.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory/SharedPtr.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/operators.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/subset_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
npm ERR!   rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
npm 
lerna ERR! npm install --no-save --production exited 1 in 'conversifi-web'
Error: Process completed with exit code 1.
```

**Comment by cclauss** [comment]
[node-sass](https://github.com/nodejs/node-gyp/tree/master/docs#node-sass-is-deprecated)

**Comment by BjornSkarsgard** [comment]
Not working, help me please. Im installing tars-cli and get errors. (python - inst, Visual studio installer and C++ - inst )

npm ERR! code 1
npm ERR! path C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=      
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\WEB\skardev.v2\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\WEB\skardev.v2\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\WEB\skardev.v2\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2.7 Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\WEB\skardev.v2\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\WEB\skardev.v2\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\WEB\skardev.v2\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\WEB\skardev.v2\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python2.7". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
npm ERR! gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.1
npm ERR! gyp verb command install [ '16.13.1' ]
npm ERR! gyp verb install input version string "16.13.1"
npm ERR! gyp verb install installing version: 16.13.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.1
npm ERR! gyp verb build dir attempting to create "build" dir: C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass\build
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
npm ERR! gyp verb find vs2017   - Using this installation with Windows 10 SDK
npm ERR! gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass\build\config.gypi
npm ERR! (node:8656) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Skar\\.node-gyp\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Skar\\.node-gyp\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Skar\\.node-gyp\\16.13.1\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\Skar\.node-gyp\16.13.1
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WEB\\skardev.v2\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\WEB\skardev.v2\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0

https://github.com/nodejs/node-gyp/tree/master/docs#versions-of-node-gyp-that-are-earlier-than-v8xx
