### ISSUE TITLE
Compiler doesn't find librt.so

### ISSUE THREAD

**Issue by MaxHausmann** [nodejs/node-gyp#2117]
Hi there,

I am trying to use boost interprocess (header only) library. The compiling itself
runs perfectly, but the node script crashes by showing the message:

`node: symbol lookup error: /home/[...]/image_processing_interface/build/Release/image_processing_interface.node: undefined symbol: shm_unlink`

The method shm_unlink is from the "mman.h"-lib, a linux standard lib, as you know. I guess boost
calls it to allocate a managed shared memory segment.

Basically (without the node-specific things) the source-code is like this:

```cpp
#include <boost/interprocess/managed_shared_memory.hpp>
#include <iostream>
#include "SLY_register_settings.hpp"

using namespace boost::interprocess;
using namespace std;

int main()
{
    //allocate the absolute minium of memory
    shared_memory_object::remove(SALLY_SHARED_MEM);
    managed_shared_memory sharedMem{open_or_create, SALLY_SHARED_MEM, mapped_region::get_page_size()};
    bool *sharedRegAlloc = sharedMem.find_or_construct<bool>(SIPR_REGISTER)[16](false);
    interprocess_mutex *mutex = sharedMem.find_or_construct<interprocess_mutex>(SALLY_MUTEX)();
}
```
Compiling with the standard g++ compiler works and it runs also.

Maybe an issue or you have some tip for me?

**Comment by MaxHausmann** [comment]
I found the reason for this problem by compiling with g++ and looking for the paths of the libs.
The missing library was librt: "/lib/x86_64-linux-gnu/librt.so".
But I used already the "-fno-rtti"-flag. My binding.gyp looks now like this:

```
{
    "targets": [{
        "target_name": "image_processing_interface",
        "cflags_cc!": ["-fno-exceptions", "-fno-rtti"],
        "sources": [
            "main.cpp",
            "SLY_async_worker.cpp"
        ],
        'include_dirs': [
            "<!@(node -p \"require('node-addon-api').include\")",
            "/usr/include/boost",
        ],
        'libraries': [
            "/lib/x86_64-linux-gnu/librt.so",
        ],
        'dependencies': [
            "<!(node -p \"require('node-addon-api').gyp\")",
        ],
    }]
}
```
Maybe the flag is wrong or the compiler can't find it. Any suggestions?

**Comment by bnoordhuis** [comment]
@MaxHausmann librt is part of glibc, it houses a number of auxiliary functions (aio, clock/timer functions and, notably, POSIX message queues, what boost::interprocess is undoubtedly using.)

Adding `'libraries': ['-lrt']` should fix it.

**Comment by MaxHausmann** [comment]
Okay, despite "-fno-rtti"? Because I thought that is for using such libraries? (Without it, my program won't compile at all).

**Comment by MaxHausmann** [comment]
Thank you, that fixed it!

**Comment by bnoordhuis** [comment]
@MaxHausmann `-fno-rtti` is not in any way related to librt. It stops the compiler from emitting (most) Runtime Type Information, what you need to make C++'s `dynamic_cast` work.
