### ISSUE TITLE
npm installing issue

### ISSUE THREAD

**Issue by yash2708** [nodejs/node-gyp#2118]
> bufferutil@3.0.5 install D:\JPMC\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

D:\JPMC\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\JPMC\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yashj\AppData\Roaming\npm-cache\_logs\2020-05-08T17_25_59_163Z-debug.log

**Comment by cclauss** [comment]
`gyp ERR! node-gyp -v v3.8.0`  # is too old.

**Comment by yash2708** [comment]
i upgraded the node-gyp now its 6.1.0 but its still not working and showing the same error

**Comment by yash2708** [comment]
the file bufferutil is not there in my node-models but it is still trying to install it

**Comment by yash2708** [comment]
D:\JPMC\JPMC-tech-task-2-PY3\node_modules\bufferutil there is no such directory in my module

**Comment by cclauss** [comment]
> gyp ERR! node -v v11.0.0
Is also no longer supported https://nodejs.org/en/about/releases/

Given your directory name contains PY3, please use relatively current releases of Node.js because it’s Python 3 support was completed in the second half of 2019.

**Comment by yash2708** [comment]
108 warn @jpmorganchase/perspective@0.2.12 requires a peer of webpack@>=3.5 <4 but none is installed. You must install peer dependencies yourself.
109 warn uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
110 warn bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
111 warn bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
112 warn extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
113 verbose stack Error: bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
113 verbose stack Exit status 1
113 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
113 verbose stack     at EventEmitter.emit (events.js:310:20)
113 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
113 verbose stack     at ChildProcess.emit (events.js:310:20)
113 verbose stack     at maybeClose (internal/child_process.js:1021:16)
113 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
114 verbose pkgid bufferutil@3.0.5
115 verbose cwd D:\JPMC\JPMC-tech-task-2-PY3
116 verbose Windows_NT 10.0.18363
117 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
118 verbose node v12.16.3
119 verbose npm  v6.14.4
120 error code ELIFECYCLE
121 error errno 1
122 error bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
122 error Exit status 1
123 error Failed at the bufferutil@3.0.5 install script.
123 error This is probably not a problem with npm. There is likely additional logging output above.
124 verbose exit [ 1, true ]

**Comment by yash2708** [comment]
this is the latest log after all upgradations

**Comment by cclauss** [comment]
https://www.npmjs.com/package/bufferutil @4.0.1 ?

**Comment by yash2708** [comment]
i guess there is some prb with the packasge...anyways thanku for your help

**Comment by chaseroldan** [comment]
The nodes_module folder is missing. Just add that folder from the troubleshooting section to the JPMC task folder.

**Comment by champ2461** [comment]
bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild'????

**Comment by cclauss** [comment]
https://www.npmjs.com/package/bufferutil @4.0.6 ?

**Comment by champ2461** [comment]
Cannot find module '@jpmorganchase/perspective'.  TS2307

**Comment by champ2461** [comment]
./src/index.tsx
Module not found: Can't resolve 'react' in 'C:\Users\user\OneDrive\Desktop\jp_morgan\JPMC-tech-task-2\src'

**Comment by champ2461** [comment]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules\@npmcli\fs\lib\fs.js:6:23)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:707:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:605:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:643:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
gyp ERR! stack     at Object.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules\@npmcli\fs\lib\index.js:2:6)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:707:30)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\OneDrive\Desktop\jp_morgan\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2022-07-16T18_45_10_570Z-debug.log

**Comment by htran844** [comment]
> gyp ERR! UNCAUGHT EXCEPTION gyp ERR! stack TypeError: Object.fromEntries is not a function gyp ERR! stack at Object. (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules@npmcli\fs\lib\fs.js:6:23) gyp ERR! stack at Module._compile (internal/modules/cjs/loader.js:707:30) gyp ERR! stack at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10) gyp ERR! stack at Module.load (internal/modules/cjs/loader.js:605:32) gyp ERR! stack at tryModuleLoad (internal/modules/cjs/loader.js:544:12) gyp ERR! stack at Function.Module._load (internal/modules/cjs/loader.js:536:3) gyp ERR! stack at Module.require (internal/modules/cjs/loader.js:643:17) gyp ERR! stack at require (internal/modules/cjs/helpers.js:22:18) gyp ERR! stack at Object. (C:\Users\user\AppData\Roaming\nvm\v11.0.0\node_modules\node-gyp\node_modules@npmcli\fs\lib\index.js:2:6) gyp ERR! stack at Module._compile (internal/modules/cjs/loader.js:707:30) gyp ERR! System Windows_NT 10.0.22000 gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js" "rebuild" gyp ERR! cwd C:\Users\user\OneDrive\Desktop\jp_morgan\JPMC-tech-task-2\node_modules\bufferutil gyp ERR! node -v v11.0.0 gyp ERR! node-gyp -v v9.1.0 gyp ERR! Node-gyp failed to build your package. gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author. npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself. npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself. npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE npm ERR! errno 7 npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild` npm ERR! Exit status 7 npm ERR! npm ERR! Failed at the bufferutil@3.0.5 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\user\AppData\Roaming\npm-cache_logs\2022-07-16T18_45_10_570Z-debug.log

**I got same issue. How to fix that?** 
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> bufferutil@3.0.5 install D:\VLS2\app\node_modules\bufferutil
> prebuild-install || node-gyp rebuild


D:\VLS2\app\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Error output:
prebuild-install WARN install No prebuilt binaries found (target=3.0.13 runtime=electron arch=x64 platform=win32)
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
gyp ERR! stack     at Unpack.afterTarball (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:211:21)
gyp ERR! stack     at Unpack.emit (events.js:198:13)
gyp ERR! stack     at Unpack.[maybeClose] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\unpack.js:171:12)
gyp ERR! stack     at Unpack.opt.ondone._ (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\unpack.js:89:23)
gyp ERR! stack     at Unpack.emit (events.js:198:13)
gyp ERR! stack     at Unpack.[emit] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:230:12)
gyp ERR! stack     at Unpack.[maybeEnd] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:346:17)
gyp ERR! stack     at Unpack.[consumeChunk] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:375:21)
gyp ERR! stack     at Unpack.write (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:310:25)
gyp ERR! stack     at Unpack.end (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:419:14)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\VLS2\app\node_modules\bufferutil
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.0.3
