### ISSUE TITLE
Building an asan nodejs c++ addon with node-gyp won't work

### ISSUE THREAD

**Issue by oldmtn** [nodejs/node-gyp#2136]
how to build a c++ nodejs addon.
I used below config to build nodejs addon.

>       'xcode_settings': {
>         'OTHER_LDFLAGS': [
>           '-fsanitize=address',
>           '-fsanitize-recover=address',
>           '-fno-omit-frame-pointer',
>           '-O1'
>         ],
>         'MACOSX_DEPLOYMENT_TARGET': '10.13',
>         "GCC_GENERATE_DEBUGGING_SYMBOLS": "YES",
>         "DEBUG_INFORMATION_FORMAT": "dwarf-with-dsym",
>         'FRAMEWORK_SEARCH_PATHS': [
>           './sdk/mac',
>           './sdk/mac/frameworks'
>         ]
>       },

and then create a boom code as below:

> int *array = new int[100];
> delete [] array;
> int t1 = array[5];  // BOOM
> 
> array[9] = 12;

But above code won't crash.
Why?

BTW:
I don't use the official electron version, I use an asan electron build by myself.

**Comment by bnoordhuis** [comment]
OTHER_LDFLAGS are linker flags. You're probably looking for OTHER_CFLAGS or OTHER_CPLUSPLUSFLAGS.

**Comment by oldmtn** [comment]
solved, thanks
