### ISSUE TITLE
Colud not find my_node_addon on Windows 

### ISSUE THREAD

**Issue by ali-chaudhry** [nodejs/node-gyp#2137]
I have checked the npm directory nod_modules and node_gyp folder too but I could not find any folder with  name.

**Comment by rvagg** [comment]
this needs more context to be actionable @ali-chaudhry, why are you looking for "my_node_addon", as far as I know this is not part of the documentation for node-gyp.

**Comment by bzoz** [comment]
No follow up, closing.
