### ISSUE TITLE
getting error on npm install in windows

### ISSUE THREAD

**Issue by mannesudhir** [nodejs/node-gyp#2138]
getting this error on npm install, not getting is this issue regarding hiredis or node-gyp

![image](https://user-images.githubusercontent.com/13063282/82530227-7c1f2800-9b5a-11ea-8002-a0f0e7ca633c.png)

**Comment by cclauss** [comment]
https://github.com/redis/hiredis/releases 0.5.0 —> 0.14.1 ?

**Comment by mannesudhir** [comment]
@cclauss getting error as  No matching version found for hiredis@0.14.1.

**Comment by cclauss** [comment]
Please see edit above

**Comment by mannesudhir** [comment]
@cclauss how to npm hiredis

**Comment by cclauss** [comment]
https://github.com/NodeRedis/node-redis/blob/master/README.md#node-redis
