### ISSUE TITLE
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1)  install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the locati on of the component to the system path if it is installed elsewhere.  [D:\courseera-bootstrap\as signments\node_modules\node-sass\build\binding.sln]

### ISSUE THREAD

**Issue by 23subbhashit** [nodejs/node-gyp#2155]
I was trying to install sass using this command

`
 npm install --save-dev node-sass@4.7.2
`
Then i got this error:
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) 
install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the locati
on of the component to the system path if it is installed elsewhere.  [D:\courseera-bootstrap\as
signments\node_modules\node-sass\build\binding.sln]
Done Building Project "D:\courseera-bootstrap\assignments\node_modules\node-sass\build\binding.s
ln" (default targets) -- FAILED.

Build FAILED.

"D:\courseera-bootstrap\assignments\node_modules\node-sass\build\binding.sln" (default target) (
1) ->
(_src_\libsass target) -> 
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1
) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the loca
tion of the component to the system path if it is installed elsewhere.  [D:\courseera-bootstrap\
assignments\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.79
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\courseera-bootstrap\assignments\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\courseera-bootstrap\\assignments\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\courseera-bootstrap\assignments\node_modules\node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN confusion@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SUNIL\AppData\Roaming\npm-cache\_logs\2020-06-15T10_15_54_471Z-debug.log

Can anyone tell me what i am doing wrong?

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

**Comment by bzoz** [comment]
You need to update `npm`, which will in turn update `node-gyp`: https://docs.npmjs.com/try-the-latest-stable-version-of-npm

I would suggest using a newer Node version. The v10 you are using is getting quite old.

I'm going to close this. Feel free to open a new issue if you still have problems after updating npm. Remember, that you also need to install build tools (can be done by calling `npm install --global --production windows-build-tools`), after which you need to set up correct VS version (this can be done by `npm config set msvs_version 2017` after you have installed `windows-build-tools`).
