### ISSUE TITLE
copy_cmd `cp -a` isn't supported on Solaris

### ISSUE THREAD

**Issue by cjbj** [nodejs/node-gyp#2160]
The `cp` option `-a` in copy_cmd fails on Solaris.  Currently `npm install` of a binary add-on gives:

```
cp: illegal option -- a
Usage: cp [-f] [-i] [-p] [-@] [-/] f1 f2
       cp [-f] [-i] [-p] [-@] [-/] f1 ... fn d1
       cp -r|-R [-H|-L|-P] [-f] [-i] [-p] [-@] [-/] d1 ... dn-1 dn
```

A work around is to use `node-gyp configure`, edit build/Makefile and change the `cp` syntax to use `-pPR`.  Then run `node-gyp build`:

```
bash-4.4$ diff build/Makefile build/Makefile.bak
134c134
< cmd_copy = rm -rf "$@" && cp -pPR "$<" "$@"
---
> cmd_copy = rm -rf "$@" && cp -af "$<" "$@"
```

Also see https://github.com/nodejs/node-gyp/issues/562#issuecomment-620623044

* **Node Version**: 12.18.1
* **Platform**: solaris
* **Compiler**: gcc (GCC) 7.3.0
* **Module**: oracledb

**Comment by rvagg** [comment]
Sorry to shunt you around @cjbj but GYP is maintained in the [nodejs/gyp-next repo](https://github.com/nodejs/gyp-next) and we just vendor it in. So any changes to this will have to happen there.

I believe the relevant code is this: https://github.com/nodejs/gyp-next/blob/fdc1948b97a7e382fccd49922aef1ead06441004/pylib/gyp/generator/make.py#L2338-L2381

I think you should just be able to add `copy_archive_arguments = "-pPR"` (maybe add an `f` too?) in the `"solaris"` section on line 2364. Test it locally of course before submitting a PR, we don't have any Solaris in our CI. Although SmartOS gets involved ar various points in our use of GYP, I don't know if we exercise this bit or even if SmartOS is identified as `"solaris"`.
