### ISSUE TITLE
A suggesting for node_gyp for resolve node file easy.

### ISSUE THREAD

**Issue by victor-thrifts** [nodejs/node-gyp#2161]
Error: No native build was found for platform=win32 arch=ia32 runtime=node abi=72 uv=1 libc=glibc
at Object../node_modules/ref-napi/lib/ref.js (D:\nodeWeb\angular-tour\dist\server\main.js:162130:111)
at webpack_require (D:\nodeWeb\angular-tour\dist\server\main.js:20:30)

this project is a angular server side app. (angular ssr demo found on angular.io),

i only add a line to this project. 
        const ref = require('ref-napi');    

no luck. 

i zoom into the pyg code.   it so complicated for resolve the node file. but it should be simple.

1.  a *.node file should be in the module's root directory.  i mean,  whatever debug, release, or perbuild, i dont care.
     node_gyp should copy it to the module's root directory when "node_gyp build" success.

2. require('ref-napi'),  gyp look for the ref-napi module root package.json. just for a name. why not use the 'ref-napi' 
as the name?  when do that. it will be easy.

**Comment by bzoz** [comment]
The `node-gyp` is a tool to build native addons for Node. It creates those `.node` files, it is not responsible for loading them in any way.
