### ISSUE TITLE
node-gyp installation problems

### ISSUE THREAD

**Issue by marcoippolito** [nodejs/node-gyp#2170]
I'm having problems in installing node-gyp.
I attach here the complete installation log: 
[node-gypInstallationProblems.txt](https://github.com/nodejs/node-gyp/files/4972007/node-gypInstallationProblems.txt)

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ python -V
    Python 3.7.4

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ vue info

    Environment Info:

      System:
        OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Browsers:
        Chrome: 84.0.4147.89
        Firefox: 78.0.2

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by rvagg** [comment]
OK, so it looks like the version of the package you're trying to build here, utp-native, isn't compatible with the version of Node.js taht you're using. For most addons there's a strict window of Node.js versions they support as the C++ interfaces change over time (with Node.js major versions, e.g. 12 to 13 to 14 ...). Your solution might be as simple as updating the version of utp-native that you're using, maybe a newer version will work with the version of Node.js you're using. The other option is to downgrade the version of Node.js you're using, but that would mean going back to Node 10, which isn't terrible and might be instructive if it works, but the ideal would be 12 or even 14. So head on over to utp-native and figure out what versions of Node.js they support. You're using utp-native v2.2.1 by the look of the Yarn output at the bottom.
