### ISSUE TITLE
Recommend users install win32 version of Python rather than Microsoft Store package

### ISSUE THREAD

**Issue by Toothless204** [nodejs/node-gyp#2172]
The issue is about documentation and thus much of the below environment info is not applicable.

* **Node Version**: N/A
* **Platform**: Windows 10
* **Compiler**: N/A
* **Module**: N/A

It might be better to recommend installing the win32 version of Python over the Microsoft Store package because of [issues with accessing certain shared locations](https://docs.python.org/3/using/windows.html#the-microsoft-store-package) (see "Known Issues" section), most importantly the previously mentioned locations includes `%TEMP%`

I would be curious to see other people's opinion on which version should be recommended

**Comment by cclauss** [comment]
My sense is that it would be a disservice to the vast majority of users to recommend that they do a manual install of a static 32-bit version when we live in a 64-bit world.  The Microsoft Store package will prompt users for updates like the 3.8.5 release that shipped this week.  Those few users who really want those capabilities can do their own research and should be self-supporting for any troubles that arise.

**Comment by Toothless204** [comment]
Just for the record I wish to point out that 64-bit Python has been available for a long time now, note the 64-bit options listed on the [download page for the latest Python release](https://www.python.org/downloads/release/python-385/) for example

Thank you for clarifying the project's stance and reasoning on this issue

**Comment by bzoz** [comment]
@Toothless204 thanks for your suggestion, but as per @cclauss answer, we will stick to the store package.
