### ISSUE TITLE
Error: 403 response downloading https://nodejs.org/download/release/v10.15.1/node-v10.15.1-headers.tar.gz

### ISSUE THREAD

**Issue by anandsiddharth** [nodejs/node-gyp#2174]
I have turned off my firewall and everything the above url works in the browser but not while node-gyp rebuild

C:\Users\tech team\yoheim\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\tech team\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\tech team\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://nodejs.org/download/release/v10.15.1/node-v10.15.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\tech team\AppData\Roaming\npm\node_modules\node-gyp\lib\install.js:187:14)
gyp ERR! stack     at Request.emit (events.js:194:15)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\tech team\AppData\Roaming\npm\node_modules\node-gyp\node_modules\request\request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:442:20)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at addChunk (_stream_readable.js:284:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:265:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tech team\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\tech team\yoheim\node_modules\node-pty
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v7.0.0

OS: Windows 10

**Comment by rvagg** [comment]
Corporate firewall? Do you have `http_proxy` `https_proxy`, `HTTP_PROXY`, `HTTPS_PROXY` or any other such env var set on your machine? does `npm config list` show anything that suggests a proxy might be getting in the way?

**Comment by anandsiddharth** [comment]
No its not, npm install just runs fine.
Here is the output for npm config list

C:\Users\tech team\yoheim>npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.11.3 node/v10.15.1 win32 x64"

; userconfig C:\Users\tech team\.npmrc
node_gyp = "C:\\Users\\tech team\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"

; globalconfig C:\Users\tech team\AppData\Roaming\npm\etc\npmrc
msvs_version = "2015"
python = "C:\\Users\\tech team\\.windows-build-tools\\python27\\python.exe"

; builtin config undefined
prefix = "C:\\Users\\tech team\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\tech team\yoheim
; HOME = C:\Users\tech team
; "npm config ls -l" to show all defaults.

I tried in ubuntu system in a virtual machine, it has the same problem

**Comment by rvagg** [comment]
Unfortunately I don't have good suggestions for where else to look at this. I'm still suspecting there's proxy issues going on here. Are you in a corporate network that's likely to require a proxy and maybe your browser is auto-configured to use a proxy?

Maybe your DHCP is pushing a proxy to your machine that's being used by many of the HTTP services but hasn't been communicated to node-gyp - normally you'd do this with an environment variable. I'm not sure why an `npm install` would be working but node-gyp wouldn't be able to download, but it uses a different HTTP client to talk on the network and maybe npm has some smarts that we don't have built in here.

fwiw the majority of the proxy configuration is done in https://github.com/nodejs/node-gyp/blob/master/lib/proxy.js if that helps.

**Comment by rvagg** [comment]
Another option to consider: you're hitting cloudflare with that request, npm uses fastly (at least they used to last time I checked), maybe CF is flagging your request as at risk due to its risk measurement heuristics. It would be interesting to see the contents of that 403 body, maybe you could hack your local node-gyp to output more information. In C:\Users\tech team\AppData\Roaming\npm\node_modules\node-gyp\lib\install.js you could edit just above line 187 and do a `res.pipe(process.stdout)` (you might need to ditch the `cb()` so it doesn't end prematurely, but the process will probably hang and you'll need to ctrl-c it).

Ref: https://github.com/nodejs/node-gyp/blob/master/lib/install.js#L187

**Comment by StefanStojanovic** [comment]
This issue has been stale for too long and it uses a no longer supported version of tools. I'll close it for those reasons. If you encounter something similar, feel free to reopen it or open a new issue.
