### ISSUE TITLE
Find python Syntax error

### ISSUE THREAD

**Issue by mstrug** [nodejs/node-gyp#2177]
* **Node Version**: 14.0.0
* **Platform**: Windows 10
* **Compiler**: 
* **Module**: node-gyp

<details><summary>Command line output</summary>

```
gyp ERR! stack Error: Command failed: D:\programy\Python36-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
```

</details>

There is a problem with find-python.js script on Windows in lines:
```
  argsExecutable: ['-c', 'import sys; print(sys.executable);'],
  argsVersion: ['-c', 'import sys; print("%s.%s.%s" % sys.version_info[:3]);'],
```
there are missing quote marks, it should be:
```
  argsExecutable: ['-c', '"import sys; print(sys.executable);"'],
  argsVersion: ['-c', '"import sys; print(\'%s.%s.%s\' % sys.version_info[:3]);"'],
```

**Comment by cclauss** [comment]
Please look for a line in the full output (that you did not include that reads something like `ERR! node-gyp -v vX.Y.Z`.  The [current node-gyp](https://github.com/nodejs/node-gyp/releases) is v7.
