### ISSUE TITLE
Cant find dll (with out .h and .lib files). absolute path.

### ISSUE THREAD

**Issue by AndrewFrank-zxy** [nodejs/node-gyp#2178]
* **Node Version**: 12.18.2
* **Platform**: Windows10
* **Compiler**: vs2019
* **Module**: addons to import dll

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
no error but dll is null
HMODULE hDLL = LoadLibrary("F:\\mydll.dll");
```

</details>

When i use nodejs addons to import dll. I found it cant find dll and i dont know why.

**Comment by bzoz** [comment]
You are trying to use `LoadLibrary` from a node native module, right?

If the module is null, use GetLastError to get the error code.

**Comment by bzoz** [comment]
I'll guess that whatever the issue was, it is gone now. Feel free to reopen if you provide more info.
