### ISSUE TITLE
win10 + BuildTools 2017 install error

### ISSUE THREAD

**Issue by wxgang168** [nodejs/node-gyp#2180]
D:\nodejs\brandmamq\nodejs> npm install  -g node-expat

> node-expat@2.3.18 install C:\Users\28218\AppData\Roaming\npm\node_modules\node-expat
> node-gyp rebuild

C:\Users\28218\AppData\Roaming\npm\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Users\28218\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\28218\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\28218\AppData\Roaming\npm\node_modules\node-expat\build\deps\libexpat\..\..\..\deps\libexpat\version.c
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mUNCAUGHT EXCEPTION[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at onErrorNT (internal/child_process.js:469:16)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.18362
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\28218\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m C:\Users\28218\AppData\Roaming\npm\node_modules\node-expat
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v12.18.2
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v5.1.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m[35m[0m This is a bug in `node-gyp`.
[0m[37;40mgyp[0m [0m[31;40mERR![0m[35m[0m Try to update node-gyp and file an Issue if it does not help:
[0m[37;40mgyp[0m [0m[31;40mERR![0m[35m[0m     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\28218\AppData\Roaming\npm-cache\_logs\2020-07-31T06_46_37_681Z-debug.log

**Comment by bzoz** [comment]
Please use the issue template.

**Comment by cclauss** [comment]
`npm install -g npm`  # to upgrade node-gyp to v7

**Comment by DeeDeeG** [comment]
> `npm install -g npm` # to upgrade node-gyp to v7

stable npm is still on `node-gyp@^v5.1.0`, npm 7 beta is still on `node-gyp@^6.1.0`, currently as an indirect dependency. Though they are discussing moving to `node-gyp@7`.
