### ISSUE TITLE
I can't debug my addon project in Xcode

### ISSUE THREAD

**Issue by qixin1106** [nodejs/node-gyp#2184]
I use the generated Xcode project to debug, follow [the tutorial](https://medium.com/@nicknaso/debug-node-js-native-addon-with-xcode-656d740003c0) configuration, the console output error. I can't debug my addon project

### Xcode run and console log error:
```
Message from debugger: Error 1
Program ended with exit code: -1
```

**Comment by richardlau** [comment]
Suspect this is https://github.com/nodejs/node/pull/34378.
