### ISSUE TITLE
wrong include path generated for module node-addon-api

### ISSUE THREAD

**Issue by Jamol** [nodejs/node-gyp#2185]
my addon project depends on node-addon-api and I add the include as follow:
```
'include_dirs': [
        "<!@(node -p \"require('node-addon-api').include\")"
 ]
```
but the include path to node-addon-api is wrong in VC project which generated by "node-gyp configure": 
..\\..node_modulesnode-addon-api
it should be: 
..\\..\\node_modules\\node-addon-api

I ran node command (node -p "require('node-addon-api').include") and it returned the correct path.

* **Node Version**: v14.7.0
* **Platform**: Windows 10
* **Compiler**: Visual Studio Community 2017 
* **Module**:

**Comment by rvagg** [comment]
Odd, I guess the `\` is being treated as escaping. What happens if you remove the `@`?

**Comment by Jamol** [comment]
@rvagg Thanks.
The issue is really fixed after remove ```@```

**Comment by rvagg** [comment]
@nodejs/addon-api hey, the docs for node-addon-api have the `@` but we don't use it for the NAN docs. Perhaps this should change? https://github.com/nodejs/node-addon-api/blob/master/doc/setup.md, I don't think it's necessary if it's just one item being returned, not an array, and in this case it seems to be to blame for doing some extra escaping on Windows, which I don't get, but maybe @nodejs/gyp understands.
