### ISSUE TITLE
Command failed: node-gyp rebuild --jobs max

### ISSUE THREAD

**Issue by qsjh898** [nodejs/node-gyp#2186]
* **Node Version**: 
node -v v12.18.3
npm -v 6.14.6
node-gyp -v 5.1.0

* **Platform**:
Windows7

* **Compiler**: 
windows-build-tools 5.2.2 (not sure about this part)

* **Module**: 
opencv4nodejs

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
ERR! Error: Command failed: node-gyp rebuild --jobs max
gyp http GET https://nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: tar.extract is not a function
gyp ERR! stack     at Request.<anonymous> (F:\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:199:22)
gyp ERR! stack     at Request.emit (events.js:327:22)
gyp ERR! stack     at Request.onRequestResponse (F:\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:469:22)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:271:9)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd F:\nodejs\node_global\node_modules\opencv4nodejs
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

</details>

**Comment by bzoz** [comment]
Could not reproduce. I tried installing opencv4nodejs package with Node.js 12.18.3 on Windows 10 and it installed successfully.

Sorry, Windows 7 is no longer supported.

**Comment by balajianbalagan** [comment]
> Could not reproduce. I tried installing opencv4nodejs package with Node.js 12.18.3 on Windows 10 and it installed successfully.
> 
> Sorry, Windows 7 is no longer supported.

hey I tried installing opencv4nodejs package but I get gyp module not found error 

ERR! Error: Command failed: node-gyp rebuild --jobs max
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'D:\usr\local\lib\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
could you please help me out?

**Comment by cclauss** [comment]
If Windows 7 then we cannot provide support.  If Windows 10 then please open a new issue with the command typed and the full error log.
