### ISSUE TITLE
Help linking LibSodium library via bindings.gyp for Windows

### ISSUE THREAD

**Issue by rsispal** [nodejs/node-gyp#2193]
Hello all,

Forgive me for having to ask here, but this is my last avenue for help on this matter which has been going on for many weeks with little progress. 

I've built an NAPI library for my applications that depends on LibSodium, and am struggling getting it compiling on Windows, as I'm unsure how to specifically link the library (static or dynamic) via the `binding.gyp` file. Ideally I'd like to include the library source and have it build for Windows, MacOS and Linux (though I can live with manually installing on Mac as its so easy).

My questions are:
1. Is there any benefit to use the static lib over the dynamic? I've included the latest LibSodium build in my library codebase so have the static include directory, alongside the `.lib` file and a `.dll` file.
2. The LibSodium build has a Win32 and X64 version - how do I handle these variants in the `binding.gyp` file?
3. How would I "tell" `binding.gyp` to look in a specific directory for the include/library files (i.e. inside my `src/native/libs/sodium/win` folder)
4. Is there a way I can use the raw source and have it build for Windows/Mac (and I guess Linux) without having to manually compile/install on the OS first?

[I've created a very minimal test project here for ease of testing](https://github.com/rsispal/ngyp-libsodium-test), in case anyone wants to have a try. Below is the `binding.gyp` file it uses for reference:

```js

{
    'variables': {
        'target_arch%': '<!(node -e \"var os = require(\'os\'); console.log(os.arch());\")>'
    },
    "targets": [
        {
          "target_name": "Native",
          "sources": [
            "./src/native/module.cc",
            "./src/native/libs/base64/base64.cpp",
            "./src/native/libs/aes/class.cpp",
            "./src/native/libs/json/class.cpp",
            "./src/native/libs/datetime/class.cpp"
          ],
          "cflags!": [ "-fno-exceptions" ],
          "cflags_cc!": [ "-fno-exceptions" ],
          'include_dirs': [
              "<!@(node -p \"require('node-addon-api').include\")"
          ],
          'libraries': [],
          'dependencies': [
              "<!(node -p \"require('node-addon-api').gyp\")"
          ],
          'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
          'conditions': [
              ['OS=="mac"', {
                'libraries': [ '-lsodium' ]
              }],
              ['OS=="win"', {
                  "include_dirs": [
                    "<(module_root_dir)/ ???"
                  ],
                  "libraries": [
                    "<(module_root_dir)/ ???"
                  ]
              }],

            ]
        }
    ]
}

```

* **Node Version**: 13.9.0
* **Platform**: Windows, MacOS (windows, unix)
* **Compiler**: 11.0.3
* **Module**: LibSodium library

**Comment by Ayzrian** [comment]
Hi! 
Gyp has predefined variable `target_arch`, so you can use something like this. 

```
"conditions": [
        	[
        		"OS=='win' and target_arch=='x64'",
        		{
                            // x64 libs
        		}
        	],
        	[
                       "OS=='win' and target_arch=='x32'",
                      {
                        // x32 libs
                      }
                ]
        ]
```

**Comment by rsispal** [comment]
@Ayzrian , thank you for informing me about `target_arch`! This solves question 2 🎉

I will ensure I use this once I finally find a way to link this library source!

**Comment by rsispal** [comment]
Good news. All built on Windows using the following code:

```
          'conditions': [

                ["OS=='win' and target_arch=='x64'", {
                    "include_dirs": [
                        "C:/ngyp-libsodium-test/src/native/libs/sodium/win/include"
                    ],
                    "libraries": [
                        "C:/ngyp-libsodium-test/src/native/libs/sodium/win/x64/Release/v142/dynamic/libsodium.lib"
                    ],
                    "copies": [
                        {
                            "destination": "<(module_root_dir)/build/Release/",
                            "files": [
                                "C:/ngyp-libsodium-test/src/native/libs/sodium/win/x64/Release/v142/dynamic/libsodium.dll"
                            ]
                        }
                    ]
                }],

                ["OS=='win' and target_arch=='x32'", {
                    "include_dirs": [
                        "C:/ngyp-libsodium-test/src/native/libs/sodium/win/include"
                    ],
                    "libraries": [
                        "C:/ngyp-libsodium-test/src/native/libs/sodium/win/Win32/Release/v142/dynamic/libsodium.lib"
                    ],
                    "copies": [
                        {
                            "destination": "<(module_root_dir)/build/Release/",
                            "files": [
                                "C:/ngyp-libsodium-test/src/native/libs/sodium/win/Win32/Release/v142/dynamic/libsodium.dll"
                            ]
                        }
                    ]
                }]

            ]

```

Closing the issue
