### ISSUE TITLE
Exit code: 1 Command: node-gyp rebuild on MacOS!

### ISSUE THREAD

**Issue by Freeland90** [nodejs/node-gyp#2194]
Hello,
followed every tutorial on this error, it just won't get fixed, I'd appreciate any help.

https://i.ibb.co/rtrnfGw/Screen-Shot-2020-08-13-at-8-44-59-PM.png
https://i.ibb.co/rMQm9nc/Screen-Shot-2020-08-13-at-8-45-12-PM.png
https://i.ibb.co/jwdJ9cT/Screen-Shot-2020-08-13-at-8-45-22-PM.png

Here is the error, if you don't want to click the links: 

`
 yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["websocket@github:web3-js/WebSocket-Node#polyfill/globalThis"] is trying to unpack in the same destination "/Users/**/Library/Caches/Yarn/v6/npm-websocket-1.0.29/node_modules/websocket" as pattern ["websocket@1.0.29"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-standard@14.1.1" has unmet peer dependency "eslint-plugin-import@>=2.18.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > ckeditor4-react@1.1.1" has unmet peer dependency "ckeditor4@^4.14.1".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > fbt-runtime@0.9.4" has incorrect peer dependency "babel-plugin-fbt@0.9.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > fbt-runtime@0.9.4" has incorrect peer dependency "babel-plugin-fbt-runtime@0.9.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > babel-plugin-fbt-runtime@0.9.12" has incorrect peer dependency "babel-plugin-fbt@^0.14.2".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/shop-backend > connect-session-sequelize@7.0.1" has incorrect peer dependency "sequelize@>= 6.1.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/services > ipfs > libp2p-delegated-content-routing@0.5.0" has incorrect peer dependency "ipfs-http-client@^44.0.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/services > ipfs > libp2p-delegated-peer-routing@0.5.0" has incorrect peer dependency "ipfs-http-client@^44.0.0".
warning "workspace-aggregator-62fb901f-c370-4604-b91f-cd13e2b045bd > @origin/services > ipfs > prometheus-gc-stats@0.6.2" has incorrect peer dependency "prom-client@>= 10 < 12".
[4/4] 🔨  Building fresh packages...
[22/43] ⠈ leveldown
[20/43] ⠈ ursa-optional
[6/43] ⠈ scrypt
[16/43] ⠁ keccak
error /Users/**/dshop/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/**/dshop/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.8.0 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/**/dshop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/**/dshop/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/**/dshop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/**/.node-gyp/14.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/**/.node-gyp/14.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/**/dshop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/**/.node-gyp/14.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/**/dshop/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:
../src/node-boilerplate/inc/scrypt_common.h:39:14: error: no matching member function for call to 'Get'
      N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
        ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:
../src/node-boilerplate/inc/scrypt_common.h:40:14: error: no matching member function for call to 'Get'
      r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
        ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:
../src/node-boilerplate/inc/scrypt_common.h:41:14: error: no matching member function for call to 'Get'
      p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
        ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:
../src/node-boilerplate/inc/scrypt_async.h:53:17: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      callback->Call(1, argv);
                ^
../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:35:36: error: too few arguments to function call, single argument 'context' was not specified
      maxtime(info[0]->NumberValue()),
              ~~~~~~~~~~~~~~~~~~~~ ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:2861:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/**/.node-gyp/14.8.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:36:39: error: too few arguments to function call, single argument 'context' was not specified
      maxmemfrac(info[1]->NumberValue()),
                 ~~~~~~~~~~~~~~~~~~~~ ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:2861:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/**/.node-gyp/14.8.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:37:36: error: too few arguments to function call, single argument 'context' was not specified
      maxmem(info[2]->IntegerValue()),
             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:2863:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/**/.node-gyp/14.8.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: too few arguments to function call, single argument 'context' was not specified
      osfreemem(info[3]->IntegerValue())
                ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:2863:3: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/**/.node-gyp/14.8.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/node-boilerplate/scrypt_params_async.cc:23:8: error: no matching member function for call to 'Set'
  obj->Set(Nan::New("N").ToLocalChecked(), Nan::New<Integer>(logN));
  ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node-boilerplate/scrypt_params_async.cc:24:8: error: no matching member function for call to 'Set'
  obj->Set(Nan::New("r").ToLocalChecked(), Nan::New<Integer>(r));
  ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node-boilerplate/scrypt_params_async.cc:25:8: error: no matching member function for call to 'Set'
  obj->Set(Nan::New("p").ToLocalChecked(), Nan::New<Integer>(p));
  ~~~~~^~~
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/**/.node-gyp/14.8.0/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node-boilerplate/scrypt_params_async.cc:32:13: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  callback->Call(2, argv);
            ^
../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings and 10 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/**/dshop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/**/dshop/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/**/dshop/node_modules/scrypt
`

**Comment by richardlau** [comment]
Those errors indicate that the scrypt module just isn't compatible with Node.js 14. You could try with Node.js 12 or 10. Looking at the npm page it looks like this module hasn't been updated for four years, so if those don't work or you want to use Node.js 14 you'll probably have to look for an alternative: https://www.npmjs.com/package/scrypt

**Comment by Freeland90** [comment]
> Those errors indicate that the scrypt module just isn't compatible with Node.js 14. You could try with Node.js 12 or 10. Looking at the npm page it looks like this module hasn't been updated for four years, so if those don't work or you want to use Node.js 14 you'll probably have to look for an alternative: https://www.npmjs.com/package/scrypt

Thank! I downgraded to 10, and it gave me a different error! Are we progressing? 

`node -v
v10.22.0
Air:dshop fayaa$ yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["websocket@github:web3-js/WebSocket-Node#polyfill/globalThis"] is trying to unpack in the same destination "/Users/fayaa/Library/Caches/Yarn/v6/npm-websocket-1.0.29/node_modules/websocket" as pattern ["websocket@1.0.29"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-standard@14.1.1" has unmet peer dependency "eslint-plugin-import@>=2.18.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > ckeditor4-react@1.1.1" has unmet peer dependency "ckeditor4@^4.14.1".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > fbt-runtime@0.9.4" has incorrect peer dependency "babel-plugin-fbt@0.9.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > fbt-runtime@0.9.4" has incorrect peer dependency "babel-plugin-fbt-runtime@0.9.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > babel-plugin-fbt-runtime@0.9.12" has incorrect peer dependency "babel-plugin-fbt@^0.14.2".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/shop-backend > connect-session-sequelize@7.0.1" has incorrect peer dependency "sequelize@>= 6.1.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/services > ipfs > libp2p-delegated-content-routing@0.5.0" has incorrect peer dependency "ipfs-http-client@^44.0.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/services > ipfs > libp2p-delegated-peer-routing@0.5.0" has incorrect peer dependency "ipfs-http-client@^44.0.0".
warning "workspace-aggregator-8152e211-64e9-43bc-84ed-89cedf149836 > @origin/services > ipfs > prometheus-gc-stats@0.6.2" has incorrect peer dependency "prom-client@>= 10 < 12".
[4/4] 🔨  Building fresh packages...
[13/43] ⠐ @web3-js/websocket
[6/43] ⠐ scrypt
[7/43] ⠐ websocket
[8/43] ⠐ fsevents
error /Users/fayaa/dshop/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/fayaa/dshop/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.22.0 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/Users/fayaa/dshop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fayaa/dshop/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fayaa/dshop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fayaa/.node-gyp/10.22.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/fayaa/.node-gyp/10.22.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/fayaa/dshop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/fayaa/.node-gyp/10.22.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/fayaa/dshop/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Users/fayaa/dshop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/fayaa/dshop/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/fayaa/dshop/node_modules/scrypt




warning Error running install script for optional dependency: "/Users/fayaa/dshop/node_modules/gc-stats: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/fayaa/dshop/node_modules/gc-stats
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.22.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64/gcstats.node\" (not found)
node-pre-gyp http GET https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp http 403 https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@10.22.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v64-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.22.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.22.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fayaa/dshop/node_modules/gc-stats/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fayaa/Library/Caches/node-gyp/10.22.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/fayaa/Library/Caches/node-gyp/10.22.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/fayaa/Library/Caches/node-gyp/10.22.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/fayaa/dshop/node_modules/gc-stats',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.22.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64/gcstats.node\" \"--module_name=gcstats\" \"--module_path=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64\" \"--napi_version=6\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v64\"
gyp ERR! cwd /Users/fayaa/dshop/node_modules/gc-stats
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/fayaa/dshop/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/Users/fayaa/dshop/node_modules/gc-stats/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/fayaa/dshop/node_modules/gc-stats
node-pre-gyp ERR! node -v v10.22.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/fayaa/dshop/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)"
info This module is OPTIONAL, you can safely ignore this error`

**Comment by richardlau** [comment]
> You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.

This is probably the issue. I'm not a macOS user but it looks like you'll need to read and accept the license for Xcode.

**Comment by Freeland90** [comment]
> > You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.
> 
> This is probably the issue. I'm not a macOS user but it looks like you'll need to read and accept the license for Xcode.

Can I donate to you using Bitcoin's lightning network? This took me weeks and you solved it in a minute. THANK YOU!
please consider making a tippin.me
