### ISSUE TITLE
Windows Powershell signing scripts?

### ISSUE THREAD

**Issue by juju4** [nodejs/node-gyp#2195]
This is more a general request than a bug for users of node-gyp on Windows.
Any plan to use signed powershell scripts that would work as is with RemoteSigned or AllSigned Execution policy?

This would help a lot for organizations that have more restrictive default settings.

Avoid Unrestricted as request in https://github.com/nodejs/node-gyp/blob/master/lib/Find-VisualStudio.cs#L6

Thanks

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7
https://4sysops.com/archives/sign-your-powershell-scripts-to-increase-security/
http://woshub.com/how-to-sign-powershell-script-with-a-code-signing-certificate/
https://devblogs.microsoft.com/scripting/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-2-of-2/

**Comment by StefanStojanovic** [comment]
Closing this since it's been stale for too long. If needed feel free to reopen.
