### ISSUE TITLE
/Users/mine/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory

### ISSUE THREAD

**Issue by XiaohengLiu** [nodejs/node-gyp#2199]
i installed node through nvm, but node-gyp is trying to use the standard node_module in the `usr/local/lib` repo.

`/Users/mine/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory`

node-gyp: 7.1.0
node: 12.13.1
mac OS: 10.15.6

**Comment by rvagg** [comment]
run `npm config list`, you may have a `node_gyp` set in there. Unset it with `npm config delete` and `node-gyp-bin/node-gyp` should do a relative reference rather than absolute.
