### ISSUE TITLE
https://registry.npmjs.org/node_gyp - E404 error with npm install

### ISSUE THREAD

**Issue by Satya318** [nodejs/node-gyp#2201]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node_gyp'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.17.0
4 verbose npm-session 8bf6ab7e19c7805f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/node_gyp 1170ms
8 http fetch GET 404 https://registry.npmjs.org/node_gyp 67ms
9 silly fetchPackageMetaData error for node_gyp@latest 404 Not Found - GET https://registry.npmjs.org/node_gyp - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 1259ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/node_gyp - Not found
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid node_gyp@latest
15 verbose cwd /Users/s1b06wv/OneDrive - Walmart Inc/ui_workspace/new-ui/self-service-portal/src
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node_gyp"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/node_gyp - Not found
22 error 404
23 error 404 'node_gyp@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by richardlau** [comment]
This project is `node-gyp`, i.e. with a hyphen instead of an underscore.
