### ISSUE TITLE
Cannot find `-lnode`

### ISSUE THREAD

**Issue by eepp** [nodejs/node-gyp#2208]
* **Node Version**: Node.js 10.19.0; npm 6.14.4
* **Platform**: Linux c79d1d38c67b 5.8.1-arch1-1 #1 SMP PREEMPT Wed, 12 Aug 2020 18:50:43 +0000 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: Target: arm-gcc49-linux-gnueabi; gcc version 4.9.4 (gcc-4.9.4 + glibc-2.27)
* **Module**: Node.js 10.22.0's `test/addons/hello-world` example

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> node-gyp build --arch=arm --nodedir=/path/to/node-v10.22.0/
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory 'node-v10.22.0/test/addons/hello-world/build'
  SOLINK_MODULE(target) Release/obj.target/binding.node
arm-gcc49-linux-gnueabi/bin/ld: cannot find -lnode
collect2: error: ld returned 1 exit status
make: *** [binding.target.mk:126: Release/obj.target/binding.node] Error 1
make: Leaving directory 'node-v10.22.0/test/addons/hello-world/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.1-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--arch=arm" "--nodedir=node-v10.22.0/"
gyp ERR! cwd node-v10.22.0/test/addons/hello-world
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

</details>

I cross-compiled Node.js 10.22.0 with the following configuration options:

```
--prefix=/usr --dest-cpu=arm --cross-compiling --dest-os=linux --with-arm-float-abi=softfp --with-arm-fpu=vfpv3-d16 --without-dtrace --without-etw --without-intl --without-inspector
```

My host's Node.js version is 10.19.0 (Ubuntu 20.04 package).

It seems like GYP eventually creates Makefiles which pass `-lnode` to the linker. For example, `binding.target.mk` contains

```
LIBS := \
        -lnode
```

Where is this libnode to be found? Node.js's `make install` does not install any library (static or shared). There is a `libnode.a` in Node.js's build directory: `out/Release/obj.target/libnode.a`. However, this looks like an internal convenience library for the build process.

I looked at the four GYP files which node-gyp passes to GYP:

* `binding.gyp` (`hello-world` example)
* `config.gypi` (generated by node-gyp)
* `addon.gypi` (node-gyp static file)
* `node-v10.22.0/common.gypi` (Node.js static file)

I cannot find anything related to libnode in those.

So, from GYP's perspective, where does this `-lnode` comes from?

Also, if I manually remove `-lnode` from the generated Makefile (`binding.target.mk`), then make succeeds and I get `Release/binding.node`.

Can you shed light on this problem?

**Comment by eepp** [comment]
I found [the offender](https://salsa.debian.org/js-team/node-gyp/-/blob/debian/6.1.0-1/debian/patches/link_libnode.patch):

``` diff
Description: Link to node shared lib on debian
Last-Update: 2019-01-01
Forwarded: not-needed
Author: Jérémy Lal <kapouer@melix.org>
--- a/addon.gypi
+++ b/addon.gypi
@@ -159,6 +159,11 @@
          (OS=="linux")', {
         'cflags': [ '-fPIC' ],
       }],
+      [ 'OS in "linux freebsd openbsd netbsd solaris"', {
+        'libraries': [
+          '-lnode'
+        ],
+      }]
     ]
   }
 }
```

This is a Debian patch which changes node-gyp's `addon.gypi` so that any addon links to libnode (which is installed as `/usr/lib/x86_64-linux-gnu/libnode.so`, for example).

So, not node-gyp's fault in the end, which is why I'm closing the issue.

My solution is installing my own version of node-gyp locally (`npm i node-gyp`), which comes with its own original `addon.gypi`, and using this one.

I didn't investigate why Debian installs libnode.

But it's still weird in my opinion that node-gyp eventually uses the installed `addon.gypi` as is without considering the target Node.js project (specificied with `--nodedir`). Other things are fixed in `addon.gypi` and the generated `config.gypi` which I believe should be dynamic. To generate `config.gypi`, node-gyp [starts with `process.config`](https://github.com/nodejs/node-gyp/blob/v6.1.0/lib/configure.js#L100); this doesn't make sense (using the host's Node.js) when cross-compiling. Why not give the option to include Node.js's generated `config.gypi`?

**Comment by cclauss** [comment]
That conditional is too permissive in Python because all substrings (instead of all words) match.

% python3
```
>>> for OS in "linux a e i o u bsd free open net solar":
>>>         OS in "linux freebsd openbsd netbsd solaris".split()

# prints all True

>>> for OS in "linux a e i o u bsd free open net solar".split():
>>>         OS in "linux freebsd openbsd netbsd solaris".split()

# prints True for linux but False for all the rest
```

**Comment by eepp** [comment]
@cclauss 

``` python
OS in {'linux', 'freebsd', 'openbsd', 'netbsd', 'solaris'}
```

**Comment by QGB** [comment]
arm-gcc49-linux-gnueabi/bin/ld
