### ISSUE TITLE
Do we need Travis CI anymore or are GitHub Actions good enough?

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-gyp#2209]
https://travis-ci.com/github/nodejs/node-gyp vs. https://github.com/nodejs/node-gyp/actions

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
(...)
```

</details>

**Comment by imatlopez** [comment]
@cclauss is this related to #2127? I think actions is more transparent. There are two consistent failing tests (with python 2.7) on Travis and you wouldn't know that unless you go there.

**Comment by rvagg** [comment]
yeah, I'd be happy to see #2209 land and ditch travis - maybe someone can help out or take over that effort?

**Comment by imatlopez** [comment]
@codebytere do you still have the time? Maybe I can take over if you don't. Never worked with gh actions since my company's enterprise doesn't have them (just checks), but never too late to learn

**Comment by codebytere** [comment]
I can try to look more for sure but feel free to push to the branch in the meantime!
