### ISSUE TITLE
c1xx: fatal error C1083: Could not open source file: '.. \ src \ binding.cc ': No such file or directory [D: \ xxxx \ xxx \ xxxx \ build \ binding.vcxproj] 

### ISSUE THREAD

**Issue by BombyX113** [nodejs/node-gyp#2216]
Hello, i tried to install node-gyp but when i try to do `node-gyp build` or` node-gyp rebuild` from an error, i.e c1xx: fatal error C1083: Could not open source file: '.. \ src \ binding.cc ': No such file or directory [D: \ xxxx \ xxx \ xxxx \ build \ binding.vcxproj] and going to node_modeles I can't find the' binding.cc 'file and there is not even uninstalling, reinstalling the node-gyp, how do i solve?

> PS D:\Discord\Bot\Wherjen> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@14.9.0 | win32 | x64
gyp info find Python using Python version 3.8.5 found at "C:\Users\Massimo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2019 (16.7.30413.136) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Massimo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\xxxx\\xxx\\xxxxx\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.9.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\xxxx\xxxxx\xxxxxx',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\xxxx\\xxx\\xxxx\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
D:\Discord\Bot\Wherjen\build\..\src\binding.cc
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "-m".
  binding.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Non è possibile aprire il file origine: '..\src\binding.cc': No such file or directory [D:\Discord\Bot\Wherjen\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.20201
gyp ERR! command "C:\\Program Files\\node.js\\node.exe" "C:\\Users\\Administrator\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\xxxx\xxx\xxxxx
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok

(the powershell is a 7.0.3 open as administrator)

**Comment by BombyX113** [comment]
i fund a soluzion, i not insert binding.gyp and binding.cc

**Comment by MS4794** [comment]
> i fund a soluzion, i not insert binding.gyp and binding.cc

where you added binding.cc file?

**Comment by SnowElves** [comment]
I have the same problem, have you solved it

**Comment by ticclark-clgx** [comment]
dfdaf

**Comment by ticclark-clgx** [comment]
I believe all references do you not tell you to add the binding.cc  file to your  node-gyp/src     the path reference for the node-gyp build or rebuild is the  within the directory that you are running  the command in

**Comment by ticclark-clgx** [comment]
The same goes for the  binding.gyp
