### ISSUE TITLE
not working when cross compiling

### ISSUE THREAD

**Issue by jandrieu** [nodejs/node-gyp#224]
We have cross-compiled node, getting it to work on our embedded ARM system. It works great. Now I am trying to get the serialport module working, and of course, it is compiled for my dev box, not the embedded system, so it hurls miserably.

If I could configure serialport to cross compile...

I tried passing the required parameters to node-gyp configure (with various ENV vars--CC, CXX, and LINK set to right places).

> sudo node-gyp configure --without-snapshot --dest-cpu=arm --dest-os=linux --with-arm-float-abi=softfp --prefix=/home/ubuntu/XXX/usr/local

That didn't cause any errors.

But then node-gyp build failed at 

> cc1plus: error: unrecognized command line option "-m32"
> make: **\* [Release/obj.target/serialport/src/serialport.o] Error 1

Any suggestions on how I might get it to work?

Oh. FWIW, the ARM box doesn't have a compiler and I always run NPM from the dev box.

Here's the full output from node-gyp configure and make:
# 

> ubuntu@ubuntu-VirtualBox:~/XXX/node/node_modules/serialport$ sudo node-gyp configure --without-snapshot --dest-cpu=arm --dest-os=linux --with-arm-float-abi=softfp --prefix=/home/ubuntu/XXX/usr/local
> [sudo] password for ubuntu: 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@0.9.2
> gyp info using node@0.10.0 | linux | ia32
> gyp info spawn python
> gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/ubuntu/XXX/www/node/node_modules/serialport/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/ubuntu/.node-gyp/0.10.0/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/0.10.0',
> gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/XXX/node/node_modules/serialport',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info ok 
> 
> ubuntu@ubuntu-VirtualBox:~/XXX/node/node_modules/serialport$ node-gyp build
> gyp info it worked if it ends with ok
> gyp info using node-gyp@0.9.2
> gyp info using node@0.10.0 | linux | ia32
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/ubuntu/XXX/node/node_modules/serialport/build'
>   CXX(target) Release/obj.target/serialport/src/serialport.o
> cc1plus: error: unrecognized command line option "-m32"
> make: **\* [Release/obj.target/serialport/src/serialport.o] Error 1
> make: Leaving directory '/home/ubuntu/XXX/node/node_modules/serialport/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:256:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
> gyp ERR! System Linux 3.0.0-32-generic
> gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
> gyp ERR! cwd /home/ubuntu/XXX/node/node_modules/serialport
> gyp ERR! node -v v0.10.0
> gyp ERR! node-gyp -v v0.9.2
> gyp ERR! not ok

**Comment by AllenBird** [comment]
I have the same problem!!

**Comment by maclover7** [comment]
Moving to #829, see also https://github.com/nodejs/node-gyp/issues/829#issuecomment-160660375
