### ISSUE TITLE
How can I change MSBuild path during initialization ?

### ISSUE THREAD

**Issue by AramAnd** [nodejs/node-gyp#2243]
* **Node Version**: v12.13.1 and 6.1.0
* **Platform**: Windows 10
* **Compiler**: Visual Studio 2019/msbuild
* **Module**: npm install

I am try to install the module and my issue lies that the path of msbuild is incorrect

**C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\15.0\\Bin\\MSBuild.exe**

instead of above it should be 

**C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin\\MSBuild.exe**

How can i change the path precisely ?

![image](https://user-images.githubusercontent.com/7838312/96869084-0bb96180-1480-11eb-8659-6f0ecb4baa77.png)

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/3baa4e4172c47052ee7e942cef542c1a7dea75aa/lib/configure.js#L145

https://github.com/nodejs/node-gyp/search?q=GYP_MSVS_VERSION

**Comment by cclauss** [comment]
Can this issue be closed?
