### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by robinsongz** [nodejs/node-gyp#2246]
I keep getting this error when I try to npm install. I recently upgraded Node to v14, please help.

`C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime> npm install

> integer@1.0.7 install C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime\node_modules\integer
> node-gyp rebuild

C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  integer.cpp
  win_delay_load_hook.cc
c:\users\mrrob\onedrive\desktop\slime bot\test-slime\node_modules\integer\src\integer.cpp(329): error C2664: 'v8::String::Value::Value(const v8::String::Value &)': cannot convert argument 1 from 'v8::Local<v8::String>'
 to 'const v8::String::Value &' [C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime\node_modules\integer\build\integer.vcxproj]
  c:\users\mrrob\onedrive\desktop\slime bot\test-slime\node_modules\integer\src\integer.cpp(329): note: Reason: cannot convert from 'v8::Local<v8::String>' to 'const v8::String::Value'
  c:\users\mrrob\onedrive\desktop\slime bot\test-slime\node_modules\integer\src\integer.cpp(329): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called   
c:\users\mrrob\onedrive\desktop\slime bot\test-slime\node_modules\integer\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime\node_modu 
les\integer\build\integer.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mrrob\OneDrive\Desktop\slime bot\test-slime\node_modules\integer
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN slime-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mrrob\AppData\Roaming\npm-cache\_logs\2020-10-28T02_55_25_069Z-debug.log`

**Comment by cclauss** [comment]
gyp ERR! node-gyp -v v5.1.0

Please upgrade.

**Comment by cclauss** [comment]
Can this issue be closed?
