### ISSUE TITLE
node-gyp configure failed

### ISSUE THREAD

**Issue by bharatsingh100** [nodejs/node-gyp#2247]
node-gyp configure failed
OS: windows 10 

$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@8.11.2 | win32 | x64
gyp info find Python using Python version 2.7.10 found at "C:\Python27\python.ex
e"
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, mkdir 'C:\Users\Angryge
rmankid\AppData\Local\node-gyp\Cache\8.11.2'
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\Angrygermankid\AppData\Roaming\nvm\v8.11.2
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

**Comment by cclauss** [comment]
Node 8 is no longer supported.  https://github.com/nodejs/Release

**Comment by bharatsingh100** [comment]
which version of node-gyp supports node 8
