### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by mrmoonribs** [nodejs/node-gyp#2248]
### **_This is the error that I receive when I run the command "node ." to start my bot._**

Error: Could not locate the bindings file. Tried:
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\compiled\15.0.1\win32\x64\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\lib\binding\node-v88-win32-x64\better_sqlite3.node
    at bindings (C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\quill\OneDrive\Desktop\Discord\Discord Bots\Discord Bot 2\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30) {
  tries: [
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\bett    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node',
    'C:\\Users\\quill\\OneDrive\\Desktop\\Discord\\Discord Bots\\Discord Bot 2\\node_modules\\better-sqlite3\\lib\\binding\\node-v88-win32-x64\\better_sqlite3.node'
  ]
}

_**Please help! Thanks.**_

**Comment by MrMoonRibs** [comment]
;-;

**Comment by WickedWizard3588** [comment]
Hopefully, you made a `bindings.gyp` in the root of your project. If not, make that file, and copy-paste the details from [here](https://github.com/nodejs/node-gyp#the-bindinggyp-file)

**Comment by owl-from-hogvarts** [comment]
Does this issue have been solved?

**Comment by StefanStojanovic** [comment]
Closing this since it's been stale for too long. Feel free to reopen if needed.
