### ISSUE TITLE
Invalid version number Electron beta.

### ISSUE THREAD

**Issue by ccorcos** [nodejs/node-gyp#2253]
I'm using `electron-builder` and trying to build my app against `electron@11.0.0-beta.19` and node-gyp is complaining about that version number.

* **Node Version**:  v12.18.3
* **Platform**:  macOS 11.0.1
* **Compiler**:  clang-1200.0.32.4
* **Module**:  cld

```
   gyp ERR! stack Error: Invalid version number: ^11.0.0-beta.19
    gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:56:25)
    gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:30:7
    gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
    gyp ERR! System Darwin 20.1.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/chet/Code/notion-next/build/desktop/node_modules/cld
    gyp ERR! node -v v12.18.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! cld@2.5.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
```

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.1.0

Please upgrade node-gyp to a more current version.

**Comment by ccorcos** [comment]
Hmm. Good point, when I run `npm ls`, it says `node-gyp@7.1.2` under `electron-rebuild`... Not sure where this is coming from...

**Comment by ccorcos** [comment]
Do you know where `/usr/local/lib/node_modules/npm/node_modules/` is coming from?

**Comment by rvagg** [comment]
yes, that's the `npm` version of node-gyp, you can upgrade npm to get a newer node-gyp too - `npm install npm -g`

**Comment by rvagg** [comment]
or download and install a newer version of Node.js which comes with a newer npm & node-gyp

**Comment by cclauss** [comment]
@rvagg How should users resolve the [`Multiple node-gyp versions are installed`](https://github.com/nodejs/node-gyp/labels/Multiple%20node-gyp%20versions%20are%20installed) on macOS and Linux?
@joaocgreis provided [detailed instructions for Windows](https://github.com/nodejs/node-gyp/issues/1753#issuecomment-501827267) but I am unsure how to do the same on non-Windows platforms.

**Comment by cclauss** [comment]
@ccorcos Did this work for you?  Can this issue be closed?

**Comment by ccorcos** [comment]
Yes, this worked. There was some wonkiness with electron-builder as well. Thanks.

**Comment by rvagg** [comment]
@cclauss https://github.com/nodejs/node-gyp/issues/2272
