### ISSUE TITLE
Installing a script on Big Sur gives me an error

### ISSUE THREAD

**Issue by ivangodfather** [nodejs/node-gyp#2262]
2 errors generated.
make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:315:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack at ChildProcess. (/Users/ivan/Gas/bbb-react-native-shop/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/ivan/Gas/bbb-react-native-shop/node_modules/api-ecommerce/node_modules/grpc
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0

v14.15.1
Darwin Ivans-iMac.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.1.0

Please upgrade to a [current release](https://github.com/nodejs/node-gyp/releases) of node-gyp.

**Comment by ivangodfather** [comment]
@cclauss can you point me out how to install 7.1.2 from tar.gz ? it has any installer inside?

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp#installation

**Comment by ivangodfather** [comment]
I'm still having the same issue in another laptop.

Seems I don't have the latest version of npm-pre-gyp from the logs
gyp ERR! node-gyp -v v7.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.12.0 (0.16.0 seems to be the latest)

 npm install node-pre-gyp -g


changed 66 packages, and audited 66 packages in 4s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
how do I update the *pre*?

**Comment by rvagg** [comment]
I think you'll need to take this up with the grpc folks or node-pre-gyp, this isn't coming from node-gyp, it's only being used to call down in to node-pre-gyp to do this. Perhaps it's getting confused about the precompile binary name it's supposed to find `node-v83-darwin-x64-unknown`? I don't see anything in that log output that indicates _why_ node-pre-gyp is failing, just that it is.

**Comment by cclauss** [comment]
Is this a new Mac with "Apple silicon" M1?

**Comment by ivangodfather** [comment]
No, is an iMac from about 6 years ago. 
I just solves this issue installing a previous version of Node with nvm. 
Ivan
