### ISSUE TITLE
node-gyp rebuild fails when npm install nodobjc

### ISSUE THREAD

**Issue by xjtulk** [nodejs/node-gyp#2267]
Hi, When I try to install nodobjc in my electron project, it seems trigger the node-gyp rebuild
the command is `npm install nodobjc --save`
and get the output like below
![image](https://user-images.githubusercontent.com/8480676/100338113-251b7380-3013-11eb-9f10-4333ac860d59.png)
here is my env
**npm  6.14.9
node  v10.16.3
electron v11.0.3
node-gyp v7.1.2
Python 2.7.16
os mac-catalina-10.15.7**

I also feel strange that `node-gyp -v` shows v7.1.2 but the error output above shows node-gyp -v v5.1.0

**Comment by X-Ray-Jin** [comment]
Hi, i have the exact same issue. Just that I am on Windows 10
I face this when trying to install [Snowboard](https://github.com/bukalapak/snowboard) API renderer. It fails when trying to install [Protagonist](https://www.npmjs.com/package/protagonist)

![image](https://user-images.githubusercontent.com/6496299/100377729-11bbd880-3012-11eb-8af3-a6bb48d918b3.png)

I tried everything from this [here](https://spin.atomicobject.com/2019/03/27/node-gyp-windows/) but it doesn't help at all.

Any other solutions or things I might try?

**Comment by rvagg** [comment]
those errors suggest that the version of the addon you're using is not compatible with the version of Node.js you're using. You should either find a newer version of the addon that supports your Node.js version, or downgrade Node.js to the maximum supported version for the addon you're using.
