### ISSUE TITLE
angular error: An unhandled exception occurred: Cannot find module '@angular/compiler-cli/src/tooling'

### ISSUE THREAD

**Issue by omkarML** [nodejs/node-gyp#2268]
im working on a angular project im getting this error after upgrading angular version.i have tried deleting node_modules,package-lock.json files even gets error while npm install 
npm start gives me this error , can anyone help me determine it ?
An unhandled exception occurred: Cannot find module '@angular/compiler-cli/src/tooling'
Require stack:
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js    
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@ngtools\webpack\src\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\webpack\configs\typescript.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\utils\index-file\write-index-html.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\browser\index.js 
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\models\architect-command.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\schematics\tools\export-ref.js     
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\models\command-runner.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\lib\init.js
- C:\Users\HP\Desktop\New folder\gitlab repos\lms-dashboard\node_modules\@angular\cli\bin\ng
See "C:\Users\HP\AppData\Local\Temp\ng-BYilZm\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! scssdestmoney@1.0.0 start: `ng serve --port 4201`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the scssdestmoney@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-11-27T08_51_24_187Z-debug.log

**Comment by cclauss** [comment]
What command was typed?  Why remove the part of the error log that tells what version of node, node-gyp, etc.?

**Comment by omkarML** [comment]
@cclauss npm start ,i didnt removed error log

**Comment by cclauss** [comment]
Your command was `npm start `  ?

A complete error log should look like #2249 and if there are no lines that start with `gyp ERR!` then this is not the right repo for this issue.

**Comment by omkarML** [comment]
@cclauss yea this is my complete error log ,the line do not start with `gyp ERR!`

**Comment by cclauss** [comment]
> npm ERR! scssdestmoney@1.0.0 start: ng serve --port 4201

[`scssdestmoney` does not exist in npm.](https://www.npmjs.com/search?q=scssdestmoney)
