### ISSUE TITLE
Node Erorr

### ISSUE THREAD

**Issue by dfdfdfs** [nodejs/node-gyp#2280]
Hello everyone. Tell me what is the problem?

I have Windows 8.1 64bit when trying to npm install command I get this error

User @ WIN-9G17FRIREA8 C: \ dexcalibur
# npm install

> xz@2.0.2 install C: \ dexcalibur \ node_modules \ xz
> node-gyp rebuild

User @ WIN-9G17FRIREA8 C: \ dexcalibur \ node_modules \ xz
# if not defined npm_config_node_gyp (node ​​"C: \ Program Files \ nodejs \ node_modules \ npm \ node_modules \ npm-lifecycle \ node-gyp-bin \\ .. \ .. \ node_modules \ node-gyp \ bin \ node-gyp .js "rebuild) else (node" C: \ Program Files \ nodejs \ node_modules \ npm \ node_modules \ node-gyp \ bin \ node-gyp.js "rebuild)
Build projects in this solution one at a time. To enable parallel build, add the "/ m" parameter.
  unpack_xz_dep
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C: \ dexcalibur \ node_modules \ xz \ build \ Release \\ nothing.lib
  configure_and_make
  "eval" is not internal or external
  command, executable program, or batch file.
C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ V140 \ Microsoft.CppCommon.targets (171.5): error MSB6006: "cmd.exe" ended with code 1. [C: \ dexcalibur \ node_modules \ xz \ build \ deps \ xz.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C: \ Program Files (x86) \ MSBuild \ 14.0 \ bin \ msbuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C: \ Program Files \ nodejs \ node_modules \ npm \ node_modules \ node-gyp \ lib \ build.js: 262: 23)
gyp ERR! stack at ChildProcess.emit (events.js: 196: 13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal / child_process.js: 256: 12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C: \\ Program Files \\ nodejs \\ node.exe" "C: \\ Program Files \\ nodejs \\ node_modules \\ npm \\ node_modules \\ node-gyp \\ bin \\ node-gyp. js "" rebuild "
gyp ERR! cwd C: \ dexcalibur \ node_modules \ xz
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xz@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xz@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C: \ Users \ User \ AppData \ Roaming \ npm-cache \ _logs \ 2020-12-15T18_08_14_232Z-debug.log

NodeJs version 12.0.0 64 bit. Python 2.7 64bit. Registered in a system variable.

Tried so

npm install --global --production windows-build-tools --vs2015
npm config set msvs_version 2015 –global
npm config set python python2.7
npm install

The error remains.

**Comment by cclauss** [comment]
Node-gyp v3 vs. the current v7

**Comment by cclauss** [comment]
See https://github.com/nodejs/node-gyp/issues/2272 for steps to upgrade node-gyp (_not_ node).
