### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by dfdfdfs** [nodejs/node-gyp#2283]
I want to install this project https://github.com/FrenchYeti/dexcalibur

Tried commands
npm install --global --production windows-build-tools --vs2015
npm config set msvs_version 2015 –global
npm config set python python2.7

npm install --global node-gyp @ latest
for / f "delims ="% P in ('npm prefix -g') do npm config set node_gyp "% P \ node_modules \ node-gyp \ bin \ node-gyp.js"

The error remains

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\MSBuild\14.0\Bin ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:406:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dexcalibur\node_modules\xz
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in node-gyp.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! xz@2.0.2 install: node-gyp rebuild
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the xz@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-12-17T15_17_01_142Z-debug.log

Tell me what else to try?

**Comment by cclauss** [comment]
Node-gyp v3 vs. the current v7.  See #2272 for steps to upgrade node-gyp (not node).

**Comment by dfdfdfs** [comment]
I tried updating to version 7, the error remained.

I wrote to you   

**npm install --global node-gyp @ latest
for / f "delims ="% P in ('npm prefix -g') do npm config set node_gyp "% P \ node_modules \ node-gyp \ bin \ node-gyp.js"**

See 

Microsoft Windows [Version 6.3.9600]

User@WIN-9G17FRIREA8 C:\dexcalibur
# npm install --global node-gyp@latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\User\AppData\Roaming\npm\node-gyp -> C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@7.1.2
updated 1 package in 10.945s

User@WIN-9G17FRIREA8 C:\dexcalibur
# for /f "delims=" %P in ('npm prefix -g') do npm config set node_gyp "%P\node_modules\node-gyp\bin\node-gyp.js"

User@WIN-9G17FRIREA8 C:\dexcalibur
# npm config set node_gyp "C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"

User@WIN-9G17FRIREA8 C:\dexcalibur
# npm install
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> frida@14.1.3 install C:\dexcalibur\node_modules\frida
> prebuild-install || node-gyp rebuild


> xz@2.0.2 install C:\dexcalibur\node_modules\xz
> node-gyp rebuild


User@WIN-9G17FRIREA8 C:\dexcalibur\node_modules\xz
# if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:406:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dexcalibur\node_modules\xz
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! xz@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the xz@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-12-18T17_47_53_710Z-debug.log

**Comment by rvagg** [comment]
```
 gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin ENOENT
```

do you know if vs 2017 is properly installed? or do you have another version that it should be finding? Perhaps you can dig into that directory tree to see what it _should_ be finding and whether it's all there.

**Comment by laurenku** [comment]
I also had an issue with this error! It was resolved when I installed Visual Studio Community 2017.

**Comment by cclauss** [comment]
Can this issue be closed?
