### ISSUE TITLE
Unknown error: Error: EPERM: operation not permitted, read

### ISSUE THREAD

**Issue by hellojt9040** [nodejs/node-gyp#2288]
Not able to run any of the ng commands. Gone through some of the threads but in vain.
I followed #1830 and i am getting the same error. Need help!

**Comment by cclauss** [comment]
This is not the repo for `ng`.

**Comment by hellojt9040** [comment]
I followed #1830 and got that this is due node-gyp.

![image](https://user-images.githubusercontent.com/41210284/103154942-4c579300-47c1-11eb-8fbf-0c010d0e9bc4.png)

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v 5.1.0

Current is v7.1.2 https://github.com/nodejs/node-gyp/releases
