### ISSUE TITLE
Visual Studio Build Tools no installation

### ISSUE THREAD

**Issue by VictorPro007** [nodejs/node-gyp#2289]
Hello. I was installing all the tools required for node-gyp in Windows with the command: `npm install --global windows-build-tools`. 1 minute later, it log me that I can't install Visual Studio Build Tools and that I should restart. Can someone help me, please?

**Comment by cclauss** [comment]
https://github.com/felixrieseberg/windows-build-tools is the repo you want to post this to.

**Comment by VictorPro007** [comment]
Thanks
