### ISSUE TITLE
If you're going to require python why don't you let npm download it

### ISSUE THREAD

**Issue by Kreijstal** [nodejs/node-gyp#2291]
Let's say I'm in a Windows machine with no administrator access, when npm downloads node-gyp, node-gyp should by default see: There is no installation of python (or of a compiler for that matter) and just automatically download it, then use it, this will reduce friction by 90% of all node packages. And probably make node easier to use, for beginners, and experts alike.
Users shouldn't mangle with internal dependencies, otherwise what is npm other than a leaky abstraction?

**Comment by cclauss** [comment]
Your operating system vendor offers an admin-less install at https://www.microsoft.com/en-us/p/python-39/9p7qfqmjrfp7

**Comment by Kreijstal** [comment]
I mean, sure, but why does the user has to do this, this only causes problems for normal people trying to install packages
see
https://www.reddit.com/r/node/comments/ey82ov/its_2020_why_is_nodegyp_still_breaking_builds/
https://www.xspdf.com/resolution/53914572.html
https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

Well, anyway, thank you.
