### ISSUE TITLE
Node-gyp error 

### ISSUE THREAD

**Issue by Sentrycs** [nodejs/node-gyp#2308]
OS=Windows 10
Node 10.16.0
Yarn 1.22.10
The following errors at node-gyp have occurred
![Screenshot 2021-01-20 162527](https://user-images.githubusercontent.com/42841002/105323238-91a98d80-5bd2-11eb-83e6-32c359313e8a.jpg)
![Screenshot 2021-01-20 162436](https://user-images.githubusercontent.com/42841002/105323296-a38b3080-5bd2-11eb-9ca5-5a961d72d479.jpg)

 :

**Comment by cclauss** [comment]
To upgrade from node-gyp v3 to v7 try `npm install -g node-gyp`

**Comment by Sentrycs** [comment]
I did upgrade to v7 as you suggested, but the script above insists on running node-gyp@3.8.0 with the same error. How I force it to run v7?

**Comment by cclauss** [comment]
Perhaps open an issue at https://github.com/MetaMask/metamask-extension
