### ISSUE TITLE
My version of node-gyp is out of date

### ISSUE THREAD

**Issue by FaceFox** [nodejs/node-gyp#2310]
Hello, I have a problem with node-gyp, when  I try to install a package example dotenv I get a really annoying error. 
I updated node-gyp
I updated npm
Nothing works.
![image](https://user-images.githubusercontent.com/72278624/105525724-1f2bd100-5cea-11eb-8f1d-8b895648d259.png)

**Comment by tveronezi** [comment]
Try with a new version of `node-gyp`? It looks like you have `v5.1.0`

**Comment by chengkai2022** [comment]
> Try with a new version of `node-gyp`? It looks like you have `v5.1.0`

I have update the version of node-gpy as [](https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp )，but when i run it，it works on older one.why?
![屏幕截图(14)](https://user-images.githubusercontent.com/70818246/116236205-5b5f4980-a791-11eb-80c4-e745b7a77744.png)

**Comment by cclauss** [comment]
You are going backwards!  The error log now says you are using node-gyp v3.8.0 vs. https://github.com/nodejs/node-gyp/releases

**Comment by chengkai2022** [comment]
> You are going backwards!
> The error log now says you are using node-gyp v3.8.0 vs. https://github.com/nodejs/node-gyp/releas

look the info of bottom，i have updated as [](https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp)
node-gyp -v 8.0.0
but it dose't work👀👀.
your help is needed

**Comment by cclauss** [comment]
Can you please try @DeeDeeG [instructions here](https://github.com/nodejs/node-gyp/issues/2354#issuecomment-810429130) or https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp to try to get to a current node-gyp?

**Comment by chengkai2022** [comment]
> The log line `npm ERR! node-gyp -v v3.8.0` is what matters.
> 
> Can you please try @DeeDeeG [instructions here](https://github.com/nodejs/node-gyp/issues/2354#issuecomment-810429130) or
> https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp to try to get to a current node-gyp?

Thank you! i have tried to get to a new node-gyp https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp  the day before yesterday,but it dose’t work.Finally，I find node-sass  is the key,when i abandon it，everything is ok

**Comment by cclauss** [comment]
Nodes Sass is deprecated in favor of Dart Sass https://github.com/nodejs/node-gyp/labels/Node%20Sass%20--%3E%20Dart%20Sass
