### ISSUE TITLE
Attempting to install discord.js with error

### ISSUE THREAD

**Issue by madeyefire** [nodejs/node-gyp#2325]
<img width="727" alt="Screen Shot 2021-02-10 at 3 21 08 PM" src="https://user-images.githubusercontent.com/68868092/107568082-8388d480-6bb4-11eb-8fa1-7a972dafb9a7.png">

This is my first time doing anything of this sort, and I have no idea what any of this means. Any assistance is welcome.

**Comment by cclauss** [comment]
Node 8 is no longer supported.  https://github.com/nodejs/Release

The current version of npm is v7.5.3 https://www.npmjs.com/package/npm
