### ISSUE TITLE
warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### ISSUE THREAD

**Issue by raphael10-collab** [nodejs/node-gyp#2328]
Installing electron-rebuild gives this warning :

`warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

    O.S.: Ubuntu 18.04.4 Desktop
    -node: v14.5.0

**Comment by raphael10-collab** [comment]
@cclauss Can you explain me why you labelled this issue as "wrong repo"? 

     node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by cclauss** [comment]
#2220
