### ISSUE TITLE
Discord bot configure shows Input Files Missing Error

### ISSUE THREAD

**Issue by WickedWizard3588** [nodejs/node-gyp#2329]
Hey,
I installed node-gyp for my discord bot. I ran everything correctly until I reached `node-gyp configure`. I placed a `binding.gyp` file in the root of my project. 
<details>
<summary>Binding.gyp File</summary>
<br>
<pre>
<code>
{
    "targets": [
        {
            "target_name": "binding",
            "sources": [ "src/binding.cc" ]
        }
    ]
}
</code>
</pre>
</br>
</details>

Then, I ran, `node-gyp configure`. When I ran this, it showed that everything was ok, except for one part. The last three lines threw an error, that the `Input Files were missing`.
<details>
<summary>Configure Output</summary>
<br>
<pre>
<code>
 node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.7.0 | win32 | x64
gyp info find Python using Python version 3.9.1 found at "C:\Python39\python.exe"
gyp info find VS using VS2017 (15.9.28307.1401) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Chintu\\Discord\\Xyborg\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\15.7.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\15.7.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.7.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Chintu\\Discord\\Xyborg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Chintu\\Discord\\Xyborg\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
D:\Chintu\Discord\Xyborg\build\..\src\binding.cc
gyp info ok
</code>
</pre>
</br>
</details>

I thought that this was some ignorable error because the last line showed that `gyp info ok`. I proceeded with the `node-gyp build` command
<details>
<summary>Build Output</summary>
<br>
<pre>
<code>
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.7.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [D:\Chintu\Discord\Xyborg\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\Chintu\Discord\Xyborg
gyp ERR! node -v v15.7.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
</code>
</pre>
</br>
</details>

So, how do I fix that `Input Files Missing Error`, and finally use gyp, so that I can use `sqlite3`

Thanks for helping me :)

**Comment by cclauss** [comment]
> fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [D:\Chintu\Discord\Xyborg\build\binding.vcxproj]

Please provide the full pathname to your `src\binding.cc` file.

**Comment by WickedWizard3588** [comment]
Ok, I will attach a picture here of my whole bot folder, so that you can see the path. This is before running `configure`
![image](https://user-images.githubusercontent.com/67627239/107926002-2ec1d100-6f9b-11eb-9e30-234cbc8bcc0b.png)

**Comment by cclauss** [comment]
The image above shows that you have a `binding.gyp` file but not `binding.cc` file.
The absence of `binding.cc` is what the error message is complaining about.

**Comment by WickedWizard3588** [comment]
Where should I put that file then?

I tried putting it in the same directory as the `binding.gyp` file, but it still threw the same error

**Comment by WickedWizard3588** [comment]
Ok, so I found a fix I changed some things in my `binding.gyp file`
<details>
<summary>Binding.gyp file</summary>
<br>
<pre>
<code>
{
    "targets": [
        {
            "target_name": "binding",
            "sources": [ "binding.cc" ]
        }
    ]
}
</code>
</pre>
</br>
</details>

This helped me..... Thanks for the help @cclauss

**Comment by WickedWizard3588** [comment]
Copy paste the `binding.gyp` file, and then add an empty `binding.cc` file at the root, beside `package.json` @MS4794

**Comment by afrin1307** [comment]
Copy paste the binding.gyp file, and then add an empty binding.cc file at the root, beside package.json-this didnt work for me showing the same error
