### ISSUE TITLE
Building grunt error

### ISSUE THREAD

**Issue by GreXLin85** [nodejs/node-gyp#2335]
I was trying to build the template I bought with grunt but I get an error

* **Node Version**: 
* Node v15.7.0
* NPM 7.5.4
* **Platform**: 
* OS Name:                   Microsoft Windows 10 Pro
* OS Version:                10.0.19042 N/A Build 19042
* System Type:               x64-based PC
* **Compiler**: 
* msbuild /version & cl (i cant execute this command)
* **Module**: 
* https://elements.envato.com/flatkit-dashboard-ui-kit-FLRDLJ

<details><summary>

https://paste.ubuntu.com/p/gXdqb9xy9d/

</summary>
</details>

**Comment by cclauss** [comment]
Ouch!
> npm ERR! gyp info using node-gyp@3.8.0

https://github.com/nodejs/node-gyp/releases please upgrade

**Comment by GreXLin85** [comment]
I'm updated to 7.1.2 and I get the error again

* **Node Version**: 
* Node v15.9.0
* NPM 7.5.4
* Node-GYP 7.1.2

Error : https://paste.ubuntu.com/p/8YdYvDxcpy/

**Comment by cclauss** [comment]
The output still says
> error gyp info using node-gyp@3.8.0

**Comment by GreXLin85** [comment]
> 
> 
> The output still says
> 
> > error gyp info using node-gyp@3.8.0

What can I do in this situation
Updated Node
Updated GYP manually
