### ISSUE TITLE
Nodegyp Install Error

### ISSUE THREAD

**Issue by Umut-Ozkan** [nodejs/node-gyp#2336]
![unknown](https://user-images.githubusercontent.com/68606364/108629489-2c66e780-7471-11eb-9f71-68e8a43ba1e4.png)

**Comment by cclauss** [comment]
The error message says you are using Node-gyp when the current is v7.1.2

**Comment by Umut-Ozkan** [comment]
what should i use to prevent this

**Comment by umutfahriozkan** [comment]
@cclauss can you delete the issue? thanks
