### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by WickedWizard3588** [nodejs/node-gyp#2341]
Hey, 
I'm getting the syntax error below. This only occurs when the rebuild runs after the `npm install` and not when I run `node-gyp rebuild` manually.....

* **Node Version**: `node -v`: 14.16.0 `npm -v`: 7.5.6
* **Platform**: Windows 10, 64 Bit
* **Compiler**: MS Build Tools 2019, Python 3.7
* **Module**: General `npm i`

<details><summary>Verbose output from node-gyp:</summary>

```
λ npm i

> xyborg@2.0.5 install
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.16.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Chintu\\Discord\\Xyborg\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Chintu\Discord\Xyborg
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code 1
npm ERR! path D:\Chintu\Discord\Xyborg
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2021-03-13T10_22_46_181Z-debug.log
```

</details>

As mentioned above, this only occurs when I run `npm i` and not when I run `npm i sqlite3` or something else. Neither does it occur when I run `node-gyp rebuild`. I'm running on v`7.1.2`..... 
![image](https://user-images.githubusercontent.com/67627239/111027214-cee10d80-8414-11eb-95af-77b94f7d47d3.png)

**Comment by cclauss** [comment]
The second line of the output is `gyp info using node-gyp@3.8.0`

**Comment by WickedWizard3588** [comment]
But why is it showing an other version when I use `node-gyp -v` and how do I update this?

**Comment by WickedWizard3588** [comment]
Hey there,

I read this issue, #2272, and I tried the Command Prompt one for Windows, it worked perfectly fine. This tells me that it is a pain with npm's node-gyp. I cannot update it after v5 through the method given in the Wiki. Is there any workaround to use the npm's built-in one, by updating it to the current node-gyp version?

Thanks :)

**Comment by AdamMajer** [comment]
On Sat, Mar 13, 2021 at 04:46:44AM -0800, WickedWizard3588 wrote:
> But why is it showing an other version when I use `node-gyp -v` and how do I update this?

One is (old) module dependency and another is what you've installed
globally. The global install has nothing to do with the dependency in
the dependency chain.

Track down which module wants the old version and update it. `npm
outdated` comes to mind here.
