### ISSUE TITLE
Gyp-error

### ISSUE THREAD

**Issue by lukaszek11** [nodejs/node-gyp#2349]
npm i quick.db

> better-sqlite3@7.1.2 install C:\Users\Łukasz\Desktop\Clays v2.0\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=14.15.1 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.2 build-release
> node-gyp rebuild --release

gyp ERR! configure error 
gyp ERR! stack Error: spawn C:\Users\�ukasz\.windows-build-tools\python27\python.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Łukasz\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Łukasz\Desktop\Clays v2.0\node_modules\better-sqlite3
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code 1
npm ERR! path C:\Users\Łukasz\Desktop\Clays v2.0\node_modules\better-sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild --release

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Łukasz\AppData\Roaming\npm-cache\_logs\2021-03-23T08_21_59_641Z-debug.log
npm WARN Invalid version: "0.1"
npm WARN Clays v2.0 No description
npm WARN Clays v2.0 No repository field.
npm WARN Clays v2.0 No README data
npm WARN Clays v2.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Łukasz\AppData\Roaming\npm-cache\_logs\2021-03-23T08_21_59_893Z-debug.log 

Above I gave an error while installing quick.db. Does anyone have a way to solve it?

**Comment by cclauss** [comment]
Please upgrade node-gyp...
> gyp ERR! node-gyp -v v3.8.0

vs. v7.1.2 at https://github.com/nodejs/node-gyp/releases

**Comment by cclauss** [comment]
Unicode in the pathname might be a problem.
