### ISSUE TITLE
error running npm rebuild after nvm install

### ISSUE THREAD

**Issue by andrit** [nodejs/node-gyp#2350]
* **Node Version**: node@v8.17.0, npm@6.13.4
* **Platform**: Darwin Kernel Version 20.3.0
* **Compiler**: Apple clang version 11.0.0 
* **Module**: npm rebuild

<details><summary>Received the following error after running `npm rebuild` after wiping then reinstalling Node 8.17.0 with
`rm -rf /$NVM_DIR/versions/node/v8.17.0 && nvm install 8.17.0 && nvm use 8.17.0`
In the error it suggests reporting it here</summary>

```
gyp ERR! stack Error: glob dependency not found, set `options.disableGlob = true` if intentional
gyp ERR! stack     at defaults (/myProject/node_modules/rimraf/rimraf.js:46:11)
gyp ERR! stack     at rimraf (/myProject/node_modules/rimraf/rimraf.js:64:3)
gyp ERR! stack     at clean (/myProject/node_modules/node-gyp/lib/clean.js:20:3)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as clean] (/myProject/node_modules/node-gyp/lib/node-gyp.js:55:37)
gyp ERR! stack     at run (/myProject/node_modules/node-gyp/bin/node-gyp.js:87:30)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:132:7)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:181:9)
gyp ERR! stack     at Function.Module.runMain (module.js:696:11)
gyp ERR! stack     at startup (bootstrap_node.js:204:16)
gyp ERR! stack     at bootstrap_node.js:625:3
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/aritter/.nvm/versions/node/v8.17.0/bin/node" "/myProject/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /myProject/node_modules/node-sass
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

</details>

**Comment by DeeDeeG** [comment]
Two suggestions...

- Try `npm ci`, which will delete your `node_modules` and reinstall/rebuild all the dependencies. It seems your project's local copy of `rimraf` is missing its dependency `glob`. Doing `npm ci` should fix that.
- node-gyp 3 is quite old. It would be a good idea to run a newer copy of node-gyp... You can get newer node-gyp bundled with newer npm: `npm install -g npm@6` to get the latest `npm` from the v6.x series... Or if you're comfortable with potentially breaking changes in npm, upgrade to npm v7: `npm install -g npm@latest`

**Comment by andrit** [comment]
cool, thanks. 
Yeah this came up as a problem while Im working on a task to update a big Ember 2.4 project.
I was doing alot of tearing down and reinstalling node versions  and somewhere in that is probably where the issue came up.
I was in the exploratory phase of my update strategy, anyway.
My solution ended up being trashing that branch and starting from scratch (I had figured out a pretty good set of steps to move forward with)

The error didnt show up after that.
This is good advice though. So, thanks.
