### ISSUE TITLE
MSVC address sanitizer - the specified module not found

### ISSUE THREAD

**Issue by aminya** [nodejs/node-gyp#2363]
* **Node Version**:  v15.14.0, v7.7.6
* **Platform**:  Win 10 x64
* **Compiler**:  MSVC Version 16.10.0 Preview 1.0
* **Module**:  
https://github.com/atom-community/zadeh/tree/asan

<details><summary>Verbose output (from npm or node-gyp):</summary>
<br/>

I enabled fsanitize like this in node-gyp
https://github.com/atom-community/zadeh/blob/3db452abe43e568feba69181d9b0ecaef4f5db1c/binding.gyp#L100-L103
```py
                "/fsanitize=address",
                "/Zi",
                "/INCREMENTAL:NO",
```

Here is how to install and build:
```
> npm install
> node-gyp rebuild --debug
```

Basically running any code that uses the library:

temp.js
```js
require("./build/Debug/zadeh.node")
```

```
❯ node ./temp.js --verbose
node:internal/modules/cjs/loader:1151
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\zadeh\build\Debug\zadeh.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\zadeh\temp.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```

</details>

It seems that the address sanitizer dll isn't actually found by Node although according to the docs, the libraries are linked automatically.

The docs for address sanitizers:
https://docs.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-160

Adding the full link to the libraries doesn't fix the issue:
```
      "libraries": [ "C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.29917/bin/Hostx64/x64/clang_rt.asan_dbg_dynamic-x86_64.dll", "C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.29917/lib/x64/clang_rt.asan_dbg_dynamic_runtime_thunk-x86_64.lib" ],
```

**Comment by aminya** [comment]
On a second try, adding the following two paths to my PATH environment variable seems to fix the issue!
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.29917/bin/Hostx64/x64
```
and 
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.29917/lib/x64/
```

A bit manual and hacky, but seems to do the job.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by aminya** [comment]
Adding `fsanitize` should be enough for MSVC 16.9 Preview 3 or later. But `node-gyp` doesn't add these libraries to the PATH.

> If you are on Visual Studio version 16.9 Preview 3 or later, if thefsanitize=address compiler flag is specified, ASan libraries are automatically linked (both for console and IDE builds).

https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/#compiling-with-asan-from-the-console

**Comment by StefanStojanovic** [comment]
Together with being stale for too long, this issue also targets old, no longer supported versions. For those reasons, I'm closing this issue now. If you experience similar behavior again, feel free to either reopen this one or open a new one.
