### ISSUE TITLE
Acid test for macOS fails

### ISSUE THREAD

**Issue by mTvare6** [nodejs/node-gyp#2376]
* **Node Version**: v15.13.0 node, 7.7.6 npm
* **Platform** MacOS 11.3
* **Compiler** : Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

<details><summary>Acid test for macos fails even though `xcode-select -print-path` shows `/Applications/Xcode.app/Contents/Developer`</summary>

**Comment by cclauss** [comment]
That path would correspond to [Solution #1](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#solutions) where the full Xcode has been installed.  Can you please make sure that Xcode is up-to-date?

**Comment by mTvare6** [comment]
> That path would correspond to [Solution #1](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#solutions) where the full Xcode has been installed.
> Can you please make sure that Xcode is up-to-date?

Yep, I reinstalled XCode yesterday as certain things stopped working and says CLI tools weren't to be found
