### ISSUE TITLE
Update "tap" and "standard" to newer version

### ISSUE THREAD

**Issue by owl-from-hogvarts** [nodejs/node-gyp#2379]
Node-gyp uses to old tap `12.7.0`. In fact now last tap version is `15.x.x`
Node-gyp uses to old standard package `14.3.4`. In fact now last tap version is `16.x.x`

**Comment by rvagg** [comment]
Yeah, we got stuck on 12.x because it dropped support for versions of Node.js that we still needed to support in 13.x+ (we did upgrade but had to roll back). That hasn't been revisited in a while so it might be possible to do it now.

**Comment by owl-from-hogvarts** [comment]
@rvagg the latest [changelog](https://node-tap.org/changelog/#breaking-changes) states that tap drop `node < 10` support. In node-gyp readme there is no states about minimal supported version of node, that is required to run node-gyp, but github checks run tests for node.js 10 and above

**Comment by rvagg** [comment]
npm has been more aggressive in their minimum version support in the last year or two so it's probably appropriate for us too. Mostly we just need to make sure we don't get ahead of npm, but otherwise we should be able to move forward.
Feel free to do an upgrade and PR it if you want to try and reconcile these things.

**Comment by owl-from-hogvarts** [comment]
lol it seems that the version of `standard` we use does not know how to work with static keyword and class property decalration syntax: 
```js
class foo {
  static bar = 'foobar'
}
```
that code raise exeption: 
```
Parsing error: Unexpected token =
```

**Comment by owl-from-hogvarts** [comment]
@rvagg 
As i figured out, we can safly update both `tap` and standard to newest versions.

There «Node.js v10 or higher must be installed to run this program» in readme of npm/cli repo.

According to `tap` [changelog](https://node-tap.org/changelog/) they dropped support of node.js below 10 version
> Drop support for node <10

`standard` drop support of node.js 8 [here](https://github.com/standard/standard/blob/master/CHANGELOG.md#1500---2020-10-21) thus i can make a conclusion that it should support node.js 10
