### ISSUE TITLE
 Cannot find module 'C:\...\node-gyp\bin\node-gyp.js'

### ISSUE THREAD

**Issue by skaneprime** [nodejs/node-gyp#2381]
Hi! I'm trying to use node-gyp but when I call `node-gyp` in shell it throws me this error 
```
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "" build )
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\node_modules\node_modules\node-gyp\bin\node-gyp.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

What should I do? 
I tried to install windows-build-tools
originally `npm i -g windows-build-tools` it installs for eternal but `npm i -g windows-build-tools@4.0.0` works

**Comment by skaneprime** [comment]
Tried to reinstall but didn't go well 
![image](https://user-images.githubusercontent.com/50551032/115675243-171a1680-a357-11eb-9d88-f18e0d322ceb.png)

**Comment by skaneprime** [comment]
Installed build tools from here too. https://github.com/nodejs/node-gyp/wiki/Common-issues 
Nothing changed.

**Comment by owl-from-hogvarts** [comment]
as i know, npm uses its own copy of node-gyp package. Check if in node.js installation folder (Default `C:\Program Files\nodejs` on windows)
`nodejs installation folder\node_modules\npm\node_modules\node-gyp` exists. 

>Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\node_modules\\***node_modules***\node-gyp\bin\node-gyp.js'


P.S. There is an additional `node_modules` path segment in your error message. I think it is related to error. Please provide version of node and npm you are using 😃

**Comment by skaneprime** [comment]
@owl-from-hogvarts 

`C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp` exsits 

NodeJS: v14.14.0
NPM: 6.14.8

**Comment by owl-from-hogvarts** [comment]
According to this https://github.com/nodejs/node-gyp/issues/2272, you should try to run `npm config delete node_gyp`.

My thoughts are that somewhere in configs is a line which tells to npm to use 
` 'C:\Program Files\nodejs\node_modules\npm\node_modules\node_modules\node-gyp\bin\node-gyp.js'` path which contain excess `node_modules` path segment. The above line should delete wrong line from config

**Comment by joshuanathanson** [comment]
> According to this #2272, you should try to run `npm config delete node_gyp`.
> 
> My thoughts are that somewhere in configs is a line which tells to npm to use
> ` 'C:\Program Files\nodejs\node_modules\npm\node_modules\node_modules\node-gyp\bin\node-gyp.js'` path which contain excess `node_modules` path segment. The above line should delete wrong line from config

Thanks!  This got me unblocked

**Comment by owl-from-hogvarts** [comment]
@skaneprime try with `-g` flag which will execute this command for global config file. It is all i can propose now)

**Comment by skaneprime** [comment]
> @skaneprime try with `-g` flag which will execute this command for global config file. It is all i can propose now)

Didn't solve it neither 
![image](https://user-images.githubusercontent.com/50551032/116793431-6686e200-aacf-11eb-8459-1ce4a688e2b6.png)

**Comment by owl-from-hogvarts** [comment]
@skaneprime pls, run `npm config ls` with and without `-g` flag. If you will find any node-gyp mention, remove these lines by running `npm config delete` or by editing `.npmrc` file in your user direcory. Notice: if you have run `npm config ls` with `-g` flag do not forget to supply this one for the command `npm config delete`. Also there may be environment variable, try to explore env vars to find one that mention node-gyp. There may be `npm_config_node_gyp`  env var. Try to remove it. if it will not help, try to run original command with `--verbose` flag and provide output.

**Comment by owl-from-hogvarts** [comment]
upon the whole my guess is that you have `node_gyp` environment var setted up, and setted up wrong

**Comment by skaneprime** [comment]
> @skaneprime pls, run `npm config ls` with and without `-g` flag. If you will find any node-gyp mention, remove these lines by running `npm config delete` or by editing `.npmrc` file in your user direcory. Notice: if you have run `npm config ls` with `-g` flag do not forget to supply this one for the command `npm config delete`. Also there may be environment variable, try to explore env vars to find one that mention node-gyp. There may be `npm_config_node_gyp` env var. Try to remove it. if it will not help, try to run original command with `--verbose` flag and provide output.
I have run `npm config ls` with and without `-g`. There's nothing about `node gyp`. Even inside of `npmrc` 
![image](https://user-images.githubusercontent.com/50551032/116847826-050c6380-abf4-11eb-9d17-fc9b5db31348.png)
![image](https://user-images.githubusercontent.com/50551032/116847833-0b024480-abf4-11eb-8813-26d2e7e32b89.png)
![image](https://user-images.githubusercontent.com/50551032/116847843-0f2e6200-abf4-11eb-881f-e521167f4251.png)

**Comment by owl-from-hogvarts** [comment]
What about env var?

**Comment by skaneprime** [comment]
Sorry for long response. How to check environment var and delete it?

**Comment by owl-from-hogvarts** [comment]
@skaneprime if you are using `cmd`, to list all env vars type `set`. If you will find mention of node-gyp, type `set VARNAME=`, where `VARNAME` is the name of env var that mention node-gyp, to unset it for current instance of terminal, and try to run your original command. If it will help, run next command to unset this var on userwide level across system: `REG delete HKCU\Environment /F /V VARNAME`.  `/F` flag will not prmompt you for confirmation, `/V` is used to specify var name to delete.

PS. In fact we are intrested in `node_gyp` env var

**Comment by skaneprime** [comment]
> @skaneprime if you are using `cmd`, then to list all env vars type `set`. If you will find mention of node-gyp, type `set VARNAME=`, where `VARNAME` is the name of env var that mention node-gyp, to unset it for current instance of terminal, and try to run your original command. If it will help, run next command to unset this var on userwide level across system: `REG delete HKCU\Environment /F /V VARNAME`. `/F` flag will not prmompt you for confirmation, `/V` is used to specify var name to delete.
> 
> PS. In fact we are intrested in `node_gyp` env var

There no `node_gyp` var 
![image](https://user-images.githubusercontent.com/50551032/117128466-1b5a2100-ada6-11eb-9bd5-4ce7aa87f35b.png)

**Comment by owl-from-hogvarts** [comment]
ok, pls try to run `npx node-gyp` instead of `node-gyp` in original folder (where issue is previosly arose)

**Comment by owl-from-hogvarts** [comment]
another my guess is that, as i saw, you have added wrong node-gyp to your PATH variable: you have added node-gyp from internals of npm, but not from global node_moduels location (by default `%APPDATA%\npm`). When you have run `node-gyp` it has executed node-gyp from internals of npm and because npm uses magical `node-gyp.cmd` to launch the node-gyp itself, you got such strange error.

The solution is:
1. press `Win` + `R`
2. type `SystemPropertiesAdvanced.exe` and press `Enter`
3. press `Environment Variables` button in bottom right corener of the window
4. select `Path` var in User variables area and press `Edit`
5. find row which contain `appdata\roamning\npm`, select it and press `up` button on the right side of windows so many times until the line will not be higher than all ones which contain `C:\Program Files\nodejs\node_modules\npm`

By moving this line up, we raising priority of this path, that mean windows will earlier check this path than others (especially wrong one). 

After doing this restart your terminals and try to run `node-gyp` as in original comment.
But i have heard that it is not recomended way to do the stuff. better run commands via `npx`

PS. more clear [guide](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/) how to change env vars

**Comment by skaneprime** [comment]
> ok, pls try to run `npx node-gyp` instead of `node-gyp` in original folder (where issue is previosly arose). it should use globally intalled version of node-gyp

![image](https://user-images.githubusercontent.com/50551032/117197924-0ce52700-adf1-11eb-845f-ede9560425e9.png)

**Comment by skaneprime** [comment]
> another my guess is that, as i saw, you have added wrong node-gyp to your PATH variable: you have added node-gyp from internals of npm, but not from global node_moduels location (by default `%APPDATA%\npm`). When you have run `node-gyp` it has executed node-gyp from internals of npm and because npm uses magical `node-gyp.cmd` to launch the node-gyp itself, you got such strange error.
> 
> The solution is:
> 
> 1. press `Win` + `R`
> 2. type `SystemPropertiesAdvanced.exe` and press `Enter`
> 3. press `Environment Variables` button in bottom right corener of the window
> 4. select `Path` var in User variables area and press `Edit`
> 5. find row which contain `appdata\roamning\npm`, select it and press `up` button on the right side of window so many times until the line will not be higher than all ones which contain `C:\Program Files\nodejs\node_modules\npm`
> 
> By moving this line up, we raising priority of this path, that mean windows will earlier check this path than others (especially wrong one).
> 
> After doing this restart your terminals and try to run `node-gyp` as in original comment.
> But i have heard that it is not recomended way to do the stuff. better run commands via `npx`
> 
> PS. more clear [guide](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/) how to change env vars

Works! Thank you! I wouldn't now that the error was in priority stuff! 
![image](https://user-images.githubusercontent.com/50551032/117198622-ea9fd900-adf1-11eb-97f6-8101a328f02f.png)

**Comment by kairois** [comment]
```shell
Error: Cannot find module 'nopt'
Require stack:
- /usr/share/nodejs/node-gyp/lib/node-gyp.js
- /usr/share/nodejs/node-gyp/bin/node-gyp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/share/nodejs/node-gyp/lib/node-gyp.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/node-gyp/lib/node-gyp.js',
    '/usr/share/nodejs/node-gyp/bin/node-gyp.js'
  ]
``` 

What forked in my case was, removing the path 
```shell
sudo rm -rf /usr/share/nodejs/node-gyp/
``` 

Then reinstalling the package no need to change the version of npm or node. 

```shell
npm i node-gyp -g
```
