### ISSUE TITLE
error in python 3.8.5 

### ISSUE THREAD

**Issue by salimzadeh** [nodejs/node-gyp#2386]
Hi guys
whene use python 3.8.5 in windows 10 after use "yarn install" command it  make error :
gyp ERR! configure error

in the file configure.js line 451 must be change to this :
    var args = ['-c', 'import sys; print **(**"%s.%s.%s" % sys.version_info[:3];**)**']

**Comment by cclauss** [comment]
Look in the error logs for a line that says `ERR! node-gyp = v` to know what ancient version of node-gyp is running.

Please upgrade to node-gyp v8.
