### ISSUE TITLE
node-gyp 8.0.0 failed to build node-ffi-napi while node-gyp 7.1.2 worke-error on call to preprocess_asm

### ISSUE THREAD

**Issue by softguy** [nodejs/node-gyp#2399]
Hi, Recently I found an error after upgrading node-gyp from 7.1.2 to 8.0.0,
node v14.16.0
node-ffi-napi are from the latest git repository

C:\opn2\node-ffi-napi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.16.1 | win32 | x64
gyp info find Python using Python version 3.6.1 found at "C:\pub\python\Python36\python.exe"
gyp info find VS using VS2019 (16.9.31105.61) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\pub\python\Python36\python.exe
gyp info spawn args [
gyp info spawn args   'F:\\pub\\node-v14.16.1-win-x64\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\opn2\\node-ffi-napi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\pub\\node-v14.16.1-win-x64\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\a\\AppData\\Local\\node-gyp\\Cache\\14.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\a\\AppData\\Local\\node-gyp\\Cache\\14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=F:\\pub\\node-v14.16.1-win-x64\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\a\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\opn2\\node-ffi-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\opn2\\node-ffi-napi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn[0m C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m [
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m   'build/binding.sln',
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m   '/clp:Verbosity=minimal',
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m   '/nologo',
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m   '/p:Configuration=Release;Platform=x64'
[0m[37;40mgyp[0m [0m[32minfo[0m [0m[35mspawn args[0m ]
[0mBuilding the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
  '"preprocess_asm.cmd"' is not recognized as an internal or external command,
  operable program or batch file.
C:\opn2\node-ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: The command "call call "preprocess_asm.cmd" "
include" "config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" exited w
ith code 1. [C:\opn2\node-ffi-napi\build\deps\libffi\ffi.vcxproj]
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\opn2\node-ffi-napi\build\Release\\nothing.lib
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.onExit (F:\pub\node-v14.16.1-win-x64\node_modules\node-gyp\lib\build.js:194:23)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (events.js:315:20)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.21376
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "C:\\pub\\node\\node.exe" "C:\\pub\\node\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m C:\opn2\node-ffi-napi
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v14.16.1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v8.0.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m
[0m
C:\opn2\node-ffi-napi>

see node-ffi-napi failed to build. 
However, switching node-gyp from 8.0.0 back to 7.1.2 seems to fix the issue !

After some inveistigation here found the issue is that the generated xxxx.props files contains invalid path to preprcoess_asm.cmd 
Seem below are the differences between 2 versions:

in pylib\gyp\generator\msvs.py:

LINE 421
        command.insert(0, "call")

<<<
        # Fix the paths
        # TODO(quote): This is a really ugly heuristic, and will miss path fixing
        #              for arguments like "--arg=path" or "/opt:path".
        # If the argument starts with a slash or dash, it's probably a command line
        # switch
        arguments = [i if (i[:1] in "/-") else _FixPath(i) for i in cmd[1:]]
        arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in arguments]

>>>
        arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in cmd[1:]]

BELOW IS MY  temporary fix:

        '''@@@TMP FIX FOR node-ffi-napi NOT COMPILING issue
        
        #BECAUSE node-gyp 7.1.2 works BUT node-gyp 8.0.0 DOES NOT WORK
        # found out that the issue is in generated libffi.props 
        this is generated by node-gyp 8.0.0
        
      <CommandLineTemplate>call call &quot;preprocess_asm.cmd&quot; &quot;include&quot; &quot;config/win/x64&quot; &quot;%(Identity)&quot; &quot;$(IntDir)%(Filename).asm&quot;</CommandLineTemplate>
        
        in VS2019 will cause error when node-gyp build:
        
        Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
        '"preprocess_asm.cmd"' is not recognized as an internal or external command,
        operable program or batch file.
  
        
        this is generated by node-gyp 7.1.2
      <CommandLineTemplate>call call &quot;..\..\..\deps\libffi\preprocess_asm.cmd&quot; &quot;..\..\..\deps\libffi\include&quot; &quot;..\..\..\deps\libffi\config\win\x64&quot; &quot;%(Identity)&quot; &quot;$(IntDir)%(Filename).asm&quot;</CommandLineTemplate>
        this worked !!!

        THIS IS THE ORIGINAL ONE LINE

        arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in cmd[1:]]

        THS FIX IS COMING FROM node-gyp 7.1.2 code
        '''
        #@@@ ORIGINAL 7.1.2 working code
        # Fix the paths
        # TODO(quote): This is a really ugly heuristic, and will miss path fixing
        #              for arguments like "--arg=path" or "/opt:path".
        # If the argument starts with a slash or dash, it's probably a command line
        # switch
        arguments = [i if (i[:1] in "/-") else _FixPath(i) for i in cmd[1:]]
        arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in arguments]

        #@@@ COMMENT OUT FOR FAILED CODE in 8.0.0
        #@@@arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in cmd[1:]]                
        

Hopefully this is useful to anybody who might have similar issue and  somebody know more internal about gyp can have a permanent fix and integrate into master.

Thanks.

**Comment by imatlopez** [comment]
I believe this issue should go in the `gyp-next` repo (python), then ask for node-gyp maintainers to update gyp.

**Comment by bliu2683** [comment]
Thanks this post saved my life. BTW if someone encounters the same issue while using `electron-rebuild` like me, downgrade your `electron-rebuild` to `@2.3.5`, which is the last version using `node-gyp@7.1.0`.

**Comment by lkallas** [comment]
Addition to your fix there's possibility to just `npm i -D node-gyp@7.1.2` which makes it use the the `node-gyp` that works for you from the devDependencies. That way you do not need to fiddle with globally installed `node-gyp`.

Alternatively the `node-ffi-napi` could update their `deps/libffi/libffi.gyp` to point to absolute paths not relative ones that gets broken in later versions of `node-gyp`.

**Comment by gengjiawen** [comment]
close via https://github.com/nodejs/gyp-next/pull/121
