### ISSUE TITLE
install bcrypt error: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by MadShura** [nodejs/node-gyp#2405]
I'm already having the correct dependencies
python 2.7
VS2017
OS: window10 version:2004
when type npm install bcrypt still throw sth wrong.
how can i do?
is like as gyp  error
here is the err msg:
PS C:\Users\AXL\Desktop\tieba\gaopudaimaApi> npm install bcrypt
npm ERR! code 1
npm ERR! path C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.4 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.0 found at "D:\python 2.7\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1525) found at:
npm ERR! gyp info find VS "D:\vscode\c++"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn D:\python 2.7\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt\build\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\AXL\AppData\Local\node-gyp\Cache\14.15.4\include\node\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\Users\AXL\AppData\Local\node-gyp\Cache\14.15.4',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\Users\\AXL\\AppData\\Local\\node-gyp\\Cache\\14.15.4\\<(target_arch)\\node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.onCpExit (C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)npm ERR! gyp ERR! stack at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "D:\node\node.exe" "C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\AXL\AppData\Local\npm-cache_logs\2021-05-20T20_50_41_119Z-debug.log

**Comment by MadShura** [comment]
waiting your reply ,save me pls~

**Comment by cclauss** [comment]
Python 2 died 500+ days ago.  Please upgrade.

**Comment by cclauss** [comment]
See https://github.com/nodejs/node-gyp/issues?q=label%3Abcrypt+is%3Aclosed

**Comment by MadShura** [comment]
i don't know why but when use yarn add bcrypt , is work!
thank you @cclauss
