### ISSUE TITLE
xcode-select setup no longer works

### ISSUE THREAD

**Issue by void8** [nodejs/node-gyp#241]
Running on Mac OS X 10.8.3, the code that executes 'xcode-select -print-path' no longer works.  xcode-select is a symlink to xcrun, which doesn't provide the same functionality.

xcode-select comes from com.apple.pkg.Essentials.

**Comment by Trott** [comment]
@nodejs/node-gyp Should this remain open?

**Comment by gibfahn** [comment]
Don't think so, comment if you disagree.
