### ISSUE TITLE
why node-gyp need to http GET node?

### ISSUE THREAD

**Issue by peterxia** [nodejs/node-gyp#242]
[node@irdgc3 hello-world]$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.10.2 | linux | x64
gyp http GET http://nodejs.org/dist/v0.10.2/node-v0.10.2.tar.gz

I had install nodejs, npm and noed-gyp

other, because here, localhost can not direct connect to www, so now i use http proxy server, npm is ok, 
but node-gyp , how do?

**Comment by amersaw** [comment]
What if I don't have internet access at all, I'm able only to download the required files manually and copy them locally to the destination machine.
Is there any option allows me to do that ?
