### ISSUE TITLE
I can't use Node-gyp v3.8.0 to install packages for my project

### ISSUE THREAD

**Issue by yukkon** [nodejs/node-gyp#2424]
I try to install node_packages for project ang receive the error

2274 error gyp ERR! node -v v16.2.0
2274 error gyp ERR! node-gyp -v v3.8.0
2274 error gyp ERR! This is a bug in `node-gyp`.
2274 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
2274 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
2274 error Build failed with error code: 7

* **Node Version**: 16.2.0
* **Platform**: OS Name:                   Microsoft Windows 10 Pro for Workstations
OS Version:                10.0.19042 N/A Build 19042
System Type:               x64-based PC
* **Compiler**: msbuild' is not recognized
*I use "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" 
* **Module**: I try to install all node packeges, but node-sass use node-gyp

<details><summary>2274 error gyp ERR! node -v v16.2.0
2274 error gyp ERR! node-gyp -v v3.8.0
2274 error gyp ERR! This is a bug in `node-gyp`.
2274 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
2274 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
2274 error Build failed with error code: 7</summary>

```
[2021-05-31T14_33_42_287Z-debug.log](https://github.com/nodejs/node-gyp/files/6570986/2021-05-31T14_33_42_287Z-debug.log)
```

</details>

**Comment by cclauss** [comment]
Closing as dup of #2423
