### ISSUE TITLE
npm install 引发的node-gpy rebuild问题

### ISSUE THREAD

**Issue by Dylan-lijl** [nodejs/node-gyp#2429]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
c1xx : fatal error C1083: 无法打开源文件: “..\src\binding.cc”: No such file or directory [E:\learn\tuling_demo\mall-admin-web\build\binding.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onExit (E:\learn\tuling_demo\mall-admin-web\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\learn\\tuling_demo\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild"
gyp ERR! cwd E:\learn\tuling_demo\mall-admin-web
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code 1
npm ERR! path E:\learn\tuling_demo\mall-admin-web
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2021-06-05T05_56_11_232Z-debug.log

**Comment by fuzhuyuan** [comment]
Me too.

**Comment by nightwindnw** [comment]
应该是需要按照MSVC的构建工具，懒得搞可以直接用Visual Studio installer 安装一下node js。

**Comment by fplun** [comment]
就是死活装 不上

**Comment by cxp4** [comment]
安装好之后我的MSBuild在current目录下不在15.0目录下。

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
