### ISSUE TITLE
Maybe command "node-gyp configure" generated wrong .vcproj file on Windows.

### ISSUE THREAD

**Issue by warrenwyf** [nodejs/node-gyp#244]
I am a beginner of node-gyp, I stucked in first sample of node.js addon.

When I run the command "node-gyp build", I got an error "LINK : fatal error LNK1181: cannot open input file 'C:\Users\xxx.node-gyp\0.10.5\node.lib' "

I checked the .vcproj file, there is a variable $(Configuration) before "\node.lib", After I changed it to "$(ConfigurationName)" building is okay.

I am not sure if the "node-gyp build" command generated the wrong project file?

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.
