### ISSUE TITLE
Unknown file extension ".node" in ES6 module

### ISSUE THREAD

**Issue by adam-nielsen** [nodejs/node-gyp#2454]
I have a problem with multiple Node modules, all of which are using node-gyp, and so I am suspecting the problem must lie with either node-gyp, or the way to use node-gyp has changed and these packages have not been updated.

When I create an ES6 module (i.e. I add `"type": "module"` to `package.json`) then try to use a module (any module, apparently) that has been compiled with node-gyp, I get an error like this:
```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for node_modules/talib/build/Release/talib.node
    at new NodeError (node:internal/errors:363:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:105:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:243:31)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:75:21)
    at async Promise.all (index 0)
    at async link (node:internal/modules/esm/module_job:80:9) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```
It seems that when Node is running an ES6 module, it is no longer able to read any of the `.node` files that node-gyp has produced.  When not using an ES6 module and using `require()` instead of `import` then everything works fine.

* **Node Version**: v16.2.0, npm 7.14.0
* **Platform**: `Linux 5.12.6-arch1-1 #1 SMP PREEMPT Sun, 23 May 2021 00:45:50 +0000 x86_64 GNU/Linux`
* **Compiler**: gcc version 11.1.0
* **Module**: Tested talib and netcdf4, but talib is small so a good example

<details><summary>Verbose output (from npm or node-gyp):</summary>
No errors produced by node-gyp, the module compiles and installs successfully.

EDIT: Here is the successful output of `npm --verbose install` as requested by @cclauss:
```
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '--verbose', 'install' ]
npm info using npm@7.14.0
npm info using node@v16.2.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 0ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/uqaniel1/incoming/gyp-test/.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/home/uqaniel1/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 6ms
npm timing npm:load:configload Completed in 6ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 0ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 10ms
npm timing config:load:flatten Completed in 1ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 16ms
npm timing idealTree:userRequests Completed in 0ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 18ms
npm timing reify:loadTrees Completed in 22ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 1ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/nan Completed in 168ms
npm timing reifyNode:node_modules/talib Completed in 249ms
npm timing reify:unpack Completed in 250ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 0ms
npm info run talib@1.1.4 install node_modules/talib node ./src/lib/build.js && node-gyp configure && node-gyp build
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 472ms
npm timing auditReport:getReport Completed in 473ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 475ms
npm info run talib@1.1.4 install { code: 0, signal: null }
npm timing build:run:install:node_modules/talib Completed in 18820ms
npm timing build:run:install Completed in 18820ms
npm timing build:deps Completed in 18821ms
npm timing build Completed in 18821ms
npm timing reify:build Completed in 18821ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 3ms
npm timing reify Completed in 19108ms

added 2 packages, and audited 3 packages in 19s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 19116ms
npm verb exit 0
npm timing npm Completed in 19269ms
npm info ok 
```
----
</details>

To reproduce the problem, do:

* Add `"type": "module"` to `package.json`
* Run `npm install talib`
* Add `import talib from 'talib'` to `index.js`
* Run `node index.js`
* Receive error about .node filename extension being unknown

I have looked through the documentation and issues and can't find much about this issue, so my apologies if this is covered somewhere and I have missed it.

**Comment by cclauss** [comment]
Verbose output is missing.

**Comment by adam-nielsen** [comment]
You can run `npm install talib` on your own machine to see the verbose output.  I don't think it's relevant in this case as the module is being compiled successfully.

The problem comes when you change your project to become an ES6 module - suddenly the previously working node-gyp output no longer works.

I will run the `npm install` and update the ticket with the above output but I'm not sure it will give you any useful information.

**Comment by rvagg** [comment]
I think you're going to have to take this up over at nodejs/node with the folks working on ESM. Have a read of https://nodejs.org/api/esm.html first, it's quite a complicated set of constraints they're solving for. Especially https://nodejs.org/api/esm.html#esm_resolver_algorithm which even mentions addons.

My understanding is that .js, .cjs, and .mjs are the only file extensions supported by the ESM resolver at the moment. You can run it with `--experimental-specifier-resolution` to get .node and .json back, for now: https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm

A couple of things you could do to work around this: do the loading from a CJS file, giving it a .cjs extension within your package, then `module.exports = require('....node')` from there, and `import foo from './loader.cjs'` in your ESM file. Or, make a subdirectory in your project with a package.json in it with just `{"type": "commonjs"}` in it then your files in that directory can do the `module.exports=require('...')` and be just .js files (tbh I only know this works for `"module"` but I don't see why it wouldn't work the other way).

Until it evolves further in nodejs/node, you're better off just loading from a CJS file, in whatever way you can pull it off. Sorry!
