### ISSUE TITLE
Potential risk:  	External Control of File Name or Path 

### ISSUE THREAD

**Issue by kerenren** [nodejs/node-gyp#2463]
Source code:
https://github.com/nodejs/node-gyp/blob/f0882b1264b2fa701adbc81a3be0b3cba80e333d/gyp/tools/pretty_gyp.py#L144Attack 

Description: This call to open() contains a path manipulation flaw. The argument to the function is a filename constructed using user-supplied input. If an attacker is allowed to specify all or part of the filename, it may be possible to gain unauthorized access to files on the server, including those outside the webroot, that would be normally be inaccessible to end users. The level of exposure depends on the effectiveness of input validation routines, if any.

Remediation: Validate all user-supplied input to ensure that it conforms to the expected format, using centralized data validation routines when possible. When using blocklists, be sure that the sanitizing routine performs a sufficient number of iterations to remove all instances of disallowed characters.

References: [CWE](http://cwe.mitre.org/data/definitions/73.html) [WASC](http://projects.webappsec.org/w/page/13246952/Path%20Traversal)

**Comment by rvagg** [comment]
please take it up with https://github.com/nodejs/gyp-next (or get a more intelligent code scanning tool)
