### ISSUE TITLE
Use of a Broken or Risky Cryptographic Algorithm

### ISSUE THREAD

**Issue by kerenren** [nodejs/node-gyp#2464]
Source code: 
https://github.com/nodejs/node-gyp/blob/f0882b1264b2fa701adbc81a3be0b3cba80e333d/gyp/pylib/gyp/xcodeproj_file.py#L433

https://github.com/nodejs/node-gyp/blob/4d036526c5347ad6fb0394993bda05f8260f7ae4/gyp/pylib/gyp/generator/make.py#L1995

Description: This function uses the hashlib.sha1() function, which uses a hash algorithm that is considered weak. In recent years, researchers have demonstrated ways to breach many uses of previously-thought-safe hash functions such as MD5.

Remediation: Consider using a stronger algorithm in order to prevent attackers from being able to manipulate hash results. If this algorithm is being used to hash passwords, then consider using a strong computationally-hard algorithm such as PBKDF2 or bcrypt instead of a plain hashing algorithm.

References: [CWE](http://cwe.mitre.org/data/definitions/327.html)

**Comment by rvagg** [comment]
please take it up with https://github.com/nodejs/gyp-next (or get a more intelligent code scanning tool)
