### ISSUE TITLE
Failed to build the application in windows...!

### ISSUE THREAD

**Issue by Surekha95** [nodejs/node-gyp#2467]
While building with the command **node-gyp build**  I'm getting issue as fatal error C1083: Cannot open include file: 'sys/ipc.h': No such file or directory. Is there any configuration required to get this file. And even in the code v8.h, node.h, sys/shm.h files are showing as not found. Please check the attached image for further reference.
![Node js Issue](https://user-images.githubusercontent.com/24824197/127303118-8142db86-45cf-41d8-abf0-ed41ef4c137f.PNG)

**Comment by alfredbaudisch** [comment]
- Download Build Tools 2017: https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15
- Install only the checked component and pay attention to the path
![image](https://user-images.githubusercontent.com/248383/130095070-e03bf08f-a4b9-4773-a876-87f76f51db94.png)

Then:
```
npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"
npm config set python "C:\Python27\python2.exe"
npm config set msvs_version 2017
```

Then finally try `npm install` again.

(Set the python to whichever is your path)

**Comment by cclauss** [comment]
> npm config set python "C:\Python27\python2.exe"

Python 2 died 592 days ago so it is ___not___ supported by node-gyp.

**Comment by alfredbaudisch** [comment]
@cclauss but after hours of fighting with trying to build this in Windows, it worked with this exact params. I mixed and match every possible Build Tools and Python combination. Only Python 2.7 + MSBuild 2017 worked (under Windows 10 Pro).

And it's ok if it's not supported, the Windows env is just my dev env, I just needed to be able to make node-gyp to build :)

**Comment by cclauss** [comment]
Yes because you are using node-gyp v3 instead of v8.

**Comment by alfredbaudisch** [comment]
> Yes because you are using node-gyp v3 instead of v8.

Makes sense. It's @phoenixframework/phoenix that requires node-sass, which in turn uses node-gyp v3.

**Comment by cclauss** [comment]
https://sass-lang.com/blog/libsass-is-deprecated
