### ISSUE TITLE
Problem install on windows

### ISSUE THREAD

**Issue by starcevpro** [nodejs/node-gyp#2469]
Hi there, i get error with installing electron-vibrancy.

<details>
  <summary>Error</summary>
  
PS C:\Users\e\projects\qlaunch> yarn add electron-vibrancy
yarn add v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > custom-electron-titlebar@3.2.7" has incorrect peer dependency "electron@^10.0.0 || ^11.0.0 || ^12.0.0".
warning " > frameless-titlebar@2.1.4" has unmet peer dependency "react@^16.9.0".
warning " > vuex@4.0.2" has unmet peer dependency "vue@^3.0.2".
warning " > @babel/eslint-parser@7.14.7" has unmet peer dependency "@babel/core@>=7.11.0".
warning " > eslint-webpack-plugin@2.5.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
[4/4] ⠐ electron
[-/4] ⠐ waiting...
[3/4] ⠐ electron-vibrancy
error C:\Users\e\projects\qlaunch\node_modules\electron-vibrancy: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\e\projects\qlaunch\node_modules\electron-vibrancy
Output:
C:\Users\e\projects\qlaunch\node_modules\electron-vibrancy>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.3 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\e\\projects\\qlaunch\\node_modules\\electron-vibrancy\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\e\\AppData\\Local\\node-gyp\\Cache\\14.17.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\e\\AppData\\Local\\node-gyp\\Cache\\14.17.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\e\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\e\\projects\\qlaunch\\node_modules\\electron-vibrancy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\e\\projects\\qlaunch\\node_modules\\electron-vibrancy\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
���ઠ �஥�⮢ � �⮬ �襭�� �� ������. �⮡� ������� ��ࠫ������ ᡮ��, ������� ��ࠬ��� "/m".
C:\Users\e\projects\qlaunch\node_modules\electron-vibrancy\build\Vibrancy.vcxproj(20,3): error MSB4019: ������஢���� �஥�� "C:\Microsoft.Cpp.Default.props" �� �����㦥�. �஢���� ���� � ������� <Import> � ����稥 䠩�� �� ��᪥.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\e\projects\qlaunch\node_modules\electron-vibrancy
gyp ERR! node -v v14.17.3
</details>

Steps to reproduce:

1.  Remove and install VS Build tools (via vs app)
2. Change BT version 2017 to 2015

My versions

- electron-vibrancy - latest
- yarn - 1.22.10
- npm - 6.14.13
- node - 14.17.3
- MSBuild - 15/17
- Windows 10
- Windows Terminal

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@5.1.0

vs. node-gyp@8.1.0 https://github.com/nodejs/node-gyp/releases

https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md
