### ISSUE TITLE
Failed to install on Arch

### ISSUE THREAD

**Issue by eulertour** [nodejs/node-gyp#2478]
* **Node Version**:  v16.5.0 and 7.17.0, respectively
* **Platform**:  `Linux eulerbrick 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`
* **Compiler**: 
```
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (GCC)
```
* **Module**:  node-gyp
__Verbose output (from npm or node-gyp):__
After running `npm install node-gyp`: https://pastebin.com/jxz9Cm1y

I noticed that the version in the error message is v7.1.2 instead of the latest (v8.1.0), but I haven't been able to install with the latest version even if I explicitly specify `npm installl node-gyp@8.1.0`. I also followed the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md to no avail.

**Comment by rvagg** [comment]
this is a C++ compile/dependency issue that you should take up with https://github.com/stackgl/headless-gl, likely they need to add some flags or get you to install a `*-dev` package to make it compile
