### ISSUE TITLE
Action defined in binding.gyp results misconfigured file path in generated vcxproj file after v4.0.0

### ISSUE THREAD

**Issue by lkallas** [nodejs/node-gyp#2485]
* **Node Version**:  v14.17.4
* **Platform**: 
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
System Type:               x64-based PC
```
* **Compiler**:  Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
* **Module**:  [node-rdkafka](https://github.com/Blizzard/node-rdkafka)

Correct file path generation for Windows `vcxproj` build files is broken.

Tiny repository for reproducing the bug provided with bug description & workaround can be found [here](https://github.com/lkallas/hello-world-node-addon#file-path-bug-version--400).

<details><summary>Verbose output (from node-gyp rebuild):</summary>

```
error C:\sixfold\code\sixfold-tour-status-service\node_modules\node-rdkafka: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\sixfold\code\sixfold-tour-status-service\node_modules\node-rdkafka
Output:
C:\sixfold\code\sixfold-tour-status-service\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (no
de "C:\Users\Lennar\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.17.4 | win32 | x64
gyp info find Python using Python version 3.8.2 found at "C:\Python38\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Lennar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\sixfold\\code\\sixfold-tour-status-service\\node_modules\\node-rdkafka\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Lennar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Lennar\\AppData\\Local\\node-gyp\\Cache\\14.17.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Lennar\\AppData\\Local\\node-gyp\\Cache\\14.17.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Lennar\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Lennar\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.4\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\sixfold\\code\\sixfold-tour-status-service\\node_modules\\node-rdkafka',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\sixfold\\code\\sixfold-tour-status-service\\node_modules\\node-rdkafka\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Getting librdkafka from nuget
  python: can't open file 'deps/windows-install.py': [Errno 2] No such file or directory
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 2. [C:\sixfold\code\sixfold-tour-status-service\node_modules\node-rdkafka\build\node-librdkafka.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Lennar\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lennar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\sixfold\code\sixfold-tour-status-service\node_modules\node-rdkafka
gyp ERR! node -v v14.17.4
gyp ERR! node-gyp -v v8.1.0
```

</details>

**Comment by cclauss** [comment]
@edenhill Do you have advise on this issue?

**Comment by edenhill** [comment]
Sorry, no idea. Never used node-gyp.

**Comment by rvagg** [comment]
https://github.com/Blizzard/node-rdkafka/blob/57d6fd7f154f197d4d83c6044e1eac706045c5f9/binding.gyp#L35

That path is coming out of node-rdkafka's binding.gyp, have you taken it up with them? It might be something they've seen before.

**Comment by lkallas** [comment]
> https://github.com/Blizzard/node-rdkafka/blob/57d6fd7f154f197d4d83c6044e1eac706045c5f9/binding.gyp#L35
> 
> That path is coming out of node-rdkafka's binding.gyp, have you taken it up with them? It might be something they've seen before.

@rvagg No that is not the issue. The issue is that the `vcxproj` file that is generated by `node-gyp` that has version greater than 4.0.0 is generating wrong file path so the MSBuild will fail with file not found error.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/releases/tag/v4.0.0 Was a long time ago and had tons of changes.  Can you please provide both the wrong and the right filepaths?

**Comment by lkallas** [comment]
> https://github.com/nodejs/node-gyp/releases/tag/v4.0.0 Was a long time ago and had tons of changes. Can you please provide both the wrong and the right filepaths?

@cclauss 

Here you go

File generated: `\build\node-librdkafka.vcxproj`

The command with **invalid** path generated:
```
<Command>call call python &quot;deps/windows-install.py&quot;&#xD;&#xA;if %errorlevel% neq 0 exit /b %errorlevel%</Command>
```

Correct should be

```
<Command>call call python &quot;..\deps\windows-install.py&quot;&#xD;&#xA;if %errorlevel% neq 0 exit /b %errorlevel%</Command>
````

**Comment by lkallas** [comment]
@cclauss 

Found the lines where the difference comes in between v4.0.0 and v8.1.0. It's the `gyp-next` which is used in `node-gyp` that needs fixing.

Here's the [code ](https://github.com/nodejs/node-gyp/blob/v4.0.0/gyp/pylib/gyp/generator/msvs.py#L367-L368)that creates correct path in v4.0.0

```python
    arguments = [i if (i[:1] in "/-") else _FixPath(i) for i in cmd[1:]]
    arguments = [i.replace('$(InputDir)', '%INPUTDIR%') for i in arguments]
```

And [here ](https://github.com/nodejs/node-gyp/blob/v8.1.0/gyp/pylib/gyp/generator/msvs.py#L421)is the latest:

```python
        arguments = [i.replace("$(InputDir)", "%INPUTDIR%") for i in cmd[1:]]
```

I'll leave it to you to decide the correct way to fix it. Thank you!

**Comment by cclauss** [comment]
@targos Can you please weigh in on the change at https://github.com/nodejs/gyp-next/commit/fc22f8335e2016da4aae4f4233074bd651d2faea ?  I am not a Windows guy so I cannot really make sense of this.

**Comment by lkallas** [comment]
If fixing the path in `gyp-next` does not make sense, then the workaround is to make the path absolute using `<(module_root_dir)`:

```
'inputs': [
  '<(module_root_dir)/deps/hello-world.py'
]
```

But that needs at least some documentation update.

**Comment by cclauss** [comment]
Related to #2399 ?

**Comment by lkallas** [comment]
> Related to #2399 ?

Looks like the same issue.

**Comment by targos** [comment]
> @targos Can you please weigh in on the change at [nodejs/gyp-next@fc22f83](https://github.com/nodejs/gyp-next/commit/fc22f8335e2016da4aae4f4233074bd651d2faea) ?
> I am not a Windows guy so I cannot really make sense of this.

That change was made so that the paths in commands do not have backslashes (because that would break building V8 for Node.js). Refs: https://github.com/nodejs/gyp-next/pull/84#issuecomment-735393334
Windows generally supports forward slashes, so it seemed okay to do, but I didn't realize that `_FixPath` used a global prefix variable too.
I suppose we could partially revert my change and add a parameter to `_FixPath` to disable the backslash conversion part?
