### ISSUE TITLE
disable flake8 test for this repo

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-gyp#2487]
Should we add this rule in https://github.com/nodejs/gyp-next ?

Also should we disable flake8 test for this repo since gyp sources is an upstream project ?

@cclauss @rvagg

_Originally posted by @gengjiawen in https://github.com/nodejs/node-gyp/pull/2481#discussion_r692781091_

**Comment by cclauss** [comment]
Better safe than sorry.  How long does a flake8 run take?  If the run takes less than 5 minutes then I see no reason to eliminate it.

**Comment by gengjiawen** [comment]
> Better safe than sorry. How long does a flake8 run take? If the run takes less than 5 minutes then I see no reason to eliminate it.

The issue now is that rules on both side are not consistent. Works fine on `gyp-next` and breaks on this repo. 

We may need to align the rules in the long run.

**Comment by cclauss** [comment]
Put the rules in `setup.cfg` and copy that file when we copy the Python code.
