### ISSUE TITLE
The generated config.gypi file should inherit from $nodedir/config.gypi instead of process.config

### ISSUE THREAD

**Issue by zcbenz** [nodejs/node-gyp#2490]
Currently the `variables` field of the generated `config.gypi` file inherits from `process.config`:

https://github.com/nodejs/node-gyp/blob/5f1a06c50f3b0c3d292f64948f85a004cfcc5c87/lib/configure.js#L101-L103

And the `target_defaults` field does inherit from `process.config` for the reason that the build configurations of the running `node` executable may be different from the target being compiled for:
https://github.com/nodejs/node-gyp/blob/5f1a06c50f3b0c3d292f64948f85a004cfcc5c87/lib/configure.js#L115-L122

However the `variables` field also belongs to build configurations of Node.js, and should be treated the same with `target_defaults`, for example Node.js executable compiled with `v8_enable_pointer_compression=1` can not load modules compiled with `v8_enable_pointer_compression=0`.

This has been causing problems when compiling modules for Electron, because node-gyp is using `process.config.variables` of the running `node` executable for compilation, which are different from the build configurations of Electron.

So the generated `config.gypi` file should not inherit from `process.config` at all, and it should inherit from the `$nodedir/include/node/config.gypi` file instead, which is the actual build configuration of the target.

I can start working out a pull request if the above suggested solution sounds good to the maintainers.

/cc @rvagg

**Comment by rvagg** [comment]
@zcbenz I'm inclined to trust you on this and say go ahead and submit a PR and we'll see if we can figure out what the blast radius of such a change might be. Maybe it's just a semver-major to be safe if we can't find evidence of a major impact.

Any input from other @nodejs/gyp heads would be good head (tbh my mental bandwidth on this is a bit limited at the moment).
