### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-gyp#2495]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

The only references I see in the repo to master (other than in links to licence files which should redirect on their own) are:

.github/workflows/release-please.yml
/README.md  (buld status branch)

There two would required an update to change master -> main at the same time.

Opening this issue to see what the best way to get the update done. I can rename the branch/update those two files but might better if somebody active in the project does it or we did it together.

**Comment by NiceneNerd** [comment]
Gross

**Comment by mhdawson** [comment]
@rvagg do you think there is anything else in addition to the two things I've mentioned that would need to be updated. If not would you be ok with me doing those?

**Comment by rvagg** [comment]
not sure if there's more than that, there's a CI job or two for node-gyp, maybe a default value could be changed in there too

**Comment by mhdawson** [comment]
We are down to 6 repos that need the rename and this is one of them.

Are there any objections to be renaming and updating the defaults in
https://ci.nodejs.org/job/nodegyp-test-commit
https://ci.nodejs.org/job/nodegyp-test-commit-arm64/configure

**Comment by mhdawson** [comment]
@nodejs/node-gyp we plan to do the rename for nodejs/node on June 15 at which point this would be the only repo that has not been renamed.   Any objections if we rename and do the changes discussed in the previous comments at the same time?  If so please let me know before June 15.

**Comment by mhdawson** [comment]
There were no objections and we've just done the nodejs/node repo so doing here as well.

**Comment by mhdawson** [comment]
* Branch renamed,
* [release-please.yml](https://github.com/nodejs/node-gyp/blob/main/.github/workflows/release-please.yml) updated to use main 
* CI jobs in Node.js CI updated to ref main
