### ISSUE TITLE
Use prebuilt binaries instead of building them.  It is too hard to understand node-gyp's errors

### ISSUE THREAD

**Issue by oscarcoding** [nodejs/node-gyp#2502]
You guys MUST supply an option to use prebuilt native code. This module node-gyp is ridiculously hard to use if there is even the slightest error.

For example the level of skill required to add a npm module to a project is very low. Any one can do it:

`yarn add some-module`

BUT as soon as that module throws an error in node-gyp, it becomes impossible for anyone except an expert in node-gyp to fix it.  Very few people can do this.  I can't.  The manner in which your module fails makes it too hard for the average person to solve the problem.

You have taken something available to everyone, and made it way too hard to use.  Why cant you just download a prebuilt native module? Our server is on linux, so just download the linux binaries.  Our dev is on Mac so just download the Mac binaries.

**You are preventing people from using modules that should be very easy to use.**

I'm only trying to install `yarn add xlsx` but I instead get tons of errors in many different modules, which are completely incomprehensible:

```
#10 241.3 gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[...removed a huge number of lines...]
#10 241.3 __attribute__((deprecated(message))) declarator
#10 241.3 ^~~~~~~~~~
#10 241.3 protagonist.target.mk:157: recipe for target 'Release/obj.target/protagonist/src/parse_async.o' failed
#10 241.3 make: Leaving directory '/tmp/node_modules/protagonist/build'
#10 241.3 make: *** [Release/obj.target/protagonist/src/parse_async.o] Error 1
#10 241.3 gyp ERR! build error
#10 241.3 gyp ERR! stack Error: `make` failed with exit code: 2
```

Again, why cant you just simply download prebuilt binaries for the current OS?  Having to solving these build issues are above most peoples ability levels.

**Comment by rvagg** [comment]
Questions regarding hosting, authentication, ABI matching, etc. are pretty complex. To date, we've decided to defer these issues to the ecosystem and there are a number of projects which support this, including https://github.com/prebuild/prebuild-install and https://github.com/mapbox/node-pre-gyp which are very simple to insert in to a package's `"install"` such that the author has full control over where the binaries can be fetched from if they are available, with a simple fall-back to build with node-gyp. So, for now, node-gyp has a very limited responsibility here of _building_ the addons. Concerns beyond that are best left to other pieces of tooling in the install toolchain. If there are additional ways for node-gyp to support that then we've always been open to helping, and have done in the past.

If your favourite addon doesn't have prebuilds, then you can either encourage them to add them or even help them add support as I'm sure that would be appreciated.
