### ISSUE TITLE
Python Executable Syntax Error

### ISSUE THREAD

**Issue by blpraveen** [nodejs/node-gyp#2506]
I could not install CoreUI Template

Because of this error I have installed python 3.8

but it gives me syntax errror

![134974720-490eee78-0576-4146-ad4e-fca1698d2b92](https://user-images.githubusercontent.com/3274289/134987592-6433bb6e-18ba-45b8-b12c-baa0e41796b5.png)

**Comment by cclauss** [comment]
The answer to your problem was in the text that you deleted above.
