### ISSUE TITLE
On Windows, arguments passed to the "action" command are still transformed to replace slashes with backslashes

### ISSUE THREAD

**Issue by somanuell** [nodejs/node-gyp#2507]
node v14.17.6
npm 6.14.15
node-gyp 8.2.0
cmake 3.21.3
Python 3.9.7
Windows 10 and VS 2019

In the folowing action command:
`'action': [ 'cd <(module_root_dir)/deps/cpu_features/build && cmake -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /Ob2 /DNDEBUG" -DCMAKE_BUILD_TYPE=Release -DBUILD_PIC=ON -A <(cmake_arch) ..' ],`
the 4 slashes are still replaced with backslash.

See https://github.com/mscdex/cpu-features/issues/3 for context.

Maybe it's not `node-gyp` that does the replacement. If so, sorry for the false issue, but could you hint me on how to pass slash to cmake in that case?

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
