### ISSUE TITLE
Node-gyp on Debian 11 x64 

### ISSUE THREAD

**Issue by Navid61** [nodejs/node-gyp#2508]
I've the same problem and I don't know how I can fix that?
My OS is Debian 11 x64 + GUI is Cinammon 5
node version:16.10.0
yarn version: 1.22.5
npm version: 7.24.0

make: Leaving directory '/home/sigma/panel/node_modules/react-app-rewire-sass-rule/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sigma/panel/node_modules/react-app-rewire-sass-rule/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.10.0-8-amd64
gyp ERR! command "/usr/bin/node" "/home/sigma/panel/node_modules/react-app-rewire-sass-rule/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/sigma/panel/node_modules/react-app-rewire-sass-rule/node_modules/node-sass
gyp ERR! node -v v16.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

_Originally posted by @Navid61 in https://github.com/nodejs/node-gyp/issues/2453#issuecomment-928781087_

**Comment by cclauss** [comment]
Please do not delete the issue text and then put in a line like
> gyp ERR! node-gyp -v v3.8.0

when the current release of this code is v8.2.0. https://github.com/nodejs/node-gyp/releases
