### ISSUE TITLE
Missing SHASUMS256.txt in uploaded version 14.17.6

### ISSUE THREAD

**Issue by abrahamb4b** [nodejs/node-gyp#2509]
node gyp build is currently failing because the recently uploaded version of node is generating a 404 for the file at https://nodejs.org/download/release/v14.18.0/SHASUMS256.txt

**Comment by tomquist** [comment]
I've the same problem but for the headers [node-v14.18.0-headers.tar.gz](https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz):
https://github.com/nodejs/node/issues/40309

**Comment by richardlau** [comment]
I queued a cdn purge and the link appears to be working for me now. Please could you try again?

**Comment by rvagg** [comment]
resolved and an explanation posted @ https://github.com/nodejs/node/issues/40309#issuecomment-934030197
sorry for the inconvenience
