### ISSUE TITLE
Feature Requests: MSVC discovery as separate module, method for retrieving compiler to be used by node-gyp

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-gyp#2526]
As the title says, I have a couple of "feature requests":

1. Can the MSVC discovery module be made available separately on npm?

2. Could we have some way of querying node-gyp (perhaps programmatically?) for the compiler it's going to use to compile a node addon? I'm mainly thinking detecting the compiler from say an npm package install/preinstall script. That way any `msvs_version` and other settings would have already been accounted for.

The use case for this is I am writing a tool to do autoconf-style checks, so the first "feature request" would help for determining a default compiler and the second request would help specifically when said tool is specifically used within the context of node addons so that the checks are done using the same compiler that will be used to eventually compile the addon.

**Comment by richardlau** [comment]
FWIW It hasn't been updated in years, but msvc discovery was the intent of https://github.com/node4good/windows-autoconf.
