### ISSUE TITLE
Can't resolve node-gyp error on mac, version 11.6 - Followed your mac docs, can't resolve! 

### ISSUE THREAD

**Issue by GhostCrawl3r** [nodejs/node-gyp#2530]
Hi, 

I keep getting this error @ work when I yarn install:

```                                              ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nickmorgan/WebstormProjects/MX Digital - Corporate Website/Frontend/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/opt/homebrew/Cellar/node/16.11.1/bin/node" "/Users/nickmorgan/WebstormProjects/MX Digital - Corporate Website/Frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/nickmorgan/WebstormProjects/MX Digital - Corporate Website/Frontend/node_modules/node-sass
gyp ERR! node -v v16.11.1
```

How do I resolve this? I've done the following:
- Deleted node_modules/yarn.lock and reinstalled
- Followed the node-gyp docs: https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md
- Re installed xcode and xcode select
- upgraded xcode and xcode select
- downgraded them to a lower version
- upgraded python to latest
- downgraded python to lower packages
- restarted my pc
- downgraded my mac version and upgraded
- reinstalled node/npm 
- upgraded/downgraded node/npm
- cleared terminal/node_module/npm/yarn cache
- read over 100 articles on stack, followed and nothing..

**Comment by gtupak** [comment]
I have the same problem on Mac OS Monterey

**Comment by cclauss** [comment]
> gyp ERR! node -v v16.11.1

The _very next line_ tells us what version of `node-gyp` was running.  This is important data for diagnosing problems.

[`Node Saas` is deprecated](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22+) so we can no longer provide support for it here.

**Comment by cclauss** [comment]
Does `npm install node-sass@latest` solve this for you?

**Comment by gtupak** [comment]
> I have the same problem on Mac OS Monterey

Update: I had an issue with a package, finally (`node-sass`); so it wasn't related to node-gyp.

**Comment by GhostCrawl3r** [comment]
I managed to fix this by updating node-saas to ^6

Kind Regards,

Nick Morgan
Co-Founder
Interstellar Digital LTD
Company Number: 12694832
***@***.***
This e-mail and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by jaydipjpinfotech** [comment]
> > I have the same problem on Mac OS Monterey
> 
> Update: I had an issue with a package, finally (`node-sass`); so it wasn't related to node-gyp.

hii is this worked for. you ?
could you help me with it please

**Comment by cclauss** [comment]
@jaydipjpinfotech This issue is closed so please open a new issue and provide the command typed and the full error log.

**Comment by TheMostCreative** [comment]
For me helped installing version of node 16 or 14 using nvm
then I received error about mozjpeg. Installed it via homebrew
But then the next command helped me.
`ln -s /opt/homebrew/opt/mozjpeg /usr/local/opt/mozjpeg`
Maybe also possible option to use 
`npm install -g mozjpeg`
After that it's possible to change to any version of node.
