### ISSUE TITLE
Version 8 Lowest supported Python 3 should be 3.5 (instead of 3.6)

### ISSUE THREAD

**Issue by ronilan** [nodejs/node-gyp#2540]
## Overview
Node-Gyp version 8 requires [Python 3.6 and above](https://github.com/nodejs/node-gyp#on-unix).
That was introduced when [support for Python 2 was dropped](https://github.com/nodejs/node-gyp/pull/2333).

Debian 9 (Stretch) comes with [Python 3.5](https://packages.debian.org/stretch/python3).
It is in [LTS mode until the end of June 2022](https://www.debian.org/releases/stretch/).

## Problem 
[NPM upgraded to Version 8](https://github.com/npm/run-script/pull/39) of node-gyp, and support for Debian 9 was inadvertently dropped as a result.

See full bug description here: https://github.com/npm/run-script/issues/40

## Solution

To allow NPM to use version 8 of node-gyp - set lowest required version of Python to 3.5 instead of 3.6.

**Comment by cclauss** [comment]
Not going to happen.  We try to keep a secure platform.  https://devguide.python.org/devcycle/#end-of-life-branches

Python 3.6 and above supports both type hint (help us find bugs) and f-strings ([accelerate string manipulation](https://www.scivision.dev/python-f-string-speed/)).
