### ISSUE TITLE
Feature request: include VC version in config.gypi on Windows

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-gyp#2541]
It'd be nice to have the VC version (not the VS version) included in config.gypi, so that we can easily tell what compiler was used to build the project.

The use case for this is I want to be able to prebuild node addons that include the VC version used so that I can check at install time that a compatible VC runtime is installed and that the prebuilt addon will be usable.

**Comment by StefanStojanovic** [comment]
This issue has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
