### ISSUE TITLE
ffi-napi@4.0.3 install: `node-gyp-build`

### ISSUE THREAD

**Issue by tangyoulintylgit** [nodejs/node-gyp#2549]
D:\workspace\WebstormProjects\WP400>npm install

> ref-napi@3.0.3 install D:\workspace\WebstormProjects\WP400\node_modules\ref-napi
> node-gyp-build

> @serialport/bindings@9.2.5 install D:\workspace\WebstormProjects\WP400\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=x64 libc= platform=win32)

D:\workspace\WebstormProjects\WP400\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "D:\workspace\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bi
n\node-gyp.js" rebuild )  else (node "D:\workspace\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
    正在创建库 D:\workspace\WebstormProjects\WP400\node_modules\@serialport\bindings\build\Release\bindings.lib 和对象 D:\workspace\WebstormProjects\WP400\node_modules\@serialport\bindings\build\Release\bindings.exp
  bindings.vcxproj -> D:\workspace\WebstormProjects\WP400\node_modules\@serialport\bindings\build\Release\\bindings.node

> bufferutil@4.0.5 install D:\workspace\WebstormProjects\WP400\node_modules\bufferutil
> node-gyp-build

> ffi-napi@4.0.3 install D:\workspace\WebstormProjects\WP400\node_modules\ffi-napi
> node-gyp-build

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\workspace\\WebstormProjects\\WP400\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\workspace\WebstormProjects\WP400\node_modules\ffi-napi
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN wp400@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ffi-napi@4.0.3 install: `node-gyp-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ffi-napi@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Taney\AppData\Roaming\npm-cache\_logs\2021-11-11T07_40_37_875Z-debug.log

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

https://github.com/nodejs/node-gyp/releases --> __v8.4.0__
* https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md
