### ISSUE TITLE
No VS Installation found - windows 10

### ISSUE THREAD

**Issue by humanfriend22** [nodejs/node-gyp#2555]
I have tried every solution on this issue, but I am getting the same error. Can someone help me?

The original issue is locked and so I am continuing it here.

As a reply for cclauss, the version shows 8.2.0

_Originally posted by @humanfriend22 in https://github.com/nodejs/node-gyp/issues/2203#issuecomment-971023244_

**Comment by cclauss** [comment]
The current release of this project is v8.4.1. https://github.com/nodejs/node-gyp/releases

Is 8.20.0 above a typo?

If your error log does not say `gyp info using node-gyp@v8.4.1` then please upgrade using the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md and retry your command.

If you are running the current version then please provide:
* The command you typed
* The full error log

**Comment by humanfriend22** [comment]
My bad, I fixed the typo. I will get back to you tomorrow. Thank you for your help!

**Comment by humanfriend22** [comment]
I have updated node-gyp and just running node-gyp as a command in Command prompt tells me that my installed node-gyp version is 8.4.1.

However, when I try to install any package that requires node-gyp, it says it is using version 8.2.0.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by humanfriend22** [comment]
I have read the whole instruction and followed them. Installing packages still show 8.2.0.

**Comment by ingtellect** [comment]
I am having this issue, too while installing sqlite3.
I use windows 10 and installed visual studio community 2022. 
I also tried the dev powershell from vs 2022 as stated in [the comment of the original post](https://github.com/nodejs/node-gyp/issues/2203#issuecomment-978429819) but no luck.

**Comment by humanfriend22** [comment]
I have also installed Visual Studio 2022 and previous versions. I am trying to install ```mmmagic``` and ```robotjs```.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/docs/Common-issues.md

**Comment by ingtellect** [comment]
> 

Tried this but got another error
`C:\Users\ingtellect\Documents\repo\NOL\next-auth-example>npm install
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 1
npm ERR! path C:\Users\ingtellect\Documents\repo\NOL\next-auth-example\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! �� �ַ���� ������Ʈ�� �� ���� �ϳ��� �����մϴ�. ���� ���带 ����Ϸ��� "-m" ����ġ�� �߰��ϼ���.
npm ERR!   nothing.c
npm ERR!   win_delay_load_hook.cc
npm ERR!   nothing.vcxproj -> C:\Users\ingtellect\Documents\repo\NOL\next-auth-example\node_modules\sqlite3\build\Release\\nothing.lib
npm ERR!   unpack_sqlite_dep
npm ERR!   Python
npm ERR! C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for '..\..\deps\sqlite-autoconf-3360000.tar.gz' exited with code 9009. [C:\Users\ingtellect\Documents\repo\NOL\next-auth-example\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.0 found at "C:\Users\ingtellect\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.31911.196) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\ingtellect\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\ingtellect\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ingtellect\\Documents\\repo\\NOL\\next-auth-example\\node_modules\\sqlite3\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ingtellect\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ingtellect\\AppData\\Local\\node-gyp\\Cache\\16.13.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ingtellect\\AppData\\Local\\node-gyp\\Cache\\16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ingtellect\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ingtellect\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ingtellect\\Documents\\repo\\NOL\\next-auth-example\\node_modules\\sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\ingtellect\\Documents\\repo\\NOL\\next-auth-example\\node_modules\\sqlite3\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\ingtellect\AppData\Roaming\nvm\v16.13.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ingtellect\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\ingtellect\Documents\repo\NOL\next-auth-example\node_modules\sqlite3
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok`

**Comment by StefanStojanovic** [comment]
This issue has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
