### ISSUE TITLE
Dependency Error Through node-sass

### ISSUE THREAD

**Issue by RyFive85** [nodejs/node-gyp#2566]
We're suddenly getting the following error in our CI/CD pipeline when trying to run the **_npm install_** command.  This has been working fine up until last week.  The full stack of our error is much longer, but it just seems to be a lot of **_error gyp info spawn args_** errors.

13574 error gyp verb node dev dir C:\Users\VssAdministrator\.node-gyp\16.13.0
13574 error gyp verb found first Solution file build/binding.sln
13574 error gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
13574 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
13574 error gyp info spawn args [
13574 error gyp info spawn args   'build/binding.sln',
13574 error gyp info spawn args   '/nologo',
13574 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
13574 error gyp info spawn args ]
13574 error gyp ERR! UNCAUGHT EXCEPTION
13574 error gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
13574 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
13574 error gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
13574 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
13574 error gyp ERR! System Windows_NT 10.0.17763
13574 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\a\\1\\s\\HoneyBee\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
13574 error gyp ERR! cwd D:\a\1\s\HoneyBee\node_modules\node-sass
13574 error gyp ERR! node -v v16.13.0
13574 error gyp ERR! node-gyp -v v3.8.0
13574 error gyp ERR! This is a bug in `node-gyp`.
13574 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
13574 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
13574 error Build failed with error code: 7
13575 verbose exit 1

We do not have node-gyp installed a direct dependency; it's a dependency of node-sass 4.14.1.  So I don't think it's as easy as installing the update to version 3.8.1 of node-gyp.

**Comment by cclauss** [comment]
Try `npm install --global node-sass@latest` but [node-sass is deprecated](https://github.com/sass/node-sass#node-sass) so we [cannot help much](https://github.com/nodejs/node-gyp/issues?q=is%3Aissue+label%3A%22Node+Sass+--%3E+Dart+Sass%22+) here.

> error gyp ERR! node-gyp -v v3.8.0 

Does not align with v8.4.1.  https://github.com/nodejs/node-gyp/releases

Please update: https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/tree/master/docs#node-sass-is-deprecated
