### ISSUE TITLE
node-gyp fails at npm i

### ISSUE THREAD

**Issue by javiercoh** [nodejs/node-gyp#2572]
node : 14.17.5
npm : 8.3.0

```
npm ERR! code 1
npm ERR! path C:\suplai-asistente\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\suplai-asistente\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\suplai-asistente\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.17.5 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Users\Lenovo\.windows-build-tools\python27" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Users\Lenovo\.windows-build-tools\python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\suplai-asistente\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\suplai-asistente\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\suplai-asistente\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! gyp verb `which` failed  C:\Users\Lenovo\.windows-build-tools\python27 Error: not found: C:\Users\Lenovo\.windows-build-tools\python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\suplai-asistente\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\suplai-asistente\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\suplai-asistente\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:\Users\Lenovo\.windows-build-tools\python27". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Users\\Lenovo\\.windows-build-tools\\python27\\python.exe"
npm ERR! gyp verb check python version `C:\Users\Lenovo\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 14.17.5
npm ERR! gyp verb command install [ '14.17.5' ]
npm ERR! gyp verb install input version string "14.17.5"
npm ERR! gyp verb install installing version: 14.17.5
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 14.17.5
npm ERR! gyp verb build dir attempting to create "build" dir: C:\suplai-asistente\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\suplai-asistente\node_modules\node-sass\build
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files\Microsoft Visual Studio\2022\Community
npm ERR! gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
npm ERR! gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
npm ERR! gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
npm ERR! gyp verb find vs2017   - Some required components are missing, not using this installation
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
npm ERR! gyp verb find vs2017   - Using this installation with Windows 10 SDK
npm ERR! gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\suplai-asistente\node_modules\node-sass\build\config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: C:\suplai-asistente\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\suplai-asistente\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Users\Lenovo\.windows-build-tools\python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Lenovo\\.node-gyp\\14.17.5\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Lenovo\\.node-gyp\\14.17.5',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Lenovo\\.node-gyp\\14.17.5\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\suplai-asistente\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\Lenovo\.node-gyp\14.17.5
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\suplai-asistente\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\suplai-asistente\node_modules\node-sass
npm ERR! gyp ERR! node -v v14.17.5
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

Usage: npm i --force --verbose

```

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0

https://github.com/nodejs/node-gyp/blob/master/docs/README.md

**Comment by javiercoh** [comment]
> > npm ERR! gyp info using node-gyp@3.8.0
> 
> https://github.com/nodejs/node-gyp/blob/master/docs/README.md

Thank you very much for pointing that out. I have been following the instructions with no success though; node-gyp version still set at 3.8.0 after updating

By looking at the last modification date, I confirmed that the global directory for node-gyp was `\users\Lenovo\appdata\roaming\npm\node_modules\node-gyp` so I proceeded as follows:

´´´
npm i -g node-gyp@latest
for /f "delims=" %P in ('npm prefix -g') do npm config set node_gyp "%P\users\Lenovo\appdata\roaming\npm\node_modules\node-gyp\bin\node-gyp.js"
npm config set msvs_version 2019
´´´

Must be doing something silly here but cannot figure it out... any idea?


´´´
npm ERR! code 1
npm ERR! path C:\suplai-asistente\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files (x86)\nodejs\node.exe C:\suplai-asistente\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\suplai-asistente\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.17.0 | win32 | ia32
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Users\Lenovo\.windows-build-tools\python27" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Users\Lenovo\.windows-build-tools\python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\suplai-asistente\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\suplai-asistente\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\suplai-asistente\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! gyp verb `which` failed  C:\Users\Lenovo\.windows-build-tools\python27 Error: not found: C:\Users\Lenovo\.windows-build-tools\python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\suplai-asistente\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\suplai-asistente\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\suplai-asistente\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\suplai-asistente\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:\Users\Lenovo\.windows-build-tools\python27". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Users\\Lenovo\\.windows-build-tools\\python27\\python.exe"
npm ERR! gyp verb check python version `C:\Users\Lenovo\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 14.17.0
npm ERR! gyp verb command install [ '14.17.0' ]
npm ERR! gyp verb install input version string "14.17.0"
npm ERR! gyp verb install installing version: 14.17.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 14.17.0
npm ERR! gyp verb build dir attempting to create "build" dir: C:\suplai-asistente\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\suplai-asistente\node_modules\node-sass\build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\suplai-asistente\node_modules\node-sass\build\config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: C:\suplai-asistente\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\suplai-asistente\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Users\Lenovo\.windows-build-tools\python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2019',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Lenovo\\.node-gyp\\14.17.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Lenovo\\.node-gyp\\14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\suplai-asistente\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Lenovo\\.node-gyp\\14.17.0\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\suplai-asistente\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\suplai-asistente\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
npm ERR!     generator_flags.get('msvs_version', 'auto'))
npm ERR!   File "C:\suplai-asistente\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
npm ERR!     versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
npm ERR! KeyError: '2019'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\suplai-asistente\node_modules\node-gyp\lib\configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\suplai-asistente\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\suplai-asistente\node_modules\node-sass
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-12-16T01_21_42_000Z-debug-0.log´´´

**Comment by javiercoh** [comment]
the above result was for an ionic 3 project. However ran `npm i` for an ionic 6 project and it did work.

> Must be doing something silly here but cannot figure it out... any idea? Also downgraded node to 14.17.0 and installed visual studio 2019 with desktop c++

Maybe I am using an unsupported node version...

**Comment by cclauss** [comment]
#2574

**Comment by pflajszer** [comment]
@javiercoh  I had the exact same problem and the linked fix didn't help.
What did help was forcing the usage of a specific node version (just replicated what I had on my machine):

YAML:
```yaml
steps:
- task: NodeTool@0
  displayName: 'Use Node 14.15.0'
  inputs:
    versionSpec: 14.15.0
```
Having said that, while `npm install` finishes successfully, the `node-gyp` version is still `3.6.2` and it still errors, but it doesn't prevent the pipeline to fail. 

I appreciate **this is not the full solution**, but it is enough for your use case, so I'm posting it here.

**Comment by javiercoh** [comment]
Thanks Pawel! i will try this out next week

**Comment by AlexByte** [comment]
just update module `gulp-sass` to the latest version, add `sass` module to the package.json and write `const sass = require('gulp-sass')(require('sass'));` to the gulpfile.js to get rid off node-gyp.

**Comment by am0wa** [comment]
Damn `node-sass` 

`node: 16.13.2`
`gyp: 8.4.1`

`path /Users/am/projects/pt/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /Users/am/projects/pt/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/am/projects/ptnode_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/Library/Developer/CommandLineTools/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.8.9"
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.2
npm ERR! gyp verb command install [ '16.13.2' ]
npm ERR! gyp verb install input version string "16.13.2"
npm ERR! gyp verb install installing version: 16.13.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version not already installed, continuing with install 16.13.2
npm ERR! gyp verb ensuring nodedir is created /Users/am/Library/Caches/node-gyp/16.13.2
npm ERR! gyp verb created nodedir /Users/am/Library/Caches/node-gyp/16.13.2
npm ERR! gyp http GET https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp verb command remove [ '16.13.2' ]
npm ERR! gyp verb remove using node-gyp dir: /Users/am/Library/Caches/node-gyp
npm ERR! gyp verb remove removing target version: 16.13.2
npm ERR! gyp verb remove removing development files for version: 16.13.2
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz failed, reason: connect ETIMEDOUT 104.20.23.46:443
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> 
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:402:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/am/projects/pt/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/am/projects/pt/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
`

**Comment by cclauss** [comment]
> Damn `node-sass`

Is deprecated as is `lib-sass`

**Comment by cclauss** [comment]
https://www.npmjs.com/package/node-sass <-- DEPRECATED!!!
* https://github.com/nodejs/node-gyp/tree/main/docs#node-sass-is-deprecated
