### ISSUE TITLE
[question]: Is there a timeline for dropping node10 support?

### ISSUE THREAD

**Issue by wraithgar** [nodejs/node-gyp#2599]
We are in the process of updating our support matrix for the npm cli and its dependencies.  One of these dependencies, [make-fetch-happen](https://github.com/npm/make-fetch-happen), just had its engines field updated to drop node10 support.  We'd like to help keep node-gyp up to date on that dependency but it still supports node `>= 10.12.0`.

Are there plans or is there a timeline for updating this field?

**Comment by cclauss** [comment]
https://nodejs.org/en/about/releases/

**Comment by wraithgar** [comment]
@cclauss that's the nodejs release cycle, nothing on there mentions node-gyp?  Does this mean it can drop node10 now and it was just overlooked?

**Comment by rvagg** [comment]
no plans, I think we can be flexible around npm's needs on this I think, and we should be able to bump it to at least 12.0.0 (unless you want to suggest a later release of 12?)

**Comment by MylesBorins** [comment]
Might I suggest this as the engines field

https://github.com/MylesBorins/node-osc/blob/main/package.json#L14

It scoped to versions to 12/14 that support the full esm implementation

**Comment by rvagg** [comment]
sgtm
