### ISSUE TITLE
Overriding default flags

### ISSUE THREAD

**Issue by tristanz** [nodejs/node-gyp#26]
This is likely a question born of ignorance, but is there a way to override the default flags in common.gypi?

I need to compile with RTTI enabled but node-gyp defaults to `-fno-rtti`.  This is required to compile against boost, for instance.

**Comment by ben-kirk** [comment]
I've tried all the things listed here and in https://github.com/nodejs/node-gyp/issues/857, but I still can't get RTTI enabled in my auto-generated MSVS 2015 project. Here is my binding.gyp below (Oh, I'm using nbind with Electron). I have all the methods I've tried listed in this file contents below, but I also tried them separately to no avail...

{
	'targets': [
		{
			'includes': [
				'auto.gypi'
			],
      'sources': [
        'addon.cc'
      ],
      'cflags_cc!': [
        '-fno-rtti'
      ],
      'conditions': 
      [
        [
          'OS=="mac"',
          {
            'xcode_settings': { 'GCC_ENABLE_CPP_RTTI': 'YES' }
          },
        ],
        [
          'OS=="win"',
          {                        
            'cflags': [
                '/GR',
              ],
            'configurations': {
              'Debug': {
                'msvs_settings': {
                  'VCCLCompilerTool': {
                    'RuntimeTypeInfo': 'true',
					'AdditionalOptions': ['/GR'], 
                  }
                }
              },
              'Release': {			                  
			    'msvs_settings': {
				  'VCCLCompilerTool': {
				    'RuntimeTypeInfo': 'true',
					'AdditionalOptions': ['/GR'],
				  }
				}
              }
            }
          }
        ]
      ],
      'defines': [
        '_WIN32_WINNT=0x0601'
      ],
      'include_dirs': [
        'C:/Program Files/boost/boost_1_62_0'
      ],        
      'link_settings': {
        'library_dirs': [
          'C:\\Program Files\\boost\\boost_1_62_0\\lib64-msvc-14.0'
        ]  
      }
		}
	],
  'includes': [
    'auto-top.gypi'
  ]
}

**Comment by KrishnaPG** [comment]
For the `/EHsc` issue, with VS Build Tools 2017 and node v12.9.1 the below worked in the bindings.gyp:
````
  "targets": [
    {
      "target_name": "addon",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "addon.cc" ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],

      'msvs_settings': {
          'VCCLCompilerTool': {
            'ExceptionHandling': '1',    
            'AdditionalOptions': ['/EHsc']
          }
      }

    }
````
Sharing here in case anyone facing the same problem: 
````
warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file
 ..\addon.cc) [..\build\addon.vcxproj]
````
