### ISSUE TITLE
Rebuild and Installation Issue. 

### ISSUE THREAD

**Issue by Marwan7035** [nodejs/node-gyp#2604]
Please look thru your error log for the string `gyp info using node-gyp@` and if the version number is less than the [current release of node-gyp](https://github.com/nodejs/node-gyp/releases) then __please upgrade__ using the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md and try your command again.

Requests for help with [`node-sass` are very common](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22). Please be aware that this package is deprecated, you should seek alternatives and avoid opening new issues about it here.

* **Node Version**:  3.10.10
* **Platform**: Windows 10
* **Compiler**:  Visual Studio/2017
* **Module**:  node-gyp & ffi 

<details><summary>Verbose output (from npm or node-gyp):</summary>

gyp ERR! stack async function getBaseConfigGypi ({ gyp, nodeDir }) {
gyp ERR! stack       ^^^^^^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token function
gyp ERR! stack     at createScript (vm.js:56:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:97:10)
gyp ERR! stack     at Module._compile (module.js:549:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:586:10)
gyp ERR! stack     at Module.load (module.js:494:32)
gyp ERR! stack     at tryModuleLoad (module.js:453:12)
gyp ERR! stack     at Function.Module._load (module.js:445:3)
gyp ERR! stack     at Module.require (module.js:504:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)
gyp ERR! System Windows_NT 10.0.19043```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
(...)
```

</details>

<!-- Any further details -->

**Comment by cclauss** [comment]
The important parts of the error log are missing.  Please provide the command typed and the ENTIRE error log.

**Comment by Marwan7035** [comment]
The command is: node-gyp rebuild. The error log is attached. Thank you for your time. 
C:\Users\marwan.alamoudi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@6.17.1 | win32 | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
gyp ERR! stack async function getBaseConfigGypi ({ gyp, nodeDir }) {
gyp ERR! stack       ^^^^^^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token function
gyp ERR! stack     at createScript (vm.js:56:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:97:10)
gyp ERR! stack     at Module._compile (module.js:549:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:586:10)
gyp ERR! stack     at Module.load (module.js:494:32)
gyp ERR! stack     at tryModuleLoad (module.js:453:12)
gyp ERR! stack     at Function.Module._load (module.js:445:3)
gyp ERR! stack     at Module.require (module.js:504:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node.exe" "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

C:\Users\marwan.alamoudi>node-gyp -v
v8.4.1

C:\Users\marwan.alamoudi>msbuild -v
'msbuild' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\marwan.alamoudi>msvc -v
'msvc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\marwan.alamoudi>MSBuild -v
'MSBuild' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\marwan.alamoudi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@6.17.1 | win32 | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
gyp ERR! stack async function getBaseConfigGypi ({ gyp, nodeDir }) {
gyp ERR! stack       ^^^^^^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token function
gyp ERR! stack     at createScript (vm.js:56:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:97:10)
gyp ERR! stack     at Module._compile (module.js:549:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:586:10)
gyp ERR! stack     at Module.load (module.js:494:32)
gyp ERR! stack     at tryModuleLoad (module.js:453:12)
gyp ERR! stack     at Function.Module._load (module.js:445:3)
gyp ERR! stack     at Module.require (module.js:504:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node.exe" "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

C:\Users\marwan.alamoudi>npm -v
3.10.10

C:\Users\marwan.alamoudi>node-gyp
C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
async function getBaseConfigGypi ({ gyp, nodeDir }) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)

C:\Users\marwan.alamoudi>node-gyp config
C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
async function getBaseConfigGypi ({ gyp, nodeDir }) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)

C:\Users\marwan.alamoudi>node-gyp config
C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
async function getBaseConfigGypi ({ gyp, nodeDir }) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)

C:\Users\marwan.alamoudi>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@6.17.1 | win32 | x64
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\build.js:43:20)
gyp ERR! stack     at ReadFileContext.callback (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\node_modules\graceful-fs\graceful-fs.js:123:16)
gyp ERR! stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node.exe" "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

C:\Users\marwan.alamoudi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@6.17.1 | win32 | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\create-config-gypi.js:18
gyp ERR! stack async function getBaseConfigGypi ({ gyp, nodeDir }) {
gyp ERR! stack       ^^^^^^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token function
gyp ERR! stack     at createScript (vm.js:56:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:97:10)
gyp ERR! stack     at Module._compile (module.js:549:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:586:10)
gyp ERR! stack     at Module.load (module.js:494:32)
gyp ERR! stack     at tryModuleLoad (module.js:453:12)
gyp ERR! stack     at Function.Module._load (module.js:445:3)
gyp ERR! stack     at Module.require (module.js:504:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\marwan.alamoudi\Documents\nodejsV6\node-v6.17.1-win-x64\node_modules\node-gyp\lib\configure.js:10:26)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node.exe" "C:\\Users\\marwan.alamoudi\\Documents\\nodejsV6\\node-v6.17.1-win-x64\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

**Comment by cclauss** [comment]
v6 ain't got async... https://www.infoq.com/news/2017/02/node-76-async-await

https://nodejs.org/en/about/releases is what we support.

**Comment by Marwan7035** [comment]
The node is updated to a compatible version. 

>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.4.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp info find VS using VS2017 (15.9.28307.1778) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\node_modules\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\marwan.alamoudi\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\marwan.alamoudi\\node_modules',gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\node_modules\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\marwan.alamoudi\node_modules) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi\node_modules
gyp ERR! node -v v17.4.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

C:\Users\marwan.alamoudi\node_modules>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.4.0 | win32 | x64
gyp ERR! build error
gyp ERR! stack Error: Could not find *.sln file. Did you run "configure"?
gyp ERR! stack     at C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:85:25
gyp ERR! stack     at f (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\once\once.js:25:25)
gyp ERR! stack     at Glob.<anonymous> (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\glob\glob.js:148:7)
gyp ERR! stack     at Glob.emit (node:events:520:28)
gyp ERR! stack     at Glob._finish (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\glob\glob.js:194:8)
gyp ERR! stack     at done (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\glob\glob.js:179:14)
gyp ERR! stack     at Glob._processReaddir2 (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\glob\glob.js:405:12)
gyp ERR! stack     at C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\glob\glob.js:368:17
gyp ERR! stack     at RES (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\inflight\inflight.js:31:16)
gyp ERR! stack     at f (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\node_modules\once\once.js:25:25)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\marwan.alamoudi\node_modules
gyp ERR! node -v v17.4.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

C:\Users\marwan.alamoudi\node_modules>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.4.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp info find VS using VS2017 (15.9.28307.1778) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\node_modules\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\marwan.alamoudi\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\marwan.alamoudi\\node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\node_modules\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\marwan.alamoudi\node_modules) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\marwan.alamoudi\node_modules
gyp ERR! node -v v17.4.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by cclauss** [comment]
Two separate issues...  Can you solve either of these?
> gyp: binding.gyp not found (cwd: C:\Users\marwan.alamoudi\node_modules) while trying to load binding.gyp

> gyp ERR! stack Error: Could not find *.sln file. Did you run "configure"?

**Comment by Marwan7035** [comment]
I ran configure; however, the same errors appear. 

I placed a binding.gyp file in the root file of the package. But, the gyp: binding.gyp not found (cwd: C:\Users\marwan.alamoudi\node_modules) while trying to load binding.gyp  error still exist as shown below. 

node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.4.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp info find VS using VS2017 (15.9.28307.1778) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\marwan.alamoudi\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\marwan.alamoudi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\marwan.alamoudi) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v17.4.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by cclauss** [comment]
`dir C:\Users\marwan.alamoudi`  # Is there a `binding.gyp` file there?!?

**Comment by Marwan7035** [comment]
The binding.gyp issue is fixed. 

There is new errors showing when running any node-gyp <command>. 

>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.4.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp info find VS using VS2017 (15.9.28307.1778) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\marwan.alamoudi\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\marwan.alamoudi\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\marwan.alamoudi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\marwan.alamoudi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
C:\Users\marwan.alamoudi\build\..\src\binding.cc
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\binding.cc': No such file or directory [C:\Users\marwan.alam
oudi\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\marwan.alamoudi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marwan.alamoudi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marwan.alamoudi
gyp ERR! node -v v17.4.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
