### ISSUE TITLE
can u help me for fix this eror sir 

### ISSUE THREAD

**Issue by akbardwiyan** [nodejs/node-gyp#2605]
npm ERR! code 1
npm ERR! path C:\nft\instal\generate-nfts-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\nft\instal\generate-nfts-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\nft\instal\generate-nfts-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@16.13.2 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "C:\nft\instal\generate-nfts-main\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-win32-unknown-ia32.tar.gz failed, reason: getaddrinfo ENOTFOUND github.com
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-win32-unknown-ia32.tar.gz failed, reason: getaddrinfo ENOTFOUND github.com
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.10.1 found at "C:\Users\USER\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: ENOENT: no such file or directory, stat 'C:\Users\am\projects\pt\.tmp\node-v16.13.2-headers.tar.gz'
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\nft\\instal\\generate-nfts-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\nft\\instal\\generate-nfts-main\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd C:\nft\instal\generate-nfts-main\node_modules\canvas
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\nft\instal\generate-nfts-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\nft\instal\generate-nfts-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\nft\instal\generate-nfts-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.18363
npm ERR! node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\nft\\instal\\generate-nfts-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\nft\instal\generate-nfts-main\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2022-02-04T04_06_42_949Z-debug-0.log

**Comment by cclauss** [comment]
Please provide the command typed and the full error log.

This log starts with `npm ERR! code 1` but it is impossible to fix unless we know what it was trying to do BEFORE it returned error code 1.

**Comment by radhika1406** [comment]
Hi @cclauss  I am also facing the same issue , Please find the logs [2022-02-27T18_34_48_303Z-debug.log](https://github.com/nodejs/node-gyp/files/8149229/2022-02-27T18_34_48_303Z-debug.log)
entered npm install command
 to run api-playground @  https://github.com/BestBuy/api-playground

**Comment by cclauss** [comment]
Closing `node-pre-gyp` is unmaintained.
