### ISSUE TITLE
No problem

### ISSUE THREAD

**Issue by menglingyu659** [nodejs/node-gyp#2618]
!!!

**Comment by menglingyu659** [comment]
node version: 12.20.0
npm version: 6.14.15
node-gyp version: 8.2.0

**Comment by cclauss** [comment]
Is `pdb` this?  Or something else?  https://docs.python.org/3/library/pdb.html

**Comment by menglingyu659** [comment]
> Is `pdb` this? Or something else?   ##https://docs.python.org/3/library/pdb.html

This one: 
![middle_img_v2_200099df-bc37-4f75-b81b-6aa1a3a98ecg](https://user-images.githubusercontent.com/50974543/155053287-e25b8d75-edc7-4255-9005-ce8209a8a97c.png)

The following is the contents of the `binding.gyp` file: 
![middle_img_v2_6c836f49-d23b-435c-b062-f08d689f2f7g](https://user-images.githubusercontent.com/50974543/155053300-d91949de-72b7-411c-9761-bb339948f85e.png)


On Windows, I need this`.pdb` file for error stack analysis, which it does generate on Windows.
Macos also requires a `.dsym /.sym` file for analysis, but does not generate the corresponding `.dsym /.sym` file in MacOS
