### ISSUE TITLE
Angular application - installing node-gyp checking for Python and throwing Error not found

### ISSUE THREAD

**Issue by lakshmipuli** [nodejs/node-gyp#2649]
Node Version: 14.18.3
Angular : 13.1.4
Platform: Windows
Compiler: Windows
Module: npm install node-gyp

npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.18.3 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Program Files\Python\Python39"" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Program Files\Python\Python39"

Couple things that I tried from google : 
1. Installed Python 3.9.9
2. Npm set config Python "path to python"
3. PATH variable (both environment and system) to have respective Python path
4. npm install --global --production windows-build-tools

**Comment by cclauss** [comment]
Please create a new issue and instead of deleting the default text, read it!
> npm ERR! gyp info using node-gyp@3.8.0

v.s. version 9

**Comment by lakshmipuli** [comment]
Sorry couldn't follow u. I read it before I deleted it.

**Comment by cclauss** [comment]
OK.  The first sentence says…

Please look thru your error log for the string `gyp info using node-gyp@` and if the version number is less than the [current release of node-gyp](https://github.com/nodejs/node-gyp/releases) then __please upgrade__ using the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md and try your command again.
