### ISSUE TITLE
Trying To npm install -g node-gyp@3.6.2 and this is what i'm getting this

### ISSUE THREAD

**Issue by YungKingz** [nodejs/node-gyp#2655]
yungkingz@Yungs-MBP ~ % npm install -g node-gyp@3.6.2
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yungkingz/.npm/_logs/2022-05-06T23_31_22_320Z-debug.log

**Comment by cclauss** [comment]
`mkdir -p /usr/local/lib/node_modules`

**Comment by YungKingz** [comment]
> `mkdir -p /usr/local/lib/node_modules`

I'm sorry I don't understand what this mean.. I'm new to coding

**Comment by YungKingz** [comment]
> npm install -g node-gyp@3.6.2

I think I fix it

yungkingz@Yungs-MBP ~ %  npm install -g node-gyp@3.6.2
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@3.6.2
added 97 packages from 66 contributors in 5.013s

**Comment by cclauss** [comment]
The current release is `node-gyp@9`  https://github.com/nodejs/node-gyp/releases

**Comment by YungKingz** [comment]
> The current release is `node-gyp@9` https://github.com/nodejs/node-gyp/releases

I just bought a blockchain developer course  from Dapp University and I'm going through the instruction and for this specific project he saying to use this version of node... but thank you for helping me out. I do believe I solve my issue from looking up your first reply.
