### ISSUE TITLE
I mistakenly committed to master… Can someone please revert?

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-gyp#2657]
Please revert https://github.com/nodejs/node-gyp/commit/a37f186eacc17145e00972262d91e6402404ce05

**Comment by bacloud22** [comment]
This might be it, I'm pulling my hair to make it work 😄 
Good luck @cclauss and thank you for supportin `node-gyp` 💌

**Comment by rvagg** [comment]
force pushed to remove it, also edited a commit that's second in the stack but had a bad name: `Update README.md`, I changed it to: `doc: update docs/README.md with latest version number`.
