### ISSUE TITLE
Improve documentation for Windows install

### ISSUE THREAD

**Issue by namazso** [nodejs/node-gyp#2678]
As the default Visual Studio install recommended in the README no longer works (see https://github.com/nodejs/node-gyp/pull/2565) and the PR fixing it doesn't seem to ever get merged (it has been 6 months already) could we at least in the meantime get a documentation update to have it say that you need to install a Windows **10** SDK to make it work? Digging through the issues to find out how to get this working isn't fun.

**Comment by cclauss** [comment]
@nodejs/platform-windows

**Comment by DeeDeeG** [comment]
I think the current thing to do is to use direct downloads from Microsoft, (orsomething like Chocolatey) to get Visual Studio (or Visual Studio Build Tools) and make sure to select the "Visual C++ build tools" workflow and a Windows SDK (10 or 11, maybe Universal also works, but I'm not sure).
