### ISSUE TITLE
node-gyp throws error when doing 'npm install'

### ISSUE THREAD

**Issue by woflydev** [nodejs/node-gyp#2679]
I have upgraded to the latest version of node-gyp.

* **Node Version**: 16.13.0 
* **Platform**: Windows NT 10.0 
* **Compiler**: 
* **Module**:

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
details in 
log file.

Usage: npm install
(...)
```
Log file:
[Attached](https://github.com/nodejs/node-gyp/files/8878370/2022-06-10T11_16_29_296Z-debug.log)

</details>

Throws error when trying to do 'npm install'.

**Comment by cclauss** [comment]
> error gyp info using node-gyp@3.8.0

You are using node-gyp v3 and [the current version](https://github.com/nodejs/node-gyp/releases) is v9.

**Comment by woflydev** [comment]
I solved the error by reinstalling Visual Studio 2019 (turns out I had two copies) and then running:
``npm install -g --msvs_version=2019 node-gyp rebuild``
