### ISSUE TITLE
[Question] `node-gyp` for windows 10 (and now v11) in 2022

### ISSUE THREAD

**Issue by ghost** [nodejs/node-gyp#2691]
I have a few questions for the node gyp project:

1. Is `node-gyp` up to date on Node.js v17+? I tried to comb through this ["giant thread"](https://github.com/nodejs/node-gyp/issues/629#issue-79269678), but there is so much confusion in the discussion, and it looks like it's _way_ out of date (~7 years out of date).
2. Are the native APIs provided by each target still relevant? I mean, the developer community is trending towards virtual machines (ex. JVM, CLR/Mono, etc.), and towards shifting the execution/API to the web (DenoJS, and CDNs such as jsDelivr). Also Node.js has several builtin modules (ex. `fs`, `http`, `crypto`, etc.), so why are these APIs "reinventing the wheel" when Node.js already has the tools they need (see example)?

Now, correct me if I'm wrong, but for example the `sqlite3` package could use the `fs` module with a parser dependency to parse a string of SQL, sanitize it, evaluate it and access data in a file, while other (No)SQL package could use `http`, `crypto`, and/or other modules to request a server to execute a query.

P.S. Let me know if any of this is wrong, please (I'm kind of new to the github/nodejs community btw). Thank you.

**Comment by IRod22** [comment]
Edited title as Windows 11 is already out.

**Comment by sytclh** [comment]
Why node-gyp can't found the version of VS 2022 Community? Is there something wrong with my env variables?

**Comment by sytclh** [comment]
set node-gyp config `npm config set node_gyp "your global node-gyp"`  and try again

**Comment by IRod22** [comment]
@sytclh just curious, but what happened to this comment I received in my email inbox?

> Why node-gyp can't found the version of VS 2022 Community? Is there something wrong with my env variables?

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
