### ISSUE TITLE
node-gyp fails on npm install on Windows 11 latest build

### ISSUE THREAD

**Issue by mabramishvili** [nodejs/node-gyp#2703]
I'm using VS 2022 build tools and python 3.9, but the `npm install` seems to fail on node-gyp
I also tried using VS 2019 and 2017 with no success

node version I'm using is `16.13.0`
npm version is `8.14.0`

Here is the log:

> npm ERR! code 1
> npm ERR! path C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\utf-8-validate
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\mixei\AppData\Local\Temp\install-583a6339.cmd
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@8.4.1
> npm ERR! gyp info using node@16.13.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.9.0 found at "C:\Users\mixei\AppData\Local\Programs\Python\Python39\python.exe"
> npm ERR! gyp info find VS using VS2022 (17.2.32630.192) found at:
> npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
> npm ERR! gyp info find VS run with --verbose for detailed information
> npm ERR! gyp info spawn C:\Users\mixei\AppData\Local\Programs\Python\Python39\python.exe
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'msvs',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\utf-8-validate\\build\\config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\AppData\\Local\\node-gyp\\Cache\\16.13.0\\common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\mixei\\AppData\\Local\\node-gyp\\Cache\\16.13.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\mixei\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.0\\\\<(target_arch)\\\\node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\utf-8-validate',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\utf-8-validate\\build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp: C:\Users\mixei\AppData\Local\node-gyp\Cache\16.13.0\common.gypi not found (cwd: C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\utf-8-validate) while reading includes of binding.gyp while trying to load binding.gyp
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\node-gyp\lib\configure.js:259:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> npm ERR! gyp ERR! System Windows_NT 10.0.22000
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\utf-8-validate
> npm ERR! gyp ERR! node -v v16.13.0
> npm ERR! gyp ERR! node-gyp -v v8.4.1
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\mixei\AppData\Local\npm-cache\_logs\2022-07-14T10_39_57_847Z-debug-0.log

any ideas?

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@8.4.1

https://github.com/nodejs/node-gyp/releases is v9.1.0

**Comment by mabramishvili** [comment]
@cclauss tried 9.1.0, same result:

> npm ERR! code 1
> npm ERR! path C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\fibers
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\mixei\AppData\Local\Temp\install-3af03f79.cmd
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.1.0
> npm ERR! gyp info using node@16.13.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.9.0 found at "C:\Users\mixei\AppData\Local\Programs\Python\Python39\python.exe"
> npm ERR! gyp info find VS using VS2022 (17.2.32630.192) found at:
> npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
> npm ERR! gyp info find VS run with --verbose for detailed information
> npm ERR! gyp info spawn C:\Users\mixei\AppData\Local\Programs\Python\Python39\python.exe
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'msvs',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\fibers\\build\\config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\AppData\\Local\\node-gyp\\Cache\\16.13.0\\common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\mixei\\AppData\\Local\\node-gyp\\Cache\\16.13.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\mixei\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.0\\\\<(target_arch)\\\\node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\fibers',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\fibers\\build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp: C:\Users\mixei\AppData\Local\node-gyp\Cache\16.13.0\common.gypi not found (cwd: C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\fibers) while reading includes of binding.gyp while trying to load binding.gyp
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\node-gyp\lib\configure.js:284:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> npm ERR! gyp ERR! System Windows_NT 10.0.22000
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mixei\\Desktop\\Forbes Projects\\garden\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd C:\Users\mixei\Desktop\Forbes Projects\garden\node_modules\fibers
> npm ERR! gyp ERR! node -v v16.13.0
> npm ERR! gyp ERR! node-gyp -v v9.1.0
> npm ERR! gyp ERR! not ok

also did `npm config set msvs_version 2022`


it works if I switch to node 14 and older version of node-gyp but I'm trying to upgrade the project to use node 16..

**Comment by cclauss** [comment]
@platform-windows @gengjiawen @namazso @hubbergit @joaocgreis @owl-from-hogvarts 
Any hints on how to solve this... The new node-gyp v9.1 release does not fix it.  Many of [our Windows issues](https://github.com/nodejs/node-gyp/labels/Windows) are similar.

**Comment by cclauss** [comment]
@mabramishvili Does this help?   (I do not have a Windows box.)

**Comment by mabramishvili** [comment]
ok it worked after following this
https://github.com/Automattic/node-canvas/issues/1701

and then from this thread section about installing GTK here
https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

**Comment by cclauss** [comment]
So can this issue be closed?

**Comment by TobiasMW** [comment]
What exactly do you mean by following this link? @mabramishvili

**Comment by mabramishvili** [comment]
> What exactly do you mean by following this link? @mabramishvili

I downloaded GTK bundle from https://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip

and unzipped the contents inside
C:\GTK.

afterwards `npm install` worked without errors

**Comment by ziruil3** [comment]
mine is like this:
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\zirui/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\zirui\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\zirui\AppData\Local\npm-cache\_logs\2023-07-29T20_22_23_105Z-debug-0.log

node version: 18.17.0

**Comment by cclauss** [comment]
Is there a file `C:\Users\zirui\package.json`?

**Comment by ziruil3** [comment]
@cclauss No. I redirected to my project folder and ran the same command "npx create-react-app@3.4.1 my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm", but more errors occur.
```
Creating a new React app in C:\Users\zirui\Desktop\skyscanner\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and @skyscanner/backpack-react-scripts with @skyscanner/cra-template-backpack...

npm ERR! code 1
npm ERR! path C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\zirui\\Desktop\\skyscanner\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.17.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path
npm ERR! gyp verb find Python - "python" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python39\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python39\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python39-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python38\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python38\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python38-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python37-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python36\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python36\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Users\zirui\AppData\Local\Programs\Python\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp verb find Python - executing "C:\Program Files (x86)\Python36-32\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp verb find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp verb find Python - executing "py.exe" to get Python 3 executable path
npm ERR! gyp verb find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\zirui\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\zirui\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-gyp\lib\find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-gyp\lib\find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-gyp\lib\find-python.js:228:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-gyp\lib\find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zirui\\Desktop\\skyscanner\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\zirui\Desktop\skyscanner\my-app\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: C:\Users\zirui\AppData\Local\npm-cache\_logs\2023-07-30T10_48_05_302Z-debug-0.log
```

**Comment by cclauss** [comment]
Try:
```
python3 --version
python --version
py --version
```
Requests for help with [`node-sass` are very common](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22). Please be aware that this package is deprecated, you should seek alternatives and avoid opening new issues about it here.

#2870 discusses `skyscanner`

**Comment by ziruil3** [comment]
Here is the message.
```
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases

py : The term 'py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again
```

**Comment by ziruil3** [comment]
I just read #2870. You mean the project isn't runnable because of deprecated node-sass? @cclauss

**Comment by cclauss** [comment]
On Python: Read https://github.com/nodejs/node-gyp#on-windows
On node-sass: Try `sass` instead of `node-sass` or get support from https://github.com/Skyscanner/backpack

**Comment by ziruil3** [comment]
I installed Python from Microsoft store and the project ran successfully. Thanks for the help. @cclauss
