### ISSUE TITLE
can install i2c-bus on rpi4

### ISSUE THREAD

**Issue by fmuntean** [nodejs/node-gyp#2712]
sudo npm install i2c-bus
npm ERR! code 1
npm ERR! path /mnt/dietpi_userdata/node-red/node_modules/i2c-bus
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.1 | linux | arm
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:709:12)
npm ERR! gyp ERR! System Linux 5.15.32-v7l+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/mnt/dietpi_userdata/node-red/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /mnt/dietpi_userdata/node-red/node_modules/i2c-bus
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

python --version
Python 3.9.2

npm --version
8.11.0

Please help, I don't understand where that python 2 code in the error is from.

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0

current version is v9.1

**Comment by fmuntean** [comment]
thank you
