### ISSUE TITLE
cnpm i heapdump error

### ISSUE THREAD

**Issue by leviluo** [nodejs/node-gyp#2717]
when i install heapdump,it show error as below
<img width="1224" alt="截屏2022-08-10 12 55 51" src="https://user-images.githubusercontent.com/19730473/183821365-83079793-a9c1-40ce-aebc-004b85b45051.png">

**Comment by cclauss** [comment]
Do you get the same results when installing a current version of https://www.npmjs.com/package/nan ?

**Comment by cclauss** [comment]
What was the solution?
