### ISSUE TITLE
node_gyp not working with python 2.7

### ISSUE THREAD

**Issue by kheuch2018** [nodejs/node-gyp#2724]
I try to use node-gyp with a project using python 2.7 but it requires python 3. Has anyone encountered this issue and have a workaround ?

**Comment by cclauss** [comment]
Python 2 died 968 days ago on 1/1/2020.  There have been no security updates since then so it should not be trusted.  #2300 landed in [node-gyp v8.0.0](https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md#v800-2021-04-03) so a v7 node-gyp should support legacy Python.
