### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2 How to fix this?

### ISSUE THREAD

**Issue by MrMaxorz** [nodejs/node-gyp#2725]
* **Node Version**: node v16.16.0, npm v8.11.0
* **Platform**:  macOS 12.4 (21F79) M1
* **Compiler**: 
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* **Module**: node-gd

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
$node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@16.16.0 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No targets specified and no makefile found.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node@16/16.16.0/bin/node" "/opt/homebrew/bin/node-gyp" "build"
gyp ERR! cwd /Users/Maxorz
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
```

</details>

**Comment by cclauss** [comment]
> gyp info using node-gyp@5.1.1

https://github.com/nodejs/node-gyp/tree/main/docs#readme

**Comment by MrMaxorz** [comment]
`gyp: binding.gyp not found (cwd: /Users/Maxorz) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/usr/local/bin/node" "/opt/homebrew/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Maxorz
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok`

same error

**Comment by MrMaxorz** [comment]
> > gyp info using node-gyp@5.1.1
> 
> https://github.com/nodejs/node-gyp/tree/main/docs#readme

after upgrade to v9.1.0

gyp: binding.gyp not found (cwd: /Users/Maxorz) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack at ChildProcess.emit (node:events:513:28)
gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/usr/local/bin/node" "/opt/homebrew/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Maxorz
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok

same error

**Comment by cclauss** [comment]
> no makefile found

Running `make` requires that there is a `Makefile` in the current working directory.

**Comment by MrMaxorz** [comment]
The reproduce steps:
1. brew install node@16
2. npm i -g npm
3. npm i -g node-gyp
4. node-gyp configure

err log:

> $node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maxorz/Works/Longdo/thaimap-snippet/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maxorz/Library/Caches/node-gyp/16.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Maxorz/Library/Caches/node-gyp/16.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Maxorz/Library/Caches/node-gyp/16.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Maxorz/Works/Longdo/thaimap-snippet',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/Maxorz/Works/Longdo/thaimap-snippet) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node@16/16.17.0/bin/node" "/opt/homebrew/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Maxorz/Works/Longdo/thaimap-snippet
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok

**Comment by cclauss** [comment]
`touch /Users/Maxorz/Works/Longdo/thaimap-snippet/binding.gyp`

**Comment by MrMaxorz** [comment]
nothing show ...

**Comment by cclauss** [comment]
Did you try homebrew?

**Comment by MrMaxorz** [comment]
yes, I tried homebrew.

**Comment by MrMaxorz** [comment]
After I tried touch and run `node-gyp configure`

error logs:

Traceback (most recent call last):
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 400, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(
  File "/opt/homebrew/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 237, in LoadOneBuildFile
    build_file_data = eval(build_file_contents, {"__builtins__": {}}, None)
  File "binding.gyp", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by MrMaxorz** [comment]
$brew list
==> Formulae
aom		ca-certificates	gd		imath		libavif		libtiff		macos-term-size	openexr		webp
brotli		fontconfig	giflib		jpeg-turbo	libnghttp2	libuv		node@14		openssl@1.1
c-ares		freetype	icu4c		jpeg-xl		libpng		libvmaf		node@16		pkg-config

==> Casks
fig

**Comment by cclauss** [comment]
`echo "{}" > /Users/Maxorz/Works/Longdo/thaimap-snippet/binding.gyp`

**Comment by MrMaxorz** [comment]
After I tried echo `echo "{}" > /Users/Maxorz/Works/Longdo/thaimap-snippet/binding.gyp`

Error log:

gyp: Unable to find targets in build file binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node@16/16.17.0/bin/node" "/opt/homebrew/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Maxorz/Works/Longdo/thaimap-snippet
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok

**Comment by MrMaxorz** [comment]
I found something strange

`$which node`
/opt/homebrew/opt/node@16/bin/node`

but in error log use:
`gyp ERR! command "/opt/homebrew/Cellar/node@16/16.17.0/bin/node" "/opt/homebrew/bin/node-gyp" "configure"`

**Comment by cclauss** [comment]
/opt/homebrew/opt/node@16/bin/node --version
/opt/homebrew/Cellar/node@16/16.17.0/bin/node --version

**Comment by MrMaxorz** [comment]
`lrwxr-xr-x   1 Maxorz  admin    25B Aug 29 16:40 node@16@ -> ../Cellar/node@16/16.17.0`

**Comment by MrMaxorz** [comment]
Full error log:

```
$node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maxorz/Works/Longdo/thaimap-snippet/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maxorz/Library/Caches/node-gyp/16.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Maxorz/Library/Caches/node-gyp/16.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Maxorz/Library/Caches/node-gyp/16.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Maxorz/Works/Longdo/thaimap-snippet',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Unable to find targets in build file binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node@16/16.17.0/bin/node" "/opt/homebrew/bin/node-gyp" "configure"
gyp ERR! cwd /Users/Maxorz/Works/Longdo/thaimap-snippet
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
```

**Comment by iMonZ** [comment]
@cclauss any information here? I can't find a solution in this thread, so could you please reopen this issue?
