### ISSUE TITLE
`node-gyp rebuild` npm ERR! Exit status 7

### ISSUE THREAD

**Issue by abhishek-rathore07** [nodejs/node-gyp#2731]
I am running npm i in the project root and getting below error :-

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! libpq@1.8.12 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the libpq@1.8.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhis\AppData\Roaming\npm-cache\_logs\2022-09-13T05_21_33_970Z-debug.log

Attaching Error logs for the reference.

![error 1](https://user-images.githubusercontent.com/113411230/189817442-af5aa102-9516-4feb-8700-1cf87ff0731b.PNG)
![error 2](https://user-images.githubusercontent.com/113411230/189817451-c42c935a-d290-4bd3-bdcf-17b40a803288.PNG)

**Comment by cclauss** [comment]
Please try https://github.com/nodejs/node-gyp/issues/2714#issuecomment-1243711637

If that does not work then please open an issue on https://github.com/brianc/node-libpq

**Comment by abhishek-rathore07** [comment]
it didn't worked. Raised issue on [node-libpq](https://github.com/brianc/node-libpq)

[#91](https://github.com/brianc/node-libpq/issues/91)
