### ISSUE TITLE
Node gyp cannot find the msvs 2017 in the PC which installed multi-version of msvs.

### ISSUE THREAD

**Issue by Ray23210** [nodejs/node-gyp#2739]
* **Node Version**: 
* node version v16.16.0.  npm v8.11.0.
* **Platform**: 
* Windows
* **Compiler**: 
* msbuild
* **Module**: 

I tried to "set node-gyp configure --msvs_version=2017", and also tried add "msvs_version=2017" in project .npmrc
but it still find vs2022 as its compiler.

<details><summary>Verbose output (from npm or node-gyp):</summary>
```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm verb cli c:\ThirdPty\nodejs\node.exe c:\ThirdPty\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@8.11.0
npm info using node@v16.16.0
npm verb title npm install
npm verb argv "install"

Usage: npm <command>
(...)
```

</details>
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.16.0 | win32 | x64
gyp info find Python using Python version 3.6.4 found at "C:\Program Files\Python36\python.exe"
gyp info find VS using VS2022 (17.2.32630.192) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional"
gyp info find VS run with --verbose for detailed information

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
