### ISSUE TITLE
can't build node-register-scheme

### ISSUE THREAD

**Issue by UnbreakCode** [nodejs/node-gyp#2744]
since I had so much problems using VS 2022 with node-gyp, I am now getting random build errors when using https://github.com/devsnek/node-register-scheme in my project. Sometimes it is working and sometimes not and I dont know why.

I am using "yarn install -force" to achive this error

yarn version: 1.22.17
node version: 16.17.1
node-gyp version: 9.0.0

`[4/4] Rebuilding all packages...
[-/6] ⠐ waiting...
[2/6] ⠐ register-scheme
[3/6] ⠐ @seorii/win32-displayconfig
[4/6] ⠈ naudiodon
error C:\Users\Niclas\Desktop\test\node_modules\register-scheme: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Niclas\Desktop\test\node_modules\register-scheme
Output:
C:\Users\Niclas\Desktop\test\node_modules\register-scheme>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Debugger attached.
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.17.1 | win32 | x64
gyp info find Python using Python version 3.10.7 found at "C:\Users\Niclas\AppData\Local\Programs\Python\Python310\python.exe"
gyp info find VS using VS2022 (17.1.32210.238) found at:
gyp info find VS "E:\Visual Studio 2022"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Niclas\AppData\Local\Programs\Python\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Niclas\\Desktop\\test\\node_modules\\register-scheme\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Niclas\\AppData\\Local\\node-gyp\\Cache\\16.17.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Niclas\\AppData\\Local\\node-gyp\\Cache\\16.17.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Niclas\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Niclas\\Desktop\\test\\node_modules\\register-scheme',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Niclas\\Desktop\\test\\node_modules\\register-scheme\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Debugger attached.
Waiting for the debugger to disconnect...
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Niclas\Desktop\test\node_modules\register-scheme
gyp ERR! node -v v16.17.1`

**Comment by StefanStojanovic** [comment]
This has been stale for a long time so I'll close it. If still relevant, feel free to reopen.
