### ISSUE TITLE
Support for OS X Command Like Tools

### ISSUE THREAD

**Issue by Paxa** [nodejs/node-gyp#275]
In current version there is a problem with `xcodebuild` and `xcode-select`

This is issue in gyp project https://code.google.com/p/gyp/issues/detail?id=292
In the end of topic is solution, this patch https://codereview.chromium.org/14887003/patch/1/2

Please apply it

**Comment by tk120404** [comment]
@Paxa can you please close this issue

**Comment by Paxa** [comment]
Thank you

**Comment by gibfahn** [comment]
FWIW I think https://github.com/nodejs/node-gyp/pull/1370 will fix this.

**Comment by tk120404** [comment]
👍
