### ISSUE TITLE
Unstable installation on Windows

### ISSUE THREAD

**Issue by michalzaq12** [nodejs/node-gyp#2751]
* **Node Version**: v16
* **Platform**: Windows 10 / 11

The unpacked archive downloaded from `https://nodejs.org/download/release/v16.17.1/node-v16.17.1-headers.tar.gz` (Node version doesn't matter) is sometimes corrupted on Windows. Which causes a lot of bugs (`<file> not found`,  `unable to open <file>: No such file or directory`).
I think this may be related to the Windows `tar` `unlink` workaround: https://github.com/npm/node-tar/blob/26a496e5fa74eeaa0c3539511560fc181ef56557/lib/unpack.js#L52

File `v8-platform.h` is missing
<img width="742" alt="node-gyp" src="https://user-images.githubusercontent.com/28574933/196043982-363860fb-2b6b-421b-a608-885ee972c93f.png">

Linked issues:
- https://github.com/nodejs/node-gyp/issues/2714
- https://github.com/nodejs/node-gyp/issues/2683

**Comment by psvks** [comment]
Happend to me. gyp its not stable and gave me so much errors
