### ISSUE TITLE
Cannot assign to read only property 'cflags' of object '#<Object>'

### ISSUE THREAD

**Issue by guanzhengyinqin** [nodejs/node-gyp#2752]
build node-sass error

c++ compiler
gcc -E -dM - </dev/null | grep "STDC_VERSION"
#define __STDC_VERSION__ 201710L

> details
npm --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@7.1.2
gyp info using node@19.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.10.8"
gyp info find Python using Python version 3.10.8 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 19.0.0
gyp verb command install [ '19.0.0' ]
gyp verb install input version string "19.0.0"
gyp verb install installing version: 19.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 19.0.0
gyp verb build dir attempting to create "build" dir: /home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:189:23)
gyp ERR! System Linux 6.0.2-arch1-1
gyp ERR! command "/usr/bin/node" "/home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/guanzheng/document/workspace/codeworkspace/webstormProject/Saber/node_modules/node-sass
gyp ERR! node -v v19.0.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.

**Comment by cclauss** [comment]
Here is the text that you deleted when you opened this issue...

Please look thru your error log for the string `gyp info using node-gyp@` and if the version number is less than the [current release of node-gyp](https://github.com/nodejs/node-gyp/releases) then __please upgrade__ using the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md and try your command again.

Requests for help with [`node-sass` are very common](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22). Please be aware that this package is deprecated, you should seek alternatives and avoid opening new issues about it here.

**Comment by Jakobeha** [comment]
Note the above instructions don't work in npm 9. What did work and force nodejs to use the correct `node-gyp` version was adding it to devDependencies as described [here](https://stackoverflow.com/questions/70800909/how-to-force-npm-to-use-different-node-gyp-version-when-installing-packages)

**Comment by alper** [comment]
This is a relatively old project. I'm not sure how randomly upgrading node-gyp will solve it and not break a bunch of other things.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/tree/main/docs#readme

**Comment by alper** [comment]
I can't upgrade it because it's not one of our main dependencies. Some other package is depending on it.

**Comment by xzifan** [comment]
I was trying to rebuild ref-napi and ffi-napi for electron and the same error showed up. 

Adding  `"node-gyp": "^10.0.1"` to devDependencies fixed it in my case.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/issues?q=ffi-napi+label%3Affi-napi is another set of problems.

**Comment by kapilshanaz** [comment]
Adding 
`
"node-gyp": "10.0.1"
"nan": "2.18.0"
`
Also adding
`
"resolutions": {
	"nan": "2.18.0"
}
`
to package.json worked for me for Node.JS 20 build failure

**Comment by Guilherhast** [comment]
In my case moving the folder `$HOME/.config/yarn/global` to `$HOME/.config/yarn/global_bak` solved the issue.
It was a conflict between the packages installed to user and the ones installed in the operating system.

**Comment by remixer-dec** [comment]
I was trying to install a [project](https://github.com/mokuappio/serverless-invoices) from 2022 that has `node-sass` in it's dependencies.
None of the suggested solutions worked for me, here is what worked:
- removing the package that causes this from package.json, 
- then installing latest node-gyp, 
- trying to install node-sass again, then realizing that it is not working because of https://github.com/nodejs/node-gyp/issues/2869 
- then [downgrading sass-loader](https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function), 
- then installing `sass` instead of `node-sass`.

**Comment by cclauss** [comment]
Correct.  Repeating from above (https://github.com/nodejs/node-gyp/issues/2752#issuecomment-1719011294), `node-sass was deprecated long ago.

**Comment by LukeShu** [comment]
Sure, but this is a node-gyp problem, not a node-sass problem.

Since this ticket is what comes up if you search for `Cannot assign to read only property 'cflags' of object '#<Object>'`, whether or not you're using node-sass: The problem is that you'll need node-gyp 8.2.0 or later for Node 16+.  In Yarn syntax, you can force this with:

```json
  "resolutions": {
    "//": [
      "Pull in https://github.com/nodejs/node-gyp/pull/2368 (first included in",
      "v8.2.0) for compatibility with Node 16+"
    ],
    "node-gyp": "8.2.0",
  }
```

You should of course upgrade to a newer node-gyp if you can; but if you're trying to get an old project going again, you probably want to be as conservative as you can for a bit.

If you are using node-sass, you'll need the above, but you'll also need at least node-sass 6.0 for that version of node-gyp:

```json
  "resolutions": {
    "//": [
      "Pull in https://github.com/nodejs/node-gyp/pull/2368 (first included in",
      "v8.2.0) for compatibility with Node 16+"
    ],
    "node-gyp": "8.2.0",
    "//": [
      "Since node-gyp 8.2.0 requires C++20 or later, we require at least",
      "node-sass v6 which is the first to no longer force `-std=c++0x`"
    ],
    "node-sass": "6.0.0"
  }
```

You should of course look into migrating from `node-sass` to `sass`, but if `node-sass` is being pulled in by another large dependency (maybe Vue 2), then upgrading major versions of other things is likely to be a larger task you don't want to tackle right away.
