### ISSUE TITLE
[QUESTION] Engines of next major version?

### ISSUE THREAD

**Issue by lukekarrys** [nodejs/node-gyp#2753]
In `npm/cli` we depend on `node-gyp` and would like to make sure the next major version is compatible with `npm` when it comes to `engines.node`.

Previously, `npm` used `^12.13` as the lower base and `node-gyp` used `^12.22` which caused the following issue: https://github.com/npm/cli/issues/4987

`npm@9` was recently released (but is not yet tagged `latest`) with the engines set to `^14.17.0 || ^16.13.0 || >=18.0.0` (see our reasoning here https://github.com/npm/statusboard/issues/519).

Are there plans for a major release soon? If so, has `engines.node` support been discussed?

**Comment by bnb** [comment]
@targos any thoughts on this? 👀

**Comment by ljharb** [comment]
Additionally/separately/related, can v9 lower its bottom threshold to v12.13? That would address https://github.com/npm/cli/pull/5049#issuecomment-1252911275 without the npm team having to do a dozen backports.

**Comment by cclauss** [comment]
Given https://github.com/nodejs/release#release-schedule working to preserve unsupported versions seems like busywork. that is encouraging the community to be lazy about performing upgrades that may increase reliability, performance, and security.

**Comment by ljharb** [comment]
@cclauss the support for a version is irrelevant; there's still a semver violation that's happened, and that needs to be fixed - if node-gyp won't drop its arbitrarily raised support threshold, then npm would be forced to backport almost a dozen packages. The difference in effort seems pretty clear cut to me ¯\\\_(ツ)_/¯

**Comment by cclauss** [comment]
https://github.com/npm/statusboard/issues/519 says that npm is making a breaking change in their next major upgrade.  That sounds like a good idea to me.  My comment is that node-gyp should make a similar breaking change in its next major release.  Making such breaking changes does not mean that dozens of tools need to be backported.  It may however mean that dozens of tools need to be upgraded.

**Comment by ljharb** [comment]
That's totally fine! My comment is just about a patch for the convenience of me, and the npm team, in v9 to lower the threshold. In v10 you can drop whatever you want :-)

**Comment by targos** [comment]
I'm not really involved in `node-gyp`, but I'm a bit confused by this issue. The `engines` field was updated by @wraithgar in https://github.com/nodejs/node-gyp/pull/2601 so I would have thought it was coming with npm 9 in mind.

**Comment by wraithgar** [comment]
#2601 was made for npm 8 so that it could have a much more deduplicated node_modules tree.  This request will do the same for npm 9.

Since this issue was created npm 9 has been tagged as `latest`

**Comment by bnb** [comment]
my apologies for the ping @targos - I saw you were someone with a high number of commits and I know you 😅

**Comment by lukekarrys** [comment]
I opened two PRs to address this issue:

- #2771 which can be released on the `node-gyp@9` release line
- #2770 which would be a major release
