### ISSUE TITLE
Update `make-fetch-happen`

### ISSUE THREAD

**Issue by rtritto** [nodejs/node-gyp#2756]
`make-fetch-happen` dependency needs an update to _v11_ because `@npmcli/move-file` (dependency of  `cacache`) is deprecated.

## Steps to reproduce
- `yarn init -y`
- `yarn set version canary`
- `yarn add node-gyp@9.3.0`

<details><summary>Output</summary>

```console
➤ YN0000: ┌ Resolution step
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings
```

</details>

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/search?q=make-fetch-happen

**Comment by rtritto** [comment]
Node v12 reached end of support (is not maintained) and is deprecated. It should be replaced with Nove v18.
