### ISSUE TITLE
node-gyp rebuild failed

### ISSUE THREAD

**Issue by lisichka999** [nodejs/node-gyp#2763]
when running npm install getting the following error:

gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Sources\sfw_mobile_V_JELLY\node_modules\node-expat
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

* **Node Version**: 14.17.1
* **Platform**: Windows
* **Compiler**: Windows
* **Module**: npm install
</details>

**Comment by cclauss** [comment]
gyp ERR! node-gyp -v v5.1.0
