### ISSUE TITLE
[FEATURE REQ] VSCodium as alternative?

### ISSUE THREAD

**Issue by jajosheni** [nodejs/node-gyp#2765]
node-gyp requires VSCode to be installed.   I instead use VSCodium. Can we make an alternative for that?

**Comment by MRayermannMSFT** [comment]
@jajosheni where do you get the impression VSCode is required? From the README:

> Install the current version of Python from the [Microsoft Store package](https://www.microsoft.com/en-us/p/python-310/9pjpw5ldxlz5).
> 
> Install tools and configuration manually:
> 
> Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload) or [Visual Studio Community](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community) (using the "Desktop development with C++" workload)
> Launch cmd, npm config set msvs_version 2017
> If the above steps didn't work for you, please visit [Microsoft's Node.js Guidelines for Windows](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules) for additional tips.
> 
> To target native ARM64 Node.js on Windows 10 on ARM, add the components "Visual C++ compilers and libraries for ARM64" and "Visual C++ ATL for ARM64".

I only see an optional dependency on using Visual Studio Community to get C++ tooling, with the other option for getting C++ tooling being just downloading them directly.

**Comment by jajosheni** [comment]
Yeah i figured out ,misread it,  forgot to close the ticket
