### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by badeend** [nodejs/node-gyp#277]
Node-gyp refuses to build any native modules I've tried. I'm on Windows 7 64 bit (I'm trying to compile for x86 though, as I don't have the x64 SDK installed). Node-gyp says it's a bug which I need to report, so here I am:

```
E:\project\node-ffi>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.2
gyp info using node@0.10.12 | win32 | ia32
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:980:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:771:
34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Gebruiker\\AppData\\Roaming\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd E:\project\node-ffi
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

**Comment by sajith-dulanjaya** [comment]
Setting environment variable for Python as mentioned by fredpantuzza above worked for me. Thanks fredpantuzza.

PYTHONPATH=C:\Pyhon
PYTHON=%PYTHONPATH%\python.exe

**Comment by sahilthadhani** [comment]
The below worked for me. 

PYTHONPATH=C:\Pyhon
PYTHON=%PYTHONPATH%\python.exe

I also had to add the python in path variable just like path = %PYTHON%

Also, the python version supported is between 2.5 and 3 only.

**Comment by kristofferostlund** [comment]
For me, this was solved by installing Python 2.7.10 (previously had Python 3.5.2 which was referenced by path as `py` and `python`).

I'm running Windows 10, Node v5.0.0

**Comment by debasishmohanty** [comment]
For me this was solved by setting : npm config set python C:\Python27\python.exe

**Comment by JsDevHub** [comment]
## The solution is to update your system python then set it o NPM configuration

**Comment by thany** [comment]
@JsDevHub Can you please also explain how to do that then?

**Comment by Judjohn** [comment]
In my case I was able to run the Gulp task in the Angular CLI, but was getting this issue in Visual Studio 2017.  My solution was to change the order of my paths in Visual Studio. 
Tools > Options > Projects and Solutions > Web Package Management > External Web Tools

once there, re-order your paths such that $(PATH) is in the list right after your node modules as such:

<img width="356" alt="path" src="https://user-images.githubusercontent.com/18578481/31843524-17279aba-b5b9-11e7-902c-4e929ed1899e.PNG">

Hope that helps someone.
