### ISSUE TITLE
when i tried installing yarn

### ISSUE THREAD

**Issue by bdkw** [nodejs/node-gyp#2776]
E:\ev2\simple-NFT-generator>yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
warning " > ts-jest@24.3.0" has incorrect peer dependency "jest@>=24 <25".
[5/5] Building fresh packages...
[1/4] ⡀ canvas
[2/4] ⡀ pngquant-bin
[-/4] ⢀ waiting...
error E:\ev2\simple-NFT-generator\node_modules\canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: E:\ev2\simple-NFT-generator\node_modules\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@18.12.1 | win32 | x64
node-pre-gyp info check checked for "E:\ev2\simple-NFT-generator\node_modules\canvas\build\Release\canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.12.1 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.12.1 | win32 | x64
gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2022
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at E:\ev2\simple-NFT-generator\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ev2\\simple-NFT-generator\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\ev2\\simple-NFT-generator\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=E:\\ev2\\simple-NFT-generator\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108" "--msvs_version=2022"gyp ERR! cwd E:\ev2\simple-NFT-generator\node_modules\canvas
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\ev2\simple-NFT-generator\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\ev2\simple-NFT-generator\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\ev2\simple-NFT-generator\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 --msvs_version=2022' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\ev2\simple-NFT-generator\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Windows_NT 10.0.19045
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ev2\\simple-NFT-generator\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\ev2\simple-NFT-generator\node_modules\canvas
node-pre-gyp ERR! node -v v18.12.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\ev2\simple-NFT-generator\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\ev2\simple-NFT-generator\node_modules\canvas\build\Release\canvas.node --module_

**Comment by cclauss** [comment]
> gyp info using node-gyp@5.1.1

Current is v9.3.0

**Comment by bdkw** [comment]
how to install??i downloaded the source code zip

**Comment by bdkw** [comment]
its still giving the error, even after installing node-gyp

**Comment by cclauss** [comment]
Does https://github.com/nodejs/node-gyp/issues/1546#issuecomment-1356791283 fix this?

**Comment by PenguinTaro** [comment]
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning lerna > @lerna/add > pacote > @npmcli/run-script > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @aries-framework/react-native@0.3.3" has unmet peer dependency "indy-sdk-react-native@^0.3.0".
warning " > @aries-framework/react-native@0.3.3" has unmet peer dependency "react-native-fs@^2.18.0".
warning " > @aries-framework/react-native@0.3.3" has unmet peer dependency "react-native-get-random-values@^1.7.0".
warning "workspace-aggregator-c4e039c2-b4af-4a43-92d3-9984b111869f > @aries-framework/react-native > react-native > metro-react-native-babel-transformer@0.64.0" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-c4e039c2-b4af-4a43-92d3-9984b111869f > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > expo-random@13.0.0" has unmet peer dependency "expo@*".
warning "workspace-aggregator-c4e039c2-b4af-4a43-92d3-9984b111869f > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > react-native-securerandom@0.1.1" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-c4e039c2-b4af-4a43-92d3-9984b111869f > @aries-framework/react-native > react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[5/5] Building fresh packages...
[1/7] ⠁ indy-sdk
[6/7] ⠂ ffi-napi
[3/7] ⠂ @mattrglobal/node-bbs-signatures
[4/7] ⠂ @mattrglobal/node-bbs-signatures
warning Error running install script for optional dependency: "D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments: 
Directory: D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@14.20.0 | win32 | x64
node-pre-gyp info check checked for \"D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\node-bbs-signatures\\native\\index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v83-win32-x64.tar.gz       
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v83-win32-x64.tar.gz  
node-pre-gyp ERR! stack     at D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\node-bbs-signatures\\node_modules\\@mapbox\\node-pre-gyp\\lib\\install.js:67:15
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"D:\\\\sdk\\\\aries-framework-javascript\\\\node_modules\\\\@mattrglobal\\\\node-bbs-signatures\\\\node_modules\\\\@mapbox\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\node-bbs-signatures
node-pre-gyp ERR! node -v v14.20.0
[1/7] ⡀ indy-sdk
[6/7] ⡀ ffi-napi
[3/7] ⡀ @mattrglobal/node-bbs-signatures
[4/7] ⡀ @mattrglobal/node-bbs-signatures
warning Error running install script for optional dependency: "D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\bls12381-key-pair\\node_modules\\@mattrglobal\\node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments:
Directory: D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\bls12381-key-pair\\node_modules\\@mattrglobal\\node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@14.20.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\bls12381-key-pair\\node_modules\\@mattrglobal\\node-bbs-signatures\\native\\index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v83-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\\sdk\\aries-framework-javascript\\node_modules\\node-pre-gyp\\lib\\install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:412:35)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\\sdk\\aries-framework-javascript\\node_modules\\request\\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:267:9)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"D:\\\\sdk\\\\aries-framework-javascript\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd D:\\sdk\\aries-framework-javascript\\node_modules\\@mattrglobal\\bls12381-key-pair\\node_modules\\@mattrglobal\\node-bbs-signatures
node-pre-gyp ERR! node -v v14.20.0
[1/7] ⠂ indy-sdk
[6/7] ⠂ ffi-napi
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
error D:\sdk\aries-framework-javascript\node_modules\indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\sdk\aries-framework-javascript\node_modules\indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@14.20.0 | win32 | x64
gyp info find Python using Python version 3.11.1 found at "C:\Program Files\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\sdk\aries-framework-javascript\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\sdk\\aries-framework-javascript\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sdk\aries-framework-javascript\node_modules\indy-sdk.

I was trying to do the demo for Aries JavaScript Framework but after the yarn install as mentioned in readme file,I get the following error. I tried to set the msvs version too  but I am still not happening.

**Comment by cclauss** [comment]
Closing.  Both `ffi-napi` and `node-pre-gyp` are unmaintained.
