### ISSUE TITLE
Node-gyp error when npm install

### ISSUE THREAD

**Issue by ashishkushwaha22** [nodejs/node-gyp#2785]
npm ERR! path C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Ashis\\Desktop\\dhitva_blog\\dhitva-dev-blog_admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "c:\python27\python.exe" in the PATH
npm ERR! gyp verb `which` succeeded c:\python27\python.exe c:\python27\python.exe
npm ERR! gyp verb check python version `c:\python27\python.exe -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.12.1
npm ERR! gyp verb command install [ '18.12.1' ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: Cannot find module './lib/writer.js'
npm ERR! gyp ERR! stack Require stack:
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\fstream\fstream.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\node_modules\tar\lib\entry.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\node_modules\tar\lib\entry-writer.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\node_modules\tar\lib\pack.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\node_modules\tar\tar.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\lib\install.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\lib\node-gyp.js
npm ERR! gyp ERR! stack - C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-gyp\bin\node-gyp.js
npm ERR! gyp ERR! stack     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR! gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR! gyp ERR! stack     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR! gyp ERR! stack     at Object.<anonymous> (C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\fstream\fstream.js:3:18)
npm ERR! gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR! gyp ERR! stack     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR! gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR! gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ashis\\Desktop\\dhitva_blog\\dhitva-dev-blog_admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ashis\AppData\Local\npm-cache\_logs\2023-01-09T12_06_39_511Z-debug-0.log

**Comment by cclauss** [comment]
The following are deprecated and not supported:
> npm ERR! path C:\Users\Ashis\Desktop\dhitva_blog\dhitva-dev-blog_admin\node_modules\node-sass
> ...
> npm ERR! gyp info using node-gyp@3.8.0
> ...
> npm ERR! gyp verb check python checking for Python executable "c:\python27\python.exe" in the PATH
