### ISSUE TITLE
`npm config set python` no longer supported by npm as of npm v9.0.0

### ISSUE THREAD

**Issue by davidmurdoch** [nodejs/node-gyp#2798]
See https://github.com/npm/cli/issues/6126 for more details

**Comment by amany9000** [comment]
Also facing the same issue, @davidmurdoch did you find any solutions

**Comment by davidmurdoch** [comment]
Downgrading npm works (npm install npm@8 -g). In my case I was able to remove this step from our build process entirely and things just contributed to work perfectly fine 🤷‍♂️.

**Comment by stuartcusackie** [comment]
I'm not sure if I'm having the same issue but Gyp seems to want to use Python 3, no matter what I do:
`gyp info find Python using Python version 3.11.0 found at xxx`

I downgrade to node-gyp@8 but that has the same problem.
Version 7 uses the correct Python version that I have set in my environment:
`npm install node-gyp@7 -g`

**Comment by cclauss** [comment]
What is
> the correct Python version that I have set

**Comment by stuartcusackie** [comment]
> What is
> 
> > the correct Python version that I have set

I mean Windows 11 Environment Variables. I have Python 2.7 higher up the load order than 3.x. Everything else follows this load order but node-gyp ignores it for some reason that I don't understand. Might be an unrelated issue...

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp#configuring-python-dependency

**Comment by lukekarrys** [comment]
The docs here no longer recommend `npm config set python` since [https://github.com/nodejs/node-gyp/pull/2880](https://github.com/nodejs/node-gyp/issues/2798#event-10192848202). There's nothing else to do for this in `node-gyp`, so I'm going to close this.
