### ISSUE TITLE
Win7 MingW

### ISSUE THREAD

**Issue by Silberling** [nodejs/node-gyp#280]
Hi,

I have not the option using Visual Studio but I have the option to use the Win7 SDK or a MingW such as TDM-GCC.

Why is GCC supported on linux platforms but not on Windows?

Thanks

**Comment by bigfatbrowncat** [comment]
Actually, the main problem with Microsoft tools isn't that they are not free (or something), but that they are completely incompatible with all other C/C++ world. No autotools and no correct gnu-style makefile support means most legacy projects are out of scope and some others need very tough effort to build. And there is always "other way" of doing the same things. Yeah, gyp isn't bad inside, but if you would try to build something that relies on something else...

That would be better if mingw-w64 + msys is supported in some way. That will solve many many small and big problems. For example, I have no idea, why Chromium itself couldn't be built with gnu toolchain on Windows.

**Comment by smaudet** [comment]
This is also terribly inconvenient to me. MSVC should not be a pre-req for gyp on windows...I have a working version of nodejs (and the v8 runtime) built with the gcc toolchain.

There isn't a good reason this isn't supported, other than the node-gyp people are lazy.

**Comment by bnoordhuis** [comment]
@smaudet First and only warning: insults get you banned.  Maintain a professional attitude from now on.
