### ISSUE TITLE
npm config set tarball no longer supported by npm as of npm v9.3.1

### ISSUE THREAD

**Issue by matthias-heller** [nodejs/node-gyp#2800]
npm config set tarball not working anymore

Is there any workaround? We were using the tarball option to prevent the download of the node headers from internet as our environment doesn't have an internet access. Simply passing it to node-gyp doesn't work because a sub dependency which we don't have in our hand need node-gyp

Executed command
- npm config set tarball "/node/node-headers.tar.gz" --verbose

npm details:
- node bin location = C:\Program Files\nodejs\node.exe
- node version = v18.14.1
- npm local prefix = C:\Users\User
- npm version = 9.3.1
- cwd = C:\Users\User
- HOME = C:\Users\User
- Run `npm config ls -l` to show all defaults.

Verbose output:
>npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@9.3.1
npm info using node@v18.14.1
npm verb title npm config set tarball
npm verb argv "config" "set" "tarball" "" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\User\AppData\Local\npm-cache\_logs\2023-02-18T09_38_37_771Z-
npm verb logfile C:\Users\User\AppData\Local\npm-cache\_logs\2023-02-18T09_38_37_771Z-debug-0.log
npm info config set "tarball" ""
npm verb stack Error: `tarball` is not a valid npm option
npm verb stack     at Config.set (C:\Program Files\nodejs\node_modules\npm\lib\commands\config.js:158:15)
npm verb stack     at Config.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\config.js:120:22)
npm verb stack     at Config.cmdExec (C:\Program Files\nodejs\node_modules\npm\lib\base-command.js:130:17)
npm verb stack     at Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:154:20)
npm verb stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:134:5)
npm verb cwd C:\Users\User
npm verb Windows_NT 10.0.19044
npm verb node v18.14.1
npm verb npm  v9.3.1
npm ERR! `tarball` is not a valid npm option
npm verb exit 1
npm verb code 1
Usage: npm <command>
(...)
```

**Comment by StefanStojanovic** [comment]
Hello, there is a very similar issue to this one https://github.com/nodejs/node-gyp/issues/2798. In short, the workaround is to downgrade npm. For more details on what caused this behavior and when it started, please visit the see https://github.com/npm/cli/issues/6126#issuecomment-1431758381

**Comment by doteric** [comment]
@matthias-heller AFAIK the new approach is setting the `nodedir` and making sure it contains the node-headers unpacked.
For example:
```
curl -sSL https://nodejs.org/download/release/${NODE_VERSION}/node-${NODE_VERSION}-headers.tar.gz -o /opt/node-headers.tgz
tar -xzvf /opt/node-headers.tgz /opt/node-headers
npm config set nodedir /opt/node-headers
```
Please let me know if this is not the recommended approach.

**Comment by doteric** [comment]
Is there any recommended approach to this? Looks like the `nodedir` option has also been removed as of npm v9.

**Comment by jhested** [comment]
Not sure what the use case is here, but hopefully this is of some help to others.

I managed to get around the issue when using yarn by doing 

```
npm_config_tarball=node-headers.tar.gz yarn install
```

**Comment by sseuzss** [comment]
Try using `export GYP_TARBALL=/node/node-headers.tar.gz` for workaround it

**Comment by SteveMartinUK** [comment]
I had this issue and initially downgraded npm to get the old behaviour to work. The following worked with **npm 9.6.7**

`npm install --tarball=/tmp/node-headers.tgz`

**Comment by lukekarrys** [comment]
As others have posted, the preferred way to set npm configs is put `npm_config_<NAME>=<VALUE>` before your command. This has been updated in the docs.
