### ISSUE TITLE
Node-gyp rebuild not working for node 14.13.0 and npm 6.14.8

### ISSUE THREAD

**Issue by nitesh-1092** [nodejs/node-gyp#2804]
#

Node Version: 14.13.0 and npm version: 6.14.8
Platform: Windows 10
Compiler: Windows
I am using npm install to install frontend part of my web platform in react. I have visual studio 17. Do I need to install Visual studio 15. 
Below I am sharing the output. Is the error with msvs version or node-gyp version. 

![image](https://user-images.githubusercontent.com/21355238/221364269-f7ca68dd-79e1-4bf1-ace4-b682939be388.png)

Please help me I am stuck here .

**Comment by cclauss** [comment]
Will setting the environment variable `%GYP_MSVS_VERSION%` help?  https://github.com/nodejs/node-gyp/issues/2807#issuecomment-1449607865

**Comment by nitesh-1092** [comment]
> @nitesh-1092 the log there says this is running from a Visual Studio Command Prompt for VS2022, node-gyp gets this from the environment variable VCINSTALLDIR. I don't know how the variable got set, but if you clear it then node-gyp should work.

I removed the VCINSTALLDIR variable and found this error
![image](https://user-images.githubusercontent.com/21355238/223322422-5ccb267f-5024-4f30-9d56-cebf739ac2a8.png)

**Comment by cclauss** [comment]
The log above says mode-gyp v5.1.0 instead of v9.3.1.  Please upgrade.  https://github.com/nodejs/node-gyp/releases

**Comment by nitesh-1092** [comment]
> The log above says mode-gyp v5.1.0 instead of v9.3.1. Please upgrade. https://github.com/nodejs/node-gyp/releases

Actually, my node version is 14.13.0 so it supports node-gyp version 5.1.0 and thus if I upgrade it to 9.3.1 it won't work I guess

**Comment by cclauss** [comment]
The log above also says:
> This is a bug in `node-gyp`.

So, please do us all a favor an upgrade node-gyp.

**Comment by nitesh-1092** [comment]
> The log above also says:
> 
> > This is a bug in `node-gyp`.
> 
> So, please do us all a favor and upgrade node-gyp.

I upgraded the node-gyp version globally and also added Microsoft visual studio 15, but I am still getting errors. 
![image](https://user-images.githubusercontent.com/21355238/224348236-1addaeee-5821-4cb7-8e19-d0938e047e2c.png)

**Comment by TylerJaacks** [comment]
I am experience this same issue.

**Comment by cclauss** [comment]
To upgrade from v5 to v9 see https://github.com/nodejs/node-gyp/tree/main/docs

You probably have a [`package-lock.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json) or similar file that specifies the out-of-date version.

**Comment by nitesh-1092** [comment]
I updated visual studio 2015 and updated VS2015 by opening a new C++ file. This took care of all my issues. So I am closing the issue. Thank you to all who helped.
