### ISSUE TITLE
 Could not find any Visual Studio installation to use

### ISSUE THREAD

**Issue by afeichuanqi** [nodejs/node-gyp#2807]
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'D:\electron\js-debugger-yiran\node_modules\win-mouse'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use

Error: node-gyp failed to rebuild 'D:\electron\js-debugger-yiran\node_modules\win-mouse'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find any Visual Studio installation to use

    at NodeGyp.rebuildModule (D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\module-type\node-gyp.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\rebuild.js:149:13)
    at async Promise.all (index 4)
    at async Rebuilder.rebuild (D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\rebuild.js:108:13)     
    at async D:\electron\js-debugger-yiran\node_modules\@electron\rebuild\lib\src\cli.js:158:9

Step by step by step but I just can't find any way. It's amazing. I've been working all day

![image](https://user-images.githubusercontent.com/51334360/221896616-a12e06a5-1a7e-4240-8bf5-6023279bb40a.png)

win10-Enterprise edition
node v19.0.0
npm 8.19.4 （Forcing node-gyp to be used in NPM doesn't help either）
node-gyp  9.1.0（I've tried every version. It's no use）

Does that help?

**Comment by afeichuanqi** [comment]
> @afeichuanqi Please provide the **command typed** and the **full error log**.
> 
> @kapetan Any ideas? https://www.npmjs.com/package/win-mouse https://github.com/kapetan/win-mouse

This is what I do with electric rebuild.

**Comment by afeichuanqi** [comment]
> @afeichuanqi Please provide the **command typed** and the **full error log**.
> 
> @kapetan Any ideas? https://www.npmjs.com/package/win-mouse https://github.com/kapetan/win-mouse

![%LT~2`}79M)NHKP LQEB317](https://user-images.githubusercontent.com/51334360/222049599-57717c5a-8f90-4162-947f-4758546b38cd.png)
![55{W2C_XKVRCLM~7DV53}}L](https://user-images.githubusercontent.com/51334360/222049641-78027b78-d076-4231-8840-b011e81ff585.png)


Can you explain why? When I use the electric to rebuild, msvc_ The version cannot be set. I'm still a novice to Electron.

He actually defaulted to 2015. I guess it was Electron who gave it to MSVS when rebuilding_ The default value of versions? What's the matter? Now I have to download 2015 because I can't understand the relationship between electric and node-gyp

I think the relationship is very complicated.

**Comment by cclauss** [comment]
This could be the difference between `_` and `-` in:
```
npm config set msvs_version 2022
npm config set msvs-version 2022
```
Please run __both__ of these commands and try again.

**Comment by afeichuanqi** [comment]
> This could be the difference between `_` and `-` in:
> 
> ```
> npm config set msvs_version 2022
> npm config set msvs-version 2022
> ```
> 
> Please run **both** of these commands and try again.

I mean, I don't care about set msvs_ Version or set msvs-version is 2022. In findvs, he always takes 2015. You can also see that my terminal writes set msvs_ Version 2022, but I debugger, he is always msvs_ Version 2015 That's the doubtful point

**Comment by kapetan** [comment]
I don't think I can help much. I haven't I tried building win-mouse with Visual Studio 2022 and now I don't have access to a Windows computer.

**Comment by afeichuanqi** [comment]
> 我觉得我帮不了什么忙。我还没有尝试使用 Visual Studio 2022 构建 win-mouse，现在我无法访问 Windows 计算机。



> I don't think I can help much. I haven't I tried building win-mouse with Visual Studio 2022 and now I don't have access to a Windows computer.

![1IWO{5UP`K93_N MT1N4LRB](https://user-images.githubusercontent.com/51334360/222090786-e00b589b-1ae6-46c0-8b9b-9c7cc6954a38.png)
The problem has been solved. I took the version of the environment variabl

**Comment by afeichuanqi** [comment]
> I don't think I can help much. I haven't I tried building win-mouse with Visual Studio 2022 and now I don't have access to a Windows computer.

The problem has been solved. I took the version of the environment variable

![1IWO{5UP`K93_N MT1N4LRB](https://user-images.githubusercontent.com/51334360/222091122-e758540d-59f2-44fa-b1ca-ab6ffb1db322.png)
