### ISSUE TITLE
Why is this thing broken so often when I install?

### ISSUE THREAD

**Issue by alper** [nodejs/node-gyp#2818]
I have no idea what this thing does, I just know that once every so often when I do `yarn install`, I get an error message pertaining to `node-gyp`.

What's going on here? Can this be fixed or deprecated in some way?

**Comment by cclauss** [comment]
If you are unwilling to put the full error log into the issue as requested in the new issue template then no one can help.

**Comment by rvagg** [comment]
yeah, ok, so `node-gyp` shows up in your logs so it's the obvious thing to blame, just know that the vast majority of problems are from a package you're trying to install, `node-gyp` is just attempting to run the compile toolchain to turn the code into a binary and there's a _lot_ of stuff that can go wrong.

> the version of node-gyp you install must be compatible with the version of node you're running

not really - the version of the package you're installing must be compatible with the version of Node you're using. Check your dependencies, see what's being installed and failing, go chase that up, moaning here is either going to get ignored or elicit a response like @cclauss' or the one I'm writing now.
