### ISSUE TITLE
Do not lock conversations while they are ongoing

### ISSUE THREAD

**Issue by kevlarr** [nodejs/node-gyp#2835]
When maintaining open source software, conversations should be encouraged, particularly when people are polite. Give them a chance to respond prior to locking out a conversation (especially when the following advice doesn't clearly answer questions, hence why people keep posting questions about it) if you want to maintain a positive, collaborative community 😊

Open source maintenance is tough and a lot of us truly appreciate what you do. If it seems like we are not paying attention to the text in the "New issue" description, perhaps it means it isn't clear to us and there is a way to improve the messaging.

In this case, yes, I know that "node-sass is dead" from the "New issue" text, but that still doesn't address why there are syntax errors in node-gyp's `.gypi` files which is what I was trying to ask about. 🤷 

>              @kevlarr
> 1. Open a new issue.  --> https://github.com/nodejs/node-gyp/issues/new and click the > `Preview` tab.
> 2. Read ALL the text there.  Hint: You have two different problems with your setup but solutions to both are described.
> 3. Please send all questions about `node-sass` to that team.
> _Originally posted by @cclauss in https://github.com/nodejs/node-gyp/issues/2831#issuecomment-1527039890_

**Comment by kevlarr** [comment]
I'm honestly not sure what to improve, much less how to improve it, since it's unclear why there are issues with `.gypi` files and why they look as if the first half of the file was cut off, eg:

```
❯ head -10 ~/.node-gyp/18.16.0/include/node/common.gypi

e_data_file_flag%': 1
      }]
    ],
  },

  'target_defaults': {
    'default_configuration': 'Release',
    'configurations': {
      'Debug': {
        'variables': {
```

**Comment by kevlarr** [comment]
I'm happy to close this out @cclauss , since I think the `ERR! node-gyp -v <= v9.x.x` tag gives me a lot more to dig into. Opening this was just the only way that I had to respond.

**Comment by cclauss** [comment]
Clicking on the two labels above:
* [`ERR! node-gyp -v <= v9.x.x`](https://github.com/nodejs/node-gyp/labels/ERR%21%20node-gyp%20-v%20%3C%3D%20v9.x.x) 13 open and 111 closed issues.
* [`Node Sass --> Dart Sass`](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22+is%3Aclosed) 62 closed issues.
