### ISSUE TITLE
Request to update node-gyp version

### ISSUE THREAD

**Issue by stali1234** [nodejs/node-gyp#2836]
any information about when an updated version of the npm package, which includes a fix for the security vulnerability in http-cache-semantics, will be released?

![image](https://user-images.githubusercontent.com/60595536/235283732-f5e06a6f-7149-4596-99bf-eb1842bcf214.png)

**Comment by stali1234** [comment]
@rvagg  any udpates on above comments would really helpfull.

Thanks!

**Comment by stali1234** [comment]
@RafaelGSS  @japj  @jkp  @mikeal  any updates on above comments would be reallly helpful .

Thanks!

**Comment by cclauss** [comment]
How about we fix our continuous integration tests _before_ we make a release.

**Comment by stali1234** [comment]
@cclauss  got it 
any idea when will it get release  the new node-gyp version?

**Comment by japj** [comment]
@stali1234 please do not at me. 
I am currently not involved in this project and do not have time & expertise to contribute.

If you want/need a new release I would suggest helping out by contributing in a way that will get the tree in a state to be releasable (e.g. see what integration test are failing and help get those resolved)

**Comment by cclauss** [comment]
Please move this discussion to #2816
