### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by IceMasterT** [nodejs/node-gyp#2839]
Binding File? ive made one wrote all the stuff. same thing. i deleted started over.. same result, spent too much time dickin around . anyone know?
```
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.14.2 | win32 | x64
gyp info find Python using Python version 3.11.3 found at "C:\Users\squii\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.5.33627.172) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\squii\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\squii\\AppData\\Roaming\\nvm\\v16.14.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\squii\\source\\repos\\NFT_Achemizer\\NFT_alch\\node_modules\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\squii\\AppData\\Roaming\\nvm\\v16.14.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\squii\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\squii\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\squii\\AppData\\Roaming\\nvm\\v16.14.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\squii\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\squii\\source\\repos\\NFT_Achemizer\\NFT_alch\\node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\squii\\source\\repos\\NFT_Achemizer\\NFT_alch\\node_modules\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\squii\source\repos\NFT_Achemizer\NFT_alch\node_modules) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\squii\AppData\Roaming\nvm\v16.14.2\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\squii\source\repos\NFT_Achemizer\NFT_alch\node_modules
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
```

**Comment by IceMasterT** [comment]
dang it still no closer

**Comment by cclauss** [comment]
@StefanStojanovic I am not a Windows user.  Do you know of a solution to this problem which is plaguing many Windows users.  It would be awesome if someone could create a GitHub Action that failed in this was so that we could all see how this failure happens.

**Comment by StefanStojanovic** [comment]
Also, I see in the log that CWD is the node_modules directory. Are you sure that's where you expect the `binding.gyp` file?

```
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\squii\source\repos\NFT_Achemizer\NFT_alch\node_modules
```

**Comment by IceMasterT** [comment]
I honestly have no idea.. 1 month ago I didn't even know what github was. I'm still very very new to this. I'm not the sharpest knife but I'm not dull either. just need to run across the stone a few times.

**Comment by StefanStojanovic** [comment]
I understand. What I meant is that unless the `binding.gyp` file you created was in the `C:\Users\squii\source\repos\NFT_Achemizer\NFT_alch\node_modules` directory, this failure was expected. By the look of that path, I'd assume you've created your `binding.gyp` file in `C:\Users\squii\source\repos\NFT_Achemizer\NFT_alch`. In that case, you need to navigate back to that directory (or any other directory which holds the `binding.gyp` file) and run the node-gyp command from there.

In general, [this repo](https://github.com/nodejs/help) is the best place to start when looking for help with things that are Node.js related. For more specific help with node-gyp and how to use it check out the [README.md](https://github.com/nodejs/node-gyp/blob/main/README.md), especially part on [the binding.gyp file](https://github.com/nodejs/node-gyp#the-bindinggyp-file).

On the other hand, if you're certain you've found some issue with a particular part of Node.js (eg. node-gyp), please provide the minimal code that can reproduce the issue, as well as other important information such as versions used, etc., and open an issue in the appropriate repo, so we can try to reproduce it.

I hope you find this information helpful.
