### ISSUE TITLE
I have a error trying to run ibsass on node-gyp@3.8.0

### ISSUE THREAD

**Issue by 99Earlysummer** [nodejs/node-gyp#2841]
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\nodejs\node.exe D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.19.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb download using dist-url https://npm.taobao.org/dist
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:13:12)    
npm ERR! gyp verb `which` failed     at F (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:13:12)    
npm ERR! gyp verb `which` failed     at F (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python D:\Python310\python.EXE
npm ERR! gyp verb check python version `D:\Python310\python.EXE -c "import sys; print "2.7.13
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.19.1
npm ERR! gyp verb command install [ '16.19.1' ]
npm ERR! gyp verb download using dist-url https://npm.taobao.org/dist
npm ERR! gyp verb install input version string "16.19.1"
npm ERR! gyp verb install installing version: 16.19.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.19.1
npm ERR! gyp verb build dir attempting to create "build" dir: D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass\build      
npm ERR! gyp verb build dir "build" dir needed to be created? D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass\build      
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
npm ERR! gyp verb find vs2017   - Using this installation with Windows 10 SDK
npm ERR! gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass\build\config.gypi
npm ERR! (node:16184) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass\config.gypi        
npm ERR! gyp verb common.gypi checking for gypi file: D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass\common.gypi        
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn D:\Python310\python.EXE
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\23518\\.node-gyp\\16.19.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\23518\\.node-gyp\\16.19.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\23518\\.node-gyp\\16.19.1\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb download using dist-url https://npm.taobao.org/dist
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\23518\.node-gyp\16.19.1
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "D:\\nodejs\\node.exe" "D:\\MyProject\\guigu-oa-parent\\zguigu-oa-vue\\guigu-oa-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\MyProject\guigu-oa-parent\zguigu-oa-vue\guigu-oa-web\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.19.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2023-05-10T08_21_56_376Z-debug-0.log

**Comment by cclauss** [comment]
When you opened this pull request the issue template text explained both problems that you are having.  Please read that text.
