### ISSUE TITLE
Can packages build with node-gyp using python3 on build environment run properly on runtime environment having python2? 

### ISSUE THREAD

**Issue by sanketdhoble** [nodejs/node-gyp#2842]
We are testing upgrading to node 16 and have packages like node-rdkafka, aerospike which need node-gyp to build.

I installed python3 on the build environment running node 16 so that node-gyp can install aerospike & kafka.
But our runtime environment doesn't have python3 installed. Will our build still work fine on the runtime environment?

**Comment by cclauss** [comment]
Python 2 died 1,226 days ago on 1/1/2020.  Running Python 2 is no longer safe so we and the Python core team no longer support it.
