### ISSUE TITLE
node-gyp 0.10.1+ fails to download node source with custom node builds

### ISSUE THREAD

**Issue by Jimbly** [nodejs/node-gyp#285]
We have our own branch of node, with a different tag in the version string (e.g. "0.10.6-myver") so that we can definitively know we're running the right node executable.  Up until node-gyp version 0.10.1, this worked fine, node-gyp would download the node source from http://nodejs.org/dist/v0.10.6/node-v0.10.6.tar.gz .  Starting with node-gyp@0.10.1, it tries to download the wrong path, e.g., http://nodejs.org/dist/v0.10.6-myver/node-v0.10.6-myver.tar.gz, which of course fails.  Can node-gyp be adjusted to allow custom node versions again? If not, is there some other way to accomplish this (compile node such that "node --version" tells us something useful, but somehow spoofs node-gyp into getting the right source code, or some other trick?).

**Comment by Trott** [comment]
Should this remain open?

**Comment by Jimbly** [comment]
I definitely don't care anymore, no idea if it's still an issue =).

**Comment by bnoordhuis** [comment]
Various workarounds exist these days so I'll go ahead and close this out.
