### ISSUE TITLE
npm ERR! code 236 npm ERR! git dep preparation failed

### ISSUE THREAD

**Issue by richierockskool** [nodejs/node-gyp#2852]
npm install -g homebridge-inkbird-wifi-gateway
npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/######/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /Users/######/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! npm ERR! dest /Users/######/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/Users/######/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/######/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'
npm ERR! 

Mac OS Monterey 12.6.6

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
(...)
```

</details>

**Comment by cclauss** [comment]
Please provide the full error log.

**Comment by richierockskool** [comment]
Hi Christian,

Here is the full the error when we try and install.

CMD: npm install -g ***@***.***

npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/richjagger/.npm --prefer-offline=false --prefer-online=true --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/richjagger/.npm/_logs/2023-05-20T12_23_56_030Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richjagger/.npm/_logs/2023-05-20T12_23_46_947Z-debug-0.log

Operation failed. Please review log for details.

**Comment by cclauss** [comment]
So, given that the command run was `npm` and the log does not mention `gyp`, why open an issue in this repo?

Did you try the `mkdir` suggestion above?

**Comment by richierockskool** [comment]
Yes, I did with the same result, I just can not get this error solved, I thought this was the route to take. 

Where do I find the definitions or the explanation for "Code 236"?

**Comment by cclauss** [comment]
% `npm doctor`
% `npm explain npm homebridge-inkbird-wifi-gateway`
% `npm explore npm homebridge-inkbird-wifi-gateway`

**Comment by richierockskool** [comment]
I think we are getting very close...

npm doctor comes up with this...What npm -v should I use? and how do you add that $PATH?

Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              not ok  Use npm v9.6.7
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           not ok  Error: Add /Users/richjagger/.npm-packages/bin to your $PATH
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
npm WARN verifyCachedFiles Content garbage-collected: 3 (506357 bytes)
npm WARN verifyCachedFiles Cache issues have been fixed
Verify cache contents               ok      verified 959 tarballs
npm ERR! Some problems found. See above for recommendations.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richjagger/.npm/_logs/2023-05-20T16_02_41_910Z-debug-0.log

**Comment by cclauss** [comment]
`export PATH=~/.npm-packages/bin:$PATH`

**Comment by richierockskool** [comment]
We are on 9.6.6 how do you get 9.6.7?

npm -v                              not ok  Use npm v9.6.7

**Comment by cclauss** [comment]
% `npm upgrade --global npm`

You should try asking questions to https://chat.openai.com

**Comment by richierockskool** [comment]
Sorry, I figured it out, before I could pull the comment...

Here is the latest from the npm doctor...

Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              ok      current: v9.6.7, latest: v9.6.7
node -v                             ok      current: v20.2.0, recommended: v20.2.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           ok      /Users/richjagger/.npm-packages/bin
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
Verify cache contents               ok      verified 1386 tarballs

**Comment by richierockskool** [comment]
And still can not get past this?

npm install -g homebridge-inkbird-wifi-gateway
Debugger attached.
npm WARN tar ENOENT: Cannot cd into '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'
npm WARN tarball tarball data for homebridge-inkbird-wifi-gateway@git+ssh://git@github.com/richierockskool/homebridge-inkbird-wifi-gateway.git#f689c4a594eafe31c826c9c707615a86544ecf16 (null) seems to be corrupted. Trying again.
npm WARN tar ENOENT: Cannot cd into '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'
npm WARN tarball tarball data for homebridge-inkbird-wifi-gateway@git+ssh://git@github.com/richierockskool/homebridge-inkbird-wifi-gateway.git#f689c4a594eafe31c826c9c707615a86544ecf16 (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! enoent ENOENT: Cannot cd into '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by richierockskool** [comment]
I think this is the issue?

undefined@undefined
/Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway

**Comment by richierockskool** [comment]
And everything is back again? after all the updates etc. I do not get it?

CMD: npm install -g homebridge-inkbird-wifi-gateway@1.0.9

npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/richjagger/.npm --prefer-offline=false --prefer-online=true --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'
npm ERR!

**Comment by richierockskool** [comment]
The latest new error:

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'

**Comment by cclauss** [comment]
```
cd /Users/richjagger/.npm-packages/lib/node_modules
homebridge-inkbird-wifi-gateway_junk
touch homebridge-inkbird-wifi-gateway
```

**Comment by richierockskool** [comment]
That did not work.

**Comment by richierockskool** [comment]
After everything it still comes back to this?

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'

**Comment by richierockskool** [comment]
Hi Christian,

no matter what I do I can not get out out of this loop…

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w’

Please assist, or explain why...

Thank you,

**Comment by richierockskool** [comment]
And here is the Doctor…

npm ping                            ok       
npm -v                              ok      current: v9.6.7, latest: v9.6.7
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           ok      /Users/richjagger/.npm-packages/bin
Perms check on cached files         ok       
npm WARN checkFilesPermission should be owner of /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build
npm ERR! checkFilesPermission Missing permissions on /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build (expect: readable, writable)
Perms check on local node_modules   not ok  Check the permissions of files in /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules (should be owned by current user)
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
Verify cache contents               ok      verified 1351 tarballs
npm ERR! Some problems found. See above for recommendations.

**Comment by cclauss** [comment]
Go to https://chat.openai.com and ask:
* [ ] `On Windows, how can I set richjagger to be the owner of the directory /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules and all files inside that directory?`
* [ ] `On Windows, how can I set the directory /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build to be readable and writable?`

**Comment by richierockskool** [comment]
I am on a mac, but I will try, I could not get into that web site when I tried last time.

**Comment by cclauss** [comment]
% `chown --help`
% `chown -R richjagger /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules`

% `chmod --help`
% `chmod -R +rw /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build`

**Comment by richierockskool** [comment]
Hi Christian,

That did not do it either, still the error messages.



> On May 25, 2023, at 8:29 AM, Christian Clauss ***@***.***> wrote:
> 
> 
> % chown --help
> 
chown: illegal option -- -
usage: chown [-fhnvx] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhnvx] [-R [-H | -L | -P]] :group file ...
> % chown -R richjagger /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules
> 
> 
chown -R richjagger /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/gyp-mac-tool: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Makefile: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/fse.target.mk: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/.target.mk: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/obj.target/fse/fsevents.o: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/obj.target/fse: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/obj.target: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.node: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release/obj.target/fse/fsevents.o.d: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release/obj.target/fse: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release/obj.target: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release/.node.d: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release/fse.node.d: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps/Release: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/.deps: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release/fse.node: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/Release: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/config.gypi: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/binding.Makefile: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/node_gyp_bins/python3: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build/node_gyp_bins: Operation not permitted
chown: /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build: Operation not permitted
> % chmod --help
> 
chmod: illegal option -- -
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...

**Comment by cclauss** [comment]
% chown help
% sudo chown -R richjagger /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules

% chmod help
% sudo chmod -R +rw /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build

**Comment by richierockskool** [comment]
Still the same error loop

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'

**Comment by cclauss** [comment]
% `npm doctor`

**Comment by richierockskool** [comment]
Npm Doctor gives me this:

Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              not ok  Use npm v9.6.7
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           not ok  Error: Add /Users/richjagger/.npm-packages/bin to your $PATH
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
Verify cache contents               ok      verified 1394 tarballs
npm ERR! Some problems found. See above for recommendations.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richjagger/.npm/_logs/2023-05-25T14_18_30_416Z-debug-0.log

Until I run 
export PATH=~/.npm-packages/bin:$PATH

Then Npm Doctor gives me this:

Check                               Value   Recommendation/Notes
npm ping                            ok       
npm -v                              ok      current: v9.6.7, latest: v9.6.7
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/bin/git
global bin folder in PATH           ok      /Users/richjagger/.npm-packages/bin
Perms check on cached files         ok       
Perms check on local node_modules   ok       
Perms check on global node_modules  ok       
Perms check on local bin folder     ok       
Perms check on global bin folder    ok       
Verify cache contents               ok      verified 1394 tarballs

**Comment by richierockskool** [comment]
> Go to https://chat.openai.com and ask these two questions:
> 
> * [ ]  `On Windows, how can I set richjagger to be the owner of the directory /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules and all files inside that directory?`
> * [ ]  `On Windows, how can I set the directory /Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/node_modules/.nodemon-xd0s1R7V/node_modules/fsevents/build to be readable and writable?`

Openai will not let me open an account?

**Comment by richierockskool** [comment]
Hi Christian,

Still the same after everything we tried, I change many things, but still no joy. And, I can not even delete the Plugin from Homebridge…But, crazy enough it still loads..

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w’

If you can think of anything else to try,

Thank you,

Rich

**Comment by cclauss** [comment]
Let's continue this conversation at richierockskool/homebridge-inkbird-wifi-gateway#18
