### ISSUE TITLE
http-cache-semantics vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by Wolfie432** [nodejs/node-gyp#2856]
Related to #2849 
Related to #2850 

http-cache-semantics vulnerable to Regular Expression Denial of Service:
Node-gyp v9.3.1 uses "make-fetch-happen": "^10.0.3" which in turn uses "http-cache-semantics": "4.1.0" we need  "http-cache-semantics": "^4.1.1" to fix  http-cache-semantics vulnerable to Regular Expression Denial of Service

**Comment by lukekarrys** [comment]
`make-fetch-happen@10` uses `http-cache-semantics@^4.1.0` so updating your dependencies will update to a non-vulnerable version of that.
