### ISSUE TITLE
9.4.0 should've been semver-major

### ISSUE THREAD

**Issue by blattersturm** [nodejs/node-gyp#2873]
We're stuck running on Node.js 12.x due to [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi/issues) being nondeterministically [broken](https://github.com/node-ffi-napi/node-ffi-napi/issues/97) on any release above 14.x.

In this project, we install `node-gyp@9`, but since 9.4.0 bumped to `make-fetch-happen@11` (via 02480f6b6894a6bb81dd3e1365bc4df6d5336f7c) which has a semver-major change that propagates downward, installing fails as such:

```
error make-fetch-happen@11.1.1: The engine "node" is incompatible with this module. Expected version "^14.17.0 || ^16.13.0 || >=18.0.0". Got "12.22.12"
error Found incompatible module.
```

From the [make-fetch-happen changelog](https://github.com/npm/make-fetch-happen/blob/v11.0.3/CHANGELOG.md#1100-2022-10-13):

> ### ⚠️ BREAKING CHANGES
>
> * `make-fetch-happen` is now compatible with the following semver range for node: `^14.17.0 || ^16.13.0 || >=18.0.0`

Another failing in this amazing 'semver' system? Probably.

**Comment by lukekarrys** [comment]
`v9.4.1` has been released which reverts the dependency changes that caused this issue. Those changes will be released again as `v10.0.0` with the changelog outlining the newly supported Node versions.
