### ISSUE TITLE
Drop `npm config set` support

### ISSUE THREAD

**Issue by lukekarrys** [nodejs/node-gyp#2879]
npm 9 no longer supports setting arbitrary config items. This should be removed from the docs, with the other methods of setting items such as environs being the ideal solution.

This is a breaking change so it is good timing to make this change along with the breaking engine changes that already landed.

Ref #2798 #2800

**Comment by cclauss** [comment]
Is removing things that no longer work from the docs a breaking change?

Perhaps doc edits could be separated from _other methods of setting items_.

**Comment by richardlau** [comment]
FWIW the relevant code is:
https://github.com/nodejs/node-gyp/blob/53c99ae573bd5a5435e843b7de6b2e684f4de4d3/lib/node-gyp.js#L134-L156

Removing that would be semver major for node-gyp. While npm 9 may no longer be setting `npm_config_` prefixed environment variables for arbitrary config items, what about the other package managers? Or in other words, node-gyp doesn't care _who_ sets them, but will process any `npm_config_` prefixed environment variables.

We could, for example keep the above code and this documentation https://github.com/nodejs/node-gyp/blob/53c99ae573bd5a5435e843b7de6b2e684f4de4d3/README.md?plain=1#L224-L241 as manually setting such environment variables still works but drop https://github.com/nodejs/node-gyp/blob/53c99ae573bd5a5435e843b7de6b2e684f4de4d3/README.md?plain=1#L243-L254 or amend it to say it no longer works for npm 9 onwards.

**Comment by lukekarrys** [comment]
Good points @cclauss and @richardlau. Here's what I'm thinking now:

- Change `npm config set python X` to `npm_config_python=X` in method 2
- Possibly add a note to the bottom of the section saying in npm <= 8 you can run `npm config set python` as well

Then this is no longer a breaking change.

My main goal is to not have `npm config set python` as part of the docs that is easily scannable by users since the error message for this in npm is pretty generic and doesn't offer guidance to the user that is specific to `node-gyp` resulting in a lot of confusion.
