### ISSUE TITLE
issue with npm 9.x.x: `python` is not a valid npm option

### ISSUE THREAD

**Issue by madanbisht** [nodejs/node-gyp#2881]
We are using node: v18.14.1 which comes with npm: 9.3.1 and we are facing below issue while setting python in npm. We found that this is deprecated from npm version 9.x.x onwards.

**Can anybody suggest how to set python, msvs_version etc with npm 9.x.x?**

```
% > npm config set python /usr/local/bin/python
npm ERR! `python` is not a valid npm option

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-07-06T08_33_30_694Z-debug-0.log

 
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp#configuring-python-dependency

Please try 3.

If 3. does not work, please try 4.

Please create a pull request to remove 2.

**Comment by madanbisht** [comment]
Thanks @cclauss for your response, 
We tried and 4 is working well with `python` but its not working with `msvs_version`.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/labels/Visual%20Studio%20not%20found

**Comment by madanbisht** [comment]
Thank you
For now we are adding the keys on npm config file.

**Comment by Atzelon121** [comment]
THANK YOUUU
