### ISSUE TITLE
C not found while loading dependencies of binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by chenlogin** [nodejs/node-gyp#2911]
windows ，node18.17.1，npm9.6.7，node-gyp9.4.0，执行node-gyp rebuild报错，C not found (cwd: C:\workspace\CppEnhancer) while loading dependencies of binding.gyp while trying to load binding.gyp
![企业微信截图_16970058967162](https://github.com/nodejs/node-gyp/assets/7815279/b9a06bf8-3604-4902-83bf-ab6114e4af01)

**Comment by StefanStojanovic** [comment]
Hey @chenlogin can you run `node-gyp` with `--verbose` option and paste the output as a comment here? That'll give us more information to go on. Thanks in advance.

**Comment by StefanStojanovic** [comment]
I intend to close this issue if no further information is provided by Thursday. By just looking at what we have in the issue, seems like build tools are not installed. In addition, I don't remember any similar issues to this one (with loading dependencies), which also points in the direction of the bad setup.
