### ISSUE TITLE
gyp http 404 https://nodejs.org/download/release/v18.0.0/win-x86/node.lib

### ISSUE THREAD

**Issue by Zzhiter** [nodejs/node-gyp#2913]
when I run npm install, it seems that the URL **https://nodejs.org/download/release/v18.0.0/win-x86/node.lib** should be **https://nodejs.org/download/release/v18.0.0/win-x64/node.lib**, because the first URL is not found. what can I do?

npm ERR! gyp http 404 https://nodejs.org/download/release/v18.0.0/win-x86/node.lib
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp verb command remove [ '18.0.0' ]
npm ERR! gyp verb remove using node-gyp dir: C:\Users\zz\.node-gyp
npm ERR! gyp verb remove removing target version: 18.0.0
npm ERR! gyp verb remove removing development files for version: 18.0.0
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.0.0/win-x64/node.lib
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
npm ERR! gyp ERR! stack     at Request.<anonymous> (D:\Downloads\chrome-extension-boilerplate-react-3.0.0\chrome-extension-boilerplate-react-3.0.0\node_modules\node-gyp\lib\install.js:344:20)
npm ERR! gyp ERR! stack     at Request.emit (node:events:539:35)
npm ERR! gyp ERR! stack     at Request.onRequestResponse (D:\Downloads\chrome-extension-boilerplate-react-3.0.0\chrome-extension-boilerplate-react-3.0.0\node_modules\request\request.js:1059:10)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
npm ERR! gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR! gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:494:22)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at addChunk (node:internal/streams/readable:324:12)
npm ERR! gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "D:\\nodejs\\node.exe" "D:\\Downloads\\chrome-extension-boilerplate-react-3.0.0\\chrome-extension-boilerplate-react-3.0.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Downloads\chrome-extension-boilerplate-react-3.0.0\chrome-extension-boilerplate-react-3.0.0\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.0.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zz\AppData\Local\npm-cache\_logs\2023-10-15T03_12_20_593Z-debug-0.log

**Comment by cclauss** [comment]
> npm ERR! gyp ERR! node-gyp -v v3.8.0

Please!  https://github.com/nodejs/node-gyp/releases
