### ISSUE TITLE
node-gyp is updated to v.9.3.0 according to the instruction but npm still uses node-gyp@3.8.0

### ISSUE THREAD

**Issue by Ludmila06Marques** [nodejs/node-gyp#2916]
I'm trying to install the dependencies of my project but it always gives an error in node-sass. 
My python version is 3.7.0, node is v20.9.0, node-gyp v9.4.0. I do not know what else to do !!! I leave here the error logs and my package json

npm ERR! code 1
npm ERR! path C:\Users\insti\OneDrive\Área de Trabalho\DEVELOP\standard-works-1\frontend-pro\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\insti\OneDrive\Área de Trabalho\DEVELOP\standard-works-1\frontend-pro\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\insti\\OneDrive\\Área de Trabalho\\DEVELOP\\standard-works-1\\frontend-pro\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.9.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Users\insti\AppData\Local\Programs\Python\Python37-32\python.exe" in the PATH   
npm ERR! gyp verb `which` succeeded C:\Users\insti\AppData\Local\Programs\Python\Python37-32\python.exe C:\Users\insti\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\insti\AppData\Local\Programs\Python\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                                ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\insti\\OneDrive\\Área de Trabalho\\DEVELOP\\standard-works-1\\frontend-pro\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\insti\OneDrive\Área de Trabalho\DEVELOP\standard-works-1\frontend-pro\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: C:\Users\insti\AppData\Local\npm-cache\_logs\2023-10-26T16_12_26_779Z-debug-0.log
PS C:\Users\insti\OneDrive\Área de Trabalho\DEVELOP\standard-works-1\frontend-pro>

>  "dependencies": {
    "@date-io/date-fns": "^2.17.0",
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@grapecity/spread-excelio": "15.2.0",
    "@grapecity/spread-sheets": "15.2.0",
    "@grapecity/spread-sheets-barcode": "15.2.0",
    "@grapecity/spread-sheets-charts": "15.2.0",
    "@grapecity/spread-sheets-designer": "15.2.0",
    "@grapecity/spread-sheets-designer-react": "15.2.0",
    "@grapecity/spread-sheets-designer-resources-en": "15.2.0",
    "@grapecity/spread-sheets-languagepackages": "15.2.0",
    "@grapecity/spread-sheets-pdf": "15.2.0",
    "@grapecity/spread-sheets-pivot-addon": "15.2.0",
    "@grapecity/spread-sheets-print": "15.2.0",
    "@grapecity/spread-sheets-react": "15.2.0",
    "@grapecity/spread-sheets-resources-ja": "15.2.0",
    "@grapecity/spread-sheets-resources-ko": "15.2.0",
    "@grapecity/spread-sheets-resources-zh": "15.2.0",
    "@grapecity/spread-sheets-shapes": "15.2.0",
    "@grapecity/spread-sheets-tablesheet": "15.2.0",
    "@material-ui/core": "^4.12.4",
    "@material-ui/pickers": "^3.3.10",
    "@mui/icons-material": "^5.14.11",
    "@mui/material": "^5.14.11",
    "@types/classnames": "^2.2.6",
    "@types/core-js": "^2.5.5",
    "@types/plotly.js": "^1.54.22",
    "@types/react-data-grid": "^4.0.6",
    "@types/react-loader": "^2.4.5",
    "@types/react-plotly.js": "^2.5.1",
    "@types/react-resize-detector": "^6.1.0",
    "@types/react-select": "^4.0.18",
    "@types/react-slick": "^0.23.10",
    "@types/react-transition-group": "^4.4.6",
    "@types/react-webcam": "^3.0.0",
    "@types/react-widgets": "^4.4.7",
    "@types/uuid": "^8.3.1",
    "@wojtekmaj/react-datetimerange-picker": "^5.4.2",
    "@zxing/library": "^0.20.0",
    "ag-grid-community": "^27.2.1",
    "ag-grid-enterprise": "^27.2.1",
    "ag-grid-react": "^27.2.1",
    "animate-sass": "^0.8.2",
    "apexcharts": "^3.36.3",
    "axios": "^0.21.1",
    "babel-standalone": "^6.26.0",
    "bootstrap": "^4.6.0",
    "bootstrap-icons": "^1.11.1",
    "capture-frame": "^4.0.0",
    "classnames": "^2.2.6",
    "colorjs.io": "^0.4.3",
    "core-js": "^3.30.2",
    "date-fns": "^2.30.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-prettier": "^4.2.1",
    "ffmpeg-webworker": "^1.3.0",
    "file-extension": "^4.0.5",
    "firebase": "^8.2.7",
    "firebase-tools": "^11.21.0",
    "frappe-gantt": "^0.6.1",
    "google-map-react": "^2.2.1",
    "history": "^5.3.0",
    "html2canvas": "^1.4.1",
    "jquery": "^3.4.1",
    "leaflet": "^1.9.4",
    "loaders.css": "^0.1.2",
    "lodash": "^4.17.21",
    "material-ui": "^0.20.2",
    "mathjs": "^11.9.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.43",
    "mongoose": "^7.1.1",
    "pe7-icon": "^1.0.4",
    "plotly.js": "^2.7.0",
    "postcss": "^8.4.21",
    "prismjs": "^1.28.0",
    "prop-types": "^15.8.1",
    "rc-collapse": "^3.5.1",
    "rc-menu": "^9.8.1",
    "react": "17.0.2",
    "react-apexcharts": "^1.3.3",
    "react-app-polyfill": "^1.0.4",
    "react-beautiful-dnd": "^13.1.1",
    "react-bootstrap": "^1.6.0",
    "react-burgers": "^1.3.0",
    "react-calculatxr": "^1.0.10",
    "react-circle": "^1.1.1",
    "react-clock": "^4.2.0",
    "react-color": "^2.19.3",
    "react-color-palette": "^6.2.0",
    "react-contextmenu": "^2.14.0",
    "react-countup": "^4.2.2",
    "react-data-grid": "5.0.1",
    "react-data-grid-addons": "5.0.1",
    "react-data-table-component": "^7.0.0-rc2",
    "react-datepicker": "^4.11.0",
    "react-dom": "17.0.2",
    "react-drag-drop-files": "^2.3.7",
    "react-horizontal-timeline": "^1.5.3",
    "react-icons": "^3.8.0",
    "react-image-gallery": "^1.2.12",
    "react-images-uploading": "^3.1.6",
    "react-instagram-embed": "^3.0.0",
    "react-leaflet": "^4.2.1",
    "react-loader-advanced": "^1.7.1",
    "react-loader-spinner": "^6.0.0-0",
    "react-loaders": "^3.0.1",
    "react-localization": "^1.0.17",
    "react-multilevel-dropdown": "^2.0.0",
    "react-perfect-scrollbar": "^1.5.3",
    "react-plotly.js": "^2.5.1",
    "react-recurrence": "^0.3.0",
    "react-redux": "^7.1.1",
    "react-reflex": "^4.0.12",
    "react-resize-detector": "^7.1.2",
    "react-router": "^6.11.2",
    "react-router-dom": "^6.11.2",
    "react-scripts": "^5.0.1",
    "react-select": "^4.3.1",
    "react-simple-code-editor": "^0.11.2",
    "react-simple-image-viewer": "^1.2.2",
    "react-slick": "^0.29.0",
    "react-switch": "^4.1.0",
    "react-table": "^6.10.3",
    "react-tabs": "^3.2.3",
    "react-textarea-autosize": "^7.1.0",
    "react-to-print": "^2.13.0",
    "react-toastify": "^9.1.3",
    "react-transition-group": "^4.4.5",
    "react-trello": "^2.2.11",
    "react-ts-tradingview-widgets": "^1.0.14",
    "react-twitter-widgets": "^1.11.0",
    "react-use-websocket": "^3.0.0",
    "react-webcam": "^7.1.1",
    "react-widgets": "^4.4.11",
    "react-youtube": "^10.1.0",
    "reactflow": "^11.7.4",
    "reactstrap": "^8.0.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "sass": "^1.57.1",
    "simple-react-calculator": "^0.4.1",
    "stream": "0.0.2",
    "stream-browserify": "^3.0.0",
    "styled-components": "^4.4.0",
    "sweetalert2": "^10.16.6",
    "typescript": "^4.4.2",
    "use-sound": "^4.0.1",
    "uuid": "^8.3.2",
    "video-react": "^0.14.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts --max_old_space_size=12288 build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint src . --ext .ts,.tsx",
    "lint:fix": "npm run lint -- --fix",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^6.5.16",
    "@storybook/testing-library": "^0.0.13",
    "@types/frappe-gantt": "^0.6.1",
    "@types/google-map-react": "^2.1.7",
    "@types/jquery": "^3.5.14",
    "@types/leaflet": "^1.9.3",
    "@types/lodash": "^4.14.191",
    "@types/prismjs": "^1.26.0",
    "@types/react": "^18.0.32",
    "@types/react-beautiful-dnd": "^13.1.2",
    "@types/react-csv": "^1.1.2",
    "@types/react-datepicker": "^4.11.0",
    "@types/react-dom": "^18.0.11",
    "@types/react-image-gallery": "^1.2.0",
    "@types/react-router": "^5.1.18",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-tabs": "^2.3.4",
    "@types/wojtekmaj__react-datetimerange-picker": "^3.0.2",
    "@typescript-eslint/eslint-plugin": "^4.31.0",
    "@typescript-eslint/parser": "^4.33.0",
    "babel-loader": "^8.3.0",
    "css-loader": "5.2.6",
    "eslint": "^7.32.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-typescript": "^14.0.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-jest": "^24.4.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "install-peerdeps": "^3.0.3",
    "prettier": "^2.8.8",
    "react-csv": "^2.2.2",
    "react-refresh": "^0.14.0",
    "sass-loader": "10.1.1",
    "style-loader": "2.0.0",
    "node-gyp": "^9.3.0"
  }
}

**Comment by cclauss** [comment]
The text that you deleted when you created this issue said:
> Requests for help with [`node-sass` are very common](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22). Please be aware that this package is deprecated, you should seek alternatives and avoid opening new issues about it here.
