### ISSUE TITLE
gyp ERR! UNCAUGHT EXCEPTION 

### ISSUE THREAD

**Issue by ZacB** [nodejs/node-gyp#293]
I'm trying to run this on a Raspberry Pi. Any ideas?

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Invalid Version: 2.7.3rc2
gyp ERR! stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:257:11)
gyp ERR! stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:410:10)
gyp ERR! stack     at Function.gte (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:459:10)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:104:18
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:635:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:735:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:948:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Linux 3.1.9adafruit+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/firmata/node_modules/serialport
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues
unbuild serialport@1.1.1
unbuild firmata@0.2.8
npm ERR! weird error 7
npm ERR! not ok code 0

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.
