### ISSUE TITLE
Conflicting Node.js information in 10.0.0 release notes

### ISSUE THREAD

**Issue by MikeMcC399** [nodejs/node-gyp#2937]
[node-gyp v10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) contains conflicting information about support of Node.js `14` and the minimum version of Node.js `16.x` that is supported:

## BREAKING CHANGES

- node-gyp now supports node ^16.14.0 || >=18.0.0
- update engines.node to ^14.17.0 || ^16.13.0 || >=18.0.0

## Features

- drop node 14 support ([#2929](https://www.github.com/nodejs/node-gyp/issues/2929)) ([1b3bd34](https://www.github.com/nodejs/node-gyp/commit/1b3bd341b40f384988d03207ce8187e93ba609bc))

---

https://github.com/nodejs/node-gyp/blob/4c302cad0eba96f3dfc2bb3d8908c3b1ad48bf43/package.json#L36-L38

---

## Suggestion

Remove the incorrect line
 - update engines.node to ^14.17.0 || ^16.13.0 || >=18.0.0

from the release notes [node-gyp v10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) .

**Comment by lukekarrys** [comment]
Good catch, that's because v10 did include two separate commits changing the node version since v10 was in development for awhile.

@MikeMcC399 Do you want to open a PR removing the incorrect version from the changelog?

**Comment by MikeMcC399** [comment]
@lukekarrys 

> Do you want to open a PR removing the incorrect version from the changelog?

I will submit a PR for the [CHANGELOG](https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md). 

Somebody with write privileges to the repo would however need to edit the release text on [node-gyp v10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) separately to complete the resolution of this issue I guess.

**Comment by lukekarrys** [comment]
> Somebody with write privileges to the repo would however need to edit the release text on [node-gyp v10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) separately to complete the resolution of this issue I guess.

Thanks for the reminder there, I went ahead and removed that line in the release.

**Comment by MikeMcC399** [comment]
Thanks @lukekarrys !

- The original issue I reported is now resolved. The related issue in the [CHANGELOG](https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md) is covered by PR #2938.
