### ISSUE TITLE
node-gyp crashing when using node 20.9.0 and works on 18.17.1

### ISSUE THREAD

**Issue by galpodlipnik1** [nodejs/node-gyp#2940]
when running npm i diskusage
```
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command C:\\Program Files\\nodejs\\node.exe C:\\Users\\Uporabnik\\AppData\\Roaming\\nvm\\v20.9.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js rebuild
npm ERR! gyp ERR! cwd C:\Users\Uporabnik\Desktop\AG Studio\Admin_Dashboard\server\node_modules\diskusage
npm ERR! gyp ERR! node -v v20.9.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
```

**Comment by cclauss** [comment]
Is that the full error log or just a portion of it?

**Comment by Apollon77** [comment]
@galpodlipnik1 update npm to at least 10.2.2 or such ... this is https://github.com/nodejs/node-gyp/issues/2869

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it has been stale for some time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
