### ISSUE TITLE
TypeError: Cannot read property 'pipeline' of undefined

### ISSUE THREAD

**Issue by pagspiey** [nodejs/node-gyp#2947]
* **Node Version**:  Node: 14.15.1, NPM:16.14.8
* **Platform**: Windows
* **Compiler**: MsBuild that came with Visual Studio 2022
* **Module**: Keytar@7.9.0

<details>
<summary>So, previously I was having an issue, where node-gyp couldn't find the version of Visual Studio being used. Turned out, that node-gyp version that came with my version of NPM did not support Visual Studio 2022. So I upgraded my version to the latest node-gyp(as per https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md). After upgrading, I was able to get by the Visual Studio version error, but then got an error "TypeError: Cannot read property 'pipeline' of undefined. It seems to have an issue with this line in install.js:

`const { Transform, promises: { pipeline } } = require('stream')`
</summary>

```
gyp ERR! configure error 
gyp ERR! stack TypeError: Cannot read property 'pipeline' of undefined
gyp ERR! stack at Object.<anonymous> (C:\Users\<user>\AppData\Roaming\nvm\v14.15.1\node_modules\node-gyp\lib\install.js:8:32)
gyp ERR! stack at Module._compile (internal/modules/cjs/loader.js:1063:30)
gyp ERR! stack at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
gyp ERR! stack at Module.load (internal/modules/cjs/loader.js:928:32)
gyp ERR! stack at Function.Module._load (internal/modules/cjs/loader.js:769:14)
gyp ERR! stack at Module.require (internal/modules/cjs/loader.js:952:19)
gyp ERR! stack at require (internal/modules/cjs/helpers.js:88:18)
gyp ERR! stack at Object.acc.<computed> [as install] (C:\Users\<user>\AppData\Roaming\nvm\v14.15.1\node_modules\node-gyp\lib\node-gyp.js:80:32)
gyp ERR! stack at getNodeDir (C:\Users\<user>\AppData\Roaming\nvm\v14.15.1\node_modules\node-gyp\lib\configure.js:53:26)
gyp ERR! stack at configure (C:\Users\<user>\AppData\Roaming\nvm\v14.15.1\node_modules\node-gyp\lib\configure.js:24:10)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\<path>\node_modules\keytar
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.9.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.9.0 build script.
```

</details>

**Comment by cclauss** [comment]
Please provide the FULL error log.

**Comment by StefanStojanovic** [comment]
@pagspiey  I think this is the issue: the node-gyp you are using is the latest one, but Node.js is very old (not even supported anymore). In the [node-gyp v10 release notes](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) it even mentions that Node v14 is no longer supported. Can you please try updating the Node.js you are using and retrying?
```
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v10.0.1
```

**Comment by StefanStojanovic** [comment]
I'm closing this, since there's been no feedback, plus the behavior is already documented in the release notes.
