### ISSUE TITLE
http GET http://mirrors.sh.ctriptravel.com/nodejs.org/dist/v16.14.0/node-v16.14.0-headers.tar.gz fails

### ISSUE THREAD

**Issue by Hao-yiwen** [nodejs/node-gyp#2951]
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET http://mirrors.sh.ctriptravel.com/nodejs.org/dist/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp http 403 http://mirrors.sh.ctriptravel.com/nodejs.org/dist/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: 403 response downloading http://mirrors.sh.ctriptravel.com/nodejs.org/dist/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp ERR! stack     at go (/Users/yw.hao/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:153:17)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR! gyp ERR! stack     at async install (/Users/yw.hao/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
npm ERR! gyp ERR! System Darwin 23.1.0
npm ERR! gyp ERR! command "/Users/yw.hao/.nvm/versions/node/v16.14.0/bin/node" "/Users/yw.hao/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/yw.hao/.nvm/versions/node/v16.14.0/lib/node_modules/@ctrip/xtaro-cli/node_modules/fibers
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by Hao-yiwen** [comment]
what should I do?

**Comment by cclauss** [comment]
What command was typed?
Please provide the full error log.

**Comment by cclauss** [comment]
http://mirrors.sh.ctriptravel.com does not exist.
