### ISSUE TITLE
Windows_NT 10.0.19045

### ISSUE THREAD

**Issue by nhdlam05** [nodejs/node-gyp#2953]
can't npm install when use node v14 and Visual Studio 2022, node-gyp 9.4.0

> yp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Admin\AppData\Roaming\nvm\v14.21.3\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sleek-bitbucket\sleek-back\node_modules\mmmagic
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok

**Comment by StefanStojanovic** [comment]
Node v14 is no longer supported, The lowest version that is currently supported is v18.

**Comment by cclauss** [comment]
`README.md` must be updated to reflect that:
> Multiple target versions of Node.js are supported (i.e. 0.8, ..., 4, 5, 6, etc.), regardless of what version of Node.js is actually installed on your system (node-gyp downloads the necessary development files or headers for the target version).

**Comment by StefanStojanovic** [comment]
Since the docs PR landed and there was no other feedback, I'm closing this issue.
