### ISSUE TITLE
Error: You must run node-gyp configure first!

### ISSUE THREAD

**Issue by andy0983** [nodejs/node-gyp#2954]
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack at loadConfigGypi (/usr/local/lib/node_modules/node-gyp/lib/build.js:48:15)
gyp ERR! stack at async build (/usr/local/lib/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 6.1.21-v8+
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/dietpi
gyp ERR! node -v v21.4.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
help

**Comment by cclauss** [comment]
# Error: You must run node-gyp configure first!
