### ISSUE TITLE
Why did node choose the version of node gyp

### ISSUE THREAD

**Issue by abcln** [nodejs/node-gyp#2969]
node-gyp configure && node-gyp build

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.20.1 | win32 | x64

在win10中，我安装node-gyp是 5.1.0。
node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@5.1.0  D:\Users\Administrator\AppData\Roaming\nvm\v16.20.1\node_modules\node-gyp
node@16.20.1
但是，他给我的是 9.1.0。为什么。npm install 是根据什么选择 node-gyp的版本。

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md
