### ISSUE TITLE
I can't find "my_node_addon" on Windows 10.

### ISSUE THREAD

**Issue by HadifRoslan** [nodejs/node-gyp#2977]
How to Use
To compile your native addon first go to its root directory:

"cd my_node_addon"

As the instructions stated above, I need to change my directory to "my_node_addon".  But when I input the command,
"The system cannot find the path specified."
<img width="458" alt="image" src="https://github.com/nodejs/node-gyp/assets/159116397/8ef92cb6-6796-4243-9c06-aead9da7d015">

**Comment by StefanStojanovic** [comment]
Your current directory is `C:\Users\USER` I assume there is no `my_node_addon` directory in there. Make sure you navigate to the correct directory.

As this is not a `node-gyp` issue I'll close it. If you encounter some problem with node-gyp, feel free to open a new issue. Thanks.
