### ISSUE TITLE
Issues after installing python on mac

### ISSUE THREAD

**Issue by eberhapa** [nodejs/node-gyp#2979]
Hi,

I didn't know that mac has python preinstalled and downloaded the installer from the python website.
I'm not able to run npm install anymore because I get a python error. 

If I now check my python installations I get 3 different installs:
- /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 (3.12)
- /usr/bin/python3 (3.9.6)
- /usr/local/bin/python3 (3.12)

I removed the /usr/local/bin version because that was the one I installed but I'm still not able to run npm install anymore without exporting the PYTHON path in .zshrc.

How to I get the initial state back?

ProductName:	macOS
ProductVersion:	14.3
BuildVersion:		23D56

**Comment by cclauss** [comment]
Apple traditionally preinstalled Python in macOS but stopped including Python when it released Catalina.  In any case, you should not rely on this "system Python" but should either `brew install python` or install from the Python website.

> I'm not able to run npm install anymore because I get a python error.

Please provide the full error text.

**Comment by eberhapa** [comment]
gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp verb find Python - executing "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.12.2"
npm ERR! gyp info find Python using Python version 3.12.2 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"

**Comment by cclauss** [comment]
The whole error message please.

**Comment by eberhapa** [comment]
npm ERR! code 1
npm ERR! path /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Binary found at /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/vendor/darwin-arm64-115/binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: dlopen(/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/vendor/darwin-arm64-115/binding.node, 0x0001): tried: '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/vendor/darwin-arm64-115/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/vendor/darwin-arm64-115/binding.node' (no such file), '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/vendor/darwin-arm64-115/binding.node' (not a mach-o file)
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at module.exports (/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/lib/binding.js:19:10)
npm ERR!     at Object.<anonymous> (/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/lib/index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR! Building the binary locally
npm ERR! Building: /usr/local/bin/node /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@20.11.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp verb find Python - executing "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.12.2"
npm ERR! gyp info find Python using Python version 3.12.2 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 20.11.0
npm ERR! gyp verb command install [ '20.11.0' ]
npm ERR! gyp verb install input version string "20.11.0"
npm ERR! gyp verb install installing version: 20.11.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 20.11.0
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/patrick/Library/Caches/node-gyp/20.11.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/patrick/Library/Caches/node-gyp/20.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/patrick/Library/Caches/node-gyp/20.11.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 23.3.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: /Users/patrick/.npm/_logs/2024-02-09T06_47_41_409Z-debug-0.log

**Comment by cclauss** [comment]
What do you get when you type the following in the terminal?
`brew --version`
`python3 --version`
`npm --version`

Two problems are discussed https://github.com/nodejs/node-gyp/blob/main/docs/README.md
> npm ERR! gyp ERR! node-gyp -v v8.4.1

> npm ERR! path /Users/patrick/Local Sites/basiskultur/app/public/wp-content/themes/basiskultur/node_modules/node-sass

**Comment by eberhapa** [comment]
Homebrew 4.2.6 (but I'm not using homebrew for python)
Python 3.12.2
npm 10.4.0

Seems to work without node-sass but I don't understand it because it worked with node-sass to the point I installed python with the python installer.

**Comment by cclauss** [comment]
Python 3.12 support was added in node-gyp v10.

**Comment by eberhapa** [comment]
So by installing python with the installer it automatically took the new version by default and that is not working with node-sass?

**Comment by cclauss** [comment]
Perhaps you should open an issue on the `node-sass` repo because this is not a `node-gyp` issue.
