### ISSUE TITLE
mac sqlite3 system lib fmdb

### ISSUE THREAD

**Issue by iPermanent** [nodejs/node-gyp#2991]
I am confused with the binding.gyp file, as I use some sqlite code with the osx system sqlite, when I build it, it show me an error with: 
../src/osx/fmdb/FMDatabase.m:175:12: error: no matching function for call to 'sqlite3_limit'
    return sqlite3_limit(_db, type, newLimit);
           ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sqlite3.h:4093:16: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to 'sqlite3 *' for 1st argument
SQLITE_API int sqlite3_limit(sqlite3*, int id, int newVal);
               ^
../src/osx/fmdb/FMDatabase.m:262:19: error: no matching function for call to 'sqlite3_close'
And in the binding.gyp file, with the osx config, I wrote:
'link_settings': {
						'libraries': [
							'-framework Cocoa',
							'-framework CoreFoundation',
							'-framework AppKit',
							'libsqlite3'
						]
					},
maybe this libsqlite3 is some other values I should use? as the xcode I use to add sqlite lib, it shows "libsqlite3.tbd" at the Link Binary with Libraries, it confused me what should I fill in this field
Thanks very much

**Comment by cclauss** [comment]
Command typed and full error logs please.
