### ISSUE TITLE
node-gyp fails on Sonoma with CLI only and not XCode (Mac M1 / Apple Silicon)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [nodejs/node-gyp#2992]
node-gyp fails on Sonoma with CLI only and not XCode (Mac M1 / Apple Silicon)

At https://github.com/nodejs/node-gyp/blob/main/gyp/pylib/gyp/xcode_emulation.py#L1496C41-L1496C51 it appears to be looking for version numbers at the end of the "xcodebuild -version" command. But for me, that command does not produce version numbers, see below

The code seems to describe itself working well even if the box only has CLI tools and not full Xcode, but that doesn't seem to be the case in reality:

`$ uname -a 
Darwin Geoffs-Mac-mini.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103 arm64
(base)`

`$ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Mac M1 / Sonoma 14.4

**Comment by cclauss** [comment]
It would be super helpful if we all could see what you are seeing.  Would it be possible to create a GitHub Action to show everyone what happens?

If you use `os: [macos-14]` your GitHub Action will run on an M1 Mac.

* https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
* https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions

**Comment by GeoffreyPlitt** [comment]
@cclauss I created a PR based on a fork here with a new GHA action, can you approve? It says the action needs approval to run.
https://github.com/nodejs/node-gyp/pull/2993

**Comment by cclauss** [comment]
Single backticks \` are for one line.

Use triple backticks for  multiline strings.

**Comment by GeoffreyPlitt** [comment]
Hi guys, the action I created (assuming I created it correctly?) seems to point to a bug where a Windows path is being used on Mac: https://github.com/nodejs/node-gyp/pull/2993#issuecomment-1992402017

**Comment by cclauss** [comment]
Agreed.  Is this a runtime problem or just a test time problem?

**Comment by GeoffreyPlitt** [comment]
@cclauss Install-time. My `pnpm install` does not complete successfully.

**Comment by v29neil** [comment]
Facing same issue , when running `yarn add npm-check-updates`
Node - v20.11.1
npm - v10.5.1
Sonoma OS

`error /Users/v29neil/Office/SaveSageTools/node_modules/argon2: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/v29neil/Office/SaveSageTools/node_modules/argon2
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.11.1 | darwin | arm64
node-pre-gyp info check checked for "/Users/v29neil/Office/SaveSageTools/node_modules/argon2/lib/binding/napi-v3/argon2.node" (not found)
node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.7 and node@20.11.1 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.1 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.1 | darwin | arm64
gyp info find Python using Python version 3.12.2 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
gyp info spawn args [
gyp info spawn args   '/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/v29neil/Office/SaveSageTools/node_modules/argon2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/v29neil/Library/Caches/node-gyp/20.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/v29neil/Library/Caches/node-gyp/20.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/v29neil/Library/Caches/node-gyp/20.11.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/v29neil/Office/SaveSageTools/node_modules/argon2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 23.4.0
gyp ERR! command "/Users/v29neil/.nvm/versions/node/v20.11.1/bin/node" "/Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/v29neil/Office/SaveSageTools/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/Users/v29neil/Office/SaveSageTools/node_modules/argon2/lib/binding/napi-v3" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/v29neil/Office/SaveSageTools/node_modules/argon2
gyp ERR! node -v v20.11.1
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/v29neil/.nvm/versions/node/v20.11.1/bin/node /Users/v29neil/Office/SaveSageTools/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/v29neil/Office/SaveSageTools/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/Users/v29neil/Office/SaveSageTools/node_modules/argon2/lib/binding/napi-v3 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/v29neil/Office/SaveSageTools/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 23.4.0
node-pre-gyp ERR! command "/Users/v29neil/.nvm/versions/node/v20.11.1/bin/node" "/Users/v29neil/Office/SaveSageTools/node_modules/argon2/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/v29neil/Office/SaveSageTools/node_modules/argon2
node-pre-gyp ERR! node -v v20.11.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok `

**Comment by cclauss** [comment]
> gyp info using node-gyp@9.4.1
> gyp info using node@20.11.1 | darwin | arm64
> gyp info find Python using Python version 3.12.2

Upgrade to node-gyp@10 or downgrade to python@3.11.

**Comment by cclauss** [comment]
Can you do this without `node-pre-gyp`?

**Comment by cclauss** [comment]
@GeoffreyPlitt Now that we have a macOS ARM GitHub Action in place, is it possible to modify it (add `pnpm`?, add `node-pre-commit`?, add both?`) to replicate your config and make the tests fail?

https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#tools

**Comment by GeoffreyPlitt** [comment]
@cclauss Can you explain more what you mean? I'll help if I can.

I saw that https://github.com/nodejs/node-gyp/pull/2993 is closed, did it get resolved?

**Comment by cclauss** [comment]
* #3011
Added a GitHub Action on MacOS ARM64 Apple Silicon test which closed #2993
https://github.com/nodejs/node-gyp/blob/323957b74e9586fb3fbfb2acad5040379c778de6/.github/workflows/tests.yml#L100-L102

I do not believe that _solves_ this problem.  It might offer a way to replicate the problem in our GitHub Actions so that everyone can see the failure.

Is it possible to modify `.github/workflows/tests.yml` (add pnpm?, add node-pre-commit?, add both?`) to replicate your config and make the tests fail?

**Comment by GeoffreyPlitt** [comment]
Shoot, it's been 1.5 months and I can't remember how I first encountered this bug, to be honest. I know it was during `pnpm install` for my employer's project, but at some point I found a workaround or something and haven't seen it for a while.

**Comment by ToshihitoKon** [comment]
FYI:
I encountered the same problem and found a solution in node-gyp 9.x.

```
pip3 install setuptools
```

I don't know why it works, but it resolved.

node-gyp: v9.4.1
OS: M1 MacOS Sonoma 14.4.1 
Python: v3.12.1
Node: v20.11.1

**Comment by MeirP-3** [comment]
MacOS Sonoma 14.5 failed `npm install canvas`.

After digging in the error log, root cause were errors similar to `error <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.`.

Solution was:
```bash
export SDKROOT=$(xcrun --show-sdk-path)
npm install canvas
```

**Comment by linhaosunny** [comment]
soo, it's solves this problem?, i can't found what usefull solutions, and why it be closed?

**Comment by linhaosunny** [comment]
> so, it's solves this problem?, i can't found what usefull solutions, and why it be closed? I try all guys sayed, but it not work, I still have the issue.


npm WARN deprecated react-native@0.63.3: Issues and pull requests filed against this version are not supported. See the React Native release support policy to learn more: https://github.com/reactwg/react-native-releases#releases-support-policy
npm ERR! code 1
npm ERR! path /Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/21.7.1/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@21.7.1 | darwin | arm64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@21.7.1 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-darwin-arm64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.7.1 | darwin | arm64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.7.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.5 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/danxiao/Library/Caches/node-gyp/21.7.1/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/Users/danxiao/Library/Caches/node-gyp/21.7.1',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/Users/danxiao/Library/Caches/node-gyp/21.7.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.7.1 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
npm ERR! gyp ERR! System Darwin 23.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/21.7.1/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120"
npm ERR! gyp ERR! cwd /Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3
npm ERR! gyp ERR! node -v v21.7.1
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/21.7.1/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3/lib/binding/node-v120-darwin-arm64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 23.1.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/21.7.1/bin/node" "/Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/danxiao/Desktop/LeeGithub/ghostery/user-agent-ios/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v21.7.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/danxiao/.npm/_logs/2024-08-28T03_49_26_755Z-debug-0.log

@cclauss

**Comment by kimyu92** [comment]
Run into issue while trying to install `canvas`

For those who uses `asdf` to mange python, make sure to run 

```sh
# verify where is the executable python 
which python

# install missing setuptools
python3 -m pip install setuptools
```

**Comment by jswhisperer** [comment]
[source](https://stackoverflow.com/a/59539249)

create a binding.gyp file and place it in your project root. the content of the file looks like this:



`{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ "src/binding.cc" ]
    }
  ]
}`

**Comment by charsen** [comment]
Thanks a lot, guys. 

`
# Check where Python 3 is installed
which python3

# Install missing setuptools using pip
python3 -m pip install setuptools

# Alternatively, install it via Homebrew (if you're on macOS)
brew install python-setuptools
`
