### ISSUE TITLE
node-gyp verison used when npm -install are not align to installed node-gyp version

### ISSUE THREAD

**Issue by tuantuanzi-code** [nodejs/node-gyp#2997]
I have installed node-gyp v10.0.1, but when execute npm install, it shows ERR! node-gyp -v v3.8.0, while node -v v17.9.1, I have tried https://github.com/nodejs/node-gyp/blob/main/docs/README.md, but can not fix the issue. Please help me
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yaoya\\OneDrive - Synopsys, Inc\\Documents\\system_Yao Yao\\DRMS\\drms_00815\\client\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\yaoya\OneDrive - Synopsys, Inc\Documents\system_Yao Yao\DRMS\drms_00815\client\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

npm ERR! A complete log of this run can be found in:

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/main/docs/README.md
