### ISSUE TITLE
Why gyp is using unofficial-builds.nodejs.org to download node-headers ?

### ISSUE THREAD

**Issue by niko2** [nodejs/node-gyp#3003]
We are encountering issues with the download of headers

#15 196.1 npm ERR! gyp ERR! stack FetchError: request to https://unofficial-builds.nodejs.org/download/release/v18.19.1/node-v18.19.1-headers.tar.gz failed, reason: read ETIMEDOUT

No issue to download this file from outside of the build

**Comment by cclauss** [comment]
Please provide the command typed and the FULL error log.

**Comment by fish-uncle** [comment]
[2024-07-22T12_07_05_916Z-debug.log](https://github.com/user-attachments/files/16341256/2024-07-22T12_07_05_916Z-debug.log)
i have the same question

**Comment by cclauss** [comment]
> 222 error gyp ERR! node -v v16.0.0
> 222 error gyp ERR! node-gyp -v v7.1.2

https://github.com/nodejs/node/releases
https://github.com/nodejs/node-gyp/releases
