### ISSUE TITLE
find-python broke with 18.20.0 (?) on ARM

### ISSUE THREAD

**Issue by black-snow** [nodejs/node-gyp#3009]
Not sure where to report this but as it relates to node-gyp this might be the right place.

My OCI builds fine with `node:18-bookworm-slim@sha256:e01db0ed571851e2a67b11624abb90992af585db0afaff451972e64c604dffa1` but broke with `node:18-bookworm-slim@sha256:a7423cbf419ccea2723be0af141b663b643c30bea56d19bf2e8fe171e904fde9` on my mac book.  
The only real difference I can spot is node `18.19.1` vs. `18.20.0`. When I force `--platform=linux/amd64` it works fine.

On ARM I end up with:
> 12.65 npm ERR! path /build/node_modules/@parcel/watcher
12.65 npm ERR! command failed
12.65 npm ERR! command sh -c node-gyp-build
12.65 npm ERR! gyp info it worked if it ends with ok
12.65 npm ERR! gyp info using node-gyp@9.4.1
12.65 npm ERR! gyp info using node@18.20.0 | linux | arm64
12.65 npm ERR! gyp ERR! find Python 
12.65 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
12.65 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
12.65 npm ERR! gyp ERR! find Python checking if "python3" can be used
12.65 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
12.65 npm ERR! gyp ERR! find Python checking if "python" can be used
12.65 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
12.65 npm ERR! gyp ERR! find Python 
12.65 npm ERR! gyp ERR! find Python **********************************************************
12.65 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
12.65 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
12.65 npm ERR! gyp ERR! find Python you can try one of the following options:
12.65 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
12.65 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
12.65 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
12.65 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
12.65 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
12.65 npm ERR! gyp ERR! find Python For more information consult the documentation at:
12.65 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
12.65 npm ERR! gyp ERR! find Python **********************************************************
12.65 npm ERR! gyp ERR! find Python 
12.65 npm ERR! gyp ERR! configure error 
12.65 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
12.65 npm ERR! gyp ERR! stack     at PythonFinder.fail (/build/node_modules/node-gyp/lib/find-python.js:330:47)
12.65 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/build/node_modules/node-gyp/lib/find-python.js:159:21)
12.65 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/build/node_modules/node-gyp/lib/find-python.js:202:16)
12.65 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/build/node_modules/node-gyp/lib/find-python.js:294:16)
12.65 npm ERR! gyp ERR! stack     at exithandler (node:child_process:430:5)
12.65 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
12.65 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
12.65 npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:290:12)
12.65 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
12.65 npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
12.65 npm ERR! gyp ERR! System Linux 6.6.16-linuxkit
12.65 npm ERR! gyp ERR! command "/usr/local/bin/node" "/build/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
12.65 npm ERR! gyp ERR! cwd /build/node_modules/@parcel/watcher
12.65 npm ERR! gyp ERR! node -v v18.20.0
12.65 npm ERR! gyp ERR! node-gyp -v v9.4.1
12.65 npm ERR! gyp ERR! not ok
12.65 
12.65 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-04T14_35_22_838Z-debug-0.log

I diffed the images and they are pretty much the same. I have no idea what (else) changed between those versions.

**Comment by cclauss** [comment]
What do you get when you:
% `python3 --version`

From your log:
> 12.65 npm ERR! gyp info using node-gyp@9.4.1

Please upgrade:
https://github.com/nodejs/node-gyp/releases

**Comment by black-snow** [comment]
`docker run -it --rm --entrypoint=/bin/bash node:18-bookworm-slim@sha256:e01db0ed571851e2a67b11624abb90992af585db0afaff451972e64c604dffa1 python3 --version` yields `python3: No such file or directory` on either image.

**Comment by cclauss** [comment]
Oh, the joys of using `slim`...
`apt update && apt install python3 --yes && python3 --version`

**Comment by black-snow** [comment]
@cclauss thanks for the quick reply.
Was this inteded for me as a "fix"? I know how to work around the issue, but it's probably not meant to be broken on a different arch, right? Or is it some node package that's requiring but missing some platform-specific binaries and hence needs to be built from source on ARM but not on amd64?

**Comment by cclauss** [comment]
> Was this intended for me as a "fix"?

Yes. `apt update && apt install python3 --yes && python3 --version` was intended as a fix because `slim` does not pre-install Python.  I do not think the problem is about `amd64` but is instead about `slim`.
