### ISSUE TITLE
[Request] Upgrade tar to v6.2.1

### ISSUE THREAD

**Issue by anhcao142** [nodejs/node-gyp#3013]
Hi currently, our `yarn npm audit` alerts that tar versions < 6.2.1 are vulnerable. This is our log

```
└─ tar
   ├─ ID: 1096915
   ├─ Issue: Denial of service while parsing a tar file due to lack of folders count validation
   ├─ URL: https://github.com/advisories/GHSA-f5x3-32g6-xq36
   ├─ Severity: moderate
   ├─ Vulnerable Versions: <6.2.1
   │
   ├─ Tree Versions
   │  └─ 6.2.0
   │
   └─ Dependents
      └─ @mapbox/node-pre-gyp@npm:1.0.11
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/77737e45db5cd7873f440c43154302e22ef21c85/package.json#L33

**Comment by lukekarrys** [comment]
@anhcao142 The log you posted indicates that `@mapbox/node-pre-gyp` is the dependency responsible for the vulnerable version of `tar`.

**Comment by anhcao142** [comment]
Yeah I just noticed that, will close this now

**Comment by mvanzoest** [comment]
Hi, just as a heads up, it looks like tar is a direct dependency of node-gyp:

![image](https://github.com/nodejs/node-gyp/assets/6361257/acafe118-0be3-4c2e-b8f2-97141ad395df)

**Comment by cclauss** [comment]
Yes.  As stated at https://github.com/nodejs/node-gyp/issues/3013#issuecomment-2046680557

**Comment by mvanzoest** [comment]
> Yes. As stated above at [#3013 (comment)](https://github.com/nodejs/node-gyp/issues/3013#issuecomment-2046680557)
> 
> > @anhcao142 Are you able to make a pull request to update this dependency?

https://github.com/nodejs/node-gyp/pull/3021
