### ISSUE TITLE
Node.js v22: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SkybuckFlying** [nodejs/node-gyp#3029]
V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet>npm rebuild
npm error code 7
npm error path V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@3.8.0
npm error gyp info using node@22.0.0 | win32 | x64
npm error (node:37456) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error (node:37456) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error gyp http GET https://nodejs.org/download/release/v22.0.0/node-v22.0.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v22.0.0/node-v22.0.0-headers.tar.gz
npm error gyp ERR! UNCAUGHT EXCEPTION
npm error gyp ERR! stack RangeError: Maximum call stack size exceeded
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! stack     at Stats.set [as atime] (node:internal/fs/utils:469:18)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "G:\\Tools\\NodeJS\\node.exe" "V:\\Worktrees\\ViteXWallet\\version-1.6.9\\vite-web-wallet\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3
npm error gyp ERR! node -v v22.0.0
npm error gyp ERR! node-gyp -v v3.8.0
npm error gyp ERR! This is a bug in `node-gyp`.
npm error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

npm error A complete log of this run can be found in: C:\Users\skybu\AppData\Local\npm-cache\_logs\2024-04-27T15_34_57_154Z-debug-0.log

**Comment by SkybuckFlying** [comment]
Other issues, seems to be going around in circles, but this the main one:

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet>npm uninstall -g node-gyp

removed 101 packages in 379ms

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet>npm install -g node-gyp@latest

added 101 packages in 2s

14 packages are looking for funding
  run `npm fund` for details

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet>yarn
yarn install v1.22.19
warning package.json: "dependencies" has dependency "@babel/plugin-proposal-class-properties" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "^7.5.0"
warning package.json: "dependencies" has dependency "@babel/plugin-proposal-object-rest-spread" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "^7.5.4"
warning package.json: "dependencies" has dependency "@babel/preset-typescript" with range "~7.3.3" that collides with a dependency in "devDependencies" of the same name with version "^7.3.3"
warning ..\package.json: No license field
warning vite-wallet@3.4.0: "dependencies" has dependency "@babel/plugin-proposal-class-properties" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "^7.5.0"
warning vite-wallet@3.4.0: "dependencies" has dependency "@babel/plugin-proposal-object-rest-spread" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "^7.5.4"
warning vite-wallet@3.4.0: "dependencies" has dependency "@babel/preset-typescript" with range "~7.3.3" that collides with a dependency in "devDependencies" of the same name with version "^7.3.3"
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > @babel/preset-es2015@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-arrow-functions@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-block-scoped-functions@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-block-scoping@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-classes@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-computed-properties@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-destructuring@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-duplicate-keys@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-for-of@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-function-name@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-instanceof@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-literals@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-amd@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-commonjs@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-systemjs@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-umd@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-object-super@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-parameters@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-regenerator@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-shorthand-properties@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-spread@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-sticky-regex@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-template-literals@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-typeof-symbol@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-unicode-regex@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning " > eslint-plugin-vue@4.7.1" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
[4/4] Building fresh packages...
[23/24] ⠁ node-sass
[13/24] ⠁ websocket
[-/24] ⠁ waiting...
[12/24] ⠁ sha3
error V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3
Output:
V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3>if not defined npm_config_node_gyp (node "G:\Tools\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@22.0.0 | win32 | x64
gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"

gyp info find VS using VS2022 (17.8.34316.72) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python312\python.exe
gyp info spawn args [
gyp info spawn args 'G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'V:\\Worktrees\\ViteXWallet\\version-1.6.9\\vite-web-wallet\\node_modules\\sha3\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\skybu\\AppData\\Local\\node-gyp\\Cache\\22.0.0\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\skybu\\AppData\\Local\\node-gyp\\Cache\\22.0.0',
gyp info spawn args '-Dnode_gyp_dir=G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\skybu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.0.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=V:\\Worktrees\\ViteXWallet\\version-1.6.9\\vite-web-wallet\\node_modules\\sha3',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'V:\\Worktrees\\ViteXWallet\\version-1.6.9\\vite-web-wallet\\node_modules\\sha3\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  addon.cpp
V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23): error C2039: 'AccessorSignature': is not a member of 'v8' [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8.h(71,11):
  see declaration of 'v8'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23): error C2065: 'AccessorSignature': undeclared identifier [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,13): error C2923: 'v8::Local': 'AccessorSignature' is not a valid template type argument for parameter 'T' [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23):
  see declaration of 'AccessorSignature'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,42): error C2955: 'v8::Local': use of class template requires template argument list [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(252,1):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,14): error C2955: 'v8::Local': use of class template requires template argument list [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(252,1):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2641: cannot deduce template arguments for 'v8::Local' [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(const v8::LocalBase<T> &)': expects 1 arguments - 0 provided [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(401,3):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(const v8::Local<T> &,v8::api_internal::StackAllocated<false>::no_checking_tag)': expects 2 arguments - 0 provided [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(398,3):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(v8::api_internal::StackAllocated<false>::no_checking_tag)': expects 1 arguments - 0 provided [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(396,3):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(v8::Local<S>)': expects 1 arguments - 0 provided [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(263,3):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2783: 'v8::Local<T> v8::Local(void)': could not deduce template argument for 'T' [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(260,3):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(v8::Local<T>)': expects 1 arguments - 0 provided [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-local-handle.h(252,1):
  see declaration of 'v8::Local'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6): error C2665: 'v8::ObjectTemplate::SetAccessor': no overloaded function could convert all the argument types [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-template.h(1055,8):
  could be 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)'
        V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
        'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)': cannot convert argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
                V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2475,7):
                Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or parenthesized function-style cast)
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-template.h(1049,8):
  or       'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)'
        V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
        'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)': cannot convert argument 2 from 'Nan::imp::NativeGetter' to 'v8::AccessorGetterCallback'
                V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2472,7):
                This conversion requires a reinterpret_cast, a C-style cast or parenthesized function-style cast
  V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
  while trying to match the argument list '(v8::Local<v8::String>, Nan::imp::NativeGetter, Nan::imp::NativeSetter, v8::Local<v8::Object>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)'

V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_typedarray_contents.h(34,43): error C2039: 'GetContents': is not a member of 'v8::ArrayBuffer' [V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\22.0.0\include\node\v8-wasm.h(19,7):
  see declaration of 'v8::ArrayBuffer'
  V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_typedarray_contents.h(34,43):
  the template instantiation context (the oldest one first) is
        V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_typedarray_contents.h(88,2):
        see reference to class template instantiation 'Nan::TypedArrayContents<T>' being compiled

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (G:\Tools\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:520:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "G:\\Tools\\NodeJS\\node.exe" "G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd V:\Worktrees\ViteXWallet\version-1.6.9\vite-web-wallet\node_modules\sha3

**Comment by cclauss** [comment]
Please retry with Node.js v20 instead of v22 which was just released 24 hours ago.

**Comment by richardlau** [comment]
This looks like https://github.com/nodejs/node/issues/52705 which is a bug in Node.js 22.

**Comment by albertmarques7** [comment]
using Node.js v20 worked pretty well with me . thanks

**Comment by cclauss** [comment]
Fixed and merged in:
* https://github.com/nodejs/node/pull/52708
