### ISSUE TITLE
How to crosscompile form debian 64bit to ARM 32bit?

### ISSUE THREAD

**Issue by z0nk** [nodejs/node-gyp#304]
I am trying to cross compile my node-addon.
using the following configure command:  _node-gyp --arch arm --host_arch=arm --arm_fpu=vfpv2 configure_
The _config.gypi_ File looks correct but I get the following error if i try to use the addon:

module.js:356
  Module._extensions[extension](this, filename);
Error: /home/pi/site/test/build/Release/myaddon.node: wrong ELF class: ELFCLASS64
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/temp/website/app.js:14:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

And if I try to compile the addon nativ on my raspberry I get the following error:
_cc1plus: error: unrecognized command line option ‘-std=c++11’_

I cant find anything to solve this problem. Can someone help?
thanks!

**Comment by AllenBird** [comment]
I have the same problem...

  CXX(target) Release/obj.target/hello/hello.o
**cc1plus: error: unrecognized command line option '-m32'**
make: *** [Release/obj.target/hello/hello.o] error 1
make:离开目录“/home/hzmct/Downloads/node-addon-examples-master/1_hello_world/nan/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hzmct/Downloads/node-addon-examples-master/1_hello_world/nan
gyp ERR! node -v v0.10.42
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by almesh** [comment]
salah140581@gmailcom

**Comment by maitreyi-timesys** [comment]
I am trying to generate arm specific node-sqlite3 addon by following commands
1- Have set the env by sourcing the env generated from Toolchain
to set following
echo $CC
arm-poky-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi
echo $CXX
arm-poky-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a9 --sysroot=/home/user/ansbld/tmp/deploy/sdk/toolchain/sysroots/cortexa9-vfp-neon-poky-linux-gnueabi

2- Now invoking npm
sudo npm install sqlite3 --target_arch=arm --build-from-source=sqlite3 --target_platform=linux

This generates the lib/binding/node-v14-linux-arm/node_sqlite3.node but this is not compiled for arm platform rather for host environment

I have also tried using node-gyp and node-pre-gyp
but no success so far

**Comment by bnoordhuis** [comment]
Cross-compilation is not really supported at the moment, see the discussion in #829, particularly https://github.com/nodejs/node-gyp/issues/829#issuecomment-160660375.  I'll close out this issue in favor of that one.
