### ISSUE TITLE
node-pty install is failed with gyp ERR

### ISSUE THREAD

**Issue by WhityGhost** [nodejs/node-gyp#3077]
I'm using node v20.17.0 and node-gyp is up-to-date (using v10.2.0)
But whenever I try to install dependencies for my project, I get this error output.

<details><summary>Node-gyp output:</summary>

```
gyp info using node@20.17.0 | win32 | x64
gyp info find Python using Python version 3.12.4 found at "C:\Users\USER\AppData\Local\Programs\Python\Python312\python.exe"
gyp info find VS using VS2022 (17.10.35013.160) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\USER\AppData\Local\Programs\Python\Python312\python.exe
gyp info spawn args [
gyp info spawn args 'C:\\Users\\USER\\AppData\\Roaming\\nvm\\v20.17.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'D:\\_Workspace\\Development\\Web\\Nextjs\\hackerium-project\\website\\node_modules\\node-pty\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\USER\\AppData\\Roaming\\nvm\\v20.17.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\USER\\AppData\\Local\\node-gyp\\Cache\\20.17.0\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\USER\\AppData\\Local\\node-gyp\\Cache\\20.17.0',
gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\USER\\AppData\\Roaming\\nvm\\v20.17.0\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\USER\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.17.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=D:\\_Workspace\\Development\\Web\\Nextjs\\hackerium-project\\website\\node_modules\\node-pty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'D:\\_Workspace\\Development\\Web\\Nextjs\\hackerium-project\\website\\node_modules\\node-pty\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\nvm\v20.17.0\node_modules\node-gyp\lib\build.js:216:23)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\_Workspace\Development\Web\Nextjs\hackerium-project\website\node_modules\node-pty
gyp ERR! node -v v20.17.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok

error: install script from "node-pty" exited with 1
```

</details>

I used bun v1.1.21 for installation.
I tried to remove the packages installed and reinstall node-gyp, but all didn't work.
Any help please...
Thank you.

**Comment by cclauss** [comment]
[`node-pty` issues](https://github.com/search?q=repo%3Anodejs%2Fnode-gyp+node-pty&type=issues)

**Comment by huseyinacacak-janea** [comment]
As can be seen from [this link](https://www.npmjs.com/package/node-pty#dependencies), the current `node-pty` release supports only Node.js v16. In your case, you try to use it with Node.js v20.
What can be done to use it with the latest versions of Node.js is to use `node-pty@beta`. Could you please try to install the module with this version in your project?

**Comment by WhityGhost** [comment]
Thank you for your reply
but installing node-pty@beta shows the same error

**Comment by cclauss** [comment]
Perhaps upgrade the tests from Node.js v18 to 20 or 22.

https://github.com/microsoft/node-pty/blob/main/azure-pipelines.yml

**Comment by huseyinacacak-janea** [comment]
> Thank you for your reply but installing node-pty@beta shows the same error
> 
> And installing node-pty in new empty directory fails with the same error as well

I created an empty folder and ran the following commands inside:
- `npm init`
- `npm install node-pty@beta`

The installation was successful with the latest versions of Node.js (v22.9.0, v20.18.0 and v18.20.4). So, I'm not able to reproduce it locally. Could you write down the commands that you've run?

**Comment by Tyriar** [comment]
node-pty definitely works on node 20, that's what I use everyday.

> I used bun v1.1.21 for installation.

Last time I heard there were problems with bun and node-gyp/NAPI? https://github.com/microsoft/node-pty/issues/632

**Comment by cclauss** [comment]
Thanks for your work on `node-pyt` and your quick response here!

[`nappi`](https://github.com/nodejs/node-gyp/issues?q=label%3Affi-napi) is a frequently reported problem.
* node-ffi-napi/node-ffi-napi#269

**Comment by StefanStojanovic** [comment]
Hello everyone, since this has gone stale, and is not reproducible with the beta version, I'll close it. Feel free to reopen if needed.
