### ISSUE TITLE
Help: Revert Windows Installation (Manual Installation)

### ISSUE THREAD

**Issue by Souvik-Cyclic** [nodejs/node-gyp#3083]
* **Node Version**:  v23.0.0, 10.8.1
* **Platform**:  Windows
* **Compiler**:  Windows
tried doing this 
https://github.com/Automattic/node-canvas/wiki/Installation:-Windows 
(manual installation)

Help me revert all the steps, is there a proper guide for this?

**Comment by StefanStojanovic** [comment]
From what I see, you opened this issue in the `node-canvas` repository, which I was planning to suggest you try. Since that's already done, I'll close this one.
