### ISSUE TITLE
Windows10教育版本 和Windows企业版本 为啥使用的node-gyp的版本不一致

### ISSUE THREAD

**Issue by gongyuan300** [nodejs/node-gyp#3088]
widnow10教育版本 和window企业版本上 安装electron20.3.8和node16.18.0 打包为啥为啥使用的node-gyp的版本不一致   教育版使用的是9  企业版使用的11  在 C:\Users\Open\AppData\Local\node-gyp\Cache\16.18.0  中installVersion中体现的版本不一致  导致 企业版无法打包成功

---
__Why do the versions of node-gyp used in Windows 10 education version and Windows enterprise version differ?__

Why do I install electron20.3.8 and node16.18.0 on widnow10 education version and window enterprise version? The node-gyp versions used are inconsistent. The education version uses 9 and the enterprise version uses 11. The versions reflected in installVersion in C:\Users\Open\AppData\Local\node-gyp\Cache\16.18.0 are inconsistent, which makes the enterprise version unable to be packaged successfully

**Comment by gongyuan300** [comment]
widnow10教育版本 和window企业版本上 安装electron20.3.8和node16.18.0 打包为啥为啥使用的node-gyp的版本不一致   教育版使用的是9  企业版使用的11  在 C:\Users\Open\AppData\Local\node-gyp\Cache\16.18.0  中installVersion中体现的版本不一致  导致 企业版无法打包成功

**Comment by cclauss** [comment]
Node.js 16 is no longer supported.  Please upgrade.  https://nodejs.org/en/about/previous-releases

The log output would help a lot because there is no node-gyp version 11 yet.  https://github.com/nodejs/node-gyp/releases

**Comment by gongyuan300** [comment]
node版本 升级18.20.4 依然报错    C:\Users\Open\.electron-gyp\20.3.8这个目录下的installVersion的版本 也是11，刚才这个\.electron-gyp文件夹是不存在的原因是被我删除掉了。操作之前我先把C:\Users\Open\ AppData\ Local\node-gyp\Cache\16.18.0删除掉，然后打包 C:\Users\Open\ AppData\ Local\node-gyp\Cache\16.18.0这个没有生成 但是生成C:\Users\Open\.electron-gyp\20.3.8，对应的版本是11 就会报错。我在其他的window10的电脑上 教育版、专业版的就没有这个问题以上两个目录无论咋编译都是9  我觉得这应该兼容性问题

**Comment by gongyuan300** [comment]
<img width="930" alt="企业微信截图_2bd460cd-5682-4b21-91b0-f5ceec9f6ac6" src="https://github.com/user-attachments/assets/6182f8b2-7e09-4f6d-b74a-91d15d2b62be">
上面的图片显示 就是11

**Comment by gongyuan300** [comment]
源码显示11 在什么情况下是9呢  为啥在企业版上判断不对呢

**Comment by gongyuan300** [comment]
显示呢11在什么情况下源码是9为啥在企业版上判断不对呢

**Comment by gongyuan300** [comment]
在同样的代码下面  electron 20.8.3  
还有一个很奇怪的问题  widnow10教育版 node_modules中@electron 下面的包是四个   而window10企业版 node_modules中@electron 是五个  
![企业微信截图_8fa61423-a3aa-4d29-b87e-aa084a3b161f](https://github.com/user-attachments/assets/53ca0722-a63a-46be-b85f-7a18c5b8acff)


并且打包的使用到了其中node_gyp如图
![企业微信截图_7bccb917-d835-4818-86f5-4ca01d0800b1](https://github.com/user-attachments/assets/99876255-e387-4607-b05b-c24919917bd9)
感觉不可思议  相同代码 node electron版本  package.json是相同的 竟然会不同

**Comment by gongyuan300** [comment]
企业版本系统信息
![Uploading 企业微信截图_a7c51056-46b1-430b-b085-64fcf2c97d6e.png…]()

**Comment by gongyuan300** [comment]
企业版本系统信息
![企业微信截图_a7c51056-46b1-430b-b085-64fcf2c97d6e](https://github.com/user-attachments/assets/b11a91b3-e918-4ace-8532-93c3ed33c6a8)

**Comment by gongyuan300** [comment]
教育版本也不能使用了，我猜测和环境有关系，目前不清楚为啥打包缓存使用electron-gyp或者node-gyp 一会是11 一会是9 这个是什么原因导致的

**Comment by gongyuan300** [comment]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Open\Desktop\test\be-test-client\node_modules\@electron\node-gyp\lib\build.js:215:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Open\\Desktop\\test\\be-openexam-client\\node_modules\\@electron\\node-gyp\\bin\\node-gyp.js" "rebuild"     
npm ERR! gyp ERR! cwd C:\Users\Open\Desktop\test\be-test-client\node_modules\ffi-napi
npm ERR! gyp ERR! node -v v16.18.0
npm ERR! gyp ERR! node-gyp -v v10.2.0-electron.1
npm ERR! gyp ERR! not ok

**Comment by gongyuan300** [comment]
问题已经确认  是electron/rebuild导致的问题 详细见
https://github.com/nodejs/node-gyp/issues/3088

**Comment by cclauss** [comment]
Issues with the `ffi-napi` label.
* https://github.com/nodejs/node-gyp/issues?q=label%3Affi-napi+

**Comment by gongyuan300** [comment]
这里   https://github.com/electron/rebuild/issues/1160
