### ISSUE TITLE
Npm İnstall Error Help :/ 

### ISSUE THREAD

**Issue by ugur010** [nodejs/node-gyp#3090]
PS C:\xampp\htdocs> npm install
npm warn deprecated move-concurrently@1.0.1: This package is no longer supported.
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated copy-concurrently@1.0.5: This package is no longer supported.
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated fs-write-stream-atomic@1.0.10: This package is no longer supported.
npm warn deprecated vue@2.6.14: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
npm warn deprecated eslint@6.8.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path C:\xampp\htdocs\node_modules\node-sass
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm error Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm error gyp verb cli   'C:\\xampp\\htdocs\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm error gyp verb cli   'rebuild',
npm error gyp verb cli   '--verbose',
npm error gyp verb cli   '--libsass_ext=',
npm error gyp verb cli   '--libsass_cflags=',
npm error gyp verb cli   '--libsass_ldflags=',
npm error gyp verb cli   '--libsass_library='
npm error gyp verb cli ]
npm error gyp info using node-gyp@3.8.0
npm error gyp info using node@22.11.0 | win32 | x64
npm error gyp verb command rebuild []
npm error gyp verb command clean []
npm error gyp verb clean removing "build" directory
npm error gyp verb command configure []
npm error gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
npm error gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
npm error (node:10016) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.18
npm error gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm error gyp verb get node dir no --target version specified, falling back to host node version: 22.11.0
npm error gyp verb command install [ '22.11.0' ]
npm error gyp verb install input version string "22.11.0"
npm error gyp verb install installing version: 22.11.0
npm error gyp verb install --ensure was passed, so won't reinstall if already installed
npm error (node:10016) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error gyp verb install version is already installed, need to check "installVersion"
npm error gyp verb got "installVersion" 9
npm error gyp verb needs "installVersion" 9
npm error gyp verb install version is good
npm error gyp verb get node dir target node version installed: 22.11.0
npm error gyp verb build dir attempting to create "build" dir: C:\xampp\htdocs\node_modules\node-sass\build
npm error gyp verb build dir "build" dir needed to be created? C:\xampp\htdocs\node_modules\node-sass\build
npm error gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
npm error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
npm error gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
npm error gyp verb find vs2017   - Using this installation with Windows 10 SDK
npm error gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm error gyp verb build/config.gypi creating config file
npm error gyp verb build/config.gypi writing out config file: C:\xampp\htdocs\node_modules\node-sass\build\config.gypi
npm error gyp verb config.gypi checking for gypi file: C:\xampp\htdocs\node_modules\node-sass\config.gypi
npm error gyp verb common.gypi checking for gypi file: C:\xampp\htdocs\node_modules\node-sass\common.gypi
npm error gyp verb gyp gyp format was not specified; forcing "msvs"
npm error gyp info spawn C:\Python27\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args   'C:\\xampp\\htdocs\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'msvs',
npm error gyp info spawn args   '-G',
npm error gyp info spawn args   'msvs_version=2015',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'C:\\xampp\\htdocs\\node_modules\\node-sass\\build\\config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'C:\\xampp\\htdocs\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   'C:\\Users\\uur\\.node-gyp\\22.11.0\\include\\node\\common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\uur\\.node-gyp\\22.11.0',
npm error gyp info spawn args   '-Dnode_gyp_dir=C:\\xampp\\htdocs\\node_modules\\node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=C:\\Users\\uur\\.node-gyp\\22.11.0\\<(target_arch)\\node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\node_modules\\node-sass',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'C:\\xampp\\htdocs\\node_modules\\node-sass\\build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onCpExit (C:\xampp\htdocs\node_modules\node-gyp\lib\configure.js:345:16)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Windows_NT 10.0.19045
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm error gyp ERR! cwd C:\xampp\htdocs\node_modules\node-sass
npm error gyp ERR! node -v v22.11.0
npm error gyp ERR! node-gyp -v v3.8.0
npm error gyp ERR! not ok
npm error Build failed with error code: 1
npm error A complete log of this run can be found in: C:\Users\uur\AppData\Local\npm-cache\_logs\2024-11-08T21_57_37_858Z-debug-0.log

**Comment by cclauss** [comment]
npm error gyp info using node-gyp@3.8.0

On Python 2???

**Comment by ugur010** [comment]
What do you recommend me to do? I should not use xampp. Python is installed 2,7 and 3.

**Comment by cclauss** [comment]
PS C:\xampp\htdocs> node-gyp --version  # Python >= 3.12 will NEED node-gyp >=10.

I only had a quick review, but I believe xampp needs much modernization work.

If you can use a modern version of `node-gyp,` then it will find and use Python 3.  Update any `package.json` and/or `package-lock.json` files that specify out-of-date versions of `node-gyp`.

**Comment by ugur010** [comment]
PS C:\xampp\htdocs> node-gyp --version
v10.2.0
PS C:\xampp\htdocs>

**Comment by cclauss** [comment]
Perfect...

Update all `package.json` and/or `package-lock.json` files that specify out-of-date versions of `node-gyp`.

**Comment by cclauss** [comment]
Nose-sass is history… https://www.npmjs.com/package/node-sass

**Comment by ugur010** [comment]
> cross-env NODE_ENV=development webpack --config webpack.mix.js --progress

Entrypoint main =

ERROR in main
Module not found: Error: Can't resolve './src' in 'C:\xampp\htdocs'
resolve './src' in 'C:\xampp\htdocs'
  using description file: C:\xampp\htdocs\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\xampp\htdocs\package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\xampp\htdocs\src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\xampp\htdocs\src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\xampp\htdocs\src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        C:\xampp\htdocs\src.wasm doesn't exist
      as directory
        C:\xampp\htdocs\src doesn't exist

webpack 5.96.1 compiled with 1 error in 83 ms

Uur@DESKTOP-B4ULHIB C:\xampp\htdocs\resources\src\translations\locales

webpackmix.js

const mix = require('laravel-mix');
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

/*
 |----------------------------------------------------------------------
 | Mix Asset Management
 |----------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

// JavaScript ve Vue dosyalarını derle
mix.js('resources/src/main.js', 'public/js') // Ana JavaScript dosyasını 'public/js' dizinine
   .js('resources/src/login.js', 'public/js') // Login JavaScript dosyasını 'public/js' dizinine
   .vue(); // Vue.js desteği

// Webpack yapılandırmasını özelleştirme
mix.webpackConfig({
    output: {
        // Çıktı dosya ismi ve hash ekleyerek her derlemede yeni bir dosya ismi oluşturulur
        filename: 'js/[name].min.js',  // JS dosyasının ismi
        chunkFilename: 'js/bundle/[name].[hash].js',  // Chunk dosyaları için isim
    },
    plugins: [
        // Moment.js'teki gereksiz yerel ayarları temizlemek için
        new MomentLocalesPlugin(),
        // Çıktı klasörünü temizlemek için
        new CleanWebpackPlugin({
            cleanOnceBeforeBuildPatterns: ['public/js/*'],  // 'public/js' dizinini temizler
        }),
    ],
});

// Geliştirme ve üretim için ayrı komutlar
if (mix.inProduction()) {
    mix.version();  // Üretim ortamında dosyaların versiyonlarını ekler
}



and my files are not visible in the C:\xampp\htdocs\resources\src folder.
