### ISSUE TITLE
File /Users/$USERNAME/.node-gyp/0.10.15/common.gypi not found

### ISSUE THREAD

**Issue by i11v** [nodejs/node-gyp#313]
In node-gyp 0.10.15 version there is not `common.gypi` file. I copied it from ~/.node-gyp/0.10.11/ to resolve this issue.

**Comment by fulup-bzh** [comment]
Fail on a clean new install of OpenSuse-13.2. While a hard copy of /usr/share/node/common.gypi from an older installation worked for me, it look like something is wrong within installer.

On a clean install with standard nodejs in place. Following command does not generate an error, but does not install  /usr/share/node/common.gypi

sudo npm install -g node-gyp

**Comment by kira-backes** [comment]
@fulup-bzh 
zypper in nodejs-devel fixed this for me, this package contains the missing file.

**Comment by pradhanshrijal** [comment]
same problem for me while installing i2c

![gyperror](https://cloud.githubusercontent.com/assets/11836341/9321704/1fb88938-4594-11e5-93b6-0a2cba83baca.JPG)

**Comment by harlantwood** [comment]
I was getting similar errors; in my case upgrading from node 5.11.x to 5.12 along with `rm -rf ~/.node_gyp ./node_modules` fixed it.

**Comment by pradhanshrijal** [comment]
It ok, I installed Debian Jesse instead of Debian Wheezy in which the problem occurred and it was resolved
