### ISSUE TITLE
Error: no error, when requiring my addon

### ISSUE THREAD

**Issue by ngryman** [nodejs/node-gyp#314]
Hi,

I have a weird error when I require my addon. `node -pe "require('./build/Release/ribs.node')"` gives me:

``` bash
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: no errorD:\Users\ngryman\Code\ribs\build\Release\ribs.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:901:3
```

Here is my `binding.gyp`: https://github.com/ngryman/ribs/blob/master/binding.gyp.

When I remove all references and link to `liblept168.lib` (to use the associated `dll`), this works fine. It seems to be related to linking with this library.
I have downloaded prebuilt binaries of `leptonica` here: http://www.leptonica.org/vs2008doc/downloading-binaries.html. They are built with Visual Studio 2008 for `32-bit`.

Here are more infos about my configuration:
- Windows 7 x64
- Visual Studio Express 2012
- Node `32-bits` `v0.10.17`
- node-gyp `v0.10.9`

Do you have an idea why linking to that library would break the require?

Thanks!

**Comment by tk120404** [comment]
@ngryman can you please close this issue
