### ISSUE TITLE
Debugging source on OSX

### ISSUE THREAD

**Issue by zippo445** [nodejs/node-gyp#316]
I would like to debug a node-module compiled with node-gyp. 
I am currently able to build a debug version of the module and to use gdb to trace through my code...

being a bit lazy, I would like to use a visual IDE (xcode) to step through the code and inspect values... I was under the impression that node-gyp would generate a xcode project that I could use and then using 'attach to process..." from xcode be able to set breakpoint and trace the code...

a) is that the correct approach?
b) can't find the xcode project... should it be somewhere in the /build directory?

**Comment by graysonlang** [comment]
node-gyp configure -- -f xcode

**Comment by kimown** [comment]
https://www.youtube.com/watch?v=DND2H2-XfAc

It works, but I want to know how to achieve same result using Clion?

**Comment by maclover7** [comment]
The fix, as noted by @graysonlang, would be to pass `-f xcode` to generate an XCode project. Going to close since there's no bug here in node-gyp or gyp
