### ISSUE TITLE
How to add dependence to static library in binding.gyp?

### ISSUE THREAD

**Issue by alex-netkachov** [nodejs/node-gyp#328]
I did not find in the documentation how to add static library to binding.gyp?

I've successfully compiled my node.js extension with reference to the shared library as follows:

```
    {
      "targets": [
        {
          "target_name": "myext",
          "sources": [
            "code/main.cpp",
            "code/load.cpp",
            "include/load.h"
          ],
          "include_dirs": [
            "include", "../Library/include"
          ],
          "libraries": [
            "-lmylib", "-L/home/admin/MyLib/Library/binaries/linux/Release"
          ],
          "cflags!": [ "-fno-exceptions" ],
          "cflags": [ "-std=c++11" ],
          "cflags_cc!": [ "-fno-exceptions" ]
        }
      ]
    }
```

and now want to add static version of the library to the extension to avoid libray loading issues. Is this possible?

Thanks!

**Comment by ashish0389** [comment]
Thank you for your answer @TooTallNate . It's really helpful.

**Comment by peiyun007** [comment]
@Vimos , you can write like this: "libraries": [ "-Wl,-rpath, mylib.a" ] . This can work.

**Comment by Embedded4development** [comment]
if i want to link shared library then i need to just replace .a with .so or anything else do i need to do?

**Comment by bnoordhuis** [comment]
@Embedded4development `'libraries': ['-L/path/to/dir', '-lfoo']` if the shared object is called libfoo.so.  The `-L` switch is only necessary when it's not in a standard location.  You may also want to pass `-Wl,-rpath` in that case.

**Comment by Embedded4development** [comment]
@bnoordhuis 
if i have multiple libraries then what would be perfect syntax to map library name & respective path?

**Comment by bnoordhuis** [comment]
@Embedded4development `'libraries': ['-lfoo', '-lbar', '-lbaz']` - add search directories and rpaths if necessary.

**Comment by Embedded4development** [comment]
@bnoordhuis Thanks for useful response..

**Comment by drFabio** [comment]
I am compiling on Windows and as I saw the file get's compiled but the static library is not embedded on the code, is there a way for the generated .node file to have the static library embbedded on it's code? So that the client does not need to have a dll.

**Comment by bnoordhuis** [comment]
@drFabio If you have a dll, it's not a static library.

**Comment by drFabio** [comment]
@bnoordhuis  I have a .lib but the generated .node file when inspected with dependency worker says it's needing the dll.
It compiles without error , but when in use on the windows machine if the user does not have a registered dll it does not work.

**Comment by bnoordhuis** [comment]
@drFabio Where does the lib file come from?  Who or what produces it?

**Comment by drFabio** [comment]
It is libeay32.lib I use the lib that comes from the installer in from
http://slproweb.com/products/Win32OpenSSL.html that is recommended on
https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

**Comment by bnoordhuis** [comment]
At a guess, it sounds like the lib file is just glue code for the dll.  In that case you're SOL.

**Comment by drFabio** [comment]
This whole time I was assuming this was node-gyp default behaviour.
Everything makes sense now. Thanks a ton!

**Comment by Shivani26Singh** [comment]
How to add dependence of shared_library in binding.gyp?
I have .node file of my C++ project and I want to refer this .node file in its Unit test project.
But I am unable to link .node/ .dll file in binding.gyp file of my Unit Test project.
If I build my C++ project with static library, I am able to execute my unit tests sucessfully.

**Comment by bumi001** [comment]
Instead of 
"libraries": ["-lmylib", "-L/home/admin/MyLib/Library/binaries/linux/Release"]
you could say
"libraries": ["-lmylib", "-L'<!(pwd)'"]
assuming your libmylib.so file is in the same directory as binding.gyp.

**Comment by wlzla000** [comment]
**For making the path relative**, just use `module_root_dir`, which is a variable exposed by `node-gyp`.

```
"libraries": ["<(module_root_dir)/......"]
```

-----

`-Wl,-rpath,...` did not work for me, causing symbol lookup errors.

**Comment by nehasharan** [comment]
What is wrong in below code? It is throwing linking error.
'targets': [
    {
      'target_name': 'abc',
      'type': 'shared_library',
      'conditions': [],
      'dependencies': [],
      'libraries':[
          'mylib.a'
      ],
      'mac_framework_dirs' : [
      ],
      'all_dependent_settings': {},
    },

**Comment by phishoes** [comment]
> Just specify the path the to the static .a file in the "libraries" section:
> 
> ```python
>   "libraries": [ "/usr/local/lib/mylib.a" ]
> ```

Does this make it so in node you can call the function from mylib.a? If so, what would that formatting look like?

**Comment by csjjzhou** [comment]
thanks a lot!
