### ISSUE TITLE
Wrong node-gyp library path resolving for VS2012

### ISSUE THREAD

**Issue by AlexAtNet** [nodejs/node-gyp#329]
The property "libraries" is expected to be a relative path to the binding.gyp file. When the VS2012 Pro project type is selected, the library is resolved from the folder "build", not from the folder where the binding.gyp is.

Example:

```
binding.gyp:
{
  "targets": [
    {
      "target_name": "MyLib",
      "type": "shared_library",
      "sources": [ ... ],
      "conditions": [
        [ "OS=='win'", { "libraries": [
          "..\\Library\\binaries\\x64\\Release\\mylib.lib"
        ] } ]
      ]
    }
  ]
}

c:\...> dir ..\\Library\\binaries\\x64\\Release\\mylib.lib
   shows file info
c:\...> node-gyp configure --msvs_version=2012 && node-gyp build
   ...
   LINK : fatal error LNK1181: cannot open input file '..\Library\binaries\x64\Release\mylib.lib'
   ...
```

Adding one more "../" to the library path is workaround for this issue.

```
c:\...>node-gyp -v
v0.10.10
```

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.

**Comment by issuefiler** [comment]
@JayBeavers The former. Paths in `libraries` are still relative to `build/….vcxproj`, not `binding.gyp`.
