### ISSUE TITLE
Remove `<RuntimeTypeInfo>false</RuntimeTypeInfo>` from visual studio project release configuration

### ISSUE THREAD

**Issue by LaurentGoderre** [nodejs/node-gyp#335]
This option was causing all sorts of problem with node-sass. I discovered this problem because the debug version worked but not the release. I arrowed it down to this option.

**Comment by saper** [comment]
I think this can be closed. In the recent versions of node-sass we separate binding configuration (binding.gyp) which closely matches how node itself has been compiled and libsass.gyp which builds the C++11 library with lots of bells and whistles (rtti, exceptions, etc.). We supply now appropriate /GR and /EH options to the Visual Studio.

Most importantly, there is little that node-gyp can do better., except for better handling of desirable overrides #26 (in the comments).
