### ISSUE TITLE
variable override from the commandline isn't documented

### ISSUE THREAD

**Issue by joshmarinacci** [nodejs/node-gyp#338]
I want to override the OS variable from the commandline. After some searching I found the right way to do this is with:

node-gyp  configure --OS=raspberrypi

This option isn't documented anywhere on the wiki or manual.  Also, doing node-gyp --help says I should be able to do node-gyp <command> --help for more details on a command, but doing node-gyp configure --help actually runs the configure instead of giving me help.

**Comment by Trott** [comment]
@nodejs/node-gyp Should this remain open? I see some stuff in the README about overriding environment variables, but I'm pretty node-gyp ignorant and I'm not sure it's what is being referred to here.

**Comment by joshmarinacci** [comment]
Honestly I don't remember. This was over four years ago and I don't work on that project anymore, so I guess it's no longer relevant. I'll close it.
