### ISSUE TITLE
Please update gyp to add support for Visual Studio 2013

### ISSUE THREAD

**Issue by JayBeavers** [nodejs/node-gyp#339]
https://code.google.com/p/gyp/source/detail?spec=svn1763&r=1725

I've started down this path and found I could not simply swap in gyp r1725 as the calling convention seems to have changed.  I started modifying configure.js and node-gyp.js and found myself spiralling inward.

I will attempt to patch by bringing in the updated gyp files that add VS 2013 support without bringing in all updates to gyp.

While reviewing the gyp changes, I also noticed that support for --msvs_version has been dropped from newer versions of gyp.

**Comment by voltagex** [comment]
What path does ~/.node-gyp correspond to on Windows?

**Comment by gimelfarb** [comment]
@voltagex `C:\Users\<username>\.node-gyp` or using variables `%USERPROFILE%\.node-gyp`

**Comment by kierenj** [comment]
For me, .node-gyp doesn't have common.gypi.  A subfolder, 0.12.3, does - but that file doesn't contain the line with "msbuild_toolset".

This is after I removed and reinstalled, my node-gyp version is 1.0.3, installed globally...

I know this is closed, but it just doesn't seem resolved - I have VS 2013, installed the latest version, and  it doesn't work.. is there anything else I can try?

I get simply:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\....\node_modules\nightmare\node_modules\phantom\node_modules\dnode\node_modules\weak\build\weakref.vcxproj]

**Comment by keithl8041** [comment]
@kierenj did you follow [the instructions posted earlier detailing how to re-install node-gyp](https://github.com/TooTallNate/node-gyp/wiki/Updating-npm's-bundled-node-gyp). Solved my issue, I was getting the same as you.

**Comment by kierenj** [comment]
In the end after posting here a colleague told me to try setting the environment variable GYP_MSVS_VERSION to 2013, which worked instantly.  Yours may work too keith thanks, but I'd suggest others with the problem could try "setx GYP_MSVS_VERSION 2013 /M" from an admin command prompt / PowerShell too :)

**Comment by Sogl** [comment]
+100500!
Much pain with 'node-gyp'! 15 GB of Visual Studio versions/SP/tools downloaded...

For windows 7 I use VS 2010 and SDK 7.1 command prompt. This instructions can help:
https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

With Windows 8.1 pro and VS 2013 Express and SDK 8.1 I'm still get this error:
```
  bufferutil.cc
..\src\bufferutil.cc(7): fatal error C1083: Не удается открыть файл включение:
v8.h: No such file or directory [C:\Users\Артем\AppData\Roaming\npm\node_module s\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_module s\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcx proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Артем\AppData\Roaming\npm\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```
