### ISSUE TITLE
Problems on Mavericks with only Command Line Tools installed

### ISSUE THREAD

**Issue by OliverJAsh** [nodejs/node-gyp#341]
I have installed the Command Line Tools:

```
$ xcode-select --print-path
/Library/Developer/CommandLineTools
```

However, when anything tries to use `node-gyp`, I get the following error:

```
$ npm install bcrypt
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.7 install /Users/Oliver/Development/sbscribe/node_modules/bcrypt
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp: Error 1 running xcodebuild
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Oliver/Development/sbscribe/node_modules/bcrypt
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

On Mountain Lion it was possible to use this without installing the whole of Xcode, rather just the Command Line Tools. Is it possible to do this on Mavericks? How can I get it working?

N.B. This is on a **clean install** of Mavericks.

**Comment by cburmeister** [comment]
This still hasn't been fixed?

**Comment by jesstelford** [comment]
To re-iterate @Poohblah's [solution](https://github.com/TooTallNate/node-gyp/issues/341#issuecomment-33969512):

# The Error

`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

# The Solution

1. Run `which xcodebuild` in the terminal. If it gives no output, continue to step 2. If it gives output, then this solution will not work for you.
2. Create a file `/usr/local/bin/xcodebuild`. In that file, use your favourite editor to add the contents:
  ```bash
#!/bin/bash

exit 0
  ```
3. Save that file, and exit your editor.
4. Give the file the correct permissions by running `sudo chmod a+x /usr/local/bin/xcodebuild`
5. You're done! Re-runt he command that caused the error.

**Comment by neverfox** [comment]
I get this warning (whether I use 0.10, 0.11, 0.12, or io.js) but then everything seems to work fine anyway. I do get output from `which xcodebuild` (`/usr/bin/xcodebuild`) FWIW. I would prefer not to get the warning though, obviously, as it makes one wonder if everything is really alright.

**Comment by ilei** [comment]
Can you give me an answer?

**Comment by jesstelford** [comment]
@ilei 42.

**Comment by Ajithsou** [comment]
I have faced the same problem and resolved by installing the xcode6.

**Comment by HipsterZipster** [comment]
Problem still exists in Yosemite. Wish there was a way NOT to install 3GB xcode :-1:

**Comment by prashcr** [comment]
Not 3GB. Fully installed Xcode is 6GB according to AppCleaner, probably including libraries and frameworks outside Xcode. Utterly ridiculous that I have to give up 6GB on my 100GB SSD for something I'll never use.

**Comment by itajaja** [comment]
thanks @jesstelford, your solution worked perfectly! :+1:

**Comment by u2** [comment]
Thanks @Poohblah, it works for me.

**Comment by bdwyertech** [comment]
You can also symlink ```/usr/local/bin/xcodebuild``` to ```/usr/bin/true```

```bash
# Fix XcodeBuild Issue
if [[ -d '/Applications/XCode.app' ]] || [[ -d '/Developer/Applications/XCode.app' ]]; then
  echo 'Xcode Seems to be installed...'
else
  if [[ ! $(xcodebuild | grep 'requires Xcode') ]]; then
    echo 'Fixing the Xcodebuild issue by symlinking xcodebuild to true'
    ln -s /usr/bin/true /usr/local/bin/xcodebuild
    source '/etc/profile'
  fi
fi
```

**Comment by cebor** [comment]
Also get this error ...

**Comment by ivanreese** [comment]
Getting this error on El Capitan

**Comment by mourner** [comment]
`ln -s /usr/bin/true /usr/local/bin/xcodebuild` hint by @bdwyertech works perfectly, although I'm still not sure whether it has any unwanted side effects.

**Comment by jelpern** [comment]
I'm also getting this error. @bdwyertech @mourner can you explain where to put this code and how to run it, for someone who is less familiar with bash scripts?

Has anyone confirmed whether this works on El Capitan?

The only silver lining I've seen is that Xcode seems to have dropped in size down to \*only\* 4GB ...

**Comment by MarcDiethelm** [comment]
@jelpern: @bdwyertech's script (thank you!!) works for me under El Capitan (OSX 10.11). You can just put it in a new file anywhere, and call it e.g. `fix-xcodeless-build.sh`. Make it executable `chmod +x fix-xcodeless-build.sh`. And run it: `sudo ./fix-xcodeless-build.sh`.

**Comment by jelpern** [comment]
Thank you @MarcDiethelm. Would there be any downside to putting this in my .bash_profile? Also why does this need to be run as sudo?

**Comment by tcelestino** [comment]
Thanks @jesstelford, your solution worked for me on El Capitan.
