### ISSUE TITLE
Support matrix for Windows getting too large

### ISSUE THREAD

**Issue by JayBeavers** [nodejs/node-gyp#343]
I'm working on making changes to support VS 2013 and I was noticing that the test matrix is...wow...on Windows.  Here's what I'm looking at:

Windows XP x86
x Windows Vista x86
x Windows Vista x64
Windows 7 x86
Windows 7 x64
Windows 8 x86
Windows 8 x64

multiplied by:

Windows 7 SDK
Windows 8 SDK
Windows 8.1 SDK
VS 2010 Express
VS 2010 Full
VS 2012 Express
VS 2012 Full
VS 2013 Express
VS 2013 Full

Assuming we don't officially support Vista, we're still looking at a test matrix of 9 x 5 == 45 combinations.

I'd like to suggest we call out our officially supported matrix.  [Chromium build is called out](http://www.chromium.org/developers/how-tos/build-instructions-windows) at Windows 7 or later, x86 not supported, VS 2010SP1 + Windows 8 SDK.

This is a little funky, given that VS 2010 is a couple of generations back.  My suggestion for official support is:

Windows 7 x86, Windows 7 x64, Windows 8 x64
Windows 8.1 SDK, VS 2012 Express, VS 2012 Full, VS 2013 Express, VS 2013 Full

That's still a cross matrix of 15, so I'd recommend we test / fully support:

Windows 7 x86 + VS 2012 Express
Windows 7 x64 + VS 2013 Full
Windows 8.1 x64 + Windows 8.1 SDK

And we support (but do not test) VS 2012 Full and VS 2013 Express.

I also suggest we pull out support for VS 2010 (Express and Full) and Windows SDKs < 8.1 and simplify the logic.

@picisaurus, @isaacs, @sblom this has implications for Node on Windows support as well.

**Comment by Trott** [comment]
Should this remain open? @nodejs/node-gyp
