### ISSUE TITLE
Insufficient diagnostic output with npm install --verbose to find failure cases

### ISSUE THREAD

**Issue by JayBeavers** [nodejs/node-gyp#349]
See [issue 212 in node-serialport](https://github.com/voodootikigod/node-serialport/issues/212) for context.

When evaluating a verbose output log for a cause of build failure, I see a snippet like:

```
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: msbuild failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
```

This doesn't help me to figure out what's going wrong.  Missing information is:
- Version of compiler detected (2010? 2012? 2013?)
- Was the C++ compiler even installed?  Or is a different product (e.g. C# or Visual Basic) installed?
- Was what the log from the build failure?  Even the last line of the log would be helpful.  A link to the full log output would be nice.

**Comment by Trott** [comment]
Is this still a valid issue that should remain open? @nodejs/node-gyp

**Comment by rvagg** [comment]
I think this falls into "please open a pull request" territory
