### ISSUE TITLE
'module' object has no attribute 'script_main'

### ISSUE THREAD

**Issue by tj** [nodejs/node-gyp#363]
all the addons are exploding for some reason:

```
> bcrypt@0.7.7 install /home/ubuntu/projects/api/node_modules/bcrypt
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/projects/api/node_modules/bcrypt
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
```

version info:

```
node-gyp@0.12.1  /usr/local/lib/node_modules/node-gyp
node@0.10.22
python 2.7.5+
```

**Comment by davidlanger** [comment]
Just had the same issue on an Amazon Elastic Beanstalk Instance (64bit Amazon Linux 2014.03 v1.1.0 running Node.js). Had installed globally via `sudo yum install nodejs npm --enablerepo=epel` as I needed bunyan to view logs. This borked up my deployments with the same error (`AttributeError: 'module' object has no attribute 'script_main'`).

Solved by running `sudo yum remove gyp.noarch`. Thanks guys!

Beforehands, I tried to remove node via `sudo yum remove nodejs npm --enablerepo=epel` but this did not remove the gyp installation which affected the build.

**Comment by Jbudone** [comment]
Same problem on Amazon EC2, fixed w/ `sudo npm -g install node-gyp`

**Comment by darkoverlordofdata** [comment]
This worked on Mint 17, also. Thanks!!! I tried upgrading npm, node, switching py versions. It just shuffled the problem around. I thought I was going nuts. This fixed it:

sudo apt-get remove gyp

**Comment by LogeshEswar** [comment]
while running codebox I got an following error Module did not self-register the i used the code node-gyp rebuild. Now its showing this error. 

gyp: binding.gyp not found (cwd: /home/logesh/code/megam/workspace/codebox) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/logesh/code/megam/workspace/codebox
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
logesh@logesh-Aspire-E1-431:~/code/megam/workspace/codebox$ node -v
v0.12.4
logesh@logesh-Aspire-E1-431:~/code/megam/workspace/codebox$ npm -v
1.4.21
