### ISSUE TITLE
install error: Missing binding.gyp

### ISSUE THREAD

**Issue by DrYSG** [nodejs/node-gyp#367]
I am following up on issue #203 , I am assuming this is a different problem.

I did the following steps as you recommended:
1. Upgrade to VS2013 PRO (we have MSDN subscription)
2. upgrade node to v0.10.23
3. npm install node-gyp -g [works fine]
4. node-gyp clean [no problem]
5. node-gyp configure (error below)

I am glad to help in any way (but I am a node novice, and have booked next week to learn all I can).

![image](https://f.cloud.github.com/assets/2865368/1743367/760a1f66-640b-11e3-916f-271381e46b86.png)

**Comment by tk120404** [comment]
@DrYSG Can we close this issue?

**Comment by DrYSG** [comment]
@tk120404 well, I personally am not interested in this problem anymore. (I am not using leveldown)

**Comment by tk120404** [comment]
@DrYSG I hope this would have got fixed by now. So can you please close this
