### ISSUE TITLE
Ensuring correct version of <!(node)

### ISSUE THREAD

**Issue by glasser** [nodejs/node-gyp#371]
Is there a way to run Node via `<!(node)` (as, eg, nan suggests you do) and ensure you're running the exact version of node that is currently executing?

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.
