### ISSUE TITLE
Be more specific about what exactly to install with Windows 7 SDK

### ISSUE THREAD

**Issue by christiaanwesterbeek** [nodejs/node-gyp#373]
I find the Windows 7 SDK installation package to be quite large and I'm sure I don't need all parts.
![image](https://f.cloud.github.com/assets/465989/1805440/4f943b5e-6c81-11e3-8f54-8f9a2404c3a1.png)

Could you indicate which of the parts shown in the installation wizard are actually needed for node-gyp?

**Comment by tk120404** [comment]
@christiaanwesterbeek can we close this issue?

**Comment by christiaanwesterbeek** [comment]
Wow, 2013, yeah definitely. I'm sure it's easier these days to get it working on Windows.

**Comment by tk120404** [comment]
👍
