### ISSUE TITLE
EACCES error...

### ISSUE THREAD

**Issue by imaclean** [nodejs/node-gyp#377]
I am trying to install/build tesseract-js however it fails at the 'node-gyp rebuild' stage (detailed log below).  I can see from the logs that the module downloads along with the dependencies however fails to build (see below).  I have had tesseract-js build/deploy on a windows box and saw the same issue with an unrelated project on my linux box so I suspect the issue lies with my linux setup/environment.  Any ideas on where i can look?
This is my setup:
* Linux RH 5.9
* Python 2.7.5
* GCC 4.1.2
* Behind firewall/with proxy
*** OUTPUT ***
npm http GET https://registry.npmjs.org/tesseract-js
npm http 304 https://registry.npmjs.org/tesseract-js
npm http GET https://registry.npmjs.org/chai/1.3.0
npm http 304 https://registry.npmjs.org/chai/1.3.0

> tesseract-js@0.0.1 install /home/im80750/workspace/tools/node.js/lib/node_modules/tesseract-js
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:980:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
gyp ERR! System Linux 2.6.18-348.18.1.el5
gyp ERR! command "node" "/home/im80750/workspace/tools/node.js/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/im80750/workspace/tools/node.js/lib/node_modules/tesseract-js
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! tesseract-js@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tesseract-js@0.0.1 install script.
npm ERR! This is most likely a problem with the tesseract-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls tesseract-js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.18-348.18.1.el5
npm ERR! command "/home/im80750/workspace/tools/node.js/bin/node" "/home/im80750/workspace/tools/node.js/bin/npm" "install" "-g" "tesseract-js"
npm ERR! cwd /home/im80750/workspace/js
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/im80750/workspace/js/npm-debug.log
npm ERR! not ok code 0

**Comment by voltagex** [comment]
Could you retry with a newer version of Node or close this issue if you're no longer affected?

**Comment by imaclean** [comment]
Done
