### ISSUE TITLE
.mm files are compiled as cpp, no matter what.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nodejs/node-gyp#392]
I am trying to compile an addon that uses some mac-internal functions - and hence, it ends up being a .mm file. But when I add it, its interpreted as C++ instead - AND so are the included/imported files. It seems to know what #import is, but it doesnt seem to utilize it. I just get a bunch of error messages, that smell like they shouldn't be there.

I am going to attach my binding.gyp file, and the whole error message.

Find them here:
Output: http://puu.sh/6Fjxd.txt
binding.gyp: http://puu.sh/6FjyT.gyp

**Comment by tk120404** [comment]
@IngwiePhoenix can we close this issue?

**Comment by gibfahn** [comment]
If this is still an issue comment and I'll reopen.
