### ISSUE TITLE
having standalone gyp installed on windows causes npm to break

### ISSUE THREAD

**Issue by Pomax** [nodejs/node-gyp#400]
I had to install GYP (following the install instructions after checking out https://code.google.com/p/gyp/source/checkout) to compile some software on windows 7 (specifically, to compile OTS) and now notice that an `npm install` that installs packages that require node-gyp building fails quite hard, with about a million console log entries that look like the following:

```
ImportError: No module named gyp
bower outlayer#>=1.1 <2                   extract archive.tar.gz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Program Files (x86)\Python 2.7\lib\multiprocessing\forking.py", line 346, in main
    prepare(preparation_data)
  File "c:\Program Files (x86)\Python 2.7\lib\multiprocessing\forking.py", line 455, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
```

Running a `pip uninstall gyp` to remove the "real" version of gyp from the python package list and then running `npm install` again works, so it seems that somehow node-gyp gets confused by gyp being explicitly installed on the system.

**Comment by tk120404** [comment]
@Pomax Can you please close this issue

**Comment by gibfahn** [comment]
If this is still an issue comment and I'll reopen.
