### ISSUE TITLE
Link error LNK1104 including c++ lib and dll in binding.gyp

### ISSUE THREAD

**Issue by juditnile** [nodejs/node-gyp#401]
I need to connect my Node.js module with an external C++ dll.

In my project folder I have these files:
addon.js
binding.gyp
MathFuncsDll.dll
MathFuncsDll.h
MathFuncsDll.lib
test.cpp

This is the structure of my binding.gyp file:

{
  "variables": {
    "dll_files": ["MathFuncsDll.dll"]
  },
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "test.cpp"],
      "libraries": [ "MathFuncsDll.lib" ],
      "cflags!": [ "-fno-exceptions" ],
      "cflags": [ "-std=c++11" ],
      "cflags_cc!": [ "-fno-exceptions" ]
    }
  ]
}

Inside the test.cpp I have the include of MathFuncsDll.h and I also call some operations of this dll.

When I try to get my node file with the command "node-gyp configure build" I get this error:
LINK : fatal error LNK1181: no se puede abrir el archivo de entrada 'MathFuncsDll.lib' [C:\Projects\testAddon\build\addon.vcxproj]

What am I doing wrong?
I don't know if this is a bug or if I'm making a mistake.

Thanks in advance!

**Comment by ztooner** [comment]
Did you add "copies":... to your bindings.gyp?

**Comment by Shivani26Singh** [comment]
How to add dependence of shared_library in binding.gyp? Above case is not working. And how you are generating both .dll and .lib file . Please tell.
I have .node file of my C++ project and I want to refer this .node file in its Unit test project.
But I am unable to link .node/ .dll file in binding.gyp file of my Unit Test project.
If I build my C++ project with static library, I am able to execute my unit tests sucessfully.
