### ISSUE TITLE
node-gyp configure fails with an empty import statement

### ISSUE THREAD

**Issue by kesmit13** [nodejs/node-gyp#410]
When I run node-gyp in my project directory, I just get the following error.  It looks like an empty Python import statement, but I have no idea where it is coming from.

gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.25 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed:   File "<string>", line 1
gyp ERR! stack     import
gyp ERR! stack          ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:637:15)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:743:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:956:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Linux 2.6.32-131.0.15.el6.x86_64
gyp ERR! command "node" "/u/bin/node-gyp" "configure"
gyp ERR! cwd /u/nodejs/v8swat
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok

**Comment by a0viedo** [comment]
hey @kesmit13, it seems like you're using an old version of node. would you mind sharing the command you're using?

**Comment by kesmit13** [comment]
It's been years since I attempted this, so I don't even recall.  This issue can probably be closed.

**Comment by a0viedo** [comment]
cc @Trott
