### ISSUE TITLE
linux x64 node-gyp v 0.12 and node -v 0.10 "cannot find module"

### ISSUE THREAD

**Issue by aliph5** [nodejs/node-gyp#412]
Hi,

I recently upgraded to node v 0.10.x from node v 0.8.x and am no longer able to launch my app as I get the following error:

module.js:356
  Module._extensions[extension](this, filename);

It seems that the build files are not recognized any longer. However, when I use NVM to switch back to v 0.8 and then configure/build my classes, everything works as expected.

**Comment by jakwings** [comment]
Have you reinstall node-gyp for 0.10.x and 0.12.x?

**Comment by maclover7** [comment]
I think this is safe to close since this issue has been inactive for many years, and Node.js versions v0.x has unsupported for several years, as well. Please reopen if you can reproduce with Node.js 6.x, 8.x, or 10.x, and a newer version of `node-gyp`.
