### ISSUE TITLE
Cannot use node.js file descriptors in addon on windows (EBADF)

### ISSUE THREAD

**Issue by insidiator** [nodejs/node-gyp#416]
I am not sure if this is the correct place for my issue, so please forgive me if it turns out to be unrelated to node-gyp :)

I tried to use the node-fs-ext plugin (https://github.com/baudehlo/node-fs-ext) on windows, but it does not work, because file descriptors that come from the node.js filesystem functions are not recognized.

I added a function that opens a file to the plugin to test if something is wrong with the plugin itself, but the file pointers that I create inside the plugin work fine.
Conversely the pointers returned by my function do not work with the standard node.js functions.

After a lot of googling and trying things, I found a somewhat similar problem here http://osdir.com/ml/python.ctypes/2006-06/msg00087.html thus I suspect that there is some kind of mismatch between the runtime libraries in use.

As I am not a C++ developer I am not really sure what I can do about that, so I would be really grateful if somebody could point me in the right direction.

My setup:
Windows 7 x64
Windows SDK v7.1
Python 2.7.5
node-gyp@0.10.10
node@0.10.20 | win32 | x64

**Comment by JCMais** [comment]
Is that something we should still be aware? Or it was in someway fixed?

**Comment by davedoesdev** [comment]
This is still an issue (encountered it in `fs-ext`) but difficult to see a solution.

**Comment by bnoordhuis** [comment]
I'll close the report, it's not a node-gyp issue.  Maybe it should be reported against nodejs/node, although I don't see a short-term solution.

**Comment by davedoesdev** [comment]
Issue is now fixed (see https://github.com/nodejs/node/issues/6369)
