### ISSUE TITLE
Build fails on Windows 8.1. Upgrade .vsxproj

### ISSUE THREAD

**Issue by koistya** [nodejs/node-gyp#431]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [node_modules\contextify\build\contextify.vcxproj]

C++ 2010 cannot be installed on Windows 8.1, can it? Where this .vcxproj comes from? Maybe I could help to upgrade it, making it compatible with VS2013..

**Comment by globexdesigns** [comment]
+1 having the same issue. Have VS 2015 installed, but that doesn't seem to help. I can't find any links to allow me to install VS 2013.

**Comment by orangemocha** [comment]
You can still download VS 2013 here: https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#d-community

**Comment by rvagg** [comment]
closing due to staleness
