### ISSUE TITLE
Not enough information on failed build/install

### ISSUE THREAD

**Issue by rvagg** [nodejs/node-gyp#432]
Normally we get enough information to debug these kinds of issues, but if you look at the output provided @ rvagg/node-leveldown#92 you'll see that we have zero to go on. `make` is giving exit code 2 and therefore should be providing output. Any suggestions or could this possibly be an issue to file against npm?

**Comment by viljowilding** [comment]
Hey @rvagg, can this issue be closed? I figure it's four years old so you hopefully found a solution 👍

**Comment by gibfahn** [comment]
If it's still an issue we can raise a new one.
