### ISSUE TITLE
gyp_main.py: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by dibu28** [nodejs/node-gyp#434]
"gyp_main.py: error: no such option: --no-parallel"
"Error: `gyp` failed with exit code: 2"

Then I try to install pm2 or sleep packages. "npm install pm2 -g"

Or then I try to run "node-gyp configure"

How to fix this?

**Comment by Trott** [comment]
@nodejs/node-gyp Should this remain open?

**Comment by bnoordhuis** [comment]
No, should be fixed.  If anyone still encounters this, make sure you don't have an old copy of gyp (not node-gyp) on your path.
