### ISSUE TITLE
Auto detect VS2012 / VS2013 / VS2010

### ISSUE THREAD

**Issue by adaptabi** [nodejs/node-gyp#435]
Sometimes installing third party libraries, `node-gyp` fails during `rebuild`

```
npm config set msvs_version 2012
```

This for example can fix the rebuild, if you don't have VS2010 at all, but just 2012/2013.
However, this should not happen at all.

Please auto-detect (it's fairly easy) the version of VS the user has installed.
e.g. Look for such folder, or maybe a smarter way.

```
c:\Program Files (x86)\Microsoft Visual Studio 10.0
c:\Program Files (x86)\Microsoft Visual Studio 11.0
c:\Program Files (x86)\Microsoft Visual Studio 12.0
```

**Comment by rvagg** [comment]
closing due to staleness, I think this is all sorted now anyway
