### ISSUE TITLE
npm install issue with node-gyp rebuild

### ISSUE THREAD

**Issue by Darper** [nodejs/node-gyp#438]
I've followed the instructions in the read-me file, but can't get node-gyp rebuild to work with multiple modules. I've attached a screen shot of the errors I get when trying to run npm install, any help would be appreciated.

![node-gyp rebuild](https://cloud.githubusercontent.com/assets/6515956/2881656/9c9d0860-d485-11e3-92b8-0d0f446490a2.jpg)

**Comment by a0viedo** [comment]
hey @Darper, is this still an issue?

**Comment by Darper** [comment]
I'm not sure. I don't even remember which application I was trying to run when this occurred. Sorry.

**Comment by a0viedo** [comment]
Then I guess we can close this for now and there's still an issue it can re-opened or you can create a new issue. cc @Trott
