### ISSUE TITLE
Build 32 and 64 bits under Windows

### ISSUE THREAD

**Issue by LaurentGoderre** [nodejs/node-gyp#443]
In order to successfully build for the two configuration under Windows I had to do the following tweaks and I'm wondering if there is value in adding those to the project.
1. Changed the Additional Dependencies from
   `kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;"c:\Users\Laurent\.node-gyp\0.10.28\$(Configuration)\node.lib"`
   to
   `kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;"c:\Users\Laurent\.node-gyp\0.10.28\$(Plateform)\node.lib"`
2. Copy the file `.node-gyp\0.10.28\ia32\node.lib` to `.node-gyp\0.10.28\Win32\node.lib

**Comment by rvagg** [comment]
closing due to staleness, I think this might be resolved now anyway?
