### ISSUE TITLE
meteor installation fails on linux  - EPERM UNCAUGHT EXCEPTION 

### ISSUE THREAD

**Issue by prabhatsharma** [nodejs/node-gyp#449]
$npm -g install meteor
npm http GET https://registry.npmjs.org/meteor
npm http 304 https://registry.npmjs.org/meteor
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/less
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/nib
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/useragent
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stream-buffers
npm http GET https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/sockjs
npm http GET https://registry.npmjs.org/progress
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/fibers
npm http GET https://registry.npmjs.org/gzippo
npm http GET https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/stylus
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/less
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/mongodb
npm http 304 https://registry.npmjs.org/clean-css
npm http 304 https://registry.npmjs.org/nib
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/useragent
npm http 304 https://registry.npmjs.org/stream-buffers
npm http 304 https://registry.npmjs.org/simplesmtp
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/http-proxy
npm http 304 https://registry.npmjs.org/sockjs
npm http 304 https://registry.npmjs.org/progress
npm http 304 https://registry.npmjs.org/mailcomposer
npm http 304 https://registry.npmjs.org/fibers
npm http 304 https://registry.npmjs.org/gzippo
npm http 304 https://registry.npmjs.org/connect
npm WARN engine gzippo@0.1.7: wanted: {"node":">= 0.5 < 0.9"} (current: {"node":"v0.10.28","npm":"1.4.9"})
npm http GET https://registry.npmjs.org/yamlparser
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/rai
npm http GET https://registry.npmjs.org/xoauth2
npm http GET https://registry.npmjs.org/mimelib-noiconv
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/faye-websocket
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/formidable
npm http GET https://registry.npmjs.org/qs

> fibers@0.6.9 install /usr/lib/node_modules/meteor/node_modules/fibers
> node ./build.js

gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: EPERM, utime '/home/prabhat/.node-gyp/0.10.28'
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/meteor/node_modules/fibers
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues
Build failed
npm http 304 https://registry.npmjs.org/yamlparser
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/xoauth2
npm http 304 https://registry.npmjs.org/rai
npm http 304 https://registry.npmjs.org/mimelib-noiconv
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/faye-websocket
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/formidable
npm ERR! fibers@0.6.9 install: `node ./build.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the fibers@0.6.9 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "meteor"
npm ERR! cwd /home/prabhat
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/meteor/node_modules/mongodb/.coverage_data/1/rcover_4e6a938eeb7a2140d74cc6592a1df80f'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "-g" "install" "meteor"
npm ERR! cwd /home/prabhat
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /usr/lib/node_modules/meteor/node_modules/mongodb/.coverage_data/1/rcover_4e6a938eeb7a2140d74cc6592a1df80f
npm ERR! fstream_path /usr/lib/node_modules/meteor/node_modules/mongodb/.coverage_data/1/rcover_4e6a938eeb7a2140d74cc6592a1df80f
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/prabhat/npm-debug.log
npm ERR! not ok code 0

**Comment by a0viedo** [comment]
hey @prabhatsharma, did you managed to solve this issue?

**Comment by prabhatsharma** [comment]
@a0viedo Its been a couple of years now and I don't remember now.... I guess I never really picked meteor...

**Comment by a0viedo** [comment]
this can be closed now cc @Trott
