### ISSUE TITLE
install failed on windows 7 64 bit

### ISSUE THREAD

**Issue by rech** [nodejs/node-gyp#455]
I have tried the instructions but I get this error message:
Error: no compatible version found: ansi@'0.3.0'
valid install targets:

at installTargetsError c:\program files\nodejs\node_modules\npm\lib\cache.js:553:10

I do have supported version of node.js so whats the problem?

**Comment by maclover7** [comment]
Closing since this is an `npm` issue, not a problem with `node-gyp`. `npm` maintains a tracker [here](https://npm.community/c/bugs) for support/bugs.
