### ISSUE TITLE
Throw errors: c++: error: unrecognized command line option ‘-stdlib=libc++’

### ISSUE THREAD

**Issue by haohcraft** [nodejs/node-gyp#458]
I was installing `node-gyp build` for node-opencv but threw the error:

  CXX(target) Release/obj.target/opencv/src/init.o
c++: error: unrecognized command line option ‘-stdlib=libc++’
make: **\* [Release/obj.target/opencv/src/init.o] Error 1

any idea about this? Thanks.

p.s. 

haos-mbp-2:node-opencv Hao$ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.28 | darwin | x64
0.10.28
gyp info ok

**Comment by MatthewRalston** [comment]
Either this issue is so simple to fix that the developers are just ignoring all other developers with zero C++ experience or there isn't a fix for this yet in 2018 with Node-gyp being used in production systems across the globe. What a shame elitism is.

**Comment by bnoordhuis** [comment]
🙄 <- love this emoji.

I'll close this out - this issue should have been reported to the node-opencv project, not here.
