### ISSUE TITLE
How do I reference System/System.Core?

### ISSUE THREAD

**Issue by tkiela** [nodejs/node-gyp#466]
Hey there,

I need to compile a .NET C++/CLI application with references to System.
In special, I need the following entries in the vxproj file:

```
<ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
</ItemGroup>
```

I tried referencing the DLL-files in the "libraries" parameter, but that did not work.
I also tried to copying the files to an subfolder in my build folder and referencing this folder in "include_dirs", but this did not work neither.

So, how do I reference these libraries?

**Comment by viljowilding** [comment]
Hey, this is a pretty old issue, could it be closed? 👍

**Comment by maclover7** [comment]
It seems like this is an issue with a project `binding.gyp` file, and isn't a bug within `node-gyp`. Going to give this a close for now, but please reopen if I'm wrong :)
