### ISSUE TITLE
OS X 10.9: node-gyp links to libstdc++ instead of libc++

### ISSUE THREAD

**Issue by andrewaustin** [nodejs/node-gyp#469]
In OS X 10.9, Apple switched from gcc to clang which results in a change in the name of the standard library name from libstdc++ (gcc) to libc++ (clang).

However, it seems all modules compiled with node-gyp are linked against libstdc++ on OS X 10.9 . (For example, https://github.com/tbonelaforge/jinac/blob/master/binding.gyp ) Because dynamic libraries that node modules may link against are compiled on 10.9 with clang, there are issues resolving symbols in the standard library.

```
node-gyp -v
v0.13.1
```

I realize I can manually set the stdlib to be what it should be with `"OTHER_CFLAGS": ["-stdlib=libc++"]` but this will cause issues on OS X < 10.9.

**Comment by richardlau** [comment]
Node.js 7 onwards specifies linking against `libc++`:
https://github.com/nodejs/node/blob/09b85e2b04e560066df584fe3cc9acda822b0d18/common.gypi#L404
For [supported versions of Node.js](https://github.com/nodejs/Release/blob/master/README.md), this should only still be an issue for Node.js 6 (which doesn't specify the library to link against and uses the default). Node.js 6 will be end-of-life in April.

**Comment by rinogo** [comment]
There's a lot of "noise" on this page - for those who hit this via Google, the solution is simple - update to a newer version of Node.
