### ISSUE TITLE
Fetch all dependencies by itself

### ISSUE THREAD

**Issue by CamiloMM** [nodejs/node-gyp#477]
This may sound unrealistic, but I think it would be magnificient; would it be possible to node-gyp to download its own dependencies on a subset of the supported platforms (like Mac and Windows)?

I mean, the project seems to aim to _"[take] away the pain of dealing with the various differences in build platforms"_, but from a look at the current issues and the set of requirements, for somebody on Windows it's so bloody annoying to set up I am considering whether or not to use some modules that depend on node-gyp just for the advantage of not having to bother with node-gyp, and would never use it in its current state by myself.

I mean, I just want to install a package that depends on node-gyp. For this I need to:
- Install Python.
- Find out that by mistake, I installed the current version of Python, and instead I need a version that became obsolete more than half a decade ago.
- Install the entirety of Visual Studio 2010. It doesn't say that I can also install 2012 or 2013. What if I have either of those?
- Also install the Windows 7 64-bit SDK.
- Maybe that will fail so I'll have to uninstall C++ redistributables first.
- Maybe I'll get errors and need the compiler update for the Windows SDK 7.1
- Microsoft Visual Studio C++ 2012 for Windows Desktop too, because just one version of Visual Studio is clearly not enough. Do I need Office XP too? What about my choice of media player?

As you can see, by then I would already have felt the huge pain associated with using any package that requires node-gyp for the first time.

So my question is: how feasible would it be to e.g. download python and use that if the required version is not installed? What about not requiring the whole of Visual Studio, and if possible just downloading a compiler for Windows? I really think the only downside is setup time increasing, but it would be drastically easier and faster than having the user hunt for what to download.

**Comment by rvagg** [comment]
mostly solved with `windows-build-tools` package now I think, see https://github.com/nodejs/node-gyp#on-windows
