### ISSUE TITLE
Update readme to allow VS2013 as a prerequsite

### ISSUE THREAD

**Issue by SteveALee** [nodejs/node-gyp#478]
Accordingto #348 all has been well with VS 2013 for a while but the readme still restricts to VS 2012 (and inks to the 2012 installer). VS 2012 is no longer availabe officially from MS (at least it's not on the download page http://www.visualstudio.com/downloads/download-visual-studio-vs0)

Perhaps readme can just say 2012/2013?

If this is approved I can provide a pull request.

**Comment by a0viedo** [comment]
I think this one is outdated and no longer relevant, the README references VS 2015 now. cc @Trott
