### ISSUE TITLE
Error: "pre" versions of node cannot be installed, use the --nodedir flag instead

### ISSUE THREAD

**Issue by wyzwhp** [nodejs/node-gyp#490]
When npm install ,show error 
gyp ERR! configure error
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag ins
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/ins
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib                                          modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:722:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:999:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1167:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:461:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.
gyp ERR! cwd /data/wsites/wyx/node_modules/canvas
gyp ERR! node -v v0.13.0-pre
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

**Comment by carrickdb** [comment]
This is still an issue, and the fix mentioned [here](https://github.com/nodejs/node-gyp/wiki/Error:-%22pre%22-versions-of-node-cannot-be-installed) makes no difference.

**Comment by bnoordhuis** [comment]
The wiki is correct, though.  Since this is a very old issue, I'll go ahead and close it out.

@carrickdb Can you file a new issue and include everything the issue template asks for?  Thanks.
