### ISSUE TITLE
Error while Installing Phantom

### ISSUE THREAD

**Issue by testvgs7** [nodejs/node-gyp#493]
E:\workspace>npm install phantom
npm http GET https://registry.npmjs.org/phantom
npm http 304 https://registry.npmjs.org/phantom
npm http GET https://registry.npmjs.org/win-spawn
npm http GET https://registry.npmjs.org/dnode
npm http GET https://registry.npmjs.org/shoe
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/dnode
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/shoe
npm http 304 https://registry.npmjs.org/win-spawn
npm http GET https://registry.npmjs.org/dnode-protocol
npm http GET https://registry.npmjs.org/jsonify
npm http GET https://registry.npmjs.org/sockjs/0.3.7
npm http GET https://registry.npmjs.org/weak
npm http 304 https://registry.npmjs.org/weak
npm http 304 https://registry.npmjs.org/dnode-protocol
npm http 304 https://registry.npmjs.org/sockjs/0.3.7
npm http 304 https://registry.npmjs.org/jsonify
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/faye-websocket/0.4.4
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/faye-websocket/0.4.4

> weak@0.3.3 install E:\workspace\node_modules\phantom\node_module
> s\dnode\node_modules\weak
> node-gyp rebuild

E:\workspace\node_modules\phantom\node_modules\dnode\node_modules\
weak>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node
_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/node-uuid/1.3.3
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
E:\workspace\node_modules\phantom\node_modules\dnode\node_modules
\weak\build\weakref.vcxproj(18,3): error MSB4019: The imported project "E:\Micr
osoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> d
eclaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\workspace\node_modules\phantom\node_modules\dnode\
node_modules\weak
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm WARN optional dep failed, continuing weak@0.3.3
phantom@0.6.5 node_modules\phantom
├── win-spawn@2.0.0
├── traverse@0.6.6
├── shoe@0.0.15 (sockjs@0.3.7)
└── dnode@1.2.0 (jsonify@0.0.0, dnode-protocol@0.2.2)

E:\workspace>

**Comment by tk120404** [comment]
@testvgs7 Please close this issue
