### ISSUE TITLE
Submitted request for MinGW GCC compiler support for Windows to Google GYP team

### ISSUE THREAD

**Issue by tohagan** [nodejs/node-gyp#494]
I've just submitted this request to the Google GYP team to ask them to support MinGW GCC on Windows so that at least you have a way forward to remove the dependency on Visual Studio that prevents many Windows users making use of Node component that require C++/node-gyp.  Obviously the problem is not with node-gyp but with gyp itself. 

I made it clear in my submission that I'm not part of the Joyent Node team or node-gyp project.
- https://code.google.com/p/gyp/issues/detail?id=448

NOTE: This issue is also a major road block for system admins wanting to use Node on a production Window Server host as installing Visual Studio adds debugging hooks into the OS that you don't want on a production host. GCC is much less invasive and light weight and all  you need if installed with NodeJS for Windows.

**Comment by rvagg** [comment]
closing due to staleness, probably something to get sorted out in https://github.com/refack/GYP
