### ISSUE TITLE
How can I make node-gyp really verbose?

### ISSUE THREAD

**Issue by ralphtheninja** [nodejs/node-gyp#496]
I'm starting from scratch with a project and need to see exactly what compiler flags are fed to `gcc` so I know it's correct.

**Comment by Fishrock123** [comment]
`--verbose` or `--silly`

If using npm, `--loglevel=verbose` or `--loglevel=silly`

**Comment by tmm1** [comment]
Is there a npm_config_ equivalent env var for this?
