### ISSUE TITLE
Hello World example does not compile (Windows 8.1)

### ISSUE THREAD

**Issue by vohof** [nodejs/node-gyp#497]
I followed carefully the steps:

```
$ node-gyp configure
$ node-gyp build
```

But came across this error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.1
gyp info using node@0.10.31 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
..\binding.cc(6): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
..\binding.cc(6): error C2143: syntax error : missing ',' before '<' [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
..\binding.cc(8): error C2664: 'v8::HandleScope::HandleScope(const v8::HandleScope &)' : cannot convert argument 1 from 'v8::Isolate *' to 'const v8::HandleScope &' [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
          Reason: cannot convert from 'v8::Isolate *' to 'const v8::HandleScope'
          No constructor could take the source type, or constructor overload resolution was ambiguous
..\binding.cc(9): error C2065: 'args' : undeclared identifier [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
..\binding.cc(9): error C2228: left of '.GetReturnValue' must have class/struct/union [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
          type is 'unknown-type'
..\binding.cc(9): error C2228: left of '.Set' must have class/struct/union [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
..\binding.cc(9): error C2039: 'NewFromUtf8' : is not a member of 'v8::String' [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
          c:\Users\vohof\.node-gyp\0.10.31\deps\v8\include\v8.h(1024) : see declaration of 'v8::String'
..\binding.cc(9): error C3861: 'NewFromUtf8': identifier not found [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
..\binding.cc(13): error C2664: 'void node::SetMethod<v8::Handle<v8::Object>>(target_t,const char *,v8::InvocationCallback)' : cannot convert argument 3 from 'void (__cdecl *)(const int)' to 'v8::InvocationCallback' [C:\Users\vohof\AppData\Local\Temp\test\build\binding.vcxproj]
          with
          [
              target_t=v8::Handle<v8::Object>
          ]
          Incompatible calling conventions for UDT return value
```

[Here's the `binding.vcxproj` created.](https://gist.github.com/vohof/8f229ddf7f531a2ab3c4) BTW, I have Visual Studio express 2013 for Desktop.

**Comment by masadhashmi** [comment]
it is problem with node-gyp v8 Setup...

**Comment by masadhashmi** [comment]
i am having this error... please help

D:\Innovent Integrated Solutions\Projects\node\addon>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hello.cc
..\hello.cc(6): error C3861: 'NanScope': identifier not found [D:\Innovent Integrated Solutions\Projects\node\addon\bui
ld\hello.vcxproj]
..\hello.cc(7): error C2039: 'New': is not a member of 'v8::String' [D:\Innovent Integrated Solutions\Projects\node\add
on\build\hello.vcxproj]
  c:\users\m asad hashmi\.node-gyp\6.10.0\include\node\v8.h(2110): note: see declaration of 'v8::String'
..\hello.cc(7): error C3861: 'New': identifier not found [D:\Innovent Integrated Solutions\Projects\node\addon\build\he
llo.vcxproj]
..\hello.cc(7): error C3861: 'NanReturnValue': identifier not found [D:\Innovent Integrated Solutions\Projects\node\add
on\build\hello.vcxproj]
..\hello.cc(11): error C3861: 'NanSymbol': identifier not found [D:\Innovent Integrated Solutions\Projects\node\addon\b
uild\hello.vcxproj]
..\hello.cc(11): error C2665: 'v8::FunctionTemplate::New': none of the 2 overloads could convert all the argument types
 [D:\Innovent Integrated Solutions\Projects\node\addon\build\hello.vcxproj]
  c:\users\m asad hashmi\.node-gyp\6.10.0\include\node\v8.h(4483): note: could be 'v8::Local<v8::FunctionTemplate> v8::
  FunctionTemplate::New(v8::Isolate *,v8::FunctionCallback,v8::Local<v8::Value>,v8::Local<v8::Signature>,int)'
  ..\hello.cc(11): note: while trying to match the argument list '(overloaded-function)'
..\hello.cc(11): error C2227: left of '->GetFunction' must point to class/struct/union/generic type [D:\Innovent Integr
ated Solutions\Projects\node\addon\build\hello.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\M Asad Hashmi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\M Asad Hashmi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\Innovent Integrated Solutions\Projects\node\addon
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by billti** [comment]
I just spent a while wrestling with this and similar errors, and after looking at the macros figured out it was because the name of the add-in I was trying to build had a "-" character in the name. I would try to ensure that your folder name for your code, and your `target_name` property in the `binding.gyp` file does not have any spaces or dashes in it. (Basically, try to keep it to a simple ASCII string that would be a valid identifier name).

I must say, trying to get node-gyp working in general has been super painful. (I had VS 2017 on my machine and tried to get that working for a while before giving up).

**Comment by maclover7** [comment]
It seems like using an outdated version of Node.js was causing this, so upgrading Node.js / `node-gyp` to a supported version should fix this problem. Going to close this this ticket for now since a fix has been identified.

**Comment by bpasero** [comment]
I am still hitting this issue with node `10.16.0`. See https://github.com/the-ress/node-windows-foreground-love/pull/2#issuecomment-511400223
