### ISSUE TITLE
Hang on win7 x64

### ISSUE THREAD

**Issue by adrianhara** [nodejs/node-gyp#512]
I'm trying to install karma on a win7 x64 machine like so "npm install -g karma" but it hangs at the following message:

> ws@0.4.32 install C:\Users\developer\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I tried "npm install -g node-gyp" which works, however running e.g. "node-gyp configure" hangs as well:

`gyp info it worked if it ends with ok`
`gyp info using node-gyp@1.0.2`
`gyp info using node@0.10.31 | win32 | x64`

I have Python 2.7.3 installed and in PATH. Any idea what I'm missing?

**Comment by gibfahn** [comment]
If you still get this error after following the instructions at https://github.com/nodejs/node-gyp/#on-windows then let me know and I'll reopen.
