### ISSUE TITLE
Shared library build, cflags & gcc ignoring unused functions

### ISSUE THREAD

**Issue by jas-** [nodejs/node-gyp#513]
I have been scouring the web, irc & other sources such as the gyp support forums but have been unable to find the necessary cflag I am looking for.

If I build the shared object outside of `node-gyp` I can specify `-Wl,--whole-archive` and `gcc` will compile all files and not ignore anything that is not explicitly called.

When I try to do the same from `node-gyp` (v1.0.1) it includes the flag during compile which can be verified with `node-gyp build --verbose` but appends `-Wl,--no-whole-archive` once it links all built objects together.

Here are the relevant parts of the `binding.gyp` I am working with.

``` json
{
  "targets": [{
     "target_name": "test",
     "type": "shared_library",
     "conditions": [
       ['OS=="linux"', {
         "cflags": [
           "-O3",
           "-fPIC",
           "-std=gnu99",
           "-Wl,--whole-archive"
         ],
       }],
    "sources": [
      /* ... */
    ],
  },
  {
  "target_name": "lib",
  "type": "loadable_module",
  "dependencies": [
    "test",
   ],
  /* ... */
}
```

A sample output (relevant portion) with verbosity on:

```
  flock ./Release/linker.lock g++ -shared -pthread -rdynamic -m64  -Wl,-soname=test.so -o Release/obj.target/test.so -Wl,--whole-archive ./Release/obj.target/test/src/one.o ./Release/obj.target/test/src/two.o ./Release/obj.target/test/src/three.o ./Release/obj.target/test/src/four.o -Wl,--no-whole-archive -pthread
  SOLINK(target) Release/obj.target/test.so: Finished
  rm -rf "Release/test.so" && cp -af "Release/obj.target/test.so" "Release/test.so"
```

**Comment by Trott** [comment]
@nodejs/node-gyp Should this remain open?
