### ISSUE TITLE
Looking for help on android

### ISSUE THREAD

**Issue by yaronyg** [nodejs/node-gyp#515]
I'm building node.js for android (http://www.goland.org/nodejsonandroid/) but now I need to use NPM with node-gyp but I want to cross-compile for Android. Looking around the node-gyp code base the make files seem to want to support this. But I haven't even managed yet to figure out how to force '-f android' during Configure. I actually did this manually on the command line and it caused an 'undefined variable os_include' error down in snappy. Rather than trying to reverse engineer node-gyp's support of Android is there a 'hello world' anywhere that shows how to use node-gyp to compile on Linux a package that is targeted at Android? What parameters to pass in? What environment variables are needed? Etc.

Thanks!

**Comment by tk120404** [comment]
@yaronyg  Can you please close this issue if this is not an issue any more?

**Comment by yaronyg** [comment]
I left this work behind a long time ago.

**Comment by tk120404** [comment]
👍
