### ISSUE TITLE
Is Visual Studio really required?

### ISSUE THREAD

**Issue by DesperateGuy** [nodejs/node-gyp#517]
A few days ago I was able to install `gulp-sass` and `socketio` modules without any problem, but what I want to mention is that I haven't had to install Visual Studio. Right now I'm on a fresh Windows 8.1 (64bit) and there is that warning about missing Visual Studio.

**I have two questions:**
- Is there any alternative to Visual Studio? I am asking because VS 2013 is solving the problem, but also making very big mess on my computer:

![zrd1ng1](https://cloud.githubusercontent.com/assets/9320739/4702535/b1d76efc-5863-11e4-8371-baa8dfb0fc32.png)
- What was that on my previous OS that allowed me to install those modules without a trouble? There must be something, I just can't install all this MS stuff, if it was only one program, not 100 of them, then problem would be solved.

Please help me.

**Comment by anyong** [comment]
Isn't there any way to provide the needed bits as precompiled binaries? Pretty silly that I have to download 5 GB of Visual Studio crud just to install jest for testing my ReactJS app.

**Comment by JayBeavers** [comment]
You may be able to get away with just the Windows 8,1 SDK (https://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx).  I haven't tried this myself, so this is just an idea.

**Comment by simmani5** [comment]
I found same problem . after install free  MS Visuals studio 2019 .
I saw   install node js during install MS Visual Studio 2019 .. so I thout  it cause some proble. to me. 
but any way  install done . and I did not use MS VS2019 but..

im tried  intsall 
    git clone git@github.com:andrew/node-sass-example.git
    cd node-sass-example
    npm install  << Error here
    node server.js
    open http://localhost:8000

I think it cause VS 2019 setup . may be..
debug.log === under ===here===
4778 verbose pkgid node-sass@3.13.1
4779 verbose cwd D:\_hom\github\andrew\node-sass-example
4780 verbose Windows_NT 10.0.17763
4781 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
4782 verbose node v10.16.0
4783 verbose npm  v6.9.0
4784 error code ELIFECYCLE
4785 error errno 1
4786 error node-sass@3.13.1 postinstall: `node scripts/build.js`
4786 error Exit status 1
4787 error Failed at the node-sass@3.13.1 postinstall script.
4787 error This is probably not a problem with npm. There is likely additional logging output above.
4788 verbose exit [ 1, true ]
=============

**Comment by simmani5** [comment]
I found same problem . after install free  MS Visuals studio 2019 .
I saw   install node js during install MS Visual Studio 2019 .. so I thout  it cause some proble. to me. 
but any way  install done . and I did not use MS VS2019 but..

im tried  intsall 
    git clone git@github.com:andrew/node-sass-example.git
    cd node-sass-example
    npm install  (((=== Error here )))
    node server.js
    open http://localhost:8000
### 
I think it cause VS 2019 setup . may be..
debug.log === under ===here===
4778 verbose pkgid node-sass@3.13.1
4779 verbose cwd D:\_hom\github\andrew\node-sass-example
4780 verbose Windows_NT 10.0.17763
4781 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
4782 verbose node v10.16.0
4783 verbose npm  v6.9.0
4784 error code ELIFECYCLE
4785 error errno 1
4786 error node-sass@3.13.1 postinstall: `node scripts/build.js`
4786 error Exit status 1
4787 error Failed at the node-sass@3.13.1 postinstall script.
4787 error This is probably not a problem with npm. There is likely additional logging output above.
4788 verbose exit [ 1, true ]
=============

**Comment by a0viedo** [comment]
I would suggest opening a new issue @simmani5
