### ISSUE TITLE
Please update Installation for Windows 7

### ISSUE THREAD

**Issue by ndejesus1227** [nodejs/node-gyp#518]
Hello Nate, 

Thank you for your work!

I went through hell and back trying to get node-gyp to install (I wanted to use bcrypt). I followed the installation instructions you gave in the Read.me but nothing worked. Spent about 4 days crying, seeing tons of people having the same issues, starting with the VC Build and more and more after. I wasn't able to find a solution until I came across this:

https://github.com/TooTallNate/node-gyp/issues/154

Where @JayBeavers  mentions to installing VS 2013.

So I removed ALL components that node-gyp relied on, the dozen of MS visual studio redistributables and anything related to Windows SDK (except for Python, I didn't re-install that). And I went straight for the VS 2013 WITH the update package 3 alone (this took about 5 hours at work to download).

After that I was able to install node-gyp with a few warnings, but eventually I got to install bcrypt which was the ultimate goal.

I sucks that I had to dig all the way through these issues until I found a solution, would have been nice if under the installation section if you just had Python 2.x and MS Visual Studio 2013 with update 3.

If I'm mistaken, I apologize and please let me know if I could have done it better. This was just from my experience I'm speaking from. 

Again, thank you for all of your hard work, I aspire to contribute to the community as you do some day.

Regards,

Nick DeJesus

**Comment by bjlbernal** [comment]
Thank you @erikreppen for your comment on Nov 16, 2014. Saved me from waiting for a solution.

**Comment by thoroc** [comment]
Just wasted 4 hours on troubleshooting this. Would it not be a better option to drop completely the visual C++ compiler and go for another one distributed through saner means?

**Comment by dsebastien** [comment]
@thoroc +1 for dropping that.. and also not requiring the whole *damn* Windows SDK would be nice for w8+ ;-). 

After wasting a whole evening I couldn't resist but complain a little bit: https://www.dsebastien.net/2015/07/01/quick-npm-tip-and-a-little-rant-about-node-gyp/

I am grateful for node-gyp & gyp and what it probably does for open source, but as a simple npm user, node-gyp has made my life miserable ;-)

**Comment by Ajar-Ajar** [comment]
Any news on this nightmare?

**Comment by a0viedo** [comment]
hey @ndejesus1227, a couple of years passed, is this one still relevant?

**Comment by gibfahn** [comment]
Microsoft have done some work on making it easy to get the right dependencies on Windows, it's documented in the `node-gyp` README: https://github.com/nodejs/node-gyp/#on-windows

Therefore I'm pretty sure this can be closed, if there are other problems please raise a new issue.
