### ISSUE TITLE
node-gyp build can't find node.h

### ISSUE THREAD

**Issue by asha451** [nodejs/node-gyp#519]
Environment:
Lubuntu 14.04.1 LTS on a 32bit VM
bitnami Meanstack-2.6.4-0
I've run npm install build-essential to make sure I have python 2.7, make, etc.

While following a tutorial on creating an add-on for node, the command "node-gyp build" failed, unable to find the "node.h" file.  The following is the console log:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.33 | linux | ia32
gyp info spawn make
make: Entering directory `/home/nnnnn/Desktop/node-cpp-rcf/build'
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION Regenerating Makefile
make: Leaving directory `/home/nnnnn/Desktop/node-cpp-rcf/build'
make: Entering directory `/home/nnnnn/Desktop/node-cpp-rcf/build'
  CXX(target) Release/obj.target/nodecpptest/main.o
../main.cpp:1:18: fatal error: node.h: No such file or directory
 #include <node.h>
                  ^
compilation terminated.
make: *** [Release/obj.target/nodecpptest/main.o] Error 1
make: Leaving directory `/home/nnnnn/Desktop/node-cpp-rcf/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/nnnnn/Desktop/node-cpp-rcf
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
```

Before this, I had to copy the common.gypi file to the expected directory in order to make the "node-gyp configure" command work. (re-install of node-gyp didn't work)

Am I seeing a pattern?  How do I tell node-gyp where to find my libraries/includes?
`node-gyp configure --nodedir="/home/nnnnn/meanstack-2.6.4-0/nodejs/include/node"` was something that I found worked for the configure command, but not for the build command.

Thank you kindly for any assistance.

**Comment by DiegoRBaquero** [comment]
Did you ever get the answer @asha451 ?

**Comment by tutulyy** [comment]
I get same problem .

**Comment by cccRaim** [comment]
I have the same problem!

**Comment by gibfahn** [comment]
Try `node-gyp rebuild`, it should download the headers to `~/.node-gyp`.

**Comment by cccRaim** [comment]
I use nvm, so I should make a soft link to bin/include

**Comment by refack** [comment]
@cccRaim could you post the error message you are getting (preferably also the log).
Is it exactly the same as the OP (i.e. `node@0.10.33` and `node-gyp@0.10.10`)?
If soft-linking solves the problem, could you elaborate what's the link and what's the target?

**Comment by cccRaim** [comment]
@refack 
```
> php-pack@1.0.0-release preinstall /Users/awalong/WebstormProjects/test/node_modules/php-pack
> node-gyp rebuild

  CXX(target) Release/obj.target/phppack/pack.o
../pack.cc:1:10: fatal error: 'node/node.h' file not found
#include <node/node.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/phppack/pack.o] Error 1
```
npm@5.3
node@8.1.4

You can see the same problem, can't found the file in c language file, this problem is related to C's include rule, on the other hand, it means your include DIRs don't have the file (such as node/node.h). 
I use OS, the C include DIR is `/usr/local/include`, so I make a soft link.  
`ln -s /Users/{your username}/.nvm/versions/node/v8.1.4/include/node /usr/local/include/node`

**Comment by refack** [comment]
@cccRaim thank you for following up.
I'll see if we can incorporate some detection logic to auto solve this...

**Comment by bnoordhuis** [comment]
@cccRaim You should file an issue against php-pack because those imports are simply wrong.  It's not a node-gyp bug.

I'll close this out.  If you (generic you) run into a similar-but-not-identical issue, please file a new issue and include build output.

**Comment by cccRaim** [comment]
@bnoordhuis wait. it's not my issue. w(ﾟДﾟ)w  
I just post a thinking of this issue

**Comment by refack** [comment]
@cccRaim the original issue has been open for 3 years (and 3 major `node-gyp` versions ;) it's time was due anyway...

Cross-ref https://github.com/acgpiano/php-pack/pull/2

**Comment by jonhoo** [comment]
I wonder if this might be fixed when the fix for https://github.com/nodejs/node/issues/20921 lands

**Comment by bnoordhuis** [comment]
@jonhoo No, completely unrelated.
