### ISSUE TITLE
Link against true Debug node.lib when --debug is requested

### ISSUE THREAD

**Issue by springmeyer** [nodejs/node-gyp#525]
My understanding is that:
- On windows all libraries and executables must all be compiled in debug mode to work correctly - you can't mix some Debug and Release binaries.
- There appear to be just two pre-built `node.lib` versions available for download for each release at http://nodejs.org/dist/, one for each architecture. I presume these two `node.lib` are Release builds
- In [copyNodeLib](https://github.com/TooTallNate/node-gyp/blob/1e399b471945b35f3bfbca4a10fba31a6739b5db/lib/build.js#L180-L198) the Release `node.lib` is copied either to a final directory for linking and the same version is used no matter if the C++ addon is being compiled in Debug or Release
- And lastly therefore that this seems like a potential problem, right?

Perhaps it is not a problem in reality because most developers on windows that would pass `--debug` to node-gyp are also going to pass `--nodedir=/path/to/lib` and this will resolve to their local (likely truly Debug build) node.lib (https://github.com/joyent/node/pull/2685/files)?

Can anyone shed some light on whether my concerns are valid or whether this has the potential to lead to C++ addons built with --debug to actually be linked to Release runtimes based on a Release `node.lib` passed to the linker?

**Comment by gigadude** [comment]
Linking a Debug build against the release node.lib seems to be working for me (Win8.1, VS 2013)... I made a symlink in ~/.node-gyp/4.2.0/ from Debug -> Release and can debug the resulting build/Debug/foo.node module. This is actually 99% of what I need out of a debug build, it's a shame it doesn't work this way out of the box.

**Comment by rvagg** [comment]
closing due to staleness, probably something that someone needs to come up with a pull request for anyway
