### ISSUE TITLE
 I wonder whether the cu file must be compiled through nvcc.

### ISSUE THREAD

**Issue by Francis0121** [nodejs/node-gyp#535]
Do I need to modify the source files?
If so, what file should I modify?

Do I need to set the binding.gyp?
.... I want to build cuda(.cu) file.....

**Comment by Trott** [comment]
@nodejs/node-gyp

**Comment by Trott** [comment]
Seems like given all the time this has been open, it can probably be closed. Feel free to comment or re-open if you never got an answer and are still wondering. If someone else wants to put a link to relevant documentation, 👍 to that too.
