### ISSUE TITLE
Changing 'type' to 'shared-library' changes target path on Ubuntu Trusty

### ISSUE THREAD

**Issue by ianmacl** [nodejs/node-gyp#543]
See https://github.com/polotek/libxmljs/issues/253 for more details.

On OS X, I can build the module without issue.

On the Ubuntu box, if I npm rebuild without the shared-library line, xmljs.node gets placed in:
build/Release/xmljs.node.

If I add the shared-library line, xmljs.node gets placed in:
build/Release/lib.target/xmljs.node

This different target path causes bindings not to be able to find the xmljs.node file.

I'm not sure TBH if this is a LIBXML issue or a node-gyp issue.  I was hoping somebody more knowledgable than I on this subject would be able to quickly determine where the problem lies.

**Comment by Trott** [comment]
@nodejs/node-gyp

**Comment by bnoordhuis** [comment]
Unlikely to still be relevant.  I'll close.
