### ISSUE TITLE
What is required to be install for win7 x64?

### ISSUE THREAD

**Issue by littlee** [nodejs/node-gyp#549]
I've installed python 2.7.8

My question is if I install Microsoft Visual Studio C++ 2012/13 express, should I install Windows 7 64-bit SDK or compiler update for the Windows SDK 7.1?

**Comment by hwoarangzk** [comment]
@littlee I also write code on `win7 x64`, what I installed are as follows: `node 0.12.7, node-gyp 2.0.2, python 2.7, vs2013`. The above is enough for `node-gyp` :)

**Comment by blue-lightning** [comment]
Readme.md mentions Windows 7 64-bit SDK, but exactly what components are needed ? I don't want to install unnecessary stuff in my environment.

**Comment by rvagg** [comment]
README has all this info now
