### ISSUE TITLE
gyp build error on os x

### ISSUE THREAD

**Issue by d4ny0** [nodejs/node-gyp#552]
Hey Guys.

I tried to install the npm package 'gulp-svg-sprites'. everytime i tried to install it i got this errormessage from gyp

I use this versions of node and npm
npm -v
2.1.11

node -v
0.10.33

which i installd with homebrew.

I had this errors a while ago but since my mac had some issues i made a new clean installation from yosemite but i still get these errors.

Thanks in advance for your help!
# Log

> npm install gulp-svg-sprites
> npm WARN package.json wazzup@1.0.0 No description
> npm WARN package.json wazzup@1.0.0 No repository field.
> npm WARN package.json wazzup@1.0.0 No README data
> 
> libxmljs@0.8.1 install /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/>node_modules/libxmljs
> node-gyp rebuild
> 
> CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/src'
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/deps/uv/include'
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/deps/v8/include'
> make: **\* [Release/obj.target/libxml/vendor/libxml/buf.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
> gyp ERR! System Darwin 14.0.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/>libxmljs
> gyp ERR! node -v v0.10.33
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok 
> \
> fibers@1.0.2 install /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_>modules/phantom-sync/node_modules/make-sync/node_modules/fibers
> node ./build.js
> 
> `darwin-x64-v8-3.14` exists; testing
> Binary is fine; exiting
> 
> weak@0.2.2 install /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_>modules/phantom-sync/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild
> 
>  CXX(target) Release/obj.target/weakref/src/weakref.o
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/src'
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/deps/uv/include'
> clang: error: no such file or directory: 'Daten/Users/danyo/.node-gyp/0.10.33/deps/v8/include'
> make: **\* [Release/obj.target/weakref/src/weakref.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
> gyp ERR! System Darwin 14.0.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/node_modules/gulp-svg-sprites/node_modules/svg-sprite-data/node_modules/>phantom-sync/node_modules/phantom/node_modules/dnode/node_modules/weak
> gyp ERR! node -v v0.10.33
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok 
> npm ERR! Darwin 14.0.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "gulp-svg-sprites"
> npm ERR! node v0.10.33
> npm ERR! npm  v2.1.11
> npm ERR! code ELIFECYCLE
> 
> npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the libxmljs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls libxmljs
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Volumes/Danyo Daten/Users/danyo/Sites/sae/wazzup/npm-debug.log>

**Comment by antgonzales** [comment]
+1

**Comment by antgonzales** [comment]
@D4ny0 I was able to get SVG sprites working when switched Node versions using NVM to v0.10.35.

**Comment by D4ny0** [comment]
As my harddisk crashed, i replaced it with a new one and tried again to install it. Now it works. I don't really know why it failed before but now it works. Maybe because of some updates of npm...

**Comment by a0viedo** [comment]
this can be closed now @Trott
