### ISSUE TITLE
How to force target version for packages installed with NPM?

### ISSUE THREAD

**Issue by piranna** [nodejs/node-gyp#556]
On NodeOS we have found that [node-gyp uses the headers same version of the Node.js executable that's running it](https://github.com/NodeOS/NodeOS/pull/89), that makes not possible to use a different version of the one installed by the user. The docs and [the code](https://github.com/TooTallNate/node-gyp/blob/d3583d7f5d0a674d1d966e09611550b3ac7decd0/lib/install.js#L46) shows that's possible to define the target version to use when using node-gyp as a command line executable or as a library, but it doesn't say nothing about how to set the target Node.js version when installing a package by executing `npm install`, so I ask, there's any way to set the target version in that use case, for example by using an environment variable? Maybe a config flag on npm itself?

**Comment by rvagg** [comment]
pull request would be great if better docs are desired
