### ISSUE TITLE
node-gyp and iojs

### ISSUE THREAD

**Issue by ralphtheninja** [nodejs/node-gyp#563]
Hi,

I'm trying to rebuild `node-leveldown` which calls `install`. The following line assumes `node` is used:

https://github.com/TooTallNate/node-gyp/blob/4ceed113a800378e78435a42632fd035413c99b2/lib/install.js#L188

It's possible to configure with `--disturl=https://iojs.org/dist` so that part is cool.

**Comment by ralphtheninja** [comment]
See [`this`](https://github.com/rvagg/node-leveldown/issues/141) for more background on the problem.

**Comment by steelbrain** [comment]
Bump.

**Comment by Fishrock123** [comment]
https://github.com/nodejs/node-gyp/issues/701
