### ISSUE TITLE
System account build agent fails LNK1181 node.lib missing

### ISSUE THREAD

**Issue by ulabs-sgiroux** [nodejs/node-gyp#572]
I am setting up a TeamCity build server & agent on a Windows Server 2012 x64 machine. I intend on building and testing a NodeJS application on this build server. Here are some details:
- OS: Windows Server 2012 x64 
- Build tools: VS2013 (not express)
- node -v: v0.10.36
- node-gyp -v: v1.0.2
- npm -v: v2.4.1

`[npm install] LINK : fatal error LNK1181: cannot open input file 'C:\Windows\system32\config\systemprofile\.node-gyp\0.10.36\Release\node.lib' [C:\TeamCity\buildAgent\work\82ee4beff096a19\server\node_modules\bcrypt\build\bcrypt_lib.vcxproj]`

I have tried the command `node-gyp install` as my user account and noted `%USERPROFILE%\.node_gyp` contained what I wanted. I have always been able to use node-gyp successfully as my user account.

I tried the command `node-gyp install` as the system account (by psexec -i -s) and noted a success but no .node_gyp in %USERPROFILE% (which expands to `C:\Windows\System32\config\systemprofile` BTW)

Perhaps this is just a case that is unhandled or an issue of permissions?

**Comment by ulabs-sgiroux** [comment]
**Workaround**: Copying .node_gyp from my user account to the system account solved the problem as I suspected. It would be nice for this to work seamlessly though.

**Comment by a0viedo** [comment]
this can be closed now @Trott
