### ISSUE TITLE
Fail to install Win8 64bits

### ISSUE THREAD

**Issue by bloooooooop** [nodejs/node-gyp#573]
Hi,

My conf is : 
Windows 8.1 Pro 64bits
Python 2.7
Node 64bits v 0.12
Visual Studio 2012 express

But i have this issue : 

```
D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-sprite-data\node
_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_modules\weak>
node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Génération des projets individuellement dans cette solution. Pour activer la gén
ération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'weakref.vcxproj' is in
valid.  Platform='x64'. You may be seeing this message because you are trying t
o build a project without a solution file, and have specified a non-default Pla
tform that doesn't exist for this project. [D:\wamp\www\test\node_modules\gulp-
svg-sprites\node_modules\svg-sprite-data\node_modules\phantom-sync\node_modules
\phantom\node_modules\dnode\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-spr
ite-data\node_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_
modules\weak
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-svg-sprites"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

I tried to install node x86 but it's worst than ever with multiple issues. I alos tried to install other versions of visual studio (2010).

**Comment by ricdonson** [comment]
I am getting the same (main-) error:

    child_process: customFds option is deprecated, use stdio instead.

And then hundreds of compiler errors like these:

    f:\appdata\roaming\npm\node_modules\stanford-corenlp\node_modules\java\src\java.h(10): error C2039: 'ObjectWrap' : is not a member of 'node' (..\src\java.cpp) [f:\AppData\Roaming\npm\node_modules\stanford-corenlp\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    f:\appdata\roaming\npm\node_modules\stanford-corenlp\node_modules\java\src\java.h(10): error C2504: 'ObjectWrap' : base class undefined (..\src\java.cpp) [f:\AppData\Roaming\npm\node_modules\stanford-corenlp\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    f:\appdata\roaming\npm\node_modules\stanford-corenlp\node_modules\java\src\java.h(23): error C2039: 'Arguments' : is not a member of 'v8' (..\src\java.cpp) [f:\AppData\Roaming\npm\node_modules\stanford-corenlp\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    f:\appdata\roaming\npm\node_modules\stanford-corenlp\node_modules\java\src\java.h(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\java.cpp) [f:\AppData\Roaming\npm\node_modules\stanford-corenlp\node_modules\java\build\nodejavabridge_bindings.vcxproj]
    f:\appdata\roaming\npm\node_modules\stanford-corenlp\node_modules\java\src\java.h(23): error C2143: syntax error : missing ',' before '&' (..\src\java.cpp) [f:\AppData\Roaming\npm\node_modules\stanford-corenlp\node_modules\java\build\nodejavabridge_bindings.vcxproj]

**Comment by karland** [comment]
I suppose you are trying to install `node-gyp`?

I am not sure, if this helps, but -- if not already -- you can try the following.

1. Do not install `node.js` as suggested by the `node`-installer into `c:\program files`. Install it in `c:\nodejs`. Everything in `c:\program files` requires special windows user rights. My feeling is that this is sometimes complicating matters, so do not go there.
2. Update `npm` globally to the most recent version: `npm install npm --g` 
3. Try to install [Visual Studio 2013 Update 4](http://www.visualstudio.com/en-us/news/vs2013-update4-rc-vs.aspx).
4. Use the latest [python 2.7.9 version](https://www.python.org/downloads/release/python-279/).
5. Try running `npm install -g node-gyp --msvs_version=2013`

@bloooooooop I am not sure about your path `D:\wamp\...` and why it is reported. If wamp is in your path you may try to remove it or move it back, so that everything else is found first.

Best of luck....

**Comment by jeffreytgilbert** [comment]
Don't think that's the issue, friend. I think the issue is there are dependencies which phantom or dnode have that are out of date and those are causing an ELIFECYCLE error to kick off when the build runs.

**Comment by abdullahsalem** [comment]
I got the same problem, but that immediately happened after I updated the Visual Studio 2013 by Update 4!
Before the Update 4 I was running the gyp by passing the parameter --msvs_version=2013, but after that I got that error message even if I pass that parameter !?

**Comment by bloooooooop** [comment]
@karland, Thanks for your reply. I'm trying to install gulp-svg-sprites but I have trouble in the node-gyp part.
I did steps  1 2 4 5 but I can do the 3 because of network restrictions...

I have a new error

```
D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-sprite-data\node
_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_modules\weak>
node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\b
in\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Génération des projets individuellement dans cette solution. Pour activer la gén
ération en parallèle, ajoutez le commutateur "/m".
D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-sprite-data\nod
e_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_modules\wea
k\build\weakref.vcxproj(44,49): error MSB4025: Impossible de charger le fichier
 projet. Il existe un caractère non valide dans l'encodage donné. Ligne 44, pos
ition 49.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-spr
ite-data\node_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_
modules\weak
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "gulp-svg-sprites"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\www\test\npm-debug.log
```

To translate from french, the error is :
D:\wamp\www\test\node_modules\gulp-svg-sprites\node_modules\svg-sprite-data\nod
e_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_modules\wea
k\build\weakref.vcxproj(44,49): error MSB4025: Unable to initialise project's file. There is an invalid character in the encoding given Line 44, position 49.

**Comment by jeffreytgilbert** [comment]
I heavy handed my fix. I deleted the global node_modules and the local node modules then uninstalled and reinstalled node via brew. i believe the original issue came from the upgrade to 0.12 from 0.10 where the C components in some modules were previously built against the older release. Once you remove the old modules and reinstall them, the only errors left were ELIFECYCLE and were solved by upgrading my package.json with the latest version of the outdated library.

**Comment by jeffreytgilbert** [comment]
You should not need to run node_gyp rebuild as it suggests in the error. Thats misleading. Npm does all the work you need.

**Comment by jeffreytgilbert** [comment]
Read the error to see that npm is telling you both ELIFECYCLE and that it is having a problem with libxmljs, not the sprites module. Do you have a libxmljs in your package.json? Is it 0.8? The current version is 0.13. Upgrade that and try your install again. This does not appear to be a node-gyp issue, so I don't believe this issue belongs on this project.

**Comment by bloooooooop** [comment]
Thanks for your help @jeffreytgilbert 
If I try to install libxmljs I have the following issue : 

```
D:\wamp\www\test\node_modules\libxmljs>node "C:\nodejs\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Génération des projets individuellement dans cette solution. Pour activer la gén
ération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'libxml.vcxproj' is inv
alid.  Platform='x64'. You may be seeing this message because you are trying to
 build a project without a solution file, and have specified a non-default Plat
form that doesn't exist for this project. [D:\wamp\www\test\node_modules\libxml
js\build\vendor\libxml\libxml.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wamp\www\test\node_modules\libxmljs
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "libxmljs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\www\test\npm-debug.log
```

As you say the issue doesn't belong to this project

**Comment by a0viedo** [comment]
this one can be closed @Trott
