### ISSUE TITLE
node-gyp on Linux does not deal with libraries that need the -Wl --start-group -Wl --end-group linker commands

### ISSUE THREAD

**Issue by gavinmarkglynn** [nodejs/node-gyp#580]
I am trying to generate a node wrapper for a complicated set of libraries, which have inter dependencies. node-gyp currently leaves the "libraries" out of the generated -Wl --start-group -Wl --end-group linker parameters generated for the source file. Could the libraries and the source files be combined into a single -Wl --start-group -Wl --end-group linker parameter?

**Comment by Trott** [comment]
@nodejs/node-gyp Should this be closed? Maybe there's a quick answer that can be supplied for other people that come across the issue at a later date?

**Comment by bnoordhuis** [comment]
It's not clear to me what @gavinmarkglynn is trying to do.  Circumventing `-Wl,--as-needed`?

Seeing this issue has been open for three years, I'll go ahead and assume it's no longer relevant.  Leave a comment if it's still actual.

**Comment by gavinmarkglynn** [comment]
Thanks. In the end I gave up on using node-gpy, and used regular g++ commands in a make file.
