### ISSUE TITLE
is there example for using node-gyp to install node-inspector on yocto linux  (intel edison) ?

### ISSUE THREAD

**Issue by digerati73** [nodejs/node-gyp#582]
i am using intel edison,
i want to use node-inspector but, there is no node-inspector for x86 linux,

so, they recommand to use node-gyp to use node inspector for x86 linux

so, i come here, but i can't know how to do....

i want some example, or if you can , would you make a example how to do ??

**Comment by maclover7** [comment]
@digerati73 This seems like an issue with the `node-inspector` module, so my advice would be to open up a ticket on their issue tracker (https://github.com/node-inspector/node-inspector/issues) to get further help. Going to close this out for now, since this isn't a bug with node-gyp.
