### ISSUE TITLE
This doesn't work at all for io.js and windows x64

### ISSUE THREAD

**Issue by alanpurple** [nodejs/node-gyp#583]
All of the environmental-variable-related codes are useless and doesn't operate properly.

I spent many hours to solve this because I want to compile bson for io.js and windows x64 but as a result I finally succeeded to configure but still vcprojx has wrong conf(requires node.lib instead of iojs.lib) and I modify vcprojx manually and finally I got bson.node but that module gives me the message "module did not self-register"

Of course I also tried the forked version for iojs( https://github.com/rvagg/node-gyp/tree/iojs )

**Comment by mzgol** [comment]
Isn't this https://github.com/iojs/io.js/issues/751?

**Comment by alanpurple** [comment]
sort of...
I manually modify node-gyp source code(io.js branch) to work properly for io.js(and only) 4.2.1 x64,  and finally I got vcprojx file( for bson.node build) and that vcxproj file requires node.lib instead of iojs.lib and so I modified generated vcxproj file and I got bson.node successfully,  and finally....yes I got "module did not self-register" message.

**Comment by maclover7** [comment]
Going to give this a close since Node.js v4 is currently EOL. Please reopen if you can reproduce this on a currently supported version of Node.js
