### ISSUE TITLE
Trying to install Aglio

### ISSUE THREAD

**Issue by burkmiers** [nodejs/node-gyp#585]
I was forwarded from apiaryio/protagonist.

I've been trying to install Aglio, but it's been failing. I installed....
Node: v0.10.35 
Python:2.7.3
npm:1.4.28
Microsoft Visual C++ Compiler for Python 2.7
(http://www.microsoft.com/en-us/download/details.aspx?id=44266)

I ran the command "npm install bcrypt" but got the following errors.
## C:\DevPrograms\aglio-master>npm install bcrypt

> bcrypt@0.8.1 install C:\DevPrograms\aglio-master\node_modules\bcrypt
> node-gyp rebuild

C:\DevPrograms\aglio-master\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DevPrograms\aglio-master\node_modules\bcrypt
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "bcrypt"
npm ERR! cwd C:\DevPrograms\aglio-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by maclover7** [comment]
I think this is safe to close since the issue has been inactive for several years, and the original comment references a v0.x version of Node.js, which has been unsupported for years now.
