### ISSUE TITLE
Cannot find files to add to the path

### ISSUE THREAD

**Issue by zlandry** [nodejs/node-gyp#586]
In the description for install, there are instructions to add certain variables to the path (like platformtoolkit), but I am unable to find them in the v7.1 directory. Any help as to where I can find the path for these variables? (this is in reference to the visual studio 2010 setup guide)

**Comment by zlandry** [comment]
This is in reference to the visual studio 2010 setup

**Comment by rvagg** [comment]
closing due to staleness
