### ISSUE TITLE
Registry Free Dll for a Com DLL

### ISSUE THREAD

**Issue by kiranjoshy123** [nodejs/node-gyp#589]
I am new to node-gyp and facing a serious problem and stuck in the middle.

In our current project, we had a COM Dll which is consumed by a normal DLL. As per our requirements, we need to use the COM Dll without registering. We could find a way to achieve this by using the manifest file in the visual studio( Please refer the below link ).

http://blogs.msdn.com/b/yvesdolc/archive/2008/05/09/native-manifests-let-s-do-com-and-forget-the-registry.aspx?CommentPosted=true#commentmessage

We need to add the required settings to the client part( COM dll ) and to the component part as well. For the component part we need to add the additional manifest dependencies. For example “type='x64' name=’Dll_Name' version='1.0.0.0'”
1. Component part as an EXE
   Let the component part is an EXE. i.e. if an exe is loading the COM dll and if you add the settings to the exe, we were able to achieve the functionality without registering the COM DLL.
2. Component part as a DLL
   Let the component part is a normal DLL. i.e. if a normal DLL is loading the COM DLL and if you add the settings to the normal dll, it doesn’t works( CoCreateInstane()) failed throwing ‘class not registered’ error ).
   
   2.1. DLL invoked through an EXE
   For invoking the component DLL, let us use a EXE. If you add the settings to the EXE which is used to load the component DLL, then we were able to achieve the functionality without registering the COM DLL.
   Why can’t we achieve the functionality by adding the manifest dependency settings in the DLL ? Why is it required that it should be done only in EXE ?
   
   2.2. DLL invoked through a node server
   In our application we are using node server to invoke the component DLL.
   JavaScript -> Node server -> Component DLL -> COM DLL
   
   We are using *.gyp file to build the node file which will use visual studio compiler to build it. We added the following additional manifest dependency settings in the node file( which we added for the exe ) and build the same to obtain the node server.
   
   'msbuild_settings': {
   'Link': { 'GenerateDebugInformation': 'true', 'AdditionalManifestDependencies': "type='x64' name='Dll_Name' version='1.0.0.0'", }, },

But it didn’t worked as expected and CoCreateInstane()failed.
Why can’t I achieve the functionality by using a node server?

Any help will be appreciated.

**Comment by rvagg** [comment]
closing due to staleness
