### ISSUE TITLE
how to modify cflags

### ISSUE THREAD

**Issue by nickdesaulniers** [nodejs/node-gyp#594]
We use node-gyp in node-nanomsg.  A dependency, nanomsg, has a few warnings I'd like to silence with `-Wno-missing-field-initializers`.  No matter where I seem to add it to our binding.gyp file, I can't seem to get it to work.  What am I doing wrong?

https://github.com/nickdesaulniers/node-nanomsg/blob/master/binding.gyp

**Comment by maclover7** [comment]
Looks like this was solved, going to give this a close for now
