### ISSUE TITLE
node-gyp problem gyp ERR! This is a bug in `node-gyp`.

### ISSUE THREAD

**Issue by sunyt** [nodejs/node-gyp#595]
```
> node-gyp rebuild

gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /space/node/cherry/node_modules/oracle
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! This is a bug in `node-gyp`.
 Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! oracle@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the oracle@0.3.8 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /space/node/cherry
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /space/node/cherry/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Fishrock123** [comment]
```
 Try to update node-gyp and file an Issue if it does not help:
```

```
npm ERR! Failed at the oracle@0.3.8 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.
```

https://github.com/joeferner/node-oracle

**Comment by naeem1098** [comment]
I've done everything as I could but the problem isn't resolved yet!

**Comment by joaocgreis** [comment]
@naeem1098 please update npm:
```
npm install --global npm
```

**Comment by naeem1098** [comment]
> @naeem1098 please update npm:
> 
> ```
> npm install --global npm
> ```

Thank you @joaocgreis,  I've already solved this with node-pre-gyp.

**Comment by prathamesh613** [comment]
@naeem1098  How did you fix this,  still cannot resolve.
![Screenshot (74)](https://user-images.githubusercontent.com/54031891/83130760-70080d00-a0fc-11ea-8cda-7c19a6071122.png)

**Comment by cclauss** [comment]
Why comment on an issue that is over 5 years old?  Clearly much has changed since then.

`gyp ERR! node-gyp -v v3.8.0` is a problem.  Click the label above to see other issues about using out of date [releases of node-gyp](https://github.com/nodejs/node-gyp/releases).

**Comment by naeem1098** [comment]
> @naeem1098 How did you fix this, still cannot resolve.
> ![Screenshot (74)](https://user-images.githubusercontent.com/54031891/83130760-70080d00-a0fc-11ea-8cda-7c19a6071122.png)

I did explicitly installed the node-gyp at that time. It was needed to me for brain.js I think.

**Comment by Breeduss** [comment]
Sad this is still happening. I've nuked Node.js and Visual Studios and reinstalled. Not sure what to do might have to completely wipe computer.

**Comment by cclauss** [comment]
If you are running node-gyp v3 when the current version is v7 perhaps you need to upgrade node-gyp.

**Comment by wayfarer3130** [comment]
It would be nice to be able to do that, but it is a transitive dependency, and there doesn't seem to be a good way to force a given version of a transitive dependency, at least nothing I've tried works.  I tried updating the top level dependency to a newer version, but that breaks other things that don't have newer versions to apply.  This is in a yarn project, and it just isn't obvious how one forces an update.

**Comment by wayfarer3130** [comment]
> It would be nice to be able to do that, but it is a transitive dependency, and there doesn't seem to be a good way to force a given version of a transitive dependency, at least nothing I've tried works. I tried updating the top level dependency to a newer version, but that breaks other things that don't have newer versions to apply. This is in a yarn project, and it just isn't obvious how one forces an update.

Found a solution to allow upgrading node-gyp.  The problem is if you are using a multi package.json setup, then only the resolutions in the TOP package.json count (even if your dependency comes from a child package.json), so if you add to the top level package.json the lines:
```  
"resolutions": {
    "**/node-gyp": "8.4.1",
```
then it will over-ride the child dependency version.
