### ISSUE TITLE
Error ELIFECYCLE

### ISSUE THREAD

**Issue by RyenNelsen** [nodejs/node-gyp#598]
When attempting to install [`git-projects`](https://github.com/prrrnd/atom-git-projects) I get the following error:

```
Installing “git-projects@1.11.1” failed.

> git-utils@3.0.0 install C:\Users\rnelsen\AppData\Local\Temp\apm-install-dir-115224-10224-1bnh5am\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild


C:\Users\rnelsen\AppData\Local\Temp\apm-install-dir-115224-10224-1bnh5am\node_modules\git-projects\node_modules\git-utils>node "C:\Users\rnelsen\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\rnelsen\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\rnelsen\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\rnelsen\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\rnelsen\\.atom\\.apmrc" "install" "C:\\Users\\rnelsen\\AppData\\Local\\Temp\\d-115224-10224-dz6ybe\\package.tgz" "--target=0.21.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! git-utils@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.
```

**Comment by MatthewMazaika** [comment]
I'm seeing this same exception with libxmljs in a heroku deployment (I'm not sure how to get the additional log file, but if/when I do, I'll attach it)


remote:        make: Leaving directory `/tmp/build_7ebe040cfb9e10899e31de9a6067afe0/node_modules/wolfram/node_modules/libxmljs/build'
remote:        npm ERR! Linux 3.13.0-40-generic
remote:        npm ERR! argv "node" "/tmp/build_7ebe040cfb9e10899e31de9a6067afe0/.heroku/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/build_7ebe040cfb9e10899e31de9a6067afe0/.npmrc"
remote:        npm ERR! node v0.12.0
remote:        npm ERR! npm  v2.7.3
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the libxmljs package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls libxmljs
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_7ebe040cfb9e10899e31de9a6067afe0/npm-debug.log

**Comment by MatthewMazaika** [comment]
and there seems to be something incompatible with the newest versions of node/npm

with heroku deployments, you can lock the versions of node/npm - this was the previous combination that succeeded with my deployment and it still works today.

  "engines": {
    "node": "= 0.10.35",
    "npm": "= 2.3.0"
  }

**Comment by Fishrock123** [comment]
These are probably separate issues. Please run npm with `--verbose` and open new issues if you encounter errors, thanks!
