### ISSUE TITLE
Warning "root" does not have permission to access the dev dir #454 

### ISSUE THREAD

**Issue by cliveb** [nodejs/node-gyp#608]
tjwebb opened this issue on Jun 7, 2014 - still open April 7, 2015

https://github.com/TooTallNate/node-gyp/issues/454

NodeSchool is using node-gyp newbs are coming across the issue.

Install the core workshops with these commands:
npm install -g learnyounode
npm install -g javascripting
npm install -g git-it
npm install -g how-to-npm
npm install -g stream-adventure

**Comment by Kryz** [comment]
I had the same problem. The solution was to give my user access to the folder where npm was installed.

I fixed it with:
sudo chown -R $USER `which npm`I had the same problem. The solution was to give my user access to the folder where npm was installed.

I fixed it with:
sudo chown -R $USER `which npm`

**Comment by leecade** [comment]
+1

@Kryz not works for me,

iojs v2.2.1

**Comment by aleclarson** [comment]
No solution found for `iojs v1.6.2`. I switched to `node v0.12.4` and the installation worked.
