### ISSUE TITLE
Different behavior between windows and *nix for gyp actions.

### ISSUE THREAD

**Issue by trgoofi** [nodejs/node-gyp#613]
I am not quite sure this is a node-gyp issue or a gyp upstream issue. Anyway I fire it here. 
GYP actions called under different directory between windows and *nix.

```
...
{
   'action_name': 'some-name',
   'inputs': [ 'inputs-files' ],
   'outputs': [ 'output-files' ],
   'action': [ 'command', 'args'],
}
...
```

On windows `command` in `action` will be called under `path/to/project/build/` directory while  on *nix it called under `path/to/project/`.

FYR
node-gyp: v1.0.3
build log: [Windows](https://ci.appveyor.com/project/trgoofi/telepod/build/job/kr7pq4pvj5omuh90)  [Linux ](https://travis-ci.org/trgoofi/telepod/builds/59366304)

**Comment by rvagg** [comment]
closing due to staleness
