### ISSUE TITLE
What variables are normally defined?

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-gyp#615]
It would be good to have the list of variables available for use in a binding.gyp file defined somewhere. For example, is there a variable that evaluates to `build/Release` if it's a release build and `build/Debug` if it's a debug build?

**Comment by gabrielschulhof** [comment]
OK, I found https://code.google.com/p/gyp/wiki/InputFormatReference#Predefined_Variables which is good, but I guess it doesn't cover node-specific variables, if any.

**Comment by justinmchase** [comment]
I think that's the right documentation link. I recommend closing this issue.

**Comment by jakwings** [comment]
I don't think so. I guess the variables defined by node-gyp are not stable?
