### ISSUE TITLE
io.js 2.0.1 -- Error: 404 status code downloading tarball

### ISSUE THREAD

**Issue by wavded** [nodejs/node-gyp#623]
All addons currently are failing due to:

```
> microtime@1.4.1 install /Users/wavded/Projects/golfhits/modules/mail/node_modules/mailer/node_modules/graygelf/node_modules/microtime
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:304:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wavded/Projects/golfhits/modules/logger/node_modules/graylog/node_modules/graygelf/node_modules/microtime
gyp ERR! node -v v2.0.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

**Comment by binarykitchen** [comment]
Indeed, this is worrying and breaking the app we are developing here.

Would be extremely helpful if the error message also showed what URL it is trying to download the tarball from.

**Comment by rickdog** [comment]
node-gyp.js needs to be modified to handle iojs.
It looks for files in the wrong directories.
The x64 files are found at https://iojs.org/dist/v1.0.1/win-x64/, not https://iojs.org/dist/v1.0.1/x64/

$ node "c:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@1.0.1 | win32 | x64
gyp http GET https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http 200 https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http GET https://iojs.org/dist/v1.0.1/SHASUMS256.txt
gyp http GET https://iojs.org/dist/v1.0.1/x64/node.lib
gyp http GET https://iojs.org/dist/v1.0.1/node.lib
gyp http 404 https://iojs.org/dist/v1.0.1/x64/node.lib
gyp WARN install got an error, rolling back install
gyp http 200 https://iojs.org/dist/v1.0.1/SHASUMS256.txt
gyp http 404 https://iojs.org/dist/v1.0.1/node.lib
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib

**Comment by fengmk2** [comment]
+1

**Comment by adioo** [comment]
+1

**Comment by binarykitchen** [comment]
@rickdog thanks but i think you cannot imply without facts that the author isn't interested to support iojs. if that were true, i could make a similar assumption that the author isn't interested to support windows. how you'd feel about that? ;)

**Comment by cfsghost** [comment]
I found a fork which has no this issues for io.js. is it possible to merge?

https://github.com/rvagg/pangyp

**Comment by bryannaegele** [comment]
+1

still present in 2.0.2

**Comment by shanewho** [comment]
I'm having this same problem. I can't deploy to heroku due to bcryptjs not being able to build.

**Comment by leecade** [comment]
+1
still present in v2.2.1

**Comment by felipefdl** [comment]
+1
iojs - v2.3.3

**Comment by message** [comment]
+1

**Comment by gabeio** [comment]
:+1: side note to anyone who knows this library better (than I do at least) the author seems to be accepting pull requests frequently; so if someone could make a pull request rather than ~~complain~~ wait it'd probably save everyone a lot of trouble :heart:

**Comment by coderaiser** [comment]
Fixed in https://github.com/TooTallNate/node-gyp/pull/669

**Comment by Fishrock123** [comment]
https://github.com/nodejs/node-gyp/issues/701
