### ISSUE TITLE
OS X default compiler

### ISSUE THREAD

**Issue by Sannis** [nodejs/node-gyp#63]
As we founded in Sannis/node-mysql-libmysqlclient#127 [here](https://github.com/Sannis/node-mysql-libmysqlclient/issues/127#issuecomment-5739969), `node-gyp` and `node-waf` uses different C++ compilers: c++ vs g++.

It causes some compilation and probaly run time errors.
As I can understand, `node` itself can't be compiled with c++ compiler for now. Can you change default compiler used by `node-gyp` on OS X?

**Comment by Animeshz** [comment]
Is this issue never been worked on, and is closed? I have same problem, C/CC/CXX compilers (in env) aren't getting picked up...
