### ISSUE TITLE
How to set location of build directory

### ISSUE THREAD

**Issue by BLaurent** [nodejs/node-gyp#631]
Hi,
Is there a way to change the name and location of the build directory ?

Thanks in advance 
Regards
Ben

**Comment by peterbraden** [comment]
I'd also like to know this. This is important as I have a project that uses Bazel as a build tool, which uses the reserved filename `BUILD` which conflicts with `build`. The only way I can have both co-exist is if there's a way to have node-gyp use an alternative directory.

**Comment by bnoordhuis** [comment]
The build directory is currently hard-coded.  I'll close this issue, #263 is the de facto tracking bug.
