### ISSUE TITLE
Document GYP_MSVS_VERSION env variable

### ISSUE THREAD

**Issue by andhikanugraha** [nodejs/node-gyp#633]
At the moment, node-gyp on Windows isn't quite a nice experience. Sometimes it works, but sometimes even if Visual Studio is already installed, the proper version isn't detected and node-gyp refuses to build.

Digging through the code I found that setting the GYP_MSVS_VERSION env variable to the VS version used helped (in my case, 2015). But I don't see any docs mentioning this. Can we have this somewhere in the docs?

Thank you.

**Comment by luisrudge** [comment]
This doesn't work for me.

**Comment by grofit** [comment]
nor me, it ignores me setting it to 2013 and uses 2015. (I only found out about it on a chat room where someone mentioned it).

**Comment by djpereira** [comment]
In my case I had to manually set `GYP_MSVS_VERSION=2015` as environment variable for the right version of Visual Studio to be picked up.

**Comment by bnoordhuis** [comment]
`GYP_MSVS_VERSION` was documented in commit a8d441a0.  I'll close the issue.
