### ISSUE TITLE
Implement node-gyp in pure javascript.

### ISSUE THREAD

**Issue by lygstate** [nodejs/node-gyp#634]
At the current time, we need to dependence to python that's cause we always need to install python.
And gyp is pure JSON, maybe we can take advantage of that?

**Comment by marksweiss** [comment]
If you haven't, I suggest you take a look at what some of the Python code does. The code I looked at recently generates make files for *nix and OSX and build files for Windows. This is very complicated, with a *tremendous* amount of arcane detail and edge cases. Also this code (at least what I looked at, here: https://github.com/TooTallNate/node-gyp/blob/master/gyp/pylib/gyp/generator/make.py) comes from Google so it's provenance is well known. In short, this is really hard to get right, other excellent engineers already got it right, and there would be no functional improvement to node-gyp to recreating this code. A dependency on Python (a fairly easy dependency to manage) is in my opinion a small price to pay for the tremendous value this code provides node-gyp. It's at the heart of what node-gyp does and node-gyp wouldn't work without it.

**Comment by TooTallNate** [comment]
@lygstate What you're asking is... easier said than done...

**Comment by lygstate** [comment]
I am not just saying, I am thinking about it.

**Comment by JCMais** [comment]
Related: https://github.com/nodejs/io.js/issues/133

**Comment by justinmchase** [comment]
:+1: I realize this is easier said than done, but it would be nice. Also, yaml based instead of the unpleasant format of the gyp files.

**Comment by Fishrock123** [comment]
For reference, node also requires python to be built. It's probably a topic that is best discussed around https://github.com/nodejs/node/issues/133, but I'll leave this open also.

**Comment by Croydon** [comment]
#960

**Comment by maclover7** [comment]
Closing in favor of #960/#1092, where work has been underway.
