### ISSUE TITLE
Node exits when Visual C++ redistributable is missing

### ISSUE THREAD

**Issue by panuhorsmalahti** [nodejs/node-gyp#642]
I encountered this issue while using zmq, which uses node-gyp:
https://github.com/JustinTulloss/zeromq.node/issues/390

How to reproduce on Windows:
1. Use a node-gyp -based Node.js library which requires Visual C++ redistributable while not having it installed
2. Invoke native code, e.g. `var zmq = require('bindings')('zmq.node'); zmq.zmqVersion();`

Expected result:
An error message is displayed.

Actual result:
Node exits.

It was difficult to debug, since there's no error messages or exceptions thrown, Node simply exits the process immediately when invoking any native code.

**Comment by rvagg** [comment]
closing due to staleness
