### ISSUE TITLE
Update install documentation for Windows users

### ISSUE THREAD

**Issue by medikoo** [nodejs/node-gyp#644]
It looks that existing documentation doesn't work well for Windows 8.1 users.
1. Windows 8.1 SDK needs to be installed and not Windows 7 SDK as documentation suggests.
   https://github.com/ErikDubbelboer/node-sleep/issues/18#issuecomment-76309396
2. VS 2013 Community should be installed instead of suggested VS 2013 Express 
   https://github.com/bnoordhuis/node-iconv/issues/110#issuecomment-84412002

**Comment by medikoo** [comment]
Additional things I needed on my side
- Set VCTargtsPath with
```
set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120
```
- Run npm rebuild (or install) always withinin VS2012 x86 Native Tools Command Prompt, and with `--msvs_version=2013` argument

**Comment by donaldhook** [comment]
I have VS 2015 installed and did as you mentioned and that did not work.

**Comment by DonRichards** [comment]
Very Useful. Had to sift through blogs after blog to find this info and after upgrading to Node v5 it broke again.

**Comment by bsclifton** [comment]
This should be resolved once https://github.com/nodejs/node-gyp/pull/867 is finalized and merged. Additional details from my struggle captured here https://github.com/nodejs/node-gyp/issues/679#issuecomment-211117703

**Comment by divgit** [comment]
Real solution for Windows 10 !
https://github.com/nodejs/node-gyp/issues/702#issuecomment-468214903
