### ISSUE TITLE
iojs 2.3.0 name 'openssl_fips' is not defined"

### ISSUE THREAD

**Issue by BlueWinds** [nodejs/node-gyp#652]
While iojs 2.2.1 has been working fine, I'm unable to install any node-gyp configured modules with --target=2.3.0
```
$ npm install --target=2.3.0
\
> usage@0.7.0 install /.../node_modules/usage
> node-gyp rebuild

gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../node_modules/usage
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

```

This is reproducible on both mac and a debian box. Just in case it's relevant or helpful:

```
$ for FLAG in cflags-only-I libs-only-L libs-only-l; do pkg-config --$FLAG openssl; done

-lssl -lcrypto -lz
```

**Comment by Fishrock123** [comment]
@BlueWinds what's your binding.gyp look like?

**Comment by Fishrock123** [comment]
@BlueWinds does this still happen with a new version of io.js?

**Comment by Fishrock123** [comment]
Works for me on OS X:

```
Jeremiahs-MacBook-Pro:here-be-dragons Jeremiah$ npm -v
2.11.1
Jeremiahs-MacBook-Pro:here-be-dragons Jeremiah$ node -v
v2.3.0
Jeremiahs-MacBook-Pro:here-be-dragons Jeremiah$ npm i usage
/
> usage@0.7.0 install /Users/Jeremiah/node_modules/usage
> node-gyp rebuild

  CXX(target) Release/obj.target/sysinfo/src/binding.o
  SOLINK_MODULE(target) Release/sysinfo.node
usage@0.7.0 ../../node_modules/usage
├── bindings@1.2.1
└── nan@1.9.0
Jeremiahs-MacBook-Pro:here-be-dragons Jeremiah$ 
```

Maybe it has to do with your config?

**Comment by bmeck** [comment]
Happens intermittently for most of us at NodeSource

**Comment by BlueWinds** [comment]
I realize now I forgot to include a very important piece of the bug report, for which I apologize:
```
$ node -v
v0.10.31
```
Globally, an older version of node has been installed. So in my case it's an issue compiling more recent versions using --target when an older version of node is installed globally.

The workaround we've ended up using is to put the version of node I wanted to compile against directly in the path.
`PATH=/path/to/iojs-v2.3.3:$PATH npm i usage`

**Comment by bmeck** [comment]
more clearly, `node-gyp` is creating a config from the current `node`'s `process.config` not from the one targetted or used via `--nodedir`

**Comment by bgSosh** [comment]
Has anyone made any progress on this?   Having a similar issue with nw-gyp.

**Comment by cdaringe** [comment]
this is also affecting me as well, 100% of the time.  specifically, electron-rebuild is failing, which calls:

`node {/path/to/}npm-cli rebuild --target=version --arch=version`

@BlueWinds, your suggestion seems reasonable, however, I _dont_ have the binaries for the versions I need to build against all of the time, which is cumbersome.  I'm on `0.12.7`, and @mafintosh ref'd https://github.com/mafintosh/prebuild/issues/14.  maybe it's time to upgrade?

**Comment by royalpinto** [comment]
An extra argument `--openssl_fips=X` worked for me on `OS X`. https://github.com/nwjs/nw.js/issues/3786.

**Comment by bnoordhuis** [comment]
I'll close, I don't believe this is an issue any longer with the supported release lines.

**Comment by jakobrosenberg** [comment]
I seem to getting this error on AWS Lightsail with `electron-rebuild`.

**Comment by cclauss** [comment]
See: #2534

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/issues/2673#issuecomment-1196931379
