### ISSUE TITLE
How can I enable some cflags for specific files?

### ISSUE THREAD

**Issue by hankbao** [nodejs/node-gyp#657]
When building a native addon for OS X, I'd like to set `-fobjc-arc` on some files and unset it on the others.  Is there a way to enable some cflags for specific files? Thanks.

**Comment by justinmchase** [comment]
You could put those flags into their own target, build them as a static library and then add the flags there. Then add that target as a dependency of the other.

**Comment by hankbao** [comment]
That might be a viable solution. It's not much convenient although.

**Comment by rvagg** [comment]
closing due to staleness
