### ISSUE TITLE
How to pass a list as a variable on command line

### ISSUE THREAD

**Issue by piranna** [nodejs/node-gyp#659]
In the next snipped (from node-canvas):

``` Python
{
    'variables':
    {
        'has_cairo%': '<!(./util/has_lib.sh cairo)',
    },
    'conditions':
    [
        ['has_cairo=="true"',
        {
            'includes': ['shared.gyp']
        },
        {
            'includes': ['static.gyp']
        }]
    ],
}
```

you can call node-gyp with `--has_cairo=false` and it will take effect instead of execute the shell script, but how to do if I want to set a list of strings? I think a comma-separated list would be enough (`--foo=a.b.c`), but don't know if gyp (or node-gyp) will parse it...

**Comment by justinmchase** [comment]
The [gyp documentation](https://chromium.googlesource.com/external/gyp/+/master/docs/InputFormatReference.md#Command-Expansions) says:

> You may also put commands into arrays in order to quote arguments (but note that you need to use a different string quoting character):
> ```
'variables' : [
  'files': '<!(["ls", "-1", "Filename With Spaces"])',
],
```

Running `ls -1` from a bash prompt gives me a result of file names separated by new line characters. Therefore, instead of a list of comma-separated items I believe you want a newline-separated list of items. I didn't try it though, I hope it helps :)

**Comment by piranna** [comment]
Yeah, but how do you pass a new-line separated list from command line? Using quotes? It's not too intuitive... Using <@ seems it split on whitespace but didn't test it. Anyway I've changed it for several boolean flags one to explicit enable/disable each backend instead of autodetect, but maybe in the future I still use the array as a shortcut.

**Comment by justinmchase** [comment]
I don't fully understand what you are trying to do but something like this may work:

```
'includes': '<!(./custom_script.sh)'
```

```
#!/bin/bash
# custom_script.sh

echo "static.gyp"
echo "other_dependency.gyp"
# etc.
```

**Comment by piranna** [comment]
What I say is something like

```gyp
'includes%': '<!(./custom_script.sh)'
```

```bash
npm install --includes=foo,bar
```

**Comment by JCMais** [comment]
for anyone looking into this, I'm pretty sure you can use `npm install -includes="foo bar"`.

Gyp uses spaces as separator when expanding a string into a list, at least with the make generator
