### ISSUE TITLE
Inconsistent python2 exe running

### ISSUE THREAD

**Issue by refack** [nodejs/node-gyp#667]
My "weird" system has two executables named `python2`:
```
[12:59:24.60] c:\Users\refael>where python2
C:\Tools\res\scripts\python2.bat
C:\bin\msys64\usr\bin\python2.exe

[13:02:04.47] c:\Users\refael>C:\Tools\res\scripts\python2.bat -V
C:\bin\dev\python27\python.exe -V
Python 2.7.8

[13:02:06.15] c:\Users\refael>C:\bin\msys64\usr\bin\python2.exe -V
Python 2.7.9
```
When running `node-gyp configure` the wrong one is run:
```
...
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Tools\res\scripts\python2.BAT
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.9\n"
...
```

**Comment by TooTallNate** [comment]
Why is it the wrong one? `returned: "2.7.9\n"` <- that's the newer one.

**Comment by refack** [comment]
Obviously the two calls find different exes, and are inconsistent.
`which` finds `python2.bat`, but trying to parse the `exec()` result fails, because node finds `python2.exe` (different file, with no `.` PYTHONPATH fix)
Anyway, on my system, 2.7.8 is win32, and 2.7.9 is msys2

**Comment by refack** [comment]
So you are right @TooTallNate, this stems from `node-which` being inconsistent with `child_process.execFile`'s lookup.
But in this case, if you're already calling `which`, why not use it's result as the explicit path to `python2`?

**Comment by refack** [comment]
Relates to #750
