### ISSUE TITLE
Error: EPERM, utime '/root/.node-gyp/0.6.18'

### ISSUE THREAD

**Issue by sudhanshuraheja** [nodejs/node-gyp#67]
I am unable to get this to work. Here is the complete message I got while trying to install package 'time'.
Also node-gyp could not create /root/.node-gyp automatically, so I had to manually create this and the folder inside it.

root@vercingetorix:~# npm install time -g
npm http GET https://registry.npmjs.org/time
npm http 304 https://registry.npmjs.org/time
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/debug

> time@0.8.2 install /usr/local/lib/node_modules/time
> node-gyp rebuild

info it worked if it ends with ok 
info downloading: http://nodejs.org/dist/v0.6.18/node-v0.6.18.tar.gz 
ERR! UNCAUGHT EXCEPTION:
ERR! Error: EPERM, utime '/root/.node-gyp/0.6.18'
ERR! This is a bug in `node-gyp`. Please open an Issue:
ERR!   https://github.com/TooTallNate/node-gyp/issues
ERR! not ok

npm ERR! time@0.8.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the time@0.8.2 install script.
npm ERR! This is most likely a problem with the time package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls time
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-22-server
npm ERR! command "node" "/usr/local/bin/npm" "install" "time" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message time@0.8.2 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**Comment by zstauber** [comment]
Why was this closed?  I am getting this error on 10.14.2 in 2019, and chmod -R 777 did not solve it.  What is a 'utime' error?
