### ISSUE TITLE
Windows 8.1 fatal error C1083

### ISSUE THREAD

**Issue by Sogl** [nodejs/node-gyp#676]
Hi!

I'm trying to install [Browsersync](http://www.browsersync.io/) module, but it fails with error:

```
  bufferutil.cc
..\src\bufferutil.cc(7): fatal error C1083: Не удается открыть файл включение:
v8.h: No such file or directory [C:\Users\Артем\AppData\Roaming\npm\node_module s\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_module s\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcx proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Артем\AppData\Roaming\npm\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```

Environment:
- Windows 8.1 pro
- Node.js v 0.12.7
- Npm v 2.11.3 (can't update to latest 3.2.0 because https://github.com/npm/npm/issues/9081)
- Python 2.7 with PATH "C:\Python27\python.exe"
- Visual Studio 2013 Community (also tried with VS 2013 Express)
- Microsoft Build Tools 2013 installed
- Windows 8.1 SDK full package
- Windows 7.1 SDK full package
- GYP_MSVS_VERSION path added

Also tried:
- install with "msvs_version=2013"
- delete .node-gyp directory:
  http://stackoverflow.com/questions/19337078/node-gyp-rebuild-always-return-errors
- reinstall node.js and npm

**Comment by Sogl** [comment]
Now I'm on npm 3.2.0 with clear node.js installation - https://github.com/npm/npm/issues/9081

Still the same error.

**Comment by Sogl** [comment]
VS 2015 Community installed. Nothing changed.

**Comment by Sogl** [comment]
After month of researching and downloading/installing I found that if I use non-ASCII userprofile name - I can't install any tool with `node-gyp` dependency.
I renamed my profile to eng. and all works fine now.

**Comment by a0viedo** [comment]
this can be closed now @Trott
