### ISSUE TITLE
Need a new version of gyp to deal with duplicate basenames

### ISSUE THREAD

**Issue by maxkorp** [nodejs/node-gyp#681]
So, MSVS does this beautiful thing where it flattens basenames, such that `a/b/myfile.c` and `d/e/f/myfile.c` both just become `myfile.c`. Gyp only recently (not quite 2 months ago) added a flag for dealing with this here: [25ed9ac4ac2a4d2a08909225fbb6d56e89ad38a6](https://chromium.googlesource.com/external/gyp/+/25ed9ac4ac2a4d2a08909225fbb6d56e89ad38a6). 

This is blocking us updating [nodegit](https://github.com/nodegit/nodegit) to use the latest version of [libgit2](https://github.com/libgit2/libgit2). We've been using a fork of pangyp updated to the latest gyp,
but it doesnt work with any sort of rebuild process then (e.g. the standard setup used by electron projects, where it installs under standard node then uses apm to shell out to npm/node-gyp with global vars set), without forking the whole tree from apm->npm->node-gyp.

It appears that this has been brought in already in the latest iojs ([here](https://github.com/nodejs/io.js/commit/99cbbc0a13fdd554bfc74e29de66fbefc00cfd2a)), if that makes it any easier to pull in. Everything seems ot work locally if i just update the folder. There is one newer commit in iojs with a fix thats already been submitted to gyp but isnt in yet [here](https://github.com/nodejs/io.js/commit/58e914f9bc866fe424aa38b5e9ac42e6216d5f30). I haven't tested with those changes. 

Additionally, code needs to be added for either a commandline flag or (preferably) gypfile config or something to enable the flag to be passed. Currently our fork just always adds it to the args always (see [here](https://github.com/implausible/pangyp/blob/c0bb0c1349722c066669bd9d82c3651394e7b1f7/lib/configure.js))

Let me know if I can be of any assistance. Would a pr be welcome or is there more you like to do?

**Comment by johnhaley81** [comment]
I made a commit bringing that in https://github.com/nodegit/node-gyp/commit/0d8ded7e5dbce630c42da54aa60d67e677a0eb3e

**Comment by maxkorp** [comment]
Further inspection yields that this is a holdover from a few libs in chromium, which have duplicate basenames, but you cant have duplicate basenames if compiling with vs2008 or using make on osx. GYP already dropped support for vs2k8 (https://code.google.com/p/gyp/issues/detail?id=384). Is the later case (osx make) still supported in node-gyp, or is it all xcode? If it's ok to drop support for that, its super easy to resolve the config issue (just always pass the flag to gyp). Otherwise, we need a way to specify that flag for our project, as the default behavior is now to fail to configure if duplicate basenames exist, even when using a platform that allows them to function. I realize the argument for this being a compile time option and not a project setting, but I think now expecting users to pass --no-duplicate-basename-check in addition to other common names like --msvs_version is going to make node-gyp (and by extension npm) start feeling exceptionally verbose for windows again. Perhaps an environment variable?

**Comment by piranna** [comment]
Any update on this? I'm having the same problem to compile `libblkid` from `util-linux` as a npm package...

**Comment by piranna** [comment]
I have reviewed the code and in fact [it would just be to pass the argument](https://github.com/nodejs/node-gyp/blob/f6eab1f9e4b160b60b2736bb01a09c83785ba979/gyp/pylib/gyp/__init__.py#L328-L337). Probably it would be checked and called inconditionally for Linux, so there's no problems there... I could be able to do a pull-request for that.

**Comment by maclover7** [comment]
This is available [here](https://github.com/nodejs/node-gyp/blame/master/gyp/pylib/gyp/generator/ninja.py#L1184) via cc8b2fa83e8cf02beb27c390b4dcfb7564becac0. Going to close for now since the change has landed.
