### ISSUE TITLE
When using custom registry, node-gyp still tries to download files from nodejs.org

### ISSUE THREAD

**Issue by oji** [nodejs/node-gyp#683]
I'm using a custom registry with sinopia. When I install a package that uses node-gyp (i.e., bson-ext), I noticed that it takes too long to run node-gyp rebuild. I found out that it was downloading data from nodejs.org instead of the custom registry. 

Is there a way to use a custom registry to download the binaries?

**Comment by georgepapas** [comment]
+1

**Comment by maclover7** [comment]
If you want to use a custom Node.js dist mirror, you can do that via the `NODEJS_ORG_MIRROR` environment variable, and that should let you override `nodejs.org/dist`.
