### ISSUE TITLE
Failure to run node-gyp configure in iojs 3.0.0

### ISSUE THREAD

**Issue by sbrl** [nodejs/node-gyp#685]
If I try to install the [canvas](//npmjs.org/package/canvas) like this:

```
# npm install canvas
```

I get this:

```
> canvas@1.2.7 install /some/path/here
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/iojs-v3.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/iojs-v3.0.0-linux-x64/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 2.6.32-042stab108.5
gyp ERR! command "/usr/local/lib/iojs-v3.0.0-linux-x64/bin/iojs" "/usr/local/lib/iojs-v3.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/www-admin/codenamerainbowfrog/node_modules/canvas
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 2.6.32-042stab108.5
npm ERR! argv "/usr/local/lib/iojs-v3.0.0-linux-x64/bin/iojs" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www-admin/codenamerainbowfrog/npm-debug.log
```

Apparently, I am supposed to include `npm-debug.log` when requesting help, so I [uploaded it to termbin.com](http://termbin.com/pfck).

Does anyone know why this is happening? Is io.js v3.0.0 not supported?

**Comment by davegomez** [comment]
It seems it is not supported yet, I've been having the same issue while compiling.

**Comment by micky2be** [comment]
same here

**Comment by Fishrock123** [comment]
`gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz`

Are you folks still getting this same error?

**Comment by sbrl** [comment]
@Fishrock123 Yep, I still get the same error. I am runnign Ubuntu Server 15.04.

Here's the output from `uname -a`: 

```
Linux starbeamrainbowlabs.com 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vramana** [comment]
@Fishrock123 Shouldn't that url read `https://iojs.org/dist/v3.0.0/iojs-v3.0.0.tar.gz` cause there is no `v3.0.0` folder in `https://nodejs.org/dist` ??

**Comment by Fishrock123** [comment]
Are you folks trying to build with a different `npm` than ships with io.js? Only io.js's npm is able to build native addons for io.js. (Needs floating patches.)

**Comment by Fishrock123** [comment]
`npm ERR! npm  v2.13.4`

Looks like it. npm is only 2.13.3 in io.js 3.0.0 and 3.1.0.: https://github.com/nodejs/node/commits/6faf17cb45e27cb6feeff4a0da1513ea99a68b58/deps/npm

This is a known issue, sorry. It should be resolvable now that https://github.com/nodejs/node/commit/04fd4fad462d6cb6fa3ddfe3e673903935d9cd5a landed.

**Comment by vramana** [comment]
@Fishrock123 Yeah. I am trying out the latest npm beta version.

**Comment by sbrl** [comment]
@Fishrock123 Nope, I just installed io.js for windows 7 64 bit as normal.

**Comment by Fishrock123** [comment]
@sbrl what does `npm -v` output for you?

**Comment by Fishrock123** [comment]
https://github.com/nodejs/node-gyp/issues/701

**Comment by sbrl** [comment]
@Fishrock123 `2.13.5`.

**Comment by Fishrock123** [comment]
@sbrl Please see the above. :s

**Comment by sbrl** [comment]
@Fishrock123 Updated to npm `2.14.0`, and it still doesn't work. I doesn't really understand what's going on here.

**Comment by CuthbertJungle** [comment]
i had loads of problems with this too. fixed it with https://github.com/creationix/nvm i now have node-gyp building under both node and iojs. result !
