### ISSUE TITLE
Cannot install on Windows 10 (cannot find WindowsSDKDir variable from the registry)

### ISSUE THREAD

**Issue by Jayflux** [nodejs/node-gyp#694]
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Cou ld not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to  an invalid version number. [*******************]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. 
```

Has anybody else got this working?
I've installed Visual Studio 2015

**Comment by Jayflux** [comment]
I reinstalled Visual Studio 2015
went through the steps on this wiki and ran
```
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x64
```

Now i get this
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(214,5): error MSB4175: The task fac
tory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.v12.0.dll". Cou
ld not load file or assembly 'file:///C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.v12.0.dll' or one of its dependencies.
The system cannot find the file specified.
```

**Comment by Fishbowler** [comment]
Check your `GYP_MSVS_VERSION` environment variable, and make sure it's set to 2015. This fixed the first problem for me. I couldn't even get so far as to get the v7.1 SDK installed, so never ran `Setenv.cmd`

**Comment by No9** [comment]
Also can you confirm which version of VS 2015 you installed and also confirmed that you have tried to create a C++ project in the IDE.
Thanks

**Comment by Jayflux** [comment]
@No9 i have not tried to create a C++ project, is this something i should have done?
Also i don't have VS 2015 installed any more as i found moving to 2013 worked, please see the bottom of: https://github.com/nodejs/node-gyp/issues/679

**Comment by No9** [comment]
@Jayflux I noticed in the community edition 2015 RTM that I didn't have a c++ env until I did that. 
No formal instructions on it though :/
Happy that you have found a way through though.

**Comment by guovz** [comment]
+1

**Comment by divmgl** [comment]
Anyone have this working? This is happening to me on Windows 8.

**Comment by No9** [comment]
Hey @divmgl 
What exactly is the error. 
Current recommendation is to create a C++ project in the IDE.

**Comment by abumalick** [comment]
@No9 It worked for me, thanks

**Comment by VPusher** [comment]
Creating a new C++ project and installing prompted deps worked for me too.
> Windows 8.1, Node 0.12.7, npm 2.11.3, VS 2015 Community

I then tried with Node 4.1.1 but got some compilation errors with node-gyp (similar to [this issue](https://github.com/websockets/utf-8-validate/issues/13)). So, I reverted Node to 0.12.7.

Hope will help.

**Comment by divmgl** [comment]
@No9 I apologize that I have not been able to get the exact error. For now I have reinstalled Node 0.12 and Visual Studio 2013 and my issues have been resolved.

**Comment by No9** [comment]
No worries @divmgl thanks for getting back. 
@Jayflux if your issue is resolved then can we close this off?

**Comment by divmgl** [comment]
Welp, I'm having this issue again. This is starting to get extremely frustrating. Same environment as @VPusher.

```
> utf-8-validate@1.2.1 install C:\Users\dmiguel\AppData\Roaming\npm\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\dmiguel\AppData\Roaming\npm\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\dmiguel\AppData\Roaming\npm\node_modules\utf-8-validate\build\validation.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dmiguel\AppData\Roaming\npm\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "utf-8-validate" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utf-8-validate@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dmiguel\Documents\Source\apps-fastcalc\BHG.Apps.FastCalc\Client\js\npm-debug.log
```

**Comment by ravindraprasad75** [comment]
I am getting same problem on Windows 10. "warning MSB8003: Could not find WindowsSDKDir variable from the registry." I am using Node js V4.1.1

**Comment by ocombe** [comment]
Got this working on windows 10 & node js v4 & visual studio community 2015. As @No9 stated, you need to launch Visual studio, then do: file > new > project, in the window than opened, select "Model > Visual C++" and in the middle of the window you should see a button "install microsoft C++" or something like that, click on it and it will launch the install process for the C++ & Microsoft SDK.
Once that's done it will work as expected !

**Comment by tttanaka** [comment]
I was receiving this error and followed the steps above (@combe and @No9). Thanks!

**Comment by Jayflux** [comment]
Can we close this ticket as its a duplicate of https://github.com/nodejs/node-gyp/issues/679
If anyone has issues can you please discuss them there instead
Thanks

**Comment by allenhwkim** [comment]
Agreed to @ocombe, For me, Windows 10 / VS2015 environment, File-New-Project, Installed-Templates-Visual C++, Install SOMETHING did work.

**Comment by johnjelinek** [comment]
https://github.com/nodejs/node-gyp/issues/694#issuecomment-187719884 works for me too.

**Comment by mattblang** [comment]
@ocombe Yeah, that worked me! I had to go to `File -> New Project -> Templates`, then click on the `Visual C++` list item, then in the main area of the dialogue box I saw `Install Visual C++ 2015 Tools for Windows Desktop`. After doing that my `npm install` worked. It was `sha3` that was causing the problem. I'm surprised I haven't broken one of my monitors by now.

**Comment by danilo-teixeira-2** [comment]
@ocombe , that worked me! Thanks!!
