### ISSUE TITLE
gyp ERR MSB3491.

### ISSUE THREAD

**Issue by hogaFarming** [nodejs/node-gyp#697]
I got a error when I install `grunt-browser-syn`.Can somebody help? T-T

OS: Window 7
Operation: `npm install grunt-browser-sync --save-dev`

See this error:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\learning>cd ..\l

E:\l>npm install grunt-browser-sync --save-dev
npm WARN optional dep failed, continuing fsevents@0.3.8
-
...
> utf-8-validate@1.1.0 install E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_m
odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mo
dules\utf-8-validate
> node-gyp rebuild


E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\s
ocket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not def
ined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m"
switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB
3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.lastbuildsta
te". The specified path, file name, or both are too long. The fully qualified file name must be les
s than 260 characters, and the directory name must be less than 248 characters. [E:\l\node_modules\
grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\nod
e-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-valida
te
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

**Comment by rvagg** [comment]
I believe your answer is here:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB
3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.lastbuildsta
te". The specified path, file name, or both are too long. The fully qualified file name must be les
s than 260 characters, and the directory name must be less than 248 characters.
```

It's needing to compile @ `E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj` which is way too long.

You should try and reduce the depth of your dependency tree if you can. The best way you can try and do that right now is upgrade to npm v3 which flattens the dependency hierarchy as much as possible, specifically to deal with this.

**Comment by hogaFarming** [comment]
@rvagg Thank you! I upgraded npm to v3 and it works.
However,I got more problems with npm v3.The version is 3.3.3 and it works not so good.I've got my npm v2 back.

**Comment by rvagg** [comment]
@hogaFarming you could hack similar functionality by adding many of the deep dependencies with the same semver ranges to your top-level project.

e.g. if you have a dependency at: a->b->c->d that has `"e": "^1.1.0"` as a dependency of its own, you could lift it up to the top-level by adding `"e": "^1.1.0"` to your main project and then when you `npm install` the whole lot it should only add it at the top level because it'll decide it doesn't need to add it at the full depth. This'll require you removing node_modules and `npm install` again from scratch.

Also, if you're having npm v3 problems, you should let them know if they haven't already been notified at: https://github.com/npm/npm, it's the future and it's important that it's ready when it ships by default with Node.
