### ISSUE TITLE
Investigate automatic tool installation options

### ISSUE THREAD

**Issue by rvagg** [nodejs/node-gyp#699]
@domenic mentioned on this week's TSC call that V8's depot_tools is able to automatically download and install Windows tooling for compiling. We should investigate whether we can do something similar to minimise some of the Windows pain.

I haven't looked at this at all, just registering for someone who may have time on their hands to take a look and push this forward. Even just an initial investigation and report would be helpful.

**Comment by No9** [comment]
Hi @rvagg 
I looked at this from purely a windows perspective as I think that's where the pain point is. 

Anyway bottom line from the 30 mins I spent is that I don't think it's going to add anything 

V8 page https://developers.google.com/v8/build?hl=en 
points you to https://code.google.com/p/v8-wiki/wiki/BuildingWithGYP for windows builds 
And there is the prerequisit of "Visual Studio 2013" half way down the page. 

So I decided to dive into depot tools
This page https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up 
Says download depot_tools unzip and setup your path
Then run gclient 
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/gclient 
Which is just a wrapper around update_depot_tools
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/update_depot_tools

update_depot_tools calls win_tools.bat
https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/bootstrap/win/win_tools.bat

Which looks to be a wrapper around installing
python276
svn
zip installation 

*No windows native build environment installed there*

So I went to check on the chromium website who I understand to be the main user of depot and sure enough installing visual studio is a pre-requisite there as it is for V8
http://dev.chromium.org/developers/how-tos/build-instructions-windows#TOC-Setting-up-the-environment-for-building-with-Visual-C-2010-Express-or-Windows-7.1-SDK 

i really hope that I have missed something but I used depot a couple of years back for a custom chromium build and that is how I remember it. 

Hope this helps

**Comment by No9** [comment]
@domenic is there another tool/team that are using depot differently that I have missed

**Comment by domenic** [comment]
@No9 sorry about that. It turns out it only works on the Google internal network :(. The code is in https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/win_toolchain/ and based on the readme it might still contain the necessary code for auto-downloading and installing VS community, or maybe that is in an older revision.

**Comment by domenic** [comment]
In fact it looks like https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/win_toolchain/toolchain2013.py would be a good start.

**Comment by No9** [comment]
Pulling @mousetraps in as she was asking for feedback on VS issues.
Sara any light you can shed onto this would be really appreciated.

**Comment by orangemocha** [comment]
Ref: https://msdn.microsoft.com/en-us/library/ee225237.aspx and https://msdn.microsoft.com/en-us/library/e2h7fzkw(v=vs.100).ASPx

I suppose one could use the web bootstrapper to download the setup files locally, and then invoke setup in unattended mode. 

/cc @joshgav, (in case you know of a more streamlined way)

**Comment by bnoordhuis** [comment]
You can `npm install -g windows-build-tools` these days so I'd say this issue can be closed out.
