### ISSUE TITLE
The node-gyp and io.js meta-issue

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-gyp#701]
node-gyp does not work on io.js. This has been a known issue since io.js 1.0.0-ish.

The reason is that node-gyp is hardcoded to do certain things in respect to how node is distributed on nodejs.org. This issue will not into the reasons on why node-gyp needs to download tarballs.

As such, io.js floats a number of floating patches on npm/node-gyp to make node-gyp work, [as can be seen here](https://github.com/nodejs/node/commits/master/deps/npm).

If you are running io.js and attempt to build native modules using a different version of npm than shipped with your version of io.js, your native module builds **will fail**.

https://github.com/nodejs/node-gyp/pull/564 and https://github.com/nodejs/node-gyp/pull/669 attempt to fix this, but as of the time of this issue, both are out of date and neither uses io.js 3.0.0's `process.release`, which was introduced to alleviate this. Version checking could be acceptible for io.js 1.0.0> <3.0.0, as those will only ever be io.js releases.

**Comment by TooTallNate** [comment]
> Version checking could be acceptible for io.js 1.0.0> <3.0.0, as those will only ever be io.js releases.

I do want to add this backwards-compat logic for sure, and of course proper `process.release` checking.

**Comment by sbrl** [comment]
This module seems to be used all over the place. The `canvas` and `ttystudio` packages are just two example. Since it doesn't work with io.js, this prevents me from using a whole bunch of modules, even though my system meets all the other requirements :(

In addition, I think that once io.js and Node.js merge, the io.js version system is going to be used. Does  that mean that `node-gyp` is going to be broken on the next major release on Node.js too?

**Comment by rvagg** [comment]
node-gyp v3, released yesterday, supports both io.js and Node.js, historical versions and near future versions, it'll be bundled with Node.js v4 but isn't bundled with npm just yet—that's coming soon hopefully.

node-canvas has problems of its on in getting up to speed with the current releases, it's been a little painful making the code work with the new V8 but they are nearly ready last I looked. I don't know about ttystudio but they may just need to upgrade to NAN v2 and you'll have to file an issue with them about it—there's nothing node-gyp, nor Node core can do about this, it's all on V8.
