### ISSUE TITLE
Errors when doing npm install with Roots Sage (Wordpress starter theme)

### ISSUE THREAD

**Issue by coffeeneed** [nodejs/node-gyp#703]
Hi. Been strugling with this a couple of hourse. Reinstalling everything, Visual Studio and what'not, but nothing seems to fix this error. Anyone got an ideas on how to fix this? I really need a fix as I just don't know what to do :8ball: 
```
C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(54,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.1.0 install C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\utf-8-validate
> node-gyp rebuild


C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(54,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\thetheme\wp-content\themes\thetheme\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1

```

**Comment by coffeeneed** [comment]
This is now fixed. I didn't only uninstall node from "Remove Programs", but also deleted all the leftover folder, also in the appdata folder. Reinstalled node-v0.12.7-x64.msi and everything seem to work. Case closed :)

**Comment by coffeeneed** [comment]
Well. This problem is, unfortunately, back again :( I tried removed the node_modules folder and tried again. Problem persists. Have tried to install the Windows SDK 7.1 too and set the path to setenv.cmd (like mentioned all over the net, by other people experiencing this problem).

**Comment by coffeeneed** [comment]
Update: Looks like I am one step further regarding this issue. Managed to get try and run "npm install" (still using Wordpress Roots Sage) through call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x64. It says folder structure is too long. I've experienced the same when trying to manually delete node_module folder in Windows. That won't work because of the folder path size (I've done rm -rf node-modules from Git Bash instead). However, if this is a deeper problem regarding path sizes, I'm not very optimistic.

Here's an updated log from npm install:

C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework
,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version
of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and
 will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\xampp\htdocs\od
dkamp\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modul
es\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(1605,5): warning MSB3101: Could not write state file "Release\obj\bufferutil\b
ufferutil.vcxprojResolveAssemblyReference.cache". The specified path, file name, or both are too long. The fully qualified file name must be less than
260 characters, and the directory name must be less than 248 characters. [C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\n
ode_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
  bufferutil.cc
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(1024,23): error MSB4198: The expression "DirectoryName" cannot be evaluate
d on item "Release\obj\bufferutil\bufferutil.node.intermediate.manifest". The specified path, file name, or both are too long. The fully qualified file
 name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\xampp\htdocs\trends\wp-content\themes\trends\nod
e_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build
\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> utf-8-validate@1.1.0 install C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblies for framework ".NETFramework
,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version
of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and
 will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\xampp\htdocs\od
dkamp\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modul
es\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(1605,5): warning MSB3101: Could not write state file "Release\obj\validation\v
alidation.vcxprojResolveAssemblyReference.cache". The specified path, file name, or both are too long. The fully qualified file name must be less than
260 characters, and the directory name must be less than 248 characters. [C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\n
ode_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(254,5): error MSB3371: The file "Release\obj\validation\validation.unsucce
ssfulbuild" cannot be created. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and
 the directory name must be less than 248 characters. [C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.
io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

> node-sass@2.1.1 install C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> node-sass@2.1.1 postinstall C:\xampp\htdocs\trends\wp-content\themes\trends\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

`win32-x64-node-0.12` exists; testing
Binary is fine; exiting
gulp-rename@1.2.2 node_modules\gulp-rename

minimist@1.2.0 node_modules\minimist

traverse@0.6.6 node_modules\traverse

lazypipe@0.2.4 node_modules\lazypipe
+-- stream-combiner@0.2.2 (duplexer@0.1.1, through@2.3.8)

run-sequence@1.1.2 node_modules\run-sequence
+-- chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)

jshint-stylish@1.0.2 node_modules\jshint-stylish
+-- log-symbols@1.0.2
+-- text-table@0.2.0
+-- string-length@1.0.1 (strip-ansi@3.0.0)
+-- chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)

susy@2.2.5 node_modules\susy

merge-stream@0.1.8 node_modules\merge-stream
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

gulp-sourcemaps@1.5.2 node_modules\gulp-sourcemaps
+-- graceful-fs@3.0.8
+-- convert-source-map@1.1.1
+-- strip-bom@1.0.0 (first-chunk-stream@1.0.0, is-utf8@0.2.0)
+-- vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

gulp-load-plugins@0.10.0 node_modules\gulp-load-plugins
+-- multimatch@2.0.0 (array-differ@1.0.0, array-union@1.0.1, minimatch@2.0.10)
+-- findup-sync@0.2.1 (glob@4.3.5)

gulp-if@1.2.5 node_modules\gulp-if
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- gulp-match@0.2.1 (minimatch@1.0.0)
+-- ternary-stream@1.2.3 (fork-stream@0.0.4, duplexer2@0.0.2)

compass-mixins@0.12.7 node_modules\compass-mixins

del@1.2.1 node_modules\del
+-- is-path-cwd@1.0.0
+-- object-assign@3.0.0
+-- each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.0.0)
+-- is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
+-- globby@2.1.0 (async@1.4.2, array-union@1.0.1, glob@5.0.14)
+-- rimraf@2.4.3 (glob@5.0.14)

gulp-changed@1.3.0 node_modules\gulp-changed
+-- through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.11)

gulp-flatten@0.0.4 node_modules\gulp-flatten
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-rev@3.0.1 node_modules\gulp-rev
+-- object-assign@2.1.1
+-- vinyl-file@1.2.1 (graceful-fs@4.1.2, strip-bom-stream@1.0.0, strip-bom@2.0.0, vinyl@0.5.1)
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-plumber@1.0.1 node_modules\gulp-plumber
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-concat@2.6.0 node_modules\gulp-concat
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- concat-with-sourcemaps@1.0.2 (source-map@0.4.4)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-minify-css@1.2.1 node_modules\gulp-minify-css
+-- object-assign@4.0.1
+-- readable-stream@2.0.2 (process-nextick-args@1.0.2, isarray@0.0.1, inherits@2.0.1, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
+-- vinyl-bufferstream@1.0.1 (bufferstreams@1.0.1)
+-- vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, through2@2.0.0, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.11)
+-- clean-css@3.4.1 (commander@2.8.1, source-map@0.4.4)

gulp@3.9.0 node_modules\gulp
+-- pretty-hrtime@1.0.0
+-- interpret@0.6.5
+-- deprecated@0.0.1
+-- archy@1.0.0
+-- tildify@1.1.0 (os-homedir@1.0.1)
+-- v8flags@2.0.10 (user-home@1.1.1)
+-- chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
+-- semver@4.3.6
+-- orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
+-- vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-uglify@1.4.0 node_modules\gulp-uglify
+-- uglify-save-license@0.4.1
+-- deap@1.0.0
+-- through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
+-- vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, lodash.template@3.6.2, chalk@1.1.1, multipipe@0.1.2, dateformat@1.0.11)
+-- uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

asset-builder@1.1.0 node_modules\asset-builder
+-- object-path@0.9.2
+-- minimatch@2.0.10 (brace-expansion@1.1.0)
+-- main-bower-files@2.9.0 (path-exists@1.0.0, strip-json-comments@1.0.4, extend@2.0.1, multimatch@2.0.0, chalk@1.1.1, globby@2.1.0, vinyl-fs@1.0.0)
+-- lodash@3.10.1

wiredep@2.2.2 node_modules\wiredep
+-- propprop@0.3.0
+-- chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
+-- lodash@2.4.2
+-- bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)

gulp-autoprefixer@2.3.1 node_modules\gulp-autoprefixer
+-- object-assign@2.1.1
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- postcss@4.1.16 (js-base64@2.1.9, source-map@0.4.4, es6-promise@2.3.0)
+-- autoprefixer-core@5.2.1 (num2fraction@1.1.0, browserslist@0.4.0, caniuse-db@1.0.30000280)

gulp-imagemin@2.3.0 node_modules\gulp-imagemin
+-- plur@1.0.0
+-- object-assign@3.0.0
+-- chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
+-- pretty-bytes@2.0.1 (get-stdin@4.0.1, number-is-nan@1.0.0, meow@3.3.0)
+-- through2-concurrent@1.1.0 (through2@2.0.0)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, through2@0.6.5, meow@3.3.0, buffer-to-vinyl@1.0.1, concat-stream@1.5.0, stream-combiner2@1.0.2, vinyl-fs@1.0.0, imagemin-optipng@4.3.0, imagemin-gifsicle@4.2.0, imagemin-svgo@4.1.2, imagemin-jpegtran@4.3.0)

gulp-less@3.0.3 node_modules\gulp-less
+-- object-assign@2.1.1
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- accord@0.15.2 (indx@0.2.3, convert-source-map@0.4.1, fobject@0.0.3, resolve@1.1.6, when@3.7.3, glob@4.5.3, uglify-js@2.4.24, lodash@3.10.1)
+-- less@2.5.1 (graceful-fs@3.0.8, mime@1.3.4, image-size@0.3.5, promise@6.1.0, errno@0.1.4, mkdirp@0.5.1, source-map@0.4.4, request@2.61.0)

gulp-jshint@1.11.2 node_modules\gulp-jshint
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- minimatch@2.0.10 (brace-expansion@1.1.0)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
+-- lodash@3.10.1
+-- jshint@2.8.0 (strip-json-comments@1.0.4, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)

imagemin-pngcrush@4.1.0 node_modules\imagemin-pngcrush
+-- is-png@1.0.0
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- exec-buffer@2.0.1 (tempfile@1.1.1, rimraf@2.4.3)
+-- pngcrush-bin@3.0.0 (logalot@2.1.0, bin-wrapper@3.0.2, bin-build@2.1.2)

browser-sync@2.5.0 node_modules\browser-sync
+-- async-each-series@0.1.1
+-- emitter-steward@0.0.1
+-- opn@1.0.2
+-- dev-ip@1.0.1
+-- ua-parser-js@0.7.9
+-- browser-sync-client@1.0.2
+-- foxy@10.1.2 (cookie@0.1.3, http-proxy@1.11.1)
+-- portscanner@1.0.0 (async@0.1.15)
+-- serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
+-- meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, indent-string@1.2.2)
+-- connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
+-- resp-modifier@2.1.0 (minimatch@2.0.10)
+-- immutable@3.7.4
+-- serve-index@1.7.2 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, accepts@1.2.12, debug@2.2.0, mime-types@2.1.5)
+-- glob-watcher@2.0.0 (gaze@0.5.1)
+-- easy-extender@2.3.1 (lodash@2.4.2)
+-- eazy-logger@2.1.2 (tfunk@3.0.1, opt-merger@1.1.0)
+-- localtunnel@1.7.0 (debug@0.7.4, openurl@1.1.0, yargs@3.15.0, request@2.11.4)
+-- lodash@3.10.1
+-- browser-sync-ui@0.5.15 (connect-history-api-fallback@0.0.5, stream-throttle@0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
+-- socket.io@1.3.6 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.2, socket.io-client@1.3.6)

gulp-sass@1.3.3 node_modules\gulp-sass
+-- clone@0.1.19
+-- map-stream@0.1.0
+-- vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, chalk@1.1.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- node-sass@2.1.1 (get-stdin@4.0.1, object-assign@2.1.1, replace-ext@0.0.1, cross-spawn@0.2.9, chalk@0.5.1, semver@4.3.6, shelljs@0.3.0, mkdirp@0.5.1, npmconf@2.1.2, meow@3.3.0, nan@1.9.0, gaze@0.5.1, sass-graph@1.3.0, request@2.61.0, mocha@2.2.5, pangyp@2.3.0)

**Comment by bnoordhuis** [comment]
I can't guarantee that it works but try `subst z: \xampp\htdocs\trends\wp-content\themes\trends` as administrator and then run `npm install` from `z:\`.

**Comment by coffeeneed** [comment]
@bnoordhuis 
Thanks, that might have done something good, actually :) Interesting. However, I get another error now. Do you have more clues, Sir?

---------------------------------------------------------

Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblies for framework
 ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget
your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be reso
lved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctl
y targeted for the framework you intend. [Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules
\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
  bufferutil.cc
     Creating library Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no
  de_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib and object Z:\node_modules\browser-sync\node_modules\socket.io\node
  _modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\
  node_modules\ws\node_modules\bufferutil\build\Release\\bufferutil.node

> utf-8-validate@1.1.0 install Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.Targets(983,5): warning MSB3644: The reference assemblies for framework
 ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget
your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be reso
lved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctl
y targeted for the framework you intend. [Z:\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules
\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]

**Comment by bnoordhuis** [comment]
Make sure you have Visual Studio 2013 installed.  (2012 may also be alright for node.js v0.12.)

If you still get the error, try `set GYP_MSVS_VERSION=2013` before you run node-gyp.

**Comment by coffeeneed** [comment]
What worked :) Hurray! Thanks. Help appreciated.
