### ISSUE TITLE
node-gyp configure error in BeagleBoneBlack

### ISSUE THREAD

**Issue by pradhanshrijal** [nodejs/node-gyp#705]
I cannot run: node-gyp configure

![node-gyp-err](https://cloud.githubusercontent.com/assets/11836341/9543099/419a8f24-4da0-11e5-8b85-5796af66b5f8.JPG)

**Comment by rvagg** [comment]
Dupe, of lots of issues, https://github.com/nodejs/node-gyp/search?q=--no-parallel&type=Issues&utf8=%E2%9C%93

I think this is almostl exclusively a problem on BeagleBone Black and we probably should fix it cause it shows up frequently. Can you tell us what `gcc --version` says?

**Comment by pradhanshrijal** [comment]
gcc is 4.6.3

![gcc-v](https://cloud.githubusercontent.com/assets/11836341/9543806/07dcb234-4da6-11e5-8cc3-7f1016a65306.JPG)
