### ISSUE TITLE
Is there a timeline for supporting nodejs 0.12?

### ISSUE THREAD

**Issue by marsinvasion** [nodejs/node-gyp#706]
While playing with time https://github.com/TooTallNate/node-time/issues/79 I noticed that node-gyp doesn't support node 0.11 and 0.12. Is there a timeline for adding support or are those version not going to be supported?

Platform: Ubuntu  14.04

**Comment by TooTallNate** [comment]
This is an issue with node-time not being up-to-date with the latest nan dependency. node-gyp definitely works with v0.12.

**Comment by TooTallNate** [comment]
Try `node-time` v0.11.4, I just published it.

**Comment by marsinvasion** [comment]
sweet that works. Thanks.
