### ISSUE TITLE
fatal error: 'sys/signal.h' file not found

### ISSUE THREAD

**Issue by vleckas** [nodejs/node-gyp#712]
Hi, I'm getting the following error when trying to install bcrypt. I've globally installed node-gyp, Command Line Tools, Python v 2.7.x and X-Code v 6.x. Any assistance would be greatly appreciated. I'm running OS X Yosemite 10.10.3.
```
CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
In file included from ../src/bcrypt.cc:49:
In file included from /usr/include/stdlib.h:65:
/usr/include/sys/wait.h:109:10: fatal error: 'sys/signal.h' file not found
#include <sys/signal.h>         /* [XSI] for siginfo_t */
         ^
1 error generated.
```

**Comment by Fishrock123** [comment]
@vleckas We can't help you without the node and node-gyp versions.

**Comment by vleckas** [comment]
Thank you, good point:

node v0.12.7
node-gyp v2.0.2

**Comment by rvagg** [comment]
I really think this is an issue for the bcrypt folks, https://github.com/ncb000gt/node.bcrypt.js @defunctzombie might know what this is by looking at it

**Comment by defunctzombie** [comment]
```In file included from /usr/include/stdlib.h:65:
/usr/include/sys/wait.h:109:10: fatal error: 'sys/signal.h' file not found
#include <sys/signal.h>         /* [XSI] for siginfo_t */```

Your headers look messed up. All we do is include stdlib.h in bcrypt. That header for you seems to include other headers leading to compilation failure. Recommend you investigate your system environment.

**Comment by vleckas** [comment]
Got it. Thank you both for pointing me in the right direction, much appreciated!
