### ISSUE TITLE
Broken support for passing options to gyp

### ISSUE THREAD

**Issue by springmeyer** [nodejs/node-gyp#720]
Testing node-pre-gyp against node 4.x (which I presume bundles this version of node-gyp) revealed a regression of one obscure feature of previous node-gyp versions. That is you could do:

```sh
node-gyp configure -- -Dfoo=bar
```

And then anything after the `--` would be passed directly to gyp. This is a feature used by the node C++ bindings to [Mapbox GL](https://github.com/mapbox/node-mapbox-gl-native/blob/7092d1c60362d4c66f9272f5fe72f1823bdf0a80/Makefile#L43-L51). When this is passed now node-gyp issues an odd error:

```
gyp ERR! configure error 
gyp ERR! stack Error: Invalid version number: -Dfoo=bar
gyp ERR! stack     at getNodeDir (/Users/dane/projects/node-gyp/lib/configure.js:150:25)
gyp ERR! stack     at /Users/dane/projects/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
```

Seen in the node-pre-gyp tests after adding 4.x testing support: https://travis-ci.org/mapbox/node-pre-gyp/jobs/79551719

**Comment by rvagg** [comment]
ok, this is to do with my last round of changes, I think I know how to fix this and will get a patch bump out shortly and we'll bundle that in 4.0.1

**Comment by springmeyer** [comment]
Thank you!

**Comment by Fishrock123** [comment]
Should be fixed in https://github.com/nodejs/node-gyp/commit/6e8c3bf3c64e5f90b8cd49679e3b4d77f3ade401
