### ISSUE TITLE
Why 'http://nodejs.org/dist' is accessed during 'npm rebuild'?

### ISSUE THREAD

**Issue by enobufs** [nodejs/node-gyp#726]
I am not sure if this is the right place ask this question. Please let me know if you have any information of this...

It happened a couple of days ago, due to (probably) a misconfiguration of their web site, our `npm rebuild` failed because accesses to http://nodejs.org/dist was redirected a wrong place (its blog page). What failed was a build of dtrace-provider@0.2.8 that was needed by old bunyan(@<3.0.0). It was fixed by updating the module.

What I don’t understand is why ‘npm rebuild’ needs to access http://nodejs.org/dist. Funny thing is, I intercepted the traffic to nodejs.org during npm rebuild and returned 500 (http status code). The rebuild succeeds for all the modules, except dtrace-provider@0.2.8 (>=0.3.0 succeeds). We do shinkwrap before hand, so I’d expect there’s nothing to download during the rebuild.

I would appreciate if you could give me any insight into this behavior.

**Comment by enobufs** [comment]
Slightly related: #683

**Comment by rvagg** [comment]
two things here:

1. there was a short period where our server was misconfigured and there was a redirect active that messed up http://nodejs.org/dist, that would have been your original problem with getting the blog page
2. when you `npm rebuild` it needs to download the source or headers in order to compile against them, it gets these from nodejs.org/dist and that's why it's trying to access that. dtrace-provider is only needed on platforms where that works, mainly smartos and osx I believe, other than that it's not required in order to use bunyan. The reason that your upgrade works now is probably because bunyan now has it listed as in ["optionalDependencies"](https://github.com/trentm/node-bunyan/blob/master/package.json#L22) so a failure is fine. So if you're not building any other compiled addons then your current process including blocking access to nodejs.org should be perfectly fine.

**Comment by enobufs** [comment]
Thanks @rvagg . What I do not understand is, after removing bunyan, my project still succeeds with npm rebuild even thought I forced the http access to nodejs.org/dist to fail with 500 error. Now I have an empty project that has bson@0.2.22 in the dependency section of its package.json, then do:

```
rm -rf node_modules
rm npm-shrinkwrap.json
npm install --production
npm shrinkwrap
rm -rf ~/.node-gyp
npm_config_disturl=http://localhost:3000/dist npm rebuild
```

The last line actually generates GET /ist/v0.10.38/node-v0.10.38.tar.gz once which will receives 500 error (forced). The npm rebuild succeeds... Shouldn't it fail?
I am using node 0.10.38, npm 1.4.28 and globally installed node-gyp 3.0.1.

**Comment by enobufs** [comment]
Now, I noticed that during the npm rebuild (with 500) generates the following error log found at:
node_modules/bson/builderror.log

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/ytakeda/node/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onResponse (/Users/ytakeda/node/v0.10.38/lib/node_modules/npm/node_modules/request/request.js:1085:10)
gyp ERR! stack     at ClientRequest.g (events.js:180:16)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/ytakeda/node/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ytakeda/Projects/others/rebuild/node_modules/bson
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
```

I have also confirmed that npm rebuild succeeds with exit code 0.

The npm rebuild happens at destination hosts in a cluster during deployment (AWS Elastic Beanstalk I am using does this), a different host (at a different time) from the one where npm install/shrinkwrap is performed. So, this could be huge problem if `npm rebuild` does not report the error, couldn't it?

**Comment by rvagg** [comment]
yeah, that's an odd one, we probably need to investigate whether exit codes are properly returned by node-gyp and then propagated by npm

**Comment by enobufs** [comment]
@rvagg, later I noticed that bson uses nan which has a native code, but it appears to be optional. At run-time, I can see:

```
js-bson: Failed to load c++ bson extension, using pure JS version
```

I also expected rebuild of mongodb (native driver) would fail (if access to nodejs.org/dist fails)  with kerberos, but it is in 'optionalDependencies'.

It would be nice if we could see them as warnings on the console during npm-rebuild, but since all my initial questions were answered, let me close this ticket. Thank you.
