### ISSUE TITLE
Install on windows 7 npm install express

### ISSUE THREAD

**Issue by nianyuyu** [nodejs/node-gyp#727]
C:\Windows\System32>npm -v
2.14.3

C:\Windows\System32>npm install -g express-generator
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-6244-0dfa1f36\registry
.npmjs.org\express-generator\-\express-generator-4.13.1.tgz.dadd30692696e4e6c2ec
a59c608dc74b' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-6244-0dfa1f36\registr
y.npmjs.org\express-generator\-\express-generator-4.13.1.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Nodejs\\node.exe" "D:\\Nodejs\\node_global\\node_modules\\npm
\\bin\\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! path C:\Users\ADMINI~1\AppData\Local\Temp\npm-6244-0dfa1f36\registry.np
mjs.org\express-generator\-\express-generator-4.13.1.tgz
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ADMINI~1\AppDa
ta\Local\Temp\npm-6244-0dfa1f36\registry.npmjs.org\express-generator\-\express-g
enerator-4.13.1.tgz' while getting shasum for C:\Users\ADMINI~1\AppData\Local\Te
mp\npm-6244-0dfa1f36\registry.npmjs.org\express-generator\-\express-generator-4.
13.1.tgz
npm ERR! enoent From:     http://registry.npmjs.org/express-generator/-/express-
generator-4.13.1.tgz
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-6244-0dfa1f36\registry
.npmjs.org\express-generator\-\express-generator-4.13.1.tgz.b29c4e4f4ca015454754
3c0147d1464b' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-6244-0dfa1f36\registr
y.npmjs.org\express-generator\-\express-generator-4.13.1.tgz'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

C:\Windows\System32>

**Comment by rvagg** [comment]
not much we can do here, I suggest you clean out your temp directory (`C:\Users\ADMINI~1\AppData\Local\Temp\`) and try again, if the problem persists try contacting the express-generator maintainers however this looks very much like a windows setup problem that is going to be difficult to diagnose without being able to see what else is going on with your computer -- perhaps you have antivirus software or something else that is busy poking through your files
