### ISSUE TITLE
Install on windows 7 npm install express

### ISSUE THREAD

**Issue by nianyuyu** [nodejs/node-gyp#728]
Error creating Node.js Express App. Failed command:
D:\Nodejs\node.exe D:\Nodejs\node_modules\npm\bin\npm-cli.js install express-generator@4.13.1
Exit code: -4058
Standard error:
npm WARN retry will retry, error on last attempt: Error: EBUSY, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-10944-c6975a34\registry.npmjs.org\commander\-\commander-2.7.1.tgz.71878c64ae83d1c6ea5ac604bb2a2fa8'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Nodejs\\node.exe" "D:\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-generator@4.13.1"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\ADMINI~1\AppData\Local\Temp\npm-10944-c6975a34\registry.npmjs.org\commander\-\commander-2.7.1.tgz
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-10944-c6975a34\registry.npmjs.org\commander\-\commander-2.7.1.tgz' while getting shasum for C:\Users\ADMINI~1\AppData\Local\Temp\npm-10944-c6975a34\registry.npmjs.org\commander\-\commander-2.7.1.tgz
npm ERR! enoent From:     http://registry.npmjs.org/commander/-/commander-2.7.1.tgz
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Users\Administrator\AppData\Local\Temp\intellij-express-generator0.tmp\node_modules'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, rmdir 'C:\Users\Administrator\AppData\Local\Temp\intellij-express-generator0.tmp\node_modules']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\intellij-express-generator0.tmp\\node_modules' }
npm WARN retry will retry, error on last attempt: Error: EBUSY, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-10944-c6975a34\registry.npmjs.org\commander\-\commander-2.7.1.tgz.8aa0f60bd936b688a49bb65c3a5dcd42'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\intellij-express-generator0.tmp\node_modules\npm-debug.log

**Comment by rvagg** [comment]
looks like an intellij problem to me, try removing C:\Users\Administrator\AppData\Local\Temp\intellij-express-generator0.tmp\ and other similarly named directories and try again, if the problem persists I'm not sure there's much we can do here given that you seem to be running this in a complex IDE environment for which we have little insight
