### ISSUE TITLE
child process execute fail

### ISSUE THREAD

**Issue by xionglun** [nodejs/node-gyp#730]
![image](https://cloud.githubusercontent.com/assets/1031768/9866664/b39813d0-5b97-11e5-83aa-4ff1f6022e2a.png)

node-gyp cannot execute by child_process?

**Comment by rvagg** [comment]
I'm not sure exactly what your failure is here but node-gyp is a Node.js program that you'll need to execute with `node` in front if you're going to do it with child_process

**Comment by xionglun** [comment]
It seems my mistake, sorry.
