### ISSUE TITLE
Delay hook absolute path cannot be created error MSB3191: Unable to create directory: The given path's format is not supported

### ISSUE THREAD

**Issue by saper** [nodejs/node-gyp#732]
Full log: https://gist.github.com/saper/08ce8416f944a7fed3dc
[addon.gypi used](https://gist.github.com/saper/6fc5a3b6daef5378eeb1)
[generated libgit2.vcxproj](https://gist.github.com/saper/1f9e9a7c68bfff6c1fe5)
Source being built: https://github.com/saper/nodegit/tree/41c9e13f25441726a2493fd9279fc00db0087da9
Environment: @Appveyor [full log](https://ci.appveyor.com/project/saper/nodegit/build/job/5gw8go2hcvefojl6)

node-gyp is installed globally before just `npm install` on the package (nodegit).

Error message:

```
error MSB3191: Unable to create directory 
"C:\projects\nodegit\vendor\Release\obj\libgit2\C:\projects\nodegit\node_modules\node-gyp\src". 
The given path's format is not supported.
```

It looks like the ['<(node_gyp_dir)/src/win_delay_load_hook.c'](https://gist.github.com/saper/6fc5a3b6daef5378eeb1#file-absolute-path-addon-gypi-L44) formula doesn't mix here well...

<strike>Btw. is it normal that `.vcxproj` files are created in the source tree and not in the `build` directory?</strike> relative paths fixed

Related: #636 #637 #708

**Comment by saper** [comment]
Some investiagation:

1. Does not matter if using MSBuild 12.0 (from VS2013) or MSBuild 14.0 (from VS2015).
2. `win_delay_hook` seems to be added to **all** targets by default (in all projects I have seen)
3. Out of few attempts to compile `win_delay_hook` in the nodegit project, only one fails.
4. This errors occurs in the Visual C++-specific `MakeDirsForCl` task.

For `nodegit` it creates directories only for one of the targets (https://github.com/saper/nodegit/blob/7b30e1d3a6180db36a13503be525252435bbb85e/vendor/libgit2.gyp#L14) out of few in the project.

For `node-sass` this target is not needed.

**Comment by saper** [comment]
`MakeDirForCl` uses several properties to create directories and activates only if one of those are present. `ObjectFileName` is one of such properties and this one is set in https://gist.github.com/saper/1f9e9a7c68bfff6c1fe5#file-libgit2-vcxproj-L53 to `$(IntDir)%(RelativeDir)/`

**Comment by saper** [comment]
So it seems to me the only issue left to clarify is why `%(RelativeDir)%` is absolute:)

**Comment by panuhorsmalahti** [comment]
I'm also getting ths.

**Comment by saper** [comment]
So the absolute `%(RelativeDir)` for the Windows delay hook is caused by #637. I have worked around this in the node-git project by not using `%(RelativeDir)` at all, but this is broken for projects that need it.

**Comment by ThePhD** [comment]
This bug has negatively affected me twice and has cost me a serious amount of time: I use %(RelativeDir) to help differentiate my OBJ file builds in my C++ projects. You can imagine my surprise when I finally figured out Node.js was hooking into, using, and turning %(RelativeDir) into an absolute dir.

I am new to the Node community, but if anyone has any ideas for how I can fix this, I would not mind hacking on node-gyp to help fix this. This is the second time it's come out of nowhere and really negatively affected me, wasting quite a few hours peeling through npm logs and trying all sorts of native installs before pinning this down.

**Comment by rvagg** [comment]
I think this might be something to take up at https://github.com/refack/GYP
