### ISSUE TITLE
C:\Users\username\.node-gyp\4.0.0\common.gypi not found

### ISSUE THREAD

**Issue by rainabba** [nodejs/node-gyp#735]
Similar to https://github.com/nodejs/node-gyp/issues/376

`\4.0.0\include\node` does have common.gypi, but not the 4.0.0 folder whereas all the other versions I have (back to 0.8.20) have them right in the root of the version folder.

Is this an issue with node-gyp or the script from heapdump?

```
myProject [feature/AddLabUnitTesting +2 ~2 -0 !]> npm install heapdump --save
\
> heapdump@0.3.7 install myProject\node_modules\heapdump
> node-gyp rebuild


myProject\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Users\myUsername\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp: C:\Users\myUsername\.node-gyp\4.0.0\common.gypi not found (cwd: myProject\node_modules\heapdump) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\myUsername\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myUsername\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd myProject\node_modules\heapdump
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myUsername\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "heapdump" "--save"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     myProject\npm-debug.log
```

Issues filed with heapdump: https://github.com/bnoordhuis/node-heapdump/issues/66#issuecomment-141113319

**Comment by bnoordhuis** [comment]
I also commented on the heapdump issue but make sure you use the npm and node-gyp that come with node v4.

**Comment by rainabba** [comment]
After uninstalling/installing 4.1.0 and back to 4.0.0 and more reading, something was brought to my attention: `gyp ERR! node-gyp -v v2.0.2` when I run `node-gyp -v`, I get 3.0.3 (and I'd previously confirmed that).  Thanks to https://github.com/nodejs/node-gyp/issues/724 I realized that my globally installed version was stale.

I've tried upgrading every way I know and at the CLI, -v reports 3.0.3, but npm installs keep failing and reporting 2.0.2 in the stack.

I'm on Windows if that wasn't clear. Do I have 2 versions installed and builds are using the wrong/older version?

**Comment by rainabba** [comment]
While `C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp` had 3.0.3, `C:\Users\myusername\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp` had 2.0.2.

I emptied the older folder and copied over the contents of the newer. Seems that npm isn't dealing well with the fact that there's the system node_modules AND user account node_modules THEN the actual project.

**Comment by QuietWind** [comment]
my node is 4.0.0 is not install ! this i checkout to 0.12 can do it!..
