### ISSUE TITLE
Node-gyp is failing with Node 4.0/4.1 on Linux machines

### ISSUE THREAD

**Issue by Jiran** [nodejs/node-gyp#742]
My heroku deployments are failing for any package that depends on Node-Gyp. 

```
remote: 17426 verbose pkgid bufferutil@1.1.0
remote: 17427 verbose cwd /tmp/build_50d076bfbfe3fc826096ebd4213366a7
remote: 17428 error Linux 3.13.0-61-generic
remote: 17429 error argv "/tmp/build_50d076bfbfe3fc826096ebd4213366a7/vendor/node/bin/node" "/tmp/build_50d076bfbfe3fc826096ebd4213366a7/vendor/node/bin/npm" "rebuild"
remote: 17430 error node v4.1.1
remote: 17431 error npm  v2.14.4
remote: 17432 error code ELIFECYCLE
remote: 17433 error bufferutil@1.1.0 install: `node-gyp rebuild`
remote: 17433 error Exit status 1
remote: 17434 error Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
remote: 17434 error This is most likely a problem with the bufferutil package,
remote: 17434 error not with npm itself.
remote: 17434 error Tell the author that this fails on your system:
remote: 17434 error     node-gyp rebuild
remote: 17434 error You can get their info via:
remote: 17434 error     npm owner ls bufferutil
remote: 17434 error There is likely additional logging output above.
```

**Comment by rvagg** [comment]
I believe bufferutil@1.1.0 isn't compatible, you're going to want bufferutil@1.2.1, or whatever dependency is using bufferutil will want it -- so you probably want to upgrade some dependencies to find ones that have been updated, or go hassle them to update.

**Comment by puzankov** [comment]
the same issue

**Comment by ralphtheninja** [comment]
@Jiran Do you have any more verbose output by any chance? If you could stick in a `--verbose` somewhere and post the output in a gist that would be awesome!

**Comment by puzankov** [comment]
my gist: https://gist.github.com/puzankov/8dd9bba01a87fe62af77

**Comment by bnoordhuis** [comment]
@puzankov You need to use a C++11-capable compiler: g++ 4.8 or newer, or clang++ 3.4 or newer.

**Comment by ralphtheninja** [comment]
> @puzankov You need to use a C++11-capable compiler: g++ 4.8 or newer, or clang++ 3.4 or newer.

Correct :)

**Comment by Jiran** [comment]
@ralphtheninja My verbose output from Heroku. https://gist.github.com/Jiran/06f8c294133c3c702d9e 

I was having similar issues locally on my Mac until I updated Xcode and command line tools which however my deployment is on Heroku so I don't know what I can do to solve it, as I don't think I can fix compiler issues through Heroku, can I, could it possibly be something else?

**Comment by ralphtheninja** [comment]
People using travis for testing have had the same problems. The compiler has to be up to date to handle c++11. You could try to persuade all the native modules to start creating prebuilt binaries for you so you don't need to handle the compile step.

**Comment by Jiran** [comment]
@ralphtheninja thanks for the help. I realized I was using custom buildpacks that haven't been updated in a while so I used the official Heroku buildpack and I'm back online. Thanks for the help.

**Comment by aug70** [comment]
Had the same problem, bufferutil is at version 1.2.1 (as of 10/27/2015) but not installing...
Below plugin, purged cache and fixed the problem on heroku

```
heroku plugins:install https://github.com/heroku/heroku-repo.git
heroku repo:purge_cache -a {your app name}
git push heroku master
```

**Comment by aroc** [comment]
Just want to point out that @aug70's fix above worked for me when nothing else did. Thanks so much for that!
