### ISSUE TITLE
The default choice between debug and release builds depends ultimately on whether the node executable running it was compiled in debug or release modes. Was this intended?

### ISSUE THREAD

**Issue by gcharnock** [nodejs/node-gyp#743]
When running `node-gyp configure` without `--debug` or `--release` the build type it default to depends entirely on how the node executable that runs `node-gyp` was defined.

This can cause problems when building things. For example, [strong-for-syslog](https://github.com/strongloop-forks/strong-fork-syslog) turned out to be a dependency of a dependency of a dependency of the project I was working on. Running `npm install` with a node compiled in debug version caused the install to fail because `node-syslog.js` contains this line:

```
var SyslogWrapper = require('./build/Release/syslog');
```

The reason is in [configure.js](https://github.com/nodejs/node-gyp/blob/master/lib/configure.js) where the decision is made:

```
      console.log("setting defualt_configuration. gyp.opts = ", gyp.opts, " defaults =", defaults);
    if ('debug' in gyp.opts) {
        console.log("gyp.opts.debug = ", gyp.opts.debug);
        defaults.default_configuration = gyp.opts.debug ? 'Debug' : 'Release'
    }
    if (!defaults.default_configuration) {
        console.log("Using default value of release");
        defaults.default_configuration = 'Release'
    }
      console.log("defaults.default_configuration = ", defaults.default_configuration);
```

(Debugging log lines were added by me). This seems to want to make the default "Release" but this is not what happens. `defaults` is defined here:

```
    var config = process.config || {}
      , defaults = config.target_defaults
      , variables = config.variables
```

So it comes from `config.target_defaults` that comes from `process.config` which is [documented](https://nodejs.org/api/process.html#process_process_config) as:

*An Object containing the JavaScript representation of the configure options that were used to compile the current Node.js executable. This is the same as the "config.gypi" file that was produced when running the ./configure script.*

So the default ends up not as "Release" but whatever node was compiled with.

**Comment by bnoordhuis** [comment]
Defaulting to `process.config` doesn't strike me as unreasonable.  Most people that have debug builds installed will be core or add-on developers.

Also, /cc @sam-github - see the remark about strong-fork-syslog.

**Comment by TooTallNate** [comment]
This was the intended behavior when I originally set up node-gyp. Like Ben said, debug builds are mostly used by node core developers.

`strong-fork-syslog` could be fixed to work with either Release or Debug builds by using [`node-bindings`](https://github.com/TooTallNate/node-bindings) (sorry for the self-plug, but it gets the job done).

**Comment by rvagg** [comment]
+1 for @TooTallNate's suggestion, `var SyslogWrapper = require('./build/Release/syslog');` is now an anti-pattern in Node IMO, use `bindings` to avoid the magic. Perhaps you can file an issue upstream about this?

**Comment by bnoordhuis** [comment]
FTR, here is how I deal with it in my modules:

```javascript
try {
  var addon = require('./build/Release/addon.node');
} catch (e) {
  var addon = require('./build/Debug/addon.node');
}
```
