### ISSUE TITLE
infinite loop in node-gyp configure if an empty key is present in the .npmrc config file

### ISSUE THREAD

**Issue by jmorille** [nodejs/node-gyp#744]
if a new line is created with a space in the userconfig file /home/[user]/.npmrc
like the ticket open in npm https://github.com/npm/npm/issues/9756

that create an empty key with the values true
```shell
# npm config list
```

```shell
; userconfig /home/[user]/.npmrc
 = true
```

the command *node-gyp configure* create an infinite loop that eat all the cpu forever.

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node-gyp/pull/745 and https://codereview.chromium.org/1364373004/
