### ISSUE TITLE
node-gyp handles external file dependencies differently in npm install vs npm install <directory>

### ISSUE THREAD

**Issue by murgatroid99** [nodejs/node-gyp#752]
I have a node module that depends on a separate C library. So, I have a gyp file for that library (`library.gyp`) and a gyp file for the node module (`binding.gyp`). Some targets for the C library, such as tests, are not useful for the node module build, so the target in `binding.gyp` has a dependency on `library.gyp:library`.

When I run `npm install` in the package directory, it builds only my node module, `library.gyp:library`, and the transitive dependencies of that target. This is what I expect to happen.

However, if I go to a separate directory (`/tmp`) and run `npm install path/to/node/module`, it tries to build every target in `library.gyp`, and fails, because I did not include the test files in my `files` list in `package.json`.

**Comment by a0viedo** [comment]
hey @murgatroid99, it's been a long time since you opened this. is this still an issue?
