### ISSUE TITLE
Incorrect parsing of MAKE environment variable

### ISSUE THREAD

**Issue by vbraun** [nodejs/node-gyp#759]
I have set 

    MAKE='make -j16'

on my development box, this is the recommended way to enable makefile parallelism by default. Now node-gyp dies with
~~~~
gyp ERR! build error 
gyp ERR! stack Error: not found: make -j16
gyp ERR! stack     at F (/home/vbraun/.hashdist/bld/node/64ucaro72c57/lib/node_modules/npm/node_modules/which/which.js:40:28)
gyp ERR! stack     at E (/home/vbraun/.hashdist/bld/node/64ucaro72c57/lib/node_modules/npm/node_modules/which/which.js:43:29)
gyp ERR! stack     at /home/vbraun/.hashdist/bld/node/64ucaro72c57/lib/node_modules/npm/node_modules/which/which.js:54:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.1.7-200.fc22.x86_64
gyp ERR! command "node" "/home/vbraun/.hashdist/bld/node/64ucaro72c57/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vbraun/Talque/tools/talque/lib/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
~~~~
It is not valid to assume that `MAKE` is set to the name of an executable alone. I also don't see why node-gyp has to run which, it should just respect what I set for `MAKE`.

**Comment by bnoordhuis** [comment]
Any particular reason you don't set `MAKEFLAGS="-j16"`?  `MAKE="make -j16"` will break more than just gyp / node-gyp.

**Comment by jbergstroem** [comment]
What @bnoordhuis said. You're looking for `MAKEFLAGS=`, not `MAKE=`.

**Comment by vbraun** [comment]
Setting `MAKE` is the recommended way; `MAKEFLAGS` is implementation-dependent and meant for the communication between make instances. Autotools works just fine with `MAKE='make -jN'`.
* http://stackoverflow.com/questions/19611004/recursive-make-correct-way-to-insert-makeflags/19622824#19622824
* https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/The-Make-Macro-MAKEFLAGS.html#The-Make-Macro-MAKEFLAGS

**Comment by bnoordhuis** [comment]
Please read the pages you linked to carefully: it's about reading or changing `MAKEFLAGS` _inside_ a Makefile, which indeed you should not normally do.  It's perfectly fine for passing arguments to make from outside.

**Comment by vbraun** [comment]
The problem is that `MAKEFLAGS` is implementation depedent, it has nothing to do with when you set it. Yet posix requires make to look at it and pass it down to sub-makes.

Say you have gnu make and foo make installed. You can't `export MAKEFLAGS=--foo` in your .bashrc, this will break gnu make. Just like using a gnu extensions like `-jN` would break non-gnu make. 

Sure you can **in addition** set `MAKE` to the make that accepts the given `MAKEFLAGS` but thats not exactly convenient. Its much better to just set `MAKE` to begin with.

**Comment by bnoordhuis** [comment]
Both GNU make and BSD make support -j just fine but okay, if you're worried about breaking pmake, use `GNUMAKEFLAGS`.  GYP doesn't support non-GNU make anyway.

In case it wasn't clear, the fact that you can't put it in `MAKE` is a GYP limitation.  You'll have to live with it unless you want to put in the effort of getting a patch accepted upstream.  Don't get your hopes up though, they'll probably tell you the same thing we did: to use `MAKEFLAGS`.

I'll close the issue because there isn't much else to discuss but at least there's a bit of background and solutions now for people coming here from Google.
