### ISSUE TITLE
Support for non-ascii userprofile name on Windows

### ISSUE THREAD

**Issue by SvetlozarValchev** [nodejs/node-gyp#760]
This commit(https://github.com/nodejs/node-gyp/commit/39a06bc6092dad3130d349ddb573c666e745535c) seems to fix only some languages like Portuguese. It needs a more universal solution, as it currently does not work for cyrillic userprofile names. The system locale is modified through here 
![image](https://cloud.githubusercontent.com/assets/446056/10314358/0a8104ba-6c5d-11e5-86c6-eddf023d7fcf.png)
Almost every country has its own locale and adding them all in a try/except sequence will make for a very messy code. The code has to fetch the system locale and apply it to that snippet of code.

**Comment by rvagg** [comment]
something to take up with https://github.com/refack/GYP if this is still an issue I think
