### ISSUE TITLE
On Build: `unable to execute command: Executable "" doesn't exist!`

### ISSUE THREAD

**Issue by CWSpear** [nodejs/node-gyp#764]
When trying to build `pwuid`, I get an error: `unable to execute command: Executable "" doesn't exist!`

Seems to be something going on with `node-gyp` on my system as it's not easy to reproduce. We can't find anything on the `pwuid` side, so I'm opening a ticket here.

Please see details, including environment information and output in https://github.com/sindresorhus/pwuid/issues/3

**Comment by CWSpear** [comment]
One thought I had, is that in the README, it says to run `node-gyp --python /path/to/python2.7`, but when I do that, it just prints the help message. Is it possible that the executable it can't find is python and it has something to do with this?

**Comment by bnoordhuis** [comment]
That's almost certainly unrelated to node-gyp.  What you are experiencing is a variation on http://stackoverflow.com/questions/27494866/llvm-cannot-find-clang-binary.

**Comment by CWSpear** [comment]
Ok... that doesn't really mean anything to me. `node-gyp` can't find a binary, that much seems to make sense. But what binary? Why can't it find it? What happened between last week and this week to make it suddenly stop working? (I updated to Node `4.1.2` but can't think of anything else... I tried on versions that used to work and they still don't).

**Comment by bnoordhuis** [comment]
To be clear: it's not node-gyp that's complaining - it's clang, the compiler.  Consider reinstalling xcode, check that there's no conflicting homebrew package, etc.
