### ISSUE TITLE
Gyp not finding library files

### ISSUE THREAD

**Issue by fletchette** [nodejs/node-gyp#765]
My binding.gyp file looks something like
```javascript
{
	"targets": [
		{
			"target_name": "addon",
			"sources": [
				"hello.cpp"
			],
			"include_dirs": [
				"D:\sdk\redistributable_bin",
				"D:\sdk\public\steam"
			],
			"libraries": [
				"-lsteam_api"
			]
		}
	]
}
```

However the compiler won't find steam_api.lib (which is in D:\sdk\resdistributable_bin\steam_api.lib).

**Comment by bnoordhuis** [comment]
What happens when you use forward slashes or escape the backward slashes?

**Comment by fletchette** [comment]
Same error.

**Comment by bnoordhuis** [comment]
Okay.  I think you need to make at least the following change:

```
"link_settings": {
  "library_dirs": ["D:/sdk/redistributable_bin"],
  "libraries": ["-lsteam_api"],
}
```

**Comment by fletchette** [comment]
Ok, that fixed that issue. But now I'm getting unresolved external symbol errors.
[Pastebin](http://pastebin.com/DjXUixDQ)

**Comment by bnoordhuis** [comment]
I'm guessing you need to link in more libraries besides just steam_api.lib.

**Comment by fletchette** [comment]
Shouldn't be.
I'm porting over a project from VS 2013.
The only requirements from that are steam_api.dll and steam_api.lib.

**Comment by fletchette** [comment]
Fixed.
Compiling under vs studio it worked fine with the 32bit version of the library.
Under node-gyp it only accepted the 64bit.
