### ISSUE TITLE
Link libraries fail

### ISSUE THREAD

**Issue by kimtn-bitmark** [nodejs/node-gyp#767]
I got this error when i try to link external libraries for our project

```SOLINK_MODULE(target) Release/node_libtorrent_wrap_bindings.node
ld: library not found for -lboost_system```

Bellow is my config

in `binding.gyp`

```
"variables": {
    "boost_root%": "/path/to/libraries/"
  },
  'targets': [
     ...
     "link_settings": {
        "libraries": [
          "-lboost_system",
          "-lboost_thread",
          "-ltorrent-rasterbar",
        ],
        "ldflags": [
            "-L<@(boost_root)",
            "-Wl,-rpath,<@(boost_root)",
        ]
      },
     ...
  ]
```

I was checked `path/to/libraries` folder and found these files in that folder `libboost_filesystem.dylib`, `libboost_thread.dylib`

i'm using: OSX 10.10.5, node v0.12.7, node-gyp v2.0.2.

Someone else can help me resolve this error.
Thanks so much!

**Comment by bnoordhuis** [comment]
Can you post the output of `env V=1 node-gyp rebuild`?  I'd like to see what flags it's using at compile and link time.

**Comment by kimtn-bitmark** [comment]
Bellow are logs of `env V=1 node-gyp rebuild`

```
c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/node_libtorrent_wrap_bindings.node Release/obj.target/node_libtorrent_wrap_bindings/src/ffi.o Release/obj.target/node_libtorrent_wrap_bindings/src/callback_info.o Release/obj.target/node_libtorrent_wrap_bindings/src/threaded_callback_invokation.o Release/libffi.a -lboost_system -lboost_thread -ltorrent-rasterbar
ld: library not found for -lboost_system
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_libtorrent_wrap_bindings.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/thinhuockim/Documents/project/bitmark/libtorrent-nodewrap
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
Thanks.  What happens when you merge the 'ldflags' section into the 'libraries' section?  I don't think ldflags is a gyp directive on OS X due to its xcode emulation mode.

**Comment by kimtn-bitmark** [comment]
I dont' know why but i saw in statement that generated by node-gyp not include `-L` option when compile. i guess cause of error are be there.

**Comment by bnoordhuis** [comment]
Is it working for you with the changes I suggested?  If yes, can you close the issue?  Thanks.

**Comment by kimtn-bitmark** [comment]
I was merged, `ldflags` in to the `libraries` session but it's still does not work. But when i setting `LD_LIBRARY_PATH=path/to/libraries`, it's work probably. So i think problem are generate compiler command.
But anyway, you can close this issues.

Thanks for your support.
