### ISSUE TITLE
Stuck on node-gyp rebuild error on Ubuntu

### ISSUE THREAD

**Issue by Sukhrob** [nodejs/node-gyp#777]
![screen shot 2015-10-20 at 00 23 15](https://cloud.githubusercontent.com/assets/1179760/10588739/06a0111a-76c1-11e5-9db4-3fbe4327c7af.png)

**Comment by bnoordhuis** [comment]
Your version of node-gyp is pretty old.  What happens when you update it to the latest?

**Comment by Sukhrob** [comment]
![screen shot 2015-10-20 at 00 37 42](https://cloud.githubusercontent.com/assets/1179760/10589115/e703117a-76c2-11e5-9f1d-57820ffeffd3.png)

I am using "node@0.12.7" because "oracledb@1.3.0" requires node version to be ">=0.10.28 <3".

**Comment by Sukhrob** [comment]
![screen shot 2015-10-20 at 00 44 29](https://cloud.githubusercontent.com/assets/1179760/10589281/c3049dce-76c3-11e5-8a67-bb080718f774.png)

The same issue after updating node-gyp.

**Comment by bnoordhuis** [comment]
You're still using node-gyp v2.0.1 in that last screenshot.

**Comment by bnoordhuis** [comment]
No follow-up, closing.
