### ISSUE TITLE
Why do we need node-gyp in the first place? (Windows nightmare)

### ISSUE THREAD

**Issue by Ajar-Ajar** [nodejs/node-gyp#784]
I'm glad for you node-gyp works on your windows OS. 
It doesn't on mine and on others. It is a bloody nightmare!
It is Joynet who came up with node-gyp
Why would you let a web developer npm install a package that starts to compile c++ code?
It is a source for problems (hence the nightmare).
It is not acceptable to expect a web developer download almost 2 gigs of dependencies to be able to compile c++ code that they got nothing to do with.
When things blow up (and they do!) you are left without a clue and this is a VERY bad experience.
The alternative would be that the person who writes the library which needs compiled C++ code will compile it himself and supply the compile binaries in the npm installation. you should be able to detect the os and download the proper precompiled binaries along with the library.  

I followed closely your windows instructions and it is still does not work after a million attempts.
My case is not private. there are plenty of node web developers who work on windows and meet this nightmare every time a library has a node-gyp dependency.
You cannot assume that compiling c++ code will go smoothly. a web developer is not suppose to deal with this mess. 
Please consider to change this approach all together.
Thanks
Ajar

**Comment by bnoordhuis** [comment]
Sorry, I'm going to close this because there isn't anything actionable here.  As to your suggestion of precompiling add-ons, that's what [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) is for, but it requires action on the side of the module author.

**Comment by orangemocha** [comment]
@Ajar-Ajar I agree with your assessment. The good news is that we are working to ease this pain. I am pursuing https://github.com/nodejs/build/issues/151. Microsoft is also working on a smaller SKU for the compiler and SDK to eliminate the dependency on Visual Studio.

**Comment by Ajar-Ajar** [comment]
@orangemocha  thank you for treating this issue seriously and not just closing this issue like @bnoordhuis did. This issue is a fundamental flaw in a node developer experience. It wastes so much precious time on anything but developing with node, which is what we;re suppose to be busy with.
Sweeping it under the carpet will not make it go away... 
So I'm glad you are finally making a substantial step to solve this issue and I'm looking forward to be able to use all the libraries that depend on node-gyp on a windows machine.
Thank you.

**Comment by bnoordhuis** [comment]
@Ajar-Ajar If you wanted me to keep the issue open, you should come up with concrete steps for improvement instead of posting what is basically a rant.  No offense but save that for your blog, it doesn't belong here.

Please read [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) first next time you decide to file a bug report and please check the list of open issues first.  Everything @orangemocha told you is already public information.

**Comment by Ajar-Ajar** [comment]
@bnoordhuis this is an open issue that causes a big problem for many developers.
I wish I could contribute with some concrete steps to solve this but I know nothing of compilers & c++
My role as a user, a web developer is not to deal with c++ but to remind you that it is still a nightmare for many of us. and it is still an open issue until you'll come up with a fix. Do you want to write it off while "no offense"ing me - go ahead! 
it won't make it go away, but let's keep our eyes wide shut and get this issues list down to a minimum.

**Comment by bnoordhuis** [comment]
You conveniently skip over the part where I said that there were already open issues about the things you're griping about.  This issue doesn't add anything of value.

**Comment by Ajar-Ajar** [comment]
I understand. I didn't notice. sorry. Just wanted to make sure it's on your radar.
I apologize if I was too harsh. I just want it all to be behind us and move on to making great apps.
Thank you for putting in the time and effort. It is appreciated.
Ajar

**Comment by bnoordhuis** [comment]
No problem, happens to the best of us.
