### ISSUE TITLE
Native module fails to build on El Capitan.

### ISSUE THREAD

**Issue by octalmage** [nodejs/node-gyp#789]
Hey guys! 

I'm having a weird issue where my module [RobotJS](github.com/octalmage/robotjs) is failing to build on El Capitan, while the same code builds on Yosemite. As far as I can tell they have the same build tools, so I'm really curious where the issue is. You can see the build error here: 

https://github.com/octalmage/robotjs/issues/118

Whats different with the build process between Yosemite and El Capitan? We're using the same clang versions, same node-gyp, same Node.js, same nan, same npm, same everything. Is node-gyp doing something different here? 

Can anyone help me identify the issue? 

Thanks!

**Comment by bnoordhuis** [comment]
Looking at the bug report you linked to, it's almost certainly some incompatibility in the add-on and not a node-gyp issue.

**Comment by olalonde** [comment]
Same thing here: https://github.com/js-platform/node-webrtc/issues/235#issuecomment-152437490 though it's indeed probably an incompatibility issue and not node-gyp's fault.

**Comment by octalmage** [comment]
@bnoordhuis I agree, I'm just hoping to get some in sight as to what has changed. Like, with the same compiler version I'm getting errors in code that's not using nan, or any V8 APIs, just straight c++.

**Comment by octalmage** [comment]
I was able to solve the issue, I still don't know what changed though. I'll close this ticket.
