### ISSUE TITLE
error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by joshiparthin** [nodejs/node-gyp#791]
Tried to install npm install mongodb on windows 10. 

Python 27 path is given. VC++ 2013 option set. Still it gives node-gyp error: 

error MSB4019: The imported pro
ject "D:\Microsoft.Cpp.Default.props" was not found

Please help. Stuck since 2 days.

**Comment by bnoordhuis** [comment]
Can you post the full output?  That's everything starting from `npm install mongodb`.  Please include the contents of npm-debug.log as well.

**Comment by neoadventist** [comment]
@joshiparthin I got the same thing, solved it by running it in the visual studio 2013 console. Now i'm getting problems with it building.

**Comment by bnoordhuis** [comment]
Closing, OP never followed up.

**Comment by akontsevich** [comment]
Have same problem on Azure. Any thoughts how to solve? Related to https://github.com/JoshuaWise/integer/issues/2
