### ISSUE TITLE
Question about bundled gyp

### ISSUE THREAD

**Issue by zeroware** [nodejs/node-gyp#793]
Is it possible to choose between bundled and external version of gyp ?

I'm using nix on OSX (without XCode) and the bundled version require XCode to work.

**Comment by bnoordhuis** [comment]
And the external version doesn't?  gyp's xcode emulation mode was added years ago.  If your external copy doesn't have that it's probably too old to be used.  The answer is 'no' though, node-gyp is hard-coded to use the bundled gyp.

Maybe you can override the generator as a workaround?  Most of the xcode-specific logic is keyed on the 'mac' flavor so `node-gyp -f make-mac rebuild` would trigger it but `make-linux` would not.

**Comment by zeroware** [comment]
The external version is installed with `nix-env` and already patched to remove XCode checks.
Will check with make-linux. Thanks.

**Comment by bnoordhuis** [comment]
Seeing how you have a patched gyp, if specifying the flavor doesn't cut it, you can pass in the path to your custom generator:
```
$ node-gyp -f /path/to/yourgyp/pylib/gyp/generator/make.py rebuild
```

**Comment by bnoordhuis** [comment]
Closing, looks like this has run its course.
