### ISSUE TITLE
ld: library not found for -lgcc_s.10.5

### ISSUE THREAD

**Issue by emmanuel-ouanounou** [nodejs/node-gyp#794]
Hi,

I am trying to install node-gyp, and I have this error :

>npm WARN package.json myk@1.0.0 No repository field.
npm WARN package.json myk@1.0.0 No README data
npm WARN package.json myk@1.0.0 No license field.
npm WARN package.json Dependency 'gulp' exists in both dependencies and devDependencies, using 'gulp@^3.5.6' from dependencies
 
> contextify@0.1.14 install /Applications/XAMPP/xamppfiles/htdocs/MYKapp/MYK/ionic/MYK/node_modules/gulp-dom/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

> CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/contextify.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/XAMPP/xamppfiles/htdocs/MYKapp/MYK/ionic/MYK/node_modules/gulp-dom/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

>npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/XAMPP/xamppfiles/htdocs/MYKapp/MYK/ionic/MYK/npm-debug.log

**Comment by bnoordhuis** [comment]
I hope I don't come across as cross but did you search the bug tracker first?  There have literally been over 10 bugs filed about this one issue.

**Comment by emmanuel-ouanounou** [comment]
OK sorry, I found the answer here : https://github.com/nodejs/node-gyp/issues/792

Thank you, and sorry again.

**Comment by bnoordhuis** [comment]
No worries.  I'll close the issue.
