### ISSUE TITLE
Dependency on python being installed

### ISSUE THREAD

**Issue by stefaneg** [nodejs/node-gyp#796]
This is so wrong on many levels.

Publishing a package which cannot be installed because another toolchain (python) is not installed is always a very bad idea. Published packages should always be as immutable as possible, so depending on a local build as part of the installation of a package is, has always been, and will always be a bad idea in dependency management.

And because it is python, one first has to figure out whether it's 3+ or 2+. Of course, since I'm definitely not a python dev, and have on interest in having python installed on my machine, I am not up-to-date with the version incompatibility issues in python, and have no interest in wasting my time finding out. 

So please publish this package with python dependencies pre-built. It makes no sense to do otherwise.

Note that I'm filing this issue since react-router depends on this package, installing it is taking way too much time because of this python dependency.

**Comment by bnoordhuis** [comment]
Python 2.7 is a dependency and that's not going to change anytime soon, such is life.  Closing.

**Comment by stefaneg** [comment]
Can you give the reason why the published npm package is not published with what-ever-you build pre-built, so that those that depend on node-gyp do not get a transitive dependency on python 2.7 ? I'm kind of curious...

**Comment by bnoordhuis** [comment]
node-gyp is a thin wrapper around [GYP](https://en.wikipedia.org/wiki/GYP_%28software%29), which is a python project.  You need node-gyp to build modules that have native components.
