### ISSUE TITLE
Recompile native modules fails with nodejs not found

### ISSUE THREAD

**Issue by s-a** [nodejs/node-gyp#798]
I wonder why it tries to call ```nodejs``` instead of ```node```. Anybody an idea of what I am doing wrong here?

    > electron-recompile@2.0.0 dev c:\git\electron-recompile
    > node lib/index.js ../test/ --electron=0.34.2
    
    directory
    c:\git\test\
    recompiling native modules in c:\git\test\ processor: ia32 electron: 0.34.2 v8: 4.6.85.28
    scanning [ 'c:\\git\\test\\' ]
    found: c:\git\test\node_modules\fibers\binding.gyp
    compile fibers
    remove c:\git\electron-recompile\tmp\fibers@1.0.7
    npm.cmd [ 'install',
      '--prefix',
      'c:\\git\\electron-recompile\\tmp\\fibers@1.0.7',
      'fibers@1.0.7' ]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd c:\git\electron-recompile\tmp\fibers@1.0.7\node_modules\fibers
    gyp ERR! node -v v5.0.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    Build failed
    Der Befehl "nodejs" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.

**Comment by rvagg** [comment]
Looks like it's just the message that refers to "nodejs". I hate having to palm people off but it does look like this is either a problem with electron-recompile, or, more likely, fibers, and you should take it up there.
