### ISSUE TITLE
error: no such option: --no-parallel

### ISSUE THREAD

**Issue by maraoz** [nodejs/node-gyp#804]
I get this error every time I run node-gyp. Any ideas on how to fix it? 
I'm in version v3.0.3 which seems to be the latest

{ [Error: Command failed: /bin/sh -c /home/maraoz/git/bitcorps/node_modules/nodegit/node_modules/.bin/node-gyp rebuild
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/maraoz/git/bitcorps/node_modules/nodegit/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-51-generic
gyp ERR! command "/usr/local/bin/node" "/home/maraoz/git/bitcorps/node_modules/nodegit/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/maraoz/git/bitcorps/node_modules/nodegit
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by maraoz** [comment]
btw, I found a way around it, which is commenting this line: https://github.com/nodejs/node-gyp/blob/master/lib/configure.js#L326

But I wanted to notify you so you can fix it correctly :)

**Comment by bnoordhuis** [comment]
That error probably means node-gyp is picking up and old gyp version.  I've had similar reports from people that had gyp installed through their distro's package manager.

**Comment by cyphunk** [comment]
``gyp_main.py: error: no such option: --no-parallel`` is something that seems to come back and bug everyone. Is there a real solution to this? Is there a way to determine which node-gyp is causing the problem? (one installed from OS package, or from local npm, or other?)
