### ISSUE TITLE
new release of node-gyp

### ISSUE THREAD

**Issue by iWuzHere** [nodejs/node-gyp#805]
@rvagg @TooTallNate Would it be possible make a v3.0.4 release based on this https://github.com/nodejs/node-gyp/compare/f5d86eb...9049241
We would like to have these changes pulled into npm and ultimately node
For reference the original pull request https://github.com/nodejs/node-gyp/pull/781

**Comment by rvagg** [comment]
done, chose a cautionary semver-minor for it, so it's v3.1.0.
