### ISSUE TITLE
Need to find alternative to node-gyp!Failing million times for Windows x64 build npm install mongoose

### ISSUE THREAD

**Issue by Technologeek** [nodejs/node-gyp#806]
I have tried to uninstall/install almost all the possible versions of Visual Studio/Visual C++/Windows sdk almost 12GB's of data but nothing seems to be working with node-gyp.By the amount of time I have wasted with this installation I could have actually wrote couple of native apps with ember or ruby on rails.Why this problem is not permanently fix ?Also the actual documentation has very less help regarding the build errors .
![sss](https://cloud.githubusercontent.com/assets/3764685/11015819/5868c9a2-8593-11e5-8e6e-cfec6606059a.PNG)
Please fix this for me.

**Comment by Laucsen** [comment]
Yeah.

It is a bit annoying to have to install VS just for it. I use it on dependency chain of my projects and I always get this error.

**Comment by jmbarlow** [comment]
From the install instructions, the important bit is:

>
> All Windows Versions
>For 64-bit builds of node and native modules you will also need the Windows 7 64-bit SDK
>You may need to run one of the following commands if your build complains about WindowsSDKDir >not being set, and you are sure you have already installed the SDK:
>`call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x86`
>`call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x64`

**Comment by bnoordhuis** [comment]
Closing, has been answered.
