### ISSUE TITLE
node-gyp\4.2.2\include\node\v8.h(3264): error C2059: synta x error : ')'

### ISSUE THREAD

**Issue by mitselek** [nodejs/node-gyp#810]
just reporting

**Comment by bnoordhuis** [comment]
More context would help.  When do you get that error?  Please include output of any programs you run.

**Comment by mitselek** [comment]
Sorry, cant reproduce. This line flew by in winows console. I can't even tell exact command - I was really very-very pissed about all that windows crap. It was related to installing mmmagic and messing with different versions of Visual Studios.

**Comment by bnoordhuis** [comment]
Okay, no problem.  I'll close the issue.
