### ISSUE TITLE
Add builtin support for embedders of Node (electron/nw..)

### ISSUE THREAD

**Issue by noamokman** [nodejs/node-gyp#814]
Hi there!
My team and I worked on a product called  [native-builder](https://github.com/nachos/native-builder) :hammer: 
Which is essentially a tool to warp around node-gyp/nw-gyp/electron-rebuild and call the `rebuild` command with headers according to the platform you use.(It looks for the engines field in your package.json).

This could solve the problem of manually recompiling every native package in your dependency tree.

For example,
Your building a project running under [electron](http://electron.atom.io/).
Package `A` is a native package.
Package `B` is not a native package but it depends on package `A`.

When you install package `B` you need to know that it has a dependency on package 'A',
So something like this
``` bash
npm i
cd node_nodules/B/node_modules/A
HOME=~/.electron-gyp node-gyp rebuild --target 0.30.0 --dist-url=https://atom.io/download/atom-shell
```

To solve this problem we came up with native-builder that uses node-gyp and supports nw and electron.
However to [use it](https://github.com/nachos/native-builder#installation) you must:
*  Add this package as a dependency
``` bash
$ [sudo] npm install native-builder --save
```
* Add an install script
``` json 
{
  ...
  "scripts": {
    "install": "native-builder build"
  }
}
```

I discussed it in npm/npm#9822 and I want to add this functionality to node-gyp.

What do you think?

**Comment by bnoordhuis** [comment]
If the desired behavior can be achieved through a preinstall or install hook, then why would it need to be built into node-gyp?

**Comment by noamokman** [comment]
Because then you need to add this hook to all native packages. And all of the have a default hook to use node-gyp. This will add support for all packages, automatically.

**Comment by bnoordhuis** [comment]
What would have to change concretely in node-gyp?

> Because then you need to add this hook to all native packages.

Is your argument that you want it work transparently without manual intervention from module developers?  They still need to configure the "engines" field, don't they?

**Comment by noamokman** [comment]
Nope,  the engine field comes from the top most package.json.
Only the app developer will set that value.

**Comment by noamokman** [comment]
@paulcbetts and @rogerwang
Would love to know what you think.

**Comment by paulcbetts** [comment]
I'd actually rather patch `npm` so that I can place my own `node-gyp` executable at the beginning of `$PATH` (right now the bundled node-gyp's path always gets prepended to the path that npm uses). We don't need to patch node-gyp itself.

**Comment by paulcbetts** [comment]
@noamokman What's the use-case for being able to build packages for _either_ nw.js _or_ electron-rebuild? Wouldn't you just set up one or the other? I can't imagine people are building nw.js+electron apps, no?

**Comment by noamokman** [comment]
@paulcbetts The goal is that you wouldn't have to change your path.
This change is about abstracting that side of rebuild for different engines.
It is not necessarily about building for both of platforms, but rather make node-gyp build the packages to match the wanted engine.
Right now, the way to use nw-gyp/electron-rebuild is to find all your native sub dependencies and rebuild them.
That is a lot of work.
And during install, npm runs node-gyp anyway, for all native modules.
This is what I think we should do, make node-gyp compile the right way on the first time.
And then you don't need to traverse the dependency tree.

**Comment by paulcbetts** [comment]
Oh wait! I misread - you want to _add_ this to node-gyp directly. This would be :cool: - node-gyp should see that this is an electron project and build appropriately. 

However, I also think that patching this in npm would be the place to do it - specifically, I would submit a PR to https://github.com/npm/normalize-package-data so that instead of the default operation for binding.gyp-based node projects to be `node-gyp rebuild`, it should be the appropriate command for the platform.

**Comment by noamokman** [comment]
That's exactly where I started :sweat_smile: 
Check out my issue over at npm: npm/npm#9822
However @othiym23 said:
> I don't want to just add another layer of intermediation between users of npm and node-gyp, because that makes it tougher for us to keep things up to date for Node users (because now another stakeholder is involved when upgrades to node-gyp drop).

So here I am :smile:

**Comment by bnoordhuis** [comment]
@noamokman What would have to change concretely in node-gyp?

**Comment by omrilitov** [comment]
Hi everyone,
After looking into nw-gyp, it seems like we could actually avoid using nw-gyp and instead build nw native modules like electron does, by only switching the dist-url.
If we can achieve this, we could only patch node-gyp so it would recognize the engine and switch the dist-url accordingly, dropping the use of nw-gyp and electron-rebuild.

**Comment by paulcbetts** [comment]
@omrilitov This is the approach that I'm thinking, though I still think the appropriate place is normalize-package-data. @othiym23 probably would be more amenable to this change, since it's much less invasive (i.e. the sole change in behavior is to be slightly smarter about the default dist-url passed to `node-gyp`).

**Comment by TooTallNate** [comment]
Are electron / nw.js properly setting `process.relese` now? If they are then I would think that the dist URL defined there would be used implicitly.

**Comment by noamokman** [comment]
@TooTallNate actually, this doesn't help us because building the package is performed by the node process running npm.

**Comment by paulcbetts** [comment]
@TooTallNate We can definitely add this to Electron if it would help

**Comment by rogerwang** [comment]
In the next major version of NW.js (v0.13), users will be able to use `node-gyp --disturl` to build the native module. This will replace `nw-gyp`. However, we still need a way to build native modules that depends on other native modules...

**Comment by omrilitov** [comment]
@rogerwang That's great!
If we patch it into node-gyp as we said, every native-module will be get built the correct way directly from the npm install, which will handle all the sub dependencies as well.

**Comment by othiym23** [comment]
The way that `normalize-package-data` is responsible for figuring out how to invoke `node-gyp` is exceedingly weird – especially if logic starts being added that's specific to the platform invoking npm / `node-gyp`, and longer-term the whole `normalize-package-data` / `read-package-json` / `read-installed` / `read-package-tree` relationship probably needs to be reassessed. For now, it's probably appropriate to start a PR thread on `normalize-package-data` so we can work through just how disruptive the change is likely to be.

Just as an FYI, because the team has its hands full, we're unlikely to be in a position to land new PRs, especially complex ones, for a month or two, so patience is advised.

**Comment by Mithgol** [comment]
@TooTallNate

> Are electron / nw.js properly setting `process.release` now? If they are then I would think that the dist URL defined there would be used implicitly.

I've got an impression that `npm install` (and subsequently `node-gyp`) runs on regular Node.js engine even when the module is installed for NW.js.

Therefore internal `process.release` setting of NW.js affects scripts that run in NW.js (GUI) windowed environment but won't affect `node-gyp` that runs in CLI.

**Comment by xdvarpunen** [comment]
Is there possibility to use local path instead of --dist-url?

**Comment by Mithgol** [comment]
NW.js version 0.13 [supports](https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ) binary modules built by node-gyp for Node.js on Linux amd on Mac OS X.

However, on Windows a different version of `node-gyp\src\win_delay_load_hook.c` is required.

**Comment by bnoordhuis** [comment]
@xdvarpunen You can pass `--nodedir /path/to/sources`.

I'm going to close the issue; it seems to have stalled and I'm not even sure anything needs to change in node-gyp.  No pull requests were opened at any rate.
