### ISSUE TITLE
New release ? 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-gyp#816]
@rvagg @TooTallNate wondering what the regular cadence for releases is ?

**Comment by Fishrock123** [comment]
@mhdawson whenever we need one.

**Comment by Fishrock123** [comment]
It'l also take 1-2 weeks to get into npm since they have a 1-week test delay and alternate weeks between dep upgrades and features.

**Comment by bnoordhuis** [comment]
@Fishrock123 Can you add me as a publisher and remove Isaac?  I'm not sure why he has publish rights, I think he has one commit in total.

**Comment by Fishrock123** [comment]
Isaacs has [a bunch of commits](https://github.com/nodejs/node-gyp/commits/master?author=isaacs) and a couple releases, so I'm not going to remove him.

@bnoordhuis you should have publish access now.

**Comment by bnoordhuis** [comment]
I was looking at the long tail of `git shortlog -ns` where he only shows up once as "Isaac Z. Schlueter".  Looks like he normally commits as "isaacs".

**Comment by bnoordhuis** [comment]
On second thought: I don't think it's a bad idea to remove people that are inactive.  Every account with publish rights is a potential attack vector.

**Comment by mhdawson** [comment]
Ok I'd like to request we do one then.  The changes to add AIX support have landed and getting this into an external release that people get when the npm install node-gyp would be great. I'd also like to get cycle of having it pulled in npm start.

**Comment by bnoordhuis** [comment]
Published v3.2.0 (commit 328d671.)

/cc @othiym23

**Comment by othiym23** [comment]
Thanks for the heads up! Barring any issues, this should land in `npm@2.14.13` and `npm@3.5.1`.
