### ISSUE TITLE
Possibility of updating compiler to not use g++ command if the compiler is not C++-14 compatiable?

### ISSUE THREAD

**Issue by Gum-Joe** [nodejs/node-gyp#822]
When I compile my C++ bindings for my nodejs web-app, I receive the following error:
```
gypmake: Entering directory '/home/pi/Desktop/Programming/Web-OS/build'
 info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/mkdir/src/mkdir_linux.o
In file included from /home/pi/.node-gyp/4.1.2/src/node.h:42:0,
                 from ../src/mkdir_linux.cc:1:
/home/pi/.node-gyp/4.1.2/deps/v8/include/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.1.2/deps/v8/include/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.1.2/deps/v8/include/v8.h:852:1: error: expected unqualified-id before ‘using’
mkdir.target.mk:84: recipe for target 'Release/obj.target/mkdir/src/mkdir_linux.o' failed
make: *** [Release/obj.target/mkdir/src/mkdir_linux.o] Error 1
make: Leaving directory '/home/pi/Desktop/Programming/Web-OS/build'
```
However, this is not because of issue with nodejs. I submitted an issue on the nodejs repo (nodejs/node#3824), but they said it was invalid. Furthermore, they said I needed a C++-14 compiler, so I installed a C++-14 compiler (g++ 4.8.2), removed the old one (g++ 4.6.3) and aliased g++ to g++-4.8.  I then found I could no longer compile the bindings, with node-gyp telling me that the command `g++` was not found. This problem exists not just on my machine, but on others to, such as ci service travis-ci, thus meaning people can't test nodejs apps with C++ bindings when the default compiler, under the g++ command, is not a C++-14 compiler.

<u>My recommendation:</u> allow the setting of a NODE_CXX enviroment variable, which node-gyp could tell gyp to use if it can (I am no expert on gyp).

<u>Specs:</u>
* OS: Linux (Debian + Ubuntu (ci service only)) 
* Version: Linux 4.1.7-v7+
* Machine: Raspberry pi 2 (ARM)
* Ci worker: Ubuntu worker
* Ci Version: Linux 3.13.0-40-generic
* Nodejs version: 4.2.2
* Node-gyp version: 2.0.2
* Ci node-gyp version: 3.0.3

Hope you fix it!
Thanks in advance!

**Comment by TooTallNate** [comment]
`CXX` is the env variable you're looking for I believe.

**Comment by bnoordhuis** [comment]
`CXX` or `CXX.target` + `CXX.host`.  The host/target combo is probably only relevant when you're cross-compiling somehow.

**Comment by Gum-Joe** [comment]
Thank you @TooTallNate and @bnoordhuis, turns out I needed to set the environment variable `CXX` (assumed the Makefile would override it and listen to the aliases) but one question - what do I do on my ci (where the `sudo` command is unavailable), or when the software is distributed?

**Comment by TooTallNate** [comment]
Your CI host should have a preferred way to install additional packages, so that you can install a compatible compiler. As far as when your software is distributed, it's up to the user that is installing/compiling to have a proper toochain set up on their machine.

**Comment by Gum-Joe** [comment]
Ok, will open separate issue on travis-ci to have g++-4.8 pre-installed.
Thanks for all the help!

**Comment by TooTallNate** [comment]
No need. Just do this! https://github.com/nodejs/nan/blob/3f3fc0c2f352d6bcfd7cdef481203565c716a651/.travis.yml#L6-L11
