### ISSUE TITLE
warning C4005: WIN32_LEAN_AND_MEAN macro redefinition in win_delay_load_hook.c

### ISSUE THREAD

**Issue by pvenkatraman** [nodejs/node-gyp#823]
WIN32_LEAN_AND_MEAN macro is defined unconditionally.  The binding.gyp has this macro defined, in which builds on Windows report a warning.  It would be nice to include on if not already defined as follows:

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif 

Thanks

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node-gyp/pull/824
