### ISSUE TITLE
[feature request] Please implement an option preventing node-gyp from connecting anywhere

### ISSUE THREAD

**Issue by yurivict** [nodejs/node-gyp#828]
Once 'npm install --ignore-scripts' is run, it isn't necessary to connect to npmjs.org during 'npm rebuild'. Such option in npm.config would be great.

**Comment by bnoordhuis** [comment]
I'm not sure I understand.  node-gyp doesn't connect to npmjs.org, it only downloads from nodejs.org and only when `--nodedir` isn't set.

**Comment by yurivict** [comment]
Ok, thanks.
