### ISSUE TITLE
specify CXX via npm config?

### ISSUE THREAD

**Issue by Mischi** [nodejs/node-gyp#834]
Hi all,

can i somehow specify CXX via npm config? I know i could set the CXX env variable but i don't want to do this every time i run npm install. I probably could create an alias but it would be nice if i could place it next to the python config setting in my npmrc.

Example:
```shell
npm config python /usr/local/bin/python2.7
npm config CXX /usr/local/bin/eg++
```

Best Regards,
Fabian

**Comment by bnoordhuis** [comment]
I don't believe you can but https://github.com/npm/npm/issues is a better place to ask if you want to know for sure.

You can of course add them to your .bashrc, then they will always be set.

**Comment by Mischi** [comment]
If possible, i want to avoid setting CXX in my .kshrc :smile: as i only want to make it the default for npm. 
I will move this issue over to https://github.com/npm/npm/issues as you suggested.

Thanks for your quick response!

Regards,
Fabian
