### ISSUE TITLE
node-gyp binding file not found! image provided

### ISSUE THREAD

**Issue by uaedronemaster** [nodejs/node-gyp#839]
Hey guys!!
i need real help on this ive been at it for days!
![capture](https://cloud.githubusercontent.com/assets/16239818/11714755/d5b4713c-9f55-11e5-9e8c-c9240620884f.PNG)

**Comment by bnoordhuis** [comment]
What are you trying to do?  node-gyp is for building native modules but I doubt you have one installed in `C:\`.

**Comment by uaedronemaster** [comment]
I want to install node-oculus , the link is
https://www.npmjs.com/package/node-oculus .
But I need node-gyp for that. I am a beginner so can you tell me what is my
problem now?

Thank you

**Comment by bnoordhuis** [comment]
What happens when you run `npm install node-oculus`?

**Comment by uaedronemaster** [comment]
[image: Inline image 1]

**Comment by uaedronemaster** [comment]
![capt1111ure](https://cloud.githubusercontent.com/assets/16239818/11717373/9aca2e68-9f69-11e5-8c8c-d1c705359835.PNG)

**Comment by bnoordhuis** [comment]
It looks like you're missing Visual Studio.  Can you follow the instructions from the README and report the outcome?

**Comment by uaedronemaster** [comment]
but i have visual studio installed and i have followed the instructions

**Comment by uaedronemaster** [comment]
![capt1231ure](https://cloud.githubusercontent.com/assets/16239818/11718108/d7911204-9f6d-11e5-8ae4-fa43ce51e47a.PNG)

**Comment by uaedronemaster** [comment]
it seems like i have a msbuild problem

**Comment by bnoordhuis** [comment]
VS ships with a vcvaralls.bat script that sets up the environment.  You may have to run manually.

**Comment by uaedronemaster** [comment]
i dont understand what u mean.. i am not able to build it using msbuild ..
it is configuring now but not building

**Comment by saper** [comment]
Is this Visual Studio 2015? 

Toolset 12.0 is actually Visual Studio 2013, you should have it if all VS2015 components are installed.

**Comment by bnoordhuis** [comment]
Closing, see also #841 by the same author.
