### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by cannjeff** [nodejs/node-gyp#84]
I'm running into the following error when running npm install with the latest version of node (v0.6.19)

info it worked if it ends with ok
qs@0.5.0 ./node_modules/express/node_modules/connect/node_modules/qs
info downloading: http://nodejs.org/dist/v0.6.19/node-v0.6.19.tar.gz
ERR! Error: incorrect header check
   at Zlib.onerror (zlib.js:293:17)
ERR! not ok

npm ERR! weak@0.2.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the weak@0.2.1 install script.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "update"
npm ERR! cwd /Users/jcann/Documents/workspace/fly_swatter
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.24
npm ERR! code ELIFECYCLE
npm ERR! message weak@0.2.1 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jcann/Documents/workspace/fly_swatter/npm-debug.log
npm not ok
npm not ok

Setup:
Python 2.7.3
Mac OSX Lion 10.7.4
Node v0.6.19
Npm 1.1.24

**Comment by javefang** [comment]
our build server is behind a firewall and don't have internet access. the solution we use is to host the node header files internally (e.g. http://<server>:<port>/nodejs/dist/<node_version>), then pre-install these headers by calling 

$ node-gyp install --disturl=http://<server>:<port>/nodejs/dist

In this case "node-gyp rebuild" shouldn't try to download headers from nodejs.org again.
