### ISSUE TITLE
binding.gyp not found - Node-canvas

### ISSUE THREAD

**Issue by JerryFox1** [nodejs/node-gyp#840]
Trying to install node-canvas via npm install canvas but get missing file error 
Having issues both on OSX and a linux aws instance. Any help?

<img width="756" alt="screen shot 2015-12-10 at 11 15 34 am" src="https://cloud.githubusercontent.com/assets/2533361/11725635/83f5fc9c-9f2f-11e5-8c71-f521ad40f2ea.png">

Manually doing it:

```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/opt/node/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jerry/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.2.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/node/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jerry',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/jerry) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/node/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/opt/node/bin/node" "/opt/node/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jerry
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by TooTallNate** [comment]
You say you're trying to install canvas via `npm install canvas`, however in your screenshot and log dump above, you seem to be running `node-gyp rebuild`. That later step should not be necessary, a simple `npm install canvas` should do the trick, and after that you should be able to `require('canvas')` in your code.

**Comment by ralphtheninja** [comment]
@JerryFox1 ISTM that you are running this as `root` or `HOME` env var is pointing to `/root`

**Comment by JerryFox1** [comment]
@TooTallNate yeah that part wasn't included. 
Here is the npm install canvas issue 

 npm install canvas
npm WARN package.json cthulhu@1.0.0 No README data
-
> canvas@1.3.5 install /Users/jerry/cthulhu/node_modules/canvas
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jerry/cthulhu/node_modules/canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jerry/cthulhu/npm-debug.log

**Comment by JerryFox1** [comment]
@ralphtheninja yes but why would that be an issue?

**Comment by TooTallNate** [comment]
```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

^ that's the error you want to be focusing on. Something is up with your compilation toolchain.

**Comment by JerryFox1** [comment]
@TooTallNate okay thanks, this seems like a missing package?

**Comment by ralphtheninja** [comment]
> @ralphtheninja yes but why would that be an issue?

Can you do `npm i canvas --verbose` and put that output in a gist? Also, what does `env | grep HOME` show?

**Comment by JerryFox1** [comment]
npm i canvas --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'i', 'canvas', '--verbose' ]
npm info using npm@2.5.1
npm info using node@v0.12.0
npm WARN package.json cthulhu@1.0.0 No README data
npm verb cache add spec canvas@1.3.5
npm verb addNamed canvas@1.3.5
npm verb addNameVersion registry:https://registry.npmjs.org/canvas not in flight; fetching
npm verb request uri https://registry.npmjs.org/canvas
npm verb request no auth needed
npm info attempt registry request try #1 at 11:47:39 AM
npm verb request id 7586a861ea93d1b2
npm verb etag "8WQWKD0I5VJ2X5QDDT1WTIIZX"
npm http request GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm verb etag https://registry.npmjs.org/canvas from cache
npm verb get saving canvas to /Users/jerry/.npm/registry.npmjs.org/canvas/.cache.json
npm verb afterAdd /Users/jerry/.npm/canvas/1.3.5/package/package.json not in flight; writing
npm verb afterAdd /Users/jerry/.npm/canvas/1.3.5/package/package.json written
npm info install canvas@1.3.5 into /Users/jerry/cthulhu
npm info installOne canvas@1.3.5
npm verb installOne of canvas to /Users/jerry/cthulhu not in flight; installing
npm verb lock using /Users/jerry/.npm/_locks/canvas-418b578dcbaec6a9.lock for /Users/jerry/cthulhu/node_modules/canvas
npm verb unbuild node_modules/canvas
npm verb gentlyRm vacuuming /Users/jerry/cthulhu/node_modules/canvas
npm verb tar unpack /Users/jerry/.npm/canvas/1.3.5/package.tgz
npm verb tar unpacking to /Users/jerry/cthulhu/node_modules/canvas
npm verb gentlyRm vacuuming /Users/jerry/cthulhu/node_modules/canvas
npm info preinstall canvas@1.3.5
npm verb about to build /Users/jerry/cthulhu/node_modules/canvas
npm info build /Users/jerry/cthulhu/node_modules/canvas
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/Users/jerry/cthulhu/node_modules' ]
npm info linkStuff canvas@1.3.5
npm verb linkBins canvas@1.3.5
npm verb linkMans canvas@1.3.5
npm verb rebuildBundles canvas@1.3.5
npm info install canvas@1.3.5

> canvas@1.3.5 install /Users/jerry/cthulhu/node_modules/canvas
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.12.0
gyp verb command install [ 'v0.12.0' ]
gyp verb install input version string "v0.12.0"
gyp verb install installing version: 0.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.12.0
gyp verb build dir attempting to create "build" dir: /Users/jerry/cthulhu/node_modules/canvas/build
gyp verb build dir "build" dir needed to be created? /Users/jerry/cthulhu/node_modules/canvas/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/jerry/cthulhu/node_modules/canvas/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/jerry/cthulhu/node_modules/canvas/config.gypi
gyp verb common.gypi checking for gypi file: /Users/jerry/cthulhu/node_modules/canvas/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jerry/cthulhu/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jerry/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jerry/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/Users/jerry/cthulhu/node_modules/canvas',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/jerry/.node-gyp/0.12.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  ./gyp-mac-tool flock ./Release/linker.lock c++ -bundle -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/canvas-postbuild.node  -undefined dynamic_lookup
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jerry/cthulhu/node_modules/canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info canvas@1.3.5 Failed to exec install script
npm verb unlock done using /Users/jerry/.npm/_locks/canvas-418b578dcbaec6a9.lock for /Users/jerry/cthulhu/node_modules/canvas
npm verb stack Error: canvas@1.3.5 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1008:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
npm verb pkgid canvas@1.3.5
npm verb cwd /Users/jerry/cthulhu/libpng-1.5.18
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "canvas" "--verbose"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/canvas
npm info preuninstall canvas@1.3.5
npm info uninstall canvas@1.3.5
npm verb unbuild rmStuff canvas@1.3.5 from /Users/jerry/cthulhu/node_modules
npm info postuninstall canvas@1.3.5
npm verb gentlyRm vacuuming /Users/jerry/cthulhu/node_modules/canvas

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jerry/cthulhu/libpng-1.5.18/npm-debug.log

**Comment by ralphtheninja** [comment]
@JerryFox1 I noticed you switched node version in the middle but seems you have the same problem. This seems to be related to `clang` as @TooTallNate suggested. Upgrade your xcode? See https://github.com/TooTallNate/node-lame/issues/59

**Comment by JerryFox1** [comment]
I just noticed one issue seem to be the set up from https://github.com/Automattic/node-canvas/wiki/Installation---Amazon-Linux-AMI-%28EC2%29#pixman
has outdated links. Will try to reinstall and try again, thanks for the help!

**Comment by ralphtheninja** [comment]
> I just noticed one issue seem to be the set up from https://github.com/Automattic/node-canvas/wiki/Installation---Amazon-Linux-AMI-%28EC2%29#pixman
> has outdated links. Will try to reinstall and try again, thanks for the help!

:+1: Np :)

**Comment by bnoordhuis** [comment]
Closing, I assume it's working now.

**Comment by niftylettuce** [comment]
Your solution does not work, this is still broken.

**Comment by bnoordhuis** [comment]
Unhelpful comment.  Try explaining what doesn't work for you and what you've tried so far.
