### ISSUE TITLE
node-gyp does not honor npm's cafile config

### ISSUE THREAD

**Issue by mschnee** [nodejs/node-gyp#843]
See this persistent issue: https://github.com/nodejs/node/issues/3742

**Comment by bnoordhuis** [comment]
Fixed in 8c4b0ffa503aa385f4186e028542dcedca2efeee which was released in v3.3.0 in February.  Node.js v4.4.3 and v5.10.0 were the first releases to carry that version.

**Comment by coke** [comment]
If it's a command line option, then it's not going to work for multiple developers on the same project with different configs. Can we get it to respect an environment variable and/or npm's config where it's already set?

**Comment by bnoordhuis** [comment]
@coke That's been the case since day one, see the linked commit log.

**Comment by gibfahn** [comment]
For posterity/people who don't want to click the link:

```bash
export npm_config_cafile=/path/to/ca.crt
```

**Comment by coke** [comment]
*sigh*. I swear I tried that env var last night; in the harsh light of the morning, It works fine.

Thank you very much for your patient reply.

**Comment by light24bulbs** [comment]
Extremely odd to have a lower case env var like that

**Comment by gibfahn** [comment]
>Extremely odd to have a lower case env var like that

You can also do:

```bash
export NPM_CONFIG_CAFILE=/path/to/ca.crt
```
