### ISSUE TITLE
Sample desired for configuring debug settings for generated project

### ISSUE THREAD

**Issue by heaths** [nodejs/node-gyp#846]
Building a native addon, I find myself frequently configuring the debug settings. It would be great if I could configuring binding.gyp to do this. Looking at the source for gyp itself, it seems there's a way to do this but I haven't gotten it quite working yet. A node-specific example would be great, such that I could configure my action to debug via mocha, something like this (haven't gotten it to work, but seems to be the right syntax according to their python source):

``` json
"run_as": {
  "action": [ "node", "node_modules/mocha/bin/_mocha", "-d", "-R", "spec" ],
  "working_directory": ".."
}
```

Or if "node-gyp configure" would do this automatically, that would be great, too. Granted, you couldn't know what test runner we ultimately end up executing, but maybe the program to run (node) and working directory (module root) could be configured.

**Comment by bnoordhuis** [comment]
I'm not entirely sure what you mean with 'debug settings'.  Do you mean the `--debug` command line switch that builds an add-on with DWARF debug info and optimizations disabled?

**Comment by heaths** [comment]
When you debug in VS after opening the generated .sln (or .vcxproj), via F5 (depending on key bindings). It would be great if this could be pre-configured in the generated .vcxproj to avoid having to do this after every time I run `configure`.

**Comment by bnoordhuis** [comment]
I don't use VS but doesn't passing `--debug` to `configure` cover what you're looking for?

**Comment by heaths** [comment]
Just tried it, and it does not. The debug settings I'm talking about are such that I hit F5 and it will automatically launch node and step through my code.

**Comment by bnoordhuis** [comment]
It's possible gyp has native support for that but if it does, I don't know about it.  If you can make it work, we can look into supporting or documenting it in node-gyp.
