### ISSUE TITLE
node-gyp configure error

### ISSUE THREAD

**Issue by tongao** [nodejs/node-gyp#847]
node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.4 | linux | x64
gyp info spawn /bin/python2
gyp info spawn args [ '/usr/local/src/node-v4.2.4-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/whtest/node/works/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/node-v4.2.4-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.2.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/src/node-v4.2.4-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/whtest/node/works',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/whtest/node/works) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/src/node-v4.2.4-linux-x64/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "/usr/local/src/node-v4.2.4-linux-x64/bin/node" "/usr/local/src/node-v4.2.4-linux-x64/bin/node-gyp" "configure"
gyp ERR! cwd /home/whtest/node/works
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
> gyp: binding.gyp not found (cwd: /home/whtest/node/works) while trying to load binding.gyp

Not sure what you're trying to do but you need to have a binding.gyp file in that directory that tells node-gyp how to build your project.  I'm going to close this, not a node-gyp bug; you can a binding.gyp primer in the README.
