### ISSUE TITLE
node-gyp rebuild ECONNREFUSED

### ISSUE THREAD

**Issue by konradjurk** [nodejs/node-gyp#860]
I am trying to build my docker image an it fails all the time during node-gyp rebuild. It worked *yesterday*!

I am running on Mac OS in a boot2docker vm.

This is the error message and according to the SSL certificate 104.20.23.46 seems to be one of bitbuckets mirrors. How can I fix this?

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:856:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:879:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
gyp ERR! System Linux 4.1.12-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /madam/node_modules/bcrypt
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by konradjurk** [comment]
Hm seems to be a docker/boot2docker dns problem. The solution is to restart the docker vm, but in this case I had to do it 20 times. Suddenly, it worked. The next build failed again with the same error. Very strage

**Comment by RishabhRJain** [comment]
Hi,
Did you find any other consistent solution ?
