### ISSUE TITLE
pls help me ,i want to get cef3 as a vs2013 vcxproject .i am not very clear with the command "gyp",

### ISSUE THREAD

**Issue by enderwsp** [nodejs/node-gyp#863]
i have installed python2.7 successfully,and also have installed gyp Runtime environment without no problem by the commad 'python setup.py install'.now i try to execute 'gyp --depth=. cefclient.gyp' for a visual studio 2013 c++ project of cef3.whatever the executed GYP command is ,the vs2013 project always builds failedly.
so i got stucked ,pls give me a hand ,even just a different and small step,i will appriciate very much
1,install python2.7
2,install gyp
3,gyp cef3 for a vs2013 vcxproject
4,build the vs2013 vcxproject
my english is just so so

**Comment by bnoordhuis** [comment]
I'm going to close this; it looks like you're using gyp, not node-gyp; they're separate projects.
