### ISSUE TITLE
Windows install / VS / C++ / compiling anything dependent on node-gyp

### ISSUE THREAD

**Issue by ganna-shmatova** [nodejs/node-gyp#864]
I've been at this for about 2 weeks now. It worked ONCE and then I tried installing something that uses it in a different project and it stopped working in that project and the project it used to work in & that was 4 days ago.

I've tried VS 2015, I've tried the c++ tools preview with various SDK configurations, I've even reinstalled node.js, and ccleaned system all throughout.

Then I went back to VS studio. Installed VS studio 2013:

1. 
```
npm config set msvs_version 2013 --global
```
= It still thinking we're dealing with 2015
![image](https://cloud.githubusercontent.com/assets/7226694/12332857/e40df04e-babe-11e5-9282-c23b7a2d1a2a.png)

2.
```
npm i --msvs_version2013
```
Just whole mess of issues:
![image](https://cloud.githubusercontent.com/assets/7226694/12332884/0926542a-babf-11e5-9391-28e03b378af3.png)

---

tried to install the suggested
> If you get errors that the 64-bit compilers are not installed you may also need the compiler update for the Windows SDK 7.1

But it told me I didnt have Windows SDK installed. Which isn't riiiiiiigghhhttt...

Downloaded and tried to install Windows 7.1 SDK (https://www.microsoft.com/en-ca/download/details.aspx?id=8279), but it told me it failed and to look at some config.html file...

And now I have 20-something new programs in programs and features despite telling VS 2013 to ONLY install the SDK and not SQL features that I'm seeing right now... What...?!

---

With the SDK preview the issues were files stddef.h and stdio.h -- considering it's a 'preview' and occassionally it would blow up installing SDK 10 I decided to stop exploring that route. I've uninstalled the individual components between each install. My window ssystem si full updated & is windows 7. It's also a fairly new install and I hope I haven't botched it trying these install and uninstall cycles.

**Comment by ganna-shmatova** [comment]
nvm.,.. modules were out of date...

**Comment by abc-z** [comment]
This is my method for Windows x86 platform 

Download and install
* .Net 4.5.2 (or higher) http://www.microsoft.com/en-us/download/details.aspx?id=42642
* MS Build Tools 2013 (or highter) http://www.microsoft.com/en-us/download/details.aspx?id=40760
* JRE (maybe)
 
And run in console
* npm config set msvs_version 2013 -g
* npm i node-pre-gyp -g
* node-gyp rebuild --msvs_version=2013
