### ISSUE TITLE
Issue while installing node-oracledb : The script Failed at node-gyp rebuild

### ISSUE THREAD

**Issue by sohilvshah** [nodejs/node-gyp#870]
Hi,

I am facing issue while installing node oracle driver on my machine.
The script somewhere calls node-gyp rebuild and it fails.

Here are the environment details -
Visual Studio - Community version with update 5
Python - 2.7.10
Node - 4.2.4 (64 bit)
Oracle Client - 12.1.0.2.0 (64 bit)
System - Windows 7

Here is the log on console -

TRACKER : error TRK0002: Failed to execute command: ""C:\Program Files (x86)\Mi
crosoft Visual Studio 12.0\VC\bin\amd64\CL.exe" @C:\Users\shahsv\AppData\Local\
Temp\tmp905df070b22245508a85dfe54e2da789.rsp". The parameter is incorrect. [C:\
Users\shahsv\Desktop\node app\node_modules\oracledb\build\oracledb.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe fail
ed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack at emitTwo (events.js:87:13)
gyp ERR! stack at ChildProcess.emit (events.js:172:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\shahsv\Desktop\node app\node_modules\oracledb
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "oracledb"
npm ERR! node v4.2.4
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.5.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\shahsv\Desktop\node app\npm-debug.log

Also, here is the debug log -

408 info oracledb@1.5.0 Failed to exec install script
409 verbose unlock done using C:\Users\shahsv\AppData\Roaming\npm-cache_locks\oracledb-da25b9573ba09cd6.lock for C:\Users\shahsv\Desktop\node app\node_modules\oracledb
410 verbose stack Error: oracledb@1.5.0 install: node-gyp rebuild
410 verbose stack Exit status 1
410 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
410 verbose stack at emitTwo (events.js:87:13)
410 verbose stack at EventEmitter.emit (events.js:172:7)
410 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
410 verbose stack at emitTwo (events.js:87:13)
410 verbose stack at ChildProcess.emit (events.js:172:7)
410 verbose stack at maybeClose (internal/child_process.js:818:16)
410 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
411 verbose pkgid oracledb@1.5.0
412 verbose cwd C:\Users\shahsv\Desktop\node app
413 error Windows_NT 6.1.7601
414 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "oracledb"
415 error node v4.2.4
416 error npm v2.14.12
417 error code ELIFECYCLE
418 error oracledb@1.5.0 install: node-gyp rebuild
418 error Exit status 1
419 error Failed at the oracledb@1.5.0 install script 'node-gyp rebuild'.
419 error This is most likely a problem with the oracledb package,

Anyone experienced the same problem? Any resolution to it?

**Comment by bchr02** [comment]
This usually happens when you are missing the OCI_LIB_DIR and OCI_INC_DIR environment variables. [instructions here under section IV. Set Environment Variables](https://community.oracle.com/docs/DOC-931127)

**Comment by bnoordhuis** [comment]
Closing, almost certainly not an issue with node-gyp.
