### ISSUE TITLE
node-gyp configure - issue on Windows

### ISSUE THREAD

**Issue by rgiles18** [nodejs/node-gyp#871]
I was able to run: "npm install -g node-gyp" without issue.

What did I not do?

C:\edge>node-gyp configure -g
Node Commands

Syntax:
    node {operator} [options] [arguments]

Parameters:
        /? or /help   - Display this help message.
        list          - List nodes or node history or the cluster
        listcores     - List cores on the cluster
        view          - View properties of a node
        online        - Set nodes or node to online state
        offline       - Set one or more nodes to the offline state

For more information about HPC command-line tools,
see http://go.microsoft.com/fwlink/?LinkId=120724.

**Comment by bnoordhuis** [comment]
Make sure `node.exe` (i.e. the node.js binary) comes before the HPC tools on your PATH.  If you're not using the HPC tools, it may be better to uninstall them to avoid further conflicts.

**Comment by bnoordhuis** [comment]
I'll go ahead and assume it's working for you now.  Closing.
