### ISSUE TITLE
OSX 10.11.2 Can't complete the sudo npm install -g homebridge command

### ISSUE THREAD

**Issue by quantumquark07** [nodejs/node-gyp#872]
> mdns@2.2.11 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found

Attached is the debug file.
[npm-debug.txt](https://github.com/nodejs/node-gyp/files/103375/npm-debug.txt)

**Comment by bnoordhuis** [comment]
The error message is clear enough, isn't it?  You need to make sure node is on your PATH.

**Comment by BuckarooToo** [comment]
Similar problem (can't complete the command), but for a different reason, I think. Can anyone assist? Thanks for your time!
[npm-debug.txt](https://github.com/nodejs/node-gyp/files/232380/npm-debug.txt)

**Comment by bnoordhuis** [comment]
@BuckarooToo What was printed in the terminal?  The npm-debug.log only shows that something went wrong executing node-gyp, not what.

I'm going to close the issue because the OP never replied but feel free to ask more questions.
