### ISSUE TITLE
(Windows) Add CompileAsManaged (/clr) flag to specific files, not the entire project

### ISSUE THREAD

**Issue by amitv87** [nodejs/node-gyp#876]
Adding **'CompileAsManaged':'true'** to **msbuild_settings** in binding.gyp compiles entire project as managed.
I need to compile only some files to be compile as managed not all.

This is what i want the generated **.vcxproj** file to look like.
`  <ItemGroup>`
`    <ClCompile Include="..\src\file1.cc" />`
`    <ClCompile Include="..\src\file2.cc" />`
`    <ClCompile Include="..\src\file3.cc" />`
`    <ClCompile Include="..\src\file4.cc">`
`      <CompileAsManaged>true</CompileAsManaged>`
`    </ClCompile>`
`    <ClCompile Include="..\src\file5.cc" />`
`  </ItemGroup>`

**Comment by bnoordhuis** [comment]
Untested but I think you should be able to add a second target that has CompileAsManaged set, then make the main target depend on it with `'dependencies': ['second_target_name']`.

**Comment by amitv87** [comment]
That works perfectly fine, thanks :)
