### ISSUE TITLE
symlink the built .node files into the "build" dir

### ISSUE THREAD

**Issue by TooTallNate** [nodejs/node-gyp#88]
Sorta solves the problem of "what to require" when you want to conditionally require the Release or Debug build, depending on that was last built.

/cc @tjfontaine

**Comment by Trott** [comment]
This issue is approaching 6 years of inactivity. Should it remain open? (Not saying it should or shouldn't. Just honestly asking. For all I know, the issue has been resolved.)

**Comment by bnoordhuis** [comment]
I'm not sure what issue this was trying to solve.  I'll close it out.
