### ISSUE TITLE
This repo needs a CONTRIBUTING.md

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-gyp#881]
It can probably lift large sections from node's [CONTRIBUTING.md](https://github.com/nodejs/node/blob/v5.6.0/CONTRIBUTING.md).

**Comment by orangemocha** [comment]
The new template for contributing is also an option: https://github.com/nodejs/TSC/blob/master/BasePolicies/CONTRIBUTING.md

**Comment by vennilapanneer** [comment]
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\IS4800>d:

D:\>cd projects\electron-quick-start-master\electron-quick-start-master

D:\projects\electron-quick-start-master\electron-quick-start-master>npm install
electron-spell-check-provider --save
\
> spellchecker@3.3.1 install D:\projects\electron-quick-start-master\electron-qu
ick-start-master\node_modules\electron-spell-check-provider\node_modules\spellch
ecker
> node-gyp rebuild


D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules
\electron-spell-check-provider\node_modules\spellchecker>if not defined npm_conf
ig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:1
4)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\electron-quick-start-master\electron-quick-start-master
\node_modules\electron-spell-check-provider\node_modules\spellchecker
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "electron-spell-check-provider" "-
-save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\electron-quick-start-master\electron-quick-start-master
\npm-debug.log

D:\projects\electron-quick-start-master\electron-quick-start-master>

**Comment by gibfahn** [comment]
This was added in https://github.com/nodejs/node-gyp/pull/771, but it might be worth leaving this open as that doesn't contain anything that's `node-gyp` specific.
