### ISSUE TITLE
node-gyp rebuild Fail on osx with Xcode V 7.2.1

### ISSUE THREAD

**Issue by Barno** [nodejs/node-gyp#882]
I have a problem with `node-gyp rebuild`
Now I'm using xcode Version 7.2.1 (7C1002) and when I install the library like
`libxmljs@0.14.3` I have this error

```
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Users/bob/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd my-path/node_modules/gulp-xml-editor/node_modules/libxmljs
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/bob/.nvm/versions/node/v0.12.6/bin/node" "/Users/bob/.nvm/versions/node/v0.12.6/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

I tried with NVM with this node version

nvm 0.12.6 | nvm 0.12.7

But I have the same Problem

With command `node-gyp rebuild``

I have this output

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.12.7 | darwin | x64
gyp info spawn /Applications/MAMP/Library/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/my-path/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bob/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bob/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/my-path',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: my-path) while trying to load binding.gyp  
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd my-path
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
Can you post the full output of `node-gyp rebuild`?  It looks truncated.

**Comment by Barno** [comment]
@bnoordhuis I've updated, thanks a lot

**Comment by bnoordhuis** [comment]
> gyp: binding.gyp not found (cwd: my-path) while trying to load binding.gyp  

That means you're not in the source directory of the module you're trying to build.

Aside, there's sometimes (but not always) useful info in npm-debug.log after a failed `npm install`.

**Comment by Barno** [comment]
@bnoordhuis I'm in the root of my project. In my log file I can read the error, but it is the same of previous paste

**Comment by bnoordhuis** [comment]
Okay, try installing the latest version of libxmljs.  According to https://www.npmjs.com/package/libxmljs, 0.17.1 is the current version; 0.14.3 is probably quite vintage by now.

**Comment by Barno** [comment]
@bnoordhuis I have the same issue also with libxmljs@0.17.1

`npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.`

**Comment by bnoordhuis** [comment]
Okay, quick sanity check: can you clone that project and run `node-gyp rebuild` from its top-level directory?

**Comment by Barno** [comment]
I have already did this attempt, and I have the same issue ( thanks for your time )

**Comment by bnoordhuis** [comment]
Right, but I'm interested in the output from node-gyp.  If it's that "binding.gyp not found" error, you're not in the right directory.

**Comment by Barno** [comment]
ok, this is my output

    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.2.1
    gyp info using node@0.12.7 | darwin | x64
    gyp info spawn /Applications/MAMP/Library/bin/python2
    gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/bob/Documents/Lavori/workbook-app/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/bob/.node-gyp/0.12.7/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/bob/.node-gyp/0.12.7',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/bob/Documents/Lavori/workbook-app',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: binding.gyp not found (cwd: /Users/bob/Documents/Lavori/workbook-app) while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Darwin 15.3.0
    gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
    gyp ERR! cwd /Users/bob/Documents/Lavori/workbook-app
    gyp ERR! node -v v0.12.7
    gyp ERR! node-gyp -v v3.2.1
    gyp ERR! not ok

**Comment by wnordmann** [comment]
I am also experiencing this problem with Xcode 7.2.1, I am using node version 5.6.0

**Comment by kireol** [comment]
Also getting the same issue.  OSX El Capitan.  trying to install libxmljs and getting the same error.

node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.3.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kireol/Desktop/projects/html5/loom2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kireol/.node-gyp/4.3.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kireol/.node-gyp/4.3.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kireol/Desktop/projects/html5/loom2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/kireol/Desktop/projects/html5/loom2) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node4-lts/4.3.1/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/kireol/Desktop/projects/html5/loom2
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok

**Comment by wnordmann** [comment]
I resolved this by deleting my local node_modules/ folder and rerunning 
> npm install 

I tired all kinds of messing with xcode that had no impact.

**Comment by trevorrjohn** [comment]
has anyone gotten another solution for this. I have tried removing my node_modules folder like @wnordmann said, but still had the same issue.

**Comment by jgladch** [comment]
+1

**Comment by erdinc** [comment]
I'm using nvm and I solved this issue by `cd ~/.nvm/versions/node/v5.5.0/lib/node_modules/npm` (change v5.5.0 with your node version.) run `npm install`

**Comment by Bclayson** [comment]
@erdinc This worked for me, thanks! My question is, why does this work?

**Comment by karenpeng** [comment]
I had the same problem before, solved it by upgrading node and npm version.

**Comment by ran85** [comment]
same as @Barno

**Comment by laurenbenichou** [comment]
Solved this by deleted everything node/npm-related off my machine. Helpful link here: 

http://benznext.com/2015/04/completely-uninstall-node-js-from-mac-os-x/

I then reinstall with brew. Using node 0.12.7. I hope it helps.

**Comment by SatyaSudheer** [comment]
Facing the same issues, tried uninstalling node & getting the fresh installation also didn't help :(

**Comment by JanBrinker** [comment]
Same issues. And I just had to install node for my project just now. So re-installing everything propably won't fix this ;)

**Comment by ortizman** [comment]
`n lts` 
install node 4.5.0 and npm 2.15.9 worked for my
