### ISSUE TITLE
segfault while acquiring connection to database that doesn't exist

### ISSUE THREAD

**Issue by qpresley** [nodejs/node-gyp#886]
While using an ODBCConnection with a connection string for a database that doesn't exist I get a segfault with the following stack.  Need help debugging and a quick fix.

ODBCConnection::Open
ODBCConnection::UV_Open
ODBCConnection::UV_Open : connectTimeout=30, loginTimeout = 0
PID 26363 received SIGSEGV for address: 0x7fc0335cb1e8
/home/qpresley/MySecondApp/node_modules/loopback-connector-db2/node_modules/ibm_db/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x2ef7)[0x7fc004e4cef7]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7fc03259d340]
/home/qpresley/sqllib/lib64/libdb2.so.1(+0x5891a0)[0x7fc00d7861a0]
/home/qpresley/sqllib/lib64/libdb2.so.1(+0x584267)[0x7fc00d781267]
/home/qpresley/sqllib/lib64/libdb2.so.1(pdLog+0x410)[0x7fc00d7809b0]
/home/qpresley/sqllib/lib64/libdb2.so.1(+0x10c67ef)[0x7fc00e2c37ef]
/home/qpresley/sqllib/lib64/libdb2.so.1(sqlofmblkEx+0x892)[0x7fc00d957e82]
/home/qpresley/sqllib/lib64/libdb2.so.1(_Z17CLI_memFreeToPoolPPv+0x38)[0x7fc00d71d238]
/home/qpresley/sqllib/lib64/libdb2.so.1(SQLDriverConnectW+0x255)[0x7fc00db41e05]
/home/qpresley/MySecondApp/node_modules/loopback-connector-db2/node_modules/ibm_db/build/Release/odbc_bindings.node(_ZN14ODBCConnection7UV_OpenEP9uv_work_s+0xab)[0x7fc021de645b]
node[0xfbeaa1]
node[0xfcd8d9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x7fc032595182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fc0322c247d]
Segmentation fault (core dumped)

**Comment by bnoordhuis** [comment]
You're reporting this to the wrong project.  I'll close the issue.

**Comment by qpresley** [comment]
Thanks Ben, had too many repo's open.
