### ISSUE TITLE
 Tessel install problem issues

### ISSUE THREAD

**Issue by abhishek20502025** [nodejs/node-gyp#888]
Hey, i am trying to install tessel module on npm...facing issues ,,,please help
OS= windows 10:
Python :2.7
I installed MS VISUAL Studio.
Now,
on npm install -g tessel 
as showing some errors related to install Visual C++
I tried by installing Visual C++ Compiler...

New Error Arises.....

C:\Users.hp\npm\node_modules\tessel\node_modules\usb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding ) else (node build --fallback-to-build --module=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
core.c
descriptor.c
hotplug.c
io.c
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\io.c)C:\Users.hp\npm\node_modules\tessel\node_modu
les\usb\libusb\libusb\os/threads_windows.h(47): error C2011: 'timespec': 'struc
t' type redefinition (compiling source file ..\libusb\libusb\core.c) [C:\Users\
.hp\npm\node_modules\tessel\node_modules\usb\build\libusb.vcxproj]
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\descriptor.c) [C:\Users.hp\npm\node_modules\tessel
\node_modules\usb\build\libusb.vcxproj]

C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\c
ore.c)C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h
(39): note: see declaration of 'timespec' (compiling source file ..\libusb\li
busb\io.c)

C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\d
escriptor.c)C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libu
sb\os/threads_windows.h(47): error C2011: 'timespec': 'struct' type redefinit
ion (compiling source file ..\libusb\libusb\hotplug.c)

C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\h
otplug.c)
..\libusb\libusb\io.c(1227): warning C4244: '=': conversion from 'time_t' to 'l
ong', possible loss of data [C:\Users.hp\npm\node_modules\tessel\node_modules\
usb\build\libusb.vcxproj]
..\libusb\libusb\io.c(1902): warning C4244: '=': conversion from 'time_t' to 'l
ong', possible loss of data [C:\Users.hp\npm\node_modules\tessel\node_modules\
usb\build\libusb.vcxproj]
..\libusb\libusb\io.c(2435): warning C4244: '=': conversion from 'time_t' to 'l
ong', possible loss of data [C:\Users.hp\npm\node_modules\tessel\node_modules\
usb\build\libusb.vcxproj]
strerror.c
sync.c
poll_windows.c
threads_windows.c
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\os\threads_windows.c) [C:\Users.hp\npm\node_module
s\tessel\node_modules\usb\build\libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\o
s\threads_windows.c)
..\libusb\libusb\os\threads_windows.c(194): warning C4244: '=': conversion from
'time_t' to 'long', possible loss of data [C:\Users.hp\npm\node_modules\tesse
l\node_modules\usb\build\libusb.vcxproj]
..\libusb\libusb\os\threads_windows.c(196): warning C4244: '=': conversion from
'const time_t' to 'long', possible loss of data [C:\Users.hp\npm\node_modules
\tessel\node_modules\usb\build\libusb.vcxproj]
windows_usb.c
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\sync.c) [C:\Users.hp\npm\node_modules\tessel\node_
modules\usb\build\libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\s
ync.c)
win_delay_load_hook.c
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\os\poll_windows.c) [C:\Users.hp\npm\node_modules\t
essel\node_modules\usb\build\libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\o
s\poll_windows.c)
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\strerror.c) [C:\Users.hp\npm\node_modules\tessel\n
ode_modules\usb\build\libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\s
trerror.c)
C:\Users.hp\npm\node_modules\tessel\node_modules\usb\libusb\libusb\os/threads_
windows.h(47): error C2011: 'timespec': 'struct' type redefinition (compiling s
ource file ..\libusb\libusb\os\windows_usb.c) [C:\Users.hp\npm\node_modules\te
ssel\node_modules\usb\build\libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39):
note: see declaration of 'timespec' (compiling source file ..\libusb\libusb\o
s\windows_usb.c)
..\libusb\libusb\os\windows_usb.c(586): warning C4244: '=': conversion from '__
int64' to 'unsigned int', possible loss of data [C:\Users.hp\npm\node_modules\
tessel\node_modules\usb\build\libusb.vcxproj]
..\libusb\libusb\os\windows_usb.c(1017): warning C4996: 'GetVersionExA': was de
clared deprecated [C:\Users.hp\npm\node_modules\tessel\node_modules\usb\build\
libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433): note: s
ee declaration of 'GetVersionExA'
..\libusb\libusb\os\windows_usb.c(1020): warning C4996: 'GetVersionExA': was de
clared deprecated [C:\Users.hp\npm\node_modules\tessel\node_modules\usb\build\
libusb.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433): note: s
ee declaration of 'GetVersionExA'
..\libusb\libusb\os\windows_usb.c(1423): warning C4244: '=': conversion from '_
_int64' to 'unsigned int', possible loss of data [C:\Users.hp\npm\node_modules
\tessel\node_modules\usb\build\libusb.vcxproj]
..\libusb\libusb\os\windows_usb.c(2558): warning C4018: '<': signed/unsigned mi
smatch [C:\Users.hp\npm\node_modules\tessel\node_modules\usb\build\libusb.vcxp
roj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack at emitTwo (events.js:87:13)
gyp ERR! stack at ChildProcess.emit (events.js:172:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=C:\Users\.hp\npm\node_modules\tessel\node_modules\usb\src\binding\usb_bindings.node" "--module_name=usb_bindings" "--module_path=C:\Users\.hp\npm\node_modules\tessel\node_modules\usb\src\binding"
gyp ERR! cwd C:\Users.hp\npm\node_modules\tessel\node_modules\usb
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding' (1)
node-pre-gyp ERR! stack at ChildProcess. (C:\Users.hp\npm\node_modules\tessel\node_modules\usb\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\.hp\npm\node_modules\tessel\node_modules\usb\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users.hp\npm\node_modules\tessel\node_modules\usb
node-pre-gyp ERR! node -v v4.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=C:\Users.hp\npm\node_modules\tessel\node_modules\usb\src\binding' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "tessel"
npm ERR! node v4.3.1
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! usb@1.0.6 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR! npm owner ls usb
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment]
Wrong place.  Please report this to the tessel project.
