### ISSUE TITLE
macOSX10.11安装不成功

### ISSUE THREAD

**Issue by hhhaiai** [nodejs/node-gyp#891]
[~/code]npm install -g appdmg
/usr/local/bin/appdmg -> /usr/local/lib/node_modules/appdmg/bin/appdmg.js

macos-alias@0.2.9 install /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
node-gyp rebuild
Traceback (most recent call last):
File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in 
import gyp
File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/init.py", line 8, in 
import gyp.input
File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 16, in 
import optparse
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 90, in 
from gettext import gettext
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 49, in 
import locale, copy, os, re, struct, sys
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 110, in 
@functools.wraps(_localeconv)
AttributeError: 'module' object has no attribute 'wraps'
gyp ERR! configure error 
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack at emitTwo (events.js:87:13)
gyp ERR! stack at ChildProcess.emit (events.js:172:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "install" "-g" "appdmg"
npm ERR! node v5.4.1
npm ERR! npm v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! macos-alias@0.2.9 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macos-alias@0.2.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the macos-alias package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs macos-alias
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls macos-alias
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/sanbo/code/npm-debug.log
npm ERR! code 1

**Comment by hhhaiai** [comment]
python环境2.7.11

[~/code]python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by bnoordhuis** [comment]
I can't say for sure but it appears to be a problem with your python install, not node-gyp or gyp.  The error originates in (a dependency of) the built-in optparse module.

**Comment by hhhaiai** [comment]
what can I do ?

**Comment by hhhaiai** [comment]
![image](https://cloud.githubusercontent.com/assets/5738285/13658543/fe4e7b98-e6b2-11e5-88fe-d84feb41eb49.png)

明显，这是一个参数不匹配的问题，是否python2.xx不支持这个，必须使用3.xx才行？

**Comment by bnoordhuis** [comment]
Try doing a system update.  If that doesn't help, I don't know.

**Comment by saghul** [comment]
How did you get that Python version installed? On OSX 10.11.3 I have Python 2.7.10, not 2.7.11. I doubt 2.7.11 is broken, but maybe your system is running a weird mix? What does this print on your terminal?

~~~~
python -c 'import functools;print(functools.wraps)'
~~~~

**Comment by hhhaiai** [comment]
try it  tomorow. I'm out today. thx.

2016-03-10 15:46 GMT+08:00 Saúl Ibarra Corretgé <notifications@github.com>:

**Comment by bnoordhuis** [comment]
No follow-up.  I'll assume it's working now and close the issue.

**Comment by hhhaiai** [comment]
[~]python -c 'import functools;print(functools.wraps)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'wraps'

**Comment by hhhaiai** [comment]
Hi:
   still wrong

**Comment by saghul** [comment]
Your installation must be broken, functools.wraps is part of the standard library.
