### ISSUE TITLE
Build node-gyp on Centos

### ISSUE THREAD

**Issue by molokoloco** [nodejs/node-gyp#900]
I have a hard time for figuring out that my g++ compiler was outdated cause of unclear error message during install... My solution for it to works on CENTOS :

1/ I have installed updated g++ with devTool
> sudo yum install --skip-broken devtoolset-3
> sudo yum install devtoolset-3-gcc-c++
> sudo source /opt/rh/devtoolset-3/enable

2/ And then it work (in my case node-gyp was a dependency of "ursa" package) ! ;)
> sudo npm --loglevel verbose --unsafe-perm i ursa

**Comment by jbergstroem** [comment]
What we (nodejs) do (on centos5) when packging node is install our toolchain from the cern repo: `http://linuxsoft.cern.ch/cern/devtoolset/slc5-devtoolset.repo`:
```bash
$ curl -sL http://linuxsoft.cern.ch/cern/devtoolset/slc5-devtoolset.repo -o /etc/yum.repos.d/slc5-devtoolset.repo
$ rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/{{ ansible_architecture }}/RPM-GPG-KEYs/RPM-GPG-KEY-cern
```

**Comment by bnoordhuis** [comment]
Looks like this has been resolved.  Closing.
