### ISSUE TITLE
Please support Visual Studio 15 ( not 2015=14)

### ISSUE THREAD

**Issue by alanpurple** [nodejs/node-gyp#901]
Please support Visual Studio 15, it appears to be not compatible
with nodejs 5.10.1 x64 + node-gyp 3.3.1 on Windows 10 x64

**Comment by bnoordhuis** [comment]
Can you be more specific?  `--mvs_version=2015` does the trick just fine, AFAICT.

**Comment by alanpurple** [comment]
@bnoordhuis  no I mean, without VS2015, only with VS15 preview
now I have installed VS2015 and VS15 both, that's the only option for now

**Comment by bnoordhuis** [comment]
Oh, preview?  I don't think we'll spend any effort on that until it goes gold.
