### ISSUE TITLE
Node-gyp g++ and libsass error

### ISSUE THREAD

**Issue by fivedoor** [nodejs/node-gyp#906]
I've been following the guide to install Zurb foundation but running into a consistent issue.
`$ npm install foundation-cli --global`
is successful but 
`:foundation fivedoor$ foundation new`
brings up:
```
g++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/bin/node" "/Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
```

I have seen some similar errors in other github posts
To be honest, being pretty new to node, I'm sure it's possible I may have been inept in implementing some of the various solutions suggested . 

I have tried quite a few things without any joy:
- complete uninstall/ reinstall latest node & npm; 
- clean npm cache; install with nvm, brew; 
- updating git to latest version that supports snow leopard; 
- npm --optional install ; 
- installed macports and then updated GCC and G++; 
- deleting .node-gyp folder and reinstall; 
- uninstall and reinstall foundation-cli. 

Been keeping an expanding troubleshooting log as I go. The most recent stuff at https://github.com/fivedoor/foundation-records/blob/master/my_installation_log_post_reinstall100416
 
Failing a silver bullet solution, could someone advise if upgrading to a later OS is likely to help or not? ( I know snow leopard is old but I've clung on to it for stability.) I did get some warnings from brew that " We (and Apple) do not provide support for OS 10.6"

The frustrating thing is at  this stage I'm not trying to do anything more 'advanced' than just install the packages I need to get started.

 - MACOS X Version 10.6.8 
 - npm 3.8.6 		
 - node v4.4.2   
 - Xcode 3.2.6
 - GCC 4.7.4
 - g++ 4.7.4
 - nvm 0.31.0
 - git version 1.8.4.2 
 - curl 7.19.7

thanks

**Comment by bnoordhuis** [comment]
You could try reporting that to the libsass project.  It's not a node-gyp bug as such, I suspect that libsass has `CLANG_CXX_LIBRARY` set to `libc++` in its binding.gyp.

I'm not sure how far you'll get, though.  If you want to compile against node.js v4, you're going to need at least g++ 4.8.  You could try downgrading to node v0.10 or v0.12 but I can't promise success.  Good luck!

**Comment by fivedoor** [comment]
Thanks for your help bnoordhuis 
I updated to G++ 4.8.5 but didn't see any resolution. 

I guess I will see what feedback I can get from libsass 

thanks

**Comment by radiosource** [comment]
Have same problem, it was solved after installation gcc-c++

**Comment by radiosource** [comment]
Have same problem, it was solved after installation gcc-c++
