### ISSUE TITLE
node-gyp\5.11.0\include\node\node_internals.h(5): fatal error C1083: Cannot open include file: 'util.h'

### ISSUE THREAD

**Issue by misterfresh** [nodejs/node-gyp#913]
Downloaded and installed the 10 GB of Visual Studio Community 2015, installed Python, set the environment variable GYP_MSVS_VERSION, and now I have this error.
How can I fix it? (windows 10 x64)

**Comment by bnoordhuis** [comment]
You could start by telling what exactly you're trying to do, you're leaving me guessing now.  Are you building node.js?  An add-on?  Please post the console output verbatim.

**Comment by bnoordhuis** [comment]
No follow-up, closing.
