### ISSUE TITLE
Omit the "arch" flag on OS X

### ISSUE THREAD

**Issue by jjrv** [nodejs/node-gyp#918]
I'm using node-gyp with the Emscripten compiler. [nbind](https://github.com/charto/nbind) allows compiling the same C++ code as a native Node.js module and an asm.js fallback. On OS X I currently manually edit `build/<project>.target.mk` for Emscripten builds to remove the `-arch x86_64` flag. Otherwise Emscripten complains:

```
ERROR:root:x86_64: No such file or directory ("x86_64" was expected to be an input file, based on the commandline arguments provided)
```

It seems to simply ignore the flag and thinks its parameter is an input file. In any case Emscripten only targets a single possible architecture (JavaScript). Is there a way to omit the flag? Otherwise everything's working fine with this compiler (it derives from clang).

**Comment by TooTallNate** [comment]
--target=linux might help

**Comment by jjrv** [comment]
It didn't help... I ended up monkey-patching the command line arguments. The code is quite specific to my case but maybe it's a useful reference for some other situation...

`binding.gyp` contains:

```json
    "conditions": [
        ["emcc==1", {
            "make_global_settings": [
                ["CXX",  "<!(npm run -s emcc-path)"],
                ["LINK", "<!(npm run -s emcc-path)"],
            ]
        }]
    ]
```

`package.json` contains:

```json
  "bin": {
    "emcc-path": "bin/emcc-path.js"
  },
  "scripts": {
    "emcc-path": "emcc-path",
  }
```

`bin/emcc-path.js` contains (replace `<package>` with your package and `npm link` it if needed):

```JavaScript
#!/usr/bin/env node

process.stdout.write(require.resolve('<package>/bin/emcc'));
```

And finally, the wrapper script `bin/emcc`:

```bash
#!/bin/sh

skip=0

for arg; do
  shift
  [ "$skip" = "1" ] && skip=0 && continue
  [ "$arg" = "-arch" ] && skip=1 && continue
  set -- "$@" "$arg"
done

emcc $@
```

That drops the "-arch" flag and its argument. It should be portable across different shells.

**Comment by xzyfer** [comment]
With Web Assembly support approaching ubiquity I think it's appropriate to circle back around to this request. We (the node-sass team) have been working on porting our native extension to WASM and this issue was a hurdle for us.

Thanks @jrvv for a hint at a work around.
