### ISSUE TITLE
node-gyp - do not pass -std=gnu++0x

### ISSUE THREAD

**Issue by psinghsp** [nodejs/node-gyp#922]
I have a requirement to use node on really old Linux. I am using node 4.4.2. When I add a module like "pty.js", node-gyp complains about:

> pty.js@0.3.0 install /home3/psingh/xxx/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/home3/psingh/xxx/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1

Is there a way to customize node-gyp to not pass this flag to gcc tool chain?

**Comment by bnoordhuis** [comment]
> Is there a way to customize node-gyp to not pass this flag to gcc tool chain?

Yes, `'cflags_cc!': ['-std=gnu++0x']`, but that won't help because a C++11-capable compiler is required for anything that builds against node.js v4.x or newer.

If upgrading the compiler toolchain is not an option, your only recourse is to downgrade to node.js v0.10 or v0.12.  Good luck.

**Comment by psinghsp** [comment]
Thanks for a quick reply.
 I guess I understand now. If I compile with node v0.10 and then run the package with node 4.x, I get ELF compatibility issue. So it seems like I have to have node v10 on the platform for this to work.

**Comment by Flarna** [comment]
You could also try to install (or build) a gcc version which supports C++11 on this old linux.
If this is no option you could also try to build on some other linux machine (maybe just a VM setup only for this purpose) and move the results to the old linux box. Could be that it's needed that the linux build machine has to use a version of glibc at least as old as on the final linux.
