### ISSUE TITLE
Impossible to negate certain flags

### ISSUE THREAD

**Issue by alexhultman** [nodejs/node-gyp#924]
I need to remove some bullshit flags from my build. It doesn't work.

```
        ['OS=="linux"', {
          'cflags_cc': [ '-fexceptions', '-std=c++11' ],
          'cflags_cc!': [ '-fno-exceptions', '-std=gnu++0x', '-fno-omit-frame-pointer', '-fno-rtti' ]
        }],
```

```-fno-omit-frame-pointer``` is not removed from the build, while ```-fno-rtti``` is. This is broken, I never asked for these flags and they shouldn't be there to taint my project.

**Comment by bnoordhuis** [comment]
> -fno-omit-frame-pointer is not removed from the build, while -fno-rtti is.

You can remove it through `cflags!`.

> This is broken, I never asked for these flags and they shouldn't be there to taint my project.

They come from node's common.gypi, not node-gyp's addon.gypi.  You don't have to like it but it's not going to change.
