### ISSUE TITLE
node-gyp build fails on windows7: Cannot open include file: 'util.h'

### ISSUE THREAD

**Issue by rejas** [nodejs/node-gyp#925]
When doing a fresh npm install for my homepage, one of the modules downloaded seems to trigger a node-gyp build that fails on my windows7/node6 machine. 

I followed this answer: https://stackoverflow.com/questions/32556295/npm-install-error-the-build-tools-for-v120-platform-toolset-v120-cannot#answer-32556296, installed Visual C++ Build Tools 2015 and called npm install --msvs_version=2015

Output I get is:

D:\Projekte\mine\homepage>npm install --msvs_version=2015
(node:7160) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
loadDep:node-zlib-backpor █ ╣████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╠
WARN engine node-zlib-backport@0.11.15: wanted: {"node":">=0.10 <0.11"} (current

> node-zlib-backport@0.11.15 install D:\Projekte\mine\homepage\node_modules\node
-zlib-backport
> node-gyp rebuild

D:\Projekte\mine\homepage\node_modules\node-zlib-backport>if not defined npm_con
fig_node_gyp (node "D:\Projekte\sdk\npm\global\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  node_zlib.cc
C:\Users\veeck\.node-gyp\6.1.0\include\node\node_internals.h(5): fatal error C1
083: Cannot open include file: 'util.h': No such file or directory [D:\Projekte
\mine\homepage\node_modules\node-zlib-backport\build\zlib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Projekte\sdk\npm\global\node_modul
es\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projekte\\sdk\\npm\\
global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projekte\mine\homepage\node_modules\node-zlib-backport
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install:
`node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1

**Comment by bnoordhuis** [comment]
Can you report that to the node-zlib-backport project?  It's an issue with that module, not node-gyp.

**Comment by rejas** [comment]
will do, thx for the quick reply
