### ISSUE TITLE
node-gyp attempts to install node.lib from the wrong URL on Windows

### ISSUE THREAD

**Issue by nanowizard** [nodejs/node-gyp#929]
Attempted installing the latest version of node LTS (v4.4.4) on windows and a package with node-gyp as a dependency. During the `node-gyp rebuild`, I got the following error:

	> node-gyp rebuild

	C:\Users\blah\blah\node-gyp.js" rebuild
	gyp http GET http://nodejs.org/dist/v4.4.4/node-v4.4.4.tar.gz
	gyp http 200 http://nodejs.org/dist/v4.4.4/node-v4.4.4.tar.gz
	gyp http GET http://nodejs.org/dist/v4.4.4/SHASUMS256.txt
	gyp http GET http://nodejs.org/dist/v4.4.4/x64/node.lib
	gyp http GET http://nodejs.org/dist/v4.4.4/node.lib
	gyp http 404 http://nodejs.org/dist/v4.4.4/x64/node.lib
	gyp WARN install got an error, rolling back install
	gyp http 200 http://nodejs.org/dist/v4.4.4/SHASUMS256.txt
	gyp http 404 http://nodejs.org/dist/v4.4.4/node.lib
	gyp ERR! configure error
	gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
	gyp ERR! stack     at Request.<anonymous> (C:\Users\rsivek\AppData\Roaming\npm\n
	ode_modules\npm\node_modules\node-gyp\lib\install.js:395:20)
	gyp ERR! stack     at emitOne (events.js:82:20)
	gyp ERR! stack     at Request.emit (events.js:169:7)
	gyp ERR! stack     at Request.onRequestResponse (C:\Users\rsivek\AppData\Roaming
	\npm\node_modules\npm\node_modules\request\request.js:1255:10)
	gyp ERR! stack     at emitOne (events.js:77:13)
	gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
	gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
	gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
	gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
	gyp ERR! stack     at emitOne (events.js:77:13)
	gyp ERR! System Windows_NT 6.1.7601

It looks like node-gyp attempts to pull node.lib from http://nodejs.org/dist/v4.4.4/x64/ and http://nodejs.org/dist/v4.4.4/, which aren't there, but it looks like the file is *actually* accessible at http://nodejs.org/dist/v4.4.4/win-x64/node.lib. Note the "win-" there.

I'm running with node-gyp v3.3.1

**Comment by nanowizard** [comment]
Nevermind. Turns out it wasn't actually using v3.3.1. When I installed node v4.4.4, it included node-gyp v1.0.2, and that's what was being used until I removed that node-gyp instance from the PATH. Worked beautifully after that. Why does Node come configured with a version of node-gyp that doesn't even work with it?!

**Comment by bnoordhuis** [comment]
node.js v4.4.4 bundles node-gyp v3.3.1.  I don't know where you picked up that old copy but it wasn't from the installer.

**Comment by nanowizard** [comment]
Yeah, I realized afterward it must have been left over from my previous node installation. So the installer doesn't overwrite previous installations of node_modules?

**Comment by bnoordhuis** [comment]
No problem, happy to hear it's working now.
