### ISSUE TITLE
Is it possible to link against the c-ares node.js is built with inside an addon?

### ISSUE THREAD

**Issue by JCMais** [nodejs/node-gyp#931]
Let's say I have an addon that needs c-ares, can I use the one that is built with Node.js or I need to provide my own?

If I can use the one provided with Node.js, how I can do that?

**Comment by bnoordhuis** [comment]
I wouldn't recommend linking against the bundled c-ares.  For starters, the Windows build doesn't export the `ares_*` symbols; it simply won't work on that platform.

On Linux, the symbols are visible (albeit by incident) but it contains out-of-tree patches that affect its behavior, possibly even the API or ABI, and those can change without prior warning.

**Comment by JCMais** [comment]
I will provide my own then.

Thanks for the information!

**Comment by nikelborm** [comment]
Hi @JCMais did your last comment meant that you will create the library that will allow using c-ares in node.js? If so and you created it, where is it published and can I access it?

**Comment by JCMais** [comment]
> Hi @JCMais did your last comment meant that you will create the library that will allow using c-ares in node.js? If so and you created it, where is it published and can I access it?


No, I meant that my library (node-libcurl) needs c-ares, and I wanted to link it against the one used by node, but that is not possible, so I added c-ares directly as a build dependency, so it's built separately just for usage with my add-on. I'm not exposing any c-ares related api.
