### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by ashalaenko** [nodejs/node-gyp#94]
```
/usr/local/lib/node_modules# node-gyp rebuild


gyp info it worked if it ends with ok
gyp info using node-gyp@0.5.7
gyp info using node@0.8.1
gyp info spawn python
gyp info spawn args [ '/root/.node-gyp/0.8.1/tools/gyp_addon',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-I/usr/local/lib/node_modules/build/config.gypi',
gyp info spawn args   '-f',
gyp info spawn args   'make' ]
Traceback (most recent call last):
  File "/root/.node-gyp/0.8.1/tools/gyp_addon", line 38, in <module>
    rc = gyp.main(gyp_args)
  File "/root/.node-gyp/0.8.1/tools/gyp/pylib/gyp/__init__.py", line 471, in main
    options.circular_check)
  File "/root/.node-gyp/0.8.1/tools/gyp/pylib/gyp/__init__.py", line 111, in Load
    depth, generator_input_info, check, circular_check)
  File "/root/.node-gyp/0.8.1/tools/gyp/pylib/gyp/input.py", line 2289, in Load
    depth, check)
  File "/root/.node-gyp/0.8.1/tools/gyp/pylib/gyp/input.py", line 361, in LoadTargetBuildFile
    includes, True, check)
  File "/root/.node-gyp/0.8.1/tools/gyp/pylib/gyp/input.py", line 208, in LoadOneBuildFile
    raise Exception("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
Exception: binding.gyp not found (cwd: /usr/local/lib/node_modules) while trying to load binding.gyp
gyp ERR! rebuild error Error: `gyp_addon` failed with exit code: 1
gyp ERR! rebuild error     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:290:16)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok 
```

**Comment by whitef0x0** [comment]
I'm currently getting the same problem.

**Comment by ganna-shmatova** [comment]
one of about 7 issues i've been having installing node-gyp

**Comment by heroselohim** [comment]
I tried everything posted solution here. Still not working for me.

**Comment by kala725** [comment]
Try running the following commands and then run npm install

sudo npm cache clean -f
sudo npm install -g n
sudo n 4.4.5
sudo npm install npm -g
sudo npm uninstall node-gyp -g
sudo npm uninstall node-gyp

**Comment by niftylettuce** [comment]
Your solution does not work, this is still broken.

**Comment by krylatij** [comment]
Go to the folder with binding.gyp of your module and run "node-gyp configure" from it.

**Comment by seatownrocks** [comment]
binding.gyp does not exist...

```
ERSmith@S7-ERSMITH-L MINGW64 ~/AppData/Roaming/npm/node_modules/node-gyp/gyp
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main                                           .py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\build\\c                                           onfig.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ERSmith\\.node-gyp\\6.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ERSmith\\.node-gyp\\6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-gyp                                           ',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-                                           gyp\\gyp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\Users\ERSmith\AppData\Roaming\npm\node_modules\node-gyp\gyp) while                                            trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\ERSmith\AppData\Roaming\npm\node_modules\node-gyp                                           \lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ERSmith\\AppData\\Roaming\\npm\\node                                           _modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\ERSmith\AppData\Roaming\npm\node_modules\node-gyp\gyp
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by mrmodise** [comment]
After hours of struggling with this issue. All I did was `npm config set GYP_MSVS_VERSION 2015`. I also pointed Python to npm as well as Visual Studio version. Your .npmrc file found in the hom directory should look like this:

`msvs_version=2015
python=C:Python27python.exe
GYP_MSVS_VERSION=2015
`

Ofcourse having Visual C++ installed together with Visual Studio (I used community edition, it had both)

**Comment by Spaxe** [comment]
Having the same problem with @seatownrocks, but on Ubuntu 16.04 LTS.

```
$ sudo node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.7.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/7.7.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/7.7.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /usr/lib/node_modules) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /usr/lib/node_modules
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
```

**Comment by ctzurcanu** [comment]
+1 for mac

**Comment by Spaxe** [comment]
Update, looks like @krylatij was on point. You have to run configure in a folder where binding.gyp is, or you will get this error. 

Problem solved once I found the right folder.

**Comment by ctzurcanu** [comment]
i have not found such file on my computer. note: i had to change recently to python3 and only today i am installing python2 alongside (just because gyp does not support ver 3)

**Comment by gibfahn** [comment]
@ctzurcanu what are you trying to use `node-gyp` for? It's a tool for building native node modules, and every native node module should have a `binding.gyp` file in the root. 

For example, you could clone `node-report` (a small native module in the nodejs foundation), and run `node-gyp configure` in that.

```bash
npm install -g node-gyp # This should put node-gyp in the path if it's not already
git clone https://github.com/nodejs/node-report.git
cd node-report
node-gyp configure
```

**Comment by ctzurcanu** [comment]
@gibfahn thank you. I wanted to build https://github.com/wekan/wekan and i see no binding.gyp in the source while in node-report is clearly present in the root..
I should understand that the source there is incomplete.

**Comment by gibfahn** [comment]
@ctzurcanu I don't think `wekan` is a native module. 

But basically if you just want to use modules, `npm install` should just work, you shouldn't need to use `node-gyp` directly.

**Comment by gibfahn** [comment]
Also that module has [a pretty detailed Wiki page](https://github.com/wekan/wekan/wiki/Install-and-Update), if you want to install I recommend reading the docs for the module.

**Comment by ctzurcanu** [comment]
@gibfahn thank you. It is exactly because following that Wiki page that I got in this trouble. They said on it to install gyp before `npm install`. But at your recommendation: I skipped that step and all that was of interest to me runs fine now :)

**Comment by M-Abozaid** [comment]
same here on Ubuntu

**Comment by gibfahn** [comment]
@M-Abozaid (and anyone else planning to comment) can you please raise an issue on https://github.com/nodejs/help ? Your issue is almost certainly not a `node-gyp` error.

Feel free to include a link to this issue and to cc/ me in the issue.

**Comment by jndachenhaus** [comment]
I am trying to install node-opus and keep getting node-gyp related errors to the binding.gyp

**Comment by refack** [comment]
@jndachenhaus depending on which platform you are working on (Windows/linux/mac) there are some steps you need to take in order for `node-gyp` to function properly. 
The [README](https://github.com/nodejs/node-gyp/blob/master/README.md) is now quite good, and has gone trough allot of improvempt. If you follow it's instructions `node-gyp` should work.

**Comment by feixuwu** [comment]
OK， I found the same error, because I only install visual studio 2017 and the node-gyp currently didn't support visual studio 2017, I changed the MSVSVersion.py script(under C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp),
and then fix this problem.
after fix the problem you can use command to install :
for example: npm install dnode --msvs_version=2017

In the MSVSVersion.py, you need add code 3 position:

1、In function _CreateVersion, you can add vs2017 like this:
     versions = {
	   '2017': VisualStudioVersion('2017',
                                  'Visual Studio 2017',
                                  solution_version='12.00',
                                  project_version='14.1',
                                  flat_sln=False,
                                  uses_vcxproj=True,
                                  path=path,
                                  sdk_based=sdk_based,
                                  default_toolset='v141'),



2、In _DetectVisualStudioVersions function, add one line:
    '14.1': '2017',

3、In SelectVisualStudioVersion function,  add one line:
   '2017': ('14.1',),

this works for me, only installed visual studio 2017.

**Comment by suyingtao** [comment]
sudo npm i

**Comment by AlexandreBonneau** [comment]
On my end, I had to do this to force a rebuild manually:
```sh
cd node_modules/fibers
npm install
```
Then I could use my project as usual.

**Comment by A-lee-201** [comment]
> npm install iconv -g

This worked for me. Thanks!

**Comment by ouqunfu** [comment]
@feixuwu This worked for me. Thanks!
