### ISSUE TITLE
There doesn't seem to be a way to disable ANSI escape sequences?

### ISSUE THREAD

**Issue by aufflick** [nodejs/node-gyp#946]
Even with TERM=dumb, node-gyp build pumps out a lot of ansi escape sequences.

Searching the repo for both ansi and color doesn't seem to suggest anything. There really should be a way to do this, am I missing something?

**Comment by rvagg** [comment]
I believe all of the ansi codes are coming out of npmlog (https://github.com/npm/npmlog/blob/master/log.js) which in turn is using ansi (https://github.com/TooTallNate/ansi.js/blob/master/lib/ansi.js) which is used without options, so it _looks_ like the only way to disable them is to not use a tty. So a hack, if you really don't want to have them on your tty might be to do something like `node-gyp build 2>&1 | cat`. Alternatively you can try and get a PR into one of the projects I mentioned above to get them to pay attention to another flag, such as the `$TERM`.

**Comment by aufflick** [comment]
Cheers for the detail, I'll dig through npmlog - thanks!

-- 
Mark Aufflick
