### ISSUE TITLE
error compiling win_delay_load_hook.c with visual studio preview 2

### ISSUE THREAD

**Issue by xtaltas** [nodejs/node-gyp#949]
Apparently <delayimp.h> header changed since visual studio 2015 update  3 setting const to PfnDliHook

// Prior to Visual Studio 2015 Update 3, these hooks were non-const.  They were
// made const to improve security (global, writable function pointers are bad).
// If for backwards compatibility you require the hooks to be writable, define
// the macro DELAYIMP_INSECURE_WRITABLE_HOOKS prior to including this header and
// provide your own non-const definition of the hooks.
 
Probably should include this in win_delay_load_hook.c source file
 
#ifndef DELAYIMP_INSECURE_WRITABLE_HOOKS
#define DELAYIMP_INSECURE_WRITABLE_HOOKS
#endif

**Comment by xtaltas** [comment]
Yes apparently it looks fine

Christian Taltas
KPMG Technologies Services - Directeur Général
ctaltas@kpmg.fr<mailto:ctaltas@kpmg.fr>
+44 7482003570<tel:+44%207482003570>




On Mon, Jun 6, 2016 at 10:28 AM -0700, "Ben Noordhuis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Would const-ifying __pfnDliNotifyHook2 in src/win_delay_hook.c work?

/cc @piscisaureus<https://github.com/piscisaureus>

-

**Comment by piscisaureus** [comment]
No objections to const-ification from me.

**Comment by bnoordhuis** [comment]
https://ci.nodejs.org/job/node-test-commit-windows/975/ <- quick test

**Comment by bnoordhuis** [comment]
Okay, it clearly doesn't work with older VS versions.  I'm not going to look into it deeper but I'll be happy to review patches.

**Comment by piscisaureus** [comment]
@orangemocha you have time to dig into this?

**Comment by orangemocha** [comment]
I am investigating...

**Comment by orangemocha** [comment]
https://github.com/nodejs/node-gyp/pull/952

**Comment by RanzQ** [comment]
Just installed the latest [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) and getting the same error with `node-gyp@3.4.0`.

**Comment by bnoordhuis** [comment]
@RanzQ Can you file a new issue and include the build log?

**Comment by RanzQ** [comment]
Sorry, this was a false alarm. I'm having some problems installing the 3.4.0. `npm list --global --depth=0` shows I've got 3.4.0 but I still have `3.3.1` in my global `node_modules`.

**Comment by bayssmekanique** [comment]
Use npm next: `npm install -g npm@next`

Fixes the problem on Win 10
