### ISSUE TITLE
The node-gyp compile error message is not helpful, could anyone take a look?

### ISSUE THREAD

**Issue by EdenZhao** [nodejs/node-gyp#954]
error c2240 cannot convert from 'v8::Value *' to 'v8:object *volatile'

the error points to ".node-gyp\4.4.5\include\node\v8.h(221)", so I have no idea what's goes wrong.

p.s. compiled on a windows machine.

**Comment by bnoordhuis** [comment]
That error suggests a bug in the module you're trying to compile.  You don't mention what module it is but I'd file a bug against that project.  Good luck.
