### ISSUE TITLE
Propose v3.3.2

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-gyp#956]
It's been a while, we should get the fixes in the wild.

Just doing this here to make sure there weren't any loose ends to clean up and that 3.3.2 would be the correct version.

cc @bnoordhuis / @orangemocha

**Comment by rvagg** [comment]
+1

* [[`f31482e226`](https://github.com/nodejs/node-gyp/commit/f31482e226)] - **win**: work around __pfnDliNotifyHook2 type change (Alexis Campailla) [#952](https://github.com/nodejs/node-gyp/pull/952)
* [[`3df8222fa5`](https://github.com/nodejs/node-gyp/commit/3df8222fa5)] - Allow for npmlog@3.x (Rebecca Turner) [#950](https://github.com/nodejs/node-gyp/pull/950)
* [[`a4fa07b390`](https://github.com/nodejs/node-gyp/commit/a4fa07b390)] - More verbose error on locating msbuild.exe failure. (Mateusz Jaworski) [#930](https://github.com/nodejs/node-gyp/pull/930)
* [[`4ee31329e0`](https://github.com/nodejs/node-gyp/commit/4ee31329e0)] - **doc**: add command options to README.md (Gibson Fahnestock) [#937](https://github.com/nodejs/node-gyp/pull/937)
* [[`c8c7ca86b9`](https://github.com/nodejs/node-gyp/commit/c8c7ca86b9)] - Add --silent option for zero output. (Gibson Fahnestock) [#937](https://github.com/nodejs/node-gyp/pull/937)
* [[`ac29d23a7c`](https://github.com/nodejs/node-gyp/commit/ac29d23a7c)] - Upgrade to glob@7.0.3. (Ben Noordhuis) [#943](https://github.com/nodejs/node-gyp/pull/943)
* [[`15fd56be3d`](https://github.com/nodejs/node-gyp/commit/15fd56be3d)] - Enable V8 deprecation warnings for native modules (Matt Loring) [#920](https://github.com/nodejs/node-gyp/pull/920)
* [[`7f1c1b960c`](https://github.com/nodejs/node-gyp/commit/7f1c1b960c)] - **gyp**: improvements for android generator (Robert Chiras) [#935](https://github.com/nodejs/node-gyp/pull/935)
* [[`088082766c`](https://github.com/nodejs/node-gyp/commit/088082766c)] - Update Windows install instructions (Sara Itani) [#867](https://github.com/nodejs/node-gyp/pull/867)
* [[`625c1515f9`](https://github.com/nodejs/node-gyp/commit/625c1515f9)] - **gyp**: inherit CC/CXX for CC/CXX.host (Johan Bergström) [#908](https://github.com/nodejs/node-gyp/pull/908)
* [[`3bcb1720e4`](https://github.com/nodejs/node-gyp/commit/3bcb1720e4)] - Add support for the Python launcher on Windows (Patrick Westerhoff) [#894](https://github.com/nodejs/node-gyp/pull/894

After this I reckon we should bump to v4 and get rid of the NVM env stuff.

**Comment by bnoordhuis** [comment]
I'd like to wait until #915 and #955 have landed.  It'd be nice if someone could review #915.

**Comment by orangemocha** [comment]
It looks like https://github.com/nodejs/node-gyp/pull/915 has landed, but https://github.com/nodejs/node-gyp/pull/955 is still pending.

I would like to point out that once VS 2015 Update 3 hits RTM (it's currently in RC), we are probably going to get a lot of bug reports because of https://github.com/nodejs/node-gyp/issues/949 (which is fixed by https://github.com/nodejs/node-gyp/commit/f31482e226).

This release (or at least https://github.com/nodejs/node-gyp/commit/f31482e226) will need to be propagated to all of Node release lines.

**Comment by rvagg** [comment]
v3.4.0 published, changelog @ https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md

**Comment by rvagg** [comment]
https://github.com/npm/npm/pull/13199 & https://github.com/npm/npm/pull/13200

**Comment by shiftkey** [comment]
Just a heads up - AppVeyor has made VS2015 Update 3 available on their default images, and with the use of Node v6.2.2 it is now encountering the issue logged in #949, causing anything which depends on node-gyp v3.3.1 (in my case, `keytar`) to fail with a compilation error.

> C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\shiftkey\Documents\GitHub\desktop\node_modules\keytar\build\keytar.vcxproj]

Are there any known workarounds to get up to `node-gyp` v3.4.0 while we wait for this new release to flow upstream?

**Comment by bnoordhuis** [comment]
@shiftkey Untested, but I would expect that you can `npm install node-gyp@3.4.0` as a build_script cmd in your appveyor.yml.

**Comment by shiftkey** [comment]
@bnoordhuis thanks for the suggestion, but sadly that doesn't seem to override the behaviour of `npm install`. Oh well.

**Comment by rvagg** [comment]
@shiftkey you're going to have to be patient for this process to work itself out. We have it going in to the next npm releases (already in npm@2 to be released next week, in the process of getting in to npm@3) and then after that it'll have to come across to node for inclusion in a new release. When it's in npm you should be able to manually upgrade npm to make it work and not have to wait for Node to upgrade it's npm but you'll have to keep an eye on npm/npm#13199 & npm/npm#13200.

**Comment by beat-at-hartwig** [comment]
@shiftkey As a workaround I can propose this:

1. Go to your folder where npm is installed, e.g.:
`C:\Programes Files\nodesjs\node_modules\npm`

2. Open: `package.json`

3. Dump entry for `node-gyp` in `bundleDependencies`

4. Bump version number to `3.4.0` for `node-gyp` in `dependencies`

5. Make a `npm i` in this directory to install `node-gyp@3.4.0` to fix the problem
