### ISSUE TITLE
 getting node-gyp rebuild errors when using nom install

### ISSUE THREAD

**Issue by carriema** [nodejs/node-gyp#957]
myrs-MacBook-Pro:Documents myr$ npm install ringpop
npm WARN package.json myr@1.0.0 No repository field.
npm WARN package.json myr@1.0.0 No README data
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
/
> farmhash@0.2.2 install /Users/myr/node_modules/ringpop/node_modules/farmhash
> node-gyp rebuild

  CXX(target) Release/obj.target/farmhash/src/upstream/farmhash.o
  CXX(target) Release/obj.target/farmhash/src/bindings.o
  SOLINK_MODULE(target) Release/farmhash.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/farmhash.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myr/.nvm/v0.10.32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/myr/.nvm/v0.10.32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/myr/node_modules/ringpop/node_modules/farmhash
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! farmhash@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the farmhash@0.2.2 install script.
npm ERR! This is most likely a problem with the farmhash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls farmhash
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/myr/.nvm/v0.10.32/bin/node" "/Users/myr/.nvm/v0.10.32/bin/npm" "install" "ringpop"
npm ERR! cwd /Users/myr/Documents
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by bnoordhuis** [comment]
That's not a node-gyp issue.  The `library not found for -lgcc_s.10.5` error is either a local issue (e.g. because you need to update your system) but it might also be caused by farmhash's build settings.  Try filing an issue with that project.
