### ISSUE TITLE
Consider gyp.js?

### ISSUE THREAD

**Issue by indutny** [nodejs/node-gyp#960]
Hello everyone!

We're working on https://github.com/indutny/gyp.js , which is a port of GYP to Node.js. I think the project is reaching the point when it could be actually used as an alternative "backend" for `node-gyp`.

What do you think about bundling it here under a flag to see how well it will work?

Thank you,
Fedor.

**Comment by Fishrock123** [comment]
> What do you think about bundling it here under a flag to see how well it will work?

I think that is an excellent starting point.

I suppose a flag would just change the child-process invocation to gyp.js?

Not sure I'm the best person to lead on this though, I'm pretty pre-occupied.

**Comment by indutny** [comment]
@Fishrock123 yep, the flag will just do this.

**Comment by indutny** [comment]
Though, important thing about `gyp.js` is that it may not work on older versions of node, because of extensive ES6 usage. Is this going to be a problem for us, or can we manage it through semver?

**Comment by Fishrock123** [comment]
@indutny  We might be able to transpile it back. Does it work on v4 or just v6?

**Comment by indutny** [comment]
Just v6 at the moment.

**Comment by pmed** [comment]
@indutny See PR: #962

**Comment by indutny** [comment]
@rvagg sorry, but I have feeling that we are not moving fast enough on this. Is there any way to expedite the review process? Should we invite more collaborators to this project?

**Comment by lazaridis-com** [comment]
@indutny , strange thing. Wondering why your work is not give more priority.

**Comment by prasannavl** [comment]
It's been quite a while. Any update on the state of things?

**Comment by refack** [comment]
I'll follow up on #962

**Comment by stalkerg** [comment]
Good news: https://chromium-review.googlesource.com/c/479691

**Comment by JamesMGreene** [comment]
@stalkerg: Hmm, maybe, but AFAICT, that:
 - was last updated in April,
 - has merge conflicts,
 - has not been reviewed, and
 - has not been merged.

😢

**Comment by stalkerg** [comment]
ah... but I hope this problem is will fix

**Comment by refack** [comment]
> Good news: https://chromium-review.googlesource.com/c/479691

@stalkerg thank you for bringing this to attention

**Comment by zixia** [comment]
+1

**Comment by Pomax** [comment]
It's been quite a while again, any update on the state of things? Removing the dependency on Python is *super valuable* for people who are JavaScript developers, not Python developers, especially for those of us who need, or like, to use Windows (which does not come with any version of Python, and so anyone who is told they need python will download whatever is the latest version of Python. And then node-gyp still doesn't work. In 2017 =)

**Comment by refack** [comment]
@Pomax it's just a matter of limited resources... If you want to try and follow up on the work that's been done, I'd be very happy to help.
Good starting point: https://github.com/nodejs/node-gyp/pull/1092

**Comment by ArmorDarks** [comment]
Won't it add dependencies on Ninja and C/C++ compilers, kinda making no difference, with C dependency instead of Python?

**Comment by piranna** [comment]
> Won't it add dependencies on Ninja and C/C++ compilers, kinda making no difference, with C dependency instead of Python?

In any case, you currently has C dependencies for natives modules, in fact it would be really difficult to erradicate them...

**Comment by gibfahn** [comment]
@ArmorDarks GYP/Ninja/Cmake etc. are meta-build systems, they just generate the right Makefiles for each platform. The C/C++ compilation still has to be done whatever system you use.

**Comment by rvagg** [comment]
closing this with much sadness, gyp.js would have been nice but we were never organised enough to pull it of and @indutny has moved on now from it. If someone wants to pick this up again and push forward then please open a fresh PR and let's talk.
