### ISSUE TITLE
Update minimatch to latest version

### ISSUE THREAD

**Issue by TDA** [nodejs/node-gyp#966]
From NSP, https://nodesecurity.io/advisories/118, we need to update minimatch. This is affecting a lot of repos upstream.
I am ready to put in a PR if you guys are ok with it :)

**Comment by rvagg** [comment]
fixed in #961

**Comment by TDA** [comment]
@rvagg Thank you, can you also publish it to npm with an updated version? :) Cuz the NSP warning is still displayed if I do an `npm i node-gyp`
