### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by kadir003** [nodejs/node-gyp#973]
PS C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\kadir\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\kadir\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\kadir\.node-gyp\6.2.2\include\node\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\kadir\.node-gyp\6.2.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\kadir\AppData\Roaming\npm\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\kadir\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\kadir\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\kadir\Desktop\Ehabu\core\rubix-bootstrap
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Does anyone can help with this?

**Comment by joaocgreis** [comment]
@kadir003 Hi! What exactly are you trying to do?

If you're trying to install https://github.com/callmez/rubix-bootstrap , then node-gyp is right, there is no binding.gyp there. Perhaps the instructions at https://www.npmjs.com/package/rubix-bootstrap/tutorial can help you. If your issue is with that package and not node-gyp specifically, opening an issue there is probably the best thing to do.

**Comment by ganeshghalame** [comment]
Getting same issue, while doing `npm install` its throwing error 

> Error: Cannot find module '/var/lib/jenkins/workspace/partner/master/node_modules/node-sass/node_modules/pangyp/bin/node-gyp

I installed `node-gyp` using command ` sudo npm install -g node-gyp` its success but again getting the same error, so as per the solution [StackOverflow](http://stackoverflow.com/questions/17967546/common-gypi-not-found-error-in-node-js) I tried `node-gyp rebuild`

`ubuntu@ip-172-31-63-54:~$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.5.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.5.0/node-v6.5.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.5.0/node-v6.5.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.5.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.5.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/6.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/6.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/ubuntu) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ubuntu
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v `

**Comment by jongha** [comment]
I have a same issue.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@0.10.46 | linux | ia32
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/jongha/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.46/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.46',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/jongha',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /root/jongha) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-642.3.1.el6.i686
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/jongha
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by ChristianRich** [comment]
+1

**Comment by pringlized** [comment]
+1

**Comment by bnoordhuis** [comment]
Closing to discourage further contextless +1 comments.  OP never replied so I'll assume it's working for them.  If you need more help, search the issue tracker for similar reports.
