### ISSUE TITLE
{lamb} if not defined npm_config_node_gyp

### ISSUE THREAD

**Issue by itxuye** [nodejs/node-gyp#974]
I'm confused ~~~In windows ，i have install gyp and vs tools .But :

{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  validation.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot ifyHook2': redefinition; different type modifiers [D:\react_demo\AwesomeProject\node_modules\utf-8-validate\build\valid ation.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\react_demo\AwesomeProject\node_modules\utf-8-validate
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
AwesomeProject@0.0.1 D:\react_demo\AwesomeProject
`-- react@15.2.0

**Comment by bnoordhuis** [comment]
Fixed in node-gyp@3.4.0.  Try installing npm@next, it bundles node-gyp@3.4.0.

**Comment by itxuye** [comment]
Now it's 3.4.0. The same error~~~

{lamb} if not defined npm_config_node_gyp (node "C:\ProgramData\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\ProgramData\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: 'C:\ProgramData\npm\node_modules\npm\node_modules\node-gyp\src\win_d elay_load_hook.cc': No such file or directory [D:\react_demo\AwesomeProject\node_modules\bufferutil\build\bufferutil.vc xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ProgramData\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\react_demo\AwesomeProject\node_modules\bufferutil
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install D:\react_demo\AwesomeProject\node_modules\utf-8-validate
> node-gyp rebuild

@bnoordhuis

**Comment by bnoordhuis** [comment]
It's not the same error because now it's saying it can't find win_delay_load_hook.cc.  That file was renamed in 3.4.0 (it used to have a .c extension) so that probably means C:\ProgramData\npm\node_modules\npm\node_modules\node-gyp is still node-gyp@3.3.4.

**Comment by joaocgreis** [comment]
@itxuye if you are you still having this problem, can you try to use `npm@2.15.9` (LTS) or `npm@3.10.5` (master)? Install with `npm install -g npm@2.15.9` or `npm install -g npm@3.10.5`.

If you are updating from `npm@3.10.4`, please remove the old installation first with `rd /s /q %APPDATA%\npm`.

**Comment by itxuye** [comment]
@joaocgreis Thanks. I have solved the problem.I update the npm@next.But the new node-gyp is not in the node_modules path and in the npm path.So that I move the newest node-gyp into node_modules.  
QAQ
