### ISSUE TITLE
some problmes about node-gyp  rebuild on windows

### ISSUE THREAD

**Issue by siduoge** [nodejs/node-gyp#981]
the error is always **__pfnDliNotifyHook2 redefinition,** but I have do all the reqirements. The python I have installed correctly ,the vs2015 and .net4.5.1 are all installed in my computer . I just dont know where is wrong?

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\JCS>e:

E:>cd E:\Users\JCS\Desktop\paikankan\work\test_1

E:\Users\JCS\Desktop\paikankan\work\test_1>npm install ffi

ref@1.3.2 install E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref
node-gyp rebuild
E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref>if not defined npm_c
onfig_node_gyp (node "C:\Users\JCS\AppData\Roaming\npm\node_modules\npm\bin\node
-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node ""
rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
binding.cc
win_delay_load_hook.c
**C:\Users\JCS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win
_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; diffe
rent type modifiers [E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\re
f\build\binding.vcxproj]**
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe fail
ed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\JCS\AppData\Roaming\npm\node
_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "J:\tools\nodejs\node.exe" "C:\Users\JCS\AppData\Roaming
\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
application-name@0.0.1 E:\Users\JCS\Desktop\paikankan\work\test_1
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "J:\tools\nodejs\node.exe" "C:\Users\JCS\AppData\Roaming\n
pm\node_modules\npm\bin\npm-cli.js" "install" "ffi"
npm ERR! node v6.2.2
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.2 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! E:\Users\JCS\Desktop\paikankan\work\test_1\npm-debug.log
npm ERR! code 1

**Comment by siduoge** [comment]
I have upgrade the node.js and npm ,but all of them are no use

**Comment by bnoordhuis** [comment]
Upgrade to node-gyp@3.4.0.  Closing as duplicate, please search the list of issues first next time.

**Comment by shihrer** [comment]
@bnoordhuis I'm on node-gyp@3.4.0 and having the same issue.

**Comment by rvagg** [comment]
it's the version of node-gyp inside npm that matters here unless you are using the `node-gyp` command directly, e.g. `node-gyp rebuild` on a package that has native code. You could either manually update node-gyp in your npm installation (under node_modules/ in the directory that npm is installed in), wait for a newer npm with node-gyp@3.4.0 (was due out some time this week, I haven't kept track but I think it'll be 3.10.4?), or even use the latest npm@2 which has the fix in it already.

**Comment by shihrer** [comment]
Thanks @rvagg .  I read through the other issues but somehow that didn't click with me.  I'll try manually updating it.

**Comment by ramazanpolat** [comment]
Hi. This solved my problem.
`nvm install v6.9.1 32`
`nvm use v6.9.1`
`npm install --global --production windows-build-tools`

**Comment by granteagon** [comment]
I'm on node 6.11.1, node-gyp 3.6.2.  I can't build the npm package @ng-select/ng-select.  

Here's what happens when I install:
```
$ npm i -S @ng-select/ng-select

> integer@1.0.1 install C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer
> node tools/install


C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  integer.cpp
  win_delay_load_hook.cc
..\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\integer.vcxproj]
..\src\integer.cpp(376): warning C4244: '=': conversion from 'uint64_t' to 'unsigned char', possible loss of data [C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\integer.vcxproj]
     Creating library C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\Release\integer.lib and object C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\Release\integer.exp
  Generating code
  Finished generating code
  integer.vcxproj -> C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\Release\\integer.node
  integer.vcxproj -> C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\node_modules\integer\build\Release\integer.pdb (Full PDB)

> better-sqlite3@4.0.3 install C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3
> node deps/install

==> cwd: C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3
==> C:\Users\me\myproject\node_modules\lzz-gyp\lzz-compiled\windows.exe -hx hpp -sx cpp -k BETTER_SQLITE3 -d -hl -sl -e ./src/better_sqlite3.lzz
==> cwd: C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3
==> node-gyp rebuild

C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\me\myproject\node_modules\inspectpack\node_modules\better-sqlite3\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\me\myproject\node_modules\inspectpack\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Error: exit code 1
    at ChildProcess.<anonymous> (C:\Users\me\myproject\node_modules\lzz-gyp\lib\exec.js:19:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
CaseManagement@ C:\Users\me\myproject
+-- @ng-select/ng-select@0.14.2
`-- UNMET PEER DEPENDENCY angular@1.6.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\me\myproject\node_modules\better-sqlite3\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\me\myproject\node_modules\integer\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\me\myproject\node_modules\better-sqlite3\node_modules\integer\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\me\myproject\node_modules\inspectpack\node_modules\integer\package.json'
npm WARN angular-pageslide-directive@2.1.4 requires a peer of angular@1.5.x but none was installed.
npm WARN CaseManagement@ No description
npm WARN CaseManagement@ No repository field.
npm WARN CaseManagement@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: better-sqlite3@4.0.3 (node_modules\inspectpack\node_modules\better-sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: better-sqlite3@4.0.3 install: `node deps/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Thanks!
