### ISSUE TITLE
node-gyp build error 

### ISSUE THREAD

**Issue by bzhong2** [nodejs/node-gyp#984]
When I tried to run node-gyp build, It says cannot open source file:‘。。、src\binding.cc’: no such file or directory; I checked there is no binding.cc in \node-gyp build\src\. I checked gyp configure too, there is a warning which says missing input files \src\binding.cc. How can I fix the error? Thanks a lot!!

**Comment by bzhong2** [comment]
I am using Windows 8.1 x64.

**Comment by bnoordhuis** [comment]
That's a problem with the module you're trying to build, not node-gyp.  Please report it to the maintainers of the module.
