### ISSUE TITLE
Access(Make use of) node-dir in binding.gyp.

### ISSUE THREAD

**Issue by royalpinto** [nodejs/node-gyp#986]
Hi,

I would like to access or mention a directory from `node-dir` within the `include_dirs` section of `binding.gyp`.
Something like this:
```
"include_dirs": [
    "<node-dir>/deps/cares/include"
],
```
Is there any variable I can use to get the node directory (something like `node-dir`) ?
For now in my project https://github.com/royalpinto/node-cares, I have copied the entires `cares` dir from `node` source, but the problem is, different versions of `node` uses different versions of `cares` source. Hence copied `cares` source is not working on all versions of `node`.

Thanks.

**Comment by bnoordhuis** [comment]
It looks like you are assuming that add-ons are compiled against a source tarball but that isn't always the case.

For example, it's possible to use node-gyp with the subset of headers that `make install` installs.  Taking out a dependency on anything under deps/ would fail when built like that.

**Comment by royalpinto** [comment]
Thanks for the reply.

Here is my scenario:
I have a project (https://github.com/royalpinto/node-cares) which makes use of `c-ares` lib and is similar to default `node` `dns` module but with additional features like creating multiple instances of `Resolver`s with various configs.
This project requires `c-ares` source code, which I have currently copied from `node` version `0.12.0` and kept under `deps/` dir within my project and I am including in my `binding.gyp` like below:
```
"include_dirs": [
    "<!(node -e \"require('nan')\")",
    "deps/cares/include", # This is just copied from node js project and no modification have been done.
    "deps/cares/src", # This is just copied from node js project and no modification have been done.
],
"sources": [
    "src/cares_wrap.cc"
],
"dependencies": [ "deps/cares/cares.gyp:cares" ],
```

The problem here is that, I have to maintain `c-ares` lib up to date. I would like to re use the source code available under `node` directory rather than copying it and maintaining separately. I can see that `uv` and `v8` directories are getting added dynamically from `node` directory. I was wondering if there is any way I can add `cares` dir as well.

Here is a sample output I get in `.target.mk` file:
```
INCS_Release := \
-I/Users/lpinto/.node-gyp/4.3.0/include/node \
-I/Users/lpinto/.node-gyp/4.3.0/src \
-I/Users/lpinto/.node-gyp/4.3.0/deps/uv/include \
-I/Users/lpinto/.node-gyp/4.3.0/deps/v8/include \
-I$(srcdir)/node_modules/nan \
-I$(srcdir)/deps/cares/include \
-I$(srcdir)/deps/cares/src
```
In the above output `uv` and `v8` are added dynamically, is there any way I can make use of other deps(cares) as well ?

Thanks

**Comment by bnoordhuis** [comment]
You can't do that reliably because it assumes building against a source tarball.  When building against e.g. a headers-only tarball from http://nodejs.org/dist/, that would fail badly.

**Comment by royalpinto** [comment]
Okay got it. But If I am not wrong, when project is made to build using `node-gyp` (`node-gyp configure --target=<>`) it downloads the `node` `source code` from the `nodejs` official repo and keeps in the .node-gyp directory. That way I always get the source code (headers and the code) which I can use in my project. It wouldn't be headers only tarball. Correct me if I am wrong here.

Thanks.

**Comment by rvagg** [comment]
@royalpinto for maybe a year now node-gyp has been downloading the headers tarball when it can rather than the full source. This is reliably so for v4+ but also for more recent v0.10 and v0.12 releases. Unless you're using an old version of npm/node-gyp or an old version of Node then you _shouldn't_ be getting the full source tarball. There are a couple of caveats to that, however, mostly involving nvm, but we'll be sorting that our in node-gyp v4.

**Comment by royalpinto** [comment]
Oh okay, did not know about it. probably I am using a older version.
Thanks a lot 👍
