### ISSUE TITLE
node-gyp rebuild failing on Mac OS X 10.11.5 (15F34)

### ISSUE THREAD

**Issue by gthn** [nodejs/node-gyp#994]
Every time I try to `npm install` the package wolfram-alpha (which has a libxmljs dependency) I get an error. It seems to be a problem with `make`, but I'm not sure. I've tried updating Python to a compatible version 2.7.12, npm 6.2.2, but to no avail. Yes, I have installed the Xcode Command Line tools, but this has still not helped. Here are my error logs:

![image](https://cloud.githubusercontent.com/assets/11558805/16853547/ac1b77ee-4a04-11e6-9595-e835d1414eb0.png)

Do you have any idea what I can do to fix this?

Mac OS X 10.11.5, Node version 6.2.2, npm version 3.9.5, Python version 2.7.12.

**Comment by bnoordhuis** [comment]
wolfram-alpha probably needs to update its libxmljs dependency, it's not using the latest version.

I'm going to close the issue because it's not in any way related to node-gyp.  Good luck!
