### ISSUE TITLE
Is there a way to check within the gyp file which Node embedder the library is building against?

### ISSUE THREAD

**Issue by murgatroid99** [nodejs/node-gyp#995]
If I want to building my library for electron or nw.js, for example, is there any way to check in binding.gyp whether I am building for one of those or for standard Node?

**Comment by bnoordhuis** [comment]
I think the answer is 'not easily'.

In node.js v6.3.0 you can check the 'node_module_version' variable but that won't help with older versions and it's also not 100% reliable.  Electron made at least one release with the same module version as upstream node.js even though it's not source compatible.

You could shell out to node from your binding.gyp and check `process.versions` but the node binary used for building isn't necessarily the same as the target runtime.
