### ISSUE TITLE
Install fails on Yosemite

### ISSUE THREAD

**Issue by abhi18av** [nodejs/node-gyp#998]
Hi!

The issue is that I can't install it in my system. I've definitely explored the node-gyp / python2 suggestion but this still doesn't work.

Any suggestions, how I can solve it.

`apm 1.9.2 npm 2.13.3 node 0.10.40 python 3.5.1 git 2.8.1`

`node-gyp --python /usr/bin/python`

**Comment by bnoordhuis** [comment]
Can you be more specific about what "install fails" means?  Do you get errors?

You mention python 3.5.1 - that's not going to work, you _must_ use python 2.7.

**Comment by abhi18av** [comment]
Yes, I understand that part. 

The second line of code pints to the pre-installed python2.7 version.

Man, I really need to have those packages for a coherent environment. I appreciate your help)
